### ISSUE TITLE
Test for core polarization potential needed

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1005]
There is one case for this (GeH4) from the very old test system (circa 2007).  The test is gaussian based, so it is likely that with some small changes to the input file, it could be made to run.

The original inputs and outputs for this case are attached here, in case anyone wants to take a minute to try to get it to run.  See [GeH4_GTO_PP_CPP_2008.zip](https://github.com/QMCPACK/qmcpack/files/2293755/GeH4_GTO_PP_CPP_2008.zip).

**Comment by prckent** [comment]
It would be helpful to hear from anyone interested in using a CPP

**Comment by jtkrogel** [comment]
Feature no longer exists.
