### ISSUE TITLE
qmcfinitesize tool needs to be in develop

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1007]
The qmcfinitesize tool appears in the manual, but it is not in the main develop branch.  

It is the target tool to consume the output of the SkAllEstimator and produce accurate finite size corrections a la Holzmann et al., PRB 94 035126 (2016), https://doi.org/10.1103/PhysRevB.94.035126.

**Comment by prckent** [comment]
This would be useful to have for many people.

Is it possible to PR into the repo? @rcclay @Paul-St-Young
