### ISSUE TITLE
Linking HDF5 library statically

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1018]
Cray gives me enough headache changing hdf5 library silently. Do we have a way to request cmake linking hdf5 statically even the build uses dynamically?

**Comment by prckent** [comment]
Does QMC_BUILD_STATIC work on your Cray?

**Comment by ye-luo** [comment]
QMC_BUILD_STATIC requires me to build a static libxml2.
Also on Titan CUDA requires dynamical linking.
So I'm looking for a way linking dynamically overall but hdf5 statically.
I found HDF5_USE_STATIC_LIBRARIES in our cmake and I'm trying to fix it.

**Comment by ye-luo** [comment]
No luck with HDF5_USE_STATIC_LIBRARIES. Cray PE is hiding everything in the wrapper and cmake doesn't pick up the static library. If told to do dynamic linking, Cray PE doesn't allow fine controlling of the hdf5 libs.
