### ISSUE TITLE
Add CMake installation for QMCPACK and NEXUS

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1020]
Based on the request in #1017 , we need to arrange "make install" to work for both QMCPACK and NEXUS. CMake has many options to support this.

I suggest we just focus on the default real cpu build. In later versions we can handle Quantum Espresso, ideally after our converter is in QE, and then complex.

What needs to be installed?

build/bin/*
nexus/executables/*
nexus/library

Although NEXUS is not a python package, there must be some standards to follow.

**Comment by jtkrogel** [comment]
Happy to do the Nexus part, though not sure what is desired in the "make install" context.

**Comment by naromero77** [comment]
For reference, this is what I do in the Spack package for install.
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/qmcpack/package.py#L250

I install all binaries in bin, I copy over the entire Nexus directory, and I "install" the manual.

**Comment by naromero77** [comment]
For Python, there are usually two options:
1. install in "site-packages" subdirectory of the Python distribution
OR
2. Add the appropriate directories to PYTHONPATH environment variable.

**Comment by jtkrogel** [comment]
Thanks Nick.  I've generally taken the second option to "install" Nexus.

**Comment by prckent** [comment]
Regarding NEXUS perhaps copying to $INSTALL_DIR/nexus/...  will suffice. It would be good if qmca would work out of the box.

**Comment by prckent** [comment]
(We'll have to discuss who can handle the QMCPACK side. @PDoakORNL ?)

**Comment by jtkrogel** [comment]
qmca is fully standalone (no install required).  All that is needed is python, numpy, and (optionally) matplotlib.

**Comment by markdewing** [comment]
I can work on the QMCPACK side, unless @PDoakORNL is already working on it.

**Comment by markdewing** [comment]
The bin directory contains `qmcpack` and `convert4qmc`, which are definitely used and should be installed.
But what about these others?  Are they used? Should they be installed?
* getSupercell
* extract-eshdf-kvectors
* checkAffinity

**Comment by ye-luo** [comment]
We may add or remove files over time. So copy bin/* over.

**Comment by markdewing** [comment]
Should we adopt some sort of standard for the names of the executables? (add qmc_ prefix, or at least have qmc in the name, as in convert4qmc)  In the case where someone installs into a common directory (like /usr/local/bin), so the qmcpack-derived executables can be easily identified.

**Comment by prckent** [comment]
Good suggestion. At least qmc in the name.

**Comment by markdewing** [comment]
I can get some changes in - rename (#1208)  and install *should* be straightforward.

**Comment by prckent** [comment]
A prefix for nexus related utilities needs to be chosen carefully. e.g. nx is NoMachine's technology.

**Comment by jtkrogel** [comment]
I'll have to think more about that.

**Comment by jtkrogel** [comment]
For the QMCPACK related ones, is this desired?
* qfit -> qmc-fit
* qstat -> qmc-stat
* qtest -> qmc-test
* qmca -> qmca

**Comment by jtkrogel** [comment]
On the Nexus side, is "nxs-" or "nexus-" better for a prefix?  Googling seems to point toward "nxs-" as a better route, though this is also a file extension.

**Comment by prckent** [comment]
Should I move the NEXUS part of this to v3.7.0 or is something in the works?

**Comment by jtkrogel** [comment]
Looking into it.  I think installing the Nexus executables this way (a la #1215) should be straightforward.

Less sure if there is a good way to modify the PYTHONPATH environment variable for the user from within CMake to complete the install.

**Comment by prckent** [comment]
Closed by #1215 and #1242
