### ISSUE TITLE
AFQMC tests using nnodes are failing

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1040]
The current tests specifying nnodes on the Propagator element are failing.  The inputted xml section looks like this:
```
  <Propagator name="prop0" info="info0">
    <parameter name="nnodes">2</parameter>
  </Propagator>
```
@mmorale3, is this expected to work, or is this a superseded feature?  If so I will disable these tests.

**Comment by fdmalone** [comment]
Tests are old.
