### ISSUE TITLE
Remove and/or rename QMC_BUILD_LEVEL

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#1051]
The QMC_BUILD_LEVEL flag could be removed in most cases, and renamed to its actual function in other cases.

The default value is 3.
The only current use I'm aware of is to build the sandbox apps (level 5).  This could use a flag named something like QMC_BUILD_SANDBOX_ONLY.
Does anyone use any of the other levels?

Most of the uses in the code are checking whether it is greater than 1 or 2, so true by default.
A few places check that it is less than 5, and these could be replaced by checking the sandbox define.

**Comment by jtkrogel** [comment]
I would vote for removal if possible since it is rather opaque and not very useful.

**Comment by ye-luo** [comment]
As long as I can build Sandbox, any cleanup is appreciated.
