### ISSUE TITLE
GPU and OPENMP cannot work together for DMC

### ISSUE THREAD

**Issue by yaoyi92** [QMCPACK/qmcpack#1053]
the code crash when using OPENMP with GPU for DMC. This doesn't happen for VMC. 

details here.
https://groups.google.com/forum/#!topic/qmcpack/9rELWZgNUOo

**Comment by prckent** [comment]
Thanks for reporting this. Please can you attach the pseudopotential files so that we can attempt an exact reproduction?

**Comment by yaoyi92** [comment]
Sorry for the confusion. I have them pasted in the google group.
They were pseudopotential files I took from maybe an older version of qmcpack.
https://groups.google.com/forum/#!topic/qmcpack/9rELWZgNUOo

**Comment by yaoyi92** [comment]
I take it back. 
I think I got them from CASINO website and converted them.

**Comment by yaoyi92** [comment]
This is also Volta-V100 related (works fine with GTX1080), the same as this issue.
https://github.com/QMCPACK/qmcpack/issues/1054

**Comment by prckent** [comment]
Thanks for the updates. While our existing tests are passing, it does indeed seem that something is up with some combinations/parts of QMCPACK, certain GPUs, certain inputs.

**Comment by ye-luo** [comment]
We ran legacy CUDA with OpenMP threads by default. It seems OK right now. Open a new issue if needed.
