### ISSUE TITLE
GPU result has number of walkers dependency and doesn't match CPU result

### ISSUE THREAD

**Issue by yaoyi92** [QMCPACK/qmcpack#1054]
Details in the post here. 
https://groups.google.com/forum/#!topic/qmcpack/eOE1eIXAgaE

Not 100% sure whether it is a problem for my build. ctest results here in the post
https://groups.google.com/forum/#!topic/qmcpack/1QzNQoceNHs

![image](https://user-images.githubusercontent.com/6993167/45259435-f0239780-b39a-11e8-95ce-9d80eab075ee.png)

**Comment by yaoyi92** [comment]
This seems to be a Volta V100 specific issue. I don't have this problem compiling and running the same simulation on GTX1080.

Need help from someone with experience of Volta V100.

**Comment by jtkrogel** [comment]
Something does seem to be up with Volta: 
https://cdash.qmcpack.org/CDash/index.php?project=QMCPACK&date=2018-09-07.  

Compare "Volta-GCC-CUDA-Release" with "GCC-CUDA-Release".

**Comment by prckent** [comment]
(GCC-CUDA-Release runs on a Kepler. This is printed on one on the ~third line of output.)

**Comment by prckent** [comment]
To keep this updated: the current belief is that this has hit some kind of edge case (bug) or is a newly surfaced problem on Volta or with recent CUDAs (bug). For whatever reason, our current tests don't show the same problem.  @PDoakORNL will try to chase down.

**Comment by ye-luo** [comment]
Some recent fixes in legacy CUDA probably addressed this issue. Open a new issue if needed.
