### ISSUE TITLE
Tests need categorization

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1055]
Currently many tests are failing, but for various reasons (broken feature, SoA incompatibility, poorly constructed test).  There is a need to separate "should pass" from "known to fail" tests so that new breakages can be caught and also so that users can test their builds against what is known to work.

Recommend adding two prefixes to the names of existing and future tests:
- **deteriministic**: current unit tests and future very short deterministic tests.  These must pass under any circumstance on any architecture.
- **unstable**: all tests that currently consistently or intermittently fail.  The unstable prefix will be applied separately per build type (AoS real, SoA complex, CUDA real, etc) since this reflects the current state of affairs.

Need to separate tests into separate dashboards on CDash:
- **deterministic**: "ctest -R deterministic", run nightly (and for CI?)
- **short**: "ctest -R short -E unstable", run nightly
- **long**: "ctest -R long -E unstable", run weekly
- **unstable**: "ctest -R unstable", run nightly?

In addition to the unstable dashboard, unstable tests should be tracked in aggregate by type (via GitHub issues) to gauge progress toward development goals (e.g. the SoA transition, real/complex compatibility, desired CUDA features, etc) vs. known breakages or intermittently failing tests.

Tasks:
- [x] Add deterministic prefix to existing unit tests
- [ ] Add unstable prefix to currently identified failing tests
- [ ] Iterate over nightly/weekly tests until all failing tests are identified and labeled

- [x] Add Deterministic build group
- [x] Add Short build group
- [x] Add Long build group
- [x] Add Unstable build group
- [ ] Modify oxygen test scripts to use new build groups and test categorization
- [ ] Modify bora test scripts to use new build groups and test categorization
- [ ] Modify hyperion test scripts to use new build groups and test categorization
- [ ] Modify ceta test scripts to use new build groups and test categorization

See #1062 for an overarching view of the testing problem and links to its other aspects.  Also see #704 for discussion relating to deterministic tests.

**Comment by jtkrogel** [comment]
I can do the categorization/labeling part.  Would be great if someone else could pick up the dashboard (CDash display) part from there.

**Comment by ye-luo** [comment]
Let us also regularize the naming of tests.
short/long-stable/unstable/determinstic-system-method-WF-estimator?

**Comment by jtkrogel** [comment]
[unstable-]short/long/deterministic-system-method-WF[-estimator]-#mpi-#omp

Perhaps this is a separate task, though.

**Comment by prckent** [comment]
Dashboard: After some reading, it looks like we can setup and use "build groups" https://public.kitware.com/Wiki/CDash:Administration#Build_Groups and a single dashboard. We can add an argument to the ctest script to specify the group. Classifying and renaming needs to occur first.

**Comment by prckent** [comment]
I would prefer to lead with the flavour of test, so classifying could be "just" a matter of adding prefixes:
{deterministic,unstable}-{short,long,unit,converter,...}... {+remainder of current name}

**Comment by ye-luo** [comment]
@prckent I used this feature by changing the CTEST_DASHBOARD to Experimental in ctest_script.cmake. But this time it is better to go through command line option and add more groups.

**Comment by prckent** [comment]
Note that "The unstable prefix will be applied separately per build type (AoS real, SoA complex, CUDA real, etc) since this reflects the current state of affairs." is something we don't do currently so is a little extra work.

**Comment by ye-luo** [comment]
@prckent This will be many if else in the cmake. It is more of incompatible than unstable.

**Comment by jtkrogel** [comment]
The lists will be formed initially from the all hands slides I made, corresponding to the issues: #1058, #1057, #1056, #1059, and #861.

**Comment by jtkrogel** [comment]
@prckent do the test names need to be changed to this capitalization, or do the build groups check against the uncapitalized names?

**Comment by prckent** [comment]
The test names do not need to be updated.

ctest scripts should use the build group (CTEST_DASHBOARD) with the capitalization given. The dashboard does not care about how the tests are actually named, and simply categorizes them under the given build group. ctest will likely be invoked multiple times to handle the different build groups.

**Comment by markdewing** [comment]
ctest labels could also be used to categorize the tests, then -L/-LE can be used to include/exclude certain categories of tests.    The use of labels would make it less dependent on the test naming scheme, and less likely to inadvertently pick up a test name with the regular expression.
Although it is helpful to have the category in the test name when looking at the tests.

**Comment by jtkrogel** [comment]
@prckent posted a way to view test failing % over time (a month) for all tests in a group on issue #1057.

Viewing things this way really makes me want to add build variants to the test names (e.g. cpu/gpu, aos/soa, real/complex, mixed/full) to get a clearer picture.

Following this, @ye-luo suggested using more build groups to reveal this kind of separation.  This could help us both track down problems and keep track of "red" areas much as in the related unstable categorization issues.  Of course, this does add a lot more groups.

Thoughts?

**Comment by jtkrogel** [comment]
If we do go this way, I would probably settle for only a four-fold increase in the number of groups: aos-cpu, aos-gpu, soa-cpu, soa-gpu (times deterministic/short/long/unstable).

**Comment by prckent** [comment]
In the link I posted you can click on a named test to see the reporting builds, e.g. https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-NiO_a4_e48_pp-vmc_sdj3-1-16&date=2018-09-11 makes it easy to see that J3 is not supported on GPU but runs elsewhere are fine. If the tests were named by build type ("dmc_j3_soa_cuda"), then this would have to be done by eye.  I suggest we gain some experience with the build groups first.

**Comment by jtkrogel** [comment]
Either way.  Assigning builds (e.g. GCC-CUDA-Release) to these build groups could speed up the process of determining the list of unstable tests for each build type (task 3 at the top).

**Comment by prckent** [comment]
I'll tack the unit test rename so that we can work on the dashboard and script updated.

**Comment by prckent** [comment]
Suggestion: we use ctest labels to indicate whether functionality is supported on not. We will therefore have whether a feature is implemented/supposed to work encoded in the cmakelists.txts and will be able to do things like "ctest -R short -LE unsupported" to run all the short tests that are not labeled as unsupported.
