### ISSUE TITLE
rename UtilityFunctions.h to  FairDivide.h needed

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1090]
To better reflect its contents.
 src/Utilities/UtilityFunctions.h

adjust accordingly
#ifndef OHMMS_UTILITYFUNCTIONS_H
#define OHMMS_UTILITYFUNCTIONS_H

**Comment by jtkrogel** [comment]
Sure this is the right name?  Partition function has a particular meaning in statistical mechanics.

**Comment by ye-luo** [comment]
Call it FairDivideFunctions.h

**Comment by prckent** [comment]
FairDivide.h . Remove the OHMMS_. These are functions that we will want to keep long term unless e.g. Boost has equivalents.
