### ISSUE TITLE
Relocation of scripts from utils to tests/scripts needed

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1121]
The following scripts currently reside in the utils directory, but are actually part of the testing system:  
- [x] clean_and_link_h5.sh
- [x] test_import.py

These should be relocated to tests/scripts with the rest of the testing system scripts.  A few paths in CMake files will need updating.

**Comment by ye-luo** [comment]
I will take care of clean_and_link_h5.sh
