### ISSUE TITLE
Improved support for ctest test tracks

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1122]
Current support for multiple test tracks (noted in #1098) requires a hack due to my limited ctest understanding &/or ctest documentation/implementation issues. https://github.com/TriBITSPub/TriBITS/issues/189 and https://cmake.org/cmake/help/latest/command/ctest_start.html suggests that modifying the CTEST_START call might work.

**Comment by ye-luo** [comment]
It seems that track is a very useful feature for since 3.12.
