### ISSUE TITLE
Code may proceed or crash when Jastrow species do not match particleset groups.  Abort instead.

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#113]
Using e.g. particleset groups Ni1 and Ni2 but Jastrow labels eNi (J1 with elementType="Ni") and/or uuNi (J3 with ispecies="Ni") are incompatible.

Currently the code simply ignores the discrepancy, with the result that the J1 terms are not read in while the J3 ones still are.  The runtime behavior thereafter depends on the build environment: on Eos at OLCF the code proceeds to run to completion, while on Titan builds somewhere after SVN revision 7044 crash with a "double free or corruption" error in eeI_JastrowBuilder::putkids().

Behaviour should be changed to perform a controlled abort if Jastrow labels do not correspond to any particleset species group.

**Comment by ye-luo** [comment]
Please attach your output file.

**Comment by ye-luo** [comment]
Probably we need to add some guards at the builder level.

**Comment by prckent** [comment]
Agree, proper error handling with an informative message needed here.  Use of out of date converters can generate this problem.

#36 is not so different.

**Comment by jtkrogel** [comment]
Resolved by #1244.  Closing.
