### ISSUE TITLE
Manual looks strange in Listing

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1167]
Comparing https://docs.qmcpack.org/qmcpack_manual.pdf and https://docs.qmcpack.org/qmcpack_manual_v3.5.0.pdf

**Comment by prckent** [comment]
Please suggest some page numbers we should look at.

**Comment by ye-luo** [comment]
section 8.2.1 page 61 the XML input block.

**Comment by prckent** [comment]
I get the same less good formatting when I build the PDF myself, so we can rule out some quirk in the automatic PDF production.

Perhaps a change made while the HTML output was being enabled? The packages and settings used were simplified to enable this.

**Comment by PDoakORNL** [comment]
I can fix this Monday.  I can tweak the formatting of XML independently

**Comment by ye-luo** [comment]
It is not on the automatic generation side. I noticed it when I was working on the manual on my desktop. Some commits between 3.5 and current introduce the change.

**Comment by prckent** [comment]
Run locally, can confirm the PDF and HTML are improved. The improved PDF should be visible on docs.qmcpack.org around 5pm EST.
