### ISSUE TITLE
GAMESS inputs not included with tests

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#117]
The LiH all electron, pp, and the H4 all electron case should have the inputs for the source quantum chemistry code. At least one set of GAMESS inputs is needed. For splines/plane waves we include many Quantum Espresso inputs.

ls -R tests/molecules/
H4_ae		LiH_dimer_ae	LiH_dimer_pp

tests/molecules//H4_ae:
H4.ptcl.xml		opt-ref			optm-adaptive.xml
H4.wfs.xml		optm-OneShiftOnly.xml	optm-linear.xml

tests/molecules//H4_ae/opt-ref:
H4.s000.scalar.dat	H4.s005.scalar.dat	H4.s010.scalar.dat	H4.s015.opt.xml
H4.s001.scalar.dat	H4.s006.scalar.dat	H4.s011.scalar.dat	H4.s015.scalar.dat
H4.s002.scalar.dat	H4.s007.scalar.dat	H4.s012.scalar.dat	H4.s016.opt.xml
H4.s003.scalar.dat	H4.s008.scalar.dat	H4.s013.scalar.dat	H4.s016.scalar.dat
H4.s004.scalar.dat	H4.s009.scalar.dat	H4.s014.scalar.dat

tests/molecules//LiH_dimer_ae:
vmc_hf_noj.in.xml		vmc_hf_noj_nodrift.in.xml

tests/molecules//LiH_dimer_pp:
H.BFD.xml		Li.BFD.xml		vmc_hf_noj.in.xml

**Comment by ye-luo** [comment]
@chrislzhao Could you please add the input file from which you constructed H4_ae wavefunction?

**Comment by ye-luo** [comment]
@chrislzhao Thank you lot.

**Comment by prckent** [comment]
LiH inputs still needed
