### ISSUE TITLE
short-H4-opt-OneShiftOnly-1-16 failing since Nov 20

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1175]
Nov 19 to 20 night
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2018-11-20&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=short-H4-opt-OneShiftOnly-1-16
Nov 20 to 21 night
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2018-11-21&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=short-H4-opt-OneShiftOnly-1-16

The problem seems from #1163, The diamond solid optimization was fine. short-H4-opt-OneShiftOnly-1-16 has J1 with cusp=1. createJ1 needs to handle cusp.

We need to introduce a regression test in the unit test of J1.

**Comment by lshulen** [comment]
OK, will take a look now.  I thought I had handled this, but perhaps just for J2.

**Comment by ye-luo** [comment]
Thank you @lshulen. Hopefully the fix will be simple. You can verify by running
`ctest -j16 -R short-H4-opt-OneShiftOnly-1-16`  a couple of times, if you don't get any failure. It should be good.

**Comment by prckent** [comment]
Interested in what the issue turns out to be here. Perhaps we need to formalize checking the interface between the optimizer and the Monte Carlo.

**Comment by ye-luo** [comment]
Now we actually have the capability of testing multiple sections of QMC methods in one run and thus having more granularity within a single test. Probably adding an energy check on the first VMC block is simple but very helpful.

**Comment by prckent** [comment]
Ideally we have tests that run instantly that developers can use while developing. i.e. deterministic unit and integration tests with good enough coverage to catch these problems.

**Comment by lshulen** [comment]
Another one that I have thought would be nice would be to have some unit type test for setting whether various parameters are on or off for optimization from the input file.  It shouldn't be something that really needs calculations to be performed, but I'm not sure how to do that in practice.

**Comment by ye-luo** [comment]
As a regression test for this case, expand one of the unit test by adding cusp and then check the first element of the coefficient may be enough. https://github.com/QMCPACK/qmcpack/blob/4e650e01d7d738eb6a543371cbc4b955466d82b5/src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp#L313

**Comment by jtkrogel** [comment]
Deterministic tests for the optimizer would be good.  I think a necessary first step is for the optimizer to print out some information to formatted files each iteration (perhaps enabled by some verbosity flag).  

This way, even one or two iterations (with a small sample set?) could be deterministically checked instead of waiting for the second VMC/sampling cycle to start.

**Comment by lshulen** [comment]
I have a fix that gets the unit test to run properly.  It was as I suspected.  I just wasn't checking in createJ1 for the cusp to be set.  Ideally I actually think this should be handled by the put method of the individual functors, but I will settle for getting the code working with no additional refactoring.

I will now take a few hours and see if I can learn enough about the unit test to add something to properly test this without having to run short-H4-opt-OneShiftOnly-1-16.  It looks like Ye's suggestion to add another test like the one starting at line 313 of test_bspline_jastrow.cpp, but with the cusp set to a nonzero value will do it.
