### ISSUE TITLE
Undefined variable in Quadrature.h in Debug mode

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#1180]
#1168 commented out the definition of 'delta' in Quadrature.h.   This value is used later in an assert, which causes a compile failure in debug mode.  
The implementation of 'assert' is a macro that is empty in Release mode, so the values are never compiled or used.

Possible solutions
1. inline the definition of 'delta' into the assert.   Ugly.
2. Keep delta and live with the unused variable error in release mode.  Ugh.
3. Mark the value of delta as used to satisfy the compiler.   There are likely standard techniques or attributes to handle this.  This issue is a marker to research this and put it into the code.

**Comment by prckent** [comment]
Sorry! Would #defining the constant work?

**Comment by markdewing** [comment]
Yes, it should work.   It's a cleaner way of doing solution #1.

**Comment by ye-luo** [comment]
NDEBUG is the standard MACRO for assertion.
