### ISSUE TITLE
Need a base class for DiracDeterminant

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1181]
Currently. DiracDeterminant is not only a pure base class but also carries the CPU implementation.
Then DiracDeterminantCUDA, DiracDeterminantOpt, SlaterDetOpt, DiracDeterminantWithBackflow are all derived from it, namely carrying all the unnecessary pieces from DiracDeterminant.
To resolve this complexity, I'm considering to introduce base class SingleDeterminant(or a better name from suggestions) which mostly carry only pure virtual functions.

The reason I need this change is because I will introduce another class for delayed update using cublas on the CPU code path. The current situation is just getting worse and it is better to change on the main branch instead of my local branch.

**Comment by jtkrogel** [comment]
Would keep DiracDeterminant for base class (DiracDeterminantBase is already taken) and push down the CPU only stuff to e.g. DiracDeterminantCPU.

**Comment by ye-luo** [comment]
@jtkrogel DiracDeterminantBase has been changed to DiracDeterminant. Are you thinking DiracDeterminantBase is a better name than SingleDeterminant for the base class?

**Comment by jtkrogel** [comment]
No, just that the heavy stuff you are moving is specific to CPU and so it should follow the same pattern as for CUDA.

Either: DiracDeterminantBase as virtual base class and DiracDeterminant as CPU class
Or: DiracDeterminant as virtual base class and DiracDeterminantCPU as CPU class

I just think we should have "DiracDeterminant" in the name for all DiracDeterminant family classes.

**Comment by prckent** [comment]
While I agree that a refactor is needed here, adding yet another layer of classes is not how we should be doing this long term and probably not even in the short term. We can discuss if mainline should be updated at this point. 

Q. Why even add a class? Are there distinct benefits of that route? We only need a performance analysis at the moment, so putting the CUBLAS implementation alongside the CPU would be simple and enable very easy debug+check.

**Comment by ye-luo** [comment]
We are not adding a new layer of class. The idea is split the role of DiracDeterminant into a class carry CPU implementation and a virtual base class DiracDeterminantBase. Then all the derived class are only derived from DiracDeterminantBase. We can't avoid a base class because the upper level relies on virtual function to dispatch to the actual DiracDeterminant implemenation.

Cublas requires me to add cuda specific stuff. Putting it inside DiracDeterminant next to the CPU implementation is nasty. The implementation is not as simple as the CPU one because I need explictly control the data movement to reduce the cost. It should be like the DiracDeterminantCUDA standing alone by itself. It is allowed to select DiracDeterminant or DiracDeterminantCUBLAS at runtime from input file. Commented debugging can appear during development but is ugly in the final merged code. Currently, the cublas implementation do checks in the unit test.

**Comment by PDoakORNL** [comment]
I prefer something like
```C++
template<Batching B, Device DT>
class DiracDeterminant
{
...
QMCT::valuetype ratio(ParticleSet& P, int iel)
{
    return determinant_device->ratio(P, iel);
}
...
private:
DeterminantDevice<DeterminantDeviceImp<DT>>* determinant_device;
}

template<class DEVICEIMP>
class DeterminantDevice
{
public:
  using QMCT = QMCTraits;

    inline QMCT::ValueType ratio(ParticleSet& P, int iel)
  {
    return static_cast<DEVICEIMP*>(this)->ratioImp(P, iel);
  }

}

template<>
class DeterminantDeviceImp<Devices::KOKKOS>
    : public DeterminantDevice<DeterminantDeviceImp<Devices::KOKKOS>>
{
public:
  using QMCT = QMCTraits;
... tons of Device specific structures
inline QMCT::ValueType ratioImp(ParticleSet& P, int iel)
  {
    const int nels = psiV.extent(0);
    constexpr double shift(0.5);
    //constexpr double czero(0);
    for (int j = 0; j < nels; ++j)
    {
      psiV_host(j) = myRandom() - shift;
    }
    Kokkos::deep_copy(psiV, psiV_host);
    // in main line previous version this looked like:
    // curRatio = inner_product_n(psiV.data(), psiMinv[iel - FirstIndex], nels, czero);
    // same issues with indexing
    curRatio = lah.updateRatio(psiV, psiMinv, iel - FirstIndex);

    return curRatio;
  }
...
};
```
I prefer having something like this, if DiracDeterminant doesn't have any device independent functionality it wouldn't need to exist and would get refactored away. Although it might be the place to put conversions between data on one device and another. The device specific data structures and interfaces are hidden in the device class. DeterminantDeviceImp implies equivalence between implementations and facilitates meta programming.

Sometime in the next couple of weeks I hope to have miniqmc supporting CPU KOKKOS and OMP "devices" and Batched and Single evaluation via this pattern. I already tested this with CPU and KOKKOS determinants.

**Comment by ye-luo** [comment]
Here I'm only planning to introduce DiracDeterminantBase which will be needed even you do
```C++
template<Batching B, Device DT>
class DiracDeterminant::public DiracDeterminantBase
```
I need to keep the upper level working properly with incremental changes.
We would like to understand your prototype on miniQMC.
