### ISSUE TITLE
Change default to delayed updates

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1187]
This newly implemented optional feature should become the default, with some heuristic or (preferred) auto-tuned delay factor. We will need to test that e.g. observables work as expected.

**Comment by ye-luo** [comment]
I kind of want to enable delayed update by default to 32 for systems >=256 electrons. What kind of tests are needed to convince people that this default choice is good?

**Comment by ye-luo** [comment]
If a matrix leading dimension is >= 192, set 32. 192 correspond to NiO 32 atom cell.
Regarding performance tests, we have one set using default and one set with specific delayed rank. Should we remove one set to reduce testing time?
