### ISSUE TITLE
RadialJastrowBuilder adds extra KContainer initialization

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1192]
It seems that RadialJastrowBuilder does some extra work.
See below after printing the parameter. The old builder doesn't print "KContainer initialised..."
```
  RadialJastrowBuilder adds a functor with cusp = -0.2500000000
 size = 10 parameters
 cusp = -0.2500000000
 rcut = 5.5727791786
Parameter     Name      Value
uu_0 0.2862235606 1 1  ON 0
uu_1 0.1947736889 1 1  ON 1
uu_2 0.1319544911 1 1  ON 2
uu_3 0.0889339447 1 1  ON 3
uu_4 0.0569557585 1 1  ON 4
uu_5 0.0356595851 1 1  ON 5
uu_6 0.0220695026 1 1  ON 6
uu_7 0.0129608642 1 1  ON 7
uu_8 0.0066010072 1 1  ON 8
uu_9 0.0027871444 1 1  ON 9
  KContainer initialised with cutoff 9.4916334152
   # of K-shell  = 3523
   # of K points = 113160

  NUMBER OF OPT_BREAK KVECS = 31026066914
 finding kc:  1.5418392420 , -1.0000000000
  LRBreakp parameter Kc =1.5418392420
    Continuum approximation in k = [9.4916335819,616.7357058014)
```

**Comment by lshulen** [comment]
OK, I'll take a look.

**Comment by lshulen** [comment]
OK, It looks like I was initializing with RPA when this was not requested.  The previous builder checked to see if this was asked for in the xml.  I'll add the fix now.  Is it OK to have a single pull request that fixes this and the J1 cusp issue?

**Comment by prckent** [comment]
It is preferred to keep things separate but since the fixes and likely small and easily reviewable I think whatever route is expeditious.
