### ISSUE TITLE
numpy matmul used by NEXUS is not available in older numpy

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1207]
The updated library/structure.py merged last night uses matmul which is not always available. https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=33899

Running develop by hand on oxygen I can confirm that the tests are also broken there.

The library/gaussian_process.py code also uses it, but we don't run that in the tests yet.

Suggestions: add minimum version checks; use our own implementation (either always or when not available);

**Comment by jtkrogel** [comment]
Sounds like it should be replaced by the standard "dot" function if possible.  

@kayahans is the code making use of any matmul functionality that differs from dot?

**Comment by jtkrogel** [comment]
OK, I will change it to dot then.

**Comment by jtkrogel** [comment]
Resolved by #1210.  Closing.
