### ISSUE TITLE
Read and write permissions required on HDF5 spline file

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#122]
We require read and write permissions when only read should be needed. Code will crash if write permissions not available.

This problem was highlighted by the first runs of the performance tests. I had marked the reference spline files read only for safety.

EinsplineSetBuilderOld.cpp:
  H5FileID = H5Fopen(H5FileName.c_str(),H5F_ACC_RDWR,H5P_DEFAULT);
//  H5FileID = H5Fopen(H5FileName.c_str(),H5F_ACC_RDONLY,H5P_DEFAULT);

Curiously, at one point in the long distant past we did open the file read only. Restoring this setting works for the tests that we have. 

Before I fix this via PR, are there any cases where write permissions would actually be required?

[ Also related to #36 ]

**Comment by jtkrogel** [comment]
The only instance I can think of that where H5 write is performed for orbitals is with "--save_wfs" enabled, but unless I am mistaken this is only for the *einspline*h5 files and not the source h5.

**Comment by ye-luo** [comment]
I think we only need read-only. RW causes another problem that parallel running using the same h5 gets failure due to hdf5 file lock. RW also changes the md5sum of the source h5.
--save_wfs does not touch the source h5.

**Comment by jtkrogel** [comment]
I think this is used in the orbital rotation facility.  See EinsplineSetBuilderESHDF.fft.cpp : "h_splineData.write(H5FileID, psirName.c_str());".  Neighbouring code makes a backup of the H5 file first in H5FileName+"_bkup".

Has anyone (other than Jeremy) ever used this?

**Comment by ye-luo** [comment]
These routines are no longer used. Though they are protected with QMC_CUDA (I did this when I introducing the optimized spine routines in 2015 spring). They are actually no more used when I improved the GPU code (2016 spring). Spline construction is only with the parallel newer parallel builder.
In my opinion, changing the source h5 is a dangerous thing and should be forbidden.

**Comment by prckent** [comment]
@ye-luo Yet I hit this code overnight. So it is used. Intel 2017 build.

**Comment by ye-luo** [comment]
@prckent I mean the part Jaron mentioned is out-of-date. Which code do you refer to?

**Comment by prckent** [comment]
@ye-luo Only EinsplineSetBuilder::ReadOrbitalInfo() in EinsplineSetBuilderOld.cpp

I'll make the PR.
