### ISSUE TITLE
What is the preferred way to handle errors and terminate the application?

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#125]
To collect the ideas here about the preferred way to handle errors and termination of the app.\
We have several ways to print warning or error(with a stop) and the role and behaviour is not obvious.
Some of them are related to MPI and some are not.

abort(): from C/C++
APP_ABORT("XXXX"): macro to MPI abort, but difficult for unit tests.
exit(1): from C/C++
std::runtime_error("XXXX"): C++
app_error(): stream error output but only rank 0. No termination.

MISC ideas
1, app_error() handling. What should be sent through.
2, error messages from external libraries. Do we make it cleaner or keep them original.
3, all nodes or master only depends on error types.
4, how to integrate errors with external tools, workflow, job scheduler.

**Comment by markdewing** [comment]
Unit testing also needs to be considered - calling abort or APP_ABORT right at the point of fatal errors makes it difficult to test error paths.

**Comment by prckent** [comment]
My main user focused concern is that with typical errors such as missing files or  inconsistent inputs we return a useful message ("Couldn't write new the optimized wave function opt.xml") ahead of any library errors. Otherwise the useful message tends not to be seen and we take the blame. Conceivably this involves both HDF5 and XML handling.

**Comment by prckent** [comment]
What does app_abort() do currently? Does it behave consistently across different systems?

**Comment by ye-luo** [comment]
Paul's question raises the urgency of a preliminary dev guide. APP_ABORT looks like a macro wrapping something up. abort() is also used in the code to stop the code.

**Comment by jngkim** [comment]
Yes, it is just to call mpi finalize.

Never meant to be an error handling method.

**Comment by ye-luo** [comment]
#define APP_ABORT(msg) \
{std::cerr << "Fatal Error. Aborting at " << msg << std::endl; OOMPI_COMM_WORLD.Abort();}

**Comment by prckent** [comment]
@ye-luo Agree with deciding on the preferred way(s) and documenting them. We should simply build up a developer chapter.

**Comment by jtkrogel** [comment]
I think an abort should attempt a clean shutdown of the entire application, if possible (e.g. no broken h5 files).  

I don't have a strong opinion on how this should be handled (function call, macro, exceptions, etc).

**Comment by prckent** [comment]
The most likely aborts will all occur on initialization or at the first step, so the open H5 problem is not severe. However it would be desirable to close H5 files when an exception is thrown. I don't believe this is a big problem currently, but as observables with H5 output are added/used more extensively it will be important to handle these safely.

**Comment by ye-luo** [comment]
My experience in #1546 shows:
APP_ABORT can be safely called from every rank even if only one rank calls APP_ABORT. Unfortunately, if there were error messages sent to app_error (on rank 0), they might not be sent out when a rank!=0 stops the code first.
if the APP_ABORT is uniformly processed by all the ranks, it is better to use
```
app_error() << "intended error message" << std::endl; // only rank==0 prints
myComm->barrier() // all ranks wait, usually,  for rank==0
myComm->abort() // invoke MPI_Abort
```
All the error messages are guaranteed to be printed before the barrier. This is typically true when parsing XML input.

However, If an error is trigged only by one or a few ranks, the barrier causes hanging with the above code. The above scheme should be avoided in this case.

**Comment by markdewing** [comment]
Could this pattern be bundled into a function or macro, like APP_ABORT_ON_ALL_RANKS? or some other name?

**Comment by ye-luo** [comment]
APP_ABORT itself is a brute force stop by calling MPI_Abort directly.
I don't feel it write adding `app_error() << msg` but I'd like to print the message one once.

I prefer to stop in a more clean way.
probably add Communicate::barrier_and_abort()?

**Comment by markdewing** [comment]
Yes, that would at least combine the barrier and abort to make it easier to implement the guaranteed error output idiom.

**Comment by PDoakORNL** [comment]
Copied from #1803 

This gives us a path to better error handling wrt non-trivial concurrency and it can be checked for in catch test program.

Example

REQUIRE_THROWS_WITH(test_block(nested_tasks, std::ref(count)),
                      Catch::Contains("TasksOneToOne should not be used for nested openmp threading"));

On the other hand we do want to call MPI_Abort eventually. Although it doesn't appear this happens for unhandled exceptions right now.

**Comment by PDoakORNL** [comment]
Outside of the exceptions ones we have added explicitly added.

I believe everytime we use an STL container and don't specifiy something other than the standard allocator we're exposed to a thrown std::bad_alloc.

If true this means every parallel openmp region should contain a try catch block
As well as requiring an outer one a rank scope.

**Comment by PDoakORNL** [comment]
@markdewing  from #1803: 
I've had trouble with C++ exceptions in MPI programs - I think it was debugging some of the cusp condition problems. It may be a BG/Q issue, but it's worth checking on other platforms.

**Comment by PDoakORNL** [comment]
In the short term I think we should try something like this in qmcapp.cpp.  This gives us a backstop for anything thrown from a non threaded section.

```C++
  try
  {
    QMCMain* qmc    = 0;
    bool validInput = false;
    app_log() << "  Input file(s): ";
    for (int k = 0; k < inputs.size(); ++k)
      app_log() << inputs[k] << " ";
    app_log() << std::endl;
    qmc = new QMCMain(qmcComm);
    if (inputs.size() > 1)
      validInput = qmc->parse(inputs[qmcComm->getGroupID()]);
    else
      validInput = qmc->parse(inputs[0]);
    if (validInput)
      qmc->execute();

    Libxml2Document timingDoc;
    timingDoc.newDoc("resources");
    output_hardware_info(qmcComm, timingDoc, timingDoc.getRoot());
    TimerManager.output_timing(qmcComm, timingDoc, timingDoc.getRoot());
    qmc->ptclPool->output_particleset_info(timingDoc, timingDoc.getRoot());
    if (OHMMS::Controller->rank() == 0)
    {
      timingDoc.dump(qmc->getTitle() + ".info.xml");
    }
    TimerManager.print(qmcComm);
    if (qmc)
      delete qmc;
  }
  catch (const std::exception& e)
  {
    app_error() << e.what() << std::endl;
    APP_ABORT("Unhandled Exception");
  }
  catch (...)
  {
    app_error() << "Exception not derived from std::exception thrown" << std::endl;
    APP_ABORT("Unhandled Exception");
  }
```

**Comment by ye-luo** [comment]
I have a more clear picture how to print and abort errors properly.
[Error handling (draft)](https://github.com/ye-luo/qmcpack/wiki/Error-handling)
Printing style also needs discussion.
Currently 2), 3) and 4) add "Fatal Error. Aborting at " before the string from the argument.
We do need to distinguish a user error message and a developer error message.
```
std::cerr << "Fatal Error " << msg.
```
Then we pass in msg as

- "User: wrong size of abc" for an error message to user.
- "Developer: safeguard xxx triggered." for an error message to developer. Usually this means a bug.

**Comment by prckent** [comment]
There are implementation and presentation issues here. I'll comment on the latter, since we should also clear up the variability there:

I think it is helpful if these important message are easily greppable, so we should ensure to use a standard prefix, header, or set of words, preferably all caps or something that will be seen in the output. I think e.g. a single lower case sentence warning is unlikely to be seen due to the insufficiently friendly human output we have.

**Comment by ye-luo** [comment]
> There are implementation and presentation issues here.
Agreed. The wiki page focuses on the implementation issue. We should discuss more the presentation issue here. Please sketch desired output for warning and error. Maybe every line should start with all caps WARNING or ERROR?

**Comment by PDoakORNL** [comment]
I agree with everything @ye-luo wrote on his wiki page. I'd add that if an "error" is a possible and recoverable outcome we don't (and shouldn't) throw an exception. I believe we've made the decision that if that is the case the call should return an error value and the regular code flow check it and react accordingly. I don't think we should log this as an error.  We can warn such and such had an error and it was handled.

And we definitely need a common format for the error messages all caps works for me I think just ERROR is needed.  I think we also need to add origin i.e. `__FILE__ __LINE__` information.

a warning that needs to be written possibly not everywhere should use std::cerr.
A warning that every rank will encounter should use app_warning() 

I think the basic implementation pattern in at least the medium term could be:
Deprecate APP_ABORT as suggested by @ye-luo, replace its use in qmcapp.cpp


* on a nonrecoverable error throw something derived from std::exception
  1. If the error is something every rank will encounter first write to app_error() including origin and flush i.e. std::endl first. Somewhere like input parsing continue if possible calling app_error() on everything that is wrong, then throw a qmcplusplus::RuntimeErrorEverywhere exception. However once you have called app_error() it should be inevitable qmcplusplus::RuntimeErrorEverywhere will be thrown.
  2. If the error could happen here fill the exception message with the needed information (i.e. what happened where and with what)
  3. don't know do 2
* at each enclosing catch except at the top add to message and/or repackage if useful then rethrow. Generally this will be to add useful information on origin to exceptions thrown by external code.
* in the top try/catch block of qmcapp either
  1. catch a qmplusplus::RuntimeErrorEverywhere and call abort on the mpi wrapper.
  2. catch any other exception write the message to std::cerr and flush, then call abort on the mpi wrapper.

---

**Comment by prckent** [comment]
Do we have or anticipate any recoverable errors? Currently I think we either have genuine ABORTs (missing file, numerical error trap, incorrect input) or WARNINGS (e.g. walker lifetime and population control, optimization problems)

**Comment by ye-luo** [comment]
We do have recoverable errors in hdf5 part. Functions return success/failure and no throw. This is useful to handle backward compatibility of our hdf5 formats looking for a dataset in a few places.

**Comment by PDoakORNL** [comment]
That's the right thing to do but those should call app_warning(), which they might already.

**Comment by PDoakORNL** [comment]
In code where it might end up in a threaded section its better to have an exception to handle than the possible weirdness of calling out to a function containing an MPI_Barrier.

**Comment by PDoakORNL** [comment]
this for example would become
```c++
// from HybridRepSetReader.h
// reading atomic center info
      bool success = true;
      std::ostringstream error_string;
      app_log() << "Reading atomic center info for hybrid representation" << std::endl;
      for (int center_idx = 0; center_idx < ACInfo.Ncenters; center_idx++)
      {
        const int my_GroupID = ACInfo.GroupID[center_idx];
        if (ACInfo.cutoff[center_idx] < 0)
        {
          error_string << "Hybrid orbital representation needs parameter 'cutoff_radius' for atom " << center_idx
                      << std::endl;
          success = false;
        }

        if (ACInfo.inner_cutoff[center_idx] < 0)
        {
          const double inner_cutoff = std::max(ACInfo.cutoff[center_idx] - 0.3, 0.0);
          app_log() << "Hybrid orbital representation setting 'inner_cutoff' to " << inner_cutoff << " for group "
                    << my_GroupID << " as atom " << center_idx << std::endl;
          // overwrite the inner_cutoff of all the atoms of the same species
          for (int id = 0; id < ACInfo.Ncenters; id++)
            if (my_GroupID == ACInfo.GroupID[id])
              ACInfo.inner_cutoff[id] = inner_cutoff;
        }
        else if (ACInfo.inner_cutoff[center_idx] > ACInfo.cutoff[center_idx])
        {
          error_string << "Hybrid orbital representation 'inner_cutoff' must be smaller than 'spline_radius' for atom "
                      << center_idx << std::endl;
          success = false;
        }
...
        if (!success)
          throw RunTimeErrorEverywhere(error_string.str());
}
```

**Comment by prckent** [comment]
Regarding formatting, a simple "ERROR: message" or "WARNING: message"  should suffice, and is close to what we have been doing recently. Importantly we should take care to print at least one newline before the message, and one after in the case of WARNINGS. (Output is messy enough in a few places that they can blend in.)

**Comment by prckent** [comment]
Is everyone happy that we can handle MPI aborts and abort correctly in unit tests based on Ye's current wiki?  (I am).

Also I assume that the plan would be to remove the APP_ABORT macro and other deprecated aborts shortly after deciding on this plan.

**Comment by jtkrogel** [comment]
Discussion settled?
