### ISSUE TITLE
AFQMC not enabled in CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1252]
Currently CI scripts on Rhea do not enable BUILD_AFQMC? Does anyone remember the history?
Consider AFQMC development will be more close to the main repo, we need to turn that on.

- [x] boost 1.61 needed in CI scripts. Rhea default is 1.58
- [ ] ~~update CI script to enable BUILD_AFQMC on complex builds.~~

**Comment by prckent** [comment]
Rhea is using 1.61.0

**Comment by ye-luo** [comment]
I changed the strategy. There is no need to update the CI scripts. AFQMC will be turned on by default with appropriate build variants.
