### ISSUE TITLE
Python scripts involved in configuration should be 2/3 compatible

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#1256]
The python scripts used during configuration should be compatible with both Python 2 and 3.

Known so far:
- tests/scripts/test_labels.py
- tests/performance/adjust_qmcpack_input.py
Are there any others?

Motivated by logging into Summit - the default python seems to be python 3.

**Comment by prckent** [comment]
Very good point.

**Comment by jtkrogel** [comment]
Resolved by #1261.  Closing.
