### ISSUE TITLE
Make batched non-local pseudopotential evaluation default in CPU code

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1258]
The fastest in general algorithm should be the default.

**Comment by ye-luo** [comment]
It seems that this code path do gets slower on small memory BW and large cache architectures.
Due to the offload, I maybe need to revise the batched ratio evaluation algorithm to move less data and it helps the cache on CPU as well.

**Comment by prckent** [comment]
Closing. Not a priority then for 3.7.0. There are far more important things to work on.
