### ISSUE TITLE
LCAO SoA third derivatives for backflow needed

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1260]
Update #861 when closing this issue

**Comment by prckent** [comment]
Adding as a gating issue for v3.7.0 following discussions this week.

**Comment by prckent** [comment]
@rcclay Do you have an eta for this, or should we defer making SoA the default for another v0.1?

**Comment by rcclay** [comment]
The safest thing would be to set the default for +0.1, since I'm bogged down with other projects for this week and next.  It should only take a few days for coding+debugging once I can get the time.

**Comment by rcclay** [comment]
This is closed by #1549 .
