### ISSUE TITLE
ratio values in ratio() ratioGrad() overflow

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1267]
I noticed that overflow sometimes happens when mixed precision is used and causes NaN in KE or NLPP.
The solution will be using the log value at WaveFunctionComponent and then apply exp() at TrialWavefunction.
In this way, there is no code change needed in the drivers while the amplitude of ratio cancels within TrialWavefunction.

**Comment by jtkrogel** [comment]
I thought this would bite us sometime.  Surprised it took this long.

**Comment by ye-luo** [comment]
@jtkrogel welcome to discuss any concerns using github issue.

**Comment by jtkrogel** [comment]
Fair enough.  The last time I thought about this issue was in the pre-GitHub era.

**Comment by prckent** [comment]
- What system size & type do you find to be the threshold for this problem? 
- Does use of double precision delay this issue sufficiently for you?
- I have spotted this issue before using double precision. Are there other places where the use of log/exp are (lets say) not as advantageous as they should be?

**Comment by ye-luo** [comment]
It seems not system size but system/wavefunction dependent.
I didn't see NaN problems with double precision but the accuracy can still be affected without notice.
It is hard to say your previous NaN experience is related to issue. For example, we saw NaN in the GPU code due to the bad use of cublas. If you encounter NaN, please submit an issue with a reproducer.

**Comment by prckent** [comment]
Is there a reproducer for this problem? If not I suggest to close and open an new issue if/when it turns up again. As written this issue is not actionable.

**Comment by ye-luo** [comment]
Yes. I have one. I'm still thinking about how to handle the complex to real conversion in clean way since now we pass the log value. Please leave this open.
