### ISSUE TITLE
Could not read multi determinants as trial wavefunction for AFQMC code.

### ISSUE THREAD

**Issue by hongxiahao91** [QMCPACK/qmcpack#128]
There is no way to read multi determinants as trial wavefunction for AFQMC code. It would be very nice if we can implement this.

**Comment by fdmalone** [comment]
This is implemented for both particle-hole and non-orthogonal multi slater determinants.

See, for example,  04-N2_nomsd  05-N2_phmsd.

Currently multi determinant wavefunctions are not fully supported on GPUs.
