### ISSUE TITLE
AFQMC complex mixed precision build is broken

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1283]

**Comment by fdmalone** [comment]
It looks as if single precision isn't fully supported in AFQMC, so I would suggest for CI that it temporarily is disabled in single precision builds. We have hardcoded complex doubles and I think some of BLAS/LAPACK routines are missing.

**Comment by mmorale3** [comment]
It is not supported yet. Both mixed precision and real builds are not yet working. I’m working on both, but for now AFQMC should be disabled in both cases.
