### ISSUE TITLE
Cannot start from HF energy for HCN anion with large basis sets (avtz) for AFQMC code.

### ISSUE THREAD

**Issue by hongxiahao91** [QMCPACK/qmcpack#129]
Tried with HCN anion with avtz basis set. AFQMC cannot start at the same place where HF stays. Only happens to HCN anion. HCN neutral molecule works well.

**Comment by prckent** [comment]
Do other anions work?

**Comment by fdmalone** [comment]
Closing for now (before my time) . I imagine this is no longer an issue with the migration away from FCIDUMPs.
