### ISSUE TITLE
Should remove use of variable length arrays (VLA)

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#1299]
VLA (Variable-length arrays, where the length is determined at runtime) is a C99 feature, but not part of C++.   Most compilers accept it as an extension, though.
They are used in 
* io/hdf_dataproxy.h 
* einspline/multi_bspline_eval_{sd}_std3.cpp
* Numerics/DeterminantOperators.cpp

These could be replaced by one of:
1. static array with a fixed size (if an upper bound on the dimensions is known)
2. std::vector

(Technically, `alloca` could be used to preserve the stack allocation behavior of a VLA, but I don't think this really necessary in any of these cases?)

This was discovered using the `-pedantic-errors` switch to gcc, looking for a cleaner solution to finding c++17 features in #1296.  (So far, all the errors were about extra semicolons or VLA's)

**Comment by ye-luo** [comment]
I tried -Wvla a few months a go and there are definitely more. I'm also in favour of avoiding VLA.

**Comment by ye-luo** [comment]
VLA will be stopped as compiler error in all C++ source code except legacy CUDA build
