### ISSUE TITLE
NoMPI builds broken by counting Jastrow factor

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1307]
See e.g. https://cdash.qmcpack.org/CDash/viewBuildError.php?buildid=38283

**Comment by prckent** [comment]
@bwvdg Please can you take a quick look at this?

**Comment by bwvdg** [comment]
I neglected to change these function calls when I was changing from the std::function indexers to the Matrix classes. I'll have a fix shortly.

**Comment by prckent** [comment]
Thanks @bwvdg  , much appreciated.
