### ISSUE TITLE
High failure rate short-diamondC_2x1x1_pp-vmc_gaussian_sdj-1-16-ionion

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1316]
On the real build, the number goes wrong very frequently.
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2019-01-14&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=short-diamondC_2x1x1_pp-vmc_gaussian_sdj-1-16-ionion&field2=buildname&compare2=64&value2=complex

**Comment by ye-luo** [comment]
as well as oxygen in another night.
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&limit=0&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=short-diamondC_2x1x1_pp-vmc_gaussian_sdj-1-16-ionion&field2=buildname&compare2=64&value2=complex

**Comment by jtkrogel** [comment]
Test names and output data prefixes (project id) should be unique for the tests.  Does enforcing this fix the problem?

**Comment by ye-luo** [comment]
Let us first update the name and see what changes over the night.

**Comment by prckent** [comment]
Who will do the rename?

**Comment by prckent** [comment]
Thanks for checking @ye-luo  and @PDoakORNL for the fix.

It would be handy if cmake caused an error with generate test naming. Also, there does not appear to be an official way to query for existing tests.
