### ISSUE TITLE
GAMESS aldet conversion

### ISSUE THREAD

**Issue by mcbennet** [QMCPACK/qmcpack#1328]
When converting a gamess output in the case of an aldet calculation where the number of core orbitals is non-zero, the configurations are not correctly printed -- specifically, the core occupations are not included in the configurations.

Here is an example input for gamess (gamess_aldet_example.inp) that will reproduce the issue:

 $SYSTEM MWORDS=200 MEMDDI=100 $END
 $BASIS GBASIS=dzv $END
 $CONTRL SCFTYP=mcscf ispher=1 units=bohr $END
 $mcscf cistep=aldet fullnr=.true. $end
 $DET ncore=18 nact=6 nels=6 nstate=1 $end
 $guess guess=hcore norder=1
        iorder(18)=19,18 $end

 $DATA
benzene
dnh 2

H 1.0 0.000 4.685 0.000
H 1.0 4.057 2.342 0.000
C 6.0 0.000 2.638 0.000
C 6.0 2.285 1.319 0.000
 $END

After running "convert4qmc gamess_aldet_example.out -ci gamess_aldet_example.out", the multideterminant section of the wfnoj.xml file appears as:

      <multideterminant optimize="no" spo_up="spo-up" spo_dn="spo-dn">
        <detlist size="21" type="DETS" nca="18" ncb="18" nea="3" neb="3" nstates="6" cutoff="1e-20">
          <ci id="CIcoeff_0" coeff="0.806053" qc_coeff="0.806053" alpha="111000" beta="111000"/>
          <ci id="CIcoeff_1" coeff="-0.245232" qc_coeff="-0.245232" alpha="110100" beta="110100"/>
          <ci id="CIcoeff_2" coeff="-0.245049" qc_coeff="-0.245049" alpha="101010" beta="101010"/>
          ....

where it can be seen that the core orbitals are missing from the configurations.

**Comment by mcbennet** [comment]
In my humble opinion, it seems that (1) might be a better solution since it "cleans up" the xml input file removing long strings of '1's when core electrons are present. Additionally, it removes redundancy -- that is, the number of core orbitals is given through nca and ncb so there is no need to also give their occupations.

**Comment by prckent** [comment]
Why not just fix the configuration spec in our XML to include the core electrons correctly? If I understand the above, this will involve padding the occupations with the correct number of 1s for each spin. I think this is Anouar's option 2. This is the simplest fix with the simplest implementation. The spec is verbose for a large system,  but that is a different problem. We have already determined that the current occupation labeling is unscalable and will need to be replaced by a new spec that describes the actual excitation. When we eventually use that the concept of a core electron becomes even less necessary, and the new spec will be much more readable human readable than either of the current options.

**Comment by ye-luo** [comment]
@mcbennet Has this been fixed by #1342

**Comment by mcbennet** [comment]
Yes. The fix (PR #1342) corresponds to suggestion 2 of @anbenali above.
