### ISSUE TITLE
Formatting Issues in manual

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#1329]
List of bad formatting in manual.  If you wrote this section consider fixing it.
Build the manual to see how your fix looks.
See below for the current guidance on formatting different sections

- Additional Tools
  - [x] badly formatted XML
  - [x] Aquiring  pseudopotentials -- verbatim section overruns.
- Lab3
  - [x] appendix XML
- Lab4
  - [x] Supertwist section verbatim overruns

## Formatting suggestions
XML should be included like this
```latex
\begin{lstlisting}[style=XML]
  <simulationcell>
    <parameter name="lattice">
      3.8       0.0       0.0
      0.0       3.8       0.0
      0.0       0.0       3.8
    </parameter>
    <parameter name="bconds">
       p p p
    </parameter>
    <parameter name="LR_dim_cutoff"> 20 </parameter>
  </simulationcell>
\end{lstlisting}
```

**Comment by prckent** [comment]
Peter - If you can, please assign specific fixes to individual people. Otherwise they won't get done.
