### ISSUE TITLE
ABINIT wavefunction converter

### ISSUE THREAD

**Issue by grahamlopez** [QMCPACK/qmcpack#134]
paraphrased from a slack conversation on 24 Feb 2017

paulrckent [3:11 PM] 
Note on conversion from plane waves codes: ABINIT has an embedded CASINO converter that produces pwfn.data files. It is not parallelized. However it does mean that much of the necessary plumbing is in place when we want to interface with ABINIT. ( I know that wfconvert could do this at one point, but having an official ABINIT converter would be much better than performing the necromancy necessary to resuscitate wfconvert. )

lshulen [3:12 PM] 
Agreed about reanimating wfconvert. 

paulrckent [3:15 PM] 
ABINIT has different mixers and diagonalization schemes to QE, so we might have reason to try ourselves should we want something in addition to QE.

**Comment by prckent** [comment]
Summarizing: if we receive a request to support ABINIT, it could likely be done, at least in serial, fairly quickly.

**Comment by ye-luo** [comment]
See more focused discussion in #512
