### ISSUE TITLE
LiH dimer determinstic test fails with mixed precision builds

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1367]
Currently, the mixed precision builds are failing the deterministic LiH dimer tests.
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2019-02-07&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=deterministic-LiH

Three causes for the numerical difference.
1) Initial electron coordinates are randomly generated. They can be fixed from the input.
2) Even using the same configuration, the wf can be computed slightly different. This can be checked after 1) by not moving the electrons at all.
3) The electron trajectory can be slightly different. it needs to be confirmed that whether the amount of acceptance and rejection agree. Then numerical difference in the drift or ratio can also introduce bias. If this is the case, it will be hard to improve.

**Comment by prckent** [comment]
Three *possible* causes. In general, another is that the XXX code is wrong. Here we are likely having to deal with precision.

@Hyeondeok-Shin please can you investigate and make a recommendation.

- Are the Monte Carlo steps taken ~the same. An easy give away would be a different acceptance ratio.
- Are the runs (all properties) close enough that we consider them to be the same, i.e. we are satisfied that this is a precision issue. In general this is where the real work will be - there could be a lousy piece of code with statistically hidden errors. This could even apply in this case.
- Is there an actual bug in the mixed precision code?
- How to fix the problem? Potentially the electron positions are just different enough (single vs double precision); a shorter run could fix this. The errors would be reduced but not removed by specifying the initial position in double in the input. Changing the seed might also work, single the electrons could be in a particularly sensitive part of the wavefunction.
- ...

**Comment by prckent** [comment]
From a quick look at cdash, the kinetic energy is too far off. Interestingly all the other terms in the Hamiltonian pass.

A check on the acceptance ratio would be a quick way of identifying divergent/different MC walks from the gold reference.

**Comment by jtkrogel** [comment]
I would recommend expanding this (and all future) deterministic test to include all checkable quantities (energy terms, acceptance ratio, etc).  These are easily available and would provide additional insight on the failures.

**Comment by Hyeondeok-Shin** [comment]
I checked outputs for full & mixed precision, and it seems initial condition is slightly different between them.

[hdshin@vestalac2 LiH_dimer_pp]$ diff mixed_precision.out full_precision.out 
26c26
<   Base precision      = float
---
>   Base precision      = double
32c32
<   date    = 2019-02-07 16:59:06 UTC
---
>   date    = 2019-02-07 17:13:22 UTC
45,46c45,46
<   Simulation cell radius   = 49999.996094 bohr
<   Wigner-Seitz cell radius = 49999.996094 bohr
---
>   Simulation cell radius   = 50000.000000 bohr
>   Wigner-Seitz cell radius = 50000.000000 bohr
221c221
<    Making L=0 a local potential with a radial cutoff of 9.998999
---
>    Making L=0 a local potential with a radial cutoff of 9.999000
231c231
<    Making L=1 a local potential with a radial cutoff of 9.998000
---
>    Making L=1 a local potential with a radial cutoff of 9.999000
236c236
<     Cutoff radius = 3.161000
---
>     Cutoff radius = 3.160000
238,250c238,250
<              1.0000000000      0.0000000000      0.0000000000        0.0833333358
<             -1.0000000000      0.0000000000      0.0000000000        0.0833333358
<              0.4472135901      0.8944271803      0.0000000000        0.0833333358
<             -0.4472135901      0.7236068249      0.5257310867        0.0833333358
<              0.4472135901      0.2763932049      0.8506507874        0.0833333358
<             -0.4472135901     -0.2763932049      0.8506507874        0.0833333358
<              0.4472135901     -0.7236068249      0.5257310867        0.0833333358
<             -0.4472135901     -0.8944271803      0.0000000000        0.0833333358
<              0.4472135901     -0.7236068249     -0.5257310867        0.0833333358
<             -0.4472135901     -0.2763932049     -0.8506507874        0.0833333358
<              0.4472135901      0.2763932049     -0.8506507874        0.0833333358
<             -0.4472135901      0.7236068249     -0.5257310867        0.0833333358
<     Maximum cutoff radius 3.1610000134
---
>              1.0000000000      0.0000000000      0.0000000000        0.0833333333
>             -1.0000000000      0.0000000000      0.0000000000        0.0833333333
>              0.4472135955      0.8944271910      0.0000000000        0.0833333333
>             -0.4472135955      0.7236067977      0.5257311121        0.0833333333
>              0.4472135955      0.2763932023      0.8506508084        0.0833333333
>             -0.4472135955     -0.2763932023      0.8506508084        0.0833333333
>              0.4472135955     -0.7236067977      0.5257311121        0.0833333333
>             -0.4472135955     -0.8944271910      0.0000000000        0.0833333333
>              0.4472135955     -0.7236067977     -0.5257311121        0.0833333333
>             -0.4472135955     -0.2763932023     -0.8506508084        0.0833333333
>              0.4472135955      0.2763932023     -0.8506508084        0.0833333333
>             -0.4472135955      0.7236067977     -0.5257311121        0.0833333333
>     Maximum cutoff radius 3.1600000000
267c267
<   Initialization Execution time = 1.2076 secs
---
>   Initialization Execution time = 1.1553 secs
277,278c277,278
<     u -8.0857956409e-01  8.9382755756e-01  2.5869417936e-02
<     d  8.6934387684e-02  2.7038547397e-01  1.8422875404e+00
---
>     u -8.0857966684e-01  8.9382770057e-01  2.5869422981e-02
>     d  8.6934387366e-02  2.7038549998e-01  1.8422875954e+00
285c285
<     H  0.0000000000e+00  0.0000000000e+00  3.0139241219e+00
---
>     H  0.0000000000e+00  0.0000000000e+00  3.0139242100e+00
307c307
<   time step      = 4.0000000596e-01
---
>   time step      = 4.0000000000e-01
317c317
< <parameter name="blocks_between_recompute" condition="int">1</parameter>
---
> <parameter name="blocks_between_recompute" condition="int">0</parameter>
336,338c336,338
< <parameter name="tau" condition="au">4.0000000596e-01</parameter>
< <parameter name="time_step" condition="au">4.0000000596e-01</parameter>
< <parameter name="timestep" condition="au">4.0000000596e-01</parameter>
---
> <parameter name="tau" condition="au">4.0000000000e-01</parameter>
> <parameter name="time_step" condition="au">4.0000000000e-01</parameter>
> <parameter name="timestep" condition="au">4.0000000000e-01</parameter>
356,357c356,357
< Allocated heap: 18.10 MB, avail. heap: 16269.88 MB
< Allocated stack: 0.02 MB, avail. stack: 16269.88 MB
---
> Allocated heap: 18.10 MB, avail. heap: 16237.88 MB
> Allocated stack: 0.02 MB, avail. stack: 16237.88 MB
359c359
<   Anonymous Buffer size per walker : 544 Bytes.
---
>   Anonymous Buffer size per walker : 576 Bytes.
365,366c365,366
<     reference energy   = -0.846378
<     reference variance = 3.31699e-17
---
>     reference energy   = -0.846609
>     reference variance = -4.72919e-17
368,369c368,369
<   QMC Execution time = 1.1118e-01 secs 
<   Total Execution time = 1.4995e-01 secs
---
>   QMC Execution time = 1.1172e-01 secs 
>   Total Execution time = 1.4758e-01 secs

I'm not sure whether we can expect same results between them with this condition.

**Comment by jtkrogel** [comment]
We could consider making two new simple scalar estimators that just report the sum of all electron positions and momenta.  This would give direct insight into potential differences in positions and first order w.f. derivatives.

**Comment by jtkrogel** [comment]
@ye-luo Why is "blocks_between_recompute" larger for mixed precision than for full?

**Comment by jtkrogel** [comment]
@Hyeondeok-Shin The main question is why the kinetic energy difference is 3 orders of magnitude larger than for the potential terms.

**Comment by prckent** [comment]
That is a bug in my opinion.

(Since we *do not check the accuracy of the determinants* I would prefer that blocks_between_recompute was 1 for every single build. Other codes manage to check.)

**Comment by ye-luo** [comment]
@jtkrogel The full precision build doesn't do recompute. The mixed precision does it at every block by default.

**Comment by prckent** [comment]
@Hyeondeok-Shin what part of the difference above do you consider to be "big"? By eye they all are close to me. The mixed precision build can at most have 6-9 digits of equivalence, simply by virtue of the single precision format.  As @jtkrogel wrote, the puzzle here is why the kinetic energy is so different. Suggestion:run by hand, see if the kinetic energy agrees in the first block (which is ignored by check_scalars.py). If this disagrees, then maybe try another random seed. If that fails, see if by specifying the electron positions in the input *to single precision accuracy* reduces the difference.

**Comment by ye-luo** [comment]
1. Remove the random initialization. Input the electron coordinate by hand from xml. Use time step 0.0. This should enforce exactly the same electron configurations. Check the difference in KE and Potential.
2. Add back random initialization. Assess the impact from random initialization.
3. Use tstep=0.5 to assess the impact from the random walking. 0.5 is better than 0.4 to avoid the round off error.

**Comment by prckent** [comment]
Extra suggestion: to ensure we don't over-specialize a solution that only works for this test, create the deterministic test case for (say) carbon diamond 2x1x1.

**Comment by ye-luo** [comment]
Agree with @prckent. Creating the solid case first can be very helpful to cross verify the situation.

**Comment by Hyeondeok-Shin** [comment]
@ye-luo @prckent Agreed. I'll also do the test for the solid.

**Comment by Hyeondeok-Shin** [comment]
Quick comment : I did the deterministic test for 'diamondC_2x1x1_pp-vmc_sdj-1-1', it passed with the full precision, but failed in full vs. mixed precision for both KE and potential.

Tests for series 0
  Testing quantity: Kinetic
    reference mean value     :   8.91029274
    reference error bar      :   0.00000100
    computed  mean value     :   8.91024636
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00000300  (  3.00000000 sigma)
    deviation from reference :  -0.00004638  (-46.38410000 sigma)
    error bar of deviation   :   0.00000100
    significance probability :   1.00000000  (gaussian statistics)
    status of this test      :   fail

Tests for series 0
  Testing quantity: LocalPotential
    reference mean value     : -30.94613082
    reference error bar      :   0.00000100
    computed  mean value     : -30.94606848
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00000300  (  3.00000000 sigma)
    deviation from reference :   0.00006234  ( 62.34100000 sigma)
    error bar of deviation   :   0.00000100
    significance probability :   1.00000000  (gaussian statistics)
    status of this test      :   fail

**Comment by jtkrogel** [comment]
A major difference here is that the kinetic and potential deviations are comparable in magnitude.

**Comment by jtkrogel** [comment]
There is also agreement to about 5 significant figures, while for LiH it is 3 for kinetic and 6 for potential.

**Comment by prckent** [comment]
@Hyeondeok-Shin Please can you commit this test so that we can do iterative improvements? The first step is for multiple compilers to agree at full precision on different machines. Interestingly the mixed precision results are very close here. Of course there is actually no guarantee that there aren't problems in either the mixed precision or double precision code, so each term in the Hamiltonian needs to be looked at carefully.

**Comment by jtkrogel** [comment]
Probably we should set pass tolerance for deterministic tests to something like 1e-5*LocalPotential for all energy terms.

**Comment by prckent** [comment]
@Hyeondeok-Shin Extra thoughts:

The diamond 2x1x1 adds a Jastrow to the mix as well as splines. We have a whole series of tests built on LiH (short-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj etc.) with no Jastrow that should be informative.

Regarding achievable accuracy,  clearly if we aim for the tests to work with use of single precision in significant parts of the calculation, full single precision is the best we can expect, or ~6-9 digits. The diamond 2x1x1 tests are not far off that already, with 5 digits of equivalency. Experimenting with zero timestep as Ye suggested would help. Specifying the electron positions (use sp so that they are in the same place in dp) could be a next step depending on the variation found.

**Comment by Hyeondeok-Shin** [comment]
@prckent Thank you very much for the comments and suggestions. I'll keep updating the test as suggested in here.

**Comment by prckent** [comment]
Fixed in https://github.com/QMCPACK/qmcpack/pull/1576
