### ISSUE TITLE
Mixed precision crash with multireference LCAO

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#138]
The Intel2017-Mixed-Release builds are *sometimes* crashing or hanging in the nightly tests, in both all-MPI and threaded versions. Suggests a bug. The non-mixed precision versions do not crash.

(Low priority)

**Comment by ye-luo** [comment]
The problem is in VMC not in Optimizer. Multi-reference LCAO is not compatiable with mixed precision. Probably will get fixed with SoA change.

**Comment by prckent** [comment]
Solution: Put in an error trap and abort. The code should never run in a known incompatible situation. There is a fair chance that someone will try mixedprecision multireference LCAO due to interest in molecular calculations.

**Comment by prckent** [comment]
I believe this was fixed in #46

**Comment by ye-luo** [comment]
This has not been fixed. I had a deep investigation to the problem two days ago. There was some divide by zero issue which I don't understand at the moment. It happens in the multi-determinant area.

**Comment by ye-luo** [comment]
numerics of multi-determinant is not robust with mixed precision. guarded this code path.
