### ISSUE TITLE
Deterministic diamond 2x1x1 tests fail with complex build

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1383]
Added yesterday in #1380 , these tests are failing with the complex build. The real builds appear to be reliable across multiple compilers and systems. All the Hamiltonian components from the complex build are slightly different from the reference data, suggesting a subtly different MC walk. I suggest investigating carefully since while the difference could be "real" it could also indicate a small mishandling of the wavefunction phase or accidental use of a lower precision function. Perhaps check/add diamond 1x1x1 gamma where there are no phase considerations?

**Comment by jtkrogel** [comment]
You could also try running real/complex side by side and just turning off parts of the wavefunction (i.e. with a Jastrow but no SD, etc).

**Comment by Hyeondeok-Shin** [comment]
Thanks for the comments. So far, tests are passing only without SD in the wavefunction. I'll keep updating the test in here.

**Comment by prckent** [comment]
Any luck with 1x1x1? i.e. When the phase is zero?

**Comment by Hyeondeok-Shin** [comment]
In 1x1x1, observables in real & cplx are not identical but they are closer to each other compared to 2x1x1. But KE is still failing with current tolerance.

i.e) local energy 2x1x1 vs. 1x1x1
2x1x1
Tests for series 0
  Testing quantity: LocalEnergy
    reference mean value     : -22.59701007
    reference error bar      :   0.00000100
    computed  mean value     : -22.59206540
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00000300  (  3.00000000 sigma)
    deviation from reference :   0.00494467  ( 4944.67200000 sigma)
    error bar of deviation   :   0.00000100
    significance probability :   1.00000000  (gaussian statistics)
    status of this test      :   fail

1x1x1
Tests for series 0
  Testing quantity: LocalEnergy
    reference mean value     : -10.46490731
    reference error bar      :   0.00000100
    computed  mean value     : -10.46490587
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00000300  (  3.00000000 sigma)
    deviation from reference :   0.00000144  (  1.44300000 sigma)
    error bar of deviation   :   0.00000100
    significance probability :   0.85097944  (gaussian statistics)
    status of this test      :   pass

Kinetic energy 2x1x1 vs. 1x1x1
2X1X1
Tests for series 0
  Testing quantity: Kinetic
    reference mean value     :  21.24055356
    reference error bar      :   0.00000100
    computed  mean value     :  21.24555614
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00000300  (  3.00000000 sigma)
    deviation from reference :   0.00500258  ( 5002.58400000 sigma)
    error bar of deviation   :   0.00000100
    significance probability :   1.00000000  (gaussian statistics)
    status of this test      :   fail

1x1x1
Tests for series 0
  Testing quantity: Kinetic
    reference mean value     :   8.11343201
    reference error bar      :   0.00000100
    computed  mean value     :   8.11343610
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00000300  (  3.00000000 sigma)
    deviation from reference :   0.00000409  (  4.08990000 sigma)
    error bar of deviation   :   0.00000100
    significance probability :   0.99995682  (gaussian statistics)
    status of this test      :   fail

**Comment by prckent** [comment]
Please can you commit the 1x1x1 tests? These are very close to being acceptable. Running them on more architectures might find some variation with e.g. maths library, optimization settings.

**Comment by prckent** [comment]
Fixed in https://github.com/QMCPACK/qmcpack/pull/1490
