### ISSUE TITLE
building issue due to git commit log

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#142]
Got the following issue.

/sandbox/opt/qmcpack-dev/src/qmc_common.cpp(98): error #55: too many arguments in invocation of macro "STR_EXPAND"
      std::cerr << " git last commit subject: " << QMCPACK_GIT_COMMIT_SUBJECT << std::endl;

src/git-rev.h

#define GIT_BRANCH_RAW LAPW
#define GIT_HASH_RAW eacc1b4f419d9bf494abe42e82b6dc9d91d67b34-dirty
#define GIT_COMMIT_LAST_CHANGED_RAW Thu Mar 2 17:42:10 2017 -0600
#define GIT_COMMIT_SUBJECT_RAW At the zone, evaluation with asymptotic calc.

**Comment by markdewing** [comment]
The issue with the comma in the subject line should have been addressed this commit:
https://github.com/QMCPACK/qmcpack/commit/1b3dc9e9aca15a5a6595922a428e4d1b25fd30a1

**Comment by ye-luo** [comment]
Got it. So it is after my last sync with github. Thank you Mark.
