### ISSUE TITLE
Cannot reproduce PySCF diamondC_Xx1x1-Gaussian-pp Workflow

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#1422]
For the tests/solids/diamondC_1x1x1-Gaussian-pp and tests/solids/diamondC_2x1x1-Gaussian-pp test problems, running the pyscf scripts provided in "dft-input" fails to generate a properly populated h5 file that convert4qmc can successfully use.  I should mention that I used the current dev branch of PySCF, and the current develop branch of QMCPACK.  The issue seems to be a crash in this line:  https://github.com/QMCPACK/qmcpack/blob/c1bc241d008d5c3ae281abb903d3c36615eb21fa/src/QMCTools/PyscfToQmcpack.py#L523

Is there a reason that mo_coeff should have higher dimensionality than (N_mo, N_ao) ?  If not, the fix might be as easy as changing and len(mo_coeff[0]) and len(mo_coeff[0][0]) to len(mo_coeff) and len(mo_coeff[0]) respectively.  

Also, tests/solids/diamondC_1x1x1-Gaussian-pp/dft-inputs/e_scf differs by ~0.4Ha from the output scf value in diamondC_1x1x1_pp.out .  This feels like a copy paste bug when this was committed, but it would be nice to verify which number is right.

**Comment by prckent** [comment]
Thanks Ray. @anbenali While the remaining 3.7.0 milestone tasks are somewhat aspirational, this is an important one to try to fix.

**Comment by prckent** [comment]
Any progress on this?

**Comment by prckent** [comment]
Should this be assigned to the v3.8.0 milestone? i.e. Will definitely be fixed prior to the release?

**Comment by prckent** [comment]
Can the problem still be reproduced?

**Comment by anbenali** [comment]
I thought this was fixed??! I am sure I updated a fix.. if not I will do it
tomorrow with the python 3

**Comment by prckent** [comment]
Good news if it is already fixed.

**Comment by ye-luo** [comment]
Seems like fixed already. Open a new issue if this appears again.
