### ISSUE TITLE
Why is TOKEN= printed in the output along with the full source path?

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#145]
This looks like some legacy debugging output, but is printed by the production application. 

Is there any reason to preserve it?
Does anyone know the original motivation for it?

**Comment by prckent** [comment]
e.g. 
TOKEN=0 createSPOSetFromXML /scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp 48
TOKEN=1 ReadOrbitalInfo /scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp 37
TOKEN=3 CheckLattice /scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp 102
...

**Comment by ye-luo** [comment]
No need to print it for end user but very helpful for developers to investigate problems.

**Comment by prckent** [comment]
Because it functions as a stack trace?

**Comment by ye-luo** [comment]
Kind of. I tells me that how far the building of spline is going.

**Comment by jtkrogel** [comment]
So, should we optionally enable writes like these via an xml tag in the input ("debug" or similar) or a compile time flag?

Cleaning up the log output in general is a bigger project.

**Comment by prckent** [comment]
We can tie this in with the verbosity level now suggested in  #35 as part of the cleanup. Perhaps low/high/debug.

**Comment by prckent** [comment]
I'll close this. Decision is to have debugging text of this ilk printed only when debug verbosity is selected.
