### ISSUE TITLE
MPC tests needed for short and long diamond 1x1x1

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1454]
Will close #1449 when completed.

(Creating this issue to capture the comment in #1453)

**Comment by prckent** [comment]
@Hyeondeok-Shin any luck with creating the reference data?

**Comment by Hyeondeok-Shin** [comment]
@prckent Reference data for MPC were created and they are now in test in my side before making a PR. The PR will be made in late today or early tomorrow.

**Comment by prckent** [comment]
Closed by #1470
