### ISSUE TITLE
Relocate command line flags to XML input

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#146]
Currently the code accepts several command line flags (e.g. --dryrun, --save_wfs, --async_swap, --vacuum, --noprint) that should be placed in the input file.  It is desirable for the input file to be capable of reflecting the totality of information inputted to the code to give the user a uniform interface to control QMCPACK's behavior, and because input files are more easily saved and disseminated.

**Comment by ye-luo** [comment]
I will replace --save_wfs and put it in the input file.

**Comment by prckent** [comment]
Other than --dryrun, I agree. 

These flags should go in different places though. save_wfs is clearly spline related. async_swap is DMC driver related, but we need to avoid duplicating the input handling in the plethora of DMC drivers. 

Note that none of these flags are currently tested. save_wfs and vacuum definitely should be.

**Comment by markdewing** [comment]
I have opinions on which items should be command line arguments and which should go into the input file, but the harder part is trying to make this intuitive sense more concrete.
Options like 'help' and 'version' should be command line arguments, and don't have much value as input file options.

Much this comes down to usage models in different environments and which way best to support users and minimize human error. I spend a lot of time running directly from the command line, but that's for development. Production use (and ramping to production use) uses more batch scripts and Nexus.

One point with usability - dryrun could go in the input file, but seems like a potential trap - it's too easy to make an input file that doesn't perform the run.

As to reproducibility, writing out the options used in the output file does provide a record of what was used, but may make it harder to correctly reproduce (need to remember to add the command line switches).


Another design goal is separation of concerns - the problem should be specified by the input file, but not more.  Output control (debug, noprint, maybe dryrun, etc) seems like it should not be part of the problem specification.  Although this could be addressed by a separate section in the input file.

Nothing precludes having both a command line option and XML file input option (though these should be limited to prevent confusion, and multiple paths to the same result can be a source of bugs.).  The timer control flags might fall into this category.

Moving some of these to the XML input file may require some thought on parsing the XML (see #147).

There are two sources of command line flags - qmc_common.cpp and QMCApp/qmcapp.cpp.  This should be changed so the command line is processed in one place.

**Comment by jtkrogel** [comment]
I would favor allowing all command line options in the input file (but not necessarily eliminating all command line ones).  Having a single (global?) class (QMCCommon/QMCControl?) handle both a new xml input block and the command line processing could avoid duplication/bug concerns.  

Additionally if this class inserts the command line options into the internal (libxml) datastructure, then all command line inputs would be reproduced in the runnable *.cont.xml files, allowing the full run to be reproduced w/o having to remember the command line flags.

**Comment by ye-luo** [comment]
--save_wfs, --async_swap, --vacuum are all gone.

**Comment by ye-luo** [comment]
The residual ones will remain as command line arguments.
