### ISSUE TITLE
Failure of tests in Titan with either CPU or GPU

### ISSUE THREAD

**Issue by zenandrea** [QMCPACK/qmcpack#1467]
Hi,
I have performed the ctests ( -R 'short|converter|unit' ) on titan for qmcpack-3.6.0,
compiled as indicated in the manual and for the cases of:
1) cpu_real
2) cpu_real_SoA
3) gpu_real

All of them pass the tests "converter-*" and most of the "deterministic-*"
The only failure is in "deterministic-unit_test_wavefunction" in the case 2.

Concerning the tests "short-*", there are several failed tests.
Only in case 3 the tests finish completely in the walltime of 2 hours (max possible), and there I see 45 failed tests.
In cases 1 and 2 there are several failed tests.

I have copied the script file that I used to run the tests and the output in this link:
https://www.dropbox.com/s/25jb3tmjub83zeu/TESTS_RESULTS.tgz?dl=0

Do you have suggestions about that?
Are older versions of qmcpack doing better with respect to these tests?
I am wondering if I can use at least the cpu_real code for production calculations.

**Comment by prckent** [comment]
Frankly this sounds about right for the current state of the testing system. You'll see from other issues here on GitHub with the testing label and the nightly test results ( https://cdash.qmcpack.org ) that it is not possible for all these tests to pass currently - we have so many tests and build configurations that at least some of the short tests will fail stochastically. Additionally some of the tests run for unimplemented features. 

I don't recall the specific situation of cpu_real_soa and the wavefunction unit test in v3.6.0. It is working in all build configurations with the develop version, see. e.g. https://cdash.qmcpack.org/CDash/viewTest.php?onlypassed&buildid=49029 . Generally, newer versions of the code are better and we can prove this because the testing is more complete/reliable.

We have an ongoing effort to make deterministic integration tests *with good coverage* and have them work everywhere. This is a large amount of work.

If you paste your test results here we could comment further. You should be able to use all these build types in production. Most of the GPU failures should be from non-implemented features.

**Comment by prckent** [comment]
I followed your link and checked the results. There is nothing to worry about in my opinion
```
grep '/[0-9].*Failed' build_titan*/out_ctest
```

(Slow) SoA cpu build:
```
build_titan_cpu_real/out_ctest: 15/142 Test #223: short-c_no-hf_vmc-4-4 ...........................................***Failed    4.54 sec
```
Numerical orbital check. You are not using this


(Faster) AoS cpu build:
```
build_titan_cpu_real_SoA/out_ctest: 6/18 Test #11: deterministic-unit_test_wavefunction ....***Failed    4.31 sec
build_titan_cpu_real_SoA/out_ctest: 12/183 Test #197: short-H2-orb-opt-16-1 ...........................................***Failed    4.49 sec
build_titan_cpu_real_SoA/out_ctest: 13/183 Test #199: short-H2-FDLR-16-1 ..............................................***Failed    6.53 sec
build_titan_cpu_real_SoA/out_ctest: 17/183 Test #217: short-H4-orb-opt-16-1 ...........................................***Failed    4.71 sec
build_titan_cpu_real_SoA/out_ctest: 18/183 Test #219: short-H4-orb-opt-dmc-16-1 .......................................***Failed    6.53 sec
build_titan_cpu_real_SoA/out_ctest: 19/183 Test #221: short-H4-orb-opt-dmc-1-16 .......................................***Failed    6.48 sec
build_titan_cpu_real_SoA/out_ctest: 20/183 Test #223: short-H4-FDLR-16-1 ..............................................***Failed    6.76 sec
build_titan_cpu_real_SoA/out_ctest: 35/183 Test #115: short-C2_pp-msdj_vmc-1-16-variance ..............................***Failed    0.11 sec
build_titan_cpu_real_SoA/out_ctest: 69/183 Test #200: short-H2-FDLR-16-1-totenergy ....................................***Failed    0.21 sec
build_titan_cpu_real_SoA/out_ctest: 71/183 Test #198: short-H2-orb-opt-16-1-totenergy .................................***Failed    0.22 sec
build_titan_cpu_real_SoA/out_ctest: 72/183 Test #210: short-H4-opt-cslinear-rescale-16-1-totenergy ....................***Failed    0.05 sec
build_titan_cpu_real_SoA/out_ctest: 75/183 Test #222: short-H4-orb-opt-dmc-1-16-totenergy .............................***Failed    0.21 sec
build_titan_cpu_real_SoA/out_ctest: 76/183 Test #220: short-H4-orb-opt-dmc-16-1-totenergy .............................***Failed    0.21 sec
build_titan_cpu_real_SoA/out_ctest: 77/183 Test #218: short-H4-orb-opt-16-1-totenergy .................................***Failed    0.22 sec
build_titan_cpu_real_SoA/out_ctest: 78/183 Test #224: short-H4-FDLR-16-1-totenergy ....................................***Failed    0.05 sec
build_titan_cpu_real_SoA/out_ctest: 79/183 Test #230: short-c_no-hf_vmc-1-16-totenergy ................................***Failed    0.25 sec
build_titan_cpu_real_SoA/out_ctest: 80/183 Test #232: short-c_no-hf_vmc-4-4-totenergy .................................***Failed    0.24 sec
build_titan_cpu_real_SoA/out_ctest: 81/183 Test #234: short-c_no-sj_dmc-1-16-totenergy ................................***Failed    0.05 sec
build_titan_cpu_real_SoA/out_ctest: 82/183 Test #235: short-c_no-sj_dmc-1-16-variance .................................***Failed    0.14 sec
build_titan_cpu_real_SoA/out_ctest: 83/183 Test #236: short-c_no-sj_dmc-1-16-2-totenergy ..............................***Failed    0.23 sec
build_titan_cpu_real_SoA/out_ctest: 85/183 Test #237: short-c_no-sj_dmc-1-16-2-variance ...............................***Failed    0.31 sec
build_titan_cpu_real_SoA/out_ctest: 88/183 Test #333: short-bccH_3x3x3_ae-not_orth-deriv-1-1-check ....................***Failed    0.21 sec
```
Failure in orbital optimization, FDLR wavefunciton, numerical orbitals, and a derivatives check you are not using.

CUDA GPU:
```
build_titan_gpu_real/out_ctest: 1/49 Test  #51: short-LiH_solid_1x1x1_hybridrep_pp-x-vmc_hf_noj-1-16 ............***Failed    5.52 sec
build_titan_gpu_real/out_ctest: 3/49 Test  #73: short-bccH_3x3x3_ae-not_orth-deriv-1-1 ..........................***Failed   37.26 sec
build_titan_gpu_real/out_ctest: 4/49 Test  #79: short-bccH_2x2x2_ae-gamma-deriv-1-1 .............................***Failed    7.21 sec
build_titan_gpu_real/out_ctest: 5/49 Test  #52: short-LiH_solid_1x1x1_hybridrep_pp-x-vmc_hf_noj-1-16-kinetic ....***Failed    0.21 sec
build_titan_gpu_real/out_ctest: 6/49 Test  #53: short-LiH_solid_1x1x1_hybridrep_pp-x-vmc_hf_noj-1-16-samples ....***Failed    0.04 sec
build_titan_gpu_real/out_ctest: 7/49 Test  #54: short-LiH_solid_1x1x1_hybridrep_pp-x-vmc_hf_noj-1-16-localecp ...***Failed    0.04 sec
build_titan_gpu_real/out_ctest: 9/49 Test  #74: short-bccH_3x3x3_ae-not_orth-deriv-1-1-check ....................***Failed    0.21 sec
build_titan_gpu_real/out_ctest:10/49 Test  #80: short-bccH_2x2x2_ae-gamma-deriv-1-1-check .......................***Failed    0.21 sec
build_titan_gpu_real/out_ctest:11/49 Test  #77: short-bccH_2x2x2_ae-deriv-1-1 ...................................***Failed   52.98 sec
build_titan_gpu_real/out_ctest:12/49 Test  #78: short-bccH_2x2x2_ae-deriv-1-1-check .............................***Failed    0.03 sec
build_titan_gpu_real/out_ctest:13/49 Test  #67: short-bccH_3x3x3_ae-deriv-1-1 ...................................***Failed   61.26 sec
build_titan_gpu_real/out_ctest:14/49 Test  #68: short-bccH_3x3x3_ae-deriv-1-1-check .............................***Failed    0.04 sec
build_titan_gpu_real/out_ctest:15/49 Test  #69: short-bccH_3x3x3_ae-grad_lap-1-1 ................................***Failed   69.21 sec
build_titan_gpu_real/out_ctest:16/49 Test  #70: short-bccH_3x3x3_ae-grad_lap-1-1-check ..........................***Failed    0.21 sec
build_titan_gpu_real/out_ctest:17/49 Test  #75: short-bccH_2x2x2_ae-grad_lap-1-1 ................................***Failed   77.41 sec
build_titan_gpu_real/out_ctest:18/49 Test  #76: short-bccH_2x2x2_ae-grad_lap-1-1-check ..........................***Failed    0.09 sec
build_titan_gpu_real/out_ctest:19/49 Test  #71: short-bccH_3x3x3_ae-gamma-deriv-1-1 .............................***Failed   85.79 sec
build_titan_gpu_real/out_ctest:20/49 Test #107: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16 ..................***Failed    7.62 sec
build_titan_gpu_real/out_ctest:21/49 Test #125: short-diamondC_1x1x1_pp-vmc_sdj_kspace-1-16 .....................***Failed    9.32 sec
build_titan_gpu_real/out_ctest:22/49 Test #128: short-diamondC_1x1x1_pp-vmc_sdj_kspace-4-4 ......................***Failed    7.77 sec
build_titan_gpu_real/out_ctest:23/49 Test #180: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16 ..................***Failed    7.74 sec
build_titan_gpu_real/out_ctest:25/49 Test #211: short-monoO_1x1x1_pp-vmc_sdj3-1-16 ..............................***Failed   14.13 sec
build_titan_gpu_real/out_ctest:26/49 Test #109: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-totenergy ........***Failed    0.07 sec
build_titan_gpu_real/out_ctest:27/49 Test #110: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-eeenergy .........***Failed    0.06 sec
build_titan_gpu_real/out_ctest:28/49 Test #112: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-potential ........***Failed    0.06 sec
build_titan_gpu_real/out_ctest:29/49 Test #111: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-samples ..........***Failed    0.07 sec
build_titan_gpu_real/out_ctest:30/49 Test  #72: short-bccH_3x3x3_ae-gamma-deriv-1-1-check .......................***Failed    0.10 sec
build_titan_gpu_real/out_ctest:31/49 Test #108: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-kinetic ..........***Failed    0.09 sec
build_titan_gpu_real/out_ctest:32/49 Test #126: short-diamondC_1x1x1_pp-vmc_sdj_kspace-1-16-totenergy ...........***Failed    0.05 sec
build_titan_gpu_real/out_ctest:33/49 Test #113: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-ionion ...........***Failed    0.07 sec
build_titan_gpu_real/out_ctest:34/49 Test #129: short-diamondC_1x1x1_pp-vmc_sdj_kspace-4-4-totenergy ............***Failed    0.05 sec
build_titan_gpu_real/out_ctest:35/49 Test #127: short-diamondC_1x1x1_pp-vmc_sdj_kspace-1-16-variance ............***Failed    0.06 sec
build_titan_gpu_real/out_ctest:36/49 Test #114: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-localecp .........***Failed    0.08 sec
build_titan_gpu_real/out_ctest:37/49 Test #115: short-diamondC_1x1x1_hybridrep_pp-vmc_sdj-1-16-nonlocalecp ......***Failed    0.08 sec
build_titan_gpu_real/out_ctest:38/49 Test #130: short-diamondC_1x1x1_pp-vmc_sdj_kspace-4-4-variance .............***Failed    0.06 sec
build_titan_gpu_real/out_ctest:39/49 Test #183: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-eeenergy .........***Failed    0.08 sec
build_titan_gpu_real/out_ctest:40/49 Test #184: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-samples ..........***Failed    0.07 sec
build_titan_gpu_real/out_ctest:41/49 Test #185: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-potential ........***Failed    0.07 sec
build_titan_gpu_real/out_ctest:42/49 Test #182: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-totenergy ........***Failed    0.09 sec
build_titan_gpu_real/out_ctest:43/49 Test #181: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-kinetic ..........***Failed    0.10 sec
build_titan_gpu_real/out_ctest:44/49 Test #188: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-nonlocalecp ......***Failed    0.07 sec
build_titan_gpu_real/out_ctest:45/49 Test #212: short-monoO_1x1x1_pp-vmc_sdj3-1-16-totenergy ....................***Failed    0.08 sec
build_titan_gpu_real/out_ctest:46/49 Test #213: short-monoO_1x1x1_pp-vmc_sdj3-1-16-samples ......................***Failed    0.07 sec
build_titan_gpu_real/out_ctest:47/49 Test #186: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-ionion ...........***Failed    0.11 sec
build_titan_gpu_real/out_ctest:49/49 Test #187: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16-localecp .........***Failed    0.10 sec
```
These are all unimplemented features in v3.6.0 and still unimplemented: backflow related, 3-body jastrow (j3), k-space jastrow, hybrid representation (this would be very useful for GPUs but is not implemented).

**Comment by grahamlopez** [comment]
We could consider starting to use things like [!mayfail], [!shouldfail], etc.

https://github.com/catchorg/Catch2/blob/master/docs/test-cases-and-sections.md#special-tags

**Comment by prckent** [comment]
This is what the test labeling effort is/was meant to address, but there has not been much progress recently due to bandwidth issues.

*All* our catch2 tests (unit tests) should pass 100% reliably, and nearly do. Yesterday we had only two failures over all build combinations: the utilities unit test fails with PGI18 (only), and a still new AFQMC matrix test is failing (https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=49062 , @fdmalone ).

**Comment by markdewing** [comment]
I reproduced the CPU/SoA wavefunction unit test failure on Titan.  It seems to be some interaction between the unit tests - if I run them one at a time they pass.

**Comment by zenandrea** [comment]
Many thanks for the feedback.
Can I ask a few of other questions (mostly because I am not familiar with how ctest works):

1) Is there a clever way to do all the tests in titan despite having a max walltime of 2 hours? 
(I mean, maybe they can be broken in fragments, or I can continue from the test where they stopped?)

2) The command in my job-script is
ctest -D QMC_CUDA=1 -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=CC \
      -S $PWD/../CMake/ctest_script.cmake,release -R 'short|converter|unit' \
      -VV --timeout 7200 >& out_ctest
which I wrote by being inspired by the tests/test_automation/nightly_ornl_olcf_titan_gpu.job.
I wonder if I really need to execute $PWD/../CMake/ctest_script.cmake, and so to rebuilt qmcpack,
instead of doing the tests straight away with what I compiled myself?
Moreover, I have notices that the outcomes of the tests are different (more failures, e.g. in some deterministic tests) if I instead use the command:
ctest -R 'short|converter|unit' \
      -VV --timeout 7200 \
      >& out_ctest_nobuild
Why is that happening?

3) Is there any failed test in the CUDA gpu_real that is telling me about the issue "DMC LocalECP incorrect in GPU code" #1440.

**Comment by prckent** [comment]
1. Please run ctest as described in the manual and do not build the code in the job on titan. Once you have built the code (cmake; make) you can invoke tests by running ctest. e.g. ctest -R unit in a job (only). The way you are invoking ctest right now will rebuild the code during the job. This performs very poorly on titan for various Cray and OLCF reasons, leaving very little time to actually run tests. 
2. See 1. These should be equivalent if you have equivalent settings. You can run any test by name. ctest -R short-important-test.
3. "Is there any failed test in the CUDA gpu_real that is telling me about the issue "DMC LocalECP incorrect in GPU code" #1440. No. If we had a test that conveniently reproduces the problem we would have fixed it. Currently we are unable to reproduce the problem on a linux workstation with a Kepler card, so it might be related to titan somehow, or it could just be that we haven't been able to tickle the problem yet. Note that carbon diamond runs correctly or at least the problem is somehow hidden.

**Comment by ye-luo** [comment]
@zenandrea Make sure you specify -j 8 or -j16 with ctest to use all the cores for testing.

**Comment by zenandrea** [comment]
Dear @prckent,

concerning 1 and 2, I was expecting that I did not need to rebuilt, but I was obtaining many failures (also in the deterministic tests on the version AoS CPU version). That is why I ended up with rebuilding.
I have just discovered what was my mistake: I was not loading the cmake3 modulus into the running script when I was not rebuilding, but the default ctest version was 2.6-patch 2.
Now I am running without rebuilding but with cmake3 and I obtain the same results.

Concerning 3: Do anybody reproduce my issue on titan? Or am I the only one having produced this issue?

**Comment by prckent** [comment]
Re:3. We tried on a workstation first since it is dramatically easier to work with. We suspected a simple CUDA bug, and this should have showed up there. Will try titan next.

**Comment by prckent** [comment]
Good to hear about the cmake module solution.

**Comment by fdmalone** [comment]
@prckent  is it possible to find the build configuration somewhere?

**Comment by ye-luo** [comment]
@fdmalone Titan build configuration is listed both in the manual and config/build_olcf_titan.sh

**Comment by prckent** [comment]
Quick note here that I have reproduced @zenandrea 's bug. Will comment further in #1440

**Comment by zenandrea** [comment]
Dear @prckent,
I noticed a pair of aspects that I guess it is worth sharing (although maybe they were clear to users familiar with cmake).

1) following your suggestion I run tests without rebuilding during the job. I built the tests on the $HOMEPROJ directory in titan, then I copied the all qmcpack-3.6.0 directory into the $PROJWORK directory, and ran the tests. I had a lot of failed tests, and from the verbose output I got that ctest was still referencing to the $HOMEPROJ directory where the building was done. I guessed that this was the problem. Thus I rebuilt the code on the  $PROJWORK (build outside the job but from terminal, with the same script I used in $HOMEPROJ), and that seems to have solved the problem, as most of the tests passed.
I wonder if there is a better way to do that, which possibly does not require to rebuild on $PROJWORK?
Moreover, I think it would be good if this point of compiling the code in the scratch directory in order to perform the tests is mentioned in the manual.

2)  I built the 6 possible ways in titan: (real,complex)x(AoS,SoA,gpu), and performed the deterministic, converter and short (-LE unstable) tests. (Well, I did not test the build_titan_gpu_comp yet)
The max 2 hours walltime was not enough to allow all tests to finish.
The manual tells that the short tests should take "around 1 hour depending on the platform" on a 16 core machine.
Here it seems that more than 2 hours would be needed. Is there something wrong in the timing?
These are the last short test performed for each built:
```
build_titan_cpu_real/out_ctest_short: 76/221 Test #218: short-H4-opt-OneShiftOnly-16-1-totenergy ..........................   Passed    0.07 sec
build_titan_cpu_real_SoA/out_ctest_short: 62/242 Test #206: short-H4-opt-linear-linemin-16-1-totenergy ........................   Passed    0.20 sec
build_titan_gpu_real/out_ctest_short:95/95 Test #210: short-monoO_1x1x1_pp-vmc_sdj-1-16-samples .........................   Passed    0.10 sec
build_titan_cpu_comp/out_ctest_short: 59/151 Test #115: short-LiH_solid_1x1x1_pp-arb-dmcnl-hf_noj-1-16-totenergy ..........   Passed    0.12 sec
build_titan_cpu_comp_SoA/out_ctest_short: 57/169 Test #115: short-LiH_solid_1x1x1_pp-gamma-dmcnl-hf_noj-1-16-totenergy ........   Passed    0.15 sec
```
Anyway, there are only 3 tests failed, and two are probably for statistical reasons (slightly out from 3 sigma). 
But there is one that fails that worries me: 
```
build_titan_cpu_real_SoA/out_ctest_deterministic:11/18 Test #11: deterministic-unit_test_wavefunction ....***Failed    7.41 sec
```
This is the output I get
```
11: Reading cusp info from : ../CuspCorrection/updet.cuspInfo.xml
11: I/O warning : failed to load external entity "../CuspCorrection/updet.cuspInfo.xml"
11: Could not find precomputed cusp data for spo set: updet
11: Recalculating data.
11: Working on Center 0
11: 
11: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11: ESC[0;37mtest_wavefunction is a Catch v2.4.2 host application.
11: Run with -? for options
11: 
11: ESC[0m-------------------------------------------------------------------------------
11: ESC[0mReadMolecularOrbital GTO He
11: ESC[0mESC[0m  He, transform orbitals to grid: F
11: ESC[0m-------------------------------------------------------------------------------
11: ESC[0;37m/lustre/atlas2/cph005/proj-shared/zen/Xctest/qmcpack-3.6.0/src/QMCWaveFunctions/tests/test_MO.cpp:39
11: ESC[0m...............................................................................
11: 
11: ESC[0;37m/lustre/atlas2/cph005/proj-shared/zen/Xctest/qmcpack-3.6.0/src/QMCWaveFunctions/tests/test_MO.cpp:39: ESC[0mESC[1;31mFAILED:
11: ESC[0mESC[0;36m  {Unknown expression after the reported line}
11: ESC[0mdue to a fatal error condition:
11:   SIGSEGV - Segmentation violation signal
11: 
11: ESC[1;31m===========ESC[0mESC[1;33mESC[0mESC[0;32m====================================================================ESC[0m
11: test cases:   7ESC[0;37m | ESC[0mESC[0;32m  6 passedESC[0mESC[0;37m | ESC[0mESC[1;31m1 failedESC[0m
11: assertions: 328ESC[0;37m | ESC[0mESC[0;32m327 passedESC[0mESC[0;37m | ESC[0mESC[1;31m1 failedESC[0m
11: 
11: _pmiu_daemon(SIGCHLD): [NID 14289] [c13-7c0s7n3] [Tue Mar 26 13:52:15 2019] PE RANK 0 exit signal Segmentation fault
11: Application 20080901 exit codes: 139
11: Application 20080901 resources: utime ~0s, stime ~0s, Rss ~20736, inblocks ~11188, outblocks ~22858
11/18 Test #11: deterministic-unit_test_wavefunction ....***Failed    7.41 sec
```
Should I be concerned about that?

**Comment by zenandrea** [comment]
I am performing also the tests for qmcpack-3.6.0 on eos, for the four possible build:
```
build_eos_cpu_comp
build_eos_cpu_comp_SoA
build_eos_cpu_real
build_eos_cpu_real_SoA
```
First thing to mention: 
the script `config/build_olcf_eos.sh` is not working, 
as the default (and latest available) module version of boost is `boost/1.60.0`.
Thus, I dowloaded and installed boost version 1.69.0, and defined accordingly BOOST_ROOT.
Building the code in this ways works and most of the tests pass.

An interesting thing is that the deterministic test
`deterministic-unit_test_wavefunction`
fails within `build_eos_cpu_real_SoA`, 
while it pass for 
`build_eos_cpu_comp`, `build_eos_cpu_comp_SoA`, and `build_eos_cpu_real`.
(Similarly of what seen in Titan).

This is how it fails:
```
11:   Distance table for dissimilar particles (A-B):
11:     source: ion0  target: e
11:     Using structure-of-arrays (SoA) data layout
11:     Distance computations use open boundary conditions in 3D.
11: 
11: Reuse SPOSetBuilder "LCAOBSet" type MolecularOrbital
11: Reusing previously loaded BasisSet.
11: 
11: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11: ESC[0;37mtest_wavefunction is a Catch v2.4.2 host application.
11: Run with -? for options
11: 
11: ESC[0m-------------------------------------------------------------------------------
11: ESC[0mReadMolecularOrbital GTO He
11: ESC[0mESC[0m  He, transform orbitals to grid: F
11: ESC[0m-------------------------------------------------------------------------------
11: ESC[0;37m/lustre/atlas2/cph005/proj-shared/zen/Xctest/qmcpack-3.6.0/src/QMCWaveFunctions/tests/test_MO.cpp:39
11: ESC[0m...............................................................................
11: 
11: ESC[0;37m/lustre/atlas2/cph005/proj-shared/zen/Xctest/qmcpack-3.6.0/src/QMCWaveFunctions/tests/test_MO.cpp:39: ESC[0mESC[1;31mFAILED:
11: ESC[0mESC[0;36m  {Unknown expression after the reported line}
11: ESC[0mdue to a fatal error condition:
11:   SIGSEGV - Segmentation violation signal
11: 
11: ESC[1;31m===========ESC[0mESC[1;33mESC[0mESC[0;32m====================================================================ESC[0m
11: test cases:   7ESC[0;37m | ESC[0mESC[0;32m  6 passedESC[0mESC[0;37m | ESC[0mESC[1;31m1 failedESC[0m
11: assertions: 328ESC[0;37m | ESC[0mESC[0;32m327 passedESC[0mESC[0;37m | ESC[0mESC[1;31m1 failedESC[0m
11: 
11: _pmiu_daemon(SIGCHLD): [NID 00218] [c1-0c0s6n2] [Wed Mar 27 07:40:23 2019] PE RANK 0 exit signal Segmentation fault
11: Application 4083763 exit codes: 139
11: Application 4083763 resources: utime ~0s, stime ~0s, Rss ~26224, inblocks ~9979, outblocks ~22620
11/18 Test #11: deterministic-unit_test_wavefunction ....***Failed    5.84 sec
```

**Comment by markdewing** [comment]
@zenandrea about question 1 - the tests are built around CMake/CTest, and as you found out, these do not work right when the build directory is moved.   It might be possible to make tests that can be moved, but that would likely require moving away from CTest.

I usually leave the source directory in $HOME, create a build directory in $PROJWORK, and build there with -DQMC_SYMLINK_TEST_FILES=FALSE (by default some of the test files are symlinked to save space, but that doesn't work well at OLCF)

**Comment by markdewing** [comment]
I have found the cause of the wavefunction unit test failure - one of the tests does not clean up the wavefunction properly at the end of the test.  This is purely a unit test issue and does not affect the main code.

If you want to apply the change to the code to get to passing unit tests, the diff is
```
--- a/src/QMCWaveFunctions/tests/test_soa_cusp_corr.cpp
+++ b/src/QMCWaveFunctions/tests/test_soa_cusp_corr.cpp
@@ -574,6 +574,8 @@ TEST_CASE("Ethanol MO with cusp", "[wavefunction]")
   REQUIRE(all_grad[0][11][1] == Approx(0.9883840215));
   REQUIRE(all_grad[0][11][2] == Approx(1.7863218842));
   REQUIRE(all_lap[0][11] == Approx(-33.5202249813));
+
+  SPOSetBuilderFactory::clear();
 }
```

**Comment by zenandrea** [comment]
> I usually leave the source directory in $HOME, create a build directory in $PROJWORK, and build there with -DQMC_SYMLINK_TEST_FILES=FALSE (by default some of the test files are symlinked to save space, but that doesn't work well at OLCF)

@markdewing thanks for the suggestion.
I was indeed rebuilding everything using your suggestion.
However, I faces another problem: the qmcpack directory became huge and I finished my quota in $PROJWORK.
I see that the directory `tests` became huge (16GB before crashing my building because quota was reached).
I guess this is a consequence of `-DQMC_SYMLINK_TEST_FILES=FALSE`. Am I correct?

**Comment by zenandrea** [comment]
@markdewing I was also using this other flag 
`-D QE_BIN=/ccs/proj/cph005/QMCPACK/qmcpack-3.6.0/external_codes/quantum_espresso/qe-6.3_eos/bin` 
which could be involved in this issue!

**Comment by markdewing** [comment]
The QMC_DATA flag could also be an issue if you are using it - it points to input files for the NiO performance tests.    If you are using it, dropping it will save space.
The cause of the issue depends on which stage uses the space.  The flag to turn symlinks off will use space copying files during the configuration step.  The QE_BIN option causes the QE converter tests to run, and the intermediate wavefunction files will be created when these tests are run.

**Comment by ye-luo** [comment]
Titan is decommissioned.
