### ISSUE TITLE
Real and complex disagree in deterministic test

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1473]
Currently, the deterministic test reference values are generated from the real code and the complex code failed. I did an experiment by rotating the phase of the orbital. The real code do change values but the complex code doesn't. It is suspicious to me that there might be a bug in the real code.

**Comment by prckent** [comment]
Which tests? Please be as specific as possible.

**Comment by ye-luo** [comment]
Deterministic integration tests are not labelled correctly as deterministic. It is in the nightly category now.
https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=49206

**Comment by prckent** [comment]
I think what you are seeing is simply that these tests don't work yet. They are developmental and not production unfortunately. Fixing this needs real effort to be spent understanding the difference and then fixing them, not simply increasing the tolerance as some have suggested. Whikei would like to be wrong I suspect there is a subtle bug in at least QMCPACK's periodic spline handling.

**Comment by prckent** [comment]
@jtkrogel What is the procedure for assigning the correct label to these tests?

**Comment by jtkrogel** [comment]
I will label them over the next couple of days.  The labeling script needs a small update for this (originally meant to add descriptive labels to failure cases of statistical tests, now used for general labels).  

I will post instructions for adding tests to the deterministic category as well as for adding new labels in the future.

**Comment by jtkrogel** [comment]
I assume we just want pattern based labeling in this case (tests with names starting with "deterministic" are labeled as such) so we don't have to update any internal lists.

**Comment by prckent** [comment]
Pattern match would be simplest here and save work in future.

**Comment by jtkrogel** [comment]
See #1483.  Any deterministic tests added in the future will be labeled automatically.

If new labels are desired later on, the test labeling script (`qmcpack/tests/scripts/test_labels.py`) can be easily updated in the following way.  

To add a labels for a new fancy test type, you can pattern match based on the test name as follows:
```
    if test.startswith('deterministic'):
        labels.append('deterministic')
    #end if
    if 'fancy_new_test' in test:
        labels.append('fancy')
        labels.append('new')
    #end if
```
