### ISSUE TITLE
Test failure of deterministic-unit_test_afqmc_matrix

### ISSUE THREAD

**Issue by fdmalone** [QMCPACK/qmcpack#1475]
Opening an issue for the test failure noted in #1467. The test fails with gcc/8.2.0 on oxygen and I can reproduce with gcc/8.1.0 locally. The copy assignment on line 222 of AFQMC/Matrix/tests/test_csr_matrix.cpp seems to be causing the code to crash. Potentially a c++17 issue. Could you take a look @correaa

**Comment by correaa** [comment]
Are csr matrices being used now? I will be glad to work on it, but didn't
maintained in a while because I was told it is not a priority.

**Comment by fdmalone** [comment]
The sparse code isn't the focus right now, but ideally the unit tests should pass always.

**Comment by prckent** [comment]
Yes, we would like to get to a point where the unit tests are always passing on all platforms for all builds.

**Comment by prckent** [comment]
Has there been any progress on this? This test is still broken. We can not have deterministic tests failing since they are e.g. an install criterion. 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/13683814/58181515-eff1d080-7c79-11e9-92b3-eb448c385561.png">
