### ISSUE TITLE
Need CI for ENABLE_CUDA

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1499]
We need a third CI configuration to test ENABLE_CUDA. It is basically replace QMC_CUDA with ENABLE_CUDA.

**Comment by prckent** [comment]
I suggest we get this working in the nightlies ahead of the CI

**Comment by fdmalone** [comment]
We also should enable afqmc with ENABLE_CUDA for complex and mixed precision builds.

**Comment by prckent** [comment]
@fdmalone Is there a preferred config? e.g. clang+cuda+mkl?

**Comment by fdmalone** [comment]
gcc+cuda. This is what is used for CI at the moment right? For Nightlies clang appears to be used as well, but a number of afqmc tests are failing currently due to file name changes. It's probably safer to leave afqmc out of it until after the release.

**Comment by ye-luo** [comment]
I checked ENABLE_CUDA + BUILD_AFQMC + QMC_COMPLEX both full precision and mixed precision pass all the unit tests.
