### ISSUE TITLE
CMakeLists.txt doesn't add MPI include and link flags if default compiler is c++ instead of mpicxx

### ISSUE THREAD

**Issue by dcyang** [QMCPACK/qmcpack#150]
I noticed that CMake calls its stock FindMPI.cmake but doesn't automatically append `MPI_CXX_INCLUDE_PATH` to flags.make and `MPI_CXX_LIBRARIES` to link.txt, if `ENV{CXX}` is set to g++ or icpc (or any other C++ compiler without the MPI wrapper).

The line with `LINK_LIBRARIES(${MPI_LIBRARY})` had been commented out in CMakeLists.txt, presumably to avoid confusion due to the change `MPI_LIBRARY` -> `MPI_CXX_LIBRARIES` since CMake 2.8.5.  But CMakeLists.txt is currently set to require CMake 2.8.10 or newer, so I think we can safely change that line to `LINK_LIBRARIES(${MPI_CXX_LIBRARIES})`.

This could just be a problem with the way I have my default environment set up, so I'm asking here instead of opening a pull request.
With a clean checkout, I have to set `-DCMAKE_CXX_FLAGS` and `-DCMAKE_EXE_LINKER_FLAGS` every time I use cmake, on at least 5 different systems that I use.
With [this](https://gist.github.com/dcyang/afefa813de9e7b3943edfcf998d05326), I only need to type `cmake ..` from qmcpack/build to configure QMCPACK.

Any thoughts?

**Comment by prckent** [comment]
To aid reproducing: can you say more about your software configuration? compilers, mpi, environment variables etc.

**Comment by markdewing** [comment]
I tried this on an Ubuntu system, and the fixes work fine (and it fails to compile w/o them - the configure step works fine, but the compile fails being unable to find mpi.h)
To enhance the out-of-the-box experience (or more precisely, first-step-after-download experience), we should make this change.

**Comment by dcyang** [comment]
My environment variable `CXX` is either not set or set to g++ (tried 4.8.5 and 6.3) or icpc (17.0.1).
`MPI_HOME` is either not set (falling back to default installation) or set to the newest locally built mvapich2, mpich, openmpi, or Intel MPI (17.0.1).

The result is exactly as @markdewing says.
For locally built MPI packages, `ENV{PATH}` and `ENV{LD_LIBRARY_PATH}` are set to find all of them, but I still had to set `CMAKE_CXX_FLAGS` and `CMAKE_EXE_LINKER_FLAGS` by hand.

I'm opening a pull request ...

**Comment by ye-luo** [comment]
I feel more that we should disable that FindMPI code path in cmake. If a user specify CXX as g++ or icpc, it means a non-MPI built is requested.

**Comment by dcyang** [comment]
@ye-luo 
MPI_CXX_COMPILER separately exists for that purpose, as does QMC_MPI=1 (default).

**Comment by ye-luo** [comment]
Do you want to build the code with MPI without using MPI compiler wrappers?

**Comment by ye-luo** [comment]
I also noticed a strange behaviour.
I set environment variable CXX=icpc.
I print it in CMake  $ENV{CXX}
/opt/intel/compilers_and_libraries_2017.2.174/linux/bin/intel64/icpc
CMake enters the case
if($ENV{CXX} MATCHES "mp")

**Comment by dcyang** [comment]
Re: [286648113](https://github.com/QMCPACK/qmcpack/issues/150#issuecomment-286648113)
Actually, I wish to build with MPI but without changing my environment variables (and possibly breaking my other codes).  I think the `QMC_MPI` switch does a good job knowing when it should find/use mpicxx independent of how `ENV{CXX}` is set.

**Comment by dcyang** [comment]
Re: [286648730](https://github.com/QMCPACK/qmcpack/issues/150#issuecomment-286648730)
I noticed it too.
For some reason, it branches correctly when I type `cmake ..` the second time.

**Comment by ye-luo** [comment]
On my desktop, I have intel compiler in my path and library path.
If I don't set anything CC/CXX and do "cmake .."
compiler is chosen GNU but MPI library was Intel.
It is totally a mess. I don't think we can rely on FindMPI.
MPI should be handled by MPI compiler wrapper.

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0

-- Found MPI_C: /opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/lib/libmpifort.so;/opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/lib/release_mt/libmpi.so;/opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/lib/libmpigi.a;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so  
-- Found MPI_CXX: /opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/lib/libmpicxx.so;/opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/lib/libmpifort.so;/opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/lib/release_mt/libmpi.so;/opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/lib/libmpigi.a;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so  
-- Found mpi.h and libraries. Check for working mpi compiler

**Comment by dcyang** [comment]
Re: [286651601](https://github.com/QMCPACK/qmcpack/issues/150#issuecomment-286651601)
If you have an OS-provided gcc package installed and the Intel compiler, CMake identifying gcc/g++ is perfectly normal default behavior.  It's when you set CC=icc , CXX=icpc that CMake works with Intel compilers.

My understanding is that if you had an OS-provided MPI package (take openmpi for example) and you didn't run Intel's mpivars.sh at login, it would cleanly configure it to compile with g++ and openmpi.
If you need everything done with Intel (including MPI wrappers), you would only need to run iccvars.sh and mpivars.sh at login.

**Comment by ye-luo** [comment]
I kind of represent many users having intel compiler configured by default and try to build the code. My first build attempt enters a bad case. It is not your problem but we need to improve it.

My main point is replying on FindMPI is bad. You still need to control a lot of stuff to ensure consistency.
MPI details should be handled by MPI compiler wrappers.

Basically, QMCPACK can have two ways of specifying the compiler. CMake command line or environment variable. The former should override the later (The current case may be the opposite, need to be looked at).
Later, check whether QMC_MPI is consistent with the compiler. If no, print a message and ask user to correct either compiler or QMC_MPI flag.

For your specific needs, probably some fine control in cmake or environmental variable is unavoidable.

**Comment by markdewing** [comment]
If a user runs cmake without specifying a compiler, the behavior should better than we have now.
Possibilities:
1. David's fix: Tries to find MPI libraries and build with MPI if they're found
2. If QMC_MPI is set and compiler is not an mpi wrapper:
     A - Stop cmake and issue error message with directions on how to set the compiler or disable MPI (Ye's suggestion)
     B - disable MPI and build serial version automatically

Perhaps we should go with 1, but add a message that the user should set the compiler to an mpi wrappered version (such as "-DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++")

To fix the oddity Ye noticed, we should test against "^mp".

**Comment by ye-luo** [comment]
My case clearly shows the problem of option 1. There is no consistency check ensured between the compiler and the mpi files found by FindMPI.

**Comment by markdewing** [comment]
I added a more precise check for the wrapper compiler and a warning message
Code is here:https://github.com/markdewing/qmcpack/commit/155e49c6bcefcb0a50eaa5042cc1d9c169c32181

Output is
<pre>
-- Trying to figure out .....
-- Compiler: GNU
-- Compiler Version: 4.8.4
-- Found mpi.h and libraries. Check for working mpi compiler 
CMake Warning at CMakeLists.txt:434 (MESSAGE):
  Building MPI version without using MPI compiler wrappers.

  This may not build qmcpack correctly.  To ensure the correct version,
  specify the compiler wrappers to cmake.

  For example: cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++

  To build without MPI, pass '-DQMC_MPI=0' to cmake


-- MPI is enabled

</pre>

**Comment by ye-luo** [comment]
@markdewing 
is "^mp" OK with $ENV{CXX} having mp prefix like
/opt/intel/compilers_and_libraries_2017.2.174/linux/bin/intel64/mpiicpc
?

**Comment by markdewing** [comment]
No, the simple '^mp' match doesn't work when there's a full path.
In the linked commit, get_filename_component is used to get just the compiler name and that is used for the comparison.

**Comment by prckent** [comment]
Attempting to build with MPI without using compiler wrapper is fraught with risks. There are very strong reasons why MPI library authors provide wrappers, and for this reason using wrappers is always preferred over any kind of user specified link. For this reason, in the manual and build instructions the preferred route is to specify cmake -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc etc. 

That said, if we can support more use cases, good. I agree with the advisory comment in Mark's PR.

**Comment by dcyang** [comment]
I think I now see where I had been confused.
I thought `CMAKE_CXX_COMPILER` was set up to be automatically overwritten by `MPI_CXX_COMPILER` when we have `QMC_MPI=1` **and** a suitable MPI library is detected.

Turns out it wasn't.  Perhaps this is what we need instead:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 862e3c1..83c22a5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -417,6 +417,7 @@ ELSE(CMAKE_TOOLCHAIN_FILE)
       include(FindMPI)
       IF(MPI_FOUND)
         MESSAGE(STATUS "Found mpi.h and libraries. Check for working mpi compiler ")
+        INCLUDE_DIRECTORIES(${MPI_CXX_INCLUDE_PATH})
         FILE(WRITE ${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/testmpi.cxx 
           "#include <mpi.h>"
           "int main(int argc, char** argv){MPI_Init(&argc,&argv); MPI_Finalize();return 0;}\n")
@@ -424,11 +425,21 @@ ELSE(CMAKE_TOOLCHAIN_FILE)
         #${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/testmpi.cxx
         #OUTPUT_VARIABLE OUTPUT)
         set(MPI_WORKS 1)
+        IF(DEFINED MPI_CXX_COMPILER)
+          SET(CMAKE_CXX_COMPILER "${MPI_CXX_COMPILER}")
+        ELSE(DEFINED MPI_CXX_COMPILER)
+          SET(MPI_WARNING_LIST
+            "Building MPI version without using MPI compiler wrappers.\n"
+            "This may not build qmcpack correctly. To ensure the correct version, specify the compiler wrappers to cmake.\n"
+            "For example: cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++\n"
+            "To build without MPI, pass '-DQMC_MPI=0' to cmake")
+          MESSAGE(WARNING ${MPI_WARNING_LIST})
+        ENDIF(DEFINED MPI_CXX_COMPILER)
         IF(MPI_WORKS)
           MESSAGE(STATUS "MPI is enabled")
           SET(HAVE_MPI 1)
           SET(HAVE_OOMPI 1)
-          #LINK_LIBRARIES(${MPI_LIBRARY})
+          LINK_LIBRARIES(${MPI_CXX_LIBRARIES})
         ELSE(MPI_WORKS)
           MESSAGE(STATUS "MPI is disabled")
           SET(HAVE_MPI 0)
```

**Comment by prckent** [comment]
PR #151  has been merged now. Are there any further updates that are needed or can we close the issue?

I checked on oxygen, a RHEL box with a host of compilers and MPI libraries installed. cmake now works without any hints. In this case it picked up GCC and Intel MPI, not the best combination on the machine but a great usability improvement. Thanks @dcyang @markdewing

**Comment by dcyang** [comment]
I'd suggest pulling https://github.com/markdewing/qmcpack/commit/155e49c6bcefcb0a50eaa5042cc1d9c169c32181 before closing this issue — I think it's important that the warning message be left there.
But @markdewing will have to request it separately from PR #151.

**Comment by markdewing** [comment]
I sent a PR for that change.  Once that's in, I think we can close this issue.

**Comment by prckent** [comment]
#152 merged. Closing this issue.
