### ISSUE TITLE
Segmentation fault when using Casino PP

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1511]
It should be simple to fix.

**Comment by prckent** [comment]
Ugh. Any hints what is causing this? e.g. Andrea will have to use the AOS build or convert potentials until fixed.

**Comment by ye-luo** [comment]
I just tried the files from Andrea, SoA runs fine on my workstation. I need more clues for what is going on.

**Comment by prckent** [comment]
Crash on titan, summit?

**Comment by ye-luo** [comment]
It is on Titan. I'm asking Andrea to provide more info.

**Comment by zenandrea** [comment]
@ye-luo @prckent 
maybe not connected with the bug, but with the casino PP format:
in input I specify that I will use a casino PP in the following way
```
<pseudo elementType="C" format="casino" href="c_pp.data" lmax="2" l-local="2" nrule="4" cutoff="2.0" />
```
I wanted to point out that in the manual the attributes `lmax, l-local, nrule, cutoff` are mentioned but not really discussed. Although they can be guessed, I think it is worth to tell what `nrule` is.

Moreover, if it is not too complicated, maybe it could be introduced the possibility to define the cutoff radius not directly, via `cutoff`, but indirectly, using a new attribute that only defines what is the maximum deviation of the local or non-local potential from −Z/r at the cutoff radius (casino, for instance, works in this way, and has a default of 1e-5).

**Comment by ye-luo** [comment]
@zenandrea Indeed, the bug was exactly in the place where the cutoff is determined by scanning through the value of all the grid point. However, I think there is a numerical bug and the scanning stopped at the largest grid point because it already exceeds 1e-5 but it should not. I will take a closer look.

**Comment by zenandrea** [comment]
@ye-luo 
I had a look at where you corrected the code.
It seems to me that the code is not checking where local and non-local potentials deviates by more than the tolerance = 1.0e-5 from the −Z/r, but where the deviates from themselves.
I honestly do not understand how that can be useful.
Moreover, I do not understand what this `rc_check` ("Maxium cutoff for non-local pseudopotentials").
I mean, I provide the cutoff in input, thus I would be just interested to know what is the error, namely the difference with the asymptotic behavior (-Z/r, I guess).

**Comment by prckent** [comment]
@zenandrea I agree that the checks aren't helpful. They should also be independent of data source.

I think there are two radii of interest: when the local potential becomes purely Coulombic, -Z/r, and the radius when the non-local channels deviate from the local channel, necessitating the non-local integral be performed for electrons inside this radius.

**Comment by prckent** [comment]
We should discuss what is useful+wanted here and simply implement it.

**Comment by zenandrea** [comment]
@prckent I totally agree with the two radii idea.
Indeed, I think a good solution could be to implement an automatic definition of the two radii that you described, for a `tolerance` that could be defined from input but has a reasonable default value of 1.0e-5. This would make the definition of `cutoff` useless (but maybe it could be kept for backward compatibility, with a warning that the `tolerance` value and the automatic definition of cutoffs is in that case ignored)
