### ISSUE TITLE
verbose = high not printing all atomic positions

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1526]
Currently the code only prints 10 atoms no matter what verbose is.

**Comment by ye-luo** [comment]
In favor of #3761. Then this is not needed.

**Comment by prckent** [comment]
I think we need both. I have reopened this and tagged it as a good first issue, since it should be a simple fix. Experienced practitioners would be able to make use of #3761 but a new user might still expect everything in the log file. Some people also might want it for reproducibility.

**Comment by ye-luo** [comment]
Completed by #4401
