### ISSUE TITLE
Rescaling of drift in DMC?

### ISSUE THREAD

**Issue by zenandrea** [QMCPACK/qmcpack#1531]
I am wondering if the DMC algorithm implemented in qmcpack uses any rescaling of the drift in proximity of the nodes to avoid its divergence.
I cannot find anything about that in the manual.
I imagine that something similar to eq. 34 of Umrigar, Nightingale, and Runge JCP 1993 paper could be implemented.
However, there is a parameter `a` in Umrigar's rescaled drift that should be fixed. 
So, if the rescaling is implemented, what is the functional form and are there parameters that I can define to regulate it?

**Comment by Paul-St-Young** [comment]
@zenandrea eq. 34 is implemented in `DriftOperator.h`. The `a` parameter is currently hard-coded to 1.0.

As far as I know, the last time the drift routines were touched was in PR #546 in response to issue #544.

**Comment by zenandrea** [comment]
@Paul-St-Young Many thanks for the quick answer.
Would it be a big trouble to introduce the possibility to enter the value of parameter `a` from input?

I am asking that because, around three years ago, Cyrus Umrigar suggested me and Dario Alfe to use a value of `a=0.5`, which is typically better than `a=1.0` (here better means better time-step dependence and stability). Our tests confirmed his claim, and since them we always use `a=0.5`.

While I think that it is good to guarantee backward compatibility in qmcpack by having a default value of `a=1.0`, it is probably good also to have the possibility to take the best value for `a` in new simulations.

**Comment by jtkrogel** [comment]
It would not be hard to introduce this from input.  Suggestions for an input parameter name?  `drift_scale`?

**Comment by zenandrea** [comment]
What about being a little more specific, like `drift_umrigar_a` or `drift_unr_a`?

**Comment by zenandrea** [comment]
I am trying to understand what is performed inside `DriftOperator.h`.
I am not very familiar with C++, but I think I roughly got what it is in there.

I am not sure about a pair of points. Can somebody help me with them.

1) I was trying to check that the drift rescaling is always performed in a particle-by-particle way, as defined in eq. (3) of http://link.aps.org/doi/10.1103/PhysRevB.93.241118.
I mean, eq. (34) of Umrigar's JCP 1993 paper is not optimal, as it would make DMC size-inconsistent for finite value of tau. Umrigar himself did not implement eq. (34) but eq. (35).
In eq. (35) the drift of the whole N-electrons is broken up into contributions of individual drifting electrons. Moreover, in eq. (35) the scaling `a` is a function of the electron coordinates. This second aspect can be important in case of all-electron calculations, but with pseudo-potentials it is not useful. 
Well, I see than in qmcpack the `a(r)` dependence is not implemented, and it is not a big deal for the calculations I usually do as I always have pseudopotentials.

2) I noticed that the function `setScaledDriftPbyPandNodeCorr` returns the `sqrt(norm_scaled / norm)`. This is a potentially problematic quantity, as if it is used it can break the size-consistency of DMC at finite tau. In Umrigar's paper the quantity `norm_scaled / norm` was used in the branching, eq. (39), and that lead to a size-consistency problem. Size-consistency was restored in http://link.aps.org/doi/10.1103/PhysRevB.93.241118 by performing a branching without `norm_scaled / norm`.
So, I tried to follow there in qmcpack the `sqrt(norm_scaled / norm)` is used.
I see it is used in `QMCDrivers/QMCUpdateBase.cpp` in two places.
Can somebody help me to understand to what purpose it is used?
In particular, this quantity shoud not go into energy evaluations of branching weights!

**Comment by prckent** [comment]
Extra comment: I seem to recall that the functions for modifying and defining drift are defined many times over to cope with different types and uses cases, as opposed to being defined once. It is also important that the CUDA code uses the same functions. If this discussion results in some improvements for the drift implementation (and other parts of the Greens function) and options for setting what it used, it would be good to simplify as much as possible. Ideally there should be a single function or template defining (say) unr_eq_34 etc. and it should be easily switchable by input. An obvious extension of this work would be to finally understand the differences between the public DMC implementations.

**Comment by ye-luo** [comment]
@zenandrea 
1. QMCPACK all the p-by-p drivers implements eq.(35) of Umrigar's JCP 1993. #1550 now allows you to change the `a` parameter
2. There are some all-p drivers (VMC/RMC) still use eq.(34) to modify drifts. We will move all of them over to the new framework I just added.
3. In my opinion, some terms of `a(r)` dependence in JCP 1993 is not general and the parametrization seems customized to the test cases. Anyway, we will provide that also in the new framework.
4. The branching scheme in JCP 1993 is not size consistent and QMCPACK only implements in the CUDA code and it is turned off by default.
