### ISSUE TITLE
Restart segfaults if number of walkers less than target

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#155]
If the number of DMC walkers fluctuates below the target number, the remaining walkers are filled in with zero.  This causes a segfault on subsequent restart. (Positions all zero, interparticle distances are zero, reciprocal is Inf, indexing into a table converts Inf/Nan to segfault)

I've attached an input file that will show the problem (change suffix to .xml, github wouldn't let me upload a plain XML file)
[dmc.in.txt](https://github.com/QMCPACK/qmcpack/files/856553/dmc.in.txt)

(Might need to run it several times to get a problematic checkpoint file)

The restart file copies the QMC sections, which contains both a VMC and a DMC section. The segfault occurs for both the VMC and DMC sections.

The total # of walkers stored in the config.h5 file is taken from the WalkerOffset array 

The obvious solution is to use the number of active walkers as the number of configurations to store and load, but I don't know if there's something more involved.

See also #2, not sure if it's related

**Comment by markdewing** [comment]
This turned out to be a particular issue with the non-MPI build.  MPI builds work fine (because the WalkerOffset array gets updated).  Fix is to update the WalkerOffset array in the non-MPI builds.

**Comment by prckent** [comment]
Fixed, although more complex testing of restart code needed.
