### ISSUE TITLE
CMake with Intel Compiler and External Fortran libraries

### ISSUE THREAD

**Issue by naromero77** [QMCPACK/qmcpack#1555]
When QMCPACK is built with the Intel compiler, the most logical choice for external BLAS/LAPACK is Intel MKL. However, according to the QMCPACK manual we also support other external BLAS/LAPACK libraries, e.g. OpenBLAS, NETLIB BLAS/LAPACK. These libraries contain Fortran source, and when compiled with the Intel Fortran Compiler require that `-lifcore` be specified on the QMCPACK binary link line.

I think QMCPACK's CMake system should be responsible for adding `-lifcore` at the link line. Here is my logic:
1. It cannot be the Intel C++ compiler's responsibilities to link in an Intel Fortran library. Note that the compilers are technically sold separately and installed in separate directories.
2. Ideally, the external library would embed some information about its own dependencies. AFAIK, this is only possible with dynamically linked libraries, but not with statically linked libraries which is what is predominantly used on HPC platforms.

This is what I added to Spack to accommodate the combination of the Intel C++ compiler
and external Fortran library compiled by the Intel Fortran Compiler:
https://github.com/spack/spack/blob/eb7c79720de66cc7b74ac0c6a1ce1d44ee670cd5/var/spack/repos/builtin/packages/qmcpack/package.py#L200-L201

It would be better if QMCPACK's CMake automatically took care of this, rather than have the user have to figure this out on their own.

**Comment by ye-luo** [comment]
How do QMCPACK know a provided library was built in a certain way and needs extra dependency?
In the case of libhdf5, it depends on libz and findHDF5 module handles that not QMCPACK.
For your request, it is the responsibility of FindLAPACK (from CMake).

**Comment by prckent** [comment]
I think it is fine to not support other BLAS than MKL when Intel compilers are used. We should try to have this work, i.e. use the official CMake FindLAPACK functionality etc., but otherwise not spend much effort on this. The opposite case - non-Intel compilers with MKL - is far more important since MKL is effectively free and it is usually fastest on Intel. This combination is tested each night.

**Comment by prckent** [comment]
Lets examine this if someone reports a problem.
