### ISSUE TITLE
Deterministic test in the mixed precision.

### ISSUE THREAD

**Issue by Hyeondeok-Shin** [QMCPACK/qmcpack#1558]
[mixed_precision.xlsx](https://github.com/QMCPACK/qmcpack/files/3102137/mixed_precision.xlsx)

The attached file is a table of full vs. mixed precision for all deterministic tests. Tests were done with gcc, intel, and clang in the workstation.
 
We already discussed that we need to increase the tolerance in the mixed precision, and there are three important issues in the deterministic test for the mixed precision.

1.  Tolerance seems to be separated for each observable. Tolerance seems not to uniform for observables, it is typically large in kinetic energy (and flux), and small in potential energy.

2.  Tolerance seems to be separated for real and complex build for the mixed precision. They give very different tolerance in the same deterministic test even in 1x1x1 diamond testset.

3.  Deterministic test in the mixed precision is very sensitive with the compiler used in the build. I tested in gcc, intel, and clang, and the tolerance for the same observable is significantly different from each other.

Issue "1" and "2" seem to be able to be handled, but "3" looks pretty tricky. 

The different compiler gives a different answer (and the different machine also could), but it is not an easy way to check tolerance with all available compiler (and machine) for the relaxation.

I'd like to ask an opinion of how can we deal with the different answer with the different compilers or machines in the deterministic test in the mixed precision. 

Any comments are very welcome. 

Hyeondeok Shin

**Comment by jtkrogel** [comment]
There is a lot of data in the spreadsheet.   I've tried to cut down the data in a couple of ways.

First, I looked at relative errors instead of absolute ones.  After inspection of the data, this did not yield any clear advantage (i.e. an approximately common scale) over the absolute difference data, so I won't pursue it further.

Second, I looked at max errors across quantities and compilers for each case.  This is more instructive so I will discuss it more below.

**Comment by jtkrogel** [comment]
Both diamond and LiH display max absolute errors approaching 1e-3 for MP when compared to FP reference values.

Hopefully we can agree that numerical agreement to only 1e-3 is too large to be useful for deterministic tests (which are meant to be relatively high precision).  Also, these are pretty simple systems, so it is likely that we will see max deviations larger than this for other systems.

To me this directly implies that we cannot usefully benchmark MP runs against FP.

**Comment by jtkrogel** [comment]
For the diamond data you present, the complex MP are referenced against complex FP.

Comparing the real FP and complex FP reference data shows differences approaching 1e-2, which is again far too large.

This directly implies that we cannot usefully benchmark complex runs against real ones.

**Comment by jtkrogel** [comment]
This leaves variation across compilers.  @Hyeondeok-Shin please can you attach a version of the spreadsheet with raw data values from the different compiler runs?  Currently they can't be compared directly with each other due to the use of abs() after subtracting off the reference values.

**Comment by Hyeondeok-Shin** [comment]
[mixed_precision_compiler.xlsx](https://github.com/QMCPACK/qmcpack/files/3104762/mixed_precision_compiler.xlsx)

Thank you for comments, and sorry for the confusing with too much data.
Here I'm attaching the raw data from the different compiler runs.

**Comment by jtkrogel** [comment]
Thanks Hyeondoek.

Maximum disagreement among compilers approaches 1e-3, which is similar to variations seen above between MP and FP and between real and complex.

Given all the data above, we either live with tolerances set above 1e-2, or we give up having a single reference.

Giving up a single reference is not so bad for MP vs FP or real vs complex, but it is untenable IMO to give it up for variations across compilers.

We should rerun this analysis for FP only, looking at variations across real/complex and compilers.  If the variations are smaller (which I believe they will be given past discussions), then we can restrict deterministic test construction to FP only.  MP might need to be tested on a single machine, or checked against much larger (>1e-2) tolerances.

**Comment by jtkrogel** [comment]
Another strategy is to live with large tolerances for quantities involving wavefunction derivatives (which show the largest deviations).  The potential terms are much better.

**Comment by jtkrogel** [comment]
I suggest we set tolerances to some factor (say 10x) larger than the maximum observed variation away from the reference.  This should also include (via max) the largest variation observed between compilers.

The attached script performs this analysis for the data from deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1:
[tolerance_bounds.py.gz](https://github.com/QMCPACK/qmcpack/files/3108050/tolerance_bounds.py.gz)

**Comment by jtkrogel** [comment]
Below is the output of the script for this test case.  Using real FP as reference for complex MP results in the largest set of tolerances needed.  Using complex FP as reference for complex MP reduces the tolerances significantly, but by far the most for the terms depending on wavefunction derivatives.  Moving to MP as reference reduces the required tolerances by up to an order of magnitude in some cases.

All tolerance data shown below uses a factor of 10 and accounts explicitly for variation among compilers.
```
Tolerances with MP as reference
  Tolerances for real_mp
    LocalEnergy        0.000129500000
    Kinetic            0.000191300000
    LocalPotential     0.000061700000
    ElecElec           0.000017200000
    IonIon             0.000018100000
    LocalECP           0.000033300000
    NonLocalECP        0.000040200000
  Tolerances for comp_mp
    LocalEnergy        0.000124200000
    Kinetic            0.000074800000
    LocalPotential     0.000049400000
    ElecElec           0.000007100000
    IonIon             0.000018100000
    LocalECP           0.000049200000
    NonLocalECP        0.000014800000

Tolerances with FP as reference
  Tolerances for real_mp with real_fp as reference
    LocalEnergy        0.000129500000
    Kinetic            0.000270500000
    LocalPotential     0.000206900000
    ElecElec           0.000030300000
    IonIon             0.000069500000
    LocalECP           0.000089100000
    NonLocalECP        0.000150700000
  Tolerances for real_mp with comp_fp as reference
    LocalEnergy        0.080093900000
    Kinetic            0.079877500000
    LocalPotential     0.000061700000
    ElecElec           0.000059100000
    IonIon             0.000069500000
    LocalECP           0.000374500000
    NonLocalECP        0.000128900000
  Tolerances for comp_mp with real_fp as reference
    LocalEnergy        0.080035700000
    Kinetic            0.079396200000
    LocalPotential     0.000639500000
    ElecElec           0.000078200000
    IonIon             0.000069500000
    LocalECP           0.000657300000
    NonLocalECP        0.000130000000
  Tolerances for comp_mp with comp_fp as reference
    LocalEnergy        0.000124200000
    Kinetic            0.000285600000
    LocalPotential     0.000470700000
    ElecElec           0.000049400000
    IonIon             0.000069500000
    LocalECP           0.000227000000
    NonLocalECP        0.000108200000

```

**Comment by jtkrogel** [comment]
Once we settle on an acceptable reference and tolerance factor, the script above can be used to generate tolerance data for all the test cases.

**Comment by Hyeondeok-Shin** [comment]
Thank you very much for the fruitful comments and helps Jaron. 
 I'll be starting with larger tolerance for MP test.
