### ISSUE TITLE
Questions on implementing a new wavefunction

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#1577]
I'm trying to implement a simple sample wavefunction (He with STO orbitals and Pade Jastrow) that derives from WaveFunctionComponent.

Some questions
- Distance tables
  - For e-e (like particle) distance tables, which triangle is valid and when?   It seems the whole table is valid sometimes, but only one triangle is value during some parts of particle-by-particle moves. 
  - How are the temporary values (Temp_r and Temp_dr) indexed?  Is the i-th particle (iat) present (but with an invalid value), or is the array compressed to size N-1 (and a place for the i-th particle absent)?
- To have optimizable parameters, evaluateDerivative needs to be implemented.
  - (Comment) If evaluateDerivatives is not implemented, no error or warning message is generated.  The optimization simply fails to choose new parameter values.
  - The dlogpsi argument is the derivative of log psi with respect to a parameter (more precisely, a vector of derivatives corresponding to the vector of parameters in optvars).  What is  dhpsioverpsi?  The derivative (wrt opt parameters) of the laplacian of log psi?

**Comment by ye-luo** [comment]
STO and Pade are both available in the code. Why would you like to implement a new one?
For a distance based jastrow, we only need to implement a functor instead of a whole J2.
STO is implemented at atomic orbital level in the LCAO route.
None of them needs to be involved with WaveFunctionComponent.

**Comment by markdewing** [comment]
I'm trying to write an example with some documentation on how to add a new WaveFunctionComponent, and this is the simplest example (that has both e-n and e-e terms).
By copying from something that already exists, I can debug and test by comparing the code in detail.   Without this, I really don't know how I could get all the conventions correct.

**Comment by prckent** [comment]
This will be a helpful example and I think will e.g. clarify the requirements, what needs to be implemented, and improve error handling (an unimplemented evaluateDerivatives should abort).

**Comment by ye-luo** [comment]
Completed by #1621
