### ISSUE TITLE
Nexus tests

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#158]
Nexus should have validation tests for core workflows providing essential coverage.

Nexus modules are organized below.  Checked modules have all necessary tests.  Modules listed with a `*` contain code that would benefit from additional tests, but in areas that are not part of core Nexus execution (look for `# test needed` in the source).  

Testing utilities:
- [x]  testing.py

Utilities that do not depend on base classes:
- [x]  versions.py
- [x]  execute.py
- [x]  memory.py
- [x]  plotting.py
- [x]  superstring.py*

High level base classes and developer utilities:
- [x]  generic.py
- [x]  developer.py
- [x]  debug.py

Utilities depending only on DevBase:
- [x]  unit_converter.py
- [x]  numerics.py*
- [x]  fileio.py*
- [x]  hdfreader.py
- [x]  xmlreader.py

External tools depending on base classes and/or utilities:
- [x]  nxs-redo
- [x]  nxs-sim
- [x]  qmca
- [x]  qmc-fit
- [x]  qdens

Physical classes depending only on DevBase:
- [x]  periodic_table.py
- [x]  basisset.py*
- [x]  pseudopotential.py*
- [x]  structure.py*
- [x]  physical_system.py*
 
Core nexus classes/functions:
- [x]  nexus_base.py
- [x]  nexus.py
- [x]  machines.py*
- [x]  simulation.py
- [x]  project_manager.py
- [x]  bundle.py
 
Simulation input classes:
- [x]  vasp_input.py
- [x]  pwscf_input.py
- [x]  gamess_input.py
- [x]  pyscf_input.py
- [x]  quantum_package_input.py
- [x]  pwscf_postprocessors.py
- [x]  qmcpack_converters.py
- [x]  qmcpack_input.py

Simulation analyzer classes:
- [x]  vasp_analyzer.py
- [x]  pwscf_analyzer.py
- [x]  gamess_analyzer.py
- [x]  pyscf_analyzer.py
- [x]  quantum_package_analyzer.py
- [x]  pwscf_postprocessors.py
- [x]  qmcpack_converters.py
- [x]  qmcpack_analyzer.py
*  pwscf_data_reader.py
*  qmcpack_analyzer_base.py
*  qmcpack_method_analyzers.py
*  qmcpack_property_analyzers.py
*  qmcpack_quantity_analyzers.py
*  qmcpack_result_analyzers.py

Simulation classes:
- [x]  vasp.py
- [x]  pwscf.py
- [x]  gamess.py
- [x]  pyscf_sim.py
- [x]  quantum_package.py
- [x]  pwscf_postprocessors.py
- [x]  qmcpack_converters.py
- [x]  qmcpack.py

User style tests
- [x] user example integration tests at generate_only level (test that same inputs are generated)
- [x] add examples from qmcpack workshop

See also #322 (Nexus features) and #321(Nexus documentation)

**Comment by prckent** [comment]
Related to this:

- How to do testing in python and of NEXUS?

- How to measure coverage in python? Knowing which functions are/are not tested would be beneficial.

In both cases we want to use a minimum of tools.

**Comment by markdewing** [comment]
Some unit testing would be helpful, too.
Either using unittest (built in to Python) or pytest (not included in Python, but less syntactic overhead in the tests)

**Comment by jtkrogel** [comment]
For full workflows, there are two main aspects:
1) The production of input files for the various codes (including PP files, etc)
2) The analysis of output data and passing of this information to the next simulation in the workflow

The first could be tested by developing a "diff" or "equality" function/check for Nexus objects: produce all the files in a workflow, read them back in and check for equivalence.  The second is trickier, but I could make fake applications for QE, qmcpack, etc that "run" by spitting out canned output files, so as to avoid install/robustness issues of actual application codes (QE/VASP/GAMESS/QMCPACK) on the host machine.  Checking the flow of this information into the next simulation is then covered through the tests in (1).

Data analysis probably requires separate correctness testing, as do the many available atomic structure manipulation functions that can be used to prep input.

**Comment by prckent** [comment]
Even without running applications one could:

- Check the inputs are correctly produced (vs gold reference) for a few flavors of workflow
- Check that the "next step" inputs are correctly produced for rigged partially run workflow

The first would enable checks of the recent commits and also provide reassurance to the approvers that NEXUS has not been broken due to a simple typo.

**Comment by jtkrogel** [comment]
Started this with PR #760.  More is needed to consider this complete.

**Comment by jtkrogel** [comment]
More in PR #875.  Testing there checks that user example inputs continue to be generated correctly.

**Comment by jtkrogel** [comment]
Saving this comment before editing at the top:

Core Nexus workflows can include:
1.1 QE/VASP (relaxed structure) or XSF/POSCAR/CIF file read
1.2 QE (orbitals)
1.3 pw2qmcpack (conversion)
1.4 QMCPACK (opt)
1.5 QMCPACK (vmc/dmc)

2.1 GAMESS (orbitals/multidet)
2.2 convert4qmc (conversion)
2.3 [QMCPACK (cusp correction)]
2.4 QMCPACK (opt)
2.5 QMCPACK (vmc/dmc)

3.1 SQD (orbitals)
3.2 QMCPACK (opt)
3.3 QMCPACK (vmc/dmc)

4.1 VASP (neb)
4.2 VASP/QE/QMCPACK (end/transition state calc)

5.1 QE (scf)
5.2 various postprocessing tools (projwfc.x, etc)

**Comment by jtkrogel** [comment]
With #2093, this issue is addressed.  All modules are covered at some level at this point.  Overall test coverage is estimated at about 61%.

**Comment by prckent** [comment]
Once #2093 is merged, what do you recommend we add to both the automated CI and nightly integration tests?

**Comment by jtkrogel** [comment]
Let me watch the tests for a few days to monitor their stability.  Once any stability issues are resolved, these could be added to the CI and also to the deterministic test sets.  There might be an advantage to wait, however, with the Python 3 transition coming up.  I wouldn't want any instability caused by the transition to hold up the CI.
