### ISSUE TITLE
Change of DriftModifier type not allowed when reusing a driver

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1589]
Due to #1585, changing DriftModifier type is not allowed when reusing a driver.
This will be an issue when a second DriftModifier type is added to the code.

DriftModifier is created in QMCDriver::process() when a driver is initialized.
virutal QMCDriver::resetComponents() handles refreshing some internal objects when a driver is reused.
For the moment, resetComponents() is called before process(). For this reason, resetComponents() cannot reset things changed by the later process.

A clean solution is needed.

**Comment by prckent** [comment]
Perhaps we only have one drift modifier class and can avoid both inheritance and pointers.

**Comment by PDoakORNL** [comment]
I think that's a good path until we need another. Is there another already planned?

**Comment by ye-luo** [comment]
There are at least two on their way.
The true problem is the more than necessary layers in the drivers.
I'd like to solve that and then this issue should disappear as well.

**Comment by ye-luo** [comment]
We are moving away from reusing drivers. A fresh driver will be created for each QMC input section even two consecutive drivers are the same. For this reason, this issue is no more relevant.
