### ISSUE TITLE
pw2qmcpack.x error with large cell/cutoff

### ISSUE THREAD

**Issue by kayahans** [QMCPACK/qmcpack#1593]
I have failed to convert the orbitals of an 56 atom (~580 electrons, ecutwfc=320 Ry) unitcell using pw2qmcpack.x. 

First, I have tried with qe.6.3, which was compiled with serial hdf5 1.8.12 and intel 18.0.0  using -D__HDF5_C -DH5_USE_16_API flags. This is the output from p2q:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    task #         0
    from diropn : error #        10
    error opening pwscf_output/pwscf.wfc1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

Obviously pwscf.wfcxx files aren't in pwscf_output, but with the same system but smaller ecutwfc these files are printed with qe. I think this has been already mentioned in the manual.

Then I compiled qe.6.4 using hdf5_parallel/1.10.3 and intel/18.0.0 with -D__HDF5 -DH5_USE_16_API flags. Following the advice in the manual, I ran scf/nscf and pw2qmcpack using the same parallelization (-npool 4) and wf_collect=.false. .  This time I had the following output from p2q:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%`
     task #        50
     from pw2qmcpack : error #         1
     reading inputpp namelist
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
I could try a few more things, but each test is taking almost a day. I would appreciate any advice.

**Comment by ye-luo** [comment]
I don't remember when but `wf_collect` has been deprecated in QE. This doesn't affect pw2qmcpack which still can run in serial and parallel. It is a QE issue if it can't load its own WF. This can be highly possible with a large WF without using hdf5 in QE. With hdf5 enabled in QE, not just in pw2qmcpack, there should be no problem.

For your second issue, I believe it is due to some simple mistake in the command line.
See the following issue.
https://groups.google.com/d/msg/qmcpack/t2MLD29FBTM/L3R6JCV2AQAJ

**Comment by prckent** [comment]
Note that to test the converter it is not necessary to have a converged wavefunction. Set a very large convergence tolerance or limiting the number of electronic steps to check errors such as files not being present.

@kayahans Are you certain that some strange escape characters have not entered your pw2qmcpack.in entries or the inputs are mixed up? This error occurs before the postprocessor has done much and indicates invalid input.

**Comment by kayahans** [comment]
@ye-luo Thanks for your suggestions. I think first I had the same issue posted in the forum, but correcting this led to another problem:
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine read_rhog (1):
     error reading file pwscf_output/pwscf.save/charge-density
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

When -D_HDF5 flag is used, charge-density is also printed in hdf5 format, not only the .wfc files. Does pw2qmcpack.x look for the charge-density.hdf5 file? The file has no extension defined in the error message.

@prckent With the error above (after correcting with the suggestion from Ye) I think it means that the &inputpp block is read successfully.  Otherwise, you are right. I had seen that type of errors when I wrote pp.x inputs by hand. I didn't think that I would need to run many tests about it, I will use cheaper parameters next time, thanks for suggestions.

**Comment by ye-luo** [comment]
pw2qmcpack use pw.x restart infrastructure to load WF and density. Does your pw2qmcpack.x built the same way as your pw.x? I mean both using -D__HDF5 flag or both using -D__HDF5_C.
Did you always have -DH5_USE_16_API ?

**Comment by prckent** [comment]
Thanks @kayahans
