### ISSUE TITLE
Jastrow optimization high variance with reasonable starting guess

### ISSUE THREAD

**Issue by shivupa** [QMCPACK/qmcpack#1597]
Hi,

We have run into a jastrow optimization issue.

C60 is the system of interest, but we have used C20 as it is a simpler test system which should be chemically similar. Trial wave functions used were UHF trial wave functions in gamess with the ccecp pseudopotentials and the corresponding double zeta basis sets. For both systems the vmc without a Jastrow reproduces the uhf energy. 

C20
```
                            LocalEnergy               Variance           ratio 
qmc_c20  series 0  -109.309226 +/- 0.013823    1.0   20.457607 +/- 0.460763    1.0   0.1872
FINAL UHF ENERGY IS     -109.3041990004 AFTER  13 ITERATIONS
```
C60
```
                            LocalEnergy               Variance           ratio 
c60  series 0  -330.021858 +/- 0.022078    1.0   62.846880 +/- 0.741337    1.2   0.1904
FINAL UHF ENERGY IS     -330.0074174788 AFTER  12 ITERATIONS
```
The Problem:
Optimizing a jastrow on the C20 case works well, but taking that jastrow and using it as a starting guess for C60 fails. 

C20:
```
                            LocalEnergy               Variance           ratio 
c20  series 0  -111.602142 +/- 0.005013    1.0   7.035245 +/- 0.036576    1.0   0.0630 
c20  series 1  -111.590372 +/- 0.017419    1.0   7.016561 +/- 0.132685    1.3   0.0629 
c20  series 2  -112.318577 +/- 0.011229    1.0   2.744911 +/- 0.062958    1.2   0.0244 
c20  series 3  -112.385112 +/- 0.009639    1.0   2.342609 +/- 0.060011    1.4   0.0208 
c20  series 4  -112.380267 +/- 0.009629    1.0   2.373485 +/- 0.101419    1.0   0.0211 
c20  series 5  -112.393756 +/- 0.005847    1.1   2.303353 +/- 0.023674    1.0   0.0205 
c20  series 6  -112.392705 +/- 0.005734    1.0   2.309088 +/- 0.024905    1.0   0.0205 
c20  series 7  -112.394572 +/- 0.008088    1.1   2.329028 +/- 0.062737    2.9   0.0207 
c20  series 8  -112.405697 +/- 0.007521    1.0   2.313312 +/- 0.033051    1.0   0.0206 
c20  series 9  -112.391665 +/- 0.009450    1.7   2.338559 +/- 0.052508    1.0   0.0208 
```
C60:
```
                            LocalEnergy               Variance           ratio 
c60  series 0  -260.105616 +/- 0.021806    1.0   275.233288 +/- 3.527696    1.0   1.0582 
c60  series 1  -260.049555 +/- 0.018272    2.3   272.907847 +/- 2.293021    1.0   1.0494 
c60  series 2  -263.510212 +/- 0.019768    2.9   253.765120 +/- 2.372451    1.0   0.9630 
c60  series 3  -264.181206 +/- 0.017363    2.2   247.944478 +/- 1.399428    1.0   0.9385 
c60  series 4  -264.236542 +/- 0.016634    2.1   257.724637 +/- 14.607323    1.0   0.9754 
c60  series 5  -264.246350 +/- 0.015439    2.0   241.887703 +/- 1.154314    1.1   0.9154 
c60  series 6  -264.219998 +/- 0.019936    3.3   241.934532 +/- 1.132864    1.1   0.9157 
c60  series 7  -264.190782 +/- 0.020760    3.3   243.035842 +/- 1.266144    1.0   0.9199 
c60  series 8  -264.208320 +/- 0.016650    2.1   248.535513 +/- 3.260279    1.0   0.9407 
c60  series 9  -264.218167 +/- 0.018311    2.5   243.311858 +/- 1.528011    1.1   0.9209 
```

The optimization is similarly unstable using pure variance or reweighted variance optimization. I have tried J2, J2+J1, and J2+J1+J3 factors. I also tried the adaptive optimization method. The files necessary to reproduce this can be found at https://gist.github.com/shivupa/e7f6d45cfbc867a4e49766ef7c4d33ec

**Comment by ye-luo** [comment]
Please upload your structure file for C20 and C60

**Comment by shivupa** [comment]
Added

**Comment by ye-luo** [comment]
I don't need xyz file. I need the structure.xml which you used in your qmcpack run.

**Comment by shivupa** [comment]
Sorry I misunderstood. Added those files.

**Comment by ye-luo** [comment]
I need C.qmcpp.xml as well

**Comment by shivupa** [comment]
Added

**Comment by ye-luo** [comment]
I started from a J1+J2 optimized on the C20.
```
//VMC J1 J2
c60  series 0  -338.697497 +/- 0.015989   8.761949 +/- 0.076604   0.0259 
//OPT J1 J2
c60  series 1  -338.691933 +/- 0.014464   8.933146 +/- 0.084869   0.0264 
c60  series 2  -338.877216 +/- 0.011771   8.408588 +/- 0.077494   0.0248 
c60  series 3  -338.922028 +/- 0.009959   8.287021 +/- 0.064773   0.0245 
c60  series 4  -338.899453 +/- 0.019072   8.255217 +/- 0.060938   0.0244 
//VMC J1 J2 J3
c60  series 5  -338.913568 +/- 0.011152   8.363881 +/- 0.176789   0.0247 
/OPT J1 J2 J3
c60  series 6  -338.923589 +/- 0.009695   8.405936 +/- 0.087112   0.0248 
c60  series 7  -339.048510 +/- 0.013101   7.895118 +/- 0.112891   0.0233 
c60  series 8  -339.043713 +/- 0.010478   7.903236 +/- 0.123389   0.0233 
c60  series 9  -339.100379 +/- 0.000000   8.092320 +/- 0.000000   0.0239 
c60  series 10  -339.032222 +/- 0.008272   7.884699 +/- 0.072840   0.0233 
c60  series 11  -339.035941 +/- 0.009138   8.037477 +/- 0.059182   0.0237 
c60  series 12  -339.027570 +/- 0.006700   7.780278 +/- 0.087178   0.0229 
c60  series 13  -339.067234 +/- 0.006817   7.566304 +/- 0.050738   0.0223 
```

**Comment by prckent** [comment]
@ye-luo Can you paste your optimization settings here? How did they differ from @shivupa 's ? Or was QMCPACK misbehaving in one of the builds?

**Comment by ye-luo** [comment]
@prckent After a bit investigation, we found the issue is not the optimization but the VMC went wrong already at the first step. We tried the whole input set from @shivupa on AWS and there is no issue at all. So we are inspecting the binary now.

**Comment by shivupa** [comment]
Yup I will update this once I get it figured out, but it's pretty clear this is on my end. My inputs worked on AWS and for @ye-luo with no problem with the same versions of the code. I appreciate all the help with this so far!

**Comment by prckent** [comment]
Hopefully we can find something easier than running a full VMC calculation that can catch this. e.g. Supposing HDF5 library is bad, perhaps we can add a check at the level of one of the unit tests.

**Comment by ye-luo** [comment]
This is LCAO using large xml files. It reminds me the bad days with libxml2.

**Comment by prckent** [comment]
@shivupa Since you have a working reference, can you check to see if any of the output before the first QMC step is different?

**Comment by shivupa** [comment]
This is definitely something on my end. I've opened a ticket for the local resources to see which dependency specifically is an issue. The outputs were similar (except for the things that should be changing such as the date, time, host, etc.). I'm going to close this as it doesn't seem its a bug.
