### ISSUE TITLE
Complex builds broken: CountingFunctor.h

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1646]
https://cdash.qmcpack.org/CDash/viewBuildError.php?buildid=62701

gcc8 + complex is now having trouble.

Intel compiler is fine. Probably gcc8 is being stricter about conversions of types than Intel and the earlier versions run for other builds, as we should be.

**Comment by PDoakORNL** [comment]
This looks to be a compiler bug in intel then, this shouldn't compile when QMC_COMPLEX is defined.

**Comment by PDoakORNL** [comment]
This would be trivial to fix if I could tell what getNameAndValue() in gaussian functor was supposed to do.

I would assume return the NameAndValue vector from myVars which should obviously be 
const std::vector<std::pair<std::string, opt_variables_type>>&

GaussianFunction::getNameAndValue is not used in the code as far as I can see. I think the proper fix is to delete the method.Then @chrislzhao can restore it if he desires.

**Comment by ye-luo** [comment]
It happened to me in the past that unused template class member functions are not checked and compiled by Intel but gcc usually does it. However, I don't understand why the CI with gcc 6 passes. Probably some behaviour changed from 6 to 8.

**Comment by PDoakORNL** [comment]
Its a good point that a "lazy" compiler would just ignore this function. I wonder what the standard says about this.

**Comment by prckent** [comment]
GCC8 complex builds are now passing.

Good to learn about these compiler differences.
