### ISSUE TITLE
Counting Jastrow Code

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#1649]
Since this code is getting touched again the following should be resolved.

##QMCWaveFunctions/CountingFunctor.h
Mismatched class declaration and file name
No Unit Test.
typdef vs using
Inherits from QMCTraits
Has template parameter it doesn't use.

##QMCWaveFunctions/CountingRegion.h
Mismatched class declaration and file name
No Unit Test.
typdef vs using
Inherits from QMCTraits
Has template parameter it doesn't use.

**Comment by ye-luo** [comment]
@bwvdg Could you have a look?

**Comment by bwvdg** [comment]
I made the appropriate code convention changes. I'm currently writing the unit tests for these classes and will submit a pull request soon.

**Comment by ye-luo** [comment]
Unit test inplace
