### ISSUE TITLE
Replace FindLibxml2QMC.cmake by standard cmake find_package

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1687]
Support for libxml2 is much better than when libxml2 integration was first implemented and I suggest/question whether our custom code is needed any more. 

- Directly calling find_package(LibXml2) worked on both oxygen and summit and correctly picked up e.g. spack installed versions of LibXml2, unlike the existing code.
- Nearly all our build recipes use the default LibXml2 location, which the CMake package should pickup. The Blue Gene toolchains are the only active examples with customization, but the existing cmake_find_root_path should continue to work.

**Comment by ye-luo** [comment]
`git log FindLibxml2QMC.cmake` you wrote that this was motivated by Cray breakage on Cori at NERSC. If you can verify that Cori builds fine, we should remove our own customization.

**Comment by prckent** [comment]
Good point. Checking. Hopefully the Cray env is less quirky now.

**Comment by prckent** [comment]
Cori is fine.
