### ISSUE TITLE
gofr estimator gives incorrect results for SoA

### ISSUE THREAD

**Issue by jptowns** [QMCPACK/qmcpack#1699]
Related to #396 and #392 and #984.

AoS versions of the estimator on the HEG give expected results:
![aos_n64_gofr](https://user-images.githubusercontent.com/25334555/60619597-49c7d900-9d96-11e9-9825-0d6ab7cccd9c.png)

But SoA versions of the estimator do not have the appropriate normalization:
![soa_n64_gofr](https://user-images.githubusercontent.com/25334555/60619653-5fd59980-9d96-11e9-87a6-b80daeedadaf.png)

This behavior is not unique to the HEG, I've also seen it in FeO.
This was test on QMCPACK built on 28 June commit number
ba0e62ad98ece9c81555a8750de4e28612fc4dd2, using clang 3.9.0 on a small linux workstation.

**Comment by jtkrogel** [comment]
@markdewing I just assigned this issue to you per discussions at the ECP meeting.  Is this OK with you?

**Comment by markdewing** [comment]
Yes, this is okay with me.

**Comment by jptowns** [comment]
@jtkrogel @ye-luo I have a working implementation for SoA, but now AoS is broken. How important is it to have AoS working?

**Comment by jtkrogel** [comment]
@jptowns AoS is not important going forward.  It would be good, however, to have a test made with an older AoS version, PR it, and then make a PR with the SoA update.

**Comment by prckent** [comment]
My 2c: I think it is unimportant to have working AoS. I don't know of anyone using g(r) in production, but we do wish to use it in future, which means SoA is the priority. What is important is to have a test so that this problem will not recur.

**Comment by jptowns** [comment]
OK. I'll write a test and then submit a PR with the SoA fix and test.

**Comment by jtkrogel** [comment]
For an example of making estimator tests, see the discussion in the diamondC_1x1x1_pp README file relating to the spin density: 

https://github.com/QMCPACK/qmcpack/blob/develop/tests/solids/diamondC_1x1x1_pp/README

**Comment by markdewing** [comment]
I'm concerned that this means something is not fully understood and expressed in the code about
1. how to compute g(r)
2. The differences between AoS and SoA handling of distance tables

Submitting the SoA change as a PR will make it easier for other people to look at the code.

**Comment by markdewing** [comment]
I have a general question about the differences in using distance tables in AoS vs. SoA.  Are these differences documented anywhere?  Is there any guide on how to use the distance tables?

A more specific form of the question: The current PairCorrEstimator::evaluate function contains an if-block for the DT_SOA distance tables.  Why doesn't the AOS branch work out of the box?  What functions or data access to the distance table are no longer valid in SOA?
Possibly a question for @ye-luo

**Comment by jtkrogel** [comment]
@jptowns @markdewing Any updates?
