### ISSUE TITLE
short-afqmc-N2_vdz-4-1 failing

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1717]
I only tried the real build.
$ ctest -j16 -R short-afqmc-N2_vdz-4-1
Test project /sandbox/opt/cleanup/yeluo/build_cpu_soa
    Start 1126: short-afqmc-N2_vdz-4-1
1/2 Test #1126: short-afqmc-N2_vdz-4-1 ...........***Failed    0.08 sec
    Start 1127: short-afqmc-N2_vdz-4-1-Eloc
2/2 Test #1127: short-afqmc-N2_vdz-4-1-Eloc ......***Failed    0.03 sec

Error in the output.
Error: Unknown WalkerSet type in WalkerSetFactory::buildHandler().

**Comment by fdmalone** [comment]
There appear to be some very old test inputs in the repository which shouldn't work at the moment due to relying on plain text FCIDUMPs or have old input files. I'll remove these.
