### ISSUE TITLE
Mixed precision Intel 2018 unit test Hamiltonian is failing

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1726]
e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=5549659&build=67231

Perhaps a precision issue since only this build is failing.

**Comment by ye-luo** [comment]
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_hamiltonian&date=2021-03-21
