### ISSUE TITLE
Deterministic integration tests for CUDA code: add reference data or disable?

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1729]
Currently the deterministic tests are run for the legacy CUDA code. Necessarily they will always fail due to the different numerics. i.e. We rely on the statistical integration tests for correctness and to detect meaningful change.

It would be helpful to (1) have the deterministic tests always work ("ctest -L deterministic") and (2) catch changes on Volta, which I think is a safe reference for now. Do we add reference data or disable the numerical checks for now?

**Comment by jtkrogel** [comment]
I vote for adding data for at least a subset of the deterministic tests.

**Comment by ye-luo** [comment]
Let us do disabling first. It is basically adding if-else which will be anyway needed for adding a separate set for CUDA.

**Comment by Hyeondeok-Shin** [comment]
I'm going to work with separated deterministic test for CUDA code as @jtkrogel mentioned. As a first step, I'll disable the deterministic test for CUDA with the current reference now as @ye-luo comment in order to avoid confusion.

**Comment by ye-luo** [comment]
Legacy CUDA has been removed from the code base https://github.com/QMCPACK/qmcpack/pull/4431
