### ISSUE TITLE
Deterministic test with multi DMC sections

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1738]
We need a test to mimic users running multiple DMC sections with reducing time step.
Probably extend one of the existing test to include another DMC section with half timestep.

**Comment by prckent** [comment]
This is also needed to reasonably check changes like #1704. Currently there are no tests with repeated driver sections. We have vmc->dmc but not vmc->dmc->dmc->dmc which requires reuse or recreation of the drivers and walker info correctly.

**Comment by PDoakORNL** [comment]
The test also cannot just test the final result, it should at least nominally check if all expected files are created and contain the correct data.

**Comment by PDoakORNL** [comment]
I'm satisfied with the test added by PR 1764
