### ISSUE TITLE
Reading in a custom external potential defined on a grid.

### ISSUE THREAD

**Issue by kryczko** [QMCPACK/qmcpack#1746]
Hi all,

I presently have a script written in python to generate a custom external potential. I would like to then read in this potential to qmcpack (via whatever method is easiest i.e. hdf5 seems to be built in) and then perform VMC calculations of electrons interacting with this external potential. Does anyone have ideas what the best/easiest way to do this is?

Kevin

**Comment by markdewing** [comment]
The simplest example of an external potential is probably a harmonic potential in `src/QMCHamiltonians/HarmonicExternalPotential.{h,cpp}`.   An example input using the potential is in `tests/models/sho/vmc_sho.xml`.

HDF files are read using hdf_archive in `src\io`.

This isn't much guidance, but it's a place to start looking.

**Comment by kryczko** [comment]
I saw those files, but the SHO potentials are centred about the atoms and the potential still depends on positions of the particles. Since I don't have an analytic form for external potentials, I would need to have my potential defined numerically on a grid.

**Comment by markdewing** [comment]
See PR #1756 for an example on creating a grid-based potential.    It reuses the existing einspline code to do spline interpolation of values in 3D.

**Comment by kryczko** [comment]
Thanks for providing that code, it looks like it will be very useful. I'm thinking in my case, I would do exactly the same, except my data Array would now consist of the potential I would read in from an hdf5 file. Does that sound like it would do the trick? Is there visualization tools I could use to make sure everything is as it should be?

**Comment by markdewing** [comment]
Reading 'data' from hdf5 should work.  I'm working on updating the example to read from a simple hdf file.

**Comment by kryczko** [comment]
Great, I look forward to seeing the code.

**Comment by markdewing** [comment]
PR is updated.   The name of the file and all the dimensions are fixed in the source, which should be good enough to get started.
I don't know about visualization  - you could make a loop and print out the results of eval_UBspline_3d_d to a file.

I've been using the harmonic potential on the grid to ensure the code gives the same answer as the existing harmonic potential.  In the input file I set the random seed ( `<random seed="1"/>`) and set the mass and energy are 1.0.

**Comment by kryczko** [comment]
Great, sounds good. What is the block of xml that is going into the input file? Should it be something like:
```
<hamiltonian ... >
  <extpot type="GridExt" />
  ...
</hamiltonian>
```

**Comment by markdewing** [comment]
The type of extpot is the value tested in HamiltonianFactory.cpp - `grid` in this case.  So the xml input would look like
```
<hamiltonian>
  <extpot type="grid" />
</hamiltonian>
```

**Comment by kryczko** [comment]
Awesome, I was able to compile and run successfully. Now that it has been read in I'm guessing that data must be replaced with the data that is in the hdf_archive object. Is this true? I.e.

```
Array<double, 3> data(grid.num, grid.num, grid.num);
spline_data = create_UBspline_3d_d(grid, grid, grid, 
                                     BC, BC, BC, data.data());
```
should be replaced with something like
```
data = [grid.num][grid.num][grid.num]
spline_data = create_UBspline_3d_d(grid, grid, grid, 
                                     BC, BC, BC, hin.readEntry(data, "pot_data");
```

**Comment by markdewing** [comment]
D'oh! I must have accidentally deleted that line before checking in.  The branch is updated.
The line is
```
hin.read(data, "pot_data");
```

The hdf_archive object has code that will automatically read in various data types.   See `src/io/tests/test_hdf_archive.cpp` for some examples.

**Comment by kryczko** [comment]
Oh okay great, I had a look in that file and did not see an Array object being read/written. With your code above it looks like you can directly read it into this Array object. Looks good to me. Thanks for all of your help. I'm going to fork your repository and make some changes. What is the best way to have my changes included in the codebase (after it has been approved of course)?

**Comment by kryczko** [comment]
In addition, I would like to add the ability to include periodic boundary conditions. How would I go about doing that?

**Comment by markdewing** [comment]
The best way to submit changes is to create a new branch and make a pull request from that branch.  The biggest different from the usual github workflow is 'develop' is the main branch, not 'master'.

Longer description is on the wiki: https://github.com/QMCPACK/qmcpack/wiki/Development-workflow#workflow-process

The einspline library can handle periodic boundary conditions.  Change BC.{l|r}Code to PERIODIC. (see `src/einspline/bspline_base.h`

**Comment by kryczko** [comment]
awesome, thanks for all of your help.

**Comment by prckent** [comment]
I'll note that this facility would also be useful for embedding methods, model calculations etc. A good feature to have.

**Comment by ye-luo** [comment]
Seems related to #2164

**Comment by ye-luo** [comment]
#2164 has been merged. @kryczko thank you.
