### ISSUE TITLE
Broken CUDA deterministic tests

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1776]
e.g. https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=70893

These need investigating. Could be a tolerance issue or a sign of unreliability.

**Comment by Hyeondeok-Shin** [comment]
@prckent It seems larger tolerance with mixed precision in oxygen than the other environment. (I didn't check on oxygen when making tolerance.) I also found tolerance on MPC for DMC cycle 2 on DMC multisection on CUDA build is missing, so I'll fix them.

**Comment by ye-luo** [comment]
I'd like to have a multi VMC/DMC tests with 2 VMC sections and 2 walkers. Is it better to have a separate test or expand the existing test?

**Comment by prckent** [comment]
@Hyeondeok-Shin we have a Volta now, but I recall you tested on Volta...

@ye-luo It is cheap to add tests and knowing that a 1 walker test passes but a 2 walker test does not would be helpful => separate tests. I assume you are concerned about logic errors in the legacy CUDA?

**Comment by ye-luo** [comment]
@prckent my concern is from the restart test fix I just submitted. 1 walker per thread and 2 walkers per thread is different. Current deterministic tests run with only 1 thread.

**Comment by prckent** [comment]
Understood. More tests then. 

(I'll take back part of my comment about the tests being cheap: our run time for the deterministic tests that run QMC is surprisingly long given the tiny system size and few steps, often a few seconds. We might profile them sometime to see if there is an easy win.)

**Comment by Hyeondeok-Shin** [comment]
@prckent @ye-luo I'll make separated PR for fixing the problem and 2 walkers for thread.

**Comment by Hyeondeok-Shin** [comment]
@prckent I'd like to keep watching more test results on oxygen(Tesla V100-PCIE-32GB). There are three reasons.

 1. I double-checked test but they're obviously passing on summit. (Tesla V100-SXM2-16GB)
 2. Tolerances on oxygen are too large compared to the other environment.  
 3. In oxygen, the same testsets are failing also on the full-precision build.

 It seems not a simple tolerance issue in the mixed precision. Only oxygen with Tesla V100-PCIE-32GB is giving significantly different references to the others. It needs more discussions.

 I'll make PR for missing tolerance for MPC soon.

**Comment by ye-luo** [comment]
All looks fine now https://cdash.qmcpack.org/CDash/viewTest.php?onlypassed&buildid=196096
