### ISSUE TITLE
BGQ clang and oxygen clang unit test Hamiltonian is failing

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1779]
unit test Hamiltonian is failing but not for a wrong value.
https://cdash.qmcpack.org/CDash/testDetails.php?test=5740567&build=70990
This started 2 days ago and #1771 is the only PR get in that day.

**Comment by rcclay** [comment]
So the test is just timing out?

**Comment by rcclay** [comment]
I'll attack this after the all-hands meetings.  I forgot my ORNL fob.

**Comment by ye-luo** [comment]
I explored the issue on BGQ during the weekend. The timeout was caused by an infinite loop when istringstream parses a string and causes a failbit instead of eof. Unfortunately, I cannot reproduce this issue on my workstation. I'm wondering if this is related to specific versions of libstdc++.
