### ISSUE TITLE
Calculation with SHO potential defined on a grid with eigenstates from QBox 

### ISSUE THREAD

**Issue by kryczko** [QMCPACK/qmcpack#1791]
Dear developers,

I have issues when I try to use a simple harmonic oscillator potential defined on a grid in an HDF5 file along with eigenstates calculated with QBox. The code I am using is a fork from @markdewing for reading in an external potential. I am getting NANs when I run VMC calculations. I've also removed an abort call because I have no ions in the Qbox text file that has been serialized, QMCPACK by default exits when it does not find ions. This may be why I am getting NANs, but I'm not sure what a work around would be.

I have also found out that using a very low timestep reduces the NANs, but doesn't fully get rid of them.

I have tested that the external potential reading from HDF5 indeed works, I was able to reproduce the same values as the SHO built into QMCPACK.

I have attached a tarball containing my qbox calculations (done with the version found at https://github.com/qboxcode/qbox-public). I then use `convertpw4qmc` to convert the eigenstates into the QMCPACK format. Also within the tarball are my QMCPACK calculations. 

Please let me know if anyone has an idea what is going on here. All of my file can be found here: https://drive.google.com/file/d/1rcVQNX2tYkiwNEV7QKfdu_FgaXbrbq4B/view?usp=sharing

Thanks,
Kevin

**Comment by markdewing** [comment]
The Grid energy in the qmc.s000.scalar.dat file becomes very large in the second step.  One idea is to print the electron coordinates and the grid values in 'evaluate' function and see where they go bad.

It looks like the simulation is using periodic boundary conditions.   The example spline code I gave uses open boundary conditions.   The BC.lCode value should be updated to PERIODIC for PBC.   The number of grid points and it's relationship to delta might change in this case, too.

**Comment by kryczko** [comment]
The updated file I am using is here: https://github.com/kryczko/qmcpack/blob/add_external_potential/src/QMCHamiltonians/GridExternalPotential.cpp

This allows one to set the periodicity in the potential dynamically. 

Maybe I made an error here. You can let me know if I have.

**Comment by markdewing** [comment]
delta might need to not have the -1 in the denominator for the periodic case
`double delta = (grid.end - grid.start)/(grid.num);`

**Comment by kryczko** [comment]
ah, good catch. I'll report back!

**Comment by kryczko** [comment]
The delta doesn't seem to be used anywhere else in the code, should this be the case?

**Comment by kryczko** [comment]
I'm a bit confused now after printing out the coordinates and the value associated at the coordinates:

```
double val = 0.0;
eval_UBspline_3d_d(spline_data, r[0], r[1], r[2], &val);
app_log() << "Coordinates: " << r[0] << " " << r[1] << " " << r[2] << " " << val << std::endl;
app_log() << "Value: " << val << std::endl;
```

If the cell is from 0 to 16 in each direction, should I expect to only see coordinates from the range [-8, 8] ?

**Comment by markdewing** [comment]
PBC needs to be applied to the coordinates.  This might work:
`P.Lattice.applyMinimumImage(r);`

The code that uses einspline for SPO wavefunctions converts the coordinates to a unit cell and than applies PBC corrections.

**Comment by kryczko** [comment]
that did the trick! 

I don't follow your last comment. I don't know what the acronym SPO is.

**Comment by markdewing** [comment]
SPO = Single Particle Orbital.
