### ISSUE TITLE
SoA ports needed for Chiesa/Ceperley and Bare force estimators

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1795]
This issue was reported by @tiihonej.  Juha, please can you elaborate which specific classes need to be ported over?

**Comment by tiihonej** [comment]
Yes, so I have recently been testing all the available force estimators with the latest development branch of QMCPACK. Currently, there are 6 “modes” available, but I’ll leave out “stress”, which seems to be another topic (also, it doesn’t work): “acforce”, “bare”, “zero_variance”, “cep” (Ceperley/Chiesa) and “pulay”. 

Here’s an overview of the said estimators regarding their AoS/SoA porting. All the files are located in ‘src/QMCHamiltonians/’

ACForce
-ACForce.*
-SoA works (AoS does not; localECP forces)

Ceperley/Chiesa
-ForceCeperley.*, ForceChiesaPBCAA.*
-SoA works (Aos does not; localECP forces)
-the tentative results are way off, though, but that’s another topic!

Bare
-ForceBase.*
-SoA not implemented (fails at BareForce constructor)

Pulay
-PulayForce.*
-SoA not implemented (fails at PulayForce constructor)

Zero-variance
-ZeroVarianceForce.*
-SoA not implemented (fails at constructor)

From what I can tell, all the estimators are at least slightly different, but there is also a lot overlap. For instance, “zero_variance” estimator produces  Hellman-Feynman force with zero-variance corrections. “ACForce” does exactly the same but also adds zero-bias corrections - using exactly the same components as the “pulay” estimator (yet the “pulay term” of ACForce has a different meaning)! More or less, anyway.

The point is, there is a lot of redundancy, conflicting naming, deprecated code to keep up with latest developments. An alternative ideal would be one, maybe two, well-documented force tools. I think that should be considered before porting everything to SoA.

**Comment by rcclay** [comment]
Here's my understanding of the status of the classes mentioned:
1.) ACForce:  Only implemented for SoA, and only works when used with pseudopotentials.  I don't know what would happen if you tried to do all electron with it...  at best it would be mathematically ill posed due to infinite variance problems.  At worse, it would crash.
2.)  ForceChiesaPBCAA:  This is only well posed for all-electron calculations.  It should work with SoA provided one uses EwaldHandler3D for the long range piece.  Should be tested in case ACForce implementation broke this.
3.)  ForceBase (Bare):  Don't use this.  Force evaluation calls in this base class should APP_ABORT.
4.)  Pulay:  Deprecated. Should be removed.
5.)  Zero variance:  Deprecated.  Should be removed.

**Comment by jtkrogel** [comment]
@rcclay So for the AoS to SoA transition, you are basically saying there are two main actions items (right?):
* Check that (or fix so that) ForceChiesaPBCAA gives the same results for an all electron system in AoS and SoA when used with EwaldHander3D (is there another use case that uses something other than the Ewald handler?)
* Remove the old pulay and zero variance AoS estimators

Separately, the Chiesa force implementation needs to be checked/fixed for overall correctness, but this is not technically an AoS/SoA issue.

**Comment by rcclay** [comment]
@jtkrogel That is correct.

**Comment by rcclay** [comment]
I can pass you and Juha some finite difference tests I have for Li and H.

**Comment by tiihonej** [comment]
Please do. I can help with testing CCZ/AC force estimators regarding AoS/SoA. It's good to narrow down a bit, but who will be responsible for removing the obsolete estimators? I think it would be a good idea to implement bare Coulomb potential for AC in the future. To my experience, it now returns zeros at least with OBC.

It sounds like LR evaluation is another big issue. I'll report if I find something curious about it, but for starters I'm open to suggestions about a safe starting point. By default, I'll be using EwaldHandler3D.

**Comment by rcclay** [comment]
@tiihonej I will think about how best to have bare coulomb and pseudopotentials in one easy to use estimator.  For now, the Chiesa forces are the "bare" coulomb forces.
