### ISSUE TITLE
Remove old ADIOS code

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1802]
The old ADIOS implementation should be removed ahead of cleanup work to TraceManager. It has not been run for some time, has no tests, and is believed not working. 

@jtkrogel Reassign or remove yourself as you wish.

**Comment by grahamlopez** [comment]
@jtkrogel have you done anything on this yet, or have any thoughts about it? I was going to check in on it if you aren't already finished with it.

**Comment by jtkrogel** [comment]
I was going to make a test for TraceManager before doing this, but as I won't get to this for a while you can go ahead.

As an aside I'll note as well that there is (or at least was) also ADIOS code in the checkpoint/restart area of QMCPACK.

I guess all the relevant code is behind ifdefs?  If so, then removal should be rather safe.  If you proceed, let me know when the PR is in and I will give it a look over.

**Comment by grahamlopez** [comment]
Okay, I have noticed these two spots that you mention, but most is behind ifdefs. I'll let you know how it turns out.
