### ISSUE TITLE
cmake configuration error on python3

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1807]
Since linux distro keep python name for python2.
On a fresh ubuntu 18.04.3, python3 is installed but our cmake complains.
```
/usr/bin/env: ‘python’: No such file or directory
Warning: test labeling failed.  Test labeling error output:
```

**Comment by jtkrogel** [comment]
Until the dust settles a little from the retirement of Python 2, no single invocation of Python will work for all environments.

I think the safest thing is to make the Python scripts in the build system compatible with both Python 2 and 3 (should be pretty easy) and keep the default interpreter as "`python`" (`#! /usr/bin/env python`).

I think this will work in most environments.  Perhaps we should survey at some point and see if having only `python3` as the interpreter is more common than `python`.

To support environments where our default choice of interpreter is not present, I suggest we add a flag to our CMake (`PYTHON_INTERP`?) so the user can specify the name of a Python interpreter available on their system.

Another option is to remove Python entirely from the build system if this is deemed too fragile or inconvenient.

Thoughts?

**Comment by ye-luo** [comment]
The whole qmcpack repo has been updated to use "#! /usr/bin/env python3" shebang.
