### ISSUE TITLE
Counting Jastrow Segfaults

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1831]
See: https://cdash.qmcpack.org/CDash/testDetails.php?test=5992019&build=75823

**Comment by bwvdg** [comment]
I recently found and pushed a change in #1695 to in a bug in CountingJastrow.makeClone that produced segfaults only when using multiple threads. I believe this should fix the problem.

**Comment by ye-luo** [comment]
Everything looks good.
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2020-01-02&limit=0&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=short-H4-cjs
