### ISSUE TITLE
Unstable nightlies are broken

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1832]
All the intermittently failing (a.k.a. unstable) statistical integration tests are being run incorrectly.

All now fail with errors similar to:
```
scalar file does not exist: qmc_short_vmc_all_nodrift.s000.scalar.dat
Test status: fail
```

See:
https://cdash.qmcpack.org/CDash/index.php?project=QMCPACK&date=2019-08-27#!#Unstable

This is likely due to the removal of the unstable label from the parent process in #1825.  While semantically correct (the main execution of QMCPACK should always be successful), running only unstable tests for the unstable dashboard now excludes execution of the main QMCPACK process while keeping execution of the test checking scripts.

A straightforward solution is to add a unique label to these processes and explicitly include them when running tests for the unstable dashboard.

**Comment by ye-luo** [comment]
The reorder change seems working.
