### ISSUE TITLE
Jastrow optimization causes large errors and biases in ACForce

### ISSUE THREAD

**Issue by tiihonej** [QMCPACK/qmcpack#1847]
After recent developments ACForce estimator for VMC is very accurate for LCAO, no Jastrow (see Fig. 1; the biggest error is due to morse potential fit, but we'll be able to do better). The salvation is in the zero-bias correction (wavefunction-gradients) on top of variance-reduced Hellmann-Feynman terms. The test case is LiH (OBC) with ccECP-VDZ and GAMESS trial wavefunction.

[Fig 1: fig1_forcediff_noj.pdf](https://github.com/QMCPACK/qmcpack/files/3552813/fig1_forcediff_noj.pdf)

Adding Jastrow leads to better energies but also large errors in force estimates. According to Fig. 2 (internal validation: difference between forces and energy fit derivatives) there is systematic error, which seems to depend on radius and the optimization scheme, and can be as large as ~100%. The error is probably related to the trial-wf quality, but its origins are unknown: it could be a bug or something fundamental, which needs a different correction. More tests are on the way.

[Fig 2: LiH_obc_gms_scfJ_Fdiff.pdf](https://github.com/QMCPACK/qmcpack/files/3552971/LiH_obc_gms_scfJ_Fdiff.pdf)

Fig. 3 is the sum of forces on the two ions, Li and H. It should be zero, which reassuringly is the case with the ZVZB estimate. This suggests that the ACForce estimator is correct. On the other hand, ZV forces (and thus, ZB corrections) have large biases, which cannot be a good thing.

[Fig 3: LiH_obc_gms_forces_opt2.pdf](https://github.com/QMCPACK/qmcpack/files/3552957/LiH_obc_gms_forces_opt2.pdf)

Whatever the reason is, the Jastrow-sensitivity of forces is much greater than that of energies. This calls for special attention to stability and determinism in the optimizer.

The attached figures are not the whole picture, but I welcome any questions and discussion. I will keep updating here whenever something comes up.

**Comment by rcclay** [comment]
Can you drop the raw data used for making these plots somewhere?

**Comment by tiihonej** [comment]
I can send you some data. Do you just want the numeric data for the plots or the VMC raw data?

**Comment by rcclay** [comment]
Probably both.

**Comment by tiihonej** [comment]
Update on this issue:

It appears that the main cause of error is the Jastrow optimization process. If the Jastrow is not optimized properly (i.e. variational minimum is not reached), extra corrections to forces are needed.

[Attached](https://github.com/QMCPACK/qmcpack/files/3611615/F-error_vs_VE-Ratio.pdf) is a figure that shows correlation between variance/energy ratio and the relative error in forces for various systems. (The latter is calculated by (Fscf - Fzvzb)/Fion, which in this case is a practical although not strictly foolproof reference quantity; the ionic force Fion is used to normalize the scale between different systems). The V/E ratio is an indicator of the optimizer performance. Clearly deficiency in optimization has a huge effect on the forces, especially in homogenous dimer cases, where there are fewer degrees of freedom for J1.

On the bright side, inhomogenous systems are pretty accurate. (Also, without Jastrow, ie mean-field WF, the errors in forces are negligible in comparison.) This indicates that there are no bugs in the code related to Jastrow-forces. Rather, more effort is called for in the optimization, be it improvements in the optimizer or just its end-user.

The alternative or complementary path forward is to do explicitly the corrections mentioned in the beginning. The theory is clear enough, but the practical side needs more background work.

**Comment by prckent** [comment]
Are the different points on the most recent graph all with different Jastrow functions or are any with no Jastrow?

**Comment by tiihonej** [comment]
I forgot to mention: the different points represent different separations.

Assuming effect of the separation itself small, variation of the points of given color in x-axis indicates fluctuation of independent optimizer outcomes. Nevertheless, there seems to be linearity in the force error and the magnitude of variance.

Another curious detail: LiH with VDZ basis has bad performance compared to the same basis augmented with only a few diffuse orbitals (aug-VDZ). Otherwise the simulation is exactly the same.

**Comment by jtkrogel** [comment]
My best understanding of the force error shown in the plots is our neglect of or inability to account for how the force depends on changes in the Jastrow parameters (implicit dependence, involves derivatives of Jastrow coeffs w.r.t. ion positions).  

This term is basically (in one dimension) dE/dp*dp/dr, where p represents parameters/coefficients, E is the energy and r the ion positions.  If we have an optimized wavefunction, then dE/dp=0 and the remaining implicit dependence (dp/dr) is irrelevant.

@rcclay Is anything missing from this interpretation?  Are there other things we can do to minimize this?  For example, would spacewarp have an impact since it includes an approximation of how the wavefunction changes with the ion positions?

**Comment by jtkrogel** [comment]
Reposting as image so it is easier to see:

![F-error_vs_VE-Ratio-1 png-1](https://user-images.githubusercontent.com/24547905/64956195-0ab70900-d858-11e9-859b-02102da91276.png)

@tiihonej For the points that are most accurate (Ferr/Fion < 1%), could you list or plot them in absolute units (e.g. eV/Angstrom)?

**Comment by tiihonej** [comment]
Here's some more figures:

Below are the absolute errors (in mHa/bohr ~ 51.4 meV/Angstrom) of the most accurate simulations. The forces, and thus, the fluctuations of CO are two orders of magnitude larger. It should be noted that the "error" with respect to SCF forces is not necessarily a well-defined reference at these magnitudes. I'm working on better data to perform reliable fits to local energy.
![F-error_vs_E-Ratio_zoom](https://user-images.githubusercontent.com/12646540/64965951-e2d1a080-d86b-11e9-9887-3d126593120f.png)

The next figure has the relative errors of no-Jastrow simulations. The variance is larger to begin with, but since there are no Jastrow-DOF, the forces are essentially correct.
![F-error_vs_E-Ratio_noJ](https://user-images.githubusercontent.com/12646540/64966945-b9b20f80-d86d-11e9-8dc3-55106ff4b5f7.png)

Last, there was an experiment to correct the poorly performing LiH (VDZ+J12; blue) so that the Jastrows were replaced (green) with those optimized using well-performing aug-VDZ (orange). This helps "half-way", but not entirely.
![F-error_vs_E-RatioLiH2](https://user-images.githubusercontent.com/12646540/64967426-786e2f80-d86e-11e9-8d5b-4ee139e489da.png)

**Comment by jtkrogel** [comment]
@tiihonej and @rcclay I just realized that these errors might alternately relate to statistical bias.  The linearity with variance is particularly suspect.

@tiihonej Would you take a poorly performing (large force error) case (single qmcpack run) of each of LiH (aug-V5Z) and CO (aug-VTZ) and gather 100x more statistics?  If there is statistical bias, we should see the new force mean with 10x smaller error bars move outside the range predicted by the shorter run.

**Comment by tiihonej** [comment]
Closing the issue, since it's not likely an actual bug.

**Comment by jtkrogel** [comment]
This issue is not resolved.  Currently, Jastrow factors obtained following optimization are not sufficient to minimize the error in the forces to an acceptable level.

Since we do not have any other route to remove the bias, this is a bug.

**Comment by tiihonej** [comment]
Closing the issue. Recent careful calculations have given confidence that this is indeed a theoretical property, not a code bug.
