### ISSUE TITLE
CUDA build determinstic tests failing

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1848]
Since Aug 21.
https://cdash.qmcpack.org/CDash/testDetails.php?test=5937151&build=74769
It seems that some changes in #1810 triggered this.
The broken code actually was running the CPU driver with DiracDeterminantCUDA wavefunction.
Some piping issue.

**Comment by PDoakORNL** [comment]
I have not done enough testing with ENABLE_SOA=0 this might have to be a fixed in the cmake.  Will fix.

**Comment by ye-luo** [comment]
This issue exists with both ENABLE_SOA=0 and 1. It is caused by QMC_CUDA=1.

**Comment by PDoakORNL** [comment]
@markdewing caught this in the #1810 review I promised a subsequent PR and did not deliver.
