### ISSUE TITLE
Incorrect number of twists are generated via pw2qmcpack.x

### ISSUE THREAD

**Issue by kayahans** [QMCPACK/qmcpack#1851]
Hi, 

I am trying to generate the wavefunction using the attached simple nexus script. KPOINTS card in the QE input file corresponds to 3x3x3 cell, hence it is the following: 

> K_POINTS crystal
   27
         0.00000000       0.00000000       0.00000000       1.00000000
         0.33333333       0.00000000       0.00000000       1.00000000
         0.66666667       0.00000000       0.00000000       1.00000000
         0.00000000       0.33333333       0.00000000       1.00000000
         0.33333333       0.33333333       0.00000000       1.00000000
         0.66666667       0.33333333       0.00000000       1.00000000
         0.00000000       0.66666667       0.00000000       1.00000000
         0.33333333       0.66666667       0.00000000       1.00000000
         0.66666667       0.66666667       0.00000000       1.00000000
         0.00000000       0.00000000       0.33333333       1.00000000
         0.33333333       0.00000000       0.33333333       1.00000000
         0.66666667       0.00000000       0.33333333       1.00000000
         0.00000000       0.33333333       0.33333333       1.00000000
         0.33333333       0.33333333       0.33333333       1.00000000
         0.66666667       0.33333333       0.33333333       1.00000000
         0.00000000       0.66666667       0.33333333       1.00000000
         0.33333333       0.66666667       0.33333333       1.00000000
         0.66666667       0.66666667       0.33333333       1.00000000
         0.00000000       0.00000000       0.66666667       1.00000000
         0.33333333       0.00000000       0.66666667       1.00000000
         0.66666667       0.00000000       0.66666667       1.00000000
         0.00000000       0.33333333       0.66666667       1.00000000
         0.33333333       0.33333333       0.66666667       1.00000000
         0.66666667       0.33333333       0.66666667       1.00000000
         0.00000000       0.66666667       0.66666667       1.00000000
         0.33333333       0.66666667       0.66666667       1.00000000
         0.66666667       0.66666667       0.66666667       1.00000000

However, pw2qmcpack.x prints 63 k-points. First 27 k-points are identical as in the QE input, then the new ones seem to be added:
`for i in {0..62}; do h5ls -d pwscf.pwscf.h5/electrons/kpoint_$i/reduced_k | tail -1; done &> tmp`

>(0) 0, 0, 0
        (0) 0.33333333, 0, 0
        (0) 0.66666667, 0, 0
        (0) 0, 0.33333333, 0
        (0) 0.33333333, 0.33333333, 0
        (0) 0.66666667, 0.33333333, 0
        (0) 0, 0.66666667, 0
        (0) 0.33333333, 0.66666667, 0
        (0) 0.66666667, 0.66666667, 0
        (0) 0, 0, 0.33333333
        (0) 0.33333333, 0, 0.33333333
        (0) 0.66666667, 0, 0.33333333
        (0) 0, 0.33333333, 0.33333333
        (0) 0.33333333, 0.33333333, 0.33333333
        (0) 0.66666667, 0.33333333, 0.33333333
        (0) 0, 0.66666667, 0.33333333
        (0) 0.33333333, 0.66666667, 0.33333333
        (0) 0.66666667, 0.66666667, 0.33333333
        (0) 0, 0, 0.66666667
        (0) 0.33333333, 0, 0.66666667
        (0) 0.66666667, 0, 0.66666667
        (0) 0, 0.33333333, 0.66666667
        (0) 0.33333333, 0.33333333, 0.66666667
        (0) 0.66666667, 0.33333333, 0.66666667
        (0) 0, 0.66666667, 0.66666667
        (0) 0.33333333, 0.66666667, 0.66666667
        (0) 0.66666667, 0.66666667, 0.66666667
        (0) -0.33333333, 0.33333333, 0
        (0) -0.66666667, 0.33333333, 0
        (0) -0.33333333, 0.66666667, 0
        (0) -0.66666667, 0.66666667, 0
        (0) -0.33333333, 0, 0.33333333
        (0) -0.66666667, 0, 0.33333333
        (0) 0, -0.33333333, 0.33333333
        (0) -0.33333333, -0.33333333, 0.33333333
        (0) -0.33333333, 0.33333333, -0.33333333
        (0) 0.33333333, -0.33333333, -0.33333333
        (0) -0.66666667, -0.33333333, 0.33333333
        (0) -0.66666667, 0.33333333, -0.33333333
        (0) 0.66666667, -0.33333333, -0.33333333
        (0) 0, -0.66666667, 0.33333333
        (0) -0.33333333, -0.66666667, 0.33333333
        (0) -0.33333333, 0.66666667, -0.33333333
        (0) 0.33333333, -0.66666667, -0.33333333
        (0) -0.66666667, -0.66666667, 0.33333333
        (0) -0.66666667, 0.66666667, -0.33333333
        (0) 0.66666667, -0.66666667, -0.33333333
        (0) -0.33333333, 0, 0.66666667
        (0) -0.66666667, 0, 0.66666667
        (0) 0, -0.33333333, 0.66666667
        (0) -0.33333333, -0.33333333, 0.66666667
        (0) -0.33333333, 0.33333333, -0.66666667
        (0) 0.33333333, -0.33333333, -0.66666667

pwscf.xml also has the same data as the QE input file:

> <k_points_IBZ>
      <nk>27</nk>
      <k_point weight="1.000000000000e0">0.000000000000000e0 0.000000000000000e0 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 0.000000000000000e0 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 0.000000000000000e0 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 1.580913739113948e-3 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 1.580913739113948e-3 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 1.580913739113948e-3 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 3.161827525655309e-3 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 3.161827525655309e-3 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 3.161827525655309e-3 0.000000000000000e0</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 0.000000000000000e0 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 0.000000000000000e0 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 0.000000000000000e0 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 1.580913739113948e-3 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 1.580913739113948e-3 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 1.580913739113948e-3 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 3.161827525655309e-3 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 3.161827525655309e-3 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 3.161827525655309e-3 1.449170927930246e-3</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 0.000000000000000e0 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 0.000000000000000e0 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 0.000000000000000e0 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 1.580913739113948e-3 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 1.580913739113948e-3 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 1.580913739113948e-3 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">0.000000000000000e0 3.161827525655309e-3 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">1.633192633370169e-3 3.161827525655309e-3 2.898341899335621e-3</k_point>
      <k_point weight="1.000000000000e0">3.266385315736117e-3 3.161827525655309e-3 2.898341899335621e-3</k_point>
    </k_points_IBZ>

I am using QE 6.3 that is compiled using DFLAGS         =  -D__DFTI -D__MPI -D__SCALAPACK -D__LIBXC -D__HDF5 -DH5_USE_16_API,  hdf5_parallel_1.10.3 and intel/18.0.0. 

Thanks,
Kayahan

[lacoo3_test.zip](https://github.com/QMCPACK/qmcpack/files/3555835/lacoo3_test.zip)

**Comment by jtkrogel** [comment]
This is fixed by setting `nosym=.true.`.  Closing.
