### ISSUE TITLE
short-li2_sto-sj_dmc crashing

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1853]
https://cdash.qmcpack.org/CDash/testDetails.php?test=6012652&build=76238
Caused by #1820 not improved by #1841 
@tiihonej could you have a look?

**Comment by tiihonej** [comment]
I'll look into to it. There's another fix coming up, too, which is not affecting any existing tests. I'll extend the existing static force test a bit to catch that and post them asap.

**Comment by ye-luo** [comment]
Good now. https://cdash.qmcpack.org/CDash/testDetails.php?test=6025245&build=76469
