### ISSUE TITLE
WF optimization crashing due to unitialized timers

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1854]
accessing `myTimers[4]` in QMCFixedSampleLinearOptimize.cpp
https://cdash.qmcpack.org/CDash/testDetails.php?test=6009362&build=76168
The related problem can be solved probably by removing `std::vector<NewTimer*> myTimers;` from QMCDriver.h and QMCDriverNew.h.

@PDoakORNL hopefully you don't use myTimers in QMCDriverNew.h derived classes.

**Comment by PDoakORNL** [comment]
I’ve been removing timer dependencies in the new driver code. Planning for it to come back in the new style

**Comment by ye-luo** [comment]
good now
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=example_He_example_wf-1-1&date=2019-08-30
