### ISSUE TITLE
Clang6-CUDA-Full-Release build on Oxygen is not under full-precision.

### ISSUE THREAD

**Issue by Hyeondeok-Shin** [QMCPACK/qmcpack#1858]
Clang6-CUDA-Full-Release build on Oxygen is not under full-precision without -D QMC_MIXED_PRECISION=0 flag.

https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=76347

-- defining the float point precision
   Base precision = double
   Full precision = double
   CUDA base precision = float
   CUDA full precision = double

 This build is using exactly same build command with Clang6-CUDA-Release build for the mixed precision (https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=76336), so it needs to be checked.

  Hyeondeok Shin

**Comment by prckent** [comment]
Appears to be a scripting bug. The CPU mixed precision builds are correctly built.

**Comment by prckent** [comment]
This is happening due to how ctest_script.cmake is written. Fix in testing.
