### ISSUE TITLE
Discrepancy between Qbox and QMCPACK external energies

### ISSUE THREAD

**Issue by kryczko** [QMCPACK/qmcpack#1859]
Dear all,

I am computing a single electron problem in a harmonic oscillator potential:
```
V(x, y, z) = 0.5 * (kx * x**2 + ky * y**2 + kz* z**2)
x, y, z = [-5, 5], [-5, 5], [-5, 5]
kx = ky = kz = 1
```
I first do a Qbox calculation and obtain the following energies (Ha): 

```
Kinetic: 0.72079710
External: 0.78057710
Exchange-Correlation (LDA): -0.31188532
Coulomb: 0.25174733
Total: 1.44123621
```

I then use the `convertpw4qmc` command to read in the orbital for the VMC calculation. After running QMCPACK I end up with the energies:

```
Kinetic: 0.7218 +/- 0.0096
External: 3.1478 +/- 0.0049
Total: 3.87 +/- 0.014
```

We can see that the kinetic energies are close, as expected, but the external energies are not. 

I have run additional tests changing the values of kx, ky, and kz, and I find that the shift is not constant. I have also done another test with a flat potential, and have found agreement with Qbox and QMCPACK.

Kevin

**Comment by prckent** [comment]
If you do a determinant only VMC run with QMCPACK you should recover the non-selfconsistent Hartree-Fock energy for that determinant and Hamiltonian. If the orbital(s) happen to be Hartree-Fock orbitals then you should exactly recover the Hartree-Fock total energy from the VMC.

What exactly is the comparison here, and why should the two methods agree? The summary outputs you give are not standard from qmca - what is included in each term? It is a good sign that the kinetic energy agrees - this tells us that the orbital(s) are OK. The agreement with the constant potential is also good.

**Comment by kryczko** [comment]
I would think that in both cases, the externals energies should be the same. Am I wrong in thinking that?

**Comment by prckent** [comment]
External is definitely \int \phi V_{ext} \phi in both cases, no other terms? If so, yes, these should agree.

**Comment by kryczko** [comment]
Yes, this was exactly my thought. The difference between these terms is the issue.

**Comment by markdewing** [comment]
In the code from a previous issue, it looks like you can print out to verify the grid energy is the same as the harmonic potential - I assume this is the case?
It looks like the ratio of external energy values is about 4 (4.03 - suspiciously close to 4) - how does the ratio change with different k values?

**Comment by kryczko** [comment]
Yes, I have made sure I get the same answer as the harmonic potential with the grid. 

For different values of k the external energies:

```
kx = ky = kz = 0.5
qbox: 0.55210071
qmcpack: 1.487
ratio: ~2.7
```

```
kx = ky = kz = 2.0
qbox: 1.09963615
qmcpack: 6.528
ratio: ~6.0
```

so it looks like it is not just a factor of 4.

**Comment by markdewing** [comment]
Does the applyMinimumImage put particles in the expected box - it looks like the potential is centered at zero, so the box should be [-L/2, L/2]

**Comment by kryczko** [comment]
I've printed out the coordinates before and after the applyMinimumImage, here is one output from it that I find odd:

```
Coordinates before: 5.3918439002e+00 1.5077473712e+01 4.9164967677e+00
Coordinates After: -4.6081560998e+00 -4.9225262880e+00 4.9164967677e+00
```

Should the y-coordinate be wrapped to 0.0077473712?

**Comment by kryczko** [comment]
Ah never mind, the wrapping seems to be working properly.

**Comment by kryczko** [comment]
Any other ideas why this energy mismatch could be happening?

**Comment by markdewing** [comment]
How's the acceptance ratio and step size of the VMC calculation?
What happens if the box size is changed?

**Comment by kryczko** [comment]
For a step size of 0.25 I am getting an acceptance ratio of 0.5189 in the 10x10x10 cell. When I double the cell length 20x20x20 I get 0.79110582 for Qbox and 0.1 for QMCPACK. For this calculation I lowered the step size to 0.01 to get ~50% acceptance.

**Comment by markdewing** [comment]
It seems odd that the step size would need to be lowered so much for a larger box.  And that the energies would vary so much.   I would expect that the harmonic potential would be the dominant effect and keep the electron confined, and that the box would have little effect, especially at larger sizes.

**Comment by markdewing** [comment]
Could you attach the QMCPACK input that you are using.

**Comment by kryczko** [comment]
When I use this input:
```
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.mcc.uiuc.edu/qmc/schema/molecu.xsd">
  <project id="qmc" series="0">
    <application class="serial" name="qmcapp" role="molecu" version="0.2">
      QMC calc after running in QBox
    </application>
  </project>

  <random seed="13" />
  <qmcsystem>


  <simulationcell>
    <parameter name="lattice">20.0000 0 0 
 0 20.0000 0 
 0 0 20.0000
</parameter>
      <parameter name="bconds">p p p</parameter>
      <parameter name="LR_dim_cutoff">15</parameter>
  </simulationcell>
  </qmcsystem>


  <particleset name="e" random="yes">
    <group name="u" size="1">
      <parameter name="charge">-1</parameter>
    </group>
  </particleset>

  <wavefunction name="psi0" target="e">
    
    <determinantset href="wfs.h5" meshfactor="1.0" precision="single" source="e" type="einspline">

      <slaterdeterminant>
        <determinant id="updet" ref="updet" size="1">
          <occupation mode="ground" spindataset="0">
          </occupation>
        </determinant>
      </slaterdeterminant>

    </determinantset>

  </wavefunction>


  <hamiltonian name="h0" target="e" type="generic">
    <extpot dataset_name="vext" end="10" file_name="qmcpack_pot.h5" name="vext" num="64" pbc="true" start="-10" type="grid" /> 
    <estimator name="gr" num_bin="200" rmax="9.712825" type="gofr" />  
    <estimator delta="0.015625 0.015625 0.015625" name="density" type="density" /> 
  </hamiltonian>


  <qmc gpu="yes" method="vmc" move="pbyp">
  <parameter name="samples"> 1000 </parameter>
  <parameter name="stepsbetweensamples"> 1</parameter>
  <parameter name="substeps"> 64 </parameter>
  <parameter name="warmupSteps"> 64 </parameter>
  <parameter name="blocks"> 100 </parameter>
  <parameter name="timestep"> 0.01 </parameter>
  <parameter name="usedrift"> no </parameter>
  </qmc>

</simulation>
```

I get the following from qmca:
```
qmc  series 0 
  LocalEnergy           =             90.00 +/-             0.14 
  Variance              =           2471.66 +/-            41.44 
  Kinetic               =             15.61 +/-             0.74 
  LocalPotential        =             74.38 +/-             0.56 
  Grid                  =             74.38 +/-             0.56 
  LocalEnergy_sq        =          10571.90 +/-            31.20 
  BlockWeight           =             48.00 +/-             0.00 
  BlockCPU              =          0.009996 +/-         0.000039 
  AcceptRatio           =            0.7711 +/-           0.0031 
  Efficiency            =           5057.42 +/-             0.00 
  TotalTime             =              0.73 +/-             0.00 
  TotalSamples          =              3504 +/-                0 
```

But when I increase the number of samples:
```
  <qmc gpu="yes" method="vmc" move="pbyp">
  <parameter name="samples"> 100000 </parameter>
  <parameter name="stepsbetweensamples"> 1</parameter>
  <parameter name="substeps"> 64 </parameter>
  <parameter name="warmupSteps"> 64 </parameter>
  <parameter name="blocks"> 100 </parameter>
  <parameter name="timestep"> 0.01 </parameter>
  <parameter name="usedrift"> no </parameter>
  </qmc>
```

I get the following from qmca:
```
qmc  series 0 
  LocalEnergy           =            90.831 +/-            0.048 
  Variance              =           2705.48 +/-             5.50 
  Kinetic               =            12.691 +/-            0.034 
  LocalPotential        =            78.140 +/-            0.026 
  Grid                  =            78.140 +/-            0.026 
  LocalEnergy_sq        =          10955.98 +/-             7.52 
  BlockWeight           =           1008.00 +/-             0.00 
  BlockCPU              =           0.20466 +/-          0.00013 
  AcceptRatio           =           0.79204 +/-          0.00027 
  Efficiency            =             93.16 +/-             0.00 
  TotalTime             =             16.78 +/-             0.00 
  TotalSamples          =             82656 +/-                0 
```

**Comment by kryczko** [comment]
does anything immediately stand out?

**Comment by kryczko** [comment]
In addition, I've also computed the integral myself after reading in the orbitals from the HDF5 file that had been converted. I get back the same value as is calculated in Qbox.

**Comment by markdewing** [comment]
You could change the orbital type from einspline to pw (planewaves).  That would check that the spline orbital representation is working okay.

**Comment by kryczko** [comment]
When I switch to 'pw', it seems like the energies get even worse:

```
qmc  series 0 
  LocalEnergy           =             67.01 +/-             4.46 
  Variance              =           3878.35 +/-           340.07 
  Kinetic               =             44.22 +/-             5.16 
  LocalPotential        =             22.79 +/-             0.69 
  Grid                  =             22.79 +/-             0.69 
  LocalEnergy_sq        =           8416.87 +/-           933.70 
  BlockWeight           =             48.00 +/-             0.00 
  BlockCPU              =            1.4831 +/-           0.0028 
  AcceptRatio           =             0.804 +/-            0.010 
  Efficiency            =              0.03 +/-             0.00 
  TotalTime             =            148.31 +/-             0.00 
  TotalSamples          =              4800 +/-                0 
```

**Comment by kryczko** [comment]
could it be something with the spline representation of the potential?

**Comment by lshulen** [comment]
The variances look incredibly large given what you are doing.  Also that timestep seems very small given that you are doing a VMC calcuatlon with a sensible wavefunction.  

I'm curious about both the effect of the potential and the orbitals.  One test I would be quite keen to see the answer to is to shift the external potential to the center of the simulation cell.  For instance, if you had a 20x20x20 cell, put the center of the harmonic potential at (10,10,10).  Then you could also try switching periodic boundary conditions on and off in qmcpack and verifying that the kinetic energy was not changing.   Hopefully we could see from this whether the problem might lie in how the external potential is interacting with the periodic boundary conditions.

**Comment by kryczko** [comment]
All of the calculations done thus far have the potential centred in the cell. If you don't centre it, then you can't use PBCs. With PBCs turned on I get:

```
qmc  series 0 
  LocalEnergy           =             30.22 +/-             0.28 
  Variance              =             11.54 +/-             1.08 
  Kinetic               =             0.698 +/-            0.045 
  LocalPotential        =             29.52 +/-             0.24 
  Grid                  =             29.52 +/-             0.24 
  LocalEnergy_sq        =            927.64 +/-            16.22 
  BlockWeight           =             10.00 +/-             0.00 
  BlockCPU              =          0.001180 +/-         0.000014 
  AcceptRatio           =            0.9107 +/-           0.0026 
  Efficiency            =         101866.72 +/-             0.00 
  TotalTime             =              0.04 +/-             0.00 
  TotalSamples          =               370 +/-                0 
```
and with them turned off I get:
```
qmc  series 0 
  LocalEnergy           =             29.25 +/-             0.52 
  Variance              =             11.09 +/-             1.30 
  Kinetic               =             0.699 +/-            0.081 
  LocalPotential        =             28.55 +/-             0.44 
  Grid                  =             28.55 +/-             0.44 
  LocalEnergy_sq        =            869.63 +/-            28.76 
  BlockWeight           =             10.00 +/-             0.00 
  BlockCPU              =          0.001187 +/-         0.000028 
  AcceptRatio           =            0.9114 +/-           0.0031 
  Efficiency            =          40076.05 +/-             0.00 
  TotalTime             =              0.03 +/-             0.00 
  TotalSamples          =               280 +/-                0 
```
Not really a major difference.

**Comment by kryczko** [comment]
When I turn periodic boundary conditions off in qmcpack "bconds" I get a segmentation fault.

**Comment by markdewing** [comment]
What happens if the meshfactor value is changed.   If larger than 1.0, more mesh points are used for the orbitals.  I'm not sure how well the grid represents the orbital - it's going to be fairly localized near the center.   Even more so for the larger boxes.

**Comment by kryczko** [comment]
I changed the mesh factor to 5.0, and I got around the same energies.

**Comment by kryczko** [comment]
In the interpolation function does it extend the potential beyond the length of the cell and then wrap that value back into the cell or does it just do the interpolation inside of the unit cell and depends on the user to know to have the same value at the boundaries of the cell?

**Comment by lshulen** [comment]
I'm not an expert in how to do this, but to check that the external potential is working properly, have we previously run with a gaussian wavefunction?

@kryczko, I'm curious about the statement that changing "bconds" results in a segfault.  Are you changing "p p p" to "n n n"?  that really should work.

**Comment by kryczko** [comment]
Yes, I previously ran with a gaussian wave function, and was able to reproduce the exact same answer as with the harmonic potential built into qmcpack.

**Comment by lshulen** [comment]
This is getting a bit hard to debug.  Can you send your input file to qbox and your input file to qmcpack?  (also is a hacked version of qbox necessary to run this?)

**Comment by kryczko** [comment]
No, you do not need a hacked version of qbox to run this, this works right out of the box. I do have a modified version of qmcpack, which I have forked from @markdewing. It is found here: https://github.com/kryczko/qmcpack/tree/add_external_potential. When reading in the orbitals from QBox I had to remove an abort call because there are no ions in the system. Perhaps this is where this issue is stemming from. I am attaching a link to all the files I am using here: https://drive.google.com/file/d/1fveE_odOccg0p2FWGSpMuxuDEQSkrOul/view?usp=sharing.

**Comment by kryczko** [comment]
@lshulen, we're you able to reproduce my workflow?

**Comment by markdewing** [comment]
The orbital is not centered in the cell.
Dumping the position and potential values and plotting them shows the values cluster around -5 and 5. Similarly with plotting r and values of the wavefunction.

A quick hack that adds (5,5,5) to each position before computing the potential gives a much better total energy (1.49 +/- 0.01).

**Comment by markdewing** [comment]
More precisely, when computing the orbital, the position gets transformed from [0,L] ( or [-L,0]) to the interval [0,1].   The center of the orbital is at L/2.
( For the position transform,  see convertPos in QMCWaveFunctions/BsplineFactory/SplineR2RAdoptor.h)
The applyMinimumImage function wraps values outside the interval [-L/2, L/2] so they lie in the interval.  The center of the orbital is still at L/2.

One solution is to shift the potential by L/2.

Another solution is to use the following instead of 'P.Lattice.toUnit'
```
      PosType ru = P.Lattice.toUnit(r);
      for (int i = 0; i < OHMMS_DIM; i++) {
         ValueType img = std::floor(ru[i]);
         ru[i] -= img;
      }
      //P.Lattice.applyMinimumImage(ru);
      double val = 0.0;
      eval_UBspline_3d_d(spline_data, ru[0], ru[1], ru[2], &val);
```
And then set the grid bounds on the potential from 0.0 to 1.0.

**Comment by prckent** [comment]
Closing this because the discrepancy was solved.
