### ISSUE TITLE
Memory error shown in LiH deterministic test

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1862]
deterministic-LiH_dimer_pp-vmc_hf_noj-1-1 is failing with a memory error.  See:

https://cdash.qmcpack.org/CDash/testDetails.php?test=5995872&build=75937

**Comment by jtkrogel** [comment]
Similar for  short-H2O_dimer_sep_pp-j3_dmc_la-1-16:

https://cdash.qmcpack.org/CDash/testDetails.php?test=6005036&build=76073

**Comment by jtkrogel** [comment]
And again for  example_He_example_wf-1-1:

https://cdash.qmcpack.org/CDash/testDetails.php?test=6004949&build=76073

**Comment by ye-luo** [comment]
@jtkrogel fixes got in last week. Just click current on the page of every link.

**Comment by jtkrogel** [comment]
Strange, I moved to today's date before looking at any test.  Closing.
