### ISSUE TITLE
Jastrow coefficients are frozen in optimization loops

### ISSUE THREAD

**Issue by tiihonej** [QMCPACK/qmcpack#1888]
Since Aug 27 looping the Jastrow optimizer does not do anything, but the coefficients appear to be frozen. That is, the values remain the same on each loop iteration after the first. I'm attaching an archive with example input and output. I haven't tested thoroughly with different optimizers, but at least blocks of the following form seem affected:

`   <loop max="8">
      <qmc method="linear" move="pbyp" checkpoint="-1">
         <parameter name="warmupSteps"         >    300                </parameter>
         <parameter name="blocks"              >    200                </parameter>
         <parameter name="steps"               >    1                  </parameter>
         <parameter name="subSteps"            >    10                 </parameter>
         <parameter name="timestep"            >    0.3                </parameter>
         <parameter name="useDrift"            >    no                 </parameter>
         <parameter name="samples"             >    51200              </parameter>
         <parameter name="MinMethod"           >    OneShiftOnly         </parameter>
         <parameter name="minwalkers"          >    0.01               </parameter>
         <parameter name="nonlocalpp"          >    yes                </parameter>
      </qmc>
   </loop>`

[frozen_jastrow.zip](https://github.com/QMCPACK/qmcpack/files/3597754/frozen_jastrow.zip)

**Comment by prckent** [comment]
This looks to be a real problem that we simply didn't notice in our regular testing:
<img width="799" alt="Screen Shot 2019-09-10 at 5 56 45 PM" src="https://user-images.githubusercontent.com/13683814/64653446-72063080-d3f4-11e9-8e2c-75db8e5682d3.png">

**Comment by ye-luo** [comment]
#1830 didn't fully fix WF optimization.
