### ISSUE TITLE
AFQMC unit tests are failing

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#189]
The unit tests for fallback routines used by AFQMC when MKL is not present are failing since PR #187.

**Comment by ye-luo** [comment]
GNU only
Test project /home/yeluo/opt/qmcpack/build_gnu_real
    Start   1: unit_test_afqmc_matrix
1/3 Test   #1: unit_test_afqmc_matrix ...........   Passed    0.02 sec
    Start   2: unit_test_afqmc_numerics
2/3 Test   #2: unit_test_afqmc_numerics .........***Failed    0.02 sec
    **Start 179: short-afqmc-N2_vdz-4-1
3/3 Test #179: short-afqmc-N2_vdz-4-1 ...........***Failed    0.58 sec**

GNU+MKL
Test project /sandbox/opt/qmcpack-mmorales/build_afqmc_gnu
Start 1: unit_test_afqmc_matrix
1/3 Test #1: unit_test_afqmc_matrix ........... Passed 0.06 sec
Start 2: unit_test_afqmc_numerics
2/3 Test #2: unit_test_afqmc_numerics .........***Failed 0.09 sec
Start 179: short-afqmc-N2_vdz-4-1
3/3 Test #179: short-afqmc-N2_vdz-4-1 ........... Passed 57.58 sec

Intel+MKL
Test project /sandbox/opt/qmcpack-mmorales/build_afqmc_real
**Start 1: unit_test_afqmc_matrix
1/3 Test #1: unit_test_afqmc_matrix ...........***Failed 0.05 sec**
Start 2: unit_test_afqmc_numerics
2/3 Test #2: unit_test_afqmc_numerics .........***Failed 0.06 sec
Start 179: short-afqmc-N2_vdz-4-1
3/3 Test #179: short-afqmc-N2_vdz-4-1 ........... Passed 37.04 sec

**Comment by ye-luo** [comment]
PR #196 addresses unit_test_afqmc_numerics

**Comment by prckent** [comment]
Per cdash, these are now passing so I will close this issue.
