### ISSUE TITLE
IonOrbital need SoA

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1897]
https://cdash.qmcpack.org/CDash/testDetails.php?test=6114702&build=78458
Broken I believe since #1846.
When the code is build SoA but addTable requests AoS, the pointer to DT is nullptr and caused segmentation fault.
We need to add a check for SoA build and stop the code if AoS DT is requested.
@markdewing I assign you because you are more familiar about how to add the protection in createDT functions. 
@Paul-St-Young I assign you because you added the integration test and are more familiar with the class.

PS: I feel IonOrbital need to be renamed. The current name doesn't reflect its use.

**Comment by Paul-St-Young** [comment]
OK, I implement SOA for this along with the lattice deviation estimator.
Regarding the name, how about `LatticeGaussianProduct`?
This wavefunction is a product of gaussians, each centered around a lattice site.

**Comment by ye-luo** [comment]
Should be good. Unless other suggestions show up, just put what you suggested.
