### ISSUE TITLE
Zn.ccECP-SO.xml physically incorrect

### ISSUE THREAD

**Issue by camelto2** [QMCPACK/qmcpack#1913]
For parsing purposes, the existing Zn.ccECP-SO.xml in the pseudopotentials_for_tests directory is fine. However, for the future, it should be noted that the Zn.ccECP-SO.xml format is not technically correct and should corrected. 

For instance, the current Zn.ccECP-SO.xml took our existing Zn.ccECP.xml from pseudopotentiallibrary.org and added SO terms from the stuttgart ECP page. The p,d,f SO correction terms that were added to the Zn.ccECP-SO.xml must be coupled to another averaged relativistic semi-local projector. Since our Zn ccECP only has s,p semi-local projectors, and d is treated as a local channel, then for the spin-orbit corrections there should only be a p-channel SO correction. The current file includes p,d,f SO corrections, and there is not a corresponding semi-local projector for the d and f corrections. For the future, we should add a catch to flag issues like this

**Comment by prckent** [comment]
I suggest to add an issue referencing this one about checking for the presence of semilocal projectors for all the channels where SO corrections are given and at least printing a giant warning.
