### ISSUE TITLE
J2 optimization of H2 molecule

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#194]
When J2 up-up/down-down correlation is present in the WF of H2 molecule, VMC/DMC calculations work well but optimization may get trouble due to the singular overlap matrix.
Optimizer quartic still has this issue. OneShiftOnly has been protected in PR #193. adaptive is fine.

Apart from the optimizer, somehow we need to detect such simple mistakes.
uu/dd correlation can only be added when you have at least 2 electrons for either spin.
ud can only be used when ud pair exists (already protected).
Beginners usually start with very simple systems, H, H2, He, Li/Be with He core PP and hit similar issues.

J3 potentially has a similar issue as J2 but needs investigation.

**Comment by prckent** [comment]
Closed by #195
