### ISSUE TITLE
cmake configuration failure due to missing files but CI didn't catch it

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1949]
test_template_types.cpp was added to cmake but the file was not included in #1947.
It is very strange that Oxygen CI passed. Someone who has access to the jenkins needs to have a close look. ALCF CI correctly reports failure due to cmake error.
https://cdash.qmcpack.org/CDash/index.php?project=QMCPACK&date=2019-09-28

**Comment by PDoakORNL** [comment]
Fixing this now.  I should have trusted the ALCF CI and looked closer.

**Comment by ye-luo** [comment]
Fixed by #1959. Verified by #1961.
