### ISSUE TITLE
 ntest_nexus_grid_functions failing

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1955]
https://cdash.qmcpack.org/CDash/testDetails.php?test=6267412&build=82155
@jtkrogel Is this due to too old python or actually a bug?

**Comment by jtkrogel** [comment]
Probably due to too old numpy.

From https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html:

"Changed in version 1.9: 1-D and 0-D cases are allowed"

If using numpy with version before 1.9 (Sep. 2014), then this failure likely results.  Check the following on bora:
```
>python
Python 2.7.15+ (default, Jul  9 2019, 16:51:35) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'0.19.1'

```

**Comment by ye-luo** [comment]
I switched to a newer python and numpy and got
```
$ "/sandbox/opt/cleanup/yeluo/nexus/bin/nxs-test" "-R" "grid_functions" "--ctest" "--pythonpath=/sandbox/opt/cleanup/yeluo/nexus/lib"
Traceback (most recent call last):
  File "/sandbox/opt/cleanup/yeluo/nexus/bin/nxs-test", line 38, in <module>
    from generic import generic_settings,object_interface,NexusError
  File "/sandbox/opt/cleanup/yeluo/nexus/lib/generic.py", line 1281
    print repr(o)
             ^
SyntaxError: invalid syntax
```

**Comment by jtkrogel** [comment]
Python 3?

**Comment by ye-luo** [comment]
Yes. It was python 3. I switched to python 2 and it works well now.
