### ISSUE TITLE
Missing and misnamed files in AFQMC examples

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1964]
Some of the files in the AFQMC examples are either misnamed or missing altogether.

Examples beyond the first use `pyscf_to_afqmc.py` to produce `hamil.h5` (` pyscf_to_afqmc.py -i scf.chk -o hamil.h5 -t 1e-5 -v`) while the `gen_input.py` script expects a file named `afqmc.h5` in all examples.

Missing files:
* `06-methane_converge_back_prop` is missing `scf.py`

A more minor point: starting with example 5, the headers are off by one (example 5 is called example 4, etc).

**Comment by jtkrogel** [comment]
Also, some paths are non-existent and should be removed.  These are carry overs from the workshop, such as `$HOME/apps/qmcpack/qmcpack/utils/afqmctools/bin/`.

**Comment by prckent** [comment]
Closed by #1966
