### ISSUE TITLE
scalar.h5 should be stat.h5

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1979]
The AFQMC code currently writes heavy observables, like the 1RDM, into a `scalar.h5` file.  This is in addition to the `scalar.dat` file that actually contains scalars.

The double naming (scalar.h5 and scalar.dat) is confusing.  Additionally, the naming is confusing because the real space code uses the distinctly named `stat.h5` file for the type of heavy observables `scalar.h5` contains.

The `scalar.h5` file from the AFQMC code should be renamed `stat.h5` to standardize outputs and avoid confusion.

**Comment by prckent** [comment]
Agreed.

**Comment by prckent** [comment]
Also, the 1DRM is not a scalar...

**Comment by fdmalone** [comment]
Ok. It's not really clear that 'stat' is an obvious name for things other than 'scalars' though is it?

**Comment by jtkrogel** [comment]
Resolved by #1980.
