### ISSUE TITLE
No tests or reference input for HEG (homogeneous electron gas)

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#199]
The 3D HEG wavefunction is likely working but is untested. 2D HEG may require fixes depending on the ramifications of #188 .

Example inputs are needed.

A test in ctest would be very worthwhile since this is one of the few periodic systems where we have reference data to compare against. This would provide a strong test of the different QMC drivers since we can easily make the error bars small.

**Comment by prckent** [comment]
@jtkrogel Please add a note here if you have any old inputs

**Comment by jtkrogel** [comment]
3D HEG tests included as of PR #390.  2D HEG investigate/fix/test still outstanding.

**Comment by prckent** [comment]
Due to #188 I will close this. 2D is not much of a priority (no requests received). We can revisit the 2D HEG if requests are received or inputs unearthed and #188 fixed.
