### ISSUE TITLE
GCC glibc check fails with GCC version <6 due to unsupported -Wmisleadingindentation option

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1990]
GCC 5.5.0 builds broke last night https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=84206 due to the update in warnings in #1936 

Suggested resolution: WONTFIX. This is simplest. GCC6 introduced this flag. Since we are near a release and can update minimum dependencies, move to GCC 7.2 released August 2017 https://gcc.gnu.org/releases.html following our two year rule.

**Comment by ye-luo** [comment]
For various reasons, I still need gcc 6.
1. clang 9 openmp offload has cmath/math.h issue with gcc >6
2. Using cuda 10.0 only supports up to Intel 18
3. Intel 18 is only guaranteed with gcc 6.

**Comment by prckent** [comment]
The versions of GCC that we support as the primary compiler can be (are) different from those that Intel or Clang or CUDA might need. I therefore don't consider this a problem. For testing, the oxygen test scripts already use different versions of GCC or LLVM as required by a specific CUDA version or for C++ library support.

**Comment by prckent** [comment]
I will soon update the README.md, oxygen spack setup script and nightly scripts for new versions.
