### ISSUE TITLE
Top level C++ exception handling needed

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#2013]
Unhandled C++ exceptions typically do not leave a very informative trail - usually just a signal -6 exit code from the process.  And this makes debugging the problem more difficult than it needs to be.
See #1991 for an example.

One solution is to add a try/catch block at the top level, likely near the end of qmcapp.cpp. This could catch different errors (std::bad_alloc for out of memory, std::runtime_exception, ,etc.) and print something useful before calling APP_ABORT (to ensure all MPI ranks exit).

**Comment by grahamlopez** [comment]
This is not my fight by a long shot, but I would strongly vote for just getting rid of exceptions completely. They almost always cause more trouble and development effort than they save. They are yet another form of scope-abusing control flow (`goto` anyone?) and they exercise more edge cases of C++ behavior than almost any other single language feature. All of this isn't even considering possible performance implications (cf. `noexcept` keyword).

**Comment by markdewing** [comment]
Exceptions already exist in the code, and they are a language-standard mechanism.  Catching out-of-memory errors from the standard library would be tricky (not impossible, but much easier to just catch the bad_alloc exception). Coming up with a good alternative, teaching people to use it, and applying it to the code seems like too much work.   If there is some critical part of the code where performance or control-flow comprehension is critical, we can discuss it in more detail.

**Comment by prckent** [comment]
Is it correct to state that our only envisaged use for exceptions is when something has gone wrong (most likely memory or I/O failures) and we are about to quit? If so, what is being discussed here is the cleanest general and maintainable way to abort. Abuse of scope would not be much of a consideration here, but performance considerations should certainly be factored...

**Comment by PDoakORNL** [comment]
I agree exceptions should not be used as a replacement for goto or normal error handling. But looking through the code our use seems acceptable. However we should probably state in our coding standards that it should be assumed exceptions are thrown with no guarantee i.e. the program is probably not in a valid state, resources will almost certainly leak, etc. etc.

As far as cost my understanding is the Itanium ABI made exception frames, `try{}catch(){}`, essentially 0 cost.  Now the cost is only paid once throw is called and the exception handling begins. 

So unlike in the 90's where you could just look at code see `try` and know it was slow, that's not necessarily so anymore

I thought `noexcept` had much more to do with resolving the problem of the STL and other libraries having "provided" the strong exception guarantee but that then being incompatible with move semantics unless either static analysis or a notation could prove a particular move contructor of a type didn't throw. 

I'm putting in a PR setting up a last resort try catch block for the code.

**Comment by prckent** [comment]
A catch was added in #2014 . We can revisit this topic if needed. Going forward we need to trap (via error code checking or catching) the most frequent errors near where they occur and give meaningful feedback to the user.
