### ISSUE TITLE
Static vs dynamic linkage should be switchable

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#202]
The current cmake configuration hardwires static or dynamic linkage for particular systems. This can be problematic if the full complement of libraries is not available, e.g. libxml2 is often only installed as a shared library.

Recommendation: Improve cmakelists.txt to properly respect QMC_BUILD_STATIC and use this input parameter as an override of the present defaults. i.e. Don't change the current defaults, but allow this to be changed. e.g. On Cray permit dynamic linkage on CPU systems.

**Comment by prckent** [comment]
@ye-luo I assigned you since you were interested in this topic - I think it is a very easy fix to properly respect QMC_BUILD_STATIC, which we already document in the manual. Only override where necessary, e.g. CUDA on Cray requires dynamic.

**Comment by ye-luo** [comment]
I checked dynamic CPU build on Titan. It works well. If most system works better with dynamic, we should change default to dynamic.

**Comment by ye-luo** [comment]
The pain of Cray is that the default is not consistent. Titan has dynamic as default but Theta has static. Everything is beneath the Cray compiler wrapper.

**Comment by prckent** [comment]
I think the usage of static linkage was historic. Loading lots of libraries at runtime was probably slow, and might still be. CUDA builds have to be dynamic since NVIDIA does not ship static libraries/runtimes.

Have you seen any performance issues on Theta with dynamic linkage? e.g. large metal-oxide runs?

**Comment by ye-luo** [comment]
No one (ALCF or Cray) mentioned it to me that static linking gives better performance.

**Comment by prckent** [comment]
Closed by #203
