### ISSUE TITLE
Chiesa finite size correction not compatible with SoA

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2025]
No version of this correction exists for SoA.  As this is currently our only two body finite size correction for the kinetic energy, a port to SoA should be made.

See also #1003.

**Comment by jtkrogel** [comment]
I've currently placed this in the priority list for #861.  Perhaps @prckent should add approval/disapproval of this prioritization as time is short.

**Comment by ye-luo** [comment]
Currently the SoA codes print a warning. Users need to run AoS one step to access the correction value. The correction evaluation can be moved to the Jastrow builder but will not be printed out in scalar.dat but just one line in the output file

**Comment by jtkrogel** [comment]
It should go in scalar.dat for post processing.  The output and storage overhead is minimal and I don't want to add output log data scraping to `qmca` just for this.

**Comment by ye-luo** [comment]
I understand the convenience to collect the number via scalar.dat. On the other hand, I feel it is awkward to collect a constant by saving it in the WF object and then create an estimator to run the whole data collection machinery to print it out to scalar.dat.

**Comment by jtkrogel** [comment]
Perhaps a better route to scalar.dat is needed. I am agnostic there.  Whatever the internal route, it should end up in scalar.dat.

**Comment by ye-luo** [comment]
@Hyeondeok-Shin will help me porting this. I don't expect any significant difficulty.
