### ISSUE TITLE
xml string handling leaks memory (xmlNodeListGetString)

### ISSUE THREAD

**Issue by eneuscamman** [QMCPACK/qmcpack#204]
I was checking some of my code for thread safety and trying to ensure the xml parsing was thread safe, when I found that there are many calls to xmlNodeListGetString that are not matched to a call to xmlFree.  My understanding is that xmlNodeListGetString allocates a new character array and that it is up to the user to deallocate it.  A quick grep shows that this could lead to memory leaks in many files, including:

src/QMCApp/QMCMain.cpp
src/OhmmsData/libxmldefs.h
src/OhmmsData/OhmmsParameter.h

I did not run these down exhaustively, so if this is an issue it is probably present in many other files too...

**Comment by prckent** [comment]
Excellent find. There are also calls to xmlGetProp that appear to not have a matching xmlFree too.

**Comment by prckent** [comment]
Suggestion: After we get continuous integration ( @grahamlopez + collaborators ) and test coverage ( @markdewing  ) working, we add a leak checker to the testing. It is bad to leak at all, but leakage of small strings won't hurt us compared to, say, leakage of large walker or spline buffers.

**Comment by prckent** [comment]
Figuring out a path forward for MPI support is likely a higher priority for now.

**Comment by grahamlopez** [comment]
I've added this to my list of things to look into for CI.

**Comment by prckent** [comment]
Thanks. This particular leak is not a big problem, but there could easily be other non-identified leaks that are more serious.

**Comment by ye-luo** [comment]
I noticed that memory is leaking when I have many sections of optimization (loop). A few MB per section. Not sure if this is correlated.
