### ISSUE TITLE
Separate SPOSet tag and determinant tag needed

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2070]
Leave the LCAO a side at the moment since the handling of MO coefficients is more complicated but it carries the same problem.

Let us focus on the spline case. We have three input styles.

Style 1. using sposet_builder outside determinantset
```
<wavefunction name="psi0" target="e">
   <sposet_builder type="bspline" href="./pwscf.pwscf.h5" tilematrix="1 0 0 0 1 0 0 0 1" twistnum="0" source="ion0" version="0.10" meshfactor="1.0" precision="float" truncate="no">
      <sposet type="bspline" name="spo_ud" size="4" spindataset="0"/>
      <sposet type="bspline" name="spo_dm" index_min="4" index_max="8" spindataset="0"/>
   </sposet_builder>
   <determinantset>
      <slaterdeterminant>
         <determinant id="updet" group="u" sposet="spo_ud" size="4"/>
         <determinant id="downdet" group="d" sposet="spo_ud" size="4"/>
      </slaterdeterminant>
   </determinantset>
</wavefunction>
```
spo related info is 1 level above sposet tag.
Q1. why do we need attribute size on the determinant line. It should be derived from the number of 'u'. Or it means something else?

Style 2. using sposet inside determinantset
```
<wavefunction name="psi0" target="e">
   <determinantset type="bspline" href="./pwscf.pwscf.h5" tilematrix="1 0 0 0 1 0 0 0 1" twistnum="0" source="ion0" version="0.10" meshfactor="1.0" precision="float" truncate="no">
      <sposet type="bspline" name="spo_ud" size="4" spindataset="0"/>
      <sposet type="bspline" name="spo_dm" index_min="4" index_max="8" spindataset="0"/>
      <slaterdeterminant>
         <determinant id="updet" group="u" sposet="spo_ud" size="4"/>
         <determinant id="downdet" group="d" sposet="spo_ud" size="4"/>
      </slaterdeterminant>
   </determinantset>
</wavefunction>
```
In this case, the info on the sposet_builder are moved to determinantset and sposet are moved inside determinantset.
spo related info is 1 level above sposet tag.
What is index_min, index_max? we need documentation.

Case 3. Let me call it mixed style.
```
<wavefunction name="psi0" target="e">
   <determinantset type="einspline" href="pwscf.pwscf.h5" tilematrix="2 0 0 0 1 0 0 0 1" twistnum="0" source="ion0" meshfactor="1.0" precision="double">
      <slaterdeterminant>
         <determinant id="updet" size="8">
            <occupation mode="ground" spindataset="0"/>
         </determinant>
         <determinant id="downdet" size="8">
            <occupation mode="ground" spindataset="0"/>
         </determinant>
      </slaterdeterminant>
   </determinantset>
</wavefunction>
```
In this case the determinant section actually plays 2 roles. It represents both determinant and sposet tags of the previous styles.
spo related info is 1 level above sposet tag.
Q1: why spindataset is on the line of occupation?

@jtkrogel if I remember correctly, case 1 is desired in the case of 1RDM which needs a sposet.

If we treat xml as C++ and think about scope. I think style 3 is the worse case. It looks like treating restricted spin like unrestricted. It also has fuse two tags in one. I think we should deprecate the style 3 and update converters to write style 1 or 2 if they don't.

**Comment by prckent** [comment]
My view on this matter is that we should pick a style that is also compatible (technically and aesthetically) with excitations, make a breaking change to the input parser, converters, and NEXUS if needed. The old formats should be error trapped. The current situation is too confusing for new users and maintainers alike.

We have some time to consider what to do since v4 takes precedence by far.

**Comment by jtkrogel** [comment]
The first example is typical of 1RDM.  The `index_min` and `index_max` define a range over which orbitals are loaded.  This is primarily to avoid memory duplication.  The 1RDM will use the union of `spo_ud` and `spo_dm`.

I don't see what is gained (or what the use case is) for style 2.

Style 3 is fine.  I don't see why we need to break backwards compatibility in this case.  If `size` is not specified, the default behavior should be to use whatever is in up/down electron groups (it probably does not do this now).

None of these styles reflects the excited state format.  Again, I don't think there is an identified need to break backwards compatibility, only to extend compatibility of the existing input style for excitations with LCAO, etc.

**Comment by ye-luo** [comment]
@prckent These three styles all support excited states which is an internal detail of sposet tag.
<sposet type="bspline" name="spo_ud" size="4" spindataset="0">
    <occupation mode="ground"/> // for ground state
    <occupation mode="excited"> // for excited state
      -8 9
    <occupation>
</sposet>

**Comment by ye-luo** [comment]
@jtkrogel 
Style 3 at the input xml level treats SPO sets used by two determinants distinct.

Even in a spin restricted calculation, the LCAO converter writes two sets of indentical MO coefficients and the code builds two separate up and down SPO sets. Once we start orbital optimization, the up and down sets diverge and we get unrestricted symmetry. This is dangerous but the behaviour is correct to me.

In the case of spline SPO case, we need to save memory. The einspline builder has extra code to check if the second SPO has full spec the same as the first one or not and then decide to build a new SPO set or reuse an existing one. This works in some ways but doesn't remove the hacky nature. In berief, we don't have full control building one unique SPOset or two sets. When adding rotation parameters, the current checking code is not able to handle the full comparison for sure. the builder is error-prone.

In stye 1 and 2, determinants pick up SPOSet by name and it is easy and clean to handle spin restricted and unrestricted cases.

For the above reason, I'm in favour of deprecating style 3.

@jtkrogel what is the input style for fusing multiple arbitrary SPO sets. You have used it for your kinetic operator filtering paper, right?

**Comment by ye-luo** [comment]
In style 3, the same xml block is parsed by both determinant and sposet tags. The `size` seems being used by both but with different meanings. We need to prevent this case.

We also need to clearly document the parsing of every input parameter.
if not present, pick up default or abort
if preset and there is a default, override or abort when both are present.

**Comment by jtkrogel** [comment]
@ye-luo The sposet partitioning (post smoothing) for the KE paper looks like this:

```
      <wavefunction name="psi0" target="e">
         <sposet_builder type="bspline" href="$eshdf_file" tilematrix="1 0 0 0 1 0 0 0 1" twistnum="0" source="ion0" version="0.10" meshfactor="1.0" precision="float" truncate="no">
            <sposet type="bspline" name="spo_core" size="22" spindataset="0"/>
            <sposet type="bspline" name="spo_valence" index_min="22" index_max="42" meshfactor="$meshfactor" spindataset="0"/>
         </sposet_builder>
          <sposet_builder type="composite">
            <sposet name="spo_ud" size="42"> spo_core spo_valence </sposet>
          </sposet_builder>
         <determinantset>
            <slaterdeterminant>
               <determinant id="updet" group="u" sposet="spo_ud" size="42"/>
               <determinant id="downdet" group="d" sposet="spo_ud" size="42"/>
            </slaterdeterminant>
         </determinantset>
      </wavefunction>
```

**Comment by lshulen** [comment]
To me option 1 makes the most sense.  I like the idea of separating the creation of the SPOs from the determinant.  In the abstract, I could also see how this might help create some separation in the code between those two parts as well.  I wonder whether even moving the creation of the SPOs outside of the wavefunction could make sense if we consider observables such as the density matrix.  Certainly in that case it would be important to make sure that the order of the tags in the input file did not become important.

As for deprecating, I'm not opposed to deprecating the third form, certainly tools could stop using it.  I'm not sure of the best time line to actually have the code stop accepting it though.

**Comment by jtkrogel** [comment]
I agree with Luke's comments.  Option 1 was created to facilitate density matrix computation and is the most general form, IMO.  

I also agree that a good path forward would be to change the form produced by the converters while still accepting the old form (without trying to generalize its compatibility with all other features).

**Comment by ye-luo** [comment]
@lshulen you got the key point. We really need to separate the SPO creation from the determinants. In terms xml tag ordering. I think it is not bad to require some ordering in the xml. I expect the order of cell, partilce, spo_builder, WF, Hamiltonian then driver sections. if any flexible order is allowed, we have extra burden to support it and it is hard to read an input file by human. But if there are several sposets in a spo_builder, their order should not matter.

**Comment by prckent** [comment]
I agree that the spo creation should be separate from the determinants. i.e. option 1.

Our parser should be able to handle different orderings. i.e. It should look for entries in the order needed internally. Our execution is currently driven by the input order, which is wrong in my opinion. I don't think that supporting this should be difficult. If we need a hardwired order we have one more reason to not use XML.
 
Re: excited states: The specification should belong to the determinants i.e. the trial wavefunction. The sposet should be only a basis in my opinion. The only dependency would be informing it of (say) the number of orbitals to compute. I don't see why the excited state information should be related to the sposet. Otherwise I need to make a new SPO set if I want to (say) evaluate the density matrix for an excited state. Perhaps we already require this, but it does lead to redundant computation.

**Comment by lshulen** [comment]
@ye-luo and @prckent , my comment on element order was based on my understanding of XML.  I believe that according to the spec that order of children in XML is not guaranteed by the order they appear in the document.  Perhaps this is outdated and perhaps order independence is already broken by the way we do the parsing, but if I am correct, then we should probably make a deal of this in the manual and be aware of it if we ever look at different parsing libraries / constructs.

**Comment by jtkrogel** [comment]
Correct execution of QMCPACK as it now stands requires order dependent parsing in many places.  There are a few places where this is not true, but I think it is closer to the rule than the exception.

Ideally this would not be the case.

**Comment by ye-luo** [comment]
Re: excited states.
SPO level excitation is used to construct minimal SPO sets from input which usually has more orbital than needed. Multi-det has another level of excitation. Single det doesn't need its own excitation.

I'd like to have SPOSet with Nb orbitals support evaluating 1~Nb orbitals based on the output vector. This has been supported on LCAO in the recent orbital rotation PR. spline orbital is not there yet. With this feature, we can have a single SPO support ROHF and other places like DM.

**Comment by prckent** [comment]
As we just discussed, I suggest a sketch here of the SPOSet with suitable options that enable a subset of orbitals to be specified and evaluated.

**Comment by PDoakORNL** [comment]
I'm also in favor of deprecating and removing format 3. There should be one and only one hierarchy for the XML elements in our input and therefore only 1 or 2 should selected. If we want to provide backward compatibility a translator in python from the obsoleted format to the supported format seems a much better idea than having the C++ application code handle this. I don't see the element order as a significant issue if the hierarchy issue is settled. No leaf XML node should be read by more than one object. Having a C++ native representation of input would give us some flexibility in that reading input and actual object creation will become weakly coupled, but the hierarchy should still be sensible.

**Comment by ye-luo** [comment]
For the specification of SPOSet, please discuss in #2086

1. We seem to agree that style 3 needs to be deprecated and removed eventually.
2. Between 1 and 2, the difference is small enough that we can technically support both but let us pick one.
3. Whether we take sposet_bulder outside or inside wavefunction doesn't really make a difference to me as long as we fix one style. At the moment, how to handle the ownership of SPOset is not clear in the code, so it is better having no change.

**Comment by ye-luo** [comment]
please use thumb up for style 1 and thumb down for style 2.
