### ISSUE TITLE
MPI illegal instruction

### ISSUE THREAD

**Issue by afernandezody** [QMCPACK/qmcpack#2096]
Hello,
I'm seeing the following error while running an example:
`mpirun noticed that process rank 1 with PID 6547 on node ip-172-31-41-193 exited on signal 4 (Illegal instruction).`
The funny thing is that this is happening only while using AMD CPUs because the job completes on Intel CPUs. Any suggestion on what might be the issue or where to start looking at would be appreciated. Thanks.

**Comment by markdewing** [comment]
Could you say more about which compiler is used and which AMD CPU shows the problem?

**Comment by ye-luo** [comment]
Binaries usually are not portable across architectures. Even though both AMD and Intel are x86_64, the supported feature (instructions) can differ. That is why you get illegal instructions error. If you are not familiar with cross-compiling, recompiling the code directly on the AMD processor can be the simplest solution.

**Comment by afernandezody** [comment]
It's compiled with gcc 8.3.0 & OpenMPI v4.0.2. The AMD is EPYC (not the Rome processor, just one from the 1st gen); it was a 7451 or 7551, don't recall the exact model but will check.

**Comment by afernandezody** [comment]
Hi @ye-luo,
Thanks. I had the same thought earlier this morning so I recompiled everything from scratch using AMD power. My previous test, which was right before opening the ticket, was still outputting the same error message. My mistake was that the compute nodes were AMD but I was using Intel on the master node of the cluster. The problem seems to be fixed once the master node is also AMD. I don't fully understand why of the interference because the master node carries no computational load, but it is what it is. 
Sorry to have bothered everyone when the solution was in front of my eyes.

**Comment by ye-luo** [comment]
@afernandezody glad to hear that your problem is resolved.

**Comment by prckent** [comment]
@afernandezody  FYI, I successfully checked the development version on an AMD Epyc 7451 today.
