### ISSUE TITLE
Compilation breaks if MKL includes are not available but MKL library was detected

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2098]
We assume HAVE_MKL=true implies that at least
#include <mkl_service.h>
#include <mkl_types.h>
are available, but this need not be so. Their availability is not guaranteed unless the include paths have been setup, which we do not check for currently.

mkl_service is used to check for nested threading support. 

mkl_types is used in formic for reasons that I do not understand.

**Comment by ye-luo** [comment]
Should we error at
https://github.com/QMCPACK/qmcpack/blob/e2dfc021f400a38134af936f45ffcde00ad7af11/CMakeLists.txt#L494
and telling people use ENABLE_MKL?
I found the notes
```
    # When cmake finds and sets up the MKL libraries with a non-Intel compiler, set the flag
    # This should be tidied up when FindMKL.cmake supports non-Intel compilers.
```
Should do the tide up work now?

**Comment by prckent** [comment]
In my situation we correctly found an MKL library containing BLAS/LAPACK to link against (good) but the include paths weren't setup. This could happen with a non Intel compiler. Different cmake configure options from what I used might result in the include paths being set correctly - I haven't checked yet. Perhaps do a separate check?

**Comment by ye-luo** [comment]
I guess your MKL was found via FindLAPACK and you are using non-Intel compiler. In this case, we should require users turn on ENABLE_MKL to enable all the pieces of MKL needed by QMCPACK.
Yes. please add -DENABLE_MKL and the header should be looked for and verified.
