### ISSUE TITLE
Wavefunction gradients broken after change to log representation

### ISSUE THREAD

**Issue by tiihonej** [QMCPACK/qmcpack#2110]
Various methods involving wavefunction gradients are broken since migration to log representation (PR #2048 ). This mainly affects force-related observables, such as Pulay terms in the ACForce estimator. For instance, the attached figure demonstrates that the ZV-force (no gradients) is quite okay, but the ZB-correction (has gradients) is just garbage.
![CO_F_broken](https://user-images.githubusercontent.com/12646540/69268392-0a5f2500-0b9d-11ea-8fee-0a2d1d9258c2.png)

A special case is the estimator of the NLPP force contributions, which is produced by adding 'forces=yes' attribute to a PseudoPot hamiltonian. In this case even the total energies will be contaminated by the bug, and thus, off by a large fraction.

The apparent fix is to update the gradient methods, such as psi.ratioGrad and whatever else is needed to take gradients of wavefunction components.

**Comment by jtkrogel** [comment]
Good target for added unit tests.  Is it clear what code paths other than forces might be affected?

**Comment by ye-luo** [comment]
@tiihonej could you provide a reproducer input?

**Comment by tiihonej** [comment]
@ye-luo , Sure!

Adding the FNL estimator raises the energy to about ~-11 Ha, while is should be ~-16 Ha (remove forces=yes from PairPot hamiltonian)
[MgO_fnl_bug.zip](https://github.com/QMCPACK/qmcpack/files/3871085/MgO_fnl_bug.zip)

The nonzero pulay terms of CO at this geometry are approximately ("should be" in parentheses)
ACForce_Ewfgrad_0_0 = 21.9 (29.7)
ACForce_Ewfgrad_1_0 = -21.9 (-28.1)
ACForce_wfgrad_0_0 = -1.37 (-1.37)
ACForce_wfgrad_1_0 = 1.36 (1.30)
It looks like Ewfgrad is the one most affected.
[CO_grad_bug.tar.gz](https://github.com/QMCPACK/qmcpack/files/3871086/CO_grad_bug.tar.gz)

I'm not aware of any other code paths than these affected. I've understood that @rcclay is working on a new unit test.

**Comment by jtkrogel** [comment]
Use of what TrialWavefunction member function is causing the problem?  I would like to see if it is used elsewhere in the code.

**Comment by tiihonej** [comment]
At least TrialWaveFunction::ratioGrad has problems, and I think there's a chance that fixing it fixes it all. Another candidate for the acforce-related troubles is TrialWaveFunction::evalGradSource, but that I haven't checked explicitly.

**Comment by prckent** [comment]
As @jtkrogel mentioned, "Good target for additional unit tests"

**Comment by ye-luo** [comment]
bug confirmed. Instead of reverting to the old behaviour, I'm looking at deleting more ifdef and converging behaviours.

**Comment by tiihonej** [comment]
Of course. No reason to go back on LogValueType update, because that was clearly called for. For the time being, I'll be able to proceed with the forces using an older revision of the code. Let me know if you need more input from me.
