### ISSUE TITLE
AFQMC workflow tests need to be enabled. 

### ISSUE THREAD

**Issue by fdmalone** [QMCPACK/qmcpack#2133]
pyscf needs to be built for these to be run during the nightlies, or even less frequently.

**Comment by fdmalone** [comment]
In light of #2447 it would be great if we could enable both these tests and the afqmctools unit tests during the nightlies, both of which require pyscf to be built somewhere.

**Comment by prckent** [comment]
Can I safely assume that PySCF v1.7.1 is good? I would prefer to use a specific version.

**Comment by prckent** [comment]
What is the correct way to invoke these tests? Are they tagged with any test labels? e.g. converter?

**Comment by fdmalone** [comment]
afqmc and converter are the labels. PYSCF_BIN has to be set during cmake or else they aren't enabled.
One thing I'm not sure about is how to handle the PYTHONPATH? both pyscf and afqmctools have to be in the PYTHONPATH. Alternatively I could set up afqmctools to have a setup.py so it could be 'installed' during the build process.

**Comment by fdmalone** [comment]
This PYSCF_BIN probably can be removed, I see the pyscf dependency has been handled more gracefully in the CMakeLists

**Comment by fdmalone** [comment]
While we're at it could the afqmctools unit tests be enabled? Are unit tests run through ctest too?

**Comment by prckent** [comment]
All tests are run via ctest. Tests not in ctest effectively do not exist. This reduces our labor and the number of things that need to be described to users and maintained by us.

PYTHONPATH is set externally. This is already done for NEXUS testing. 

We do need to get much smarter about our python dependencies and installation and should have a discussion about it, with a goal of improving users experience. Unfortunately our testing will likely not use this route for a bunch of reasons.

**Comment by fdmalone** [comment]
Cool. Well the workflow tests should work fine (I hope!) through ctest once the pythonpath is set appropriately. I can setup ctest for afqmctools unit tests separately.

**Comment by fdmalone** [comment]
This has been merged and I assume they are working.

**Comment by prckent** [comment]
@fdmalone Actually there are some problems. As an AFQMC developer you need to keep an eye on https://cdash.qmcpack.org/CDash/index.php?project=QMCPACK

I will make some issues.

**Comment by fdmalone** [comment]
Is there an easy way to get pinged about this? It's not super easy to search cdash given all the failures.

**Comment by prckent** [comment]
Indeed it is not easy. This is why we have been reorganizing the tests and appealing for fixes. Generally any red in the deterministic tests or converters is an actionable problem. Performance tests sometimes have timeouts, but again, failures there are usually real problems. 

As a result of Jaron's helpful https://github.com/QMCPACK/qmcpack/pull/2457 all the tests in the nightly category should also represent real problems. We haven't gone through them yet since this was very recent.

You could focus on gcc complex mkl builds on sulfur, since I believe that this is the only combination for which all the python dependencies needed for AFQMC are satisfied. Make an issue if you need to see more.

**Comment by fdmalone** [comment]
I also can't seem to register to cdash to get email alerts?

**Comment by prckent** [comment]
@fdmalone Can we close this? The PySCF related tests aren't working well at the moment but I believe they are running for the gcc10+mpi combinations. I am not sure what is wrong with PySCF but it is not this issue.
