### ISSUE TITLE
Derive EstimatorManager from a new base class.  

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#214]
Hi all--
I'm thinking it would be a good idea to derive EstimatorManager (EstimatorManagerBase, e.g) from a new base class (EstimatorManagerBase, e.g).  The reason is that I want the ability to compute error bars on the fly via autocorrelation functions, and I want to supress/modify writing to *scalar.dat.  These required changes would be a lot more modular if variables/functions of EstimatorManger common to all QMC drivers lived in a base class, with the current EstimatorManager and my modified estimator manager deriving from it.  

Suggested changes:
1.) Create EstimatorMangerBase object and populate functions with functions common to all QMCDrivers.
2.) Change all references to EstimatorManager* in QMCDriver to EstimatorManagerBase*
3.) Add default initialization of EstimatorManager, with ability to choose alternatives.  Perhaps via a factory with optional xml block.

What does everyone think?  If its fine, I'll go ahead and implement the changes.

**Comment by jtkrogel** [comment]
I can't think of an immediate reason against doing this.  Are you planning to write some of the "final" values + error bars to the log?

**Comment by rcclay** [comment]
That's the plan.  Basically, if we start moving ions around and asking for the energy+error bar at each configuration, we want the EstimatorManager to automatically do the postprocessing the user currently does.  Also, restructuring the class makes it a lot easier to play with and drop in new EstimatorManagers in general.

**Comment by prckent** [comment]
Computing error bars on the fly would be very useful and strategic - this will let us specify target accuracies in the inputs (energies, properties such as forces).

**Comment by ye-luo** [comment]
Not sure if we need to change so much in EstimatorManager. Did you look at ScalarEstimatorBase? It seems having the capability to do calculate average variance for individual estimators. EstimatorManager is basically a collection of such classes.

**Comment by jtkrogel** [comment]
If I recall correctly, not all estimator-like quantities (e.g. QMCHamiltonianBase, which is far more common) derive from ScalarEstimatorBase.  I could be mistaken, but this would argue for something at the "manager" level.

**Comment by ye-luo** [comment]
@jtkrogel How many estimator like base class we have? QMCHamiltonianBase and ScalarEstimatorBase, also PostProcessorBase, else? What is the major difference? Calculated at different frequency? How do they interact with EstimatorManager?

**Comment by jtkrogel** [comment]
EstimatorManager was added later and sort of wraps around the original classes.  The implementation is a bit opaque: 

"LocalEnergyEstimator" actually accepts a QMCHamiltonian (which contains all QMCHamiltonianBase), and stores places in the scalars list for each observable in H.  Estimator manager then streams walkers from MCWalkerSet through all Estimators (only a few other than LocalEnergyEstimator), at which point LocalEnergyEstimator pulls accumulated observable values (corresponding to QMCHamiltonianBase's) from the property list of each walker (property list is populated by QMCHamiltonian, I believe).

So we have a rough equivalence between LocalEnergyEstimator and QMCHamiltonian, while EstimatorManager mostly just manages the direct interface to scalar.dat.  It has all the information and could therefore be used to manage twist averaging.

Ray: are you planning to do TA via MPI communication/reduce among EstimatorManager's, or are you considering a more fundamental rearrangement of the code for this (e.g. ditch MPI groups and push the existing group complexity into the classes -- lots of work, IMO not worth it).

**Comment by rcclay** [comment]
@jtkrogel Sort of a parallel discussion in Issue #147, but I'm thinking about doing the first thing you suggest:  MPI reduce among all EstimatorManagers for now.

**Comment by rcclay** [comment]
Quick question for @jtkrogel , @prckent , and @ye-luo .  I'm trying to bat out this issue.  Do you think its better to use the current EstimatorManager as a base class and allow the user to derive from it, or do you think its better to create an EstimatorManagerBase class, and then derive the current EstimatorManger from it?

**Comment by jtkrogel** [comment]
Is what you want to achieve additive w/ some replacement to current EstimatorManager functionality?  If so, adding new member functions + runtime logic to the existing EM would be clearer to read and understand than introducing new base classes.  

How extensive are the changes you are considering?

**Comment by prckent** [comment]
The naming needs to be rethought here, as should the roles of the different classes. e.g. EstimatorManager sounds like it should be a singleton.

**Comment by rcclay** [comment]
@jtkrogel .  For on-the-fly post-processing of DMC/VMC data, the easiest way to not modify the drivers is to be able to overwrite the start/stopBlock() and accumulate() behavior.  Additionally, if this gets a bit more sophisticated, it might be nice to play with I/O.

**Comment by prckent** [comment]
@rcclay On the fly processing = good. Then we'll be able to set a target error bar as a stop condition.

**Comment by jtkrogel** [comment]
Deriving a new EM from the current one and overwriting startBlock/stopBlock/accumulate is functionally equivalent to inserting a single if statement into each of these functions in the current EM (unless I am missing something).  I guess it comes down to whether we view a single EM operating in different modes (containing runtime logic) or splitting the runtime behavior (logic) across different versions of EM.

Personally, I would prefer to modify the current EM in place if it is workable.  Are there downsides to this that I am not seeing?

**Comment by prckent** [comment]
If what Jaron says is correct, lets not add to the number of files, classes etc for simple logic like this.

**Comment by rcclay** [comment]
@jtkrogel @prckent , when I say the easiest way not to mess with the drivers is by rewriting stop/startBlock and the accumulate() functions, I mean that's the only connection between the EstimatorManager and the rest of the code.  The actual changes/additions to EstimatorManager could be substantial.  If I want autocorrelation times for instance, there's a strong probability I'll need temporary arrays and functions supporting that capability, which will probably require changes to the constructor, put, and destructor functions.   If I want to do weighted twist averaging, there's more auxiliary data and routines associated with that.  For development and incorporation into the main code, it will be a lot easier from a readability, maintainability, and stability point of view to just swap between different "EstimatorManagers" at run time than it will be to add 1 or 2 code pathways per function and supporting data structures & flags to the current EstimatorManager.  

Also, philosophically speaking, while QMCPACK does have some excesses in terms of unnecessary inheritance, I think that the use of object oriented programming in QMCDrivers, QMCHamiltonian, and QMCWaveFunctions are appropriate.  I/O on the other hand, which is a textbook use case for object-oriented programming, is usually and woefully hard-coded in QMCPACK.  With the proposed modification to the level of inheritance of EstimatorManager, it will make it a lot easier to manipulate the stream of data coming out of our various drivers.

**Comment by jtkrogel** [comment]
@rcclay If changes are extensive and/or if multiple (and exclusive) code paths are involved then the inheritance approach is fine.  Putting shared/default functionality into a new base class is probably the way to go.

**Comment by rcclay** [comment]
Ok.  Sounds good.  So how should I structure this pull request?  Here's what needs to be done:
1.) Create EstimatorManagerBase class, and change all references in the code from EstimatorManager to EstimatorManagerBase.  
2.) Move essential/universal EstimatorManager data structures and functions to EstimatorManagerBase.  (I'm thinking about keeping the name EstimatorManager for the derived class). 
3.) Insert some XML parsing to allow switching between different EstimatorManagers.  

Should each of these be a pull request, or should I do them all and then submit the pull request?

**Comment by rcclay** [comment]
I think I'll stage these as 3 pull requests.

**Comment by jtkrogel** [comment]
@rcclay is this complete with PR #371 or are additional PRs still pending?

**Comment by ye-luo** [comment]
I am re-factoring the use and operation scope of EsitimatorManager to solve multiple issues.
At this point, it is not clear to me why inheritance is needed.

**Comment by prckent** [comment]
If we can reasonably flatten the structure, good. Please coordinate.

**Comment by jtkrogel** [comment]
Estimator refactoring is now following a new trajectory with the batched drivers.
