### ISSUE TITLE
MPI wrapper and AFQMC breaks Intel complex build

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2143]
https://cdash.qmcpack.org/CDash/viewBuildError.php?buildid=94091

**Comment by correaa** [comment]
It is strange, I can reproduce the error using the EDG front-end only when I *add* the move in `comm_{/*std::move(*/other.comm_/*)*/}` . In any case adding the `std::move` it is not a solution in my opinion.

This is in part why I don't like to hold a reference to the communicator in the `window` (and I don't actually https://gitlab.com/correaa/boost-mpi3/blob/master/shared_window.hpp#L23). 
Perhaps switching to a communicator pointer instead of a reference is the way to go in the custom version of MPI3.

**Comment by mmorale3** [comment]
Alfredo, 
Did you fix the issue with the version of the constructor in communicator that blocked globally (the one that took a group as argument)?
I can't get rid of the reference (or pointer) to the communicator in shared_window with this problem.

**Comment by correaa** [comment]
On Wed, Dec 11, 2019 at 10:56 AM mmorale3 <notifications@github.com> wrote:

> Alfredo,
> Did you fix the issue with the version of the constructor in communicator
> that blocked globally (the one that took a group as argument)?
>

yes. Indirectly, in the sense that the reference is not needed.

> I can't get rid of the reference (or pointer) to the communicator in
> shared_window with this problem.
>
Great. I think that is the sane approach, if there is an obvious
performance degradation we can keep looking for solution.

As I tried to explain before, my idea is that any performance cost of
creating a communicator is amortized by the fact that a barrier is needed
anyway (even if one has the communicator already) in the general case
(after any non-trivial operation).

I might be wrong but it is reasonable to think that the cost of a barrier,
of a broadcast or a communicator creation are all of the same order. Is it
also possible that the mpi environment could be caching some frequently
used communicator setup (especially here that there is an actual instance
of the communicator in existence)

Thanks,
Alfredo

**Comment by mmorale3** [comment]
Alfredo,

You are still using MPI_Comm_create, this blocks on world.

**Comment by correaa** [comment]
> Alfredo,
> 
> You are still using MPI_Comm_create, this blocks on world.

Use the communicator constructor (from group) with the extra integer.

https://gitlab.com/correaa/boost-mpi3/blob/master/communicator.hpp#L2938

I am simply following the fact that the only difference in the MPI API (besides the horrible ambiguous names) is that the one function takes an extra tag argument (the one that doesn't block) and the other dossn't take the integer (and blocks)

https://www.mpich.org/static/docs/latest/www3/MPI_Comm_create.html
https://www.mpich.org/static/docs/latest/www3/MPI_Comm_create_group.html

I don't know. I could force the non-blocking "by default" (and also use a defaut tag to pass), but it  will be a bigger departure from MPI.

By the way, the documentation says:
`tag: safe tag unused by other communication` (is it unused???)

**Comment by prckent** [comment]
Intel 2019: https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=95056
Intel 2018: https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=95037
Is this a compiler bug fixed in 2019 or capability improvement?

**Comment by correaa** [comment]
Hi Paul,

On Mon, Dec 16, 2019 at 6:34 AM Paul R. C. Kent <notifications@github.com>
wrote:

> Intel 2019: https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=95056
> Intel 2018: https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=95037
> Is this a compiler bug fixed in 2019 or capability improvement?
>
I think it is both.

The error in icc2018 was strange by itself and if I understand icc2019
doesn't complain.

However, for other reasons we have been discussing with Miguel whether it
really made sense to have a copy (reference) to the communicator in the
shared_window class.

The current agreement is that we don't have to have that reference to the
communicator, therefore the offending code shouldn't be there in the first
place.
https://gitlab.com/correaa/boost-mpi3/blob/master/shared_window.hpp#L25

That means that icc2018 will work again, whether it is a bug in the
compiler or not.

Thanks,
Alfredo

**Comment by prckent** [comment]
Super. It is a little premature to drop Intel2018, so making it work is preferred.

**Comment by prckent** [comment]
Confirmed working https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=95485
