### ISSUE TITLE
Question regarding nonlocalpp_deriv

### ISSUE THREAD

**Issue by mcbennet** [QMCPACK/qmcpack#2149]
The following is more of a question than an issue.

I recently performed a collection of optimizations with version 3.8.0 and the latest development code (commit 25fddfc) -- I used AoS build. For each code I ran all combinations of {quartic,oneshiftonly} and {nonlocalpp=false, nonlocalpp=true, nonlocalpp=true and nonlocalpp_deriv=true}.

In the case of version 3.8.0, I noticed that all cases where nonlocalpp_deriv is set true, the optimizer performs poorly. However, with the latest development code, this issue seems to be resolved and all cases lead to stochastically identical results. 

Does anyone know what differences between the two codes could lead to these very different behaviors in the case of nonlocalpp_deriv=true?

Results from Development here
![dev](https://user-images.githubusercontent.com/1430804/70823691-87ea0f80-1dae-11ea-8bd0-95a24b028458.png)

Results from v3.8 here
![v3 8](https://user-images.githubusercontent.com/1430804/70823696-8caec380-1dae-11ea-9f80-0b89af56059b.png)

**Comment by prckent** [comment]
Very good question - I know of other people having troubles with optimization, perhaps due to the same problem. However I don't recall an intentional "meaningful" change to the optimizer over this time. Of course we could check blame or the commit history. We are also clearly missing a test to catch this.

**Comment by ye-luo** [comment]
There was some issue with LCAO in v3.8.0 and fixed in #1830

**Comment by ye-luo** [comment]
Please reopen if there is further questions.
