### ISSUE TITLE
Old (python 2) nexus pickle files fail to load in python 3

### ISSUE THREAD

**Issue by tiihonej** [QMCPACK/qmcpack#2211]
The nexus' pickle files to store information and data on workflows are incompatible between the earlier code (python 2.7.x) and the recent (python 3). Trying to load and old pickle file with the new code leads to an error such as this:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 6: ordinal not in range(128)`

The old file can be successfully loaded with 'encoding=latin1', but that again won't work on the new files. It means that one cannot very reliably mix the two versions in one workflow.

I believe this will impact also others than just me, and thus discussion is called for on how to best get around this problem.

Some of the possible practices would include:
1. Hold on the migration until the project is finished
2. Manually convert the old pickle files before proceeding with the workflow
3. Implement a legacy loader for nexus that recognizes the encoding

**Comment by markdewing** [comment]
I would think making a version converter tool might be the best option (versus 3).   That way users would be alert to potential problems with the conversion.

**Comment by PDoakORNL** [comment]
Object serialization isn't a good way to archive or record the configuration of anything.

**Comment by tiihonej** [comment]
Thank you for your views. And sorry for what appears to be a false alarm in the big picture. The symptoms and the nature of the said problem seem to be limited to those pickle files created between the original python 3 transition and the recent encoding fix, PR #2210 . Any older or newer nexus files should work without a hitch. This short window is unlikely to affect many other users than myself, so I'm closing the issue.

**Comment by prckent** [comment]
Thanks Juha. If this turns up again we should give more thought to it. I was not aware of the pickling issue before you mentioned it.
