### ISSUE TITLE
Timestep extrapolation with a twist grid

### ISSUE THREAD

**Issue by jcoulter12** [QMCPACK/qmcpack#2226]
I'm attempting to perform timestep extrapolation for a system where it's favorable to include twist averaging. However, it seems that the qmc-fit tool isn't currently set up to consider a twist grid. 

Is there any recommended way to perform timestep extrapolation with a twist grid?

**Comment by camelto2** [comment]
Hi. I had this issue a while back and issued a fix. See #1401 

This will allow you to perform twist averaging with qmca, and by adding the --save_average option, it should write some averaged scalar.dat files. You can then use those new files alongside qmc-fit to perform the time step extrapolation on the twist averaged data.

**Comment by jcoulter12** [comment]
Wonderful, this appears to have worked. I initially overlooked this issue based on the title, thanks for pointing it out!
