### ISSUE TITLE
Configuration of tests in CMake is slow

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#2227]
#2203 contains a workaround - the QMC_NO_SLOW_CUSTOM_TESTING_COMMANDS flag.

This issue is to collect data and look for a more general solution.

I ran strace on the cmake configuration to see what external commands are taking time.

(Details: `strace -o stmp2.txt -ttt -T -f -e trace=%process ./s1`, where s1 is the script that runs the cmake configuration.  A python script read the strace output and accumulated time by process.)

The most time consuming processes for each case shown below (times are inclusive).  The 'cmake -E' commands are converted to a separate process name.  The 'cmake' at the bottom of each list is the overall cmake command (and it includes none of the cmake -E times).

### Without NO_SLOW flag
```
3.750469207763672 cmake_E_ "create_symlink"
5.050021409988403 /home/mdewing/physics/codes/qmcpack/github/qmcpack/tests/scripts/test_import.py
9.269521236419678 /usr/bin/make
9.886006355285645 /home/mdewing/physics/codes/qmcpack/github/qmcpack/tests/scripts/test_labels.py
14.621734619140625 /home/mdewing/anaconda3/bin/python3
35.77018904685974 /home/mdewing/prev/software/cmake/cmake-3.8.1/bin/cmake

```

### With NO_SLOW flag
```
3.1287143230438232 /home/mdewing/physics/codes/qmcpack/github/qmcpack/tests/scripts/test_labels.py
3.341794729232788 /home/mdewing/anaconda3/bin/python3
4.124614238739014 /usr/bin/make
7.532416105270386 /home/mdewing/prev/software/cmake/cmake-3.8.1/bin/cmake
7.550512075424194 ./s1

```

The calls to the python scripts test_labels.py and test_imports.py accounts for 15 seconds (out of 35).   They take time, but are not solely responsible for the test configuration slowness.

(It might be possible to cache the output of these scripts in a file and use that file for dependency checking)

Further investigation may require timing from cmake itself.  The --debug-output flag looks useful, but it lacks time information.

**Comment by PDoakORNL** [comment]
This is useful. I built a profiled version of cmake but all it showed me was the outside commands were slow. 

I can say I have cached the python dependency checks in the past. It didn’t make a significant difference with python 2 so I didn’t PR it.

**Comment by markdewing** [comment]
For completeness, a copy of the strace processing script is attached
[read_strace.py.gz](https://github.com/QMCPACK/qmcpack/files/4072571/read_strace.py.gz)

(File is gzipped because it would not let me attach a *.py file)

**Comment by ye-luo** [comment]
Another data point. I noticed using system python3 is much faster than anaconda.

**Comment by PDoakORNL** [comment]
Anaconda is pretty bloated but I’m surprised it effects startup time which I think is a significant issue for us. I suggest miniconda and just the needed packages.

However other issues are Are system python and anaconda on different file systems? Which platform x86-64 or another?

**Comment by ye-luo** [comment]
Probably it is more of file system difference. On my workstation (bora), Anaconda is on a network files system while system python3 is on local SSD.

**Comment by ye-luo** [comment]
Can we have call counts? What are the numbers today?

**Comment by ye-luo** [comment]
cmake 3.18 supports profiling cmake scripts. Add the following to your cmake command line
```
--profiling-format=google-trace
--profiling-output=qmcpack-cmake.json
```
Then open the json file using chrome browser `about:tracing`

**Comment by quantumsteve** [comment]
Is caching the results of `test_labels.py` sufficient to close this issue?

**Comment by ye-luo** [comment]
Right now `test_labels.py` is still slow but we only pay the cost once. So probably it is good enough for now.
