### ISSUE TITLE
QE 6.5 support

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2230]
This is a request from Fernando Reboredo and Tomohiro Ichibha.  They are anxious to use QE 6.5 to generate spin-polarized states with the SCAN functional for use in QMCPACK.  This would require an updated `download_and_patch_qe6.5.sh` script.

**Comment by jtkrogel** [comment]
Refer to @ichibha.

**Comment by ye-luo** [comment]
Need a bit time to work on this. Expect ready mid Feb.

**Comment by ichibha** [comment]
Thank you for your effort, @ye-luo. Requested by @prckent, I have confirmed that spin-polarized calculation works with SCAN with QE 6.5.

**Comment by prckent** [comment]
Thanks @ichibha
