### ISSUE TITLE
Uninitialized value M in DMCBatched::setMultiplicities

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2243]
GCC warning detects this in #2232 
The original code in QMCUpdateBase::setMultiplicity sets M = walker.Weight.
DMCBatched::setMultiplicities is not doing the same way.
Please explain the change and fix the warning as well.

**Comment by PDoakORNL** [comment]
I'll fix it but GCC is incorrect.
```C++
    RealType M;
    if (walker.Age > dmcdriver_input.get_max_age())
      M = std::min(onehalf, M);
    else if (walker.Age > 0)
      M = std::min(cone, M);
    else
      M = walker.Weight;
```
