### ISSUE TITLE
Estimator sofk tests are crashing

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2245]
e.g. estimator-sofk_allp-collectables-1-16, estimator-sofk_pbyp-properties-1-16, estimator-sofk_allp-collectables-1-16, and more.

This is new behavior in the last ~week.

https://cdash.qmcpack.org/CDash/testDetails.php?test=7281820&build=101633
https://cdash.qmcpack.org/CDash/testDetails.php?test=7281819&build=101633
https://cdash.qmcpack.org/CDash/testDetails.php?test=7281819&build=101633

**Comment by jtkrogel** [comment]
Is this resolved?

**Comment by ye-luo** [comment]
All looks OK from last night.
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2022-02-03&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=estimator-sofk_pbyp-properties-1-16
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2022-02-03&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=estimator-sofk_allp-properties-1-16
https://cdash.qmcpack.org/CDash/queryTests.php?project=QMCPACK&date=2022-02-03&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=estimator-sofk_allp-collectables-1-16
