### ISSUE TITLE
OutputManager needs a query mechanism

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2248]
When developing codes, sometimes I add app_log() but got nothing printed because the stream is paused. so need a way to query OutputManager the current status.

**Comment by prckent** [comment]
Perhaps OutputManager could always flush the stream. This would be simpler.

**Comment by ye-luo** [comment]
Unfortunately this is not a flush problem. OutputManager redirects output to nullstream if paused. I need to know if it is paused or not in a particular position of code.
