### ISSUE TITLE
Nexus needs to be tested by CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2263]
If this is duplication, please let me know.
#2262 indicates more automation is needed.

**Comment by prckent** [comment]
The nexus tests are missing the deterministic label that would cause them to run in the CI. Notice that they report under "nightly" results on cdash. By eye they take under 2 minutes in total to run.

**Comment by ye-luo** [comment]
I prefer not to add deterministic label to nexus tests. Instead we update CI scripts. Nexus can have a separate section on the cdash. Mixed in the nightlies is bad.

**Comment by prckent** [comment]
There are two issues around testing nexus the: First, CI != cdash. Second, how we label or identify the nexus tests. For CI it looks to be a one line change.

**Comment by PDoakORNL** [comment]
I think that we're getting to big for one repo, one PR queue, and One CI. Cmake/ctest/cdash are not a good look for python nor were they meant to be.
