### ISSUE TITLE
New DMC bug causing deterministic failures

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2315]
**Describe the bug**

The vmc-dmc trace checks are newly failing (e.g.  deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars-1-1) , indicating a new bug in DMC.
https://cdash.qmcpack.org/CDash/testDetails.php?test=7477769&build=104813
These deterministic tests have been totally reliable for a long time, but failed Tuesday evening. Possibly #2221 is to blame.

```

  TauEff     = 1.0000e-02
 TauEff/Tau = 1.0000e+00
  Etrial     = -8.0741e+01
 Running average of energy = -1.1722e+01
                  Variance = 2.2062e-01
branch cutoff = 1.0000e+01 1.5000e+01
WARNING The number of walkers is running lower than Min Walkers per MPI rank : 1. Floor is applied
WARNING WalkerControlBase::applyNmaxNmin not able to add sufficient walkers overall!
ERROR Some MPI ranks have no walkers after load balancing. This should not happen.Improve the trial wavefunction or adjust the simulation parameters.
Fatal Error. Aborting at WalkerControlBase::sortWalkers
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

```

**To Reproduce**

1. Latest develop
2. NIghtly GCC9-MKL build
3. ctest -R  deterministic-diamondC_1x1x1_pp-vmc-dmc-trace
4. None

**Expected behavior**

Deterministic tests should always pass.
Note that only GCC9+MKL has failed so far.

**System:**
 - system name [e.g. fusiont5, summit]: oxygen.ornl.gov
 - modules loaded [e.g. output of `module list`]: see tests/test_automation
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

**Comment by ye-luo** [comment]
#2221 seems fine. The run one night before was OK.
https://cdash.qmcpack.org/CDash/testDetails.php?test=7470068&build=104698

I noticed that trace_scalars and trace_scalars_sel are not deterministic. The random seeds are not fixed. check_traces.py only "Performs consistency checks between traces.h5 and scalar.dat/stat.h5/dmc.dat files"

A fixed to this issue is fixing seeds in test input files. @jtkrogel @prckent let me know if this solution is reasonable.

**Comment by ye-luo** [comment]
I can reproduced the failing by injecting random seed 36. The code tries to load balancing 2 walkers and killed all the workings due to over correction at one step.

**Comment by jtkrogel** [comment]
The runs are not deterministic, but the check is.  

The check is that the internal sum of per walker energies matches what is in scalar.dat and dmc.dat.
Since this equality should always hold, the check is deterministic.

Having additional entropy should help us catch subtle bugs that violate this constraint.

**Comment by ye-luo** [comment]
The current issue was that DMC cannot get completed due to load balancing with pathological electronic configurations. This needs to be resolved first.

**Comment by prckent** [comment]
It worked again this morning.

We need to avoid pathological configurations. I think that the correct way to do this is with a fixed seed.

**Comment by jtkrogel** [comment]
Is DMC's failure to load balance a bug or not?

**Comment by ye-luo** [comment]
In the current load balancing algorithm, all the walkers get killed all of a sudden in this test case. I consider it a feature not a bug.

**Comment by jtkrogel** [comment]
OK, probably some change has been made to the DMC algorithm at some point w.r.t. a subset of: load-balancing, weighting, when traces are collected.  I used to be able to verify scalar.dat and dmc.dat files for DMC from much longer DMC runs (including lots of load balancing).

It's sad that we can't currently benchmark in this way, but I agree that for the purpose of testing the code in its current configuration, fixing the seed is best.

**Comment by prckent** [comment]
I think we simply got unlucky with the seed and the DMC run quit since it ran out of walkers. That is all. Checking the history I noticed a couple of other failures in the first week of January 2020.
