### ISSUE TITLE
[regression in 3.9.1] error: use of undeclared identifier 'sched_getcpu'

### ISSUE THREAD

**Issue by yurivict** [QMCPACK/qmcpack#2323]
Build fails on FreeBSD 12:

```
In file included from /wrkdirs/usr/ports/science/qmcpack/work/qmcpack-3.9.1/src/Message/Communicate.cpp:28:
/wrkdirs/usr/ports/science/qmcpack/work/qmcpack-3.9.1/external_codes/mpi_wrapper/mpi3/shared_communicator.hpp:46:14: error: use of undeclared identifier 'sched_getcpu'
                        int cpu = sched_getcpu();
                                  ^
```

In src/QMCTools/check-affinity.cpp you only call this function on linux:
```
#ifdef __linux__
  int cpuid = sched_getcpu();
  return cpuid;
#else
  return -1;
#endif
```
but in external_codes/mpi_wrapper/mpi3/shared_communicator.hpp you use it unconditionally.

**Comment by prckent** [comment]
Thanks for the report and sorry for the problem.

@correaa Please can you fix this in your "upstream" mpi wrapper and plan with @markdewing how/when to update our copy? This breaks the build on FreeBSD.

**Comment by correaa** [comment]
Fixed upstream https://gitlab.com/correaa/boost-mpi3/-/blob/master/shared_communicator.hpp#L51
Seems that freeBSD doesn't have a dropin replacement for getcpu.

@markdewing , let's try to unify the versions. I can set up my repository to push changes automatically to your repository.

**Comment by prckent** [comment]
I hope we can move to using synchronized but also versioned/tagged releases of the wrapper in QMCPACK.

**Comment by ye-luo** [comment]
This choked Mac as well. All work now.
