### ISSUE TITLE
savetoqmcpack() bug

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/qmcpack#2352]
**Describe the bug**
savetoqmcpack() function is not saving
```
KPTS_0                   Group
Nb_KPTS                  Group
```
if pyhon3 is used for open boundary systems. qmcpack will crash without these groups.

**To Reproduce**
1. Release v3.9.1 and python3 environment
2. Use on open boundary system.

**Expected behavior**
When tested on Release v3.7 and python2 environment works fine.

**System:**
 - Nersc, Cori. Also tested on : Alcf, Theta
 - Modules:
```
export HDF5_USE_FILE_LOCKING=FALSE
module unload cray-libsci
module load cray-hdf5
module load python; source activate nexus3;
```

**Comment by prckent** [comment]
Thanks. Hopefully this is a small missing update to NEXUS from the python3 transition.

**Comment by jtkrogel** [comment]
`savetoqmcpack` is not part of Nexus, though it is written in Python. @anbenali is the author.

**Comment by jtkrogel** [comment]
See https://github.com/QMCPACK/qmcpack/blob/develop/src/QMCTools/PyscfToQmcpack.py

**Comment by anbenali** [comment]
@aannabe 
I am not able to reproduce your issue. 
PyscfToQmcpack.py does not generate anymore KPTS_0 or Nb_KPTS since commit of May 2nd 2019... 

Can you send me your pyscf input file, H5 file and PyscfToQmcpack.py (just to make sure)

Thanks

**Comment by aannabe** [comment]
I double-checked the inputs and it seems I used 3.7 binary for the newest PyscfToQmcpack.py which are incompatible with each other. Sorry for the trouble.
