### ISSUE TITLE
Segmentation fault when running the example

### ISSUE THREAD

**Issue by xuzpgroup** [QMCPACK/qmcpack#2353]
Dear all,

Now I am running the examples of "qmcpack_workshop_2019/day2_nexus/quantum_espresso/02_qe_diamond_dft_vmc".

When I run job for jastrow optimization, it returns as follow.

...
<parameter name="time_step" condition="au">3.0000000000e-01</parameter>
<parameter name="timestep" condition="au">3.0000000000e-01</parameter>
<parameter name="use_drift" condition="string">no</parameter>
<parameter name="usedrift" condition="string">no</parameter>
<parameter name="walkers" condition="int">1</parameter>
<parameter name="warmup_steps" condition="int">300</parameter>
<parameter name="warmupsteps" condition="int">300</parameter>
  DumpConfig==false Nothing (configurations, state) will be saved.
  Walker Samples are dumped every 1 steps.
</vmc>
  Adding a default LocalEnergyEstimator for the MainEstimator 
 Using QMCCostFunctionOMP::QMCCostFunctionOMP
  Adding a default LocalEnergyEstimator for the MainEstimator 
<optimization-report>
<vmc stage="main" blocks="100">
  Initial partition of walkers 0 1 

  Using Particle by Particle moves
  Walker moves without drift
  Total Sample Size   =51200
  Walker distribution on root = 0 1 
  Using Locality Approximation

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 30702 RUNNING AT test01
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
The attached file is log file. Can any help me?

Best,
Justin

[log_optJ2.zip](https://github.com/QMCPACK/qmcpack/files/4369319/log_optJ2.zip)

**Comment by ye-luo** [comment]
It seems that you are using v3.4.0 which is more than two years old.
Please try most recent release 3.9.1 or develop.

**Comment by prckent** [comment]
Please can you try the latest release version (3.9.1) and also report which other runs & tests are successful or not. The attached run used v3.4.0. Thanks.

**Comment by xuzpgroup** [comment]
> It seems that you are using v3.4.0 which is more than two years old.
> Please try most recent release 3.9.1 or develop.

Dear Ye Luo,

Thank you very much for our suggestion.

Best,
Justin

**Comment by xuzpgroup** [comment]
> Please can you try the latest release version (3.9.1) and also report which other runs & tests are successful or not. The attached run used v3.4.0. Thanks.
> 
> Edit: Didn't see Ye's reply until I posted, which has the same recommendation.

Thank you very much for our suggestion.

**Comment by xuzpgroup** [comment]
> It seems that you are using v3.4.0 which is more than two years old.
> Please try most recent release 3.9.1 or develop.

But When I use the example of diamond in the package of version 3.4.0, it also have  the same problem when I run qmcpack.

[log_diamond.zip](https://github.com/QMCPACK/qmcpack/files/4372800/log_diamond.zip)

**Comment by xuzpgroup** [comment]
> It seems that you are using v3.4.0 which is more than two years old.
> Please try most recent release 3.9.1 or develop.

It is OK when I use 3.9.1.
Thank you very much.

**Comment by ye-luo** [comment]
Glad to hear that.
