### ISSUE TITLE
Generic data structure for AoS vs. SoA layouts?

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#2356]
Is there value in creating a generic 2-D data structure that can switch between AoS and SoA layouts while presenting a uniform interface?

The concrete place where this shows up is in creating batched versions of evaluation functions for parameter derivatives.
The current function (`TrialWaveFunction::evaluteDerivatives`) produces a vector of derivatives (`std::vector<ValueType>& dlogpsi`).  The size of the vector is the number of variational parameters.  When moving to a batched interface, this will need to be 2D structure over a number of configurations and the number of parameters.

The calling code in QMCCostFunction already stores this data over configurations (samples) and parameters in a Matrix type `DerivRecords`. (In the actual code, there is a std::vector of these, but that vector is for thread-local storage of each structure)

The straightforward way to create a batched version is to either use a nested `std::vector` or to switch to a Matrix type.   The downside is the layout is then fixed by the data structure, how it is created, and all the places that use the data structure (order of indices).

Another solution is to create a more generic structure where accesses have fixed order (e.g. sample index first, parameter index second), but the mapping of that index to the underlying storage can change.

First question - does such a data structure already exist in QMCPACK?
Second question - would such a structure be useful?   Using a Matrix or nested std::vector is a straightforward idiom, but has the drawbacks listed above.

For the parameter derivatives I'm not sure performance of this structure is the most critical.   Ease of programming might is of higher importance.  I could make a data structure specific to parameter derivatives, but it really seems like a more general problem.

If performance doesn't matter, than any layout control or switching in the prototype is unnecessary.  What I'm aiming for is that if memory layout does matter, then it should be easy to change and experiment with without changes to how the data structure is used.

Prototype:
```
template<typename T>
class RecordList
{
public:
  int nparam_;
  int nentry_;

  int param_dim_;
  int entry_dim_;


  void transpose() {
    // Need to do in-place rectangular transpose
  }

  void setValue(int param_idx, int entry_idx, T value)
  {
   storage[param_idx + entry_idx * nparam_] = value; // AoS (param is fastest varying)
   //storage[param_idx * nentry_ + entry_idx] = value; // SoA (entry is fastest varying)
  }

  T getValue(int param_idx, int entry_idx) {
    //return storage[param_idx + entry_idx * nparam_]; // AoS (param is fastest varying)
    //return storage[param_idx * nentry_ + entry_idx]; // SoA (entry is fastest varying)
    return storage[param_idx*param_dim_ + entry_idx *entry_dim_];
  }

  RecordList(int nparam, int nentry) : nparam_(nparam),nentry_(nentry) {
    storage.resize(nparam_ * nentry_);
    // AoS (or record-oriented) - param is fastest varying
    param_dim_ = 1;
    entry_dim_ = nparam_;

    // SoA (or column-oriented) - entry is fastest varying
    //param_dim_ = nentry_; 
    //entry_dim_ = 1;
  }

  bool isAOS() {
    return param_dim_ == 1;
  }

  bool isSOA() {
    return entry_dim_ == 1;
  }

  void setAOS() {
    if (!isAOS()) {
      param_dim_ = 1;
      entry_dim_ = nparam_;
      transpose();
    }
  }
  void setSOA()
  {
    if (!isSOA()) {
      param_dim_ = nentry_;
      entry_dim_ = 1;
      transpose();
    }
  }

  std::vector<T> storage;

};

int main()
{
  int N = 3;
  int np = 1;
  RecordList<double> P(np, N);
  return 0;
}


```

**Comment by prckent** [comment]
The answer for now is, I believe, no. Are there cases where both layouts would be very useful other than for dealing with legacy?

For the optimizer the layout is not very sensitive, so we should use whatever requires the minimum amount of human effort for now. This could mean the batched code generating them in whatever the current layout needed by the optimizer is. The SoA CPU code does so successfully.

If we turn out to need many flexible view like structures we should not write them ourselves.

**Comment by PDoakORNL** [comment]
I think this can be closed.  Remember to search all issues when considering a design issue.
