### ISSUE TITLE
Qmcpack error: analyzer did not compute results required to determine jastrow

### ISSUE THREAD

**Issue by xuzpgroup** [QMCPACK/qmcpack#2378]
Dear all,

Now I am running qmcpack by using NEXUS. It returns the error when finishing jastrow optimization as follow ,

....
    Entering ./graphene_p-1L-tw/opt 3 
      copying results  3 opt 
    Entering ./graphene_p-1L-tw/opt 3 
      analyzing  3 opt 

  elapsed time 297.3 s  memory 98.62 MB 

  Qmcpack error:
    analyzer did not compute results required to determine jastrow
  exiting.

  File "graphene-1L-tw.py", line 205, in <module>
    run_project(sims)
.....

The attachments are input and log file of NEXUS.

Can anyone give me some suggestions?

Best,
Justin 

[log_and_input_nexus.zip](https://github.com/QMCPACK/qmcpack/files/4469551/log_and_input_nexus.zip)

**Comment by jtkrogel** [comment]
I'm looking into it.

**Comment by jtkrogel** [comment]
It looks like you are performing twist averaged calculations and optimizing the Jastrow for each twist separately. While this is perfectly acceptable from the point of view of QMC, the ability to map the per twist Jastrows from one QMCPACK calculation to another has not been implemented in Nexus.

Typically, a Jastrow factor optimized at one twist is sufficient for the others.  To operate in this way, add, e.g., `twistnum = 0,` to the optimization calculation, either remove the contents of `./graphene_p-1L-tw/opt` or run `nxs-redo ./graphene_p-1L-tw/opt` to store the first attempt, and then rerun.

**Comment by prckent** [comment]
@jtkrogel Would you be able to error trap this case for now?

**Comment by jtkrogel** [comment]
Should be.  I'll have a look at producing a more descriptive error for this particular case.

**Comment by xuzpgroup** [comment]
> twistnum = 0

It works well when setting twistnum = 0.

By thy way, thank you very much for the suggestions on the Jastrow optimizations.
