### ISSUE TITLE
How to contine the running using NEXUS

### ISSUE THREAD

**Issue by xuzpgroup** [QMCPACK/qmcpack#2380]
Dear all,

I have finished the Jastrow optimization using the input file generated by NEXUS.

The state of workflow is shown as follow,
  cascade status 
    setup, sent_files, submitted, finished, got_output, analyzed, failed 
    111111  0  25846     scf     ./graphene_p-1L-tw/scf  
    111111  0  25977     nscf    ./graphene_p-1L-tw/nscf  
    111111  0  26108     p2q     ./graphene_p-1L-tw/nscf  
    **111000**  0  26152     opt     ./graphene_p-1L-tw/opt  
    000000  0  ------    dmc     ./graphene_p-1L-tw/dmc  
    setup, sent_files, submitted, finished, got_output, analyzed, failed 

Now I want to use the results of Jastrow optimization to generate the input file for DMC.
I find NEXUS can only continue the running with all the the cascade status is 1. In this case (111000), it does not work.

I have a tricky way that copy a **sim_opt** folder whose status is 111111 to ./opt. But I don't know whether or not it will effect the generated input of DMC.
 
So, how to continue the running (now it should start from the **got_output** and **analyzed** in opt ) in this case?

Best,
Justin

**Comment by jtkrogel** [comment]
If you want to force Nexus to proceed, you can use the `nxs-sim` tool to manually modify the status flags.  In your case, do `nxs-sim set finished ./graphene_p-1L-tw/opt/sim_opt/sim.p`.  This will update the status to be 111100.

**Comment by xuzpgroup** [comment]
> If you want to force Nexus to proceed, you can use the `nxs-sim` tool to manually modify the status flags. In your case, do `nxs-sim set finished ./graphene_p-1L-tw/opt/sim_opt/sim.p`. This will update the status to be 111100.

Thank your very much for your suggestion. The tool of 'nxs-sim' can change the cascade status to 111111 but I cannot generate the 'analyzer.p' file.

I find it cannot generate the input without 'analyzer.p'. So is there other tools can generate this file?

**Comment by jtkrogel** [comment]
You need to set the status to `111100`.  You can do this from the current state in this way: `nxs-sim unset got_output analyzed ./graphene_p-1L-tw/opt/sim_opt/sim.p`.

This way, Nexus will complete the analysis step and create the `analyzer.p` file.

**Comment by jtkrogel** [comment]
@xuzgroup, did this work for you?

**Comment by hzhou23** [comment]
Hello Dr.Jaron,

I am now seeing the same issue, where the connection to nexus was forced terminated when the jobs are not finished. I'm pretty new to the code, is there a way for me to get the cascade status for my current job? I opened the sim.p file, there is no obvious cascade status.

An other quick question is that, once I changed the status by 'nxs-sim', should I just go back and rerun the nexus input python script and the code will automatically continue? 

Thanks in advance!

**Comment by jtkrogel** [comment]
Hi @hzhou23,

You can get the status printed by using the `--status` option. If your Nexus script is called `workflow.py`, you can get the status of all jobs by running `workflow.py --status`.

For more details about what the status report means, read over this walkthrough example:

https://github.com/QMCPACK/qmcpack/tree/develop/nexus/examples/quantum_espresso/01_diamond_scf

If the job in question has actually completed successfully, but Nexus reports a status of `111000` (submitted but not finished), then you can do `nxs-sim set finished ./path/to/my/run/sim_prefix/sim.p`.  This will set the "finished" bit (status is now `111100`), and you can make the workflow proceed by just rerunning your workflow script.

**Comment by hzhou23** [comment]
> 

Thanks Dr.Jaron. I will look into the example provided there and try out.
