### ISSUE TITLE
compiling catch main is slow

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2387]
Compiling the catch main takes a lot of time. IBM XL took > 5 mins each time. Other x86 compilers also take noticeable time.

Every unit test binary has a main either from 
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```
or
```
catch_mpi_main.hpp
```
To reduce the redundant computation, we can change catch_mpi_main.hpp to catch_main.cpp and build it once. Then all the unit test use this catch_main target.

We then can clean up
```
OHMMS::Controller->initialize(0, NULL);
```
which is duplicated in many tests.

**Comment by prckent** [comment]
Have you experimented with precompiled headers?

**Comment by ye-luo** [comment]
Need cmake 3.16 which is too new to go right away.
No matter what way to pick, certain source code refactoring is needed.
