### ISSUE TITLE
srun: unrecognized option '--bind-to'

### ISSUE THREAD

**Issue by fdmalone** [QMCPACK/qmcpack#2408]
Is there a way to optionally remove this bind-to option for ctest? srun doesn't like it.

**Comment by ye-luo** [comment]
I believe OpenMPI was detected.
Did you see "Detected Open MPI. Setting bind-to options for thread affinity in MPIEXEC_PREFLAGS." message in cmake?

You may pass -D MPIEXEC_PREFLAGS=" " to workaround "bind-to"

**Comment by fdmalone** [comment]
whoops. I messed up my build script when I tried -D MPIEXEC_PREFLAGS=" " . Can confirm this fixes my problem. Thanks!

**Comment by fdmalone** [comment]
Sorry, I was too quick there -D MPIEXEC_PREFLAGS=" " seems to cause srun to choke for me with the following error slurmstepd: error: execve():  : No such file or directory. It looks as if it thinks " " is the executable.

**Comment by fdmalone** [comment]
Should I just use mpiexec over srun to launch ctest?

**Comment by ye-luo** [comment]
1.Try -DMPIEXEC_PREFLAGS="" and see what happens.
2. in addition, change line 496 `NOT MPIEXEC_PREFLAGS` to `NOT DEFINED MPIEXEC_PREFLAGS`

**Comment by ye-luo** [comment]
It depends on your system, if srun is the proper runner provided by the system, you should not use mpiexec even if it was found somewhere.

**Comment by ye-luo** [comment]
Try -DMPIEXEC_PREFLAGS=";" and see what happens.

**Comment by fdmalone** [comment]
-DMPIEXEC_PREFLAGS=";" seems to work

**Comment by ye-luo** [comment]
`;` in CMake is the separator for list items. Then CMake gets rid of it when expanding a list of elements into a command line.

**Comment by fdmalone** [comment]
Ok thanks. This seems a little hacky but it's good enough for me.
