### ISSUE TITLE
short-bccH_1x1x1_ae-dmc_sdj-1-16 too short 

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#241]
This dmc test is too short and causes false alarms. Need to be longer to decorrelate the samples.
See my plot based on tests/solids/bccH_1x1x1_ae/qmc-ref/qmc_short_vmc_dmc.s001.scalar.dat
![short-issue](https://cloud.githubusercontent.com/assets/1454251/26656299/1a89c494-4624-11e7-8ea5-5b3921803967.png)

**Comment by prckent** [comment]
This test looks nearly stable in cdash. I suggest x4 on the block count.

**Comment by ye-luo** [comment]
Cdash shows (click dashboard test)
Test Name 	Failure 	Timeout 	Total Runs 
short-bccH_1x1x1_ae-dmc_sdj-1-16-potential 	40.91% 	0% 	22
short-bccH_1x1x1_ae-dmc_sdj-1-16-kinetic 	36.36% 	0% 	22
short-bccH_1x1x1_ae-dmc_sdj-1-16-eeenergy 	27.27% 	0% 	22
Too high (>20%) failing rate.
I will make the test longer.
