### ISSUE TITLE
Large variance in PP molecular system

### ISSUE THREAD

**Issue by mcbennet** [QMCPACK/qmcpack#2414]
**Describe the bug**
I am seeing a large variance for PP-LaO molecule for a Slater-only VMC. Orbitals have been generated with the gamess code.

// QMCPACK 3.8.0
qmca -q ev output
`series 0  -46.946821 +/- 0.001462   55.856201 +/- 0.618677   1.1898`

As a sanity check, I ran the same with QWalk, which reports the following
// QWalk mainline
`-46.94877313 +/- 0.0005 (sigma     2.292282256 )`

Qwalk therefore has a corresponding variance value of 5.2545579.

Each run uses a total of 3600 walkers, 300 blocks, 25 steps, timestep=0.4.

The traces of the total energy, kinetic, and potential are below

![Screen Shot 2020-04-29 at 10 54 06 AM](https://user-images.githubusercontent.com/1430804/80610887-e9321880-8a07-11ea-9dc5-43dc915757a4.png)
![Screen Shot 2020-04-29 at 10 54 27 AM](https://user-images.githubusercontent.com/1430804/80610892-e9caaf00-8a07-11ea-9e96-7edb59c1d740.png)
![Screen Shot 2020-04-29 at 10 54 57 AM](https://user-images.githubusercontent.com/1430804/80610893-e9caaf00-8a07-11ea-87cb-eb750fa9fe5e.png)

**To Reproduce**
1. Using qmcpack 3.8.0
2. Full inputs/outputs attached here:
[issue.tar.gz](https://github.com/QMCPACK/qmcpack/files/4552362/issue.tar.gz)

**Expected behavior**

**System:**
 - ORNL Cades
 - modules loaded:
```
  1) intel/18.0.0           2) openmpi/3.1.5           3) PE-intel/3.0           
 4) gcc/6.3.0              5) hdf5_parallel/1.10.3   6) fftw/3.3.5-pe3         
 7) cmake/3.11.0         8) boost/1.67.0-pe3      9) libxml2/2.9.9
```
 - other systems where this is reproducible: not yet tested

**Comment by jtkrogel** [comment]
It's really interesting that the energies agree, but the variances do not.  I don't have a good intuition for the type of bug that would allow for this.

**Comment by mcbennet** [comment]
I see agreement when choosing a different local channel in xml pp file.
