### ISSUE TITLE
Infinite/NaN energies on first step of VMC in supercell with extra electrons

### ISSUE THREAD

**Issue by jptowns** [QMCPACK/qmcpack#2421]
I have been attempting to do some grand canonical twist averaging calculations and I have encountered a possible bug.

I have a supercell of aluminum, and have run a series of VMC calculations with varying numbers of electrons: N-2, N-1, N+0, N+1, N+2, with N=24 (12u/12d) the charge balanced number of electrons. I noticed that for N+2 or more electrons, the LocalPotential and ElecElec energy were infinite on the first VMC block. All other calculations produced finite results of the expected magnitude. For the N+2 calculation the result depends on the compiler: Intel19 calls app_abort(), while GCC 7+ continues seemingly without a problem. When running with GCC, the subsequent blocks are finite and of the expected magnitudes.

First line of N-2 (11u/11d electrons) scalar.dat:
   index    LocalEnergy         LocalEnergy_sq      LocalPotential      Kinetic             IonIon              ElecElec            LocalECP            NonLocalECP         BlockWeight         BlockCPU            AcceptRatio         
`         0   -1.6619366818e+01    2.7791847593e+02   -2.2881651130e+01    6.2622843123e+00   -2.1568487421e+01   -5.2340399415e+00    1.0455739438e+00    2.8753022882e+00    1.0240000000e+04    6.7202931987e+00    7.8495649858e-01`

N-1 (12u/11d):
`         0   -1.6445765426e+01    2.7218465866e+02   -2.3032302289e+01    6.5865368633e+00   -2.1568487421e+01   -5.5930708454e+00    1.0871157989e+00    3.0421401784e+00    1.0240000000e+04    7.4715292208e+00    7.8334324049e-01`

N+0 (12u/12d):
`         0   -1.6185743809e+01    2.6385800677e+02   -2.3155722798e+01    6.9699789885e+00   -2.1568487421e+01   -5.8668893211e+00    1.0975314523e+00    3.1821224917e+00    1.0240000000e+04    7.6411641085e+00    7.8152669271e-01`

N+1 (13u/12d):
`         0   -1.5953712222e+01    2.5675952625e+02   -2.3305343888e+01    7.3516316656e+00   -2.1568487421e+01   -6.2148499354e+00    1.1795380897e+00    3.2984553788e+00    1.0240000000e+04    8.4838853025e+00    7.7954687500e-01`

N+2 (13u/13d):
`         0                 inf                 inf                 inf    7.7784588312e+00   -2.1568487421e+01                 inf    1.2256370560e+00    3.4079355818e+00    1.0240000000e+04    8.6526158307e+00    7.7671274038e-01`

Strangely, if I run N+2 but (14u/12d), the energies are finite, as expected:
`         0   -1.5718419652e+01    2.4925967681e+02   -2.3530887540e+01    7.8124678880e+00   -2.1568487421e+01   -6.5617277890e+00    1.2447276186e+00    3.3546000516e+00    1.0240000000e+04    8.8013343602e+00    7.7696063702e-01`

The result is the same whether one uses a tiled primitive cell, or an actual supercell. Interestingly, this problem does not occur in calculations on a primitive cell. 

**To Reproduce**
Affects Real/Complex, AoS/SoA, and full/mixed precision
 builds of develop branch ba556ca419b37e5503663524b18d339be31981a6

Minimal working example attached (without wave function but with QE inputs to generate it). As packaged, it should give Inf LocalEnergy, LocalPotential, and ElecElec energies on the first block of the scalar.dat.

**System:**
 - Local Ubuntu workstation w/ gcc9, and also various Intel-based HPC systems at Sandia using Intel19 and gcc7&gcc8.

[al_inf_mwe.zip](https://github.com/QMCPACK/qmcpack/files/4561957/al_inf_mwe.zip)

**Comment by prckent** [comment]
This is frustrating. Unfortunately there have long been murmured reports of issues around excitation handling, e.g. excitations favoring a certain spin work, but the opposite does not. Obviously some excitations do work. Perhaps there is a magic way of writing what you need for GC. I suspect a many-years old incorrect logic around supercell tiling and occupation changes. Hopefully with your report we'll be able to completely remedy this problem.
