### ISSUE TITLE
Build broken with Intel2019.1 and Clang10 due to Multi allocator.hpp due to missing destroy function

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2434]
**Describe the bug**

Build is broken with Clang10 and AFQMC enabled
https://cdash.qmcpack.org/CDash/viewBuildError.php?buildid=115274

e.g.
```
qmcpack/external_codes/boost_multi/multi/memory/allocator.hpp:62:34: error: no matching member function for call to 'destroy'

undefined                allocator_traits::destroy(ctor_, p);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
undefined
```

**To Reproduce**

Run latest develop with Clang10 and AFQMC enabled (implies an MPI build)
e.g. as configured at https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=115274

**Expected behavior**

QMCPACK should build

**System:**

sulfur, but should not matter

**Additional context**

(none)

**Comment by correaa** [comment]
Before touching the library I would like to see if the allocator for `shm::shm_ptr_with_raw_ptr(_dispatch?)` defines (or deletes) a `destroy`.

**Comment by prckent** [comment]
Thanks @correaa 

Intel2019.1 also fails

**Comment by mmorale3** [comment]
This should be fixed now.
