### ISSUE TITLE
AFQMC example failed to read hdf5 file

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2447]
**Describe the bug**
User reports failing at following an AFQMC example
https://groups.google.com/forum/#!topic/qmcpack/2gGphvbBPyk

**To Reproduce**
See google group for detail.

**Expected behavior**
Run through AFQMC example workflow.

1. We need to verify if the example itself can be run without issue. We also need to find a way to run this example nightly.
2. If there was no issue, identify how user ends up with this error.

**Comment by fdmalone** [comment]
Someone has to review my comments on the group?

Anyway, workflow tests exist but they need to be enabled I don't have access to set up the nightlies properly (see #1883 and #2133).

**Comment by fdmalone** [comment]
Yeah I can't comment on the google group until my membership is approved I guess. Could you ask him for the hdf5 file (it should be small) and how he compiled the code i.e. real or complex? My guess is the integrals are complex but the code was compiled real or visa versa. The error message is a little mysterious and it's something we hope to improve.

**Comment by mmorale3** [comment]
I mistakenly reported to the user directly a few days ago instead responding within the group.
The problem is he tried to use input for the complex build with an executable compiled for real input. The dataset dimensions don't agree and the code complains and abort. Of course, the lesson learned is that we need much better error reporting. The error should give guidance about checking consistency between build types and input.

**Comment by ye-luo** [comment]
The reported error is our hdf5 wrapper internal error and it does its job. A real dataset has dimension N while the corresponding complex dataset has dimension N+1. I don't feel it a good way to tell user that you are mixing workflow or code paths based on this inconsistency spotted in the file. Instead, an flag seems needed in the hdf5 file to indicate such file is generated with complex or real. Then AFQMC check it and issue precise error before loading data.

**Comment by prckent** [comment]
I made an issue with the specific problem in https://github.com/QMCPACK/qmcpack/issues/2448
