### ISSUE TITLE
Improvements to DMC branch cutoff scheme including size consistency

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#245]
In QMCPACK, a filter is applied on walkers based on their local energy during branching. The branch cutoff is determined currently by min(max(10 sigma, 50), 2.5/tau) where sigma is the standard deviation and tau is the time step. However, 2.5/tau is not a size consistent. A too small cutoff made equilibration longer like in PR #242 (a lot of details there). So a better scheme needs to be devised.

**Comment by prckent** [comment]
We need to implement explore the existing proposed schemes in the literature (Zen/Alfe) before cooking up anything new.

**Comment by ye-luo** [comment]
@prckent See my analysis in PR #242.

**Comment by prckent** [comment]
Ye - Close or keep open for discussion?

**Comment by ye-luo** [comment]
Close it for the moment. We can reopen it at any time when we need it.

**Comment by ye-luo** [comment]
DMC runs with the real code on the TiO2 Rutile using 35200 walkers. All the results are consistent with the old calculation.
1) Changes in the warmup do not affect the final results
2) Classic, YL, ZSGMA give consistent results.
3) YL with sigmaBound 3,4,5,7,10 tests shows the results are not biased beyond 7 sigma. In this particular system, ZSGMA is about 7 sigma.
4) Using a tight population control doesn't affect the results.
5) The mixed precision CPU code gives consistent results as the full precision code (single precision spline).
6) CPU GPU calculations agree well.

#qmca -q ev -e 25 dmc-supertwist111-supershift000-S18-new-*/*.s005.scalar.dat
#TiO2 Rutile S18 108 atom cell
#Note CPU MP uses ANL branch. All the rest uses github develop branch.
#CU Prec Branching Feedback                 LocalEnergy               Variance           ratio 
CPU SP OLD     1.0 TiO2-rutile-S18-dmc  -3262.898989 +/- 0.007574   87.780115 +/- 0.054410   0.0269
#meshfactor 0.8
CPU MP YL    1/tau TiO2-rutile-S18-dmc  -3262.905682 +/- 0.006244   87.715660 +/- 0.059709   0.0269
CPU MP YL      1.0 TiO2-rutile-S18-dmc  -3262.889029 +/- 0.006011   87.660951 +/- 0.041887   0.0269
CPU SP CLASS 1/tau TiO2-rutile-S18-dmc  -3262.899880 +/- 0.006907   87.721364 +/- 0.054412   0.0269
CPU SP CLASS   1.0 TiO2-rutile-S18-dmc  -3262.896749 +/- 0.006224   87.670419 +/- 0.048703   0.0269
GPU MP YL ANL  1.0 TiO2-rutile-S18-dmc  -3262.891878 +/- 0.007000   87.438653 +/- 0.041607   0.0268
GPU MP YL      1.0 TiO2-rutile-S18-dmc  -3262.900387 +/- 0.005240   87.655814 +/- 0.142573   0.0269
GPU MP ZSGMA   1.0 TiO2-rutile-S18-dmc  -3262.874007 +/- 0.004930   87.120772 +/- 0.035189   0.0267
GPU MP CLASS   1.0 TiO2-rutile-S18-dmc  -3262.883065 +/- 0.006734   87.729439 +/- 0.081014   0.0269

GPU MP YL sigma3   TiO2-rutile-S18-dmc  -3262.733609 +/- 0.005582   85.702387 +/- 0.037888   0.0263
GPU MP YL sigma4   TiO2-rutile-S18-dmc  -3262.854224 +/- 0.005878   86.734342 +/- 0.038728   0.0266
GPU MP YL sigma5   TiO2-rutile-S18-dmc  -3262.881342 +/- 0.006129   87.065635 +/- 0.047635   0.0267
GPU MP YL sigma7   TiO2-rutile-S18-dmc  -3262.890865 +/- 0.008826   87.347532 +/- 0.065310   0.0268
GPU MP YL sigma10  TiO2-rutile-S18-dmc  -3262.900387 +/- 0.005240   87.655814 +/- 0.142573   0.0269

#meshfactor 1.0
GPU MP YL      1.0 TiO2-rutile-S18-dmc  -3262.887364 +/- 0.005952   86.572489 +/- 0.040717   0.0265
GPU MP ZSGMA   1.0 TiO2-rutile-S18-dmc  -3262.891279 +/- 0.005313   86.412215 +/- 0.035357   0.0265
