### ISSUE TITLE
New input tag to switch implementations

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2451]
As mentioned in https://github.com/QMCPACK/qmcpack/pull/2423 we need a new an extensible input tag to switch execution between (say) cpu omp, gpuomp gpu omp+cuda ... . Hopefully not many will be needed, either for development or long term production. We will avoid compile time switches. Since this will be user visible we should discuss options before implementing.

**Comment by mmorale3** [comment]
Can you avoid compile time switches in real space?
It can be done in AFQMC, but it will take serious work.
