### ISSUE TITLE
AFQMC Hamiltonian checker is not run or tested automatically

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2462]
**Is your feature request related to a problem? Please describe.**

The new AFQMC Hamiltonian checker #2461  is not yet run automatically via ctest. As a result, it could break or be broken unknowingly.  

**Describe the solution you'd like**

Run the checker on one or more of the existing Hamiltonian files in the repo via ctest and appropriate lines in cmakelists.txt

**Describe alternatives you've considered**

There are no alternatives.

**Additional context**

We are try to regularly run all the developed scripts

**Comment by fdmalone** [comment]
I'll add this to the workflow tests.

**Comment by fdmalone** [comment]
Actually, probably just all the tests.
