### ISSUE TITLE
ion-ion deterministic test fails at large LR_dim_cutoff with opt-breakup LR handler

### ISSUE THREAD

**Issue by Hyeondeok-Shin** [QMCPACK/qmcpack#2472]
**Describe the bug**

 See also #2445.
 Tested with bug-deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1.
 
 ion-ion energy with opt-breakup seems very sensitive with CPU environment at large LR_dim_cutoff while ewald3d handler is giving identical references. This deterministic test reference was produced with the same QMCPACK binary compiled with intel18 but two separated computing nodes which have different CPU.

  |   | opt-Breakup |  
-- | -- | -- | --
LR_dim_cutoff | node1 | node2 | Diff
10 | 14.00330369 | 14.00330359 | 1E-07
20 | 14.00409717 | 14.00412958 | 3.241E-05
30 | 14.00273623 | 14.00273985 | 3.62E-06
40 | 14.00270328 | 14.0027064 | 3.12E-06

  |   | Ewald3d |  
-- | -- | -- | --
LR_dim_cutoff | node1 | node2 | Diff
10 | 13.9690802 | 13.9690802 | 0
20 | 14.00189436 | 14.00189436 | 0
30 | 14.00211652 | 14.00211652 | 0
40 | 14.00211812 | 14.00211812 | 0

Current tolerance for the deterministic test is 1E-6 so current opt-breakup is always giving failure in the test over 20 LR_dim_cutoff in different CPU. It seems to need to be investigated.
  
**To Reproduce**
1. release version or git commit hash being built
2. cmake command
3. full program/test invocation command
4. additional steps

Increase LR_dim_cutoff in /tests/solids/grapheneC_1x1_pp/det_qmc_short_z10.in.xml and run the ctest in different CPU.

**Expected behavior**

Provides different ion-ion references in different CPU.

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

Intel Xeon
   node 1 :  Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
   node 2 :  Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz

**Additional context**

**Comment by jtkrogel** [comment]
I think what you are observing here has significant overlap with issues noted earlier regarding the optimized breakup (e.g. #2105).

The optimized breakup does not converge under any circumstances for certain quasi-2D systems, which I think relates to intrinsic numerical instabilities (ill conditioned fitting for the "opt" part) that are exposed in the quasi-2D case.  

Sensitivity to slight variations in numeric representation/operations as is seen here is consistent with the ill conditionedness of the optimized breakup formulation for the quasi-2D problem class.

**Comment by jtkrogel** [comment]
As far as I know, we have no intention to "fix" the optimized breakup for these cases, but rather to use the direct Gaussian based Ewald method instead.

**Comment by Hyeondeok-Shin** [comment]
@jtkrogel Thanks. It means deterministic test for opt-breakup in the quasi-2D case is not available for now because of the numerical instability. So, the deterministic test is needed to use the other Ewald method.

**Comment by ye-luo** [comment]
@Hyeondeok-Shin close or there is remaining issue?

**Comment by Hyeondeok-Shin** [comment]
@ye-luo we can close. opt-breakup is still not working properly in certain quasi-2D system but can replace with the Ewald method.
