### ISSUE TITLE
Calculating Bader charges from QMC Electron Density

### ISSUE THREAD

**Issue by rambalachandran** [QMCPACK/qmcpack#248]
Does a feature currently exist to calculate Bader charges from the QMC electron density. This can be as minimal as identifying the zero flux surface around atoms (such as vtst tools employed on VASP CHGCAR - see http://theory.cm.utexas.edu/henkelman/code/bader/). Calculating such charges can be useful for comparison against DFT and also better understand defect chemistry

**Comment by jtkrogel** [comment]
Calculating Bader charges directly in QMC is hard, mostly because identifying the zero flux surface requires access to density derivatives, which we don't have good access to at the moment (density is calculated as a histogram).  

It is easier to get the density in pre-defined volumes, such as Voronoi/Wigner polyhedra around the atoms.  There are arguments for and against Voronoi or Bader as a "good" representation of atomic charges.  There are also other options, e.g. Mulliken.  I'm not sure which is "best" chemically speaking.

**Comment by prckent** [comment]
Just doing *something* from the QMC data would be beneficial. There is no "best" scheme here even in DFT, only equivalent comparisons. What is most practical and can also be calculated from a DFT or quantum-chemically derived density?

**Comment by jtkrogel** [comment]
Something that is higher resolution and accessible would be spherically averaged densities about each atom on radial histogram grids.  This could be extended to real spherical harmonics fairly easily.  

This way we can easily get the net charge in any atomic sphere.  If we augment with Voronoi polyhedra, I think this is the most we can easily do on the QMC side.

**Comment by rambalachandran** [comment]
vtst tools provide voronoi analysis on CHGCAR of vasp. Maybe setting up a simple diatomic molecule for comparison might be a good starting test case.

**Comment by jtkrogel** [comment]
This sounds reasonable.  Perhaps I should dedicate some time in the late summer or early fall to code up these estimators.

**Comment by jtkrogel** [comment]
Do we want to open a new issue(s) about spherically averaged or Voronoi charge densities (if this is indeed something we want to support)?

Overall I think this issue can be closed because we are unlikely to support Bader charge analysis (density gradients required) anytime soon.

**Comment by prckent** [comment]
Lets make an issue for spherical / Voronoi charge densities and close this issue. The former can be readily computed and are worth providing as an option since when postprocessing these quantities from a grid there is accuracy loss at the edge of the volumes.
