### ISSUE TITLE
Remove bind2nd use from code

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#2483]
std::bind2nd has been deprecated from C++11. Modernize.
https://github.com/QMCPACK/qmcpack/blob/9c657f06a63dd14cbffbe6b420a353d6ab0c8911/src/QMCHamiltonians/LatticeDeviationEstimator.cpp#L160

**Comment by ye-luo** [comment]
Assign the ticket to @Paul-St-Young since he introduced the code.
