### ISSUE TITLE
deterministic-unit_test_drivers consistently failing with GCC on sulfur

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2487]
**Describe the bug**

All GCC builds fail in deterministic-unit_test_drivers on sulfur (Xeon 6248R).
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_drivers&date=2020-05-27

MPI, No MPI, MKL and Blis+Netlib LAPACK, real and complex all fail. However builds with clang and Intel compilers are OK. The problem dates before 7 May and the beginning of the cdash history for this machine.

This may be related to #2271  because the tests fail in the VMC acceptance check
```
/scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/src/QMCDrivers/tests/test_vmc_driver.cpp:121: FAILED:
  REQUIRE( ar == Approx(1.0) )
with expansion:
  0.0 == Approx( 1.0 )
```

**To Reproduce**
1. release version or git commit hash being built
2. cmake command
3. full program/test invocation command
4. additional steps

Build latest develop. Reported on cdash.

**Expected behavior**
Test should pass.

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]
sulfur configured as per nightly script.

**Additional context**

**Comment by ye-luo** [comment]
It is all green now.
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_drivers&date=2020-06-18
