### ISSUE TITLE
All solid state spline runs fail with GCC built on sulfur

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2488]
**Describe the bug**

All the runs involving splines fail on sulfur with GCC9. Runs on the same machine with the same software stack using Clang or Intel pass. This suggests a memory corruption bug e.g. size mismatch in a library call  or a GCC only definition at play. All the deterministic, performance and stochastic ("nightly") tests eventually crash due to NaN or Inf energies. The DMC runs tend to crash in the DMC but problems are visible at the VMC stage.

e.g.
```
  SimpleFixedNodeBranch::finalize after a VMC block
    QMC counter        = 0
    time step          = 1
    reference energy   = -1.69932e+306
    reference variance = inf
```
( Copied from https://cdash.qmcpack.org/CDash/testDetails.php?test=8340780&build=118788 )

Note lots of HDF5 errors as well.

Real builds with the same libraries and compilers are OK.

**To Reproduce**
1. release version or git commit hash being built
2. cmake command
3. full program/test invocation command
4. additional steps

Nightly test configuration on sulfur.

**Expected behavior**

Tests should pass and energies should be sensible in magnitude.

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

sulfur configured as per the nightlies. RHEL8.

Since all the software is installed via spack, trying different combinations is straightforward.

**Additional context**

I tried a debug build and the problem disappeared, which I interpret as indicative of memory corruption or some other memory layout sensitive bug.

Sulfur is a standard Intel Xeon so we should not have any issues :-(

**Comment by ye-luo** [comment]
It seems not just complex build. All GCC9 builds on sulfur have problems
GCC9-MKL-Complex-Release https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=118787
GCC9-MKL-Release https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=118768
GCC9-NoMPI-MKL-Release https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=118677
GCC9-NoMPI-Release https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=118721
failed a lot of short runs.

For example, short-diamondC_1x1x1_pp-dmc_sdj-1-16
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-diamondC_1x1x1_pp-dmc_sdj-1-16&date=2020-05-27

Could you try GCC from the OS?

**Comment by prckent** [comment]
Yes, I got confused between the two issues I filed at the same time. Yes, they all fail. I'll edit the issue for clarity.

**Comment by prckent** [comment]
>Could you try GCC from the OS?

Excellent suggestion since I had only tried older and newer spack installed GCC, including v10.

This will need more followup to reach a definite conclusion, but builds using the Red Hat provided GCC "9.2.1" appear to work, while those built with the spack installed GCC 9.3.0 crash. Interesting.

**Comment by ye-luo** [comment]
A summary.
The issue was caused by GCC built by spack on Cascade Lake processor.
Building QMCPACK with default -march=native doesn't work.
After building with -march=broadwell, the issue goes away.

**Comment by prckent** [comment]
Example passing version of tests linked above:

https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1&date=2020-06-18

Workaround:
```
-DCMAKE_CXX_FLAGS='-march=broadwell -O3 -DNDEBUG -fomit-frame-pointer -ffast-math' -DCMAKE_C_FLAGS='-march=broadwell -O3 -DNDEBUG -fomit-frame-pointer -ffast-math'
```
