### ISSUE TITLE
Remaining tasks for AoS removal

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2506]
Remaining work for AoS removal:

- [x] Resolve #2504
- [x] Resolve #2508
- [x] Remove code in `MolecularOrbitals` directory 
- [ ] Test labeling
- [x] Test automation
- [x] Top-level CMake
- [x] Manual/README
- [x] Reduce references to SoA generally

Most of these will be done by @jtkrogel.  Some, like test automation and reducing SoA related naming in `src` will likely involve @prckent and @ye-luo.

**Comment by prckent** [comment]
It seems like the remaining cleanup tasks could be done by the next release - a recursive grep on AoS/SoA and removing from descriptions, readmes etc.

**Comment by prckent** [comment]
Manual update handled by #2756 

Readme previously updated.

**Comment by prckent** [comment]
I think we can claim this sufficiently completed. For any remaining aos issues, we should make a specific issue with clear title.
