### ISSUE TITLE
FDLR code and test needs removal

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2508]
The FDLR tests are currently failing, as expected with the removal of AoS:

https://cdash.qmcpack.org/CDash/testDetails.php?test=8433087&build=120036
https://cdash.qmcpack.org/CDash/testDetails.php?test=8433101&build=120036

The failures don't occur until VMC, indicating that some FDLR code is still lurking in the wavefunction files.  This code should be removed, a guard placed to warn against attempted FDLR input, and the tests removed.

**Comment by ye-luo** [comment]
The manual entry has not been removed.
