### ISSUE TITLE
VMCBATCH/DMCBATCH tests are failing

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2510]
The batched driver test,  short-diamondC_2x1x1_pp-vmcbatch_dmcbatch_4r_sdj-4-4 is failing.  However, this is a nightly test (and so should only check completion) and should pass.  

Somewhat confusingly, the test fails despite clearly reaching the end of the run (though not without some warnings):

```
branch cutoff = 1.1288546909e+01 1.6932820363e+01
WARNING Spawning walker outside of reserves, this ideally should never happend.
WARNING Spawning walker outside of reserves, this ideally should never happend.
WARNING Spawning walker outside of reserves, this ideally should never happend.
WARNING Spawning walker outside of reserves, this ideally should never happend.
WARNING Spawning walker outside of reserves, this ideally should never happend.
WARNING Spawning walker outside of reserves, this ideally should never happend.
  QMC Execution time = 2.9398e+01 secs
  Total Execution time = 3.1192e+01 secs

=========================================================
  A new xml input file : qmc_short_vmcbatch_dmcbatch_4r.s001.cont.xml
Stack timer profile
Timer         Inclusive_time  Exclusive_time  Calls       Time_per_call
Total           31.7085     0.8337              1      31.708492041
  DMCBatched    29.3979    29.3979              1      29.397855997
  Startup        0.5166     0.5166              1       0.516599178
  VMCBatched     0.9604     0.9604              1       0.960373878
```

See https://cdash.qmcpack.org/CDash/testDetails.php?test=8433167&build=120036

**Comment by PDoakORNL** [comment]
I'll look into this. The WARNING is confusing but the result of an important discussion on optimal DMC walker allocation myself and @ye-luo are having. It should appear in this test right now.  It should disappear from this test with my pending PR.

**Comment by ye-luo** [comment]
The strange thing here is the run completes but ctest acknowledges a failure. This doesn’t seem related to the warning.
