### ISSUE TITLE
AFQMC no more builds with CUDA 11.0

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2528]
**Describe the bug**
error in src/AFQMC/Numerics/detail/CUDA/cusparse_wrapper.hpp
cusparseDcsrmv, cusparseScsrmv, cusparseZcsrmv, cusparseCcsrmv
cusparseDcsrmm, cusparseScsrmm, cusparseZcsrmm, cusparseCcsrmm
cusparseDcsrmm2, cusparseScsrmm2
deprecated in cuda 10.1 and removed in cuda 11.
See https://docs.nvidia.com/cuda/archive/10.1/cusparse/index.html#csrmv
cusparse.h defines
```
#define CUSPARSE_VER_MAJOR 10
#define CUSPARSE_VER_MINOR 1
#define CUSPARSE_VER_PATCH 0
```
can be used. 

**To Reproduce**
1. develop
2. -DENABLE_CUDA=1 -DBUILD_AFQMC=1

**Expected behavior**
compile the code.

**System:**
 - ryzen-box

**Comment by prckent** [comment]
Good to notice that these interfaces were already deprecated.

Of course, we can't require a CUDA more recent than those on the big machines.

**Comment by ye-luo** [comment]
Some ifdef based on version will be needed to enable both old and new versions CUDA. We need both at this moment.

**Comment by ye-luo** [comment]
Ping @mmorale3

**Comment by prckent** [comment]
Which versions of CUDA 10.x do we need to support?

**Comment by prckent** [comment]
I am blocking updates on our RHEL boxes because of this issue.

**Comment by prckent** [comment]
Does clang@master work with CUDA 11 with warnings, or does it simply not work?

**Comment by ye-luo** [comment]
I think we could support all 10.x and 11.0. The difference between 10.x is tiny.
For AFQMC, we have to stay with 10.x.
For OpenMP offload, when you use Clang and CUDA10.2 or CUDA11, It is just warning.

**Comment by prckent** [comment]
11.1 is now available https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-general-new-features
