### ISSUE TITLE
ReadFileBuffer needs fix

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#253]
The unit test crashes in MPI when pp file is missing. This is introduced in #251
Error message cannot be printed correctly when a PP file is missing.
The reason is that is_open is not initialized and always set in open_file.
is_open must be initialized to false and set to false if an open failed.
open_file should check if a file is open or not before try to open anther file.

**Comment by ye-luo** [comment]
Please also avoid pseudopotentials/BFD/C.BFD.xml. This a bad file with nan in it. Though it doesn't really matter for this test, it is better to choose another one considering more tests may need this file.
See issue #43

**Comment by ye-luo** [comment]
Or just overwrite the bad one by a good one from the diamond tests.
@prckent can we just overwrite the bad one instead of waiting for issue #43.

**Comment by ye-luo** [comment]
APP_ABORT  message is not consistent with the actually routine.

**Comment by ye-luo** [comment]
Can get_file_length be a member function of ReadFileBuffer?
Can we move ReadFileBuffer to individual files instead of mixing with ECPComponentBuilder class?
Have it in src/Utilities and we can probably use it in other cases.

**Comment by markdewing** [comment]
The C.BFD.upf file as a 'nan' in it, but the C.BFD.xml file does not.

ReadFileBuffer could be moved to it's own file - something to do later, though.

I'm uncertain about get_file_length between OO design and functional design. 
  In OO design, the method operates on member variables (fin, length) and changes them.  I find this couples the function to the class more tightly and makes it harder to understand.
  In functional design, the function should be understandable in terms of inputs and outputs.  This function works well for this.
I can make it it a member function of the class, but I'll make it more functional (ie, it will not operate on the member variables) - that should keep it easier to understand w/o referencing the whole class.

**Comment by prckent** [comment]
How often do we need get_file_length or similar functionality?

**Comment by prckent** [comment]
Closed by #254
