### ISSUE TITLE
pw2qmcpack normalization failure

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2538]
I'm reporting this issue on behalf of Gopal Iyer at Brown:

"Dear Dr. Krogel,

I am a graduate student in Prof. Brenda Rubenstein's group. For one of my projects involving Pt surface modeling, I would like to convert orbital files generated from Quantum ESPRESSO (6.4) to QMCPACK (3.9.1)-readable formats to use as trial wave functions. For this, I am using pw2qmcpack.x. On running the command, the appropriate files seem to be produced: calc.ptcl.xml, calc.wfs.xml, and calc.pwscf.h5. At the end of the execution, however, I see the following message: 

```
The orbitals read from QE files are incorrect. Perhaps your QE orbital files are corrupted. 
```

For reference, I tried this with a few different QE inputs which used the PBE and revPBE functionals.
I went through both the XML files and compared them to the lab examples in the QMCPACK manual; nothing seems to be out of the ordinary. However, I am not sure whether these three files can be used safely for VMC optimization runs. I tried using these files for a test case but ended up with a bunch of segmentation faults. I don't know if this is because of corrupted orbital files or due to some other mistake in preparing the optimization  input XML file. 

I came across this page where you discuss a pw2qmcpack but was unable to understand much of it — I am a first-year student and quite new to QMCPACK and QMC methods in general.  I would appreciate any insights you can provide and am happy to share other information you may need. Thank you.

Best,
Gopal"

Files from the problem runs:
[share.zip](https://github.com/QMCPACK/qmcpack/files/4780567/share.zip)

The underlying issue appears to be a failure to properly normalize the orbitals.  The full message at the end of `p2q.log` is:
```
The wrong norm of k-point   1 band   1 , before collection, is    0.950531263508076
The orbitals read from QE files are incorrect. Perhaps your QE orbital files are corrupted.
```

Gopal is able to successfully run the oxygen example from the labs, so the issue is not general to each build/system.

**Comment by jtkrogel** [comment]
It looks like pw2qmcpack was run directly following a QE relax run, which may be the source of the problem.  If so, is there a way for `pw2qmcpack` to detect the prior run type (relax) and abort with an error message?

**Comment by ye-luo** [comment]
We have no pseudo potential support beyond normal conserving.

**Comment by jtkrogel** [comment]
So this is perhaps what needs the sentinel abort+message instead?

**Comment by ye-luo** [comment]
Yes. pw2qmcpack needs to be smarter to tell you potential source of problems.

**Comment by ye-luo** [comment]
Please also encourage him using google group.

**Comment by tiihonej** [comment]
I just ran into the same problem. Thankfully I found this thread, because I have to agree that pw2qmcpack could be more verbose about that fact that you'll really need to use NC pseudos.

**Comment by ye-luo** [comment]
Add a trap in pw2qmcpack
https://github.com/ye-luo/q-e/commit/e2b7e760e53c2397ed96470f277a3b123974c2c6
