### ISSUE TITLE
QMC calculation abnormally stopped by segmentation fault during qmc run

### ISSUE THREAD

**Issue by ichibha** [QMCPACK/qmcpack#2542]
System: Theta
QMC version: v3.9.2
Binary: /soft/applications/qmcpack/current-develop/build_KNL_Intel_cplx_MP/bin/qmcpack 

Dear all, 
I have encountered a segmentation fault error during qmc running. 
I wonder what increases the memory requirement during qmc and how to avoid this error. 

Please kindly find the attached input/output files, where qmc.output, qmc.error, and qmc.cobaltlog are the standard output of qmcpack, the error output of qmcpack, and the log of job submission system. 

Best Regards,
Tomohiro
[qmc_inout.zip](https://github.com/QMCPACK/qmcpack/files/4793951/qmc_inout.zip)

**Comment by ye-luo** [comment]
All the energy are positive. Something, probably WF, went extremely wrong.
