### ISSUE TITLE
Adjust performance tests needed

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2545]
We have performance tests with and without delayed update.
Now delayed update is turned on by default. There is no need to keep both.
Since we have new batched driver, we can change the set without explicit delayed update to serve batched driver.

**Comment by prckent** [comment]
Unless we are squeezed for time, I prefer fixing the non-delayed performance tests so that they use the sm-1 algorithm. i.e. put delay=1 in those inputs. Then the benefit of the delayed update will be readily visible.

**Comment by ye-luo** [comment]
OK. Let us fix the delay=1 and add new tests for the batched code. Please avoid running large problem with delay=1 (>=a128) in the nightlies.
