### ISSUE TITLE
QMCPACK 3.9.1 AFQMC Limited Capability in the qmca Utility

### ISSUE THREAD

**Issue by djstaros** [QMCPACK/qmcpack#2546]
While using the qmca utility of QMCPACK 3.9.1 to analyze AFQMC output data from the 01-neon_atom example, I found limited capability in extracting averages of most values reported in qmc.s000.scalar.dat. The only flag which worked with this file was "el", which outputs the average energy and variance of the "EnergyEstim__nume_real" column of the scalar.dat file. However, the other columns such as block, time, nWalkers, weight, EnergyEstim__nume_imag, etc. have no flags listed when I perform the command "qmca -o", which lists all currently implemented flags.

Ideally, the addition of more AFQMC-relevant flags to the qmca utility code would streamline evaluation of AFQMC output data in QMCPACK. This could be done either by changing the keywords generated within the AFQMC scalar.dat file (such as changing "weight" to "Weight" since the flag "w" already recognizes the capitalized "Weight" keyword in DMC output files) or addition of more flags to qmca source code for recognition of AFQMC-specific value keywords.

If this issue is already being addressed, I would greatly appreciate being redirected to the relevant resources. I am attaching a screenshot of a text file where I manually list reported values in the 01-neon_atom qmc.s000.scalar.dat file and existing flags.

<img width="810" alt="Screen Shot 2020-06-18 at 12 20 54 PM" src="https://user-images.githubusercontent.com/63654922/85046257-2a1ff100-b15e-11ea-9a1e-18d96b77b4b3.png">

**Comment by jtkrogel** [comment]
What do you get, e.g. with:
```
qmca -q PseudoEloc -e0 qmc.s000.scalar.dat
```

**Comment by jtkrogel** [comment]
@fdmalone Do you have any recommendations for good abbreviations for these quantities?  Should some of them be combined into composite quantities (e.g. `EnergyEstim__*`)?

**Comment by djstaros** [comment]
@jtkrogel When I try your PseudoEloc command, I get the output 
"QMCA error:
  PseudoEloc is not a valid quantity
  please choose quantities from the following list:"
and proceeds to print the list obtainable with the command "qmca -o".

**Comment by jtkrogel** [comment]
Thanks.  What about `qmca -e 0 qmc.s000.scalar.dat`?

**Comment by djstaros** [comment]
I had not tried the qmca command without a flag before, but I get the following. Very insightful! Thanks for the suggestion.

<img width="536" alt="Screen Shot 2020-06-18 at 2 34 23 PM" src="https://user-images.githubusercontent.com/63654922/85058918-cf43c500-b170-11ea-816d-95391271ea5c.png">

**Comment by fdmalone** [comment]
We need to do a better job of describing the output for sure. EnergyEstim__* give the real/imaginary components of the numerator / denominator of the energy estimator. For phaseless AFQMC the only relevant quantity is EnergyEstim__nume_real.

I would lean towards us converging toward the DMC scalar column output names, and leave free projection as a special case (which can't currently be dealt with in qmca).

LogOvlpFactor and PseudoEloc for example are mostly useful for diagnostic purposes, their mean values aren't particularly meaningful. But they could be given flags like lo and pe?

**Comment by fdmalone** [comment]
Similarly the block and time columns are the simulation block (block= steps*substeps iterations) and time is the imaginary time elapsed in the simulation. These average values are also not useful.

@jtkrogel can qmca just take in the column name as an argument. I wouldn't want to pollute it further with helper flags for these quantities.

**Comment by jtkrogel** [comment]
I can update it to accept full column names as long as they are present in the file.  I'll also add the "lo" and "pe" flags as you suggest.

**Comment by jtkrogel** [comment]
This is basically resolved.
