### ISSUE TITLE
diamondC_1x1x1_pp-opt_sdj-1-16 crashes on GPU with Intel compilers

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#257]
https://cdash.qmcpack.org/CDash/testDetails.php?test=485811&build=7444

This is a reliable failure with Intel+CUDA, after the VMC and near the start of the optimization. GCC+CUDA is OK. This suggests an initialization or memory handling problem surfaced by the different compiler.

**Comment by ye-luo** [comment]
This test works on both Rhea and Cooley GPU with Intel 15 + CUDA 7.5.
An investigation right on Oxygen is needed to understand the failure.

**Comment by ye-luo** [comment]
1. This only appeared on one machine.
2. The compiler and library are more than 2 years old. 
3. Not the major production GNU+CUDA combination
For the above reason, this is closed unless the problem reappears.
