### ISSUE TITLE
Restart-8-2 failing due to numerical tolerance issues

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#258]
https://cdash.qmcpack.org/CDash/testDetails.php?test=485831&build=7444

> Test output
> 2c2
> < 1.1318030733e+01 -2.9875893977e+00 -1.2775667611e+01 -6.5545628484e+00
> --- 
> 1.1318030733e+01 -2.9875893981e+00 -1.2775667611e+01 -6.5545628487e+00
>
It would help to have a more verbose error on this failure. The VMC restart is clearly not exact in this case.

**Comment by ye-luo** [comment]
Such errors appear sometimes on mixed precision codes both CPU and GPU.
The difference is mainly due to single precision round error.
The checking script needs to be a bit more tolerant.

**Comment by prckent** [comment]
Good that this is a tolerance problem. This test has to be nearly 100% reliable since it is the kind of test that could become part of our CI tests or will be used by non-specialists.
