### ISSUE TITLE
How to get stabler wave-functions in the orbitals optimization?

### ISSUE THREAD

**Issue by ichibha** [QMCPACK/qmcpack#2594]
Dear all,

I have a difficulty in the orbitals optimization, 
with which I cannot get stabler trial wave-functions as shown below.
I am glad if someone teach me some tips for the orbitals optimization. 
My calculation files are uploaded here: 

oxygen molecule
https://www.dropbox.com/sh/plzdypmmkz84ok0/AABS_3dKgG7IpGaekFU1ovZfa?dl=0

cobalt atom
https://www.dropbox.com/sh/2igku8ymecjjxp7/AACeXr0Hu277gEy7r0pfXKs1a?dl=0

where input file is gamess.qmc.in-wfj.xml and output file is gamess.qmc.out.gz. 
The input is prepared following ${QMCPACK_ROOT}/tests/molecules/H2_ae.

-----------------------------------------
oxygen molecule
                            LocalEnergy               Variance           ratio 
gamess  series 0  -37.761539 +/- 0.010623   3.523312 +/- 0.024484   0.0933 
gamess  series 1  -31.488787 +/- 0.009038   2.661083 +/- 0.023699   0.0845 
gamess  series 2  -31.507389 +/- 0.009514   2.597895 +/- 0.021946   0.0825 
gamess  series 3  -31.502565 +/- 0.006999   2.620919 +/- 0.026074   0.0832 
gamess  series 4  -31.490435 +/- 0.008847   4.164941 +/- 0.069352   0.1323 
gamess  series 5  -31.437975 +/- 0.011712   7.610208 +/- 0.268036   0.2421 
gamess  series 6  -31.426453 +/- 0.014157   10.372297 +/- 0.228305   0.3300 
gamess  series 7  -31.247987 +/- 0.017315   19.423181 +/- 0.567872   0.6216 
gamess  series 8  -30.787879 +/- 0.025601   43.346480 +/- 1.260965   1.4079 
gamess  series 9  -30.023784 +/- 0.033297   83.000714 +/- 1.744286   2.7645 
gamess  series 10  -28.621945 +/- 0.025957   185.695743 +/- 2.560586   6.4879 
-----------------------------------------
cobalt atom
                            LocalEnergy               Variance           ratio 
gamess  series 0  -57.849832 +/- 0.138662   90.250679 +/- 0.990082   1.5601 
gamess  series 1  -58.026385 +/- 0.126232   94.782600 +/- 1.503642   1.6334 
gamess  series 2  -57.548486 +/- 0.132433   182.708048 +/- 8.503518   3.1749 
gamess  series 3  -55.727145 +/- 0.207499   508.986537 +/- 33.799687   9.1335 
gamess  series 4  40.338403 +/- 5.996485   17864.179573 +/- 1671.622364   442.8579 
gamess  series 5  63.826622 +/- 7.220942   21367.724122 +/- 1540.725147   334.7776 
gamess  series 6  133.652886 +/- 5.551984   28531.929383 +/- 1199.899573   213.4778 
gamess  series 7  165.763908 +/- 14.836433   27989.367807 +/- 2650.330782   168.8508 
gamess  series 8  149.270805 +/- 3.108194   23699.878289 +/- 1123.099092   158.7710 
gamess  series 9  156.223189 +/- 10.245479   20506.473527 +/- 955.131969   131.2640 
gamess  series 10  136.735812 +/- 2.852141   17763.991403 +/- 349.351258   129.9147 
-----------------------------------------

Best Regards,
Tomohiro

**Comment by prckent** [comment]
Tomohiro - Unfortunantely I have never used this feature. However the first and second optimization cycle for oxygen look very suspicious, with a large increase in energy. This suggests an overly large step size in the optimizer given the number of samples and quality of starting point. I suggest trying to make the best possible jastrow before attempting to optimize the orbitals, and then using very conservative settings for orbital optimization. Hopefully someone who has experience can comment.

**Comment by ichibha** [comment]
Dear Paul,

Thank you for the comment. 
"<parameter name="targetExcited"> yes </parameter>" caused the problem. 
After removing it, the optimizer works.
