### ISSUE TITLE
-lpencv_hdf can not find link  error in opencv 4.1.0 and 4.3.0

### ISSUE THREAD

**Issue by gansm255** [QMCPACK/qmcpack#2595]
Hi,
I am to cross compile opencv4.1.0 to aarch64 on linux. under cygwin build installed in windows 10.
i copied hdf5 Pl1.8 to contrib package and i could compile hdf5 and lihdft.a library made.
when i compile a simple application i get hdf.a can not find error.
i searched install/lib and found no libhdf.a file.
I am new to opencv/make. i am struck for the last few weeks.
Please guide me the steps i have to do to get this library. Earlier i could fix freetype, hdf library issues.

**Comment by markdewing** [comment]
I think you might have opened this issue in the wrong repository.  This issue you describe sounds like an OpenCV issue, which QMCPACK does not use.
Your cross-compile environment also sounds complicated - you might try something simpler first.

**Comment by gansm255** [comment]
Sorry for inappropriate opening of the issue here...
Regards
