### ISSUE TITLE
wavefunction deterministic unit test is broken

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2600]
**Describe the bug**

SEGV in test_TrialWaveFunction_He.cpp in deterministic-unit_test_wavefunction with most compilers and builds (75% failure rate, https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_wavefunction&date=2020-07-24 )

e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=9113820&build=129979 shows failure in sulfur (Intel Xeon) and with Intel compiler

Since this missed our CI we can assume some illegal pointer, memory, C++ (etc.) usage that doesn't show on all platforms or all compilers.

**To Reproduce**

Run test on current develop.

**Expected behavior**

Test passes

**System:**

All of them

**Additional context**

**Comment by PDoakORNL** [comment]
I have seen this in my DMCBatched mpi population branch and was chasing it. I couldn't avoid it in older clang but it didn't occur with gcc9. I assumed some change I made caused it perhaps by moving the wrong segment into a buffer overrun in the existing code.  It was much more consistent in debug as release doesn't care about undefined access behavior.

I'm about to go back to that section of the old PR so I will share any insight, I will share any solid information with @markdewing.
