### ISSUE TITLE
wavefunction unit test failure with complex

### ISSUE THREAD

**Issue by camelto2** [QMCPACK/qmcpack#2623]
**Describe the bug**
In the process of working on a converter from DIRAC to qmcpack to do molecular calculations with spin-orbit, I noticed that the current status of develop fails a unit test with my build scripts. 

In particular, the wavefunction unit test hangs indefinitely. Running ctest with verbose output, I see the following
19:   All the species have the same mass 3
19: 
19:    Jastrow
19:    -------
19:     Name: Jee   Type: Two-Body   Function: pade
19: 
19:     Radial function for species: u - d
19: 
19: failbit detected when reading type (type_info::name) St7complexIdE, value (1,0)
19: failbit detected when reading type (type_info::name) St7complexIdE, value (6.95319e-310,0)
19: failbit detected when reading type (type_info::name) St7complexIdE, value (6.95319e-310,0)
19: failbit detected when reading type (type_info::name) St7complexIdE, value (6.95319e-310,0)
19: failbit detected when reading type (type_info::name) St7complexIdE, value (6.95319e-310,0)
19: failbit detected when reading type (type_info::name) St7complexIdE, value (6.95319e-310,0)
19: failbit detected when reading type (type_info::name) St7complexIdE, value (6.95319e-310,0)
...

This continues to print until killing the ctest. I am using intel 19.0.5, cmake 3.12.2, and also see the same for a clang9 build. I did a git bisect to track down when this failure started, which was commit a5c254689214977713fd84e8b4b1a8d2d9313b61 This commit supposedly allows open boundary conditions to work with a complex build and not fail. However, the unit test for me is definitely failing. So I'm not sure what the CI is doing such that it doesn't run into this failbit error. This commit was part of PR #2582. 

In order to get a working converter for DIRAC to qmcpack for spin orbit, I will need LCAO with complex build in open boundary conditions working...which is supposedly what commit a5c254689214977713fd84e8b4b1a8d2d9313b61 allowed for

**To Reproduce**
1. current develop
2. cmake  -DPython3_EXECUTABLE=$SEMS_PYTHON_ROOT/bin/python3 \
       -DCMAKE_CXX_FLAGS="-march=native -O3 --std=c++11" \
       -DCMAKE_C_FLAGS="-march=native -O3" \
       -DQMC_EXTRA_LIBS="" \
       -DQMC_COMPLEX=1 \
       -DBUILD_AFQMC=0 \
       -DENABLE_PHDF5=0 \
        ..
3. ctest -R unit -R wavefunction -VV
4. intel 19.0.5, cmake 3.12.2

**Expected behavior**

**System:**
 my workstation
  1) sems-env                 3) sems-intel/19.0.5        5) sems-hdf5/1.10.4/base    7) sems-boost/1.63.0/base   9) sems-cmake/3.12.2
  2) sems-gcc/6.1.0           4) sems-openmpi/1.10.1      6) sems-python/3.5.2        8) sems-zlib/1.2.8/base

**Additional context**

**Comment by camelto2** [comment]
Looks like the CI at time of commit #2582 only has alcf-gnu-mkl18 for a cpu only build

I just recompiled with gcc9.2.0, and the wavefunction unit test passes. So intel and clang builds fail with this failbit thing above, whereas gnu compilers pass without this error

**Comment by prckent** [comment]
The failbit error is printed by putContent() in libxmldefs on getting a stream error (end of file etc.). Assuming no issues with compilers etc., something is wrong with the  xml reading or we have an issue with uninitialized data (etc.). The unit test passes reliably in all our nightlies https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_wavefunction&date=2020-08-07 . Only legacy CUDA fails, which is sadly expected.

**Comment by ye-luo** [comment]
Seems fixed.
