### ISSUE TITLE
Mixed-precision deterministic test failure for kinetic energy in PBC Gaussian diamond.  

### ISSUE THREAD

**Issue by Hyeondeok-Shin** [QMCPACK/qmcpack#2630]
**Describe the bug**

Currently deterministic test is failing on PBE Gaussian diamond for mixed precision build. 
Large tolerance in the mixed precision build is not surprising, but the tolerance in kinetic energy is larger than the usual for PW diamond deterministic test (1 x 10^-5 ~ 1 x 10 ^-4). Following table shows the kinetic energy for the deterministic test performed in the worksation, bora, and sulfur. 

  | diamond 1x1x1 | diamond 2x1x1
-- | -- | --
Intel18-real | 10.15418453 | 15.7691441
intel18-cplx | 10.15418743 | 15.76914182
gcc620-real | 10.15404636 | 15.76843729
Clang7-real | 10.1544455 | 15.76813687
Bora-intel18-real | 10.15427192 | 15.76850891
Bora-intel18-cplx | 10.15427554 | 15.76851236
Sulfur-Clang10 | 10.15441212 | 15.76880614
Sulfur-Intel19-real | 10.15424951 | 15.76873393
Sulfur-Intel19-cplx | 10.15425023 | 15.76873023
  |   |  
Avg. | 10.15425813 | 15.76868352
Max tolerance | 0.000211767 | 0.000546647

Current the maximum deviation from the average is ~ 5 x 10^-4 for 2x1x1 which is 5x larger than the same diamond 2x1x1 for PW.
I'm not sure if it is bug or not because kinetic energy tolerance is usually larger than the other scalars but I'd like to hear comments to make sure if it is normal in PBC Gaussian. 

**To Reproduce**
1. QMCPACK 3.9.2
2. cmake -DQMC_MIXED_PRECISION=1
3. ctest -R deterministic-diamondC_1x1x1_pp-vmc_gaussian_sdj;  ctest -R deterministic-diamondC_2x1x1_pp-vmc_gaussian_sdj

**Expected behavior**
Providing similar scale of the tolerance for PW. (1 x 10^-5 ~ 1 x 10 ^-4)

**System:**
 - bora, sulfur
 - workstation

**Comment by prckent** [comment]
I suggest first enlarging the current error bars to get the deterministic tests passing in mixed precision.  Then investigate further. e.g. Is the larger sensitivity here due to the choice of starting electron configuration? Are any of the basis functions gridded/interpolated resulting in greater sensitivity? (Perhaps increase the grid fineness etc.)

**Comment by ye-luo** [comment]
@Hyeondeok-Shin close?
