### ISSUE TITLE
Clarify handling of LogValue

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#2643]
The evaluateLog function returns the log of the wavefunction, and also sets LogValue in WaveFunctionComponent.h

In #1860 , the batched interfaces were introduced, and routines like flex_evaluateLog and mw_evaluateLog no longer return the log (or a vector of logs). They only depend on LogValue being set.

While working on the optimizer, I ran across an issue with ExampleHeComponent.   The evaluateLog function only returns the log value, but did not set the LogValue member.   (The issue was fixed by setting LogValue).

What should be the future of these values that change during evaluation (LogValue, PhaseValue, dLogPsi, etc)?  Should they remain part of WaveFunctionComponent?  Or should they be passed in separately?

It looks like WaveFunctionComponent uses a complex value for LogValue, and TrialWaveFunction keeps separate real values for LogValue and PhaseValue.

The handling of LogValue can be different between TrialWaveFunction (flex_evaluateLog) and WaveFunctionComponent (mw_evaluateLog).

My thought is that a vector of LogValueType could be passed into mw_evaluateLog? (And we could keep TrialWaveFunction the same for now)

  virtual void mw_evaluateLog(const RefVector<WaveFunctionComponent>& WFC_list,
                              const RefVector<ParticleSet>& P_list,
                              const RefVector<ParticleSet::ParticleGradient_t>& G_list,
                              const RefVector<ParticleSet::ParticleLaplacian_t>& L_list
                              std::vector<LogValueType>& wf_value_list)
  {
#pragma omp parallel for
    for (int iw = 0; iw < WFC_list.size(); iw++)
      wf_value_list[iw] = WFC_list[iw].get().evaluateLog(P_list[iw], G_list[iw], L_list[iw]);
  }
```

**Comment by ye-luo** [comment]
> What should be the future of these values that change during evaluation (LogValue, PhaseValue, dLogPsi, etc)? Should they remain part of WaveFunctionComponent? Or should they be passed in separately?

They should be part of TWF/WFC and updated during an evaluation and can be queried later.

> It looks like WaveFunctionComponent uses a complex value for LogValue, and TrialWaveFunction keeps separate real values for LogValue and PhaseValue.

TWF keeps LogValue and PhaseValue separate is more for compatible with current drivers.

> My thought is that a vector of LogValueType could be passed into mw_evaluateLog? (And we could keep TrialWaveFunction the same for now)

Can we just call TWF::getLogPsi() and TWF::getPhase()? If the API in WFC is missing, we can add one.

I prefer the opposite direction, even G and L can removed from the API and should be kept internal to WFC and query when needed. Pasing G and L and relying on `+=` adds additional dependency between WFC objects and make concurrent computation even harder. In most cases, when we call evaluateLog, we don't need G and L and the lightweight flex_evaluateGL in designed for that.

**Comment by PDoakORNL** [comment]
Ideally I don't think that TWF/WFC should be used as state caches at all. If the log value is required to compute something you should need to pass the LogValue to call it. 

However I can see @ye-luo's point as well and he has been doing most of this work. I do think when the dust settles it may be worth looking at pulling the state data out in a way that removes unnecessary state machinery and doesn't create unnecessary data dependency.
