### ISSUE TITLE
ENABLE_TIMERS=ON on by default

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2663]
Our timer codes actually have near zero overhead if the level is set to none.
So I'd like to build with timers and set the level to none by default.
-DENABLE_TIMERS=OFF will be allowed for a while.
If we found it never needed, this build option will be removed.

Any comments?

**Comment by prckent** [comment]
One less build option, so I am in favor by default. Do you have data for a small system such as a water molecule on cpu? The timers should be benign with level=none, but are they in practice?
