### ISSUE TITLE
Offload code should print GPU info

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2664]
**Is your feature request related to a problem? Please describe.**

When compiled for offloading to accelerators there is very little information printed about which accelerators are available, what type they are, or even that the run is accelerated. The output file is therefore an incomplete record. We do print the MPI task and CPU OpenMP threading setup.

**Describe the solution you'd like**

Print the device count and ideally the types of devices.

**Describe alternatives you've considered**

None

**Additional context**

I could not find a vendor independent way to get more than the device count, but perhaps I missed an API call.

**Comment by ye-luo** [comment]
This is how the header printout looks like now
```
  Built without MPI. Running in serial or with OMP threading only.

  Total number of MPI ranks = 1
  Number of MPI groups      = 1
  MPI group ID              = 0
  Number of ranks in group  = 1
  MPI ranks per node        = 1
  Accelerators per node     = 1
  OMP 1st level threads     = 1
  OMP nested threading disabled or only 1 thread on the 2nd level

  Precision used in this calculation, see definitions in the manual:
  Base precision      = double
  Full precision      = double

  OpenMP target offload to accelerators enabled

  Current timer level is coarse

  Input XML = det_qmc_short.in.xml

  Project = det_qmc_short
  date    = 2020-09-02 14:18:19 CDT
  host    = bora

  hamiltonian has MPC. Will read density if it is found.
```

```
  Accelerators per node     = 1
  OpenMP target offload to accelerators enabled
```
are relevant to this feature request. If we cannot distribute GPUs equally to the MPI ranks in a node, extra message will be printed.

**Comment by prckent** [comment]
This is an improvement.
