### ISSUE TITLE
pyscf-diamond_1x1x1_pp_Bspline-diamondC_1x1x1_pp-vmc_gaussian-bspline_sdj-1-16 is broken

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2669]
**Describe the bug**

Broken on both sulfur and nitrogen

https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=pyscf-diamond_1x1x1_pp_Bspline-diamondC_1x1x1_pp-vmc_gaussian-bspline_sdj-1-16&date=2020-09-02

Note that since

**To Reproduce**
Run the test from latest develop, e.g. ctest -R pyscf-diamond

**Expected behavior**
Passes

**System:**

sulfur and nitrogen

**Additional context**

The software stack on nitrogen and sulfur has been reinstalled several times recently, so a good initial check is to reproduce this elsewhere. Since QMCPACK aborts on startup this can be done on a laptop.

**Comment by anbenali** [comment]
This is a bspline test. No idea how it works but I can take a look

**Comment by Hyeondeok-Shin** [comment]
It seems bspline h5 is not generated because pyscf run in nitrogen and sulfur is not converged since this week. 
As Seen in https://cdash.qmcpack.org/CDash/testDetails.php?test=9651854&build=138391, pyscf run test is giving pass signal but output is not converging at all. 
Due to the same reason, currently pyscf runs for AFQMC is not converging. (See https://cdash.qmcpack.org/CDash/testDetails.php?test=9651810&build=138391)

So, it seems problem is in the pyscf in sulfur and nitrogen, not QMCPACK.

**Comment by prckent** [comment]
Unfortunately this does indeed appear to be a PySCF problem. 

I noticed in https://cdash.qmcpack.org/CDash/testDetails.php?test=9665503&build=138634 that "BLAS" is complaining about bad memory unallocations.

We only build PySCF for GCC10 Open MPI MKL variants. This should be a boring combination but potentially is susceptible to perturbations in the spack magic. Unfortunately we do not build with Intel, which should also be boring and give us more information. However this would require configuring/building/maintaining an entirely separate stack of software. I lack the bandwidth to do so. Note that QE runs fine with the GCC10 stack, and PySCF used to work with older software versions. It seems most likely that underlying bugs in PySCF or in the combinations/configurations of packages used have been exposed.

Which version of PySCF do you two have installed? Our nightlies have 1.7.1 hardwired. 1.7.4 is the latest release. If you have any experience, is the installation any different? Which support libraries are you using?

Any other ideas for things to try?

**Comment by prckent** [comment]
In case relevant, we are using python 3.8.5 currently. 3.8 is needed to get llvm@master to build.

**Comment by Hyeondeok-Shin** [comment]
I'm using Pyscf 1.7.4 with GCC7.3 in python 3.7.3(numpy 1.16.2 , scipy 1.2.1) and it is working normally. I'm trying to reproduce this abnormal situation.

**Comment by ye-luo** [comment]
Seems all passing https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=pyscf-diamond_1x1x1_pp_Bspline-diamondC_1x1x1_pp-vmc_gaussian-bspline_sdj-1-16&date=2021-03-20

**Comment by prckent** [comment]
This was a PySCF / python dependencies and cmake dependencies issue. Indeed fixed now.
