### ISSUE TITLE
Reported inconsistency before and after DMC restart/checkpoint 

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#267]
From Dario to Anouar, restarting behaviour in #2. Not clear what quantity was plotted. It seems not energy (usually negative).

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/24738499/26524872/80c51bb4-4309-11e7-9fb5-6aa37933ad02.png)

==================================

I tried a DMC run on diamondC_2x1x1_pp with sdj.
1 VMC block (not plotted)
1 DMC block
--restart
1 DMC block
--restart
1 DMC block

The restart seems smooth.

![image](https://user-images.githubusercontent.com/1454251/27203947-e13275c6-51ed-11e7-9659-07c5c1039628.png)

**Comment by ye-luo** [comment]
@prckent I need the exact input files to reproduce the pathology.

**Comment by prckent** [comment]
@ye-luo Which additional checks do you think are needed? Or can we close this?

**Comment by ye-luo** [comment]
Everything is good. Nothing extra needed.
