### ISSUE TITLE
Warning printing to stdout instead of stderr

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2712]
**Is your feature request related to a problem? Please describe.**
Currently our warnings are printed to stderr. Since it doesn't stop the code, it is very hard to figure out where warnings comes out if it is on a different file.
I think stderr should be used by non recoverable errors which also stop the code.
Any recoverable error should be print as a warning to stdout.

So overall, print warning to stdout instead of stderr.

**Comment by prckent** [comment]
Good point. Agreed.

**Comment by PDoakORNL** [comment]
I think this is non controversial and is rather a big deal for interpreting output from bugged runs reported by users. Who can work on this?
