### ISSUE TITLE
Pseudopotential calculation from pyscf

### ISSUE THREAD

**Issue by iliya-s** [QMCPACK/qmcpack#2714]
Hi, I am using qmcpack for the first time and am having trouble doing a calculation with pseudopotentials. I'm using the given helper functions to dump a .h5 file from pyscf, and then using the convert4qmc program to dump all the .XML files for the calculation. However, when I run qmcpack it tells me I am missing a 'title'.qmcpp.xml file for my system. I've given the manual and examples a good look through and I cannot figure out how to create this file from pyscf. Any advice would be greatly appreciated.

Please let me know if there is any more information needed from me, 

Iliya

**Comment by camelto2** [comment]
Hi Iliya, 

The convert4qmc doesn't actually know anything about the pseudopotential xml file, so you will need to modify the qmc input xml file to have the correct name for whatever pseudopotential xml file you have. Since you are running with pyscf, there are a lot of pseudopotentials built in directly to pyscf, so you need the corresponding qmcpack xml. Which pseudopotential did you run with in pyscf?

**Comment by iliya-s** [comment]
I appreciate the quick response,

Where does one get the pseudopotential XML file though? I was using the bfd pseudopotential and basis set which are a part of pyscf. Ideally, though, I'd like to be able to parse any pseudopotential or basis in pyscf and generate the pseudopotential XML file necessary to perform the calculation.

**Comment by camelto2** [comment]
For BFD potentials, the main way to obtain the BFD xml files is to convert them using ppconvert, packaged with QMCPACK. You can find some information on how to use ppconvert in the manual. Depending on which system you are studying, there may be BFD files already in the source code in the test directories. For example, in tests/pseudopotentials_for_tests there are BFD xml files for C, Fe, Na, Ni, and O. 

For reference, you can find a number of pseudopotentials in qmcpack format at http://pseudopotentiallibrary.org, which include more recent pseudopotentials than BFD which are explicitly correlated and you can just download the basis sets and pseudopotentials to use directly in pyscf (pyscf uses nwchem format, so just download those). Unfortunately, we do not have the BFD pseudopotentials on pseudpotentiallibrary.org at the moment.

**Comment by iliya-s** [comment]
Okay I see, thanks, that all should work for my purposes then.

I saw the part on ppconvert, but it didn't seem to be made for use with pyscf. So just so I understand, you can't obtain the pseudopotential XML file from the 'title'.h5 that is dumped from pyscf.

As long as I have some examples to make a qmcpp.xml file I think I should good. Thanks again for the help!

**Comment by camelto2** [comment]
Right, at the moment the h5 file that is produced from pyscf essentially contains only the orbital and basis set information, as well as kpoints if you're using PBC. The pseudopotential read by qmcpack is not included in the h5, and needs to be provided separately. ppconvert is a tool to convert pseudopotentials in one format into the xml format read by qmcpack. If you have BFD pseudos, you can follow the instructions here in the manual: https://qmcpack.readthedocs.io/en/develop/additional_tools.html#obtaining-pseudopotentials
and it includes an example for BFD. 

Once you create the BFD.xml, just include that in the pseudo section in the qmcpack input and you should be good to go

**Comment by iliya-s** [comment]
I see, I understand now. I should be good to go! Thanks again Cody!

**Comment by prckent** [comment]
If your calculations permit, using the ccECPS from https://pseudopotentiallibrary.org/ would be easier since they are already converted, come with basis sets, and are likely a little more accurate depending on the elements.

**Comment by anbenali** [comment]
I was about to reply the same message as Paul.  If your purpose is to
learn/test, I will strongly advise against going to ppconvert as any
mistake could lead to various errors hard to track. The ccECPs are great
and very easy to use with both pyscf and qmcpack.

**Comment by mcbennet** [comment]
@iliya-s  Perhaps the following would suit your needs as well.

Assuming that $PYTHONPATH points to <path to qmcpack>/nexus/lib and you have a pseudopotential in gamess format. You can generate the xml file with the following bit of python

```
from pseudopotential import GaussianPP,gamessPPFile

ppf = gamessPPFile('Path to gamess formated pseudopotential')
pp = GaussianPP()
pp.read_text(ppf.pp_text,format='gamess')
pp.write_qmcpack('outputfile.xml')
```

If you wanted to do so, you could simply include this within your pyscf script
