### ISSUE TITLE
Constructing proper singlet excitations in solids

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/qmcpack#2753]
**Is your feature request related to a problem? Please describe.**
Is there a clean way of constructing proper singlet excitations for solids such as:

State<sub>EX</sub> = 1/sqrt(2) (alpha<sub>EX</sub>beta<sub>GS</sub> + alpha<sub>GS</sub>beta<sub>EX</sub>)

**Describe the solution you'd like**
Ideally, it would be great to have this in Nexus.
I am aware of [WIP] #2290 but I was curious if there is anything else before it's merged.

**Describe alternatives you've considered**
Currently, I am inserting the following in `wavefunction`  section instead of `slaterdeterminant`:

```
        <sposet basisset="LCAOBSet" name="spo-up" size="150">
          <occupation mode="ground"/>
          <coefficient size="150" spindataset="0"/>
        </sposet>
        <sposet basisset="LCAOBSet" name="spo-dn" size="150">
          <occupation mode="ground"/>
          <coefficient size="150" spindataset="0"/>
        </sposet>

      <multideterminant optimize="no" spo_up="spo-up" spo_dn="spo-dn">
        <detlist size="2" type="DETS" nca="0" ncb="0" nea="128" neb="128" nstates="150" cutoff="1e-20">
            <ci id="CIcoeff_0" coeff="0.7071067811865475" qc_coeff="0.7071067811865475" alpha="111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101000000000000000000000" beta="111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110000000000000000000000"/>                                                                                                                                                                       
            <ci id="CIcoeff_1" coeff="0.7071067811865475" qc_coeff="0.7071067811865475" alpha="111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110000000000000000000000" beta="111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101000000000000000000000"/>
        </detlist>
      </multideterminant>

```

which works, but this is very tedious and error prone in terms of the targeted gap.

**Additional context**
I am trying this for orbitals from Espresso
The excitation I am after is something like (0, 3 -> 0, 4) in (ti, bi) notation.

**Comment by prckent** [comment]
It would be much easier if we could specify the change from the ground state occupations here. However I don't believe we have any code for that in QMCPACK, so Nexus is the preferred long term route. To reduce errors, have you thought about writing a script to produce the detlist section in the interim?

**Comment by aannabe** [comment]
Thanks, yes, writing a small script is the way to go for now it seems.

**Comment by aannabe** [comment]
As #2290 was merged and this feature is implemented in Nexus, this issue can be closed.
