### ISSUE TITLE
ParameterSet cannot handle boolean

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2758]
**Describe the bug**
ParameterSet::add(bool) doesn't parse bool correctly.
The most funny logic is fliping value if the input entry is empty.
https://github.com/QMCPACK/qmcpack/blob/41b802bd38cb639ce040c555b4c20c4ecf490427/src/OhmmsData/OhmmsParameter.h#L171

**Expected behavior**
parse yes/no correctly

**Comment by prckent** [comment]
!!!

Presumably the fix will be to default to true if not present.

**Comment by ye-luo** [comment]
> !!!
> 
> Presumably the fix will be to default to true if not present.

"yes"/"no" will be the only acceptable value, the code should stop if empty value is given.
if the whole entry is not given, it is the default value as listed in the manual.

**Comment by prckent** [comment]
Good solution.

There might be a few input files to update in our tests and examples.

**Comment by ye-luo** [comment]
Another observation https://github.com/QMCPACK/qmcpack/pull/4126#discussion_r949686899
