### ISSUE TITLE
Fatal Error. Aborting at EinsplineSetBuilder::AnalyzeTwists2

### ISSUE THREAD

**Issue by kryczko** [QMCPACK/qmcpack#2768]
**Describe the bug**
After running PWSCF and a Jastrow optimization for a 2 atom graphene system, DMC fails with the following error: 

Fatal Error. Aborting at EinsplineSetBuilder::AnalyzeTwists2

This error appears in version 3.9.2 and the latest version of the code.

**To Reproduce**
The link to the files which reproduced this error is here: https://drive.google.com/file/d/1bk_h4TWQHhKgN6KO9r3AHRfuH8fBWfle/view?usp=sharing

**Expected behavior**
DMC to run as expected.

**System:**
Cori-haswell.

**Additional context**

**Comment by prckent** [comment]
@jtkrogel Are you able to see if this is a NEXUS related error or a QMCPACK error? Presumably some has gone wrong with bundling of the twists.

**Comment by jtkrogel** [comment]
I've actually given this a pretty close look.  There are 16 twists in the h5 file, each twist is requested by index (0-15), each is apparently found by QMCPACK, but then 12 of the 16 twists cause trip at the abort (4 run past the twist analysis).

I think this is a bug in the AnalyzeTwists2 routine in QMCPACK.

**Comment by prckent** [comment]
It would be interesting to know if the problem occurs without any bundling. i.e. This is definitely some problem with the twist analysis.

**Comment by kryczko** [comment]
I found the root cause after running just 1 twist as suggested by @jtkrogel. The error was:
```
ERROR Cannot use this super twist with real wavefunctions.
Please recompile with QMC_COMPLEX=1.
```
I will recompile qmcpack with this option and report back.

**Comment by kryczko** [comment]
I am now getting the error:
```
Fatal Error. Aborting at ParticleSet::addTable Cannot mix AoS and SoA distance tables.
```
I will run a single twist as well and see if I receive the same error.

**Comment by kryczko** [comment]
this issue seems to be fixed for commit id: 035e99ecd4047a805ca86326257ee3509f316031

**Comment by prckent** [comment]
That version and *older* is OK for you?

**Comment by kryczko** [comment]
Yes this version is ok. I can also double check the latest version.

Kevin

**Comment by ye-luo** [comment]
> this issue seems to be fixed for commit id: [035e99e](https://github.com/QMCPACK/qmcpack/commit/035e99ecd4047a805ca86326257ee3509f316031)

This commit itself is unlikely a fix to your issue but probably something before it.

**Comment by jtkrogel** [comment]
If you are running with the energy density on, you might run into this distance table error for v3.9.2.  All the energy density specific updates were made after this point.  Your original issue appears to be limited to real vs. complex code.

**Comment by kryczko** [comment]
yes, the real vs. complex code was the issue. Going to close.
