### ISSUE TITLE
How to disable OpenMP?

### ISSUE THREAD

**Issue by Xinying-Wang-CS** [QMCPACK/qmcpack#2778]
Hello, can anyone tell me how to use openmp when run QMCPACK? I run it on AWS Cloud, and just found I can only control the number of threads by export OMP_NUM_THREADS on 1 node, or on local node of multi-nodes experiments. So it's just impossible to control the number of threads on remote nodes when I run multi-nodes experiments. Actually, I export OMP_NUM_THREADS=1, MKL_NUM_THREADS=1, NUMEXPR_NUM_THREADS=1 on all nodes, but it only work on local node. So is there any method to correctly assign the value of OpenMP or just disable OpenMP?
Thank you~

**Comment by ye-luo** [comment]
We don't currently maintain a way to have OpenMP fully disabled. We may improve that in the future.
It is typically an issue that your job launcher `mpirun/runjob/srun` doesn't propagate environment variables properly. Please refer to your job launcher manual/help about handling of environment variables.

**Comment by prckent** [comment]
I agree with Ye here. Unfortunately there is almost certainly an issue with your MPI launcher or configuration. It is not uncommon to run QMCPACK in parallel with OMP_NUM_THREADS=1. For larger runs threading is usually more efficient.

**Comment by Xinying-Wang-CS** [comment]
Yes, thank you for the quick reply. I have 4 cores and just want to test the impact of openmp on performance such as running time. Also, when I typed echo $OMP_NUM_THREADS on remote nodes, they all display 1 correctly.  I'll try to set OMP_NUM_THREADS as 4 to see if it works.

**Comment by NavaneethS555** [comment]
> #pragma omp

 is used to specify Directives and Clauses. If /openmp isn't specified in a compilation, the compiler ignores OpenMP clauses and directives. OpenMP Function calls are processed by the compiler even if /openmp isn't specified.
By default for gcc compilers, OpenMP is disabled by default and enabled with the 

> -fopenmp

 option. Or run the code with the OMP_NUM_THREADS environment variable set to 1.

**Comment by ye-luo** [comment]
`-DQMC_OMP=OFF` should work now.
