### ISSUE TITLE
Turning off the neutralizing background

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/qmcpack#2793]
**Is your feature request related to a problem? Please describe.**
I've been looking at calculations using Wigner-Seitz Coloumb truncation using `pbc="no"` and so far the preliminary results are promising in terms of the obtained gaps. However, when charged systems are considered, the code still adds a neutralizing background even though the sums are now convergent.

**Describe the solution you'd like**
Is there a way to turn off the neutralizing background from the user end? If not, can you please point me to which routines will have to be changed?

This would be very useful for the estimation of IP, EA, and E_Fermi without resorting to clusters.

**Comment by jtkrogel** [comment]
There should not be any neutralizing background added.  This is done as a constant term in the CoulombPBC* classes.  Using `pbe="no"` should instead use the CoulombPotential class, which is identical to the open boundary conditions case and is ignorant of the cell, or even periodic boundary conditions itself.

What leads you to say it is being added?  Is something reported in the log, or do you see some evidence of it in the log file?  Please post your `<hamiltonian/>` block here.

**Comment by aannabe** [comment]
After discussions with Jaron, it's clear that the background charge is indeed not added. However, there are energy offsets in this case as well similar to Ewald interaction for charged cases.
