### ISSUE TITLE
How to calculate the inverse of complex matrix in MATLAB

### ISSUE THREAD

**Issue by yuanyuanmrwang** [QMCPACK/qmcpack#2838]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by prckent** [comment]
Hello. I think that you have opened this issue in the wrong repository. If you have a QMCPACK related question please create a new issue.

**Comment by yuanyuanmrwang** [comment]
Under Windows system, how to call CUDA library cublas to solve the inverse of many large complex matrices in MATLAB?
I have tried many times to solve only the inverse of a single double precision real matrix. Can you give a code example？

**Comment by ye-luo** [comment]
Again questions in the wrong place. See above.
