### ISSUE TITLE
Jastrow factor not sufficiently optimized with hybrid orbital representation

### ISSUE THREAD

**Issue by ichibha** [QMCPACK/qmcpack#2847]
**Describe the bug**
Jastrow optimization does not work with hybrid orbital representation.
The variance/energy ratio cannot be below 0.1.
I've confirmed that, when using B-spline basisset, the ratio converges around 0.026, with the exactly same calculation settings.
I have appended my calculation files.
[files.zip](https://github.com/QMCPACK/qmcpack/files/5817358/files.zip)

**System:**
I run the calculations on Cades at ORNL. 
You can find the submission details in the optJ2.sbatch.in in my calculation files.

**To Reproduce**
1. Extract files.zip in Cades
2. Change directory to files/opt_hybrid
3. Execute qsub optJ2.sbatch.in
4. Execute qmca -q ev *scalar.dat (after your job is finished)

QMC binary's location and version
-----------------------------------------
/home/8gb/Codes/src/qmcpack_develop/build_cades_cpu_real_skylake/bin/qmcpack 
Git branch: develop
Last git commit: 73548f001f6c8233a21cd064b2f92e23d8a64178-dirty
Last git commit date: Wed Apr 29 12:13:41 2020 -0500
Last git commit subject: Merge pull request #2409 from mmorale3/add_afqmc_estimators
-----------------------------------------
Since the binary was compiled by Chandler C Bennett, I am not sure of the compile command.

**Comment by ye-luo** [comment]
Carefully selecting parameters used by atomic centers in hybrid orbital representation is necessary.
With the same set of Jastrow, hybridrep should have a small variance to bspline only. Energy should be also match.
Clearly this is not the case in your calculation. 
No hybrid,
                            LocalEnergy               Variance           ratio 
optJ2  series 0  -199.589631 +/- 0.107751   14.750586 +/- 0.496129   0.0739 

using hybrid,
                            LocalEnergy               Variance           ratio 
optJ2  series 0  -197.337416 +/- 0.094519   36.046894 +/- 1.260242   0.1827 

Probably the current choice of parameters is poor.
cutoff_radius is not the larger the better. could you try smaller values?

your Jastrow optimization works well. Just the starting point was bad.

**Comment by prckent** [comment]
Did you check/optimize hybrid representation parameters with a determinant only calculation in VMC? This feature is only a change to the single particle orbitals, and with good parameters should be indistinguishable from conventional splines.

**Comment by ichibha** [comment]
Thank you for your replies. 
Using smaller radius_cutoff significantly reduces 1) the energy before optimization and 2) the energy and variance after optimization. 
Now (1) and (2) with hybrid representation are comparable with those without hybrid representation. 
I have not optimized the hybrid representation parameters by determinant-only vmc since I did not know that feature. 
I will use it when I need the hybrid representation, while I will accomplish this project without hybrid representation
since I have already some results with no hybrid. Thank you for your information.

I will share the QMCA log related to the above explanation:
Hybrid (radius_cutoff: B=2.085, N=1.525)
                            LocalEnergy               Variance           ratio 
optJ2  series 0  -197.337416 +/- 0.094519   36.046894 +/- 1.260242   0.1827 
optJ2  series 1  -201.525217 +/- 0.060472   31.385961 +/- 3.326591   0.1557 
optJ2  series 2  -203.383257 +/- 0.046932   21.577095 +/- 0.605649   0.1061 
optJ2  series 3  -203.537924 +/- 0.045797   23.045532 +/- 1.078252   0.1132 
optJ2  series 4  -203.500405 +/- 0.050451   22.434866 +/- 0.740465   0.1102 
optJ2  series 5  -203.530497 +/- 0.044645   23.602023 +/- 0.867512   0.1160 
optJ2  series 6  -203.513767 +/- 0.063844   21.273011 +/- 0.653439   0.1045 
optJ2  series 7  -203.498839 +/- 0.060788   30.519076 +/- 7.280707   0.1500 
optJ2  series 8  -203.575781 +/- 0.064429   22.718267 +/- 0.986218   0.1116 
optJ2  series 9  -203.606312 +/- 0.044701   22.268830 +/- 0.759507   0.1094 
optJ2  series 10  -203.444263 +/- 0.050877   19.694959 +/- 0.916387   0.0968 
optJ2  series 11  -203.590084 +/- 0.056084   23.242010 +/- 1.468734   0.1142 
optJ2  series 12  -203.585809 +/- 0.048269   23.025501 +/- 1.094527   0.1131 
optJ2  series 13  -203.590260 +/- 0.100730   24.178685 +/- 1.651851   0.1188 
optJ2  series 14  -203.379433 +/- 0.136343   24.935340 +/- 0.986679   0.1226 
optJ2  series 15  -203.639934 +/- 0.054848   22.440692 +/- 1.030368   0.1102 
optJ2  series 16  -203.655660 +/- 0.061618   23.378739 +/- 1.068513   0.1148 
optJ2  series 17  -203.616397 +/- 0.064562   26.599933 +/- 2.333981   0.1306 
optJ2  series 18  -203.533793 +/- 0.042531   22.615381 +/- 0.998556   0.1111 
optJ2  series 19  -203.486968 +/- 0.063594   21.807410 +/- 1.009827   0.1072 

Hybrid (radius_cutoff: B=1.885, N=1.325)
                            LocalEnergy               Variance           ratio 
optJ2  series 0  -197.420624 +/- 0.079302   27.001140 +/- 0.468919   0.1368 
optJ2  series 1  -201.500236 +/- 0.065111   19.430066 +/- 1.310892   0.0964 
optJ2  series 2  -203.132926 +/- 0.033564   16.618289 +/- 0.782943   0.0818 
optJ2  series 3  -203.100009 +/- 0.000000   20.216565 +/- 0.000000   0.0995 
optJ2  series 4  -203.438556 +/- 0.050050   15.777782 +/- 0.648322   0.0776 
optJ2  series 5  -203.410307 +/- 0.040669   14.654302 +/- 0.337533   0.0720 
optJ2  series 6  -203.353723 +/- 0.045313   15.622468 +/- 1.161043   0.0768 
optJ2  series 7  -203.414904 +/- 0.041618   15.655489 +/- 1.119431   0.0770 
optJ2  series 8  -203.438576 +/- 0.033290   14.849029 +/- 0.519984   0.0730 
optJ2  series 9  -203.575004 +/- 0.059497   13.349040 +/- 0.386297   0.0656 
optJ2  series 10  -203.425688 +/- 0.066046   14.971807 +/- 0.470769   0.0736 
optJ2  series 11  -203.402814 +/- 0.035409   15.587882 +/- 0.999078   0.0766 
optJ2  series 12  -203.395622 +/- 0.036533   15.372468 +/- 0.652418   0.0756 
optJ2  series 13  -203.063094 +/- 0.000000   22.061044 +/- 0.000000   0.1086 
optJ2  series 14  -203.477350 +/- 0.098412   14.877507 +/- 0.522851   0.0731 
optJ2  series 15  -203.378655 +/- 0.056399   15.465787 +/- 0.681750   0.0760 
optJ2  series 16  -203.283873 +/- 0.070740   15.564540 +/- 0.902206   0.0766 
optJ2  series 17  -203.507854 +/- 0.055946   15.504698 +/- 0.737151   0.0762 
optJ2  series 18  -203.374551 +/- 0.045850   20.119371 +/- 5.380679   0.0989 
optJ2  series 19  -203.508883 +/- 0.040662   14.456934 +/- 0.566035   0.0710 

Hybrid (radius_cutoff: B=0.9425, N=0.6625)
                            LocalEnergy               Variance           ratio 
optJ2  series 0  -199.488943 +/- 0.078953   15.400360 +/- 0.788024   0.0772 
optJ2  series 1  -203.694331 +/- 0.028895   7.911025 +/- 0.135531   0.0388 
optJ2  series 2  -205.294007 +/- 0.028994   5.974201 +/- 0.481775   0.0291 
optJ2  series 3  -205.581102 +/- 0.022662   5.505010 +/- 0.210310   0.0268 
optJ2  series 4  -205.496497 +/- 0.034520   5.213396 +/- 0.203909   0.0254 
optJ2  series 5  -205.529778 +/- 0.044006   6.283173 +/- 0.479666   0.0306 
optJ2  series 6  -205.581792 +/- 0.025658   5.425511 +/- 0.189261   0.0264 
optJ2  series 7  -173.462942 +/- 0.433166   1781.357319 +/- 35.909527   10.2694 
optJ2  series 8  -169.512318 +/- 0.730916   1857.120674 +/- 30.159830   10.9557 
optJ2  series 9  -168.663577 +/- 0.657823   1788.471179 +/- 41.170104   10.6038 
optJ2  series 10  -164.592615 +/- 0.523444   1864.516914 +/- 50.030962   11.3281 
optJ2  series 11  -161.677374 +/- 0.380963   1851.500817 +/- 37.182251   11.4518 
optJ2  series 12  -195.985302 +/- 0.150329   114.894135 +/- 4.367880   0.5862 
optJ2  series 13  -196.126388 +/- 0.110805   113.469711 +/- 1.712737   0.5786 
optJ2  series 14  -202.767259 +/- 0.052652   11.831612 +/- 0.196531   0.0584 
optJ2  series 15  -205.143019 +/- 0.046131   6.079750 +/- 0.167814   0.0296 
optJ2  series 16  -205.550295 +/- 0.029705   5.749252 +/- 0.138294   0.0280 
optJ2  series 17  -205.621741 +/- 0.002667   5.986156 +/- 0.405688   0.0291 
optJ2  series 18  -205.513660 +/- 0.064760   5.449946 +/- 0.104889   0.0265 
optJ2  series 19  -205.500156 +/- 0.019283   5.158538 +/- 0.170737   0.0251 

No hybrid 
                            LocalEnergy               Variance           ratio 
optJ2  series 0  -199.589631 +/- 0.107751   14.750586 +/- 0.496129   0.0739 
optJ2  series 1  -203.508769 +/- 0.037224   8.053003 +/- 0.205651   0.0396 
optJ2  series 2  -205.267983 +/- 0.037509   6.079233 +/- 0.303265   0.0296 
optJ2  series 3  -205.549084 +/- 0.027168   5.153941 +/- 0.093910   0.0251 
optJ2  series 4  -205.499506 +/- 0.030715   5.006539 +/- 0.093760   0.0244 
optJ2  series 5  -205.576632 +/- 0.026503   5.292642 +/- 0.178740   0.0257 
optJ2  series 6  -205.588561 +/- 0.045742   5.167959 +/- 0.140388   0.0251 
optJ2  series 7  -205.621056 +/- 0.032821   5.295420 +/- 0.067172   0.0258 
optJ2  series 8  -205.442013 +/- 0.028568   5.558818 +/- 0.161572   0.0271 
optJ2  series 9  -205.599639 +/- 0.036432   5.472083 +/- 0.133794   0.0266 
optJ2  series 10  -205.507848 +/- 0.035913   5.240303 +/- 0.228920   0.0255 
optJ2  series 11  -205.621266 +/- 0.025838   7.137553 +/- 1.194233   0.0347 
optJ2  series 12  -205.571291 +/- 0.036594   5.369171 +/- 0.244659   0.0261 
optJ2  series 13  -205.670564 +/- 0.037409   5.586685 +/- 0.445900   0.0272 
optJ2  series 14  -205.624919 +/- 0.021499   5.380483 +/- 0.130254   0.0262 
optJ2  series 15  -205.639486 +/- 0.043916   5.450380 +/- 0.228534   0.0265 
optJ2  series 16  -205.555500 +/- 0.033581   5.253249 +/- 0.159307   0.0256 
optJ2  series 17  -205.389727 +/- 0.000000   5.494561 +/- 0.000000   0.0268 
optJ2  series 18  -205.557604 +/- 0.033723   5.466245 +/- 0.171534   0.0266 
optJ2  series 19  -205.603519 +/- 0.014433   5.454627 +/- 0.241718   0.0265

**Comment by ye-luo** [comment]
@ichibha Thank you. All looks good now.

**Comment by jtkrogel** [comment]
This does not look good to me.  Even when the hybrid rep "works" there is a variance explosion in the middle of the optimization.  Also, isn't it typical to see a variance reduction w/ hybrid rep?  That is not evident at all here.

**Comment by ye-luo** [comment]
1. I saw the variance explosion. In this run, the optimization used only 8000 samples while the system has 128 electrons which is not a tiny one. So it doesn't seem to be a rigorous production to me as well. The optimization should be more robust when more samples are taken from long and wider VMC.
2. Too few samples caused large error bar on the variance. To me they are all within each other now.
3. If the spline grid is already very dense, the amount of variance reduction can be small.

**Comment by jtkrogel** [comment]
Still seems worth redoing the hybrid optimization with more samples, no?  It would be good to confirm that that there isn't a problem IMO.

Do you have a preferred procedure that constitutes careful selection of these parameters?

**Comment by prckent** [comment]
Just my opinion, but I still think it would be good to see that data on checking the hybrid representation parameters with a determinant only calculation in VMC.

**Comment by ichibha** [comment]
The variance explosion has been disappeared with 10 times more samples. 
The radius_cutoff is B=0.9425 and N=0.6625 and the mesh factor is 0.5. 
These values were just given as a try: not carefully selected. 

<img width="630" alt="スクリーンショット 2021-01-21 14 29 15" src="https://user-images.githubusercontent.com/41054969/105402733-cd098380-5bf5-11eb-9aec-33d0561cf9b2.png">
<img width="945" alt="スクリーンショット 2021-01-21 14 33 16" src="https://user-images.githubusercontent.com/41054969/105402777-d72b8200-5bf5-11eb-9070-12a4fb02730e.png">

If someone could tell me how to optimize the hybrid representation parameters with determinant-only VMC, I could check how much the variance gets reduced.

**Comment by ye-luo** [comment]
We don't have the feature optimizing hybrid representation parameters. We might consider put it on our roadmap in the future.
