### ISSUE TITLE
Nexus PRs and CI

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#2861]
Nexus tests aren't part of the CI and PRs for Nexus run the C++ CI.

So time and electricity is wasted.

**Describe the solution you'd like**
Nexus deserves its own repo and CI and to be a submodule in the QMCPACK repo.

**Describe alternatives you've considered**
Some sort of tagging or script determining where the changes in a PR are and then running the correct CI elements.
This is way more involved than the separate repos

**Additional context and Issues**
Nexus may require QMCPACK binaries to complete its testing.
The Nexus submodule hash in the QMCPACK repo would need to be updated often anyway.

**Comment by jtkrogel** [comment]
Perhaps just a script that searches for "Nexus" in PR title?  That is all it would need.

**Comment by prckent** [comment]
We also run the full CI for documentation updates (manual, changelog, readme). Again this is also wasteful. 

So the bigger question how we can be smarter overall. If we don't change the overall CI workflow, the GPU jobs would need to early return a pass on verifying that no source code was touched.

**Comment by PDoakORNL** [comment]
You would definitely need something like the Jenkins workflow I wrote awhile back.  And it would be much easier if it depended on PR titles like Jaron is suggesting as opposed to examining the content of commits.

**Comment by prckent** [comment]
Nexus is now tested in the CI. The timings are dominated by the build and test of QMCPACK. Therefore I think we can close this.

The topic of moving Nexus to a dedicated repo is an ongoing one that I am sure we'll revisit. While it might solve some perceived issues, it also adds workload. Personally, I don't think the benefits would be worth it just yet. Perhaps create a new issue for it.

**Comment by ye-luo** [comment]
Nexus is exercised by CI. Moving Nexus to a separate repo is a different topic. Let's close this one.
