### ISSUE TITLE
test_WalkerControlMPI unit test "regression" introduced in PR #2849

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#2865]
Unit tests stopped passing for Debug builds.

**To Reproduce**
1. build in debug post PR #2849 
2. ` ctest -R 'unit.*test_drivers_mpi' -V
3. Application crashes on 
../src/Particle/Walker.h:430: void qmcplusplus::Walker<qmcplusplus::QMCTraits, qmcplusplus::PtclOnLatticeTraits>::registerData() [t_traits = qmcplusplus::QMCTraits, p_traits = qmcplusplus::PtclOnLatticeTraits]: Assertion `DataSet.size() == 0' failed.

**Expected behavior**
Unit tests must pass in debug, Assertions largely protect from developer errors and must either be up to date with expected code behavior and pass.  

**System:**
Leconte, I image this is true on any system.

**Additional context**

**Comment by ye-luo** [comment]
On my way to a fix.
