### ISSUE TITLE
Bug: Cmake configure does not complete without MPI due to test dependencies

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#287]
Currently -DQMC_MPI=0 must be specified for cmake to complete:

Tested using the qmcpack 3.1.0 release tarball:

[pk7@oxygen build]$ cmake --version
cmake3 version 3.6.1

[pk7@oxygen build]$ cmake  ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
...
QMC_DATA not set. Performance tests not added.
Adding example tests for QMCPACK
Adding test example_H2O-1-1
Adding test example_He_simple-1-1
Adding test example_He_simple_dmc-1-1
Adding test example_He_simple_opt-1-1
Adding test example_He_from_gamess-1-1
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MPI_LIBRARY
    linked by target "test_utilities" in directory /home/pk7/t/qmcpack-3.1.0/src/Utilities/tests
    linked by target "test_io" in directory /home/pk7/t/qmcpack-3.1.0/src/io/tests
    linked by target "test_particle" in directory /home/pk7/t/qmcpack-3.1.0/src/Particle/tests
    linked by target "test_particleio" in directory /home/pk7/t/qmcpack-3.1.0/src/ParticleIO/tests
    linked by target "test_wavefunction" in directory /home/pk7/t/qmcpack-3.1.0/src/QMCWaveFunctions/tests
    linked by target "test_hamiltonian" in directory /home/pk7/t/qmcpack-3.1.0/src/QMCHamiltonians/tests
    linked by target "test_particle_base" in directory /home/pk7/t/qmcpack-3.1.0/src/ParticleBase/tests
    linked by target "test_drivers" in directory /home/pk7/t/qmcpack-3.1.0/src/QMCDrivers/tests
    linked by target "test_qmcapp" in directory /home/pk7/t/qmcpack-3.1.0/src/QMCApp/tests

-- Configuring incomplete, errors occurred!
See also "/home/pk7/t/qmcpack-3.1.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/pk7/t/qmcpack-3.1.0/build/CMakeFiles/CMakeError.log".

Specifically setting QMC_MPI=0 works:

cmake -DQMC_MPI=0 ..

Adding estimator tests for QMCPACK
TEST_MAX_PROCS was unset. Set to 16
Adding test estimator-skinetic-1-16
Missing python module pandas, not adding test estimator-latdev
Adding I/O tests for QMCPACK
Adding test restart-8-2
Adding test restart-1-16
Adding performance tests for QMCPACK
QMC_DATA not set. Performance tests not added.
Adding example tests for QMCPACK
Adding test example_H2O-1-1
Adding test example_He_simple-1-1
Adding test example_He_simple_dmc-1-1
Adding test example_He_simple_opt-1-1
Adding test example_He_from_gamess-1-1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pk7/t/qmcpack-3.1.0/build

**Comment by markdewing** [comment]
I think this the case where MPI is not found - FindMPI sets MPI_LIBRARY to LIBRARY-NOTFOUND.  In this case we should set MPI_LIBRARY to an empty string.

**Comment by prckent** [comment]
Agreed. It is an inconsistency in the FindMPI() handling compared to other libraries.

**Comment by prckent** [comment]
Verified as fixed by #288
