### ISSUE TITLE
Crash in VMC batched code (cusolver init) with not very large walker counts

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2874]
**Describe the bug**

Can not run many walkers before hitting a cusolver init error in the batched code.

e.g.  1024 walkers, 16 omp threads is bad:

8 electron water molecule / splines. llvmdev+cuda 11.2.0+openblas.

```
=========================================================
  Start VMCBatched
  File Root hf_vmc_1024w_batched_offload.s001
=========================================================
VMCBatched Driver running with target_walkers = 1024
                               walkers_per_rank = [1024]
                               num_crowds = 16
                    on rank 0, walkers_per_crowd = [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]

cusolverAssert: CUSOLVER_STATUS_INTERNAL_ERROR, file git_QMCPACK_prckent/qmcpack/src/QMCWaveFunctions/Fermion/DelayedUpdateCUDA.h , line 111
cusolverCreate failed!
```

With 1 omp thread and therefore crowd, 16-257 walkers are OK. 511, 512, and 1024 walkers are bad. => there is a subtle limit somewhere. If us, we should fix, if CUDA, we should chunk over some reasonable walker count to bypass.

Added: Note that the  legacy CUDA code is fine with these walker counts.

**To Reproduce**

1. development version 
2. offload build
3. cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DQMC_MPI=0 -DCMAKE_CXX_FLAGS=-Wno-unknown-cuda-version -DENABLE_OFFLOAD=ON -DUSE_OBJECT_TARGET=ON -DENABLE_CUDA=ON -DCUDA_ARCH=sm_70 -DCUDA_HOST_COMPILER=`which gcc` -DQMC_DATA=/scratch/QMC_DATA_FULL ../qmcpack/

**Expected behavior**
Large walker counts should run successfully. For small electron count systems, large walker counts are needed for performance, as per the legacy CUDA code.

**System:**

 nitrogen (AMD+NVIDIA V100), nightly testing setup.

**Additional context**

**Comment by ye-luo** [comment]
This is a memory issue I mentioned to you via slack. The reason is we cannot afford creating one cublas handle per walker. Each cublas handle needs 8MB and 1024 walker takes a lot. If you are not using batched slater determinant, you also need 33 MB per cusolver per walker.

**Comment by prckent** [comment]
I had assumed something like this was going on. It explains the legacy CUDA working successfully. The handle should be per MPI or per crowd at most. Hopefully we don't have other per walker handles, that choice just won't scale.

**Comment by prckent** [comment]
(Shouldn't all our BLAS be batched over the crowd size, or at least allow for it? => we only need one handle per crowd as you note. Perhaps a pre crowd design decision we are still living with in the source...)

**Comment by ye-luo** [comment]
Where you using batched slater determinant?
For batched slater determinant, I may have a chance to add a workaround until a clean solution was found. For the non-batched slater determinant, there is no way to handle it, nor necessary since we assume that is usefully only for extremely large problem size.

**Comment by prckent** [comment]
Usable scientific performance for sensibly-sized problems is the utmost priority. So I do think we need a workaround just yet.

**Comment by prckent** [comment]
I didn't answer your q: I copied inputs over from existing CPU and CUDA runs (what most people will do), so got the default. We'll need to change the defaults once the batched paths are fast and proven.

**Comment by ye-luo** [comment]
Resolved already.
