### ISSUE TITLE
batched VMC/DMC determinstic tests

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2889]
det_qmc_short_vmcbatch.in.xml
current configuration.
1 walker but with VMC no drift only.
Desired configuration
1 walker, VMC no dirft, VMC with drift and then DMC, in total 3 sections.

qmc_short_vmcbatch_dmcbatch.in.xml
det_qmc_short_sdbatch_vmcbatch_mwalkers.in.xml
current configuration.
2 walkers with 2 sections of VMC no drift.
Desired configuration
16 total walkers with VMC no dirft, VMC with drift and then DMC, in total 3 sections.
Needs these run cases, MPI ranks - threads
2 - 2
2 - 3 // uneven walker distribution in crowds.
1 - 4
1 - 16

**Comment by prckent** [comment]
Does the VMC batched code enforce #walkers is a multiple of the thread count? I am now more in favor of a warning and having the flexibility. If we do have the flexibility then it might be useful to test a prime number of walkers in at least one test.

**Comment by ye-luo** [comment]
@prckent No and I don't see a reason to require that enforcement. In a memory constrained scenario, 7 threads working on 10 walkers instead of 14 (insufficient memory). In this case, we do warn uneven distribution. Case "2 - 3" covers this with 8 walkers per rank on 3 threads (crowds).

**Comment by prckent** [comment]
Super.

I agree on your list of required tests.

**Comment by ye-luo** [comment]
@prckent See this example.
```
WARNING Walkers per rank (16) not divisible by number of crowds (3). This will result in a loss of efficiency.
DMCBatched Driver running with target_walkers = 16
                               walkers_per_rank = [16]
                               num_crowds = 3
                    on rank 0, walkers_per_crowd = [6, 5, 5]
```
