### ISSUE TITLE
unit_test_estimators numerical issue with Intel compiler

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#290]
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=unit_test_estimators&date=2017-07-12

All the GNU builds are fine but the Intel builds are not. I think we need to make the checking a bit more flexible to the numerics.

**Comment by prckent** [comment]
Is a full precision comparison used? The error messages show full agreement up to the number of printed digits.

/data/ci/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/src/Estimators/tests/test_accumulator.cpp:153: FAILED:
  REQUIRE( mv.second == a.variance() )
with expansion:
  5.1909181302 == 5.1909181302

**Comment by ye-luo** [comment]
Showing all pass
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=unit_test_estimators&date=2017-08-04
