### ISSUE TITLE
Numerical accuracy in comparison of Jastrow cutoffs

### ISSUE THREAD

**Issue by kylanpaa** [QMCPACK/qmcpack#291]
Currently Jastrow optimizer kills the run if rcut > WignerSeitzRadius. In my calculation rcut was less than 2e-8 % larger than WignerSeitzRadius, which ended up in a fatal error and killed the run. Some kind of tolerance could be added in order to avoid these in the future.

**Comment by prckent** [comment]
Agreed.

There are some missing tolerances in the checks added in #256 
Bsplinefunctor.h appears to be missing a tolerance check. There might be others.

**Comment by ye-luo** [comment]
Yes. I have received complaints from multiple sources.
@prckent Do we need to provide a v3.1.1 release?

**Comment by prckent** [comment]
We need to fix the problem first!

**Comment by prckent** [comment]
@ye-luo Please also try to persuade the complainers to leave GitHub issues. It is hard to fix problems and prioritize them if they are unreported.

**Comment by prckent** [comment]
Closed by #305
