### ISSUE TITLE
Linear method crashes in spin-orbit case.

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/qmcpack#2914]
**Describe the bug**
Jastrow optimization crashes when spin-orbit VMC is used after a couple of iterations with the following error:
`ERROR Safeguard failure: checkConfigurations variance out of [0.5, 2.0] * reference! Please report this bug.`

**To Reproduce**
1. develop branch, git commit: ddaf2250d2b8d51387b20d6632ba59551a182472
2. build.sh included in the attachment.

**System:**
NERSC/KNL

**Additional context**
Orbitals from Espresso/6.4.1

[qmc_opt.zip](https://github.com/QMCPACK/qmcpack/files/5978970/qmc_opt.zip)

**Comment by prckent** [comment]
Hmm. Perhaps the energy recomputation is incorrect in the spin-orbit case.

Have you been successful with any spin-orbit wavefunction optimizations?

**Comment by aannabe** [comment]
This is the only system I tried Jastrow optimizations and couldn't achieve a successful result. Actually, the crash can be avoided if `minwalker` parameter is increased significantly, at the expense of very slow optimization.

**Comment by ye-luo** [comment]
Need to understand why the re-compute in optimization driver has much larger variance than VMC.
```
====================================================
  SimpleFixedNodeBranch::finalize after a VMC block
    QMC counter        = 0
    time step          = 0.7
    reference energy   = -553.17
    reference variance = 29.767
====================================================
  Execution time = 1.3176e+02
</vmc>
<opt stage="setup">
  <log>
   Reading configurations from h5FileRoot gs_vmc.s000
  QMCCostFunction is created with 68 threads.
  Using Nonlocal PP in Opt: NonLocalECP
   Number of samples loaded to each thread : 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 
  VMC Eavg = -5.5378e+02
  VMC Evar = 4.0547e+01
  Total weights = 1.6320e+04
  Execution time = 7.3828e+00
  </log>
</opt>
```
29 vs 4.0547e+01
