### ISSUE TITLE
Testing of SoA code: machines, compiler, option combinations

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#292]
Which compiler and machine configurations should be added to our nightly tests for the SoA option ( #289 ) ?

Intel2017
GCC with netlib BLAS
GCC+MKL
GCC+CUDA ?

What about precision handling?

**Comment by ye-luo** [comment]
Need to add the flag ENABLE_SOA in CMake/ctest_script.cmake. I already have it on my local branch for the experimental nightly tests. Just need to PR it.

Intel 2017 + real +FP
Intel 2017 + cplx +MP
GCC + MKL + cplx + FP
GCC + netlib BLAS + real + MP

GCC + CUDA. I think it builds but not clear about correctness.

**Comment by prckent** [comment]
I will let the unmodified integration tests (inc. long tests) run this weekend, then assuming no problems are found will add the above to our nightly testing. 

If you have setup the "pass through" of ENABLE_SOA flag in the ctest_script, please PR it.  i.e. CTest -DENABLE_SOA={0,1} is properly routed through to CMake.

**Comment by prckent** [comment]
Added Intel builds in #330 

Will evaluate other configurations based on runtime.

GCC+MKL+Complex+Mixed precision and CUDA variants are most likely additions.

**Comment by prckent** [comment]
Handled by #351
