### ISSUE TITLE
Batched linear optimizer is failing to reach expected energy

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#2959]
Using the NiO a16-e192 system (no J3) starting from all J1 and J2 parameters equal to zero, the batched linear optimizer fails to reach the correct point.

The expected VMC energy is -1483.52 (.02), based on VMC runs using the existing variational parameters.

Batched runs reach -1480.  Using the non-batch code, they reach -1483

Run using batched code on Andes
```
batch2  series 0  LocalEnergy           =  -1476.698428 +/- 0.073924 
batch2  series 1  LocalEnergy           =  -1482.063798 +/- 0.053130 
batch2  series 2  LocalEnergy           =  -1481.374187 +/- 0.055747 
batch2  series 3  LocalEnergy           =  -1480.706633 +/- 0.036317 
batch2  series 4  LocalEnergy           =  -1480.612111 +/- 0.058774 
batch2  series 5  LocalEnergy           =  -1480.571701 +/- 0.032523 
batch2  series 6  LocalEnergy           =  -1480.605058 +/- 0.040692 
batch2  series 7  LocalEnergy           =  -1480.619242 +/- 0.059515 
```

Run using old (non-batch) code on Andes
```
nonbatch1  series 0  LocalEnergy           =  -1476.686369 +/- 0.078668 
nonbatch1  series 1  LocalEnergy           =  -1482.890977 +/- 0.049735 
nonbatch1  series 2  LocalEnergy           =  -1483.508561 +/- 0.051229 
nonbatch1  series 3  LocalEnergy           =  -1483.554442 +/- 0.034189 
nonbatch1  series 4  LocalEnergy           =  -1483.528511 +/- 0.036907 
nonbatch1  series 5  LocalEnergy           =  -1483.495636 +/- 0.042443 
nonbatch1  series 6  LocalEnergy           =  -1483.585997 +/- 0.051502 
nonbatch1  series 7  LocalEnergy           =  -1483.523396 +/- 0.041098
```

The sequence of energies is remarkably stable (different RNG seeds, different number of samples, changing the objective from 100% energy to 95% energy/%5 reweighted variance).
Running the offload code on Summit gives the same (incorrect) answer.

It started failing sometime in the last two weeks.  An older executable on my desktop produces the expected sequence of energies from the batch code.

**Comment by ye-luo** [comment]
Will you get a chance to narrow down the offending commit?

**Comment by markdewing** [comment]
I'll work on trying to figure out the problem commit.

**Comment by markdewing** [comment]
git bisect has identified this commit
https://github.com/QMCPACK/qmcpack/pull/2928/commits/174ef5d3f08babd8879e85d1b5e8186df1d85fd1

which is part of
https://github.com/QMCPACK/qmcpack/pull/2928/files

I need to understand what about this commit is causing the difference

**Comment by ye-luo** [comment]
It is also worth trying current develop 5087141
