### ISSUE TITLE
Benchmark member functions: do they have a current purpose?

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#296]
Some of our classes have "benchmark" functions. Are these useful or should they be stripped?

**Comment by ye-luo** [comment]
Could you point me one in the code?

**Comment by prckent** [comment]
There are some in the #289 PR. I thought there were more, but checking the development branch they appear to be SoA related only.

**Comment by prckent** [comment]
Examples:
src/QMCDrivers/DMC/DMCOMP.cpp:365:void DMCOMP::benchMark()
src/QMCDrivers/QMCUpdateBase.cpp:367:void QMCUpdateBase::benchMark(WalkerIter_t it, WalkerIter_t it_end, int ip)
