### ISSUE TITLE
Improve GNU compiler configurations and Cray handling.

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#297]
GNU compiler configuration now checks the CPU flags (SSE,AVX...) on the host building the code.
This is not friendly to cross-compiling and usually not accurate enough.
Proposed changes:
Align with Intel compiler setup.
1) -march=native as -xhost by default.
2) when -march is specified by users, respect it for cross-compiling.
3) In cray environment, do nothing as CC/cc already have the tuning flag beneath. (both Intel and GNU)

**Comment by ye-luo** [comment]
@prckent The nightly tests build well. Do we need extra manual checks? Nersc(see my PR note)?
This issue can be closed if no issue is spotted.

**Comment by prckent** [comment]
On Cori/Haswell with Intel compilers this yields
>-std=c++11  -qopenmp -Wno-deprecated -qopt-prefetch -ftz -mkl -O3 -DNDEBUG -restrict -unroll -ip
and most importantly the code still builds.

On Cori/KNL with Intel compilers and *following the instructions in the manual* we get
>-std=c++11 -xMIC-AVX512 -qopenmp -Wno-deprecated -qopt-prefetch -ftz -mkl -O3 -DNDEBUG -restrict -unroll -ip
whereas if we ignore the manual and don't put
>-DCMAKE_CXX_FLAGS="-xMIC-AVX512" -DCMAKE_C_FLAGS="-xMIC-AVX512"
then we don't get the AVX512 flags as expected.

I think that this is correct. Close this issue?

**Comment by ye-luo** [comment]
I would recommend not to put ``-DCMAKE_CXX_FLAGS="-xMIC-AVX512" -DCMAKE_C_FLAGS="-xMIC-AVX512"`` for KNL. CC wrapper is doing everything for you. Could you type make in this case? if you don't seen tons of -xHost warning, we can close this ticket.

**Comment by prckent** [comment]
1. There are no explicit -xHost on Cori shown by make VERBOSE=1 in any configuration.
2. Indeed, without the CXX_FLAGS override, the code does build. Hopefully the Cray environment is working.
3. The manual entry for Cori needs to be updated.
4. Theta is missing from the manual.
