### ISSUE TITLE
Enforce C++11 in CMake

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#298]
After the SoA merge, C++11 is required. The CMake configuration needs to be updated.

**Comment by ye-luo** [comment]
MEMO: Raise minimum compiler versions.

**Comment by ye-luo** [comment]
Apart from C++11, support for #pragma omp simd (OpenMP 4.0) is also needed.
Picked from http://www.openmp.org/resources/openmp-compilers/
1) In GCC 4.9.0, OpenMP 4.0 is supported for C and C++, but not Fortran.
2) XL C/C++ for Linux V13.1.5 on little endian distributions
3) OpenMP 4.0 C/C++/Fortran supported in version 15.0 and 16.0 compilers
4) The Clang 3.9 release supports all non-offloading features of OpenMP 4.5.

**Comment by prckent** [comment]
Note that this upgrade will need careful checking on all our platforms. We should check that the build recipes in the manual still work and update them if not.

**Comment by prckent** [comment]
It would be convenient if cmake could check OpenMP versions. To do so it looks like we'll have to write our own tester - ideally our configuration would error out if SOA was enabled but OpenMP4 was not available.

**Comment by prckent** [comment]
Simpler idea: Mandate C++11 and OpenMP4 now, regardless of configuration?

**Comment by markdewing** [comment]
How do compilers react that don't understand #pragma omp simd?
I tried it on gcc 4.8.4, and it silently ignored it.   With -Wall it issued a warning about an unknown pragma.

Mandating OpenMP 4 seems harder to manage.

**Comment by prckent** [comment]
I was concerned about gcc 4.8.x, but a silent fail is fine. No need to mandate.

**Comment by ye-luo** [comment]
Not very helpful to check OpenMP version. Some compilers only support part of the standard. Version doesn't represent the situation well.
I think most recent C++11 compliant compilers provide what we need already.
If it doesn't, just silent ignore #omp simd and the default auto-vectorization kicks in is fine.
