### ISSUE TITLE
Addition of max_seconds to input in order to avoid corrupted output data.

### ISSUE THREAD

**Issue by kylanpaa** [QMCPACK/qmcpack#300]
Currently, if QMCPACK exceeds wall time limit, the hdf5 files with observables such as density will not be closed and they become unusable. If the wall time limit would be given in the input QMCPACK could estimate during the simulation when to end the run without loosing all the data, that is, whether to continue to next block or not. If it would not continue further then the data as well as walkers should be saved. Mainly a feature for more user friendly QMCPACK, and conveniently utilized with NEXUS also.

**Comment by markdewing** [comment]
The DMC driver has the 'maxcpusecs' parameter.   At the end of each block, it checks to see if this time has been exceeded, and quits if so.   This isn't quite what is requested as it requires the user to know about how long each DMC block takes and set parameter to the wall time limit minus the time for one block (and minus start up time and other time occurring before the DMC driver)

It would be better for a time limit parameter work as described.

**Comment by prckent** [comment]
Agree that we should predict reaching the time limit and shut down sooner and more safely. Are the HDF5 files (observables) closed correctly in the current maxcpusecs implementation?

**Comment by markdewing** [comment]
The current maxcpusecs code exits the loop the same as reaching the target number of blocks.   So all the files should be closed correctly as long as the regular code implementation closes everything correctly.

**Comment by prckent** [comment]
@markdewing Can you get to this? If it is "just" checking that the next block can be completed with some safety factor, this seems straightforward and worthwhile.

**Comment by markdewing** [comment]
I will look into what this would take for implementation.

**Comment by prckent** [comment]
(Mark has a prototype of this feature)
