### ISSUE TITLE
AFQMC unit test failure with CUDA

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3036]
**Describe the bug**
real build fails for segmentation fault. It is not necessarily segmentation fault.
https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=196153
complex build
`Fatal Error. Aborting at  Error: KPFactorizedHamiltonian requires complex build (QMC_COMPLEX=1). `
https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=196143

**To Reproduce**
-DBUILD_AFQMC=ON -DENABLE_CUDA=ON

**Comment by ye-luo** [comment]
Actually real builds are fixed but not complex builds. Keep this issue open.

**Comment by mmorale3** [comment]
I don't understand the error. The execution should not be here if QMC_COMPLEX is defined.
This is meant to abort when real builds try to run k-point hamiltonians.

**Comment by mmorale3** [comment]
Can you point me to the build details?

**Comment by ye-luo** [comment]
@mmorale3 found the root cause #3072
