### ISSUE TITLE
Tests fail when < 16 cores available

### ISSUE THREAD

**Issue by quantumsteve** [QMCPACK/qmcpack#3038]
**Describe the bug**

Tests fail when < 16 cores available on the system

```
ctest -VV -R short-heg_14_gamma-sjb-16-1
UpdateCTestConfiguration  from :/home/wgodoy/workspace/qmcpack/build/DartConfiguration.tcl
Parse Config file:/home/wgodoy/workspace/qmcpack/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/wgodoy/workspace/qmcpack/build/DartConfiguration.tcl
Parse Config file:/home/wgodoy/workspace/qmcpack/build/DartConfiguration.tcl
Test project /home/wgodoy/workspace/qmcpack/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 110
    Start 110: short-heg_14_gamma-sjb-16-1
110: Test command: /usr/bin/mpiexec "-n" "16" "--bind-to" "none" "/home/wgodoy/workspace/qmcpack/build/bin/qmcpack" "heg-short-SJB.xml"
110: Environment variables: 
110:  OMP_NUM_THREADS=1
110: Test timeout computed to be: 3600
110: --------------------------------------------------------------------------
110: There are not enough slots available in the system to satisfy the 16
110: slots that were requested by the application:
110: 
110:   /home/wgodoy/workspace/qmcpack/build/bin/qmcpack
110: 
110: Either request fewer slots for your application, or make more slots
110: available for use.
110: 
110: A "slot" is the Open MPI term for an allocatable unit where we can
110: launch a process.  The number of slots available are defined by the
110: environment in which Open MPI processes are run:
110: 
110:   1. Hostfile, via "slots=N" clauses (N defaults to number of
110:      processor cores if not provided)
110:   2. The --host command line parameter, via a ":N" suffix on the
110:      hostname (N defaults to 1 if not provided)
110:   3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
110:   4. If none of a hostfile, the --host command line parameter, or an
110:      RM is present, Open MPI defaults to the number of processor cores
110: 
110: In all the above cases, if you want Open MPI to default to the number
110: of hardware threads instead of the number of processor cores, use the
110: --use-hwthread-cpus option.
110: 
110: Alternatively, you can use the --oversubscribe option to ignore the
110: number of available slots when deciding the number of processes to
110: launch.
110: --------------------------------------------------------------------------
1/3 Test #110: short-heg_14_gamma-sjb-16-1 .............***Failed  Required regular expression not found. Regex=[QMCPACK execution completed successfully
]  0.09 sec
test 111
    Start 111: short-heg_14_gamma-sjb-16-1-totenergy
111: Test command: /home/wgodoy/workspace/qmcpack/tests/scripts/check_scalars.py "--ns" "3" "--series" "0" "-p" "heg_short_SJB" "-e" "2" "--le" "-1.084963  0.000251"
111: Test timeout computed to be: 3600
111: scalar file does not exist: heg_short_SJB.s000.scalar.dat
111: Test status: fail
2/3 Test #111: short-heg_14_gamma-sjb-16-1-totenergy ...***Failed    0.02 sec
test 112
    Start 112: short-heg_14_gamma-sjb-16-1-variance
112: Test command: /home/wgodoy/workspace/qmcpack/tests/scripts/check_scalars.py "--ns" "3" "--series" "0" "-p" "heg_short_SJB" "-e" "2" "--va" " 0.022667  0.000764"
112: Test timeout computed to be: 3600
112: scalar file does not exist: heg_short_SJB.s000.scalar.dat
112: Test status: fail
3/3 Test #112: short-heg_14_gamma-sjb-16-1-variance ....***Failed    0.02 sec
0% tests passed, 3 tests failed out of 3
Label Time Summary:
QMCPACK                     =   1.38 sec*proc (1 test)
QMCPACK-checking-results    =   0.04 sec*proc (2 tests)
bug                         =   1.43 sec*proc (3 tests)
hard_fail                   =   1.43 sec*proc (3 tests)
quality_unknown             =   1.43 sec*proc (3 tests)
unstable                    =   0.04 sec*proc (2 tests)
Total Test time (real) =   0.19 sec
The following tests FAILED:
	110 - short-heg_14_gamma-sjb-16-1 (Failed)
	111 - short-heg_14_gamma-sjb-16-1-totenergy (Failed)
	112 - short-heg_14_gamma-sjb-16-1-variance (Failed)
Errors while running CTest
```

**To Reproduce**
1. release version or git commit hash being built
  36fce96a95b655717e24c9ad7ad3fdb59357c699
2. cmake command
  cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx ..
3. full program/test invocation command
  ctest -VV -R short-heg_14_gamma-sjb-16-1
4. additional steps
  workstation has < 16 cores

**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit]
   @williamfgc's computer
 - modules loaded [e.g. output of `module list`]
   apt package manager
 - other systems where this is reproducible [e.g. "my laptop", "none"]
  any computer with openmpi and < 16 cores

**Additional context**

Do we want to set `TEST_MAX_PROCS` to min(16,N) where N is set by [ProcessorCount[N]](https://cmake.org/cmake/help/latest/module/ProcessorCount.html) in CMake or skip the test?

`TEST_MAX_PROCS` is defined [here](https://github.com/QMCPACK/qmcpack/blob/36fce96a95b655717e24c9ad7ad3fdb59357c699/tests/CMakeLists.txt), [here](https://github.com/QMCPACK/qmcpack/blob/0ddd2f1decc1f896015c38eb7ed71627beed38c3/tests/estimator/CMakeLists.txt#L9), [here](https://github.com/QMCPACK/qmcpack/blob/849cc0cd4187a740fa597a2a6a3ec7e116a40cf5/tests/pw2qmcpack/CMakeLists.txt#L7), and [here](https://github.com/QMCPACK/qmcpack/blob/d6717f664c148af995c3c3734592443269d79112/CMakeLists.txt). Maybe set it in CmakeLists.txt and promote it to a CACHE variable?

**Comment by ye-luo** [comment]
You should still be able to test even your computer has 1 physical core. MPI ranks and OpenMP threads are software. Core is hardware. They can be decoupled. Your mpirun/mpiexec set restrictions to prevent inefficient runs and you simply need to workaround it for testing purpose. `--oversubscribe` is mention the message above. Try adding 
`-DCMPIEXEC_PREFLAGS="--bind-to;none;--oversubscribe"` to you cmake invocation.

**Comment by ye-luo** [comment]
Don't forget to add `-j` to ctest for parallel testing.

**Comment by prckent** [comment]
My understanding is that unfortunately this is the case of the OpenMPI developers having been forced to choose a default to protect themselves from (poor) benchmarkers. OpenMPI always needs special configuration as Ye indicated to do the "right thing" for applications.

**Comment by prckent** [comment]
Note that short and long tests may fail sporadically - they are statistical in nature unlike the ones labeled deterministic. However they should never give an actual error along the above lines, e.g. a misconfiguration, missing python module etc.

A few of the less popular features will also always fail due to implementation limitations/bugs etc. - see cdash or ask around if unsure.

**Comment by quantumsteve** [comment]
@ye-luo @prckent Thank you for your replies and suggestions for working around the error.

How many parallel ctest jobs do you typically run for the different categories of tests? I initially tried `ctest -j 20` on my 20 core workstation and noticed the CPU was significantly oversubscribed.

**Comment by quantumsteve** [comment]
Closing since there isn't interest in better matching the number of mpi ranks and threads with the number of cores on the test machine.

**Comment by prckent** [comment]
Some background info: since all the tests other than unit tests check some flavor of science result, currently we only have reference numerical check data for a specific number of threads/tasks. Typically 16. This is hardwired. Running ctest on multiples of 16 cores therefore makes most sense (e.g. ctest -j 48). For tests with valid statistics (those labelled short and long) the 16 core hardwiring could be generalized, since we would only need to rescale the error bar by the amount of work done. However the deterministic tests do not have valid statistics so could never be generalized.

The HPC environment is potentially one area where we would like to use many nodes for the tests. Resource allocation could be useful here. However since the build time tends to dominate overall runtime, I don't think this has ever been looked at.

**Comment by ye-luo** [comment]
> I initially tried ctest -j 20 on my 20 core workstation and noticed the CPU was significantly oversubscribed.

We do use PROCESSORS test property to avoid over-subscription. How did you judge over subscription?
