### ISSUE TITLE
ASAN test failures 

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#3083]
**Describe the bug**
Address sanitizers (ASAN) failures are currently reported from LSAN [as it is turned on by default on Linux](https://clang.llvm.org/docs/AddressSanitizer.html#memory-leak-detection). Tests are excluded from CI as added in PR #3081.
The following unit test have been identified as not currently passing ASAN and are currently labeled as `noasan` using cmake:

```
The following tests FAILED:
	 12 - deterministic-unit_test_estimators (Failed)
	 17 - deterministic-unit_test_einspline (Failed)
	 20 - deterministic-unit_test_wavefunction_trialwf (Failed)
	 21 - deterministic-unit_test_wavefunction_sposet (Failed)
	 22 - deterministic-unit_test_wavefunction_jastrow (Failed)
	 23 - deterministic-unit_test_wavefunction_determinant (Failed)
	 24 - deterministic-unit_test_hamiltonian (Failed)
	 26 - deterministic-unit_test_drivers (Failed)
	 27 - deterministic-unit_test_new_drivers (Failed)
	 29 - deterministic-unit_test_qmcapp (Failed)
```

**To Reproduce**
1. `develop` branch
2. configuration:
```
CCompiler=clang
CXXCompiler=clang++

CC=$CCompiler CXX=$CXXCompiler cmake -GNinja \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx \
  -DENABLE_SANITIZER=asan \
  -DQMC_COMPLEX=0 \
  ..
```
`export LSAN_OPTIONS=suppressions=${QMC_HOME}/config/sanitizers/lsan.supp`
`${QMC_HOME}` is your local QMCPACK source location.	
3. Build: `ninja`
4. `ctest -L noasan`

**Expected behavior**
Tests must pass.
After fixing those unit tests they must be incorporated into asan checks on CI

**System:**
 - Ubuntu 20.04
 - GitHub Actions
 - should be reproducible everywhere

**Additional context**
This is only for the real build. We can expand this ticket to complex build failures (if any)

**Comment by ye-luo** [comment]
step 4 is it ninja or ctest?

**Comment by williamfgc** [comment]
@ye-luo  good catch, thanks!

**Comment by PDoakORNL** [comment]
So what ASAN_OPTIONS is this equivalent to or is this actually a gcc sanitizer?
For instance when I look at test_new_drivers and test_estimators I see no asan failures at all only lsan failures.
Or are we talking about LSAN here?

**Comment by williamfgc** [comment]
@PDoakORNL good point, yes these are mostly leaks. `asan` on Linux includes `lsan` by default. `ASAN_OPTIONS` is not set, but `LSAN_OPTIONS` for suppressions of C underlying libraries (mostly MPI). I updated the description to enable reproducibility. The leaks come mostly from non-deallocated objects using `new`. Hope it helps, thanks.
