### ISSUE TITLE
Update Spack QMCPACK and QE packages after v3.11.0 release

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#3090]
The spack QMCPACK and QE packages need to be updated to include the v3.11.0 release and QE6.7 support.

**Comment by prckent** [comment]
I am not sure of the current status in the spack package, but it would also be good to check the status of the tests. Running all the deterministic tests for CPU builds is safe and worth having available if someone installs the package and requests them.

**Comment by naromero77** [comment]
This is what the Spack package does if you add the test flag. It will run `unit` tests first and they will need to pass for QMCPACK to be installed. It will then run `deterministic` test but excludes those tests labeled `unstable`. If the second set of  tests fail, a warning is emitted but it won't prevent QMCPACK from being installed.
```
	with working_dir(self.build_directory):
	    ctest('-R', 'unit')
            try:
                ctest('-R', 'deterministic', '-LE', 'unstable')
	    except ProcessError:
                warn  = 'Unit tests passed, but deterministic tests failed.\n'
		warn += 'Please report this failure to:\n'
                warn += 'https://github.com/QMCPACK/qmcpack/issues'
		tty.msg(warn)
```

**Comment by naromero77** [comment]
QMCPACK Spack package
https://github.com/spack/spack/pull/22978

Still need QE Spack package

**Comment by prckent** [comment]
Fair enough.

You could also use -L deterministic only with hard pass requirement. We use this in the CI. The unit tests don't have anywhere near enough coverage.

**Comment by naromero77** [comment]
We can totally change it to just
`ctest('L', 'deterministic')`
if you want.

If you think about it for a couple of days, let me know.

**Comment by naromero77** [comment]
QMCPACK QE converter:
https://github.com/spack/spack/pull/23049

**Comment by prckent** [comment]
@naromero77 Close this or are more updates needed/planned?
