### ISSUE TITLE
Batched DiracMatrix inversion and log det

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3115]
**Is your feature request related to a problem? Please describe.**
DiracMatrix is another object mixing single walker data with 1 or more walker functions.

The MatrixUpdateEngine (MatrixDelayedUpdateCUDA,MatrixUpdateOMPTarget) is another of these objects but the resolution of that is beyond the scope of this feature.  Right now there is one of these objects per walker.  Each of them holds 1 DiracMatrix object, its main purpose is to invert and calculate the log determinant of the matrix. 

**Describe the solution you'd like**
Push the matrix data member up into the MatrixUpdateEngine.
Make the DiracMatrix a 1 per crowd object that owns the shared resources required for matrix inversion and log det calculation at the crowd level. DiracMatrix will have some degree of specialization for the compute device.

**Describe alternatives you've considered**
Keeping the current design which mixes single walker data and 1 or many walker computation using the single walker data. 

**Additional context**
This confusion between data and computation is an unfortunate OO pattern that pervades the code.  It is easiest to unravel at the bottom near the actual data transformation functions.  Whenever we can we should do this.

**Comment by ye-luo** [comment]
@PDoakORNL consider completed?
