### ISSUE TITLE
C2 MSDJ test crashes

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#3161]
**Describe the bug**
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-C2_pp_msdj-XML-traditional-vmc-1-16&date=2021-05-09

short-C2_pp_msdj-XML-traditional-vmc-1-16 Mixed precision builds with Intel 2019 on sulfur and bora are crashing with NaN. The long test is also consistently failing for the same reason. 

Strongly suggests a bug. Could also be numerical troubles, but if so these should also be trapped earlier+more meaningfully. e.g. Check for problems in the MSD code if that is the source of the problem.  Could also be bad inputs that the full precision builds tolerate.

Based on the cdash history, they have been failing for all of 2021.

```
 Anonymous Buffer size per walker : 49424 Bytes.
MEMORY increase 0 MB VMC::resetRun
Fatal Error. Aborting at QMCHamiltonian::evaluate component Kinetic returns NaN

Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 3681470 RUNNING AT sulfur.ornl.gov
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================

``` 

**To Reproduce**
Latest develop, nightly configuration. Seems to require mixed precision.

**Expected behavior**

**Comment by ye-luo** [comment]
This is the "traditional" case without table method.

**Comment by ye-luo** [comment]
"traditional" code paths have been deleted.
