### ISSUE TITLE
Parameter derivatives incorrect for CI coefficients

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#3172]
Parameter derivatives are incorrect for CI coefficients in a multideterminant wavefunction. The "test" optimizer output shows a large discrepancy between the analytic and numerical gradient values.  (This certainly also affects the linear method, as the matrices are built from the same ingredients as the parameter derivatives)

The regression was introduced in https://github.com/QMCPACK/qmcpack/pull/2947
specifically, commit https://github.com/QMCPACK/qmcpack/commit/769807541057d636b75e7faa0b917db2d5dd33f9

(Thanks to "git bisect" for making it straightforward to isolate the commit)

(The real problem is we didn't have a test to catch a regression like this)

It can be reproduced with the C2_pp test case.  In the wavefunction, set the "optimize" attribute to "yes" in the  "multideterminant" tag.  (Can also turn off optimization for the Jastrow factors to make the output clearer).  Use the "test" optimize method, as
```
    <qmc method="opt" move="pbyp" checkpoint="-1">
      <optimize method="test" output_param_file="yes"/>
     ...
```

First few lines of the analytic-numerical comparison
```
Param_Name  Value    Numeric            Analytic       Percent
CIcoeff_1 3.3152e-01  1.1184e-01  -2.6137e-02  1.2337e+02
CIcoeff_2 8.4180e-02  1.3111e-01  6.6619e-02  4.9189e+01
CIcoeff_3 8.4180e-02  -6.7154e-01  2.2867e-02  1.0341e+02
```

**Comment by ye-luo** [comment]
FYI:
#2947 checked in wrong code in the optimization part but I made a fix #3031
Last night tests show passing 
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-H4-opt-OneShiftOnly-16-1&date=2021-05-13

**Comment by markdewing** [comment]
Usually the first CIcoeff is okay but the others are not (that effect doesn't show in the results I pasted).   It looks like the H4_ae test only uses and checks one coefficient.   Also that test uses CSF's, and there is a separate code path for CSF's and bare determinants.   I can reproduce the problem with C2_pp on the latest code.

**Comment by markdewing** [comment]
If I modify the H4_ae example with an extra CSF/deteminant, it works for CSF's, but fails if they are determinants.

**Comment by markdewing** [comment]
The problem is `q0` and `v` are declared at the wrong scope, so they don't get reset to zero appropriately.   This is in `evaluateDerivatives` in MultiSlaterDeterminantFast.cpp.   It does not affect the usingCSF branch of the if-statement, hence the issue only shows up for bare determinants.

```
       else
       { //usingDETS
-        ValueType q0 = 0.0;
-        std::vector<ValueType> v(Dets.size());
         for (size_t i = 1; i < C->size(); i++)
         {
           int kk = myVars->where(i - 1);
           if (kk < 0)
             continue;
+          std::vector<ValueType> v(Dets.size());
+          ValueType q0 = 0.0;
           for (size_t id = 0; id < Dets.size(); id++)
           {
```

**Comment by shivupa** [comment]
Shoot sorry about introducing this!
