### ISSUE TITLE
Support latest Sphinx-contrib BibTeX 2.x

### ISSUE THREAD

**Issue by naromero77** [QMCPACK/qmcpack#3176]
**Is your feature request related to a problem? Please describe.**
QMCPACK documentation will not build with Sphinx-contrib BibTeX 2.2 which is the latest version you get if you do a `pip` install of it.

```
Running Sphinx v4.0.1
loading pickled environment... failed
failed: You must configure the bibtex_bibfiles setting

Extension error:
You must configure the bibtex_bibfiles setting
make: *** [html] Error 2
```

**Describe the solution you'd like**
Best solution would be to modify `conf.py` to support latest version of Sphinx-contrib BibTeX. But it does not seem like this is the complete soution. I tried to fix the problem with the diff below. I was able to get `make html` to succeed, but could not manage to make the BibTeX references materialize in the actual html.
```
naromero-laptop:docs naromero$ git diff
diff --git a/docs/conf.py b/docs/conf.py
index 1e1de2e7a..14ea5111d 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -36,6 +36,15 @@ sys.path.append(os.path.abspath('extensions'))
 import sphinx_rtd_theme
 
 extensions = ['sphinxcontrib.bibtex', "sphinx_rtd_theme"]
+bibtex_bibfiles = ['bibs/LCAO.bib', 'bibs/additional_tools.bib',
+                   'bibs/afqmc.bib', 'bibs/design_features.bib',
+                   'bibs/developing.bib', 'bibs/features.bib',
+                   'bibs/hamiltonianobservable.bib',
+                   'bibs/intro_wavefunction.bib',
+                   'bibs/introduction.bib', 'bibs/lab_excited.bib',
+                   'bibs/labs_qmc_basics.bib', 'bibs/methods.bib',
+                   'bibs/running.bib', 'bibs/sCI.bib',
+                   'bibs/simulationcell.bib', 'bibs/spin-orbit.bib']
 
 numfig = True
 

```

A quick google search shows that many people have this issue because 2.0 is not backwards compatible.

**Describe alternatives you've considered**
The `requirements.txt` does say:
```
sphinxcontrib-bibtex<2.0
```

but there is nothing that locks the version down or even throws a warning to a contributor.

**Comment by prckent** [comment]
Closed by #3179
