### ISSUE TITLE
Include APP_ABORT() if reduced basis in LatticeAnalyzer is not found.

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#318]
This is in reference to Pull request #317 .  Currently, the number of iterations allowed for the reduced basis search is set to some hard coded maxIter in a for loop.  The following should be included after the for loop: 
 APP_ABORT("Reduced basis not found in allowed number of iterations.  Check unit cell or contact a developer") .  However, inclusion of this line and appropriate headers in LatticeAnalyzer.h introduces some linker errors when building the test_lattice unit test.  Inclusion of APP_ABORT() and resolution of linker errors in test_lattice definitely needed.

**Comment by ye-luo** [comment]
I think this due to a similar issue that @markdewing encountered before on the unit test of PP. Unit test doesn't like abort.

**Comment by ye-luo** [comment]
throw an execption will be the way out.
