### ISSUE TITLE
How to set targetwalkers with Nexus?

### ISSUE THREAD

**Issue by ichibha** [QMCPACK/qmcpack#3210]
I used Nexus of commit ce4411d1a1d010bea034324affd498ac57ea9dd3.
I designated the target population of walkers by 'walkers' parameter in generate_qmcpack function.
Then, the nexus gave the value for 'walkers' parameter in xml qmcpack input. 
However, qmcpack 3.9.9 did not recognize 'walkers' but it can recognize 'targetwalkers'.
I confirmed that the generate_qmcpack function does not have a parameter likely to set the target population other than 'walkers'.
Therefore, I think this is a bug.

Best Regards,
Tomohiro

**Comment by jtkrogel** [comment]
@ichibha Please provide your Nexus input here, as well as the generated QMCPACK input file along with the desired one.
