### ISSUE TITLE
Needs CPU mixed precision check in CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#323]
CPU mixed precision complex build is a good candidate to expose most issues.

**Comment by prckent** [comment]
@grahamlopez I'll be updating the builds on oxygen in the next few days, so there will be something to copy.

**Comment by grahamlopez** [comment]
@ye-luo, @prckent Sounds good. I've added this to my todo list.

**Comment by prckent** [comment]
In fact we are already testing mixed precision on oxygen. The setup is in tests/test_automation/nightly_ornl_oxygen.sh . The key is -DQMC_MIXED_PRECISION=1

**Comment by prckent** [comment]
I am adding full precision CUDA real and complex builds to the tests run on oxygen.

**Comment by grahamlopez** [comment]
closed by #363
