### ISSUE TITLE
substeps definition is not logical and should be revised

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#3247]
Revising the definition of substeps has been discussed in the past but I could not find an issue, so I am creating this one ahead of a PR.

Substeps are used for Monte Carlo moves during VMC where only the electrons are moved and no energy or other observable quantities are computed. The main use is to more cheaply decorrelate the runs than measuring at every Monte Carlo step.

The historic definition of substeps is howevever potentially confusing: if substeps is one, no "no energy measurement" steps are taken. If substeps is two, each step in the Monte Carlo where energies are measured is preceded by one "no energy measurement" step. i.e. The count is off by one from what would be logically guessed, with substeps=0 implying the energy is measured at every Monte Carlo step and substeps=1 implying alternating energy/no energy measurement Monte Carlo updates etc.

In the current scheme the total simulation time is conveniently `dt*nblocks*nsteps*nsubsteps`, while in the more logical scheme it would be `dt*nblocks*nsteps*(1+nsubsteps)`.

While this is strictly a not backwards compatible change, it is a safe to make change since any old inputs would do an extra substep and produce more decorrelated output.

I propose to update the drivers and all the inputs to address this. By my current count it involves changes to at least 534 files which is why this change likely has not been made previously.

**Comment by ye-luo** [comment]
One step contains N substeps. Each sub-step moves every electron once.
An energy measurement is performed after the last sub-step but within the step. nsubsteps=0 means no random walking.

So substep doesn't mean with/without "energy measumrent" but means random walking only.
Energy masuremtn is part of the step and has nothing to do with substep.
So we should update the doc to remove confusion. N+1 is ill defined to me.

This the same logic applies to steps in a block.
Each block contains N steps and I/O is done after the last step.
"doing I/O at the last step" is also technically incorrect.

**Comment by PDoakORNL** [comment]
If the default substeps is 1 and we supress output of it for 1 I'm fine with this.  I think nsubsteps=0 should be an input exception.

**Comment by prckent** [comment]
After thinking over the weekend, I may have a better suggestion. Will comment sometime in the future. Interested in  suggestions from everyone else of course - I am keen to make a change towards less ambiguous inputs but it certainly doesn't have to be #3259.
