### ISSUE TITLE
LMY engine MPI interface in formic/utils fails to compile due to missing C++ MPI wrappers

### ISSUE THREAD

**Issue by atillack** [QMCPACK/qmcpack#326]
I am getting multiple compile failures like these:

In file included from /ccs/home/andreas/codework/QMCPACK_MAIN_DEV/src/formic/utils/numeric.cpp:9:
/ccs/home/andreas/codework/QMCPACK_MAIN_DEV/build_summitdev_cpu_xl/src/formic/utils/mpi_interface.h:66:16: error: use of undeclared identifier 'MPI'
  inline const MPI::Comm & world() {
               ^

The error is due to the mpi_interface.h header using C++ bindings for MPI which have been deprecated for a long time and at least on SummitDev are no longer present at all.

Ironically, the error is triggered now because our C++11 detection that used to fail on SD and switched of the LMY engine now works wonderfully, leaving the LMY code on.

A work-around is to switch off LMY for that scenario (a cmake switch would be nice, but I can live with manually editing CMakeLists.txt)

The real solution is to get rid of the C++ bindings in mpi_interface.h and replace them with the C standard ones which is probably the preferred one as more and more installations will want to use newer MPI versions (w/o C++ bindings).

**Comment by ye-luo** [comment]
You can use -D BUILD_LMYENGINE_INTERFACE=0 to switch off the LMY part instead of editing CMakeLists.txt

**Comment by atillack** [comment]
@ye-luo Thanks, I tried that first, but it gets overwritten in CMakeLists.txt line 191 where it gets set back to 1.

**Comment by ye-luo** [comment]
@atillack It should not be. The command line variable is cached and that overwrite only happen when you don't specify anything.

**Comment by atillack** [comment]
@ye-luo -DBUILD_LMYENGINE_INTERFACE=0 is working now. Maybe my build script didn't update in time.

The issue with the C++ bindings for formic/utils/mpi_interface.h remains though.

**Comment by ye-luo** [comment]
Good. I remember I checked the SoA PR manually on summitdev using the instructions you wrote in the manual and at that time everything was fine.

**Comment by prckent** [comment]
In some months, the MPI interface will be redone to solve this problem. In the interim, disabling the LMYENGINE via -DBUILD_LMYENGINE_INTERFACE=0 is a workaround for incompatible MPI versions. One possibility would be to do a test compile as part of the CMake configuration and disable the incompatible code automatically.

**Comment by atillack** [comment]
Thank you. Using -DBUILD_LMYENGINE_INTERFACE=0 is fine with me.

**Comment by prckent** [comment]
Closed by #432 .

**Comment by ye-luo** [comment]
Is this verified on summitdev since it started there?

**Comment by atillack** [comment]
@ye-luo I can confirm that the code compiles fine on SummitDev - after fixing an unrelated bug preventing the Xl compiler to be detected (line 348 of CMakeLists.txt needed an additional "OR ($ENV{CXX} MATCHES "xlC")").

**Comment by ye-luo** [comment]
@acangi Good. I think is a know issue of the most recent XL compiler that CMake thought it is Clang. IBM folks are looking at it.

**Comment by atillack** [comment]
@ye-luo And of course, after everything compiled fine, linking failed:
../../lib/libformic_utils.a(lapack_interface.cpp.o): In function `formic::dsygv(int, char, char, int, double*, int, double*, int, double*, double*, int, int&)':
/ccs/home/andreas/codework/QMCPACK_MAIN_DEV/src/formic/utils/lapack_interface.cpp:(.text+0x16ac): undefined reference to `dsygv_'
../../lib/libformic_utils.a(lapack_interface.cpp.o): In function `formic::xsygv(int, char, char, int, double*, int, double*, int, double*, double*, int, double*, int&)':
/ccs/home/andreas/codework/QMCPACK_MAIN_DEV/src/formic/utils/lapack_interface.cpp:(.text+0x1754): undefined reference to `dsygv_'
../../lib/libformic_utils.a(lapack_interface.cpp.o): In function `formic::zhegv(int, char, char, int, std::complex<double>*, int, std::complex<double>*, int, double*, std::complex<double>*, int, double*, int&)':
/ccs/home/andreas/codework/QMCPACK_MAIN_DEV/src/formic/utils/lapack_interface.cpp:(.text+0x1828): undefined reference to `zhegv_'
../../lib/libformic_utils.a(lapack_interface.cpp.o): In function `formic::xsygv(int, char, char, int, std::complex<double>*, int, std::complex<double>*, int, double*, std::complex<double>*, int, double*, int&)':
/ccs/home/andreas/codework/QMCPACK_MAIN_DEV/src/formic/utils/lapack_interface.cpp:(.text+0x18e0): undefined reference to `zhegv_'

**Comment by ye-luo** [comment]
Someone probably needs to replace all the blas/lapack interface inside formic libraries and use the QMCPACK one.

**Comment by atillack** [comment]
Well, the funny thing is that these functions should normally be part of lapack -  but apparently not on SD's netlib-lapack. I am willing to let this pass at this point as this may be more of an installation problem.

**Comment by ye-luo** [comment]
I guess they are probably not used at all and we can just remove the interface.

**Comment by prckent** [comment]
No changes should be made to QMCPACK on the basis of summitdev problems until it has been thoroughly determined whether the software on that machine is really to blame. It is very beta.

**Comment by prckent** [comment]
@atillack Presumably an underscore issue or something similar has crept in after the "upgrade". Depending on where your lapack is coming from it is possible that it wasn't built the same way as before.
