### ISSUE TITLE
SoA and CUDA are not yet compatible

### ISSUE THREAD

**Issue by atillack** [QMCPACK/qmcpack#327]
This is just a minor thing: CUDA and SoA enabled can currently be compiled at the same time.

Of course, when this executable is run it will eventually bail with an error that mixing AoS and SoA is not allowed.

We could probably trap that in CMakeLists.txt if necessary.

**Comment by prckent** [comment]
Since the planned evolution of the code involves removal of the AoS code, this issue really identifies the requirement of making an SoA CUDA code. The performance portability timeline is probably too far off to avoid this.

**Comment by prckent** [comment]
Similar to #294 the strategy I suggest we follow is to simply enable SoA with CUDA in the nightlies so that the large number of test failures is visible and we have a reminder that the SoA work is not complete until all those tests are working.  Similarly, the Gaussian basis set code is currently broken in SoA, but the tests are not run. Tests will be reenabled for this soon.

**Comment by prckent** [comment]
This is now caught by the nightly integration testing on oxygen. GCC-CUDA-SoA-Release has 87 failing tests. These will continue to fail until the CUDA driver code is updated appropriately. Someone familiar with SoA will have to help; ideally we will write some SoA developer docs at the same time / update the notes already included.

On the positive side, 56 tests do pass: these look to be most of the unit tests and all the integration tests that do not depend on a jastrow function.

As indicated above, we will use test breakage to warn off users from SoA features that don't work and also to indicate our planned goals of features that will be made to work in the future. e.g.. CUDA with SoA, Gaussians/local basis with SoA.

**Comment by ye-luo** [comment]
GPU Jastrow factor classes are derived class of CPU AoS classes. Probably not much work needed. I will look at it when I have time but low priority at the moment.

**Comment by prckent** [comment]
I am hopeful that it is not much work too. Agree it is low priority.

**Comment by atillack** [comment]
@prckent @ye-luo Thanks and agreed. We could tackle that after the delayed updates as quite likely the exact same areas will be affected.

**Comment by prckent** [comment]
This will be addressed in https://github.com/QMCPACK/qmcpack/issues/861

**Comment by prckent** [comment]
@ye-luo @atillack @PDoakORNL When should we consider this complete? After Peter's #922 J1 and J2 are now working. J3 would be very useful, but is more of an additional feature, the same for observables.  Close this issue?

**Comment by ye-luo** [comment]
I vote close. The left work is part of AoS to SoA transition but has no impact on user side. J3 and Observables should be tracked by individual issues.
