### ISSUE TITLE
Realspace allocators should conform to modern c++ allocator requirements.

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3270]
**The problem and soluition**
In turn OhmmsPETE and other containers should behave in conformance with modern c++ allocator use.

Currently they are sort of C++03. This have frequently violated the priniciple of least surprise at least for me.
OMPallocator is stateful sort of, it doesn't propagate in a sensible way with regards to its device_ptr.

We make a great deal of use of these so its worth having them be high quality.

I can see how to do this without any code above the OhmmsPETE, OhmmsSoA  layer needing changes.  Some code above could be simplified afterwards but will continue to work fine.

**Describe alternatives you've considered**
Don't do anything and continue to have painful week long debugging sessions.

**Comment by ye-luo** [comment]
@PDoakORNL has this been resolved by #3271?

**Comment by PDoakORNL** [comment]
#3271 brings us to a point where we can move forward and makes it apparent that continuing to think about the implications and how we want to deal with dual space data is the more important issue.
