### ISSUE TITLE
SoA code on IBM Power8 hangs

### ISSUE THREAD

**Issue by atillack** [QMCPACK/qmcpack#328]
When I run a CPU SoA enabled build on SummitDev with the NiO S32 benchmark I ran into an infinite loop.

Things run through without looping infinitely when I comment out line 270 (#pragma omg parallel) in QMCDrivers/DMC/DMComp.cpp. In older versions of the code, some #pragma omp's used to not be used when BGP_BUG (BlueGene Power?) was set.

**Comment by ye-luo** [comment]
If your AoS is correct, this line is correct. BGP is BlueGene P before Q. No more exist.

**Comment by atillack** [comment]
@ye-luo I am sorry for the confusion, I need that coffee - what I meant (I will edit my post) is that with line 270 as-is (#pragma omg parallel) I get an infinite loop on SummitDev, with it commented out everything runs fine.

**Comment by atillack** [comment]
@ye-luo The comment was to help establish that in this corner of the code with SoA on (without SoA things run smoothly too) some things are not OMP safe.

The BGP_BUG thing was what made me test commenting out #pragma omg parallel's and then narrow it down to which one gives me the infinite loop here. Interestingly, line 270 in no older version of the code I have uses the BGP_BUG define.

**Comment by prckent** [comment]
Sketchy? https://github.com/QMCPACK/qmcpack/blob/38050ba2aa6b2977baebf520de2c14f7a9750811/src/QMCDrivers/DMC/DMCOMP.cpp#L289

The two #omp pragmas in this area don't seem to be correct here. In the outer region we are doing manual threading based on the thread #, but then inside there is a loop over *all* nw walkers with no guards.

**Comment by ye-luo** [comment]
In the inner loop, we have the Movers[ip] (line 293) with dedicated memory space. The breakup of omp parallel and omp for is on purpose. It looks correct.

**Comment by atillack** [comment]
@prckent Also, this code works fine without ENABLE_SOA=1.

**Comment by prckent** [comment]
Missed the [ip]

**Comment by naromero77** [comment]
Just a bit of history. Anouar and Jeongnim worked on the original BG/P port of QMCPACK. The OpenMP in the BG/P C++ was awful. If this is just a main stream Power compiler C++ it might be better. Unfortunately, after 10 years of using IBM compilers -- my impression is not good. I am willing to help debug this, but it may just be a compiler bug. From reading this issue, it does not even look like GPUs were involved?

**Comment by atillack** [comment]
@naromero77 Thanks! It seems that the problem went away and likely it was the BLAS library breaking things (although that could also be compiler dependent). I will update our build recipes once I am fully convinced.

**Comment by prckent** [comment]
I think we can close this as a vendor bug or SummitDev quirk. @atillack  reports completed runs for NiO with both SoA and AoS compilations on Summit, albeit initially with gcc+MAGMA. No one has reported a hang on other systems.

@atillack : Close?

**Comment by atillack** [comment]
@prckent Yes, I vote to close since this apparently wasn't our bug to begin with.
