### ISSUE TITLE
legacy CUDA not check return status enough.

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3280]
**Describe the bug**
gpu_vector.h gpu_vector.cpp doesn't check return status of call to CUDA runtime APIs. It causes failures with inaccurate message.
Can use macros from CUDA/cudaError.h.

**Comment by prckent** [comment]
I agree with the title! A much more pervasive issue than just gpu_vector but excellent place to start given the wide use of gpu_vector.

**Comment by ye-luo** [comment]
Legacy CUDA has been removed from the code base https://github.com/QMCPACK/qmcpack/pull/4431
