### ISSUE TITLE
Running qmcfinitesize on Summit

### ISSUE THREAD

**Issue by krongch2** [QMCPACK/qmcpack#3285]
I want to calculate the energy corrections from the existing structure factor files (`stat.h5`) using `qmcfinitesize`. But, I'm not sure what's the correct way to run this executable on Summit. Using `jsrun -n 1 -r 1 -c 1 -g 0 -a 7 qmcfinitesize dmc.g000.twistnum_0.in.xml --hdf5 dmc.g000.s001.stat.h5` (see attached `dmc0.02/finite.bsub.in`) results in this error: 

`SkParserHDF5::parse could not open dmc.g000.s001.stat.h5` (see attached `dmc0.02/finite.out`)

I also tried `-a 1`  instead of `-a 7` in the `jsrun` command, and this is what I got:
`ERROR:  One or more process (first noticed rank 0) terminated with signal 11 (core dumped)`

So, I was wondering how to correctly use `qmcfinitesize`. I compiled it simply by executing `./config/build_olcf_summit.sh` from `v3.11.0`

Thank you!

[test_finite.tar.gz](https://github.com/QMCPACK/qmcpack/files/6794264/test_finite.tar.gz)

**Comment by prckent** [comment]
Is qmcfinitesize working for you elsewhere?

**Comment by krongch2** [comment]
No. I haven't tried it on any other machine yet.

**Comment by krongch2** [comment]
The error has nothing to do with the machine but my input file. Thanks to @kkly1995 who pointed out, the segfault results from me using `name="SkAll"` and not `name="skall"`. This is surprising because the manual suggested using name="SkAll". But `qmcfinitesize` wants `name="skall"`. I was wondering if either of the two could be updated to match the other.
