### ISSUE TITLE
ppconvert is hanging and breaks nightlies

### ISSUE THREAD

**Issue by correaa** [QMCPACK/qmcpack#3303]
**Describe the bug**

In my CI compilation and test execution I see `convertpp` broke, it generates nans.

I think it is with this commit

```
Git branch: develop
Git commit hash: 47285714a06bed3046119b7ab65ef4641f201310
```

**To Reproduce**

Run the following recipe in debian system:

```
    - apt-get -qq update && apt-get -qq install --no-install-recommends -y libblas-dev liblapack-dev libfftw3-dev libboost-serialization-dev libopenmpi-dev gfortran g++ pkg-config cmake make git ca-certificates numdiff python3 python3-numpy python3-h5py python3-mpi4py python3-scipy libxml2-dev libhdf5-dev
    - git clone https://github.com/QMCPACK/qmcpack.git
    - cd qmcpack
    - cd build
    - cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS="--allow-run-as-root;--bind-to;none" ..
    - make ppconvert afqmc test_afqmc_matrix test_afqmc_numerics test_afqmc_slaterdeterminantoperations test_afqmc_walkers test_afqmc_hamiltonians test_afqmc_hamiltonian_operations test_afqmc_phmsd test_afqmc_wfn_factory test_afqmc_prop_factory test_afqmc_estimators qmc-afqmc-performance
    - ctest -R ppconvert --output-on-failure
```

This is the output 

```
$ ctest -R ppconvert --output-on-failure[0;m
Test project /builds/correaa/boost-multi/qmcpack/build
    Start 24: ppconvert_runs
1/2 Test #24: ppconvert_runs ...................   Passed   11.24 sec
    Start 25: ppconvert_o_diff
2/2 Test #25: ppconvert_o_diff .................***Failed    0.24 sec
----------------
##6701    #:1   <== -nan
##6701    #:1   ==> -4.63469388240121e-20
@                                                     @@
##6701    #:2   <== -nan
##6701    #:2   ==> 1.06342318361146e-03
...
```

**Expected behavior**

Test should succeed

**System:**
 - gitlab CI, debian testing

**Comment by ye-luo** [comment]
please verify the commit hash. I cannot find it.
what is the compiler?

**Comment by ye-luo** [comment]
Saw more traces. https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=227437

**Comment by correaa** [comment]
This is what cmake reports,

```
-- Ready to build qmcpack
sed supports -E
Git branch: develop
Git commit hash: 1164337ec154d68779a79b39dd3c6c5c71f707fc
Building AFQMC performance executable 
```

more details here: https://gitlab.com/correaa/boost-multi/-/jobs/1445192969

**Comment by correaa** [comment]
> Saw more traces. https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=227437

So, the problem is real and introduced recently?

**Comment by prckent** [comment]
Are you able to git bisect this issue?

One possibility is some changed compiler flags tripping this. I don't recall any touches to actual ppconvert source code in the last few days. ppconvert is not clean code - there are some historical cmake compiler flag overrides that when I checked a few weeks back turned out to be necessary. The code definitely appears to make use of uninitialized memory.

<img width="798" alt="Screen Shot 2021-07-22 at 1 48 27 PM" src="https://user-images.githubusercontent.com/13683814/126685251-a7fd4135-f7a7-4c22-983f-0b35080153f4.png">

**Comment by correaa** [comment]
It is worst, with nvcc `convertpp_run` test times out. https://gitlab.com/correaa/boost-multi/-/jobs/1445432787#L1768

**Comment by prckent** [comment]
Changed the title and added the bug tag - this is a serious problem. ppconvert is hanging or getting stuck in an infinite loop.

**Comment by correaa** [comment]
Given the timeframe perhaps it is caused by #3300 or #3302. I don't know why though.
