### ISSUE TITLE
Forces with Ceperley-Chiesa-Zhang Estimator are Broken  

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#331]
Summary:  the VMC electron-ion forces computed using CCZ estimator in the main branch differ from a.) VMC finite difference, b.) PBE forces (order of magnitude estimates only), c.) the old production force code used in the H+He benchmarking paper.  Currently testing to make sure that this is not the same issue reported by Mark and Paul in Issue #207.  My test system was an r_s=1.8837 2x2x2 tiling of an fcc primitive lithium cell, with a perturbed ion coordinate. 

CELL_PARAMETERS {alat}
6.95218  6.95219 0.00000
0.00000 6.95218  6.95219
6.95218  0.00000 6.95219

ATOMIC_POSITIONS {crystal}
Li 0.1000 0.0300 0.0500
Li 0.5000 0.0000 0.0000
Li 0.0000 0.5000 0.0000
Li 0.5000 0.5000 0.0000
Li 0.0000 0.0000 0.5000
Li 0.0000 0.5000 0.5000
Li 0.5000 0.5000 0.5000

Considering F_eI on atom 0, x-component:  
PBE = 0.3870421
VMC_OLD = 0.383 +/- 0.036
VMC_CURRENT = 0.119 +/- 0.024
DIFF(VMC_CURRENT-VMC_OLD) = -6.101(sigma)

**Comment by rcclay** [comment]
Just double checked to make sure I was using a synced version of QMCPACK.  This issue is definitely distinct from #207.

**Comment by prckent** [comment]
Tracking down the last known working version (svn, git) would be very helpful.

**Comment by rcclay** [comment]
The version that I know works is SVN rev #6361, although its uncertain whether this was correctly synced with the main branch (research code from 3 years ago).  Right now, suspicions are 1.) its not an openMP issue, since I get the same numbers regardless of how many openMP threads I use, and 2.) something is up with the e-I force computation or accumulation, since the I-I contribution is calculated correctly.  Interestingly, if you look at the estimated force magnitudes |F| between the old code and new code, the new code seems to have |F_new|<|F_old| when the difference is statistically significant.  I'll hunt this down like a dog.

**Comment by prckent** [comment]
Thanks Ray. Hopefully this is simple. 

Another reason for more tests to help catch this kind of breakage early.
