### ISSUE TITLE
Test Naming Doesn't Follow industry conventions

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3318]
Here I try to condense the agreed definitions of these test types, look them up on wikipedia or one of the 
many software engineering how to sites on the internet.

**Unit testing** - tests individual modules of code, generally at the class level. At its strictest level everything should be mocked except the tested unit and methods should be tested one at a time against both typical input as well as error and exception conditions. Dependencies through should be minimized though, this has the additional advantage limiting intermodule entanglement.
 
**Integration Testing** - tests the interaction of multiple modules of code, but not the _whole application._ i.e. custom allocators + custom containers. The modules whose integration is being tested should be clearly defined. 

These two can categories can be somewhat elastic for instance to test of integration between objects compiled in the the same "module" are of still considered unit tests, InputObject + ComputeObject. 

**Functional or Systems testing** - tests of the complete application using the applications user facing control structure to verify a user facing documented feature.

What I want is to able to call an integration test what it is and see unit tests with fewer dependencies.

**Comment by ye-luo** [comment]
I don't think we can draw a fine line between unit test and integration tests. To me the boundary is not clear. Some template class cannot be tested without pulling from another module. So I don't feel the necessity to distinguish unit and Integration tests.

Unless there is a clear benefit making a new category, we'd better not to introduce it in order to reduce burden and confusion.

**Comment by markdewing** [comment]
What we consider a "module" for integration testing needs to be defined.  Is each separate directory a module? Each library (.a)?   Much of the discussion online for unit vs integration seems to use "external" vs. "internal" - as in code the developers control vs. code they do not.

I think that defining "module" as source directory is too fine grained - almost all of our unit tests become integration tests by that definition.  Industrial standards also deal with how to scale up a project with respect to project size and multiple teams.   I don't think we have that issue.

For example, the ParticleSet class is used in many tests and the boilerplate for setting it up is one contributor to their length.   Creating a mock would probably not be that useful.  But an interface and helper functions that make setup easier and more compact would be very helpful.

External dependencies might be BLAS/LAPACK libraries, CUDA, OMP offload, MPI.  Or we might consider things like environments that have separate memory spaces for host and device.

**Comment by PDoakORNL** [comment]
I don't want to die on this hill, but I think the fact the line is completely blurred is an issue in the code base is a side effect of the poor separation of concerns in the design. In a layered design its not uncommon to have layers that can only be unit tested with some dependent (often in the same module) code included. Generally if they are within the same module and/or build only on a obligatory linkage to a "lower level" module its easiest to still consider them unit tests.

But sometimes its quite clear its not a unit test. The containers can be "completely" unit tested without recourse to the dual allocators. I'd like to reserve the term integration tests for tests that use a well specified subset of the system components to test for specific problematic integrations between modules. Ideally these wouldn't be driven by input files and the checks would not be against the output files of the application.

As far as the system/functional tests in the qmcpack/tests I don't think we should call them integration tests, I have always found that confusing. They only are in the broadest possible definition of such.  They're functional/feature tests conducted with the production application. Other than "integration" they are named exactly like this. I don't minimize their importance they're the assurance we're delivering what we say we are. 

But they are slow enough and untargetted enough that they aren't that useful in the write, compile, debug, refactor loop, and they require standard input files. There is no way to test corner cases that the input system doesn't currently produce. I think they've encouraged a lot of abuse of the input system since if you are relying on one of these to develop its tempting to bring the input into the local code you are working on.

**Comment by PDoakORNL** [comment]
ParticleSet is an interesting issue. It leads to tons of functions being difficult to analyze, they should take a container of r's or whatever but instead take a ParticleSet and even worse putting their output into that Particleset. It carries surprising state. And yes it makes tons of unit tests into integration tests.

**Comment by ye-luo** [comment]
We generally have two categories "Unit testing + Integration Testing" we tell users "unit tests", then simulation runs under "tests" for"systems testing".

The first category is for quick development (developer view)
The second category is for checking from scientific perspective (user view)

Adding new category does add more testing variants. That is my main concern and would like to minimize test categories.

Improving internal structure of the code is clearly a non-stop effort.

As a developer, I don't think it is necessary and will be annoyed looking for Containter<std::alloctor> in one place and Containter<DualAlloctor> in another place. We might need to split the test binary to reduce the dependency when testing the former. I think the decision can be made case by case if there is real gain by doing this.

**Comment by PDoakORNL** [comment]
My intention is that the integration tests always run with the unit tests, i.e. they are in your first category. They do not add more variants.  In fact one reason to have them is to reduce testing variants. For instance in test_dual_allocators_ohms_containers.cpp and test_TrialWaveFunction_diamondC_2x1x1.cpp I make effort to test all the integrations that can be build and run with the particular build switches. The tests are  fast and for those integrations I don't need to build and then test multiple times.

BTW TrialWaveFunction_diamondC_2x1x1.cpp is obviously an integration test and not a unit test by any definition.

**Comment by PDoakORNL** [comment]
I'm partially motivated by the desire to be able to demand someone write or refactor code to allow actual unit tests to be written.  Many PR's and modules have only integration tests.

**Comment by prckent** [comment]
At the moment we tell users to either ctest -L unit or ctest -L deterministic. Many, perhaps most, of our unit tests have to cover more than a single code unit due to history. The deterministic label is then used to label the superset that covers all our non-statistical integration tests and units tests. This is simple to tell users and also simple for dashboard reporting.

What are the proposed changes to ctest lines and test labeling? As developers we can call things whatever we find useful, and preferably use common standards, but we do need to be able to maintain simple instructions for users.

**Comment by PDoakORNL** [comment]
I don't propose to change the labeling and we have a agreement on lower dependency test to support specific integration tests.  I will just label them unit tests.

**Comment by prckent** [comment]
It is still true that most of our "unit" tests are integration tests.
