### ISSUE TITLE
long-diamondC_1x1x1_pp-dmc_sdj-1-16-totenergy test issue

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#334]
This long test is failing too frequently.
https://cdash.qmcpack.org/CDash/testDetails.php?test=733304&build=10360
The reference error bar seems not consistent with the measured value.

Intel2017-Release
```
Test output

Tests for series 1
  Testing quantity: LocalEnergy
    reference mean value     : -10.53158300
    reference error bar      :   0.00081500
    computed  mean value     : -10.52900539
    computed  error bar      :   0.00241660
    pass tolerance           :   0.00244500  (  3.00000000 sigma)
    deviation from reference :   0.00257761  (  3.16270863 sigma)
    error bar of deviation   :   0.00255033
    significance probability :   0.99843678  (gaussian statistics)
    status of this test      :   fail

Test status: fail
```
Intel2017-Complex-Release
```

Test output

Tests for series 1
  Testing quantity: LocalEnergy
    reference mean value     : -10.53158300
    reference error bar      :   0.00081500
    computed  mean value     : -10.53472250
    computed  error bar      :   0.00258898
    pass tolerance           :   0.00244500  (  3.00000000 sigma)
    deviation from reference :  -0.00313950  ( -3.85214873 sigma)
    error bar of deviation   :   0.00271423
    significance probability :   0.99988287  (gaussian statistics)
    status of this test      :   fail

Test status: fail
```

**Comment by jtkrogel** [comment]
Is this evidence of a poorly constructed test, a weak bug introduced some time after the reference was created, or a weak bug fixed in the reference implementation that is now apparent?

**Comment by ye-luo** [comment]
I feel it is evidence of a poorly constructed test. The number of samples was reduced to 1/10 but the reference value was not updated.

**Comment by jtkrogel** [comment]
The reference value should not be updated.  Generally the reference should be run to a precision far greater than the intended test and then the "reference error bar" should be changed to match the expected error bar of the target test (as determined by the average error bar of multiple runs of the target test length).

**Comment by jtkrogel** [comment]
Was the reference error bar just not updated to match the test?  Do we need to do a longer run to confirm we still definitely match the reference?

**Comment by prckent** [comment]
@jtkrogel Beat me to it. The reference value should not be updated and for *many but not all* of the tests comes from an even longer run than the long runs.

**Comment by prckent** [comment]
For sure we need a longer run here to check the reference values. There might be a record in the ctest definition or in the directories with the test files.

I agree that this test is failing too often. Note that we only run it weekly on oxygen.

**Comment by prckent** [comment]
Note that the reference energy should be exactly the same as for the short test. Only the error bar should be different. Our short tests are still meant to be long enough that they are equilibrated and are properly sampling the ground state.

**Comment by ye-luo** [comment]
Sorry, I mean the reference error bar needs to be updated and no changes to others.

**Comment by prckent** [comment]
Per cdash, since 1 June this long test (all builds) has failed  37.5% of the time. We are only running the Intel2017 variants. The real and complex versions are both bad.
