### ISSUE TITLE
J2 Offload fails test_wavefunction_trial on Summit and standalone P9 + V100

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3345]
**Describe the bug**
```shell
ctest -R 'unit.*trial' -V
...
   Added a fermionic WaveFunctionComponent SlaterDet
24: evalGrad 14.772495269775 -20.385232925415 4.852952003479 47.387710571289 -63.361122131348 15.318325042725
24: CUDA error: Error when synchronizing stream. stream = 0x000000004b881110, async info ptr = 0x00007fffc55f3e88
24: CUDA error: an illegal memory access was encountered
24: Libomptarget error: Failed to synchronize device.
24: Libomptarget error: Call to targetDataEnd failed, abort target.
24: Libomptarget error: Failed to process data after launching the kernel.
24: Libomptarget error: Run with LIBOMPTARGET_DEBUG=4 to dump host-target pointer mappings.
24: Libomptarget error: Source location information not present. Compile with -g or -gline-tables-only.
24: Libomptarget fatal error 1: failure of target construct while offloading is mandatory
24:
24: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
24: test_wavefunction_trialwf is a Catch v2.13.6 host application.
24: Run with -? for options
24:
24: -------------------------------------------------------------------------------
24: TrialWaveFunction_diamondC_1x1x1
24: -------------------------------------------------------------------------------
24: ../src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp:38
24: ...............................................................................
24:
24: ../src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp:38: FAILED:
24:   {Unknown expression after the reported line}
24: due to a fatal error condition:
24:   SIGABRT - Abort (abnormal termination) signal
24:
24: ===============================================================================
24: test cases:  1 |  0 passed | 1 failed
24: assertions: 19 | 18 passed | 1 failed
24:
```
cuda-gdb reports somewhat different issue
```shell
jsrun -n1 -a1 -g1 -c1 --stdin 0 cuda-gdb ../bin/test_wavefunction_trialwf
...
CUDA Exception: Warp Illegal Address

Thread 1 "test_wavefuncti" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 138, block (0,0,0), thread (0,0,0), device 0, sm 0, warp 1, lane 0]
0x0000000011e13310 in __omp_outlined__1_wrapper ()
```

**To Reproduce**
1. develop e2a5f2eece7c2c9956c89560d219bcae70acff86
2. on summit use the config/build_olcf_summit_Clang.sh
3. start an interactive session
```shell
LSB_GPU_NEW_SYNTAX=Y bsub -W 2:00 -nnodes 2 -gpu "num=12:j_exclusive=yes" -P mat151 -Is /bin/bash
```
4. cd to any offload build
5. ctest -R 'unit.*trial' -V

**Expected behavior**
No illegal address, synchronization failure or whatever

**System:**
summit
modules:
Currently Loaded Modules:
  1) gcc/8.1.1                        5) cuda/10.1.243         9) python/3.6.6-anaconda3-5.3.0
  2) spectrum-mpi/10.3.1.2-20200121   6) essl/6.1.0-2         10) llvm/master-latest
  3) cmake/3.20.2                     7) netlib-lapack/3.8.0
  4) git/2.20.1                       8) hdf5/1.10.4
Also with module load llvm/main-20210112
On leconte with llvm 12

 - other systems where this is reproducible [e.g. "my laptop", "none"]
leconte

**Additional context**

**Comment by ye-luo** [comment]
Please use llvm/main-20210724 module on Summit. On epyc-server, I can reproduce the error with main-20210112.

**Comment by PDoakORNL** [comment]
How difficult would it be to base this build on gcc/9.1.0 or gcc/9.3.0, the stdlibc++ 8.1.0 is outside of our 2 year support and has experimental std::filesystem support and no support for polymorphic memory resources.

**Comment by prckent** [comment]
For offload only very very recent compilers are (barely) working - LLVM develop and the vendor LLVM-derived ones to a limited degree. Does the problem reappear with the latest LLVM develop or the module Ye put?

**Comment by PDoakORNL** [comment]
I saw no regression with 69a909b9fefeec5d4ece6f3162f8332f125ea202 main, a commit from this morning to main.  However @ye-luo mentioned a bug in main with complex reductions in omp target which is still waiting for a patch. From that I would optimistically say this bug is fixed by c7e69e46c86c3f3785441de45db4b7bc6d26e321 and remains fixed.

**Comment by PDoakORNL** [comment]
I can confirm that by the c7e69e46c86c3f3785441de45db4b7bc6d26e321 commit to main this issue is fixed.

**Comment by ye-luo** [comment]
I picked 8.1.1 on Summit due to some missing library QMCPACK dependents and I didn't want to fight with lmod. On x86, I'm using GCC9. So feel free to use libstdc++ from gcc9 on the machine you have control. On Summit, I may have to recompile the compiler anyway after the OS upgrade next week.

**Comment by ye-luo** [comment]
Actually is C++17 happy with c7e69e46c86c3f3785441de45db4b7bc6d26e321 ?

**Comment by PDoakORNL** [comment]
It is on leconte, I'll see on summit.

**Comment by PDoakORNL** [comment]
Summit is also fine with c7e69... and c++17

**Comment by PDoakORNL** [comment]
I don't see a regression on this issue with the llvm main as of two days agao.

**Comment by ye-luo** [comment]
@PDoakORNL shall we close this one?

**Comment by PDoakORNL** [comment]
Compiler bug working version found, patched in main, tests will bomb if there is a regression.
