### ISSUE TITLE
Use git-lfs or similar for binary files.

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3354]
We have binary files for the performance testing and regression testing for hdf5 they should integrate with the repo actually being stored in it.

If you are not aware storing binary files in git is both not useful and harmful to repo performance and size in the long term.

**Describe the solution you'd like**
Decide on a git extension to use which will 
1. Allow binaries to be easily tracked along with the source code.
2. Be accessible to all users as easily as using the github repo.
3. Be available for all platforms the code is actually developed and run on. (so maybe not windows)

**Describe alternatives you've considered**
git-lfs, git-annex

**Comment by markdewing** [comment]
Would a separate (normal) github repo for these binary files be feasible?  It still has the problems of repo performance and size, but at least it's contained to a separate repository.

**Comment by PDoakORNL** [comment]
I have heard about projects doing this and dealing with that "binary" repo as a submodule. The plus is no git extension needed, the minus is its more laborious when files are updated.  Over time this definitely could have more effect on the CI, if it needed to clone this repo, if it didn't this might be better than lfs we'd need to try them both I think.

**Comment by ye-luo** [comment]
1. submodule can be tricky if someone download tarball instead of git clone source code.
2. prefer store all unit tests related files in the repo instead of requiring accessing the internet.
3. We have some unit tests enabled only when QMC_DATA has the necessary files.
4. Performance tests already require QMC_DATA to hand in large files.
5. Users need to learn how to make shallow clone.

I'm not familar with git-lfs. I prefer limited use of github services.

>    Allow binaries to be easily tracked along with the source code.
If we keep these small files in the repo. We already have this feature.
>    Be accessible to all users as easily as using the github repo.
If we keep these small files in the repo. We already have this feature.
>    Be available for all platforms the code is actually developed and run on. (so maybe not windows)
Not understanding this point. could you explain more?

**Comment by prckent** [comment]
We are not using or going to use LFS. Too many usability issues, potential costs, and general headaches.

**Comment by PDoakORNL** [comment]
I have not had previous experience with git-lfs or git-annex so I was wondering if they were workable solutions.

I was just worried about repo growth and missing tests that may require sizeable binary data. Seems like a solution is incoming so I will hold tight and not object to small binaries included in tests. Seems like this issue can be closed.

**Comment by williamfgc** [comment]
My experience with git-lfs is the same as @prckent when mixing source and data repos . With enough storage (in a separate repo) git-lfs is yet another nice frontend powered by https or ssh with the benefits of git versioning without making large copies for every change. There is also [git-ftp](https://github.com/git-ftp/git-ftp), but I never used it. In any case, CMake has: [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html) for build time fetch, [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) at configure time. I used [ExternalData](https://blog.kitware.com/cmake-externaldata-using-large-files-with-distributed-version-control/) when contributing to VTK and the workflow is a bit more complex. I'd fetch outside `build` so several build configurations can see the same data. Good topic.

**Comment by PDoakORNL** [comment]
It's starting to sound to me like cmake FetchContent might be the best way to deal with large(r) test files if we have some consistent place to host them that doesn't require users logging in or clicking through a bunch of browser pages.

**Comment by prckent** [comment]
Hosting is the major problem. We are using box.com for the QMC_DATA files but it is awkward. If we solve the hosting problem, we also must ensure that any fetching is not required. e.g. for offline install or to keep space use low in a VM.

**Comment by prckent** [comment]
This seems closable. Revisit as needed.
