### ISSUE TITLE
Replace alcf-gnu-warning-as-error with github action

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3360]
**Is your feature request related to a problem? Please describe.**
Getting latest compiler on ALCF CI instance is quite involving.  

**Describe the solution you'd like**
replace it with github-action.

**Additional context**
Remain as not required for PR approval

**Comment by williamfgc** [comment]
@ye-luo should I just reuse the current [docker container configuration](https://github.com/QMCPACK/qmcpack/blob/develop/config/docker/dependencies/ubuntu/openmpi/Dockerfile) for a CI check on a vanilla Ubuntu 20.04 (with gcc 9) environment with `-Werror`, or are we looking for the latest gcc compiler [11.2](https://gcc.gnu.org/releases.html) ?

**Comment by ye-luo** [comment]
-Wsuggest-override needs > 9.2
A low effort solution is desired when you make the docker configuration.
If you can find gcc 11.2 available that is great. If you don't, it is *not* worth compiling one.
My ubuntu 20.4 shows gcc-10 available. It can be used as a backup plan.

**Comment by ye-luo** [comment]
Don't turn on MPI.

**Comment by prckent** [comment]
Since recent compilers have significantly improved their error and warning messages, a low effort solution to (say) gcc 11.2 would be ideal

**Comment by williamfgc** [comment]
@ye-luo @prckent thanks for the input. gcc 11.2 is the default on a recent (22 days ago) Ubuntu 21.10 (Impish Indri) [image](https://hub.docker.com/layers/ubuntu/library/ubuntu/impish-20210722/images/sha256-993294f9f183ba17a61857e31f589ddcda0e8f9636fc12d8fd34922f24539c36?context=explore). I'm evaluating it locally and so far it's low effort. We can try that environment, thoughts?

**Comment by williamfgc** [comment]
Surprisingly, there is a bug when building with gcc-11  #3364 .

**Comment by williamfgc** [comment]
...and runtime errors reported in #3366

**Comment by williamfgc** [comment]
After #3367 gets merged I don't see any issues with the deterministic tests on the [container using Ubuntu 21+gcc 11](https://hub.docker.com/layers/163089210/williamfgc/qmcpack-ci/ubuntu2110-serial/images/sha256-a81d5d12500545b134b5cedc3218cfd4911f7996ff7b29cb3c595f891afb80c6?context=repo). It would add two more jobs (complex/real) to the current initial CI, which is taking 1 hour on average. Let me know what you think, I can always offload some checks (ubsan?) to a scheduled "cron" job as the trade-off to avoid a slow CI workflow.

**Comment by prckent** [comment]
Lets watch it for a week or two and see what the slow step is.

**Comment by williamfgc** [comment]
It looks like adding those two extra jobs (in parallel) hasn't slowed down CI. Checks have been running consistently for [~ 1 hr](https://github.com/QMCPACK/qmcpack/actions/workflows/ci-github-actions.yaml).
