### ISSUE TITLE
Deterministic tests failing with Ubuntu21.10+gcc11+python3-h5py-serial2.10.0

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#3366]
**Describe the bug**
Bugs related to unsupported types read by Nexus using h5py 2.10.  
`"<class 'h5py._debian_h5py_serial._hl.dataset.Dataset'>"` and `"<class 'h5py._debian_h5py_serial._hl.group.Group'>"`

**To Reproduce**

1. `develop`
2. `cmake -GNinja -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -D QMC_MPI=0 -DCMAKE_CXX_FLAGS=-Werror ../qmcpack`
3. `ninja`
4. `ctest -L deterministic`

**Expected behavior**
Tests should pass. 

**System:**
Ubuntu 21.10+gcc11+python3-h5py-serial2.10.0-9build2 docker image on Ubuntu 20.04 host

**Additional context**
It seems like python3-h5py on debian adds different classes for dataset and groups (breaks the API)? 
It should be easy to fix by supporting these types on Nexus.
`"<class 'h5py._debian_h5py_serial._hl.dataset.Dataset'>"` and `"<class 'h5py._debian_h5py_serial._hl.group.Group'>"`

```
The following tests FAILED:
	891 - deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars-1-1-check (Failed)
	893 - deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars_sel-1-1-check (Failed)
	1434 - ntest_nexus_hdfreader (Failed)
	1463 - ntest_nexus_qmcpack_analyzer (Failed)
	1472 - ntest_nexus_qmcpack_simulation (Failed)
	1478 - ntest_nexus_qdens (Failed)
```

**Comment by prckent** [comment]
Just wondering: Which version of HDF5 are you using? If too recent we might need h5py 3+. We are using this in the nightlies.

**Comment by williamfgc** [comment]
@prckent I'm trying a vanilla installation of Ubuntu 20.10 with gcc 11. 
It uses libhdf5-dev 1.10.6 (not the latest), and h5py 2.10.0 by default:

``` 
$ dpkg -l | grep libhdf5-dev
ii  libhdf5-dev                            1.10.6+repack-4                   amd64        HDF5 - development files - serial version

$ dpkg -l | grep h5py       
ii  python3-h5py                           2.10.0-9build2                    all          general-purpose Python interface to hdf5
ii  python3-h5py-serial                    2.10.0-9build2                    amd64        general-purpose Python interface to hdf5 (Python 3 serial)
```
