### ISSUE TITLE
cuda2hip.h hipBLAS.hpp have no license

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3374]
**Describe the bug**
While I would like to just consider any code without a license in it to just be public domain I doubt this is the case for the two files above.  Whats the deal with them?  Are they under the same license as other QMCPACK code, none, an incompatible one?  Are we pretending they aren't there in case Nvidia decides to start an API lawsuit?

**To Reproduce**
Read Source

**Expected behavior**
A license

**System:**
Anything

**Additional context**
Would like to use part of them for another port to HIP.

**Comment by jakurzak** [comment]
#3405
