### ISSUE TITLE
Compilation failure with GCC 7.5.0

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#3400]
**Describe the bug**
QMCPACK fails to build when GCC 7.5.0 is used (released Nov. 14, 2019).  The issue relates to private access:

```
[ 20%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/BsplineFactory/createComplexDouble.cpp.o
In file included from /home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp:30:0:
/home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h: In instantiation of ‘void qmcplusplus::HybridRepSetReader<SA>::initialize_hybridrep_atomic_centers() [with SA = qmcplusplus::HybridRepCplx<qmcplusplus::SplineC2R<double> >]’:
/home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp:103:1:   required from here
/home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h:165:16: error: ‘qmcplusplus::HybridRepCenterOrbitals<double>::smoothing_schemes qmcplusplus::HybridRepCenterOrbitals<double>::smooth_scheme’ is private within this context
       bspline->smooth_scheme = SA::smoothing_schemes::CONSISTENT;
       ~~~~~~~~~^~~~~~~~~~~~~
```

**To Reproduce**
1. release version or git commit hash being built

```
commit 6161091baa344f06eb618ed7c859a287427a7630 (HEAD -> develop, main/develop)
Merge: 9818a4703 897da66e1
Author: Ye Luo <yeluo@anl.gov>
Date:   Mon Aug 30 09:32:46 2021 -0500

    Merge pull request #3257 from shivupa/spinonebody
    
    One Body Spin dependent Jastrow
```

2. cmake command

On Ubuntu 18.04.5 LTS:

```
export CXX=mpiCC

echo "building soa real"
mkdir build_soa_real
cd build_soa_real
cmake -DENABLE_SOA=1 ..
make -j 24
cd ..
ln -s ./build_soa_real/bin/qmcpack qmcpack_soa_real
```

**Expected behavior**
Clean build.

**System:**
 - system name: Ubuntu laptop

**Comment by ye-luo** [comment]
HybridRepSetReader is a friend class of HybridRepCenterOrbitals. 
https://github.com/QMCPACK/qmcpack/blob/472b0fb60dcbf9e02133af3571c0bde766978619/src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h#L711

In my tests, GCC 8.1/8.3 works fine. GCC7.5 got choked.
GCC 7.1 was released in May 2, 2017 (4 year old). GCC 7.5 is only a bug fix release.
So raise bar to GCC 8?

**Comment by prckent** [comment]
The question is whether we can make a workaround.

**Comment by ye-luo** [comment]
> The question is whether we can make a workaround.

I’m afraid the answer is probably no.

**Comment by jtkrogel** [comment]
I'm OK with raising the minimum to GCC 8.  I was able to upgrade to gcc 8.4.0 on Ubuntu 18.04, enabling successful build:

https://tuxamito.com/wiki/index.php/Installing_newer_GCC_versions_in_Ubuntu

This is the current limit on "easily accessible" (i.e. via apt) gcc versions on Ubuntu 18.04 LTS.

**Comment by prckent** [comment]
I have a trivial fix

**Comment by correaa** [comment]
Most likely this comes from a buggy implementation of "extended friend declarations" in GCC 7.
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1791.pdf

The line ` friend class HybridRepSetReader;` might be declaring (and friending) a *new* class instead of just friending an existing one. 
A possible workaround, and also a **more correct code** is to write:

```
 friend HybridRepSetReader; 
```

```
 friend SpecificNamespace::HybridRepSetReader; 
```

Hope that this fixes the issue.

**Comment by correaa** [comment]
I actually recommend using extended friend declarations everywhere.
That is, replace `friend class SomeThing;` by `friend Something;`. 

This way one makes sure that one is not declaring a class accidentally instead of just friending it, which is the most likely intent.

**Comment by ye-luo** [comment]
> The line friend class HybridRepSetReader; might be declaring (and friending) a new class instead of just friending an existing one.

This seems to be the case.

**Comment by correaa** [comment]
yes, I think part of the problem could be that it is a template class and the friend is sort of forgetting about that.
In any case, I think either removing class or adding the namespace is sufficient but I would remove class because it is more specific to this problem.

Thank you for trying in any case.

**Comment by ye-luo** [comment]
It seems that "class" is needed for template class. The namespace is not really necessary once the declaration is added but I just keep it to be safe.

**Comment by correaa** [comment]
> It seems that "class" is needed for template class. The namespace is not really necessary once the declaration is added but I just keep it to be safe.

ah, it could be, I didn't know that. Thanks!

**Comment by prckent** [comment]
Thanks for the cleaner fix @correaa , @ye-luo !
