### ISSUE TITLE
More GPU CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3402]
We have self-hosted legacy CUDA CI runs which are quite fast. So consider to add more.

We need
- [x] ENABLE_CUDA=ON. It should be low risk as legacy CUDA. Can be GCC + CUDA.
`cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=ON -DENABLE_CUDA=ON  -DCUDA_ARCH=sm_xx ..`
- [x] ENABLE_CUDA=ON ENABLE_OFFLOAD=ON. This requires Clang 13 release at least rc2
`cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=ON   -DENABLE_CUDA=ON   -DCUDA_ARCH=sm_xx -DCUDA_HOST_COMPILER=`which gcc` -DENABLE_OFFLOAD=ON -DOFFLOAD_ARCH=sm_XX -DUSE_OBJECT_TARGET=ON ..`
- [x] CUDA2HIP cases. Maybe start with build only without running. Add `-DQMC_CUDA2HIP=ON` to the above and drop CUDA_ARCH

**Comment by prckent** [comment]
Agreed. We have bandwidth for these.

Please can you put the exact cmake build lines and define "latest Clang". The most recent release? Develop?

**Comment by prckent** [comment]
For point 2 I think we should just wait to the LLVM13 release, currently alleged for 21 September. @williamfgc Is there an easy way to get and use the RC versions? Preferences?

**Comment by ye-luo** [comment]
@williamfgc can we start to add the above CI variants. the first one only needs gcc. The second one probably we can just use llvm 12.0.1 for the moment.

**Comment by williamfgc** [comment]
@ye-luo @prckent let me look into LLVM13 and installing things on sulfur since we are not using containers for GPU.

**Comment by ye-luo** [comment]
LLVM13 has been released.

**Comment by williamfgc** [comment]
I think this issue has been addressed, thanks @ye-luo and @prckent for bringing this up. There is only one lingering thing that requires digging deeper as there are numerical instabilities on potential `Clang14Dev-MPI-CUDA-AFQMC-Offload-Complex-Mixed` `Clang14Dev-MPI-CUDA-AFQMC-Offload-Complex` (not present) configurations.
