### ISSUE TITLE
 alcf-clang13-CXX17-AFQMC-Offload-CUDA CI can't find fftw

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3423]
**Describe the bug**
CI fails due to missing part of required software stack.

**To Reproduce**
see #3418 #3422 

**Expected behavior**
CI to be configured properly and/or not cause false positives due to system capacity issues.

**System:**
alci-CI

**Additional context**

**Comment by ye-luo** [comment]
it it stable now.
It is intended to replace alcf-clang12-CXX17-AFQMC-Offload-CUDA.
Clang 12 has the issue of not removing temporal files when compiling offload and we frequently got disk space issue on `/tmp`
