### ISSUE TITLE
Unit tests for ResourceCollection don't cover ResourceCollectionTeamLock

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3424]
**Describe the bug**
actual usage pattern is also not reflected in any test case. i.e. all access is supposed to be through ResourceCollectionTeamLock.
I should have stopped this in #3324 

**To Reproduce**
Read code

**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

**Comment by ye-luo** [comment]
I found a few
```
yeluo@ryzen-box:~/opt/qmcpack/src/QMCWaveFunctions/tests$ grep Lock *
test_TrialWaveFunction.cpp:  ResourceCollectionTeamLock<ParticleSet> mw_pset_lock(pset_res, p_ref_list);
test_TrialWaveFunction.cpp:  ResourceCollectionTeamLock<TrialWaveFunction> mw_twf_lock(twf_res, wf_ref_list);
test_TrialWaveFunction_diamondC_2x1x1.cpp:  ResourceCollectionTeamLock<ParticleSet> mw_pset_lock(pset_res, p_ref_list);
test_TrialWaveFunction_diamondC_2x1x1.cpp:  ResourceCollectionTeamLock<TrialWaveFunction> mw_twf_lock(twf_res, wf_ref_list);
```
Isn't this what you are looking for?

**Comment by PDoakORNL** [comment]
That's not how unit tests work.

**Comment by PDoakORNL** [comment]
You could remove the tests of the acquire and release of resource collection since they are no longer part of the "public" API of the module but you can't not test the ResourceCollectionTeamLock.  If I want to make changes to the Resource system the idea is that the unit tests cover the Resource Modules contract with its users.  You don't runt the test_wavefunction_trialwf to verify that.
