### ISSUE TITLE
Mixed Precision Unit Test Failures

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#3427]
**Describe the bug**
Noticed that for the most recent version of develop, I get the following two unit test failures for the mixed precision (real and complex) builds:

	10 - deterministic-unit_test_longrange (Failed)
	24 - deterministic-unit_test_wavefunction_jastrow (Failed)

It looks like some numerical precision issues for the longrange test, but the jastrow test has some unsettling behavior.  Output of failed test documented in the additional information section.  

**To Reproduce**
1. 367c31ab55dde0d5d3f5cc2857ce560cc9d94a97
2. (Real build command.  Same command for complex, just change QMC_COMPLEX=1)  
  cmake -DCMAKE_C_COMPILER=mpicc    \
      -DCMAKE_CXX_COMPILER=mpic++ \
      -DCMAKE_CXX_FLAGS=""   \
      -DCMAKE_C_FLAGS=""     \
      -DQMC_COMPLEX=0             \
      -DQMC_CUDA=0                \
      -DQMC_MIXED_PRECISION=1     \
      -DENABLE_MKL=1              \
      -DBOOST_ROOT=/ascldap/users/rclay/Libraries/boost_1.69.0 \
      -DENABLE_SOA=1 ..
3. ctest -VV -R  deterministic-unit_test_longrange .  ctest -VV -R deterministic-unit_test_wavefunction_jastrow
4. none

**Expected behavior**
Expect all unit tests to pass.  

**System:**
 - SNL compute server.  Intel(R) Xeon(R) CPU E7-8890 v3 @ 2.50GHz, 
 - sems-env, sems-openmpi/1.10.1, sems-git/2.10.12, sems-gcc/9.2.0, sems-cmake/3.19.1, sems-hdf5/1.10.4/base
 - none so far

**Additional context**
One assert failure for deterministic-unit_test_longrange.  That is shown here:  

10: -------------------------------------------------------------------------------
10: StructFact
10: -------------------------------------------------------------------------------
10: /gpfs1/rclay/qmcpack4/src/Particle/LongRange/tests/test_StructFact.cpp:24
10: ...............................................................................
10:
10: /gpfs1/rclay/qmcpack4/src/Particle/LongRange/tests/test_StructFact.cpp:64: FAILED:
10:   CHECK( ComplexApprox(rhok_sum).epsilon(5e-5) == rhok_sum_ref[i] )
10: with expansion:
10:   ComplexApprox( (-125.799,-0.000913978) )
10:   ==
10:   (-125.806,0)

For deterministic-unit_test_wavefunction_jastrow, there are two failed asserts.  
First one:
24: -------------------------------------------------------------------------------
24: RPA Jastrow
24: -------------------------------------------------------------------------------
24: /gpfs1/rclay/qmcpack4/src/QMCWaveFunctions/tests/test_rpa_jastrow.cpp:31
24: ...............................................................................
24:
24: /gpfs1/rclay/qmcpack4/src/QMCWaveFunctions/tests/test_rpa_jastrow.cpp:119: FAILED:
24:   REQUIRE( logpsi_real == Approx(-1.3327837613) )
24: with expansion:
24:   -0.530167345 == Approx( -1.3327837613 )

Second one:
24: -------------------------------------------------------------------------------
24: kspace jastrow
24: -------------------------------------------------------------------------------
24: /gpfs1/rclay/qmcpack4/src/QMCWaveFunctions/tests/test_kspace_jastrow.cpp:31
24: ...............................................................................
24:
24: /gpfs1/rclay/qmcpack4/src/QMCWaveFunctions/tests/test_kspace_jastrow.cpp:118: FAILED:
24:   REQUIRE( logpsi_real == Approx(-4.4088303951) )
24: with expansion:
24:   0.0 == Approx( -4.4088303951 )

**Comment by ye-luo** [comment]
What is the compiler and its version?
Failure in test_StructFact.cpp seems to be a tolerance issue.
Failure cases from rpa and k-space look like bugs.
Without being able to reproduce issues, I'm afraid, debugging will be non-trivial.

**Comment by prckent** [comment]
Assumed long fixed. The deterministic tests are believed solid on all CPU systems today. Reopen if not.
