### ISSUE TITLE
Transition CMake CUDA support to use FindCUDAToolkit

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#3460]
**Is your feature request related to a problem? Please describe.**

We currently use FindCUDA which is long deprecated. 

**Describe the solution you'd like**

Use modern FindCUDAToolkit instead.

**Describe alternatives you've considered**

None.

**Additional context**

Needed for modern compiler support - fixes are in FindCUDAToolkit.

**Comment by quantumsteve** [comment]
I'll try updating `find_package(CUDA REQUIRED)` in CMakeLists.txt and go from there.

@correaa boost-multi has 3 calls to `find_package(CUDA)`
```
./external_codes/boost_multi/multi/adaptors/fftw/test/CMakeLists.txt:find_package(CUDA QUIET)
./external_codes/boost_multi/multi/adaptors/cuda/cublas/test/CMakeLists.txt:find_package(CUDA)
./external_codes/boost_multi/multi/adaptors/blas/test/CMakeLists.txt:find_package(CUDA QUIET)
```

**Comment by ye-luo** [comment]
FYI, we only use boost_multi as header-only. So all the CMake in boost_multi is not used by QMCPACK.

**Comment by correaa** [comment]
@prckent 

> **Is your feature request related to a problem? Please describe.**
> 
> We currently use FindCUDA which is long deprecated.
> 
> **Describe the solution you'd like**
> 
> Use modern FindCUDAToolkit instead.
> 
> **Describe alternatives you've considered**
> 
> None.
> 
> **Additional context**
> 
> Needed for modern compiler support - fixes are in FindCUDAToolkit.

**Comment by correaa** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> We currently use FindCUDA which is long deprecated.
> 
> **Describe the solution you'd like**
> 
> Use modern FindCUDAToolkit instead.
> 

I have been strugling with this for a while.

FindCUDA is deprecated in CMake 3.10 (https://cmake.org/cmake/help/latest/module/FindCUDA.html)

FindCUDAToolkit is new only in 3.17 (https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit)

I have CI machines  that use intermediate versions, so I don't know what should be done in this case.

In relation to @quantumsteve question, I am personally waiting for most of my target machines to move to CMake 3.18 or beyond before rewriting the cuda cmake code.

**Comment by correaa** [comment]
> I'll try updating `find_package(CUDA REQUIRED)` in CMakeLists.txt and go from there.
> 
> @correaa boost-multi has 3 calls to `find_package(CUDA)`
> 
> ```
> ./external_codes/boost_multi/multi/adaptors/fftw/test/CMakeLists.txt:find_package(CUDA QUIET)
> ./external_codes/boost_multi/multi/adaptors/cuda/cublas/test/CMakeLists.txt:find_package(CUDA)
> ./external_codes/boost_multi/multi/adaptors/blas/test/CMakeLists.txt:find_package(CUDA QUIET)
> ```

Yes, this is, to put it mildly, very bad. 

For one thing, I am waiting to learn how to use FindCUDAToolkit, I had problems trying to upgrade that.

Additionally, multi is really a combination of 3 or 4 libraries.
For one thing, you have the core of `multi` (`multi-core`) which is the part of multi that is memory and algorithm agnostic, it doesn't depend on any external library, and then also you have a few "adaptors", which is code that interface multi with popular libraries, like blas, cublas, fftw, cufft, thrust, tblis. (in turn cublas, cufftw, thrust depend on cuda).

In an ideal world these could be separate libraries that depend on `multi` and another library, let's say `fftw`.
However people expect these adaptors to be included with multi.

So, on one hand I want to keep `multi` as a "pure" library with not dependencies for general use.
On the other hand, the adaptors are currently shipping with multi as a subdirectory. 
As a result, I have this dependecy inversion in the file structure of the code, and that is badly reflected in the subdirectories' included CMakeLists.txt.

As a header library it is not a big problem, but to make it cmake friendly and for ctest is kind of a mess.
This what stopped me to polish and make multi fully cmake friendly so far.

If you have a better idea how to handle this situation, please let me know. 
And contributions, PRs are very welcome, BTW.

QMCPack is the main user of multi, so I can do whatever works best for you.
