### ISSUE TITLE
In Complex Mixed precision short tests fail for batched driver

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3469]
**Describe the bug**
        616 - short-diamondC_2x1x1_pp-vmcbatch_dmcbatch_sdj-1-16 (Failed)
        618 - short-diamondC_2x1x1_pp-vmcbatch_dmcbatch-4b_sdbatch_jas-1-4 (Failed)
        620 - short-diamondC_2x1x1_pp-vmcbatch_dmcbatch_4r_sdj-4-4 (Failed)

**To Reproduce**
1. b6fe6e762 
2. CXX=$(which mpic++) CC=$(which mpicc) cmake -DCMAKE_BUILD_TYPE=Debug -DQMC_COMPLEX=1 -DQMC_MIXED_PRECISION=1 -DENABLE_CUDA=1 -DENABLE_OFFLOAD=1 -DUSE_OBJECT_TARGET=1 -DCUDA_HOST_COMPILER=`which gcc` ..
3. see above
4. add -V to ctest see output from QMCDriverNew::checkLogAndGL
**Expected behavior**
I expect this debug check to pass for both QMC_MIXED_PRECISION=0 and 1 its threshold is perhaps too small for mixed.  Or there is a bug, but it looks like the threshold.

**System:**
Leconte
Developer built stack. Clang14 etc.
Checking other systems

**Additional context**

**Comment by ye-luo** [comment]
Do you know if real_FP, real_MP, cplx_FP passes or not?

**Comment by prckent** [comment]
Can you put the numerical results here?

**Comment by PDoakORNL** [comment]
complex full precision passes
