### ISSUE TITLE
Need unit test for MomentumDistribution

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3475]
**Describe the bug**
Momentum Distribution was allowed into the codebase without unit tests. It needs some.  See test_SpinDensityNew.cpp, test_OneBodyDensityMatrices.cpp, etc. For guidance.

**To Reproduce**
no `src/Estimators/tests/test_MomentumDistribution.cpp`

**Expected behavior**
All new code must have unit testing.

**Is your feature request related to a problem? Please describe.**
Work left from #3447

**Comment by jtkrogel** [comment]
I'm starting this now, but there is a strong interaction between tests that follow a similar pattern of use of built/accessed ParticleSet/TrialWavefunction components.

For example, this test case does nothing, but introducing it breaks existing OneBodyDensityMatrices tests:

```
TEST_CASE("MomentumDistribution::MomentumDistribution", "[estimators]")
{
  auto lattice     = testing::makeTestLattice();

  Communicate* comm;
  comm = OHMMS::Controller;
  outputManager.pause();

  MinimalParticlePool mpp;
  ParticleSetPool particle_pool = mpp(comm);
  MinimalWaveFunctionPool wfp;
  WaveFunctionPool wavefunction_pool = wfp(comm, particle_pool);
  auto& pset                         = *(particle_pool.getParticleSet("e"));
  auto& wf_factory                   = *(wavefunction_pool.getWaveFunctionFactory("wavefunction"));
}
```

Resulting output from DM tests:
```
31: -------------------------------------------------------------------------------
31: OneBodyDensityMatrices::evaluateMatrix
31: -------------------------------------------------------------------------------
31: /home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/Estimators/tests/test_OneBodyDensityMatrices.cpp:482
31: ...............................................................................
31: 
31: /home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/Estimators/tests/test_OneBodyDensityMatrices.cpp:307: FAILED:
31:   CHECK( returned_data[id] == Approx(data[id]) )
31: with expansion:
31:   -1.5547128175 == Approx( -0.4029298437 )
```

**Comment by jtkrogel** [comment]
After discussion w/ @PDoakORNL, it looks like this is likely to be an issue w/ the global RNG interacting w/ ParticleSet instantiation.

Peter will post a PR to cement the behavior of 1RDM and I will similarly guard the pending n(k) tests.

**Comment by PDoakORNL** [comment]
We'll need to go through and do this with any of the tests that get a test ParticleSet from MinimalParticleSetPool. Since we don't do discrete unit test executables per "unit" and we have globals there is a dependency on the order in which test run. So we have to protect against this until we remove the global Random object.

**Comment by PDoakORNL** [comment]
Still digging into this, running into the issue of Random being FakeRandom in some compilation units and BoostRandom in others.

**Comment by PDoakORNL** [comment]
This is sufficient for now.
