### ISSUE TITLE
Convert4qmc crashes while processing PySCF h5

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#3503]
**Describe the bug**

convert4qmc crashes (SEGV) while processing an h5 produced by PySCF. This include the stored gold file in the LiH converter test. It seems that the h5 is read correctly, so hopefully this is a simple bug due to string handling or somesuch. Perhaps some of the recent cleanup accidentally introduced it.

The bug was first found while testing the QMC workshop image, since this breaks the initial LiH NEXUS workflow by @jtkrogel . The bug is reproduced on sulfur with standard gcc and libraries used for the nightly testing.

This is critical bug to fix ahead of the workshop.

```
[pk7@sulfur test_LiH_pyscf]$ pwd
/home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/tests/converter/test_LiH_pyscf
[pk7@sulfur test_LiH_pyscf]$ ../../../../build_gcc/bin/convert4qmc LiH.h5
WARNING Creating LCAOHDFParser
Index of ion charge 0
Index of valence charge 1
Using LiH to name output files
Converting Wavefunction from the PySCF Code
Periodic Boundary Conditions: no
usingECP: no
Multideterminants: no
NUMBER OF AOs: 146
Size of Basis Set: 146
NUMBER OF MOs: 146
Unit in Bohr=1
Number of alpha electrons: 2
Number of beta electrons: 2
Number of electrons: 4
SPIN MULTIPLICITY: 1
NUMBER OF ATOMS: 2
 QMCGaussianParserBase::dump 
Segmentation fault (core dumped)
```

The UHF case also crashes:

```
[pk7@sulfur test_LiH_pyscf_UHF]$ ../../../../build_gcc/bin/convert4qmc LiH.h5
WARNING Creating LCAOHDFParser
Index of ion charge 0
Index of valence charge 1
Using LiH to name output files
Converting Wavefunction from the PySCF Code
Periodic Boundary Conditions: no
usingECP: no
Multideterminants: no
NUMBER OF AOs: 19
Size of Basis Set: 19
NUMBER OF MOs: 19
Unit in Bohr=1
Number of alpha electrons: 2
Number of beta electrons: 2
Number of electrons: 4
SPIN MULTIPLICITY: 1
NUMBER OF ATOMS: 2
 QMCGaussianParserBase::dump 
Segmentation fault (core dumped)
```

**To Reproduce**

Develop version. Build the code.

Run convert4qmc on the LiH.h5 we have stored in the LiH pyscf test directory:

$ cd qmcpack/tests/converter/test_LiH_pyscf
$ ../../../../build_gcc/bin/convert4qmc LiH.h5

**Expected behavior**

Converter writes expected XML files and does not crash.

**System:**

Sulfur, gcc11.2, serial build, nightly test software versions.

Also, Ubuntu 20 workshop image.

**Additional context**

**Comment by anbenali** [comment]
Not sure if this should be labeled as a bug or just a "lack of coverage for a corner case"... 

The normal behavior of convert4qmc has always been to specify a tag: 

`convert4qmc -orbitals LiH.h5`

If I do that then I get the correct behavior.

However if I omit the "type" of files I am working with original implementation is supposed to guess. However, I never took the time to update that "guess" feature. So maybe what we should do is just add an safe exist; if no type of file specified, exist gracefully? 

If this solution is acceptable let me know and I will make a PR.

**Comment by prckent** [comment]
The current output of savetoqmcpack() prints
"Use: convert4qmc -pyscf LiH.h5" to generate QMCPACK input files"

Please can you update the python and docs appropriately?

Also, do Jaron's NEXUS workflows need a minor update?
