### ISSUE TITLE
Update makeCopy return to unique_ptr

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3548]
WFC::makeClone has been udpated successful.
Similarly makeCopy under `src/QMCWaveFunctions/Fermion` can be updated

**Comment by quantumsteve** [comment]
The return type of 

https://github.com/QMCPACK/qmcpack/blob/ea59ba8ea66be86e12a8f453bfae3e9352ec7b50/src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h#L151

and

https://github.com/QMCPACK/qmcpack/blob/develop/src/QMCWaveFunctions/Fermion/DiracDeterminant.h#L181

are different.  Covariant return types only work for raw pointers and references. I [tried one trick here](https://github.com/QMCPACK/qmcpack/pull/3551) to get around that limitation.

**Comment by ye-luo** [comment]
makeClone is intended for achieving virtual copy constructor. So the return type should be the the base class.

Be cautious. There are two distinct versions makeCopy. The one with two arguments from DiracDeterminantWithBackflow.h should be renamed as makeCopyWithBF to reduce confusion. Renaming first is recommended.
