### ISSUE TITLE
Constraints on variational parameters

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#3575]
Equality constraints on variational parameters are supported in the input file (see `QMCCostFunctionBase::put`, the `set` element) and in the code (see `QMCCostFunctionBatched::resetPsi`)

One possible use case is orbital rotation where the up and down rotation matrices should be the same.  The input (for one element of the rotation matrix) is
```
 <set type="equal" name="spo-up_orb_rot_0000_0001">
      spo-down_orb_rot_0000_0001
  </set>
```

However, there are some bugs if this is activated
 * sizes of some structures are not correct (`DerivRecords`, `Dsaved`, etc) - they need to use the full number of parameters
 * derivatives need to be summed over constrained parameters

Are these equality constraints a feature that should be supported? (is it worth the effort to fix the code, add tests, and add documentation?)

**Comment by ye-luo** [comment]
Constraints might be useful but it should not be used in the case of spin-up and spin-down electrons having SPOSets sharing the same set of parameters. There should be only one set of entry for SPO parameters.

**Comment by prckent** [comment]
These aren't needed now so need not be implemented now... and they also aren't much of a design constraint, so whoever hits the science case that needs them can worry about putting these in.
