### ISSUE TITLE
Migrate CI from ANL CELS legacy jenkins

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3639]
**Is your feature request related to a problem? Please describe.**
Current CI listed with ALCF are actually provided by ANL CELS legacy jenkins service which will stop on Dec 23th.

**Describe the solution you'd like**
I think it is better to move all of them to oxygen or nitrogen. Or removed if it has been covered.

Current CI cases at ALCF.
```
GNU 8 + MKL Real, Real-Mixed, Complex, Complex-MIxed, Complex no-MPI
GNU 8 + Enable CUDA + AFQMC. Real, Real-Mixed, Complex, Complex-MIxed
Clang 13 + Enable CUDA + Offload + AFQMC. Real, Real-Mixed, Complex, Complex-MIxed
Intel + Enable CUDA + AFQMC. Real, Real-Mixed, Complex, Complex-MIxed
```

**Comment by prckent** [comment]
( http://gcc.gnu.org/releases.html indicates we can use gcc 9.2 as a minimum.  Gcc9 series started in May 2019, 9.2 was out in August 20219)

**Comment by williamfgc** [comment]
Just a status check:

- `GNU 8 + Enable CUDA + AFQMC. Real, Real-Mixed, Complex, Complex-MIxed` -> in CI
- `Intel + Enable CUDA + AFQMC. Real, Real-Mixed, Complex-MIxed`- > in CI, 
    - `Complex` bug tracked in #3654
- `Clang 13 + Enable CUDA + Offload + AFQMC. Real, Real-Mixed` -> in CI with `Clang14Dev`, 
    - bugs in `Complex, Complex-MIxed`
- GNU 8 + MKL Real, Real-Mixed, Complex, Complex-MIxed, Complex no-MPI -> WIP

**Comment by williamfgc** [comment]
@prckent I'm keeping GCC8 for now (default on RHEL8), I'll bump to GCC9 after the break.
