### ISSUE TITLE
HDFAttribIO compilation error on Summit

### ISSUE THREAD

**Issue by brtnfld** [QMCPACK/qmcpack#3648]
**Describe the bug**
Compiling on Summit I'm getting the compilation errors:

CMakeFiles/qmcwfs.dir/MuffinTin.cpp.o -c /ccs/home/brtnfld/packages/qmcpack.master/src/QMCWaveFunctions/MuffinTin.cpp
In file included from /ccs/home/brtnfld/packages/qmcpack.master/src/QMCWaveFunctions/MuffinTin.h:23,
                 from /ccs/home/brtnfld/packages/qmcpack.master/src/QMCWaveFunctions/EinsplineSet.h:25,
                 from /ccs/home/brtnfld/packages/qmcpack.master/src/QMCWaveFunctions/EinsplineSet.cpp:19:
/ccs/home/brtnfld/packages/qmcpack.master/src/Numerics/HDFNumericAttrib.h:88:8: error: redefinition of 'struct qmcplusplus::HDFAttribIO<long unsigned int>'
   88 | struct HDFAttribIO<unsigned long> : public HDFAttribIOBase
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/ccs/home/brtnfld/packages/qmcpack.master/src/Numerics/HDFNumericAttrib.h:63:8: note: previous definition of 'struct qmcplusplus::HDFAttribIO<long unsigned int>'
   63 | struct HDFAttribIO<hsize_t> : public HDFAttribIOBase
      |        ^~~~~~~~~~~~~~~~~~~~
In file included from /ccs/home/brtnfld/packages/qmcpack.master/src/QMCWaveFunctions/EinsplineSetBuilder.h:29,
                 from /ccs/home/brtnfld/packages/qmcpack.master/src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp:24:
/ccs/home/brtnfld/packages/qmcpack.master/src/Numerics/HDFNumericAttrib.h:88:8: error: redefinition of 'struct qmcplusplus::HDFAttribIO<long unsigned int>'
   88 | struct HDFAttribIO<unsigned long> : public HDFAttribIOBase
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/ccs/home/brtnfld/packages/qmcpack.master/src/Numerics/HDFNumericAttrib.h:63:8: note: previous definition of 'struct qmcplusplus::HDFAttribIO<long unsigned int>'
   63 | struct HDFAttribIO<hsize_t> : public HDFAttribIOBase
      |        ^~~~~~~~~~~~~~~~~~~~

**To Reproduce**
develop version of qmcpack

modules:
  1) lsf-tools/2.0   3) darshan-runtime/3.3.0-lite   5) DefApps      7) gcc/9.1.0      9) zlib/1.2.11          11) spectrum-mpi/10.4.0.3-20210112  13) fftw/3.3.9              15) python/3.8-anaconda3
  2) hsi/5.0.2.p5    4) xalt/1.2.1                   6) essl/6.3.0   8) cmake/3.21.3  10) netlib-lapack/3.9.1  12) boost/1.77.0                    14) netlib-scalapack/2.1.0

I'm using HDF5 1.13, built from source. Note that hsize_t is uint64_t.

the CMake command:

export HDF5_ROOT=$HOME/packages/hdf5-1.13/build/hdf5

cmake \
 -DQMC_MATH_VENDOR=IBM_MASS -DMASS_ROOT=/sw/summit/xl/16.1.1-10/xlmass/9.1.1 \
 -D CMAKE_BUILD_TYPE=Release \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D QMC_CUDA=0 \
 -D BUILD_LMYENGINE_INTERFACE=0 \
 -D MPIEXEC="jsrun" \
 ..

**Comment by prckent** [comment]
Does qmcpack/config/build_olcf_summit.sh work for you? Possibly this needs a minor module update but it should be a good starting point.

**Comment by ye-luo** [comment]
Looks like `hsize_t` and `unsigned long` overlap. So something new from hdf5 1.13

**Comment by brtnfld** [comment]
hmmm, I tried that before and it failed. But I just retried it and now it passes 😕. Let me switch out the HDF5 version in that script and see if it works.

**Comment by brtnfld** [comment]
Indeed, the definition of hsize_t was changed in June, and that was released in 1.13.

**Comment by brtnfld** [comment]
Would it be possible to point out where 

> template<>
> struct HDFAttribIO<hsize_t> : public HDFAttribIOBase

is used, I'm not finding it.

**Comment by markdewing** [comment]
It may not be used.  If I remove that specialization, it still compiles.

**Comment by ye-luo** [comment]
Let us just remove unused pieces.

**Comment by brtnfld** [comment]
Are you going to do that or do you want me to do a PR?

**Comment by ye-luo** [comment]
If @markdewing  has not prepared a PR, you @brtnfld are welcome to do it.

**Comment by markdewing** [comment]
I have not made a PR for this.
