### ISSUE TITLE
enhance CMake CHECK_PYTHON_REQS

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3662]
**Is your feature request related to a problem? Please describe.**
CHECK_PYTHON_REQS should record checked module and skip redundant checks.

**Describe the solution you'd like**
Probably keep two global lists, succeeded and failed.

**Comment by markdewing** [comment]
It already works this way.  Look in `CMakeCache.txt` and variables such as 'HAS_H5PY_PYTHON_MODULE' should be in there.

The last line in `TEST_PYTHON_MODULE` writes the python module existence variable to the cache.

**Comment by ye-luo** [comment]
Exactly. You are right.
