### ISSUE TITLE
Modernize multiline string literals

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#3675]
c++11 provided an easier way to define multiline string literals

```c++
const char * literal =   R"(
<estimator type="dm1b" name="DensityMatrices">
  <parameter name="basis"        >  spo_ud spo_dm </parameter>
  <parameter name="evaluator"    >  matrix        </parameter>
  <parameter name="integrator"   >  density       </parameter>
  <parameter name="samples"      >  64            </parameter>
  <parameter name="timestep"     >  0.5           </parameter>
  <parameter name="center"       >  0.0 0.0 0.1   </parameter>
  <parameter name="use_drift"    >  yes           </parameter>
</estimator>
)",
```

this replaces the rather painful to maintain and look at c error multiline definition
```c++
  const char* lat_xml = "<simulationcell>                                         \
                         <parameter name=\"bconds\">                            \
                           p p p                                                \
                         </parameter>                                           \
                         <parameter name=\"LR_dim_cutoff\" >     6  </parameter>\
                         <parameter name=\"rs\"            >   1.0  </parameter>\
                         <parameter name=\"nparticles\"    >     8  </parameter>\
                       </simulationcell>";
```

Open to arguments about what the type the literal should be assigned to.

**Additional context**

**Comment by ye-luo** [comment]
Thanks for pointing this out. Much more friendly to work with.
Can we use `string_view` instead of `char *`

**Comment by PDoakORNL** [comment]
Now that we are fully c++17 I think `string_view` is the best type to use, but there is a catch. If the string_view isn't constructed from a string_literal it is possible for it to not be null terminated. This will interact very badly with an c api expecting a c string.  

Of course there was nothing keeping us from passing a const char * that pointed at a non null terminated string either.
However a std::string providing a c string via a c_str() call is always null terminated.

**Comment by williamfgc** [comment]
`const std::string` as of C++17? `constexpr std::string` is only C++20 . Also, I think I ran into issues between raw string literals and automated clang-format, but nothing of major concern (might have been an old clang-format). Very useful feature BTW, good call.

**Comment by PDoakORNL** [comment]
wasn't clear I guess, I meant we could have constexpr string_view.
If we go this way we can change the parseFromString argument in src/io/OhmmsData/Libxml2Doc to a const string_view.

And I've needed to use
```c++
// clang-format off
...
// clang-format on
```
to keep clang-tidy from mauling the literal.  Its something it should be able to figure out not to do but I don't think its supported.

**Comment by correaa** [comment]
Take into account that the first character (which a newline character) is contained in the string which is, typically, not the intent.
So something like this is needed to recover strictly the original string:

```cpp
const char * literal =   R"(<estimator type="dm1b" name="DensityMatrices">
  <parameter name="basis"        >  spo_ud spo_dm </parameter>
  <parameter name="use_drift"    >  yes           </parameter>
</estimator>
)";
```

Which partly defeats the purpose of multiline string literals.
For this reason I invented this idiom to ignore the first newline character:

```cpp
const char * literal =  std::next(R"(
<estimator type="dm1b" name="DensityMatrices">
  <parameter name="basis"        >  spo_ud spo_dm </parameter>
  <parameter name="use_drift"    >  yes           </parameter>
</estimator>
)");
```
which really just means:

```cpp
const char * literal =  1 + R"(
<estimator type="dm1b" name="DensityMatrices">
  <parameter name="basis"        >  spo_ud spo_dm </parameter>
  <parameter name="use_drift"    >  yes           </parameter>
</estimator>
)";
```

Finally, I found that it is a good practice to prefix string literals with the contained format:

```cpp
const char * literal =   std::next(R"XML(
<estimator type="dm1b" name="DensityMatrices">
  <parameter name="basis"        >  spo_ud spo_dm </parameter>
  <parameter name="use_drift"    >  yes           </parameter>
</estimator>
)XML");
```

(Note the same marker has to go after the end parenthesis, in this case XML)

All this can be combined/assigned to a `string_view` (not a fan). 

If you use `string_view` (C++17) there is a yet another option:

```cpp
auto const literal =  std::string_view{R"XML(
<estimator type="dm1b" name="DensityMatrices">
  <parameter name="basis"        >  spo_ud spo_dm </parameter>
  <parameter name="use_drift"    >  yes           </parameter>
</estimator>
)XML"}.substr(1);
```

or 

```cpp
using namespace std::literals;

auto const literal =  R"XML(
<estimator type="dm1b" name="DensityMatrices">
  <parameter name="basis"        >  spo_ud spo_dm </parameter>
  <parameter name="use_drift"    >  yes           </parameter>
</estimator>
)XML"sv.substr(1);
```

None of them are very readable, perhaps the closest is to use `std::next`. 
You can play with them here: https://godbolt.org/z/476hW78Ts.

If I may add, I would say that having such a string in the code is code smell, a more elegant approach would be to use the XML library already in use to generate this strings from a code-constructed tree. Not sure how inconvenient is this.

**Comment by PDoakORNL** [comment]
There is no problem with an XML starting with a newline as I read the XML spec.  So just hit return and don't worry about it.  If you have a multiline string that is also extremely inflexible with whitespace formatting, I'm fairly worried.

And as long as XML is the defacto argument to the defacto constructor of many classes I think its better to have it visible in the test code.  Ultimately I'd rather see zero XML and instead see directly initialized native input structures in the tests.

**Comment by correaa** [comment]
> There is no problem with an XML starting with a newline as I read the XML spec. So just hit return and don't worry about it. If you have a multiline string consumer that is also extremely inflexible with whitespace formatting, I'm fairly worried.

yes, what I am saying is that the code of the OP will not be 100% equivalent. Also there could be surprising empty lines in XML concatenated from the strings.

Happy new year!

**Comment by ye-luo** [comment]
@quantumsteve Could you have a look at all the unit tests and update them with string literals and get rid of all the backslash?

**Comment by quantumsteve** [comment]
I think clang-tidy can make this change for us.
https://clang.llvm.org/extra/clang-tidy/checks/modernize/raw-string-literal.html

**Comment by ye-luo** [comment]
> I think clang-tidy can make this change for us. https://clang.llvm.org/extra/clang-tidy/checks/modernize/raw-string-literal.html

If you get a chance, could you try just this feature of clang-tidy? I was revisiting this issue because I saw new tests are created by copying old tests and the bad pattern keeps being propagated.

**Comment by quantumsteve** [comment]
I think the form feed in the string literals is preventing most for being converted automatically by clang-tidy :disappointed:

**Comment by correaa** [comment]
I have the strange feeling that form feeds in string literals are non-standard. Raw-string-literal (`R"..."`) all the way!
