### ISSUE TITLE
Need a Debug build in CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3691]
**Is your feature request related to a problem? Please describe.**
We do have Debug type builds in the nightly. Probably having one in CI is beneficial to prevent #3690.

**Comment by prckent** [comment]
See also #3696 . I am not sure how far this is from working - would be straightforward to change one of the MPI builds to also be a no OMP build.

**Comment by williamfgc** [comment]
@ye-luo @prckent this is next on my list

**Comment by ye-luo** [comment]
CI with QMC_OMP=OFF is tracked by https://github.com/QMCPACK/qmcpack/issues/3732
