### ISSUE TITLE
Building with -DQMC_OMP=OFF fails.

### ISSUE THREAD

**Issue by NAThompson** [QMCPACK/qmcpack#3696]
**Describe the bug**

Disabling OMP does not work.

**To Reproduce**

On top of git hash 174d200a04bd2564564e1cc5becff:

```
~/q/build ❯❯❯ cmake -DQMC_OMP=OFF ../ -G Ninja
-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
~/q/build ❯❯❯ ninja
[16/713] Building CXX object src/QMCTools/CMakeFiles/qmc-check-affinity.dir/check-affinity.cpp.o
FAILED: src/QMCTools/CMakeFiles/qmc-check-affinity.dir/check-affinity.cpp.o
~/qmcpack/src/QMCTools/check-affinity.cpp:15:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
```

**System:**
 - M1 Mac.

Patch for the fix is attached.

[patch.txt](https://github.com/QMCPACK/qmcpack/files/7794841/patch.txt)

**Comment by NAThompson** [comment]
Sadly, now I'm here:

```
qmcpack/external_codes/boost_multi/multi/./memory/allocator.hpp:64:3: error: static_assert failed due to requirement 'alignof(long double) >= 16' "for cuda"
                static_assert( alignof(std::max_align_t) >= 16 , "for cuda");
                ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by prckent** [comment]
Hi NAThompson -

Which compilers and tool versions are you using to build QMCPACK? And which version are you compiling? I verified that QMCPACK develop built on macOS a few weeks ago using either a very recent gcc or clang (on travel, can't check). Generally people use a set of software from macports or brew - there are instructions in the manual for this, e.g. https://qmcpack.readthedocs.io/en/develop/installation.html#installing-on-mac-os-x-using-macports . Our CMakeLists will pick up Apple's veclib for blas. We haven't checked recently whether QMCPACK builds with OpenMP disabled - this could be fixed if needed for strong enough reasons. At most I would expect that there is a missed #ifdef or two needed to protect omp includes as you found.

**Comment by NAThompson** [comment]
@prckent : The critical piece of info is that this is on ARM, not x86; I suspect they haven't implemented OMP yet. Nonetheless, I have added the requested info.

>  We haven't checked recently whether QMCPACK builds with OpenMP disabled - this could be fixed if needed for strong enough reasons.

I'm not convinced my use case (just hacking on my laptop for convenience) is a good enough reason. Nonetheless I went down a rabbit hole so maybe just removing the CMake option would be sufficient?

**Comment by PDoakORNL** [comment]
I've been interested in getting this working again for a long time.  Not sure what the priority is but in priniciple this shouldn't be hard to get working and we have abstractions covering at least the top layer of threading.

**Comment by ye-luo** [comment]
For disabling OpenMP, this is  a duplicated issue https://github.com/QMCPACK/qmcpack/issues/2778

As long as GCC is working on Mac, it is low priority to support other compilers especially proprietary ones.
In your case AppleClang is doing something different from gcc.
ARM should not be not an issue. Use gcc which has been verified a month ago by @prckent

**Comment by prckent** [comment]
@NAThompson ARM is fully supported. See https://github.com/QMCPACK/qmc_workshop_2021/tree/master/workshop_image for details of a ready-to-use virtual machine that works on m1. We have nightly tests on ARM running Ubuntu. The issue for Apple machines is that (to my knowledge) Apple simply does not support OpenMP in their compilers, so a large number of scientific codes need to be compiled with another compiler. This is unfortunate since upstream llvm does. There is commentary online about this unfortunate situation. macports, brew, spack are quick sources of the tools needed for QMCPACK.

@PDoakORNL I agree with you... not high priority but it would help check some of our abstractions, and imo it can be helpful to make a no OMP build in much the same way that it can be helpful to make a no MPI build.

**Comment by NAThompson** [comment]
> Apple simply does not support OpenMP in their compilers, so a large number of scientific codes need to be compiled with another compiler. 

Yeah, I tried it with the latest LLVM, but unfortunately hit *another* problem with LLVM on ARM!

**Comment by ye-luo** [comment]
FYI. The ARM in our nightly tests is a Raspberry Pi 4 which is ARM v8. The OS is aarch64 Raspberry PI OS derived from Debian. The compiler is Clang 13.

**Comment by correaa** [comment]
> Sadly, now I'm here:
> 
> ```
> qmcpack/external_codes/boost_multi/multi/./memory/allocator.hpp:64:3: error: static_assert failed due to requirement 'alignof(long double) >= 16' "for cuda"
>                 static_assert( alignof(std::max_align_t) >= 16 , "for cuda");
>                 ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ninja: build stopped: subcommand failed.
> ```

Is this still a problem?

There is something strange, that cuda memory cannot align below 16 bytes.
I don't know exactly how to solve this problem. 

If this is a problem, I am going to just pessimize the alignment:

```cpp
	[[nodiscard]]
	auto allocate(size_type n) -> pointer {
	//	static_assert( alignof(std::max_align_t) >= 16 , "for cuda");
		return static_cast<pointer>(static_cast<void_pointer>(mp_->allocate(
			n*sizeof(value_type),
			std::max(
				alignof(std::max_align_t),
				16  // for cuda, cuda needs alignment at 16 at least? TODO(correaa) investigate
			)
		)));
	}
```

**Comment by ye-luo** [comment]
Please try the latest develop with `-DQMC_OMP=OFF`. If there are still issues, please open new tickets.
