### ISSUE TITLE
Tests of HEG needed

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#370]
Per the discussion in #364 , the HEG special wavefunction type is believed to be working in develop.

1. I suggest we add at least one integration test to verify that this still works in future versions.
2. If we can find a good literature reference with VMC (HF) and single det DMC results to high accuracy, we should use this as an opportunity to check the VMC and DMC drivers against known results.

**Comment by jtkrogel** [comment]
I'm starting to work on this now.  I've found an old set of HEG runs from the 2012 QMCPACK school that include reference data.  The available runs are for a 14 electron HEG at the gamma point: Hartree-Fock VMC, Slater-Jastrow VMC, Slater-Jastrow-Backflow VMC, Slater-Jastrow DMC.  

I've rerun these using old and new versions of QMCPACK on both oxygen and my workstation (psi2).  Results are summarized below:

>>HEG           NI VMC     HF VMC      SJ VMC      SJB VMC     SJ DMC    
reference     0.627711  -0.8127(5)  -1.0728(5)  -1.0848(5)  -1.1101(6)
psi2   r6262  0.627711  -0.8125(1)  -1.0732(1)  -1.0855(1)  -1.1106(2)
oxygen r6259  0.627711  -0.8124(1)  -1.0733(1)  -1.0854(1)  -1.1102(2)
oxygen 3.0.0  0.627711  -0.8126(1)  -1.0732(1)  -1.0854(2)  -1.1102(2)
oxygen 3.1.1  0.627711  -0.8123(1)  -1.0733(1)   aborts     -1.1102(2)
oxygen 3.2.0  0.627711   segfault    segfault    segfault    segfault 

All runs that completed are statistically consistent with each other.  All runs were performed with the original (AOS) version of the real code built with Intel compilers.  The abort in v3.1.1 is appropriate; it relates to the backflow cutoff being set to 10 a.u. while the Wigner Seitz radius is ~9.713 a.u.  The newest release of QMCPACK (3.2.0) segfaults for all cases except for non-interacting, i.e. the bug relates at least to the introduction of the electron-electron interaction.

I am currently adjusting these runs to make a new set of tests.  These will need to be adjusted for length and I will try to reoptimize backflow with an appropriate cutoff.  I also will add some tests that drive the same HEG runs with a different/modern input style.

**Comment by prckent** [comment]
Perhaps the SoA merge broke 3.2.0 even in traditional AoS mode?

**Comment by jtkrogel** [comment]
I can confirm that optimization of jastrows and backflow works as well in v3.1.1 as in the reference values.  The alternate/modern form of the input also works in v3.1.1 and gives equivalent results to the older form.

**Comment by prckent** [comment]
Please can you define the old and alternate/modern forms of input?

**Comment by jtkrogel** [comment]
Old and new differ a little on how the simulation cell is specified (e.g. the use/abuse of the "condition" attribute on parameter "rs") and how the single particle orbitals are specified (by shell or by absolute count).  Examples are below.

**Old input style**
```
<simulationcell>
<parameter name="rs" condition="14">5</parameter>
<parameter name="bconds">p p p</parameter>
<parameter name="LR_dim_cutoff">6</parameter>
</simulationcell>

<determinantset type="electron-gas" shell="1" randomize="true"/>
```

**New input style**
```
<simulationcell>
   <parameter name="bconds">
      p p p
   </parameter>
   <parameter name="LR_dim_cutoff"       >    6                  </parameter>
   <parameter name="rs"                  >    5.0                </parameter>
   <parameter name="nparticles"          >    14                 </parameter>
</simulationcell>

<sposet_builder type="heg">
   <sposet type="heg" name="spo_ud" size="7"/>
</sposet_builder>

<determinantset>
   <slaterdeterminant>
      <determinant id="updet" group="u" sposet="spo_ud" size="7"/>
      <determinant id="downdet" group="d" sposet="spo_ud" size="7"/>
   </slaterdeterminant>
</determinantset>
```

**Comment by ye-luo** [comment]
I can run v3.2.0 with the following input with both GNU(Ryzen) and Intel(Xeon).
I got -0.8125(3).
```
      <simulationcell>
         <parameter name="bconds">
            p p p
         </parameter>
         <parameter name="LR_dim_cutoff"       >    6                 </parameter>
         <parameter name="rs"                  >    5.0                </parameter>
         <parameter name="nparticles"          >    14                 </parameter>
      </simulationcell>
      <particleset name="e" random="yes">
         <group name="u" size="7">
            <parameter name="charge"              >    -1                    </parameter>
            <parameter name="mass"                >    1.0                   </parameter>
         </group>
         <group name="d" size="7">
            <parameter name="charge"              >    -1                    </parameter>
            <parameter name="mass"                >    1.0                   </parameter>
         </group>
      </particleset>
      <wavefunction name="psi0" target="e">
         <sposet_builder type="heg" twist="0 0 0">
            <sposet type="heg" name="spo_ud" size="7"/>
         </sposet_builder>
         <determinantset>
            <slaterdeterminant>
               <determinant id="updet" group="u" sposet="spo_ud" size="7"/>
               <determinant id="downdet" group="d" sposet="spo_ud" size="7"/>
            </slaterdeterminant>
         </determinantset>
      </wavefunction>
      <hamiltonian name="h0" type="generic" target="e">
        <pairpot type="coulomb" name="ElecElec" source="e" target="e"/>
      </hamiltonian>
```
