### ISSUE TITLE
Get rid of USE_FAKE_RNG macro

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3700]
**Is your feature request related to a problem? Please describe.**
USE_FAKE_RNG can be considered a hack to force fake RNG in unit tests.
It introduces internal forks in the source tree and caused chain reaction.

**Describe the solution you'd like**
I would consider a base+derived class implementation. As long as RNGs are explicitly initialized for the tested object, there is no issue selecting true or fake RNGs.

**Describe alternatives you've considered**
I thought of templates on RNG but then it doesn't change the nature of two forks as all the types are enforced. So I prefer not to take this route.

**Comment by PDoakORNL** [comment]
To me it looks like a pure virtual base class interface is probably the easiest route to take here. We shouldn't have the need for behavior that changes depending on the RNG type.

**Comment by quantumsteve** [comment]
I think we can get the same behavior from FakeRandom and StdRandom by setting the distribution min and max of the later to be 0.5 and 0.5.
