### ISSUE TITLE
Sandbox restart compilation fails on Summit.

### ISSUE THREAD

**Issue by brtnfld** [QMCPACK/qmcpack#3704]
**Describe the bug**

This use to work for at least hash 1895faafa885b7ed1d34fec6e8214286ded835fa

On Summit with develop (fbbe1d0bdafed74a8134ffeb62f5dc1759d93c3b), I'm getting the error:

In file included from /ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/restart.cpp:24:
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:33:3: error: 'RandomGenerator' does not name a type; did you mean 'RandomGenerator_t'?
   33 |   RandomGenerator<RealType> myRNG;
      |   ^~~~~~~~~~~~~~~
      |   RandomGenerator_t
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:39:20: error: 'RandomGenerator' does not name a type; did you mean 'RandomGenerator_t'?
   39 |   NonLocalPP(const RandomGenerator<RealType>& rng) : myRNG(rng)
      |                    ^~~~~~~~~~~~~~~
      |                    RandomGenerator_t
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:39:35: error: expected ',' or '...' before '<' token
   39 |   NonLocalPP(const RandomGenerator<RealType>& rng) : myRNG(rng)
      |                                   ^
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp: In constructor 'qmcplusplus::NonLocalPP<T>::NonLocalPP(int)':
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:39:54: error: class 'qmcplusplus::NonLocalPP<T>' does not have any field named 'myRNG'
   39 |   NonLocalPP(const RandomGenerator<RealType>& rng) : myRNG(rng)
      |                                                      ^~~~~
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:39:60: error: 'rng' was not declared in this scope
   39 |   NonLocalPP(const RandomGenerator<RealType>& rng) : myRNG(rng)
      |                                                            ^~~
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:42:5: error: 'myRNG' was not declared in this scope
   42 |     myRNG.init(0, 1, 11);
      |     ^~~~~
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp: In member function 'void qmcplusplus::NonLocalPP<T>::randomize(PA&)':
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:70:27: error: there are no arguments to 'myRNG' that depend on a template parameter, so a declaration of 'myRNG' must be available [-fpermissive]
   70 |     RealType phi(TWOPI * (myRNG())), psi(TWOPI * (myRNG())), cth((myRNG()) - 0.5);
      |                           ^~~~~
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:70:27: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:70:51: error: there are no arguments to 'myRNG' that depend on a template parameter, so a declaration of 'myRNG' must be available [-fpermissive]
   70 |     RealType phi(TWOPI * (myRNG())), psi(TWOPI * (myRNG())), cth((myRNG()) - 0.5);
      |                                                   ^~~~~
/ccs/home/brtnfld/packages/qmcpack.master/src/Sandbox/pseudo.hpp:70:67: error: there are no arguments to 'myRNG' that depend on a template parameter, so a declaration of 'myRNG' must be available [-fpermissive]
   70 |     RealType phi(TWOPI * (myRNG())), psi(TWOPI * (myRNG())), cth((myRNG()) - 0.5);
      |                                                                   ^~~~~
make[3]: *** [src/Sandbox/CMakeFiles/restart.dir/build.make:76: src/Sandbox/CMakeFiles/restart.dir/restart.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:2960: src/Sandbox/CMakeFiles/restart.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2967: src/Sandbox/CMakeFiles/restart.dir/rule] Error 2

**To Reproduce**
   cmake -DCMAKE_C_COMPILER="mpicc" \
          -DCMAKE_CXX_COMPILER="mpicxx" \
          -DBUILD_LMYENGINE_INTERFACE=0 \
          -DQMC_BUILD_SANDBOX_ONLY=1 ..
  
   make restart

**System:**
Summit
Currently Loaded Modules:
  1) lsf-tools/2.0   3) darshan-runtime/3.3.0-lite   5) DefApps      7) zlib/1.2.11    9) spectrum-mpi/10.4.0.3-20210112  11) netlib-lapack/3.9.1     13) fftw/3.3.9    15) nsight-compute/2021.2.1     17) cuda/11.0.3
  2) hsi/5.0.2.p5    4) xalt/1.2.1                   6) gcc/11.1.0   8) cmake/3.21.3  10) essl/6.3.0                      12) netlib-scalapack/2.1.0  14) boost/1.77.0  16) nsight-systems/2021.3.1.54

**Comment by ye-luo** [comment]
This will be solved by https://github.com/QMCPACK/qmcpack/pull/3699

**Comment by brtnfld** [comment]
ok, I'm assuming the failing of: 

1 - deterministic-unit_test_io_hdf5

is also related to this issue?

**Comment by ye-luo** [comment]
The sandbox restart compilation issue has been resolved.
Your test failure is related to Summit setting. Your home directory is read-only on Summit compute node (jsrun).
