### ISSUE TITLE
Use of #pragma simd is deprecated

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#375]
The Intel 2018 compiler now warns heavily about the use of this feature. We should update the code.

**Comment by ye-luo** [comment]
I would like to use only #pragma omp simd.
However, there was some resolved issue related to using sincos inside simd region. GNU will crash the code.

**Comment by ye-luo** [comment]
Do you have the warning message? I have a bit doubt because what are the alternatives for codes not using OpenMP.

**Comment by ye-luo** [comment]
warning #3948: simd pragma has been deprecated, and will be removed in a future release.  Please refer to release notes for details and recommended alternatives

I went to the release notes and found no mention of "pragma simd" at all...

**Comment by prckent** [comment]
@ye-luo "GNU will crash the code". Which versions?

**Comment by ye-luo** [comment]
@prckent They were 5.4 and 6.3 with libmvec(part of glibc).

**Comment by prckent** [comment]
OK. We are not testing libmvec here since oxygen has too old libc. However, is this their bug or our bug? Just because it works on Intel does not mean that we are bug free.

**Comment by ye-luo** [comment]
Part of the sincos problem is due to the fact that sincos is not in standard. sincos also take address as argument instead of reference.

**Comment by ye-luo** [comment]
libmvec from glibc 2.23 is buggy. Using gcc on ubuntu 16.04 hits this issue need to be caught by CMake.

**Comment by prckent** [comment]
We need to identify 

- When gcc is being used
- Which glibc is being used
- The range of versions the bug exists in glibc (if it really is glibc and not specific gcc versions or a glibc-gcc interaction)

Then

- Have cmake detect this and write a warning plus set a flag, e.g. USE_SCALAR_SINCOS_WORKAROUND
- Add appropriate #ifdefs to our vector numerics code

**Comment by ye-luo** [comment]
The warning has been eliminated in PR #474. No guard in CMake yet.
