### ISSUE TITLE
SoA code and Intel compiler gives many mismatched unroll warnings

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#376]
Should be tidied. These flood the cmake output.
>remark: unroll pragma will be ignored due to unroll factor exists
>remark: unroll pragma will be ignored due to unrolling factor mismatched

**Comment by ye-luo** [comment]
This is probably a compiler bug. Intel with MIC-AVX512 has no warning.

**Comment by ye-luo** [comment]
Tried Intel 18. The reported line number is totally wrong.

**Comment by prckent** [comment]
Intel 17 also does this, so most of our users will see it.

Have you filed a bug?

**Comment by ye-luo** [comment]
Will do.

**Comment by ye-luo** [comment]
The line numbers are OK but not at the exact location. I submitted a bug report to Intel with a small code example. We will see.

**Comment by prckent** [comment]
Which lines are actually at fault and can we proactively make a fix or even improvement?
