### ISSUE TITLE
pw2qmcpack on NERSC Cori

### ISSUE THREAD

**Issue by hzhou23** [QMCPACK/qmcpack#3768]
Dear All,

I was trying to install quantum espresso in the 'external_code' on NERSC Cori. Following the manual, I downloaded the patched version of qe6.8. After that I found the hdf5 folder that includes 'bin' and 'include'. 
The path I used was : '/opt/cray/pe/hdf5/1.10.5.2/cray/9.0'. 
Then I did: ./configure --with-hdf5=/opt/cray/pe/hdf5/1.10.5.2/cray/9.0. 
After the configure, I simply did: make all

But the code stops at making pw2qmcpack.x, reporting that HDF5 flag is not enabled or manually added in make.inc. 

Then I opened the make.inc file, changed as the following:

"DFLAGS         =  -D__DFTI -D__HDF5 -DH5_USE_16_API"
"IFLAGS         = -I$(TOPDIR)/include -I$(TOPDIR)/FoX/finclude  -I/opt/intel/compilers_and_libraries_2019.3.199/linux/mkl/include -I/opt/cray/pe/hdf5/1.10.5.2/cray/9.0/include"
"HDF5_LIBS = /opt/cray/pe/hdf5/1.10.5.2/cray/9.0/include"

Then I did: make all

The code still bugged and reporting: undefined reference to `esh5_open_file_' 

If possible, could anyone share how to install pw2qmcpack on NERSC Cori? Thank you so much!

Sincerely,

Haihan Zhou

**Comment by ye-luo** [comment]
Just use CMake.
See https://github.com/ye-luo/q-e/releases/tag/v6.8%2Bpw2qmcpack
FYI. we also provide QE 7.0
https://github.com/ye-luo/q-e/releases/tag/v7.0%2Bpw2qmcpack
https://github.com/QMCPACK/qmcpack/blob/develop/external_codes/quantum_espresso/download_and_patch_qe7.0.sh

**Comment by hzhou23** [comment]
> Just use CMake. See https://github.com/ye-luo/q-e/releases/tag/v6.8%2Bpw2qmcpack FYI. we also provide QE 7.0 https://github.com/ye-luo/q-e/releases/tag/v7.0%2Bpw2qmcpack https://github.com/QMCPACK/qmcpack/blob/develop/external_codes/quantum_espresso/download_and_patch_qe7.0.sh

Thanks Ye! I got it installed with qe-7.0 now!
