### ISSUE TITLE
unit_test and unit_test_particle tests failing consistently

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#3779]
**Describe the bug**
`deterministic_unit_test` and `deterministic_unit_test_particle` tests failing consistently due to numerical differences on several CPU and GPU CI configurations.
see [logs](https://github.com/QMCPACK/qmcpack/runs/4975618782?check_suite_focus=true)

**To Reproduce**
1. `develop` branch
2. cmake command, see multiple configuration logs [here](https://github.com/QMCPACK/qmcpack/runs/4975618782?check_suite_focus=true)
3. ninja
4. ctest -L deterministic

**Expected behavior**
Tests must pass

**System:**
 - sulfur-cpu, nitrogen-rocm, sulfur-cuda

**Additional context**
Threshold for numerical error must be reduced

**Comment by ye-luo** [comment]
I think there is no issue on `develop` failure was cased by the PR.
`nitrogen-cuda (GCC8-MPI-CUDA-AFQMC-Real-Mixed)` was failing for missing CUDA.

**Comment by prckent** [comment]
This must be a config issue. nitrogen has cuda 11.6 installed  via RHEL package manger, same as sulfur. nvidia-smi reports as expected.

**Comment by williamfgc** [comment]
@prckent yes, CMake wasn't able to find it (either `PATH` or `CUDACXX` issue). Thanks @ye-luo for narrowing this down.
