### ISSUE TITLE
WFOpt nonlocalpp option

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3791]
When this option is yes, WFOpt recompute NLPP for each given set of parameters during correlated sampling.
What is the motivation to set this to "no"? Save some computation at the cost of correctness.
It just doesn't make sense to me.

**Comment by prckent** [comment]
For a few % of the time this will give a significant speedup (say, near convergence), but for most % of the time this will either slow convergence or perhaps even preclude it. Given how QMCPACK is used today I think we could safely lose the "no" option.
