### ISSUE TITLE
MEMKIND_FATAL issue on NERSC Cori with KNL 

### ISSUE THREAD

**Issue by hzhou23** [QMCPACK/qmcpack#3802]
Hello all, 

I planned to run qmcpack_complex on NERSC Cori with KNL node. The job script is generated by:

 job(nodes=4, queue='debug', hours=0.2,constraint='knl', app='qmcpack_complex',presub=qmc_presub)
 
where my qmc_presub is :

module unload cray-libsci
module load cray-hdf5-parallel
module load gcc
module list

My qmcpack_complex is compiled with parallel. 

When nexus generate the job script and submitted it, it gives me error :
MEMKIND_FATAL : Unable to initialize TBB. 

But if I enter the folder and manually sbatch the same job script generated by nexus, it went through with no issue. 

I am wondering what should be done to make it works without manually submit the job.

**Comment by jtkrogel** [comment]
Does the output from `module list` match in each case?

**Comment by hzhou23** [comment]
> Does the output from `module list` match in each case?

Yes, I copied them and did 'diff' on these, no difference detected.

**Comment by hzhou23** [comment]
> 

Yes, it is reproducible. I will attach the job file generated by nexus and output log here.

**Comment by hzhou23** [comment]
[MEMKIND_FATAL.zip](https://github.com/QMCPACK/qmcpack/files/7995973/MEMKIND_FATAL.zip)

**Comment by jtkrogel** [comment]
Do you get a different result between by hand and Nexus submission if you add `job(...,user_env=False)`?

This will no longer import the user environment, i.e. `#SBATCH --export=NONE` is used.

**Comment by hzhou23** [comment]
> Do you get a different result between by hand and Nexus submission if you add `job(...,user_env=False)`?
> 
> This will no longer import the user environment, i.e. `#SBATCH --export=NONE` is used.

After trying this, there are some other issues with intel module happening. I will try to fix that.

**Comment by mcbennet** [comment]
What does `which qmcpack_complex` show in both cases?

**Comment by hzhou23** [comment]
> 
In both cases, they are targeting at "/global/cscratch1/sd/haihan/build_nersc_cori_knl_cmplx/bin/qmcpack_complex"

**Comment by ye-luo** [comment]
probably something from python environment got involved. Before running qmcpack_complex, run
```
ldd `which qmcpack_complex` > ldd.out
```
run the job with and without nexus and compare output.

**Comment by hzhou23** [comment]
I do see differences in the ldd.out files. When running with nexus, the intel compiler was setting with 2020 version and with manual, it is 2019. 

 Back when I was installing qmcpack on nersc, I manually changed the intel module from 19.0.3.199 to 19.1.2.254, because if I didn't do this, it tells me that cmake needs an Intel compiler 19.1 or higher.

**Comment by hzhou23** [comment]
Just FYI, the issue has been solved. After changing the environment the issue is gone now.

**Comment by jtkrogel** [comment]
Glad to hear it.

**Comment by zhcui** [comment]
> Just FYI, the issue has been solved. After changing the environment the issue is gone now.

May I know what environment you change solves the problem? Thanks!
