### ISSUE TITLE
Add QMC_DATA reference inputs to self-hosted CI

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#3819]
**Is your feature request related to a problem? Please describe.**
https://github.com/QMCPACK/qmcpack/issues/3818 made it through CI since there are several sets of tests that need "large" inputs that are not run if QMC_DATA and the necessary files are not setup. 

**Describe the solution you'd like**
Since we have no storage concerns for self-hosted CI, configure QMC_DATA for these runs. 

**Describe alternatives you've considered**

**Additional context**

A full set of files are locally on sulfur:/scratch/pk7/QMC_DATA_FULL . CI could use a copy of this data, not the current files. Today CI only really needs one of the NiO files, but it is easy to envisage us adding a deterministic molecular run in future based on the molecular performance tests to cover a large open boundaries case.

**Comment by williamfgc** [comment]
@prckent do we also need to add `QMC_DATA` on nitrogen?

**Comment by prckent** [comment]
Yes. For both coverage and consistency.
