### ISSUE TITLE
Code coverage on OpenMP offload code

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3834]
Investigate if it is possible to add code coverage to OpenMP offload code running on `x86_64`.

**Comment by prckent** [comment]
Agreed.  This would need an x86_64 target offload and coverage build with clang13+.

**Comment by williamfgc** [comment]
There is a current issue, as gcov is only supported for gcc builds. I'll see what needs to be done.

**Comment by ye-luo** [comment]
https://clang.llvm.org/docs/SourceBasedCodeCoverage.html
gcov was mentioned.

**Comment by williamfgc** [comment]
Thanks @ye-luo , there is challenges: 
1. Need CMake configuration changes on QMCPACK to allow clang as a valid compiler for gcov
2. Generated XML reports uploaded to Codecov must be compatible
3. Delay Codecov checks in CI

**Comment by williamfgc** [comment]
I need some digging on this.
1. There is a typo in ClangCompiler, I will do a PR to fix it
2. Bad news: `ctest -L unit` w/offload generate a lot of corrupted gcda files that can't be merged, works without offload and `llvm-cov gcov`. Good news: I ended up spinning a docker container with gcc-12 (maybe as an alternative when offload is ready?) and clang-13 compilers in [DockerHub](https://hub.docker.com/layers/193595951/williamfgc/qmcpack-ci/ubuntu22-gcc12-clang13/images/sha256-983b5ee621349102ad7920dc7ad6bc685d4a117965c92c58ff01a5d24715a626?context=repo). 
3. `gcovr` can generate xml reports using `llvm-cov gcov` (at least that's good).

I'll do more digging, but for now it's not straight-forward to integrate offload cases.

**Comment by ye-luo** [comment]
I also experienced hardship with sanitizer running the offload code. It is challenging for tools.

**Comment by ye-luo** [comment]
We made all OpenMP offload code paths accessible by explicitly requesting it.
https://github.com/QMCPACK/qmcpack/pull/3893
So we are running coverage on offload source code with CPU-only build.
