### ISSUE TITLE
Building with GCC/9.1.0 breaks DMC

### ISSUE THREAD

**Issue by tiihonej** [QMCPACK/qmcpack#3854]
**Describe the bug**
Building QMCPACK with GCC/9.1.0 seems to break many things, most importantly DMC runs. Building with 8.3.0 works, although failing some tests. The recommendation is to block building with GCC/9.1.0, if the issue is reproduced elsewhere.

**To Reproduce**
1. release version or git commit hash being built: v.3.13.0
2. cmake command (on CSC Puhti supercluster):
```
module purge
module load gcc/9.1.0 intel-mpi/18.0.5 fftw/3.3.8-omp boost/1.68.0 hdf5/1.10.4-mpi cmake/3.18.2 intel-mkl/2019.0.4
cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DLIBXML2_LIBRARY=/usr/lib64/libxml2.so ..
```
3. full program/test invocation command: `ctest -j 40 --output-on-failure`
4. additional steps: also tested running ordinary DMC calculation, which fail with GCC/9.1.0 but work out with GCC/8.3.0.

**Expected behavior**
Passing the tests. However, also building with GCC/8.3.0 fails many tests, but not as critically.

**System:**
- see above. Not attempted to reproduce elsewhere.

**Additional context**
Newer compilers (e.g. GCC/9.2.0 or Intel/19.1.0) are at the moment unavailable on Puhti, but have been requested. Ctest outputs based on GCC/8.3.0 and GCC/9.1.0 are attached, excluding some of the long tests but giving the general idea.
[ctest_gcc830.txt](https://github.com/QMCPACK/qmcpack/files/8095425/ctest_gcc830.txt)
[ctest_gcc910.txt](https://github.com/QMCPACK/qmcpack/files/8095427/ctest_gcc910.txt)

**Comment by williamfgc** [comment]
@tiihonej   Intel [docs](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compatibility-and-portability/gcc-compatibility-and-interoperability.html) suggest gcc is picked from `PATH`: `By default, the compiler determines which version of GCC or G++ you have installed from the PATH environment variable.` Running `ldd` on the resulting qmcpack executable will show which dependencies are being picked up. Hope it helps, but yeah mixing old with newer stacks can be a problem, we had a similar issue with PGI on Titan.

**Comment by prckent** [comment]
There is at least one other bug. Looking at the failures, e.g. 
short-diamondC_2x1x1_pp-vmcbatch_dmcbatch-4b_sdbatch_jas-1-4 
I noticed

```
  Total number of MPI ranks = 1
  Number of MPI groups      = 1
  MPI group ID              = 0
  Number of ranks in group  = 1
  MPI ranks per node        = 1
  OMP 1st level threads     = 4
  OMP nested threading disabled or only 1 thread on the 2nd level
```
but
```
 Particle Set
 ------------
  Name: e   Offload : 

  All the species have the same mass 1.0000000000
```
and
```
 Time to gather the table = 0.0000074380
  Time to bcast the table = 0.0000006731
  SplineSetReader initialize_spline_pio 0.0438031629 sec
Time spent in creating B-spline SPOs 0.0942856430sec
      Setting delay_rank to default value 1
      Using rank-1 Sherman-Morrison Fahy update (SM1)
      Using walker batching.
      Running on an accelerator via OpenMP offload. Only SM1 update is supported. delay_rank is ignored.
```

in the first case the output is blank after "offload" and the second case the output about the accelerator is wrong. (@ye-luo )

**Comment by prckent** [comment]
I am building a gcc@9.1.0 to run a check here. Our nightlies on sulfur are currently done with gcc@9.2.0 and gcc@11.2.0.

**Comment by ye-luo** [comment]
@prckent It is techincally OpenMP offload code source/path but without being offload. How would you like to word the message. `Running OpenMP offload code path?`

**Comment by prckent** [comment]
@ye-luo Yes. Mentioning accelerator when there is not one in this case may cause confusion.

**Comment by prckent** [comment]
gcc 9.1 + MKL , QMC_MPI=0:
```
cmake -DQMC_MPI=0 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DQMC_DATA=/scratch/pk7/QMC_DATA_FULL/ -DQMC_NIO_MAX_SIZE=32 ../qmcpack/
make -j all
nohup ctest -j 64 -E long --output-on-failure >& ctest.out &
```
```
99% tests passed, 2 tests failed out of 1471
...
Total Test time (real) = 926.26 sec

The following tests FAILED:
        332 - short-H4-orb-opt-1-16-totenergy (Failed)
        334 - short-H4-orb-opt-dmc-1-16-totenergy (Failed)
Errors while running CTest
```

Currently running gcc 9.1 + MKL + OpenMPI 4.1.2.

**Comment by tiihonej** [comment]
Thank you all for the suggestions and taking the time to scrutinize the behavior. I tried several more module combinations with gcc/9.1.0, but none of them solved the problem.

**Comment by ye-luo** [comment]
It also depends on what module system you use, lmod might switch actual libraries based on the loaded compiler. So there are quite a few parameters to be controlled to root the issue.

**Comment by tiihonej** [comment]
Agreed. I'm closing this issue as the root cause remains unknown.
