### ISSUE TITLE
pyscf

### ISSUE THREAD

**Issue by manuelgpda** [QMCPACK/qmcpack#3898]
**Describe the bug**
I think the newest version of PySCF relies on python 3.9 and thus a compatibility issue may arise when trying to use those examples of AFQMC that QMCpack has, since the latest uses python 3.10.

**To Reproduce**

**Expected behavior**

**System:**

**Additional context**

**Comment by ye-luo** [comment]
Do you have any error message to share with?

**Comment by prckent** [comment]
Hi Manuel - Is this your own installation or are you using (say) the virtual machine from the QMCPACK workshop? What goes wrong? I don't think that there is any python 3.10 in AFQMC and QMCPACK, so 3.9 should still be OK. However perhaps something crept in.

**Comment by manuelgpda** [comment]
I installed QMCpack following the instructions for macports. Therefore, I installed python 3.10 for that and thought it was required for QMCpack to work but then I guess I was wrong because if I use python3.8 to execute files on the afqmc example folder, everything works. However, it seems afqmctools was not in PYTHONPATH (so I added it without major problems) and qmcpack is not found when invoked, so I don't know how to solve this. Maybe is this because of initially installing QMCpack with python3.10 but then using python3.8 for these executions?

Anyway, if I, alternatively, try to use the virtual machine for the first example of AFQMC, I manage to get the same afqmc.xml file as described in the tutorials by doing:

`/$HOME/apps/qmcpack/qmcpack/utils/afqmctools/bin/pyscf_to_afqmc.py -i scf.chk -o afqmc.h5 -t 1e-5 -v -q afqmc.xml`

But when trying to use qmcpack, an error appears:

`qmcuser@WorkshopVBX:~/apps/qmcpack/qmcpack/examples/afqmc/01-neon_atom$ qmcpack afqmc.xml > qmcpack.out
`
`Rank =    0  Free Memory =  1690 MB`
`ERROR  Executable not compiled with AFQMC. Recompile with BUILD_AFQMC set to 1.`
`Fatal Error. Aborting at main(). QMC Execution failed.
`

-Manuel

**Comment by prckent** [comment]
First example: Use the full path to the qmcpack executable or put the binary directory in whatever you chose for the build directory on your path. e.g. Run $HOME/someplace/build/bin/qmcpack afqmc.xml 

Second case: The 2021 workshop image has PySCF installed and QMCPACK, but unfortunately without the AFQMC build option that you are interested in. Since you are interested in that it will be quickest for you to follow the macports install route above. However next time we rebuild the workshop image we will enable AFQMC.

**Comment by manuelgpda** [comment]
Thank you for the clarification! I tried what you said and it seems qmcpack is executing now. However, it still gives the following error:
```
(base) user@users-MacBook-Pro-2 01-neon_atom % /path/to/qmcpack/build/bin/qmcpack afqmc.xml > qmcpack.out
ERROR  Executable not compiled with AFQMC. Recompile with BUILD_AFQMC set to 1.
Fatal Error. Aborting at main(). QMC Execution failed.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

The afqmc.xml file is as follows:
```
<simulation method="afqmc">
  <project id="qmc" series="0" />
  <random seed="7" />
  <AFQMCInfo name="info0">
    <parameter name="NMO">23</parameter>
    <parameter name="NAEA">5</parameter>
    <parameter name="NAEB">5</parameter>
  </AFQMCInfo>
  <Hamiltonian name="ham0" info="info0">
    <parameter name="filetype">hdf5</parameter>
    <parameter name="filename">afqmc.h5</parameter>
  </Hamiltonian>
  <Wavefunction name="wfn0" type="NOMSD" info="info0">
    <parameter name="filetype">hdf5</parameter>
    <parameter name="filename">afqmc.h5</parameter>
    <parameter name="cutoff">1e-8</parameter>
  </Wavefunction>
  <WalkerSet name="wset0" type="shared">
    <parameter name="walker_type">CLOSED</parameter>
  </WalkerSet>
  <Propagator name="prop0" info="info0">
    <parameter name="hybrid">yes</parameter>
  </Propagator>
  <execute wset="wset0" ham="ham0" wfn="wfn0" prop="prop0" info="info0">
    <parameter name="ncores">1</parameter>
    <parameter name="timestep">0.01</parameter>
    <parameter name="blocks">100</parameter>
    <parameter name="steps">10</parameter>
    <parameter name="nWalkers">10</parameter>
  </execute>
</simulation>

```

**Comment by prckent** [comment]
You need to rebuild with -DBUILD_AFQMC=1 on the cmake line. i.e. make a new build directory, run cmake and make in that. If you already tried, please share details of the steps you took.

**Comment by manuelgpda** [comment]
I tried it and then another error came up for which I had to rebuild with QMC_COMPLEX=1 but then everything seems to work.

Thank you SO much!

-Manuel
