### ISSUE TITLE
Problems with excited state calculations using the qmcpack input file

### ISSUE THREAD

**Issue by kylanpaa** [QMCPACK/qmcpack#391]
There might be some inconsistencies in the excited state calculations when using the qmcpack input file to arrange the orbitals, at least with release 3.1.0. With oxygen atom everything seemed to work fine. For VO2 the excited state energy ended up being about 15 hartree lower in energy than the ground state. However, if one manually changes the orbitals in the .h5 file then everything is working as expected, that is, the excited state is above the ground state by a reasonable number, roughly 2 eV at the gamma point.

Find attached the qmcpack input files used for the excited state calculation that produces the erroneous behaviour as well as the quantum espresso inputs used in generating the orbitals.

[inputs.zip](https://github.com/QMCPACK/qmcpack/files/1341061/inputs.zip)

**Comment by prckent** [comment]
Are there any differences you can think of that might be relevant between these runs and e.g. the seemingly successful NiO runs? Have you tried a very small cell/low electron count?

**Comment by Paul-St-Young** [comment]
@kylanpaa I think I have seen a similar issue when the SPO set does not have the virtual orbitals splined up. Could you change size="50" to size="51" in <determinant id="downdet">?

**Comment by prckent** [comment]
Does it also fail if the excitation is in the first spin channel? ("updet" here)

**Comment by kylanpaa** [comment]
It has the same effect in the first spin channel as well, and changing the size of the determinant to 51 results in a segmentation fault. I can't think of any particular differences between these and the NiO runs---maybe a different version of qmcpack was used. I was using 3.1.0, and I'm not sure what has been used for NiO. I believe this is the smallest cell for AFM VO2 already, so I haven't tested with less electrons... apart from the single Oxygen atom case.

**Comment by prckent** [comment]
Thanks. 3.2.0 should make no difference. The excitation code has not been touched for a long time, so this is likely an old book keeping bug dating from long ago.

**Comment by Paul-St-Young** [comment]
Hmm,  this is strange. I get reasonable energies when I ran the inputs on my workstation (using qmcpack3.1.0).

ground: -430.42(15) ha
excited: -429.81(22) ha
delta = 22(10) eV

The errorbars need to shrinked much more, but there is not a 15 ha gap between the two states.

Could this bee a machine-dependent problem?

[for_ilkka.zip](https://github.com/QMCPACK/qmcpack/files/1345081/for_ilkka.zip)

**Comment by prckent** [comment]
@kylanpaa Which machine did you run on and how was the code built? (OIC5 and the toolchain?)

**Comment by kylanpaa** [comment]
@Paul-St-Young Did you look at your DFT energy? In hartree units my DFT energy is -414.292533205.

I did my ground state calculation using the sposet builder environment that gives me the DMC energy of -415.580802 +/- 0.002332. If I manually configure the wave function file I get the excited state energy of -415.509796 +/- 0.006340. 

However, in the input the excited state property is only available for the older determinant format, which for me yields a similar value as you report, and thus, it is about 15 hartree lower in energy than the ground state energy calculated using the sposet_builder environment. I just tried the ground state with the older determinant format, and it also gives similar results than you obtain.

So, it seems that there is roughly 15 hartree difference between the sposet_builder and the older determinant format in the energies. The older format has a lot larger variance, however, the Jastrows were optimized in the sposet_builder case. Also the older format is about 16 hartree from the DFT energy.

**Comment by prckent** [comment]
If you run single determinant with no Jastrow, the excited state kinetic energy can be calculated from the sum of the actually occupied single particle kinetic energies.

**Comment by Paul-St-Young** [comment]
@kylanpaa My DFT energy is similar -414.292533 Ha.

However, I get around -415Ha in VMC, and around -430Ha in DMC whether I use <determinantset> or <sposet_builder> to construct the spline orbitals. I also get the same variances in both cases. Did I mess up the input somehow? Please see attached folder.

[spo_vs_det.zip](https://github.com/QMCPACK/qmcpack/files/1349395/spo_vs_det.zip)

**Comment by Paul-St-Young** [comment]
BTW, the both the new (`<sposet_builder>`) and the old (`<determinantset>`) input formats eventually route to the same function `EinsplineSetBuilder_createSPOs.cpp::createSPOSetFromXML` to build the SPO sets, so there should not be any loss of functionality. 

However, the two formats do assume different locations for the various xml attributes. The parser does not complain about unused inputs, so it takes a bit digging around using gdb to confirm that all your inputs are being used.

**Comment by Paul-St-Young** [comment]
@kylanpaa can you attach the input that generated -415Ha DMC energy please?
I took your original input, changed "excited" to "ground", but still got ~-430Ha in DMC.

**Comment by prckent** [comment]
The differences between `<sposet_builder>` and <determinantset>` (both full production features) combined with the lack of checking seems super dangerous...

**Comment by kylanpaa** [comment]
Find attached a zip file containing the original input file for the ground state as well as input files for VMC calculations of the ground state without Jastrows using both the sposet_builder and the older format. For the cases without Jastrows there are also figures of the traces of different observables, which show where the differences emerge, e.g., the variance is over 5 times larger for the "old format" case, and the local and non-local ECPs have large differences whereas electron-electron and kinetic energies are essentially the same. Moreover, the variance to energy ratio is over 8 times larger in the "old format" case compared to the sposet_builder case.

Find below the averaged data for the VMC runs without Jastrows.

VMC ground sposet_builder:

  LocalEnergy           =         -410.8049 +/-           0.0046 
  Variance                 =             58.18 +/-             0.35 
  Kinetic                    =           229.393 +/-            0.030 
  LocalPotential        =          -640.198 +/-            0.030 
  ElecElec                 =            45.838 +/-            0.015 
  LocalECP               =          -330.943 +/-            0.031 
  NonLocalECP         =           -58.644 +/-            0.025 
  IonIon                     =           -296.45 +/-             0.00 
  LocalEnergy_sq      =         168818.86 +/-             3.72 
  BlockWeight            =          16000.00 +/-             0.00 
  BlockCPU                =           8.02454 +/-          0.00069 
  AcceptRatio            =          0.652697 +/-         0.000027 
  Efficiency                =              3.19 +/-             0.00 
  TotalTime                =           3386.35 +/-             0.00 
  TotalSamples           =           6752000 +/-                0 

                            LocalEnergy               Variance           ratio 
qmc  series 0  -410.805109 +/- 0.004561   58.167202 +/- 0.350611   0.1416 



VMC ground old format:

  LocalEnergy           =          -412.811 +/-            0.017 
  Variance                 =            476.64 +/-             2.24 
  Kinetic                    =           229.421 +/-            0.035 
  LocalPotential         =          -642.232 +/-            0.031 
  ElecElec                  =            45.874 +/-            0.016 
  LocalECP                =          -321.603 +/-            0.035 
  NonLocalECP          =           -70.053 +/-            0.032 
  IonIon                      =           -296.45 +/-             0.00 
  LocalEnergy_sq      =         170889.91 +/-            13.72 
  BlockWeight            =          16000.00 +/-             0.00 
  BlockCPU                =           10.9364 +/-           0.0011 
  AcceptRatio             =          0.652625 +/-         0.000030 
  Efficiency                 =              0.23 +/-             0.00 
  TotalTime                 =           3401.23 +/-             0.00 
  TotalSamples           =           4976000 +/-                0 

                            LocalEnergy               Variance           ratio 
qmc  series 0  -412.812074 +/- 0.016874   476.744567 +/- 2.228333   1.1549 

[figs_and_inputs.zip](https://github.com/QMCPACK/qmcpack/files/1349889/figs_and_inputs.zip)

**Comment by jtkrogel** [comment]
The reference (planewave) kinetic energy is 229.381656141 Ha

Both the sposet_builder and old formats get the correct kinetic energy and agree on the electron-electron part of the potential energy.

The 2 Ha drop in the old format VMC is entirely attributable to the ECP potential terms.  Since the variance is huge for the old format case (energy/variance ratio of 1.15), the bug clearly resides with the old format run.

Since sposet_builder and old formats agree for kinetic and elec-elec, but disagree for ECP, the bug probably resides in the wavefunction ratio computation, but not in the value (elec-elec) or laplacian (kinetic) computations.

**Comment by ye-luo** [comment]
@kylanpaa Could you please check your V.opt.xml? I opened the file provided in inputs.zip and it shows symbol="O". Are you using consistent pseudopotential files in your old vs new run?

**Comment by kylanpaa** [comment]
@ye-luo Excellent catch! Thank you! That must be it! The V potential should be the one that's now attached here. I'm glad everything is most likely working like a charm after all.

[V.zip](https://github.com/QMCPACK/qmcpack/files/1349977/V.zip)

**Comment by ye-luo** [comment]
@kylanpaa Please confirm that 
1) Is the excitation working as expected or not?
2) Do the old and new input styles agree or not in VMC?
If they are both fine, we can close this ticket.

**Comment by jtkrogel** [comment]
This still highlights a bug.  QMCPACK should not accept without complaint (+abort) a PP that does not match the effective charge listed in the SPOset.

A user error of this type is preventable by a check within the code and should be implemented.  Once Ilkka confirms Ye's points, we can close this issue and open another one for the actual bug.

**Comment by prckent** [comment]
@jtkrogel Agree

**Comment by kylanpaa** [comment]
@ye-luo I can now confirm that 1. excitations are working as expected, and 2. old and new input styles agree in VMC.

**Comment by Paul-St-Young** [comment]
@kylanpaa what variance are you getting now using the correct V.opt.xml?

I get ~ 12 Ha^2, which is a lot lower than before.

**Comment by kylanpaa** [comment]
Same variance: 12.17(9) Ha^2.

**Comment by ye-luo** [comment]
This is resolved.
