### ISSUE TITLE
MSD offload code sensitive to CUDA toolkit versions

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3922]
**Describe the bug**
single det doesn't seem being affected but 
deterministic-diamondC_2x1x1-gaussian_pp_MSD-vmcbatch-dmcbatch-mwalkers_sdj-1-4 and 1-16
https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=301858
fails with CUDA >=11.3. Checked up to 11.7.
https://github.com/llvm/llvm-project/issues/54633
If you need multi det code path, be sure to use older CUDA version.

**Comment by prckent** [comment]
11.2 is no longer installed; switching to 11.8. If the problem is still there the bug will just need tackling &/or the test skipping in CI

**Comment by ye-luo** [comment]
Workaround #4773 applied

**Comment by ye-luo** [comment]
It seems that CUDA 12.3 no more produces failure.
