### ISSUE TITLE
Tests of STO needed

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#394]
Slater-type orbital functionality needs integration tests.  A good target is Li2 from Umrigar, Nightingale, & Runge (1993), which also includes a simple Pade Jastrow factor.

This system was used as a test in the early development of QMCPACK and likely was run throughout its informal testing period.  Given the amount of benchmark data available in UNR, integration of this test also provides a good opportunity to reverify the correctness and efficiency of the QMCPACK projector/Green's function.

**Comment by ye-luo** [comment]
It is good to have it.
At the moment we only have STO in one of the example He.

**Comment by prckent** [comment]
Agree good to have, particularly since we can compare with historical UNR data.

**Comment by jtkrogel** [comment]
Brief update (full detail coming in a PR soon):  VMC and DMC energies with QMCPACK reproduce UNR results, at least at small enough timesteps for Li2 STO:
```
        VMC          DMC (tau=0.01)
6259  -14.9471(2)  -14.9894(2)
v300  -14.9473(2)  -14.9893(2)
v311  -14.9469(2)  -14.9894(2)
v320  -14.9470(2)  -14.9895(2)
UNR   -14.9472(2)  -14.9895(4) 
6259  -14.94721(5) -14.98944(6)  (very long run)
```

For timesteps larger than ~0.06/Ha, QMCPACK departs strongly from UNR, though still with a quadratic timestep dependence.  The largest timestep we can use for a 1 mHa accuracy is ~0.08/Ha, while for UNR it is ~0.15/Ha.  Total energy differences are likely still accurate for UNR up to 0.25/Ha (5 mHa deviation vs. 38 mHa deviation for QMCPACK).

I am now adding long/short vmc/dmc tests to ctest.

**Comment by prckent** [comment]
We don't have the all electron fixes from UNR ( http://aip.scitation.org/doi/10.1063/1.465195 ) around Eqn 35+. Presumably this is the difference at large time step?

**Comment by jtkrogel** [comment]
Possibly.  I'm not familiar enough with UNR or our partial implementation of it.  

From my brief reading of the paper I don't immediately see why these parts/formulae are not implementable in single particle moves, but if we don't have them then that is the most likely explanation.

I am also checking Ye's other branching schemes (one of which he terms UNR) alongside our original one.

**Comment by prckent** [comment]
Probably sociology and an historic focus on PP calculations.

**Comment by jtkrogel** [comment]
Here are some results with the various branching schemes.  Below are absolute DMC timestep errors for Li2 at tau=0.2/Ha.  Data on the last line has been extracted from the UNR paper.
```
QMCPACK classic -18.2(1) mHa
QMCPACK UNR     -18.3(1) mHa
QMCPACK ZSGMA   -15.4(1) mHa
QMCPACK YL      -11.7(1) mHa
UNR              -2.3(1) mHa
```

**Comment by jtkrogel** [comment]
The zero timestep limits of QMCPACK and UNR are very slightly different (1 mHa):
```
UNR  -14.9890(2) Ha
v320  -14.98997(7) Ha
```

**Comment by ye-luo** [comment]
@jtkrogel Are you using the same Jastrow as UNR paper?

**Comment by jtkrogel** [comment]
Yes, the Jastrow is the same (Pade form).  QMCPACK and UNR VMC energies agree to 0.2 mHa.

**Comment by jtkrogel** [comment]
Tests have been added, issue closed.
