### ISSUE TITLE
Adjust offload CI needed

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3953]
**Is your feature request related to a problem? Please describe.**
Due to #3922,  #3921 was failing CI.
This issue was not exposed due to the fact that CI didn't test complex case.

**Describe the solution you'd like**
Need to force CUDA 11.2 instead of a version found under /usr/local/cuda

**Comment by prckent** [comment]
The immediate action item here is to add a complex build in the CI so this problem can not be missed again.

Do we have any indication if this bug in CUDA will be fixed "sooner" or "later"?

For now  the  CI machine has 11.2 in /usr/local/cuda-11.2 . The driver is 11.6.2 and  generally will be the latest version.

**Comment by ye-luo** [comment]
It is unclear when #3922 will be fixed. 1) I don't have a small enough reproducer 2) ptxas is a black box.
CUDA toolkit versions matters. Newer driver has no problem.

**Comment by williamfgc** [comment]
I'm testing the current `develop` branch with cuda 11.2 as complex builds still give errors as reported in #3530. I reran with cuda 11.6.2 and the same errors appear. The complex cases have always been unstable. I can provide more detail, but currently regressing to 11.2 doesn't buy much on sulfur.

**Comment by ye-luo** [comment]
1. Please check if `clang++ -v` reports cuda 11.2.
2. `which nvcc` returns cuda 11.2
3. make a clean build from scratch.
4. Upload cmake output and ctest output Testing/Temporary/LastTest.log

**Comment by prckent** [comment]
It would help to print more of the standard version reports to stdout as part of the CI in general. e.g. run clang++ -v, gcc -v etc., plus matching "which". This would be helpful in this case and to chase problems when there are version upgrades.

**Comment by ye-luo** [comment]
that is very helpful. In the configure stage before cmake, do `clang++ -v` or `g++ -v`

**Comment by williamfgc** [comment]
Nevermind, I had a lingering `LD_LIBRARY_PATH` in `.bashrc` as revealed by `ldd`. I'll do a PR soon. I'll do a separate PR for adding more debugging information once this works.
