### ISSUE TITLE
savetoqmcpack is not working for unresticted HF of KS in Pyscf

### ISSUE THREAD

**Issue by romanfanta4** [QMCPACK/qmcpack#3958]
I encountered a problem with conversion from Pyscf to QMC for UHF/UKS. 

  File "/apps/all/QMCPACK/3.13.0-intel-2020b-Python-3.8.6/QMCTools/PyscfToQmcpack.py", line 505, in savetoqmcpack
    NbAO, NbMO =mo_coeff.shape
AttributeError: 'tuple' object has no attribute 'shape'

For the same settings the ROHF/ROKS calculations the conversion was fine. My input and output files are attached. I am using PySCF version 2.0.1.

[C-UKS.zip](https://github.com/QMCPACK/qmcpack/files/8520756/C-UKS.zip)

**Comment by prckent** [comment]
@anbenali Any ideas? Did   UHF  support change?

**Comment by anbenali** [comment]
This is either a  pyscf  change or something missing from python2 to python3. Will provide a fix later today or early morning.
