### ISSUE TITLE
QuantumESPRESSO build - dependencies not found in directory UtilXlib

### ISSUE THREAD

**Issue by anselmicz** [QMCPACK/qmcpack#3967]
**Describe the bug**
I'm trying to compile Quantum Espresso (QE) as described in the [documentation](https://qmcpack.readthedocs.io/en/develop/installation.html#installing-and-patching-quantum-espresso). However, the installation fails due to unmet dependencies in UtilXlib. This does not happen when compiling QE without using patch provided in `external_codes`.

**Steps to reproduce the behavior**
1. Run the qmcpack-3.14.0/external_codes/quantum_espresso/download_and_patch_qe7.0.sh
2. patch the UtilXlib Makefile (switch 8 spaces for a tab):

```
diff -ru qe-7.0.orig/UtilXlib/Makefile qe-7.0/UtilXlib/Makefile
--- qe-7.0.orig/UtilXlib/Makefile       2022-04-22 10:20:18.302661000 +0200
+++ qe-7.0/UtilXlib/Makefile    2022-04-22 10:29:42.559498000 +0200
@@ -41,7 +41,7 @@


 esh5_interfaces.o : esh5_interfaces.c
-        $(CC) -std=c99 $(CFLAGS) -c $<
+       $(CC) -std=c99 $(CFLAGS) -c $<

 libutil.a:  $(UTIL)
        $(AR) $(ARFLAGS) $@ $?
```
This is necessary to avoid an error message about using spaces instead of a tabular.

3. Compiling QE using the same process as for an identical build without using QMCPACK-provided patches results in an error.

 ```
make[1]: *** No rule to make target `@hdf5.h@', needed by `esh5_interfaces.o'.  Stop.
make[1]: Leaving directory `/dev/shm/easybuild/build/QuantumESPRESSO/7.0/intel-2020b-forQMCPACK/qe-7.0/UtilXlib'
make: *** [libutil] Error 1
```
Testing using `make depend` provides following message:
```
Checking dependencies...
( if test -x install/makedeps.sh ; then install/makedeps.sh ; fi)
directory FFTXlib : ok
WARNING! dependencies not found in directory UtilXlib:
# some_file.o: @some_module@
esh5_interfaces.o : @hdf5.h@
esh5_interfaces.o : @hdf5_hl.h@
File UtilXlib/make.depend is broken
directory QEHeat/src : ok okkokCI : ok
directory ACFDT/src : not present in /dev/shm/easybuild/build/QuantumESPRESSO/7.0/intel-2020b-forQMCPACK/qe-7.0/install
```

**Expected behavior**
Successful build of patched QE.

**System:**
***Hardware***
[Karolina supercomputer, CPU paritition](https://docs.it4i.cz/karolina/compute-nodes/#compute-nodes-without-accelerators)
***OS***
CentOS Linux 7 (Core)
***Modules provided as QE dependencies***
```
EasyBuild/4.5.4
GCCcore/10.2.0
zlib/1.2.11-GCCcore-10.2.0
binutils/2.35-GCCcore-10.2.0
iccifort/2020.4.304
numactl/2.0.13-GCCcore-10.2.0
UCX/1.9.0-GCCcore-10.2.0
impi/2019.9.304-iccifort-2020.4.304
iimpi/2020b
imkl/2020.4.304-iimpi-2020b
intel/2020b
Szip/2.1.1-GCCcore-10.2.0
HDF5/1.10.7-iimpi-2020b
ELPA/2020.11.001-intel-2020b
libxc/5.1.3-intel-2020b
```

***Where to reproduce***
Due to the nature of this problem, it may be reproduced on any system.

**Additional context**
Problem seems to arise from the patching process, since I am able to successfully compile QE 7.0 with exactly the same settings as when not using QE patch provided in `external_codes`.

**Comment by prckent** [comment]
Thanks for the comprehensive report. To help us reproduce this please can you put your cmake configure line?

**Comment by ye-luo** [comment]
Point 2. Indeed that is a bug of our patch.
Point 3. This is invalid. I think you must start from a clean directory and QE configure should generate all the make.depend from scratch. If the patch is not applied, there should be no trace of esh5_interfaces. If you applied the patch, there is no way to turn off pw2qmcpack and hdf5 is required thus you see the error.

The simple solution is using CMake instead of configure.

FYI. QE 7.0 is the last version of QE we provide a patch for and we have switched to a new way to enable pw2qmcpack directly in QE. The new method has been added in QE develop and will be release by QE. In the new method, we exclusively support CMake instead of configure.

**Comment by ye-luo** [comment]
Point 3: I can reproduce the error
```
make[1]: *** No rule to make target `@hdf5.h@', needed by `esh5_interfaces.o'.  Stop.
```
The auto generation of make.depend (introduced in 7.0) is not happy/smart with the header file detection.
It was my oversight didn't check carefully if the configure route still works reliably.
On the other hand, CMake is the way to move forward. So fixing configure is not my consideration.

@anselmicz please let us know if CMake works for you.

**Comment by anselmicz** [comment]
> FYI. QE 7.0 is the last version of QE we provide a patch for and we have switched to a new way to enable pw2qmcpack directly in QE. The new method has been added in QE develop and will be release by QE. In the new method, we exclusively support CMake instead of configure.

Am I understanding it correctly that QE as a whole will support only CMake builds in versions > 7.0?

Using CMake, I'm experiencing an error with `gipaw` and `w90`. This isn't unique to the QMCPACK patch, it also happens in an unpatched version when using CMake:

```make: *** No rule to make target `gipaw'.  Stop.```
```make: *** No rule to make target `w90'.  Stop.```

Granted, they are external codes, but `gipaw` depends on the QE source (hence why I'm not installing it separately), and `w90` is force built, and their absence would introduce a trade-off to using the QMCPACK-enabled QE version. I'll have a closer look at them later next week.

Other than that, QE compiles successfully.

**Comment by ye-luo** [comment]
> > FYI. QE 7.0 is the last version of QE we provide a patch for and we have switched to a new way to enable pw2qmcpack directly in QE. The new method has been added in QE develop and will be release by QE. In the new method, we exclusively support CMake instead of configure.
> 
> Am I understanding it correctly that QE as a whole will support only CMake builds in versions > 7.0?

No. The new method I referred is that pw2qmcpack is a plugin of QE and you have to enable it via QE CMake. You won't have an configure option to turn pw2qmcpackon.

QE as a whole continues to support both configure and CMake. Since CMake is newer, there are still gaps.

> 
> Using CMake, I'm experiencing an error with `gipaw` and `w90`. This isn't unique to the QMCPACK patch, it also happens in an unpatched version when using CMake:
> 
> `` make: *** No rule to make target `gipaw'. Stop. `` `` make: *** No rule to make target `w90'. Stop. ``
> 
> Granted, they are external codes, but `gipaw` depends on the QE source (hence why I'm not installing it separately), and `w90` is force built, and their absence would introduce a trade-off to using the QMCPACK-enabled QE version. I'll have a closer look at them later next week.
> 
> Other than that, QE compiles successfully.

gipaw is an external code. So its developers need to work with QE to enable that part of feature for CMake. Make an issue to QE gitlab and "@" gipaw developers. wannier90 is enabled in QE CMake by default.

**Comment by anselmicz** [comment]
My mistake, after a check it seems that `w90` compiled, and that in the newer version of QE the `wannier90.x` has been replaced by `wannier_prog.x`.

Thank you so much for your assistance.

**Comment by ye-luo** [comment]
I think `wannier_prog.x` was an unintended change when CMake was introduced in QE. We will change it back to `wannier90.x` to avoid breaking user habit.
