### ISSUE TITLE
Huge time variation at scale on Summit

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3974]
**Describe the bug**
Coming out of https://github.com/QMCPACK/qmcpack/issues/3899#issuecomment-1108844541
Here is my VMC time from the second block. The expectation is flat timing.
```
# node count  block time(sec)
16    2.59
32    2.61
64    2.63
128   2.64
256   2.57
512  36.5
1024  2.69
2048  3.81
4096 27.3
```

**Comment by ye-luo** [comment]
From another 4k node run, the timing is 4.27sec.

**Comment by prckent** [comment]
Are any of the other timings different or is this the only discrepancy? If the nodes or network are sick, we might expect initialization to take longer.

**Comment by ye-luo** [comment]
```
grep  "Initialization Execution time" 
16   21.62 secs
32   21.93 secs
64   23.39 secs
128  31.69 secs
256  31.48 secs
512  36.53 secs
1024 36.71 secs
2048 39.83 secs
4096 50.13 secs
```
Not sure how this is correlated to the other time. We have a gather and bcast. The time should increase.

**Comment by prckent** [comment]
I think the initialization timing shows a different problem in the code that we could task someone with since it is so well defined. My expectation would be for a near constant time or slightly increasing time after an initial ramp. The jump from 64 to 128 nodes is pretty suspicious. Not the most critical problem but would certainly be nice to understand &/or fix. Can you please post the run details so that someone else can reproduce? I assume this is one of the NiO performance runs.

**Comment by ye-luo** [comment]
It was from #3899

**Comment by ye-luo** [comment]
Another run right after storage maintenance. 4096 nodes 3.84sec.

**Comment by ye-luo** [comment]
[n4096.zip](https://github.com/QMCPACK/qmcpack/files/8578066/n4096.zip)
I used https://github.com/ye-luo/qmcpack/tree/measure-load-imbalance code

The second VMC block takes 3.81sec which is above the ~2.6sec level.
By measuring a barrier at the end of every block, I found the slowest ranks/nodes.
minimal wait happens at the slowest rank.
```
    min wait at rank 19842, seconds = 1.3399124146e-04
    min wait at rank 19863, seconds = 1.0204315186e-04
    min wait at rank 19875, seconds = 1.0609626770e-04
    min wait at rank 19875, seconds = 1.0704994202e-04
    min wait at rank 19878, seconds = 7.2002410889e-05
    min wait at rank 19878, seconds = 8.6069107056e-05
    min wait at rank 19878, seconds = 9.5129013062e-05
    min wait at rank 19894, seconds = 8.4877014160e-05
    min wait at rank 19905, seconds = 8.6069107056e-05
    min wait at rank 19905, seconds = 8.7022781372e-05
    min wait at rank 19914, seconds = 8.4877014160e-05
    min wait at rank 19914, seconds = 8.7976455688e-05
    min wait at rank 19914, seconds = 9.5844268799e-05
    min wait at rank 19924, seconds = 7.4148178101e-05
    min wait at rank 19924, seconds = 8.7976455688e-05
    min wait at rank 19932, seconds = 8.4161758423e-05
    min wait at rank 19932, seconds = 8.6784362793e-05
    min wait at rank 23674, seconds = 7.8916549683e-05
    min wait at rank 23688, seconds = 8.2015991211e-05
    min wait at rank 23694, seconds = 8.2015991211e-05
    min wait at rank 23721, seconds = 9.6797943115e-05
    min wait at rank 23724, seconds = 1.0204315186e-04
    min wait at rank 23733, seconds = 1.0704994202e-04
    min wait at rank 23733, seconds = 1.2612342834e-04
    min wait at rank 23733, seconds = 9.0122222900e-05
    min wait at rank 23733, seconds = 9.5129013062e-05
    min wait at rank 23751, seconds = 8.2015991211e-05
    min wait at rank 23751, seconds = 8.7976455688e-05
    min wait at rank 23753, seconds = 8.4161758423e-05
    min wait at rank 23753, seconds = 8.6069107056e-05
```
rank 23733 happens 4 times. So the node id is 3955 (counting starts from 0), the node name is g37n14. It is also part of an old 512 node run which as the second block time 3.66 sec. There seem to be some correlation.

**Comment by ye-luo** [comment]
OLCF help says `We do see some things in the syslog that lead us to believe that the node may be experiencing a less severe version of our "CPU Lockup" issue.` My understanding that this issue is at the OS level (Linux kernel). It remains unclear what is the cause of OS level issue. Now trying with some nodes being filtered out.

**Comment by ye-luo** [comment]
```
#BSUB -csm y
#BSUB -n 86017
#BSUB -R 1*{select[((LN)&&(type==any))]order[r15s:pg]span[hosts=1]cu[type=rack:pref=config]}+86016*{select[(CN)&&(hname!=f03n16)&&(hname!=g21n16)&&(hname!=g37n01)&&(hname!=g37n02)&&(hname!=g37n03)&&(hname!=g37n04)&&(hname!=g37n05)&&(hname!=g37n06)&&(hname!=g37n07)&&(hname!=g37n08)&&(hname!=g37n09)&&(hname!=g37n10)&&(hname!=g37n11)&&(hname!=g37n12)&&(hname!=g37n13)&&(hname!=g37n14)&&(hname!=g37n15)&&(hname!=g37n16)&&(hname!=g37n17)&&(hname!=g37n18)&&(hname!=f37n01)&&(hname!=f37n02)&&(hname!=f37n03)&&(hname!=f37n04)&&(hname!=f37n05)&&(hname!=f37n06)&&(hname!=f37n07)&&(hname!=f37n08)&&(hname!=f37n09)&&(hname!=f37n10)&&(hname!=f37n11)&&(hname!=f37n12)&&(hname!=f37n13)&&(hname!=f37n14)&&(hname!=f37n15)&&(hname!=f37n16)&&(hname!=f37n17)&&(hname!=f37n18)&&(hname!=h37n01)&&(hname!=h37n02)&&(hname!=h37n03)&&(hname!=h37n04)&&(hname!=h37n05)&&(hname!=h37n06)&&(hname!=h37n07)&&(hname!=h37n08)&&(hname!=h37n09)&&(hname!=h37n10)&&(hname!=h37n11)&&(hname!=h37n12)&&(hname!=h37n13)&&(hname!=h37n14)&&(hname!=h37n15)&&(hname!=h37n16)&&(hname!=h37n17)&&(hname!=h37n18)&&(type==any)]order[r15s:pg]span[ptile=42]}
```
with enough nodes being excluded. My 4k node runs as expected 2.63sec in VMC.
