### ISSUE TITLE
Periodic diamond running in v3.11 but not in later versions

### ISSUE THREAD

**Issue by romanfanta4** [QMCPACK/qmcpack#3976]
I am getting the "Fatal Error. Aborting at Unhandled Exception" error for the diamond example from the [QMCWorkshop2021.](https://github.com/QMCPACK/qmc_workshop_2021/blob/master/week5_solids/runs/diamond_example_results/optJ12/example_results/diaqmc.in.xml)
This is happening in the newer versions of QMCPACK(v3.12, 3.13, v3.14), but it is running properly in v3.11.
I've tested it with outputs from Quantum Espresso 6.8 and then even from 7.0 and for QMCPACK v3.11 it is working fine with both but not for newer versions. For the different system, I've got the same outcome.

**System**:
**Hardware**
[Karolina supercomputer, CPU paritition](https://docs.it4i.cz/karolina/compute-nodes/#compute-nodes-without-accelerators)
**OS**
CentOS Linux 7 (Core)
**Loaded Modules:**
  1) GCCcore/10.2.0
  2) zlib/1.2.11-GCCcore-10.2.0
  3) binutils/2.35-GCCcore-10.2.0
  4) iccifort/2020.4.304
  5) numactl/2.0.13-GCCcore-10.2.0
  6) UCX/1.9.0-GCCcore-10.2.0
  7) impi/2019.9.304-iccifort-2020.4.304
  8) iimpi/2020b
  9) imkl/2020.4.304-iimpi-2020b
 10) intel/2020b
 11) XZ/5.2.5-GCCcore-10.2.0
 12) libxml2/2.9.10-GCCcore-10.2.0
 13) bzip2/1.0.8-GCCcore-10.2.0
 14) Boost/1.74.0-iccifort-2020.4.304
 15) Szip/2.1.1-GCCcore-10.2.0
 16) HDF5/1.10.7-iimpi-2020b
 17) ncurses/6.2-GCCcore-10.2.0
 18) libreadline/8.0-GCCcore-10.2.0
 19) Tcl/8.6.10-GCCcore-10.2.0
 20) SQLite/3.33.0-GCCcore-10.2.0
 21) GMP/6.2.0-GCCcore-10.2.0
 22) libffi/3.3-GCCcore-10.2.0
 23) Python/3.8.6-GCCcore-10.2.0
 24) pybind11/2.6.0-GCCcore-10.2.0
 25) SciPy-bundle/2020.11-intel-2020b
 26) h5py/3.1.0-intel-2020b
 27) FFTW/3.3.8-intel-2020b
 28) QMCPACK/3.11.0-intel-2020b-Python-3.8.6

**Additional context**
Input file for QMCPACK adn *.h5 file
[diamond.zip](https://github.com/QMCPACK/qmcpack/files/8562917/diamond.zip)

**Comment by ye-luo** [comment]
Could you please provide the full output file and error file?

**Comment by romanfanta4** [comment]
> Could you please provide the full output file and error file?

Sending just outputs because error files are empty.
[output.zip](https://github.com/QMCPACK/qmcpack/files/8564619/output.zip)

**Comment by prckent** [comment]
(If it would be helpful, we could update the workshop image with the latest release. There should not be any significant changes though).

**Comment by ye-luo** [comment]
I used your xml input and h5 from diamond.zip and C.ccECP.xml from QMCPACK `$REPO/tests/pseudopotentials_for_tests`.
It runs fine on my workstation.
Did you run QMCPACK ctest at least all the deterministic tests on the compute node? https://qmcpack.readthedocs.io/en/develop/installation.html#testing-and-validation-of-qmcpack
I guess you will see massive failure. Right now, it seems that your executable is sick.
I saw you are using an Intel compiler on AMD processor, it may or may not work well. The same concern applies to MKL.
So you need to validate all these dependencies. You can start with no MPI, gcc and AMD recommended BLAS or even netlib blas/lapack and then gradually switch to your preferred compiler and optimized libraries.

**Comment by romanfanta4** [comment]
Ok, thank you for the advice. Installation of the QMCPACK is done by an external IT specialist at the national computing center, so I have no idea if he did all tests.
