### ISSUE TITLE
A consistency check needed for particle description and pseudopotential

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#399]
#391 indicates a need for a consistency check between the valence charge of an ion in particle description and its pseudo charge recorded in pseudo-potential file .

**Comment by ye-luo** [comment]
Coded fix already. Not good to have last minute PR. Will PR after 3.3 release.

**Comment by prckent** [comment]
OK to commit now. I am not going to get to #528 until late next week. #528 is the blocker for 3.3.
