### ISSUE TITLE
clang support on Summit

### ISSUE THREAD

**Issue by fyzibxm** [QMCPACK/qmcpack#4018]
Hi All
 I want to do some performance tests across different platforms. I have an account on Summit and also on m100 (very similar to Summit) https://wiki.u-gov.it/confluence/pages/viewpage.action?pageId=336727645 On Summit clang build uses some private module files. Can somebody provide more details on how to set up this chain? On Summit I have just tried to replace private modules with llvm/12.0.0 or llvm/10.0.1 but it is not working. Thanks for the answer.
Jan

**Comment by ye-luo** [comment]
Regarding Summit. Private modules has been moved to a global accessible space. See https://github.com/QMCPACK/qmcpack/pull/4020/files You may avoid building LLVM.

For building LLVM  on your machine, you may modify the recipe https://github.com/ye-luo/llvm_recipes/blob/master/olcf_summit/llvm_20220317/upstream-script.sh

**Comment by fyzibxm** [comment]
Thank you very match. During compilation it has produced a lot of warnings
warning: <unknown>:0:0: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
I suppose this could affect performance ...

**Comment by ye-luo** [comment]
@fyzibxm ignore the warning.
