### ISSUE TITLE
CUDA 11.7 doesn't compile std::map when using gcc 12.1 as a host compiler

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4039]
**Is your feature request related to a problem? Please describe.**
Test a compilation in CMake and issue necessary stopper and suggestions (change CMAKE_CXX_COMPILER or use CMAKE_CUDA_HOST_COMPILER).

**Comment by prckent** [comment]
Sensible to issue a stopper. gcc 12.1 was released on May 6 https://www.gnu.org/software/gcc/gcc-12/ while CUDA 11.7, released on May 12, only claims support for gcc <=11 https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements

**Comment by prckent** [comment]
Closed by #4041
