### ISSUE TITLE
Verbosity level of output should be settable

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#404]
At least half the current output should not be printed for "normal" users with well functioning calculations, while "debug" or "verbose" output could potentially require more than we currently print. 

It would be helpful if the verbosity level can be set in the input XML as well as on the command line.

I suggest we discuss implementation here before someone does it. e.g. Could we have a per XML section verbosity parameter? i.e. set DMC to verbose but leave the wavefunction setup at a default, or would that be too fiddly/not help any problems? Are two settings "normal", "high" enough?

**Comment by jtkrogel** [comment]
I think if information is potentially useful, then it should be printed somewhere.  Perhaps we have a stripped down and very clean set of info printed to stdout, while a much more detailed ("verbose") set of information is printed to a different output/log file with a standardized name?

**Comment by prckent** [comment]
Doing I/O is extremely problematic on HPC systems, so I am not keen to log extensively by default.

**Comment by jtkrogel** [comment]
A single verbosity parameter is probably sufficient.  Starting with normal/high as options and expanding if ever necessary sounds reasonable to me.

QMCPACK currently lacks an input section to communicate global information.  We could co-opt <project/> for this as it does contain some global info already (id and series), and just add <parameter/>'s.  This would avoid the proliferation of xml elements, but we could alternatively add e.g. <controls/> or <global/> for this purpose.

**Comment by prckent** [comment]
So the suggestion is:
```
<simulation>
   <project id="qmc_short" series="0">
      <application name="qmcapp" role="molecu" class="serial" version="1.0" verbosity="high"/>
   </project>
```
This would also be a good place to put the command line options

**Comment by jtkrogel** [comment]
I was actually thinking:

```
<simulation>
   <project id="qmc_short" series="0">
      <parameter name="verbosity">   high  <parameter/>
   </project>
```

The `<application/>` element doesn't add much, and I think we can stop using it.  I agree that this is a good place to add all the other command line options.  Perhaps we move "id" and "series" to parameters too, but leave the option to read them as attributes for backwards compatibility.

**Comment by prckent** [comment]
Better.

Is the application element actually needed? The code screams "legacy".

**Comment by markdewing** [comment]
I think we will want some way of adjusting the output per-section - particularly at the debug level. Otherwise there may be too much to wade through to get to the information of interest.   Probably by adding tags or labels to parts of the code, and then use a command line parameter to adjust the tags (-verbose-tag or -debug-output="wavefunction").     Even if this isn't in the initial version, we should make sure there is a path to implement it.

**Comment by jtkrogel** [comment]
@prckent I don't think so.  "molecu" for example refers to one of David's QMC codes ((molec)ule (C)hampaign-(U)rbana ?), so definitely it is a legacy reference.

**Comment by markdewing** [comment]
When setting command line parameters in the input file - how will that work with ensemble runs?   Allow each run to have different settings, quit with an error if they are different, let the last one read in win?

**Comment by markdewing** [comment]
Some ideas on the API for implementation (not sure where best to discuss this, putting it here):

Currently, the code uses
 - cout/cerr
 - LOGMSG, WARNMSG, ERRORMSG, and DEBUGMSG macros
- app_log, app_warning, app_error, app_debug streams

We should move to a single style for outputting log message. I would like to remove the first two, and use just the streams.
For the verbosity setting, we need some way to split app_log into separate streams.
One idea is to make a new stream called app_summary() for the low verbosity setting, and continue using app_log() for the high verbosity setting.

**Comment by lshulen** [comment]
Agree with moving everything to streams.

Also think you could have the verbosity set either at the verbose level or per tag.  Internally tags would first look at their own attributes and then to the global setting.  This would also allow incremental implementation.

**Comment by prckent** [comment]
@lshulen Good suggestions.

**Comment by markdewing** [comment]
There now exists a framework for output based on verbosity level.   The level can be set via the command line. 
What still needs to be implemented is setting verbosity level in the XML input file.  Implementing this feature is going to be a lower priority, especially compared to cleaning up the output.

**Comment by prckent** [comment]
QMCPACK also creates a variety of data files from the pseudopotentials, jastrow, and spline tables. This is all rather undocumented, but they are intended to be convenient for plotting. 
Suggestion: only write *.pp.dat, J*.dat, einspline.tile.*.dat when verbosity is high?

**Comment by lshulen** [comment]
I think this depends on your mode of operation.  For instance when doing a twist averaged calculation, it is rarely necessary to look at the J*.dat or einspline.tile.*.dat files.  Could be persuaded they should be available at default level, but there should be a verbosity level that disables them.

**Comment by ye-luo** [comment]
einspline.tile* file needs to be written always. They are useful for promoting electrons. It is a bit sad that a feature requires a specific run with non-default verbosity. J*.dat or *pp.dat can be skipped in daily runs. Regarding J*.dat, just read the coefficients in the input file is a lot easier.

**Comment by jtkrogel** [comment]
The B-spline Jastrow coefficients are not the same as the function values (J*.dat).  For novice /non-programmer users, plotting the functions as smooth curves is better IMO.

**Comment by ye-luo** [comment]
I mean if you don't see your few coefficients in the input smooth. No need to look at J*.dat.

**Comment by prckent** [comment]
I propose closing this issue now that there is a global verbosity setting. We should add issues for specific cases that still need verbosity control or finer grained control (e.g. GPU code prints init info for every GPU by default...)

**Comment by prckent** [comment]
Considering done. We have global control as a result of @markdewing . Finer grained control can be added as needed.
