### ISSUE TITLE
Get Batched NLPP Working With Spinors

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#4043]
**Is your feature request related to a problem? Please describe.**
Identified in PR #4042 .  Basically, NLPP batched evaluation uses VirtualParticleSet.  This does not have properly allocated spin arrays, and the NLPP evaluations don't pass spin information into the VirtualParticleSet.  At the moment, PR #4042 stops the user from hitting this point and resizes the spins array, like every other ParticleSet interface/allocation. 

**Describe the solution you'd like**
Need an expanded interface to pass or update spin values for the virtual particle moves.  This way for spinor evaluations, we don't get undefined or unexpected behavior.  Unit test should also be included with updated interface.  Additionally, such an interface should help get batched NLPP evaluation working for spin-orbit pseudopotentials.  

**Describe alternatives you've considered**
None

**Additional context**

**Comment by camelto2** [comment]
yes, closed by #4375

**Comment by camelto2** [comment]
and is also working for the mw_ APIs as well
