### ISSUE TITLE
Implement Batched NLPP Evaluation for Spin-Orbit Pseudos.

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#4044]
**Is your feature request related to a problem? Please describe.**
Spin-orbit pseudo evaluation currently follows the legacy code path, whereby the required wavefunction ratios are done through proposed moves to quadrature points.  An easy point for optimization is to translate the existing batched NLPP evaluation algorithm to the spin orbit term.  This will require resolution of Issue #4043.

**Comment by ye-luo** [comment]
@rcclay @camelto2 is this done?

**Comment by camelto2** [comment]
yes, this is done
