### ISSUE TITLE
Need consistent input tags in pade Jastrows.

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#413]
Pade uses `var`
Pade2 takes `Var` and `parameter`

Should at least all support `parameter`.

**Comment by prckent** [comment]
The difference between pade and pade2 should also be described in the manual. Only pade2 is currently described.

**Comment by jtkrogel** [comment]
The introduction of "var" is in part to make things easy for nexus (which operates under the assumption that "parameter" => only a name/value pair.  It is easier to accomodate the additional information (i.e. "id") by using <var/> separately.  No problem with supporting both ways, though.
