### ISSUE TITLE
Multi issue with gcc 13 dev

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4184]
**Describe the bug**
```
diff --git a/external_codes/boost_multi/multi/include/multi/detail/serialization.hpp b/external_codes/boost_multi/multi/include/multi/detail/serialization.hpp
index 716bca264..2a10c5393 100644
--- a/external_codes/boost_multi/multi/include/multi/detail/serialization.hpp
+++ b/external_codes/boost_multi/multi/include/multi/detail/serialization.hpp
@@ -4,6 +4,7 @@
 #ifndef MULTI_DETAIL_SERIALIZATION_HPP
 #define MULTI_DETAIL_SERIALIZATION_HPP
 
+#include <cstdint>
 #include<algorithm>  // for_each
```
Need this patch to make the code compile other wise got error about undefined "std::uint32_t"

**Comment by correaa** [comment]
This was fixed some time ago and it is in the last release.
As per the other issue, I am going to update multi in QMCPACK to reflect this.

**Comment by ye-luo** [comment]
@correaa could you update multi? Stuck with gcc 13.

**Comment by correaa** [comment]
yes, sorry, I got distracted with finishing the other PR before updating.

**Comment by ye-luo** [comment]
Good with https://github.com/QMCPACK/qmcpack/pull/4264
