### ISSUE TITLE
Disable configuration writing upon request in batched drivers

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4195]
**Describe the bug**
`<qmc method="linear" move="pbyp" checkpoint="-1">` the "-1" should disable writting config.h5 upon driver exit.
Legacy driver does this but not batched drivers.

**Comment by quantumsteve** [comment]
It looks like checkpoint is being read inside `QMCDriver::process` which is a pure virtual function in QMCDriverNew.

https://github.com/QMCPACK/qmcpack/blob/353654b72ce7a55a0a6f9975ef2d20b64483464c/src/QMCDrivers/QMCDriver.cpp#L194
https://github.com/QMCPACK/qmcpack/blob/353654b72ce7a55a0a6f9975ef2d20b64483464c/src/QMCDrivers/QMCDriver.cpp#L435

Where do you recommend this logic be placed?
