### ISSUE TITLE
Changes to parameter derivative evaluation break parameter derivative tests

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#4203]
PR #4194 breaks some of the parameter gradient tests.

Such as https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-He_orb_rot_jastrow_param_grad_batch-1-16-jud_b&date=2022-08-24

Run the affected tests with ctest -R short-He_orb_rot*

Interestingly, the gradient test passes (the analytic vs numerical gradients are fine).  It's the comparison to the external value that fails.

It also only affects the batch driver, not the legacy driver.

**System:**
Happens on desktop and CDash nightly testing

**Comment by ye-luo** [comment]
It is a statistical test. What is "external value"?

**Comment by markdewing** [comment]
The values are 100 sigma (or more) off the reference value.  They're clearly different.

**Comment by markdewing** [comment]
The issue is in these lines.
https://github.com/QMCPACK/qmcpack/blob/719a09ef8f6c93449d026c12cd8f4475d5af403a/src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp#L369-L370

**Comment by markdewing** [comment]
I think the issue is a few lines earlier.
https://github.com/QMCPACK/qmcpack/blob/719a09ef8f6c93449d026c12cd8f4475d5af403a/src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp#L366
 
Compare with the similar line in the legacy driver
https://github.com/QMCPACK/qmcpack/blob/719a09ef8f6c93449d026c12cd8f4475d5af403a/src/QMCDrivers/WFOpt/QMCCostFunction.cpp#L296
