### ISSUE TITLE
Force backflow to use the new spline implementation.  

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#421]
To be able to run & optimize, backflow currently builds the legacy EinsplineSetExtended SPO’s.  This needs to be shifted over to the new BsplineSet<SplineAdoptor> type orbitals with construction routed through the SplineAdoptorReader classes. Dependency:  resolve #420.

**Comment by ye-luo** [comment]
Once #420 is resolved, backflow should work with the SoA spline implementation out of the box. No work is needed in the builder.
