### ISSUE TITLE
[AFQMC] wOvlp.sizes(2)?

### ISSUE THREAD

**Issue by correaa** [QMCPACK/qmcpack#4228]
https://github.com/QMCPACK/qmcpack/blob/353654b72ce7a55a0a6f9975ef2d20b64483464c/src/AFQMC/Estimators/MixedRDMEstimator.h#L97

@mmorale3  Is the `wOvlp..size(2)` a bug? should be `wOvlp.size(1)`, right?

**Comment by mmorale3** [comment]
Yes, it is a bug, should be wOvlp.size(1).

**Comment by correaa** [comment]
Thanks.

Same thing here I guess.

`    if (wDMsum.size(0) != wset.size() || wDMsum.size(2) != nx)`
