### ISSUE TITLE
Bump minimal CI compilers versions

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#4242]
**Is your feature request related to a problem? Please describe.**
QMCPACK has a two-year rule support for minimal compiler versions supported. Some GCC compilers toolchains in CI predate this two year limit.

**Describe the solution you'd like**
Bump minimum CI version on sulfur, nitrogen and migrate to Ubuntu 22 containers for GitHub Actions CI

**Describe alternatives you've considered**

**Additional context**
Related to PR #4236 

- [ ] use and test gcc-9 on sulfur and nitrogen, RHEL8 uses gcc-8 by default

**Comment by prckent** [comment]
The official newer gcc toolsets are already installed on sulfur and nitrogen, no need to install anything.

From another script:
```
# Use GCC toolset on Red Hat systems to use
# recent compilers with better architecture support.
# e.g. dnf install gcc-toolset-11
if [ -e /opt/rh/gcc-toolset-11/root/bin/gcc ]; then
    echo --- Added gcc-toolset-11 to path for RHEL provided GCC11 compilers
    export PATH=/opt/rh/gcc-toolset-11/root/bin/:$PATH
else
if [ -e /opt/rh/gcc-toolset-10/root/bin/gcc ]; then
    echo --- Added gcc-toolset-10 to path for RHEL provided GCC10 compilers
    export PATH=/opt/rh/gcc-toolset-10/root/bin/:$PATH
fi
fi
```

**Comment by ye-luo** [comment]
Ubuntu 20 is gcc-9 based and all the github action CI works fine. I doubt the need of updating container images.

**Comment by williamfgc** [comment]
@prckent @ye-luo thanks, I updated the description

**Comment by prckent** [comment]
I just checked: toolsets for gcc9, 10, 11 are already installed
