### ISSUE TITLE
Jastrow optimization with SOECP no longer working

### ISSUE THREAD

**Issue by Hyeondeok-Shin** [QMCPACK/qmcpack#4297]
**Describe the bug**
Since QMCPACK 3.15.0, Jastrow optimization with SOECP is giving failure with following message,

terminate called after throwing an instance of 'std::logic_error'
  what():  Bug!! SOECPotential::evaluateValueAndDerivativesmust be overloaded when the OperatorBase depends on a wavefunction.

As it normally works on QMCPACK 3.14.0, a trigger looks to be located between 3.14.0 and 3.15.0.

**To Reproduce**
Try VTe2 optimization located on
https://anl.box.com/s/okkc0r0iuvhe5fzbd63kte62jdwqk8gr

**Expected behavior**
Jastrow optimization should work normally with SOECP.

**System:**
 - system name 
 theta, summit

**Comment by prckent** [comment]
Thanks for catching this Hyeondeok. Seems we didn't factor that this can take a different execution path; we'll need a deterministic test to stop this recurring.

**Comment by Hyeondeok-Shin** [comment]
Yes, I'll add the test for SOECP to catch related issue once it has resolved.

**Comment by ye-luo** [comment]
Need an actual implementation in SOECP. It was working because of ignoring its contribution.

**Comment by camelto2** [comment]
Yes this was something overlooked. I will put it on the todo list
