### ISSUE TITLE
twist_info files not copied to results

### ISSUE THREAD

**Issue by camelto2** [QMCPACK/qmcpack#4301]
**Is your feature request related to a problem? Please describe.**
When nexus generates multiple twists, it creates the *.twist_info.dat files which contain the kpoint weights. qmca knows how to read those for weighted twist averaging, but they aren't copied to the "results" directory and instead are only in the "runs" directory. This is fine when runs and results are the same, but I like to put my runs on scratch directories which could get purged and then have the results point to somewhere more permanent so that I always have the input xml, stat.h5, scalar.dat, etc

**Describe the solution you'd like**
copy *twist_info.dat files to results as well. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jtkrogel** [comment]
This can be done by updating the `get_output_info` function of `BundledQmcpackInput` class in `qmcpack_input.py` to include the `twist_info.dat` file in the list called `outfiles`.

**Comment by camelto2** [comment]
ok cool I'll have a look and make a PR

**Comment by prckent** [comment]
Closed by #4302
