### ISSUE TITLE
Removing useBuffer option in WF optimization

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#433]
useBuffer was introduced before the analytic derivatives are implemented. Nowadays, this code path is no more useful and doubles work when new features are introduced. I'm going to remove this code path. Let me know if there is any concern by Friday Oct. 27.

**Comment by jtkrogel** [comment]
Could you explain a little more about what functionality will be lost by removing this option?

**Comment by ye-luo** [comment]
Basically nothing. I think all the optimization executes well as no buffer is the default.

**Comment by prckent** [comment]
How was usebuffer used in the past?

**Comment by ye-luo** [comment]
usebuffer saves static components during optimization. For example, it saves the determinants of each sample (not just each walker) in a Jastrow-only optimization. When a new set of parameters is proposed, the correlated sampling (CS) can use the saved determinants to update NLPP if nonlocalpp=yes.
if nonlocalpp=no, only wasting memory.
if nonlocalpp=yes, oneshiftonly does only 1 CS, adaptive does 3 CS, quartic does 7 CS.
In a large simulation, you can not use it because of the memory. In a small simulation, recomputing is so cheap.
Even in nonlocalpp=yes, we can avoid using determinants by saving just the ratios used for NLPP.
if determinants are also optimized, it is not useful at all.

**Comment by prckent** [comment]
This is a decision to always recompute the wavefunction and gradients and to not buffer constant parts. Given the trend towards greater optimzation and techniques to evaluate derivatives efficiently, I am OK with removing the buffering for the reasons you give. For now at least it is vastly more important that we have good Jastrows and robust optimizers. 

Q. How do varying the availability of usebuffer affect runtime of the optimizer for simple cases that someone new to QMC might encounter? e.g.  one and two body Jastrow only with single Slater determinant, 54 atoms of bulk silicon, or running one-two-three body Jastrow multi determinant small molecule?

**Comment by ye-luo** [comment]
NiO S8 32 atom 384 electron J12:
OneShiftOnly:
```
OSO-buffer-nlpp/opt-NiO-fcc-S8.out-  QMC Execution time = 7.1629e+01 secs 
OSO-buffer/opt-NiO-fcc-S8.out-  QMC Execution time = 6.1625e+01 secs 
OSO-nlpp/opt-NiO-fcc-S8.out-  QMC Execution time = 7.7717e+01 secs 
OSO/opt-NiO-fcc-S8.out-  QMC Execution time = 6.1545e+01 secs 
```

adaptive:
```
adaptive-buffer-nlpp/opt-NiO-fcc-S8.out-  QMC Execution time = 1.7153e+02 secs 
adaptive-buffer/opt-NiO-fcc-S8.out-  QMC Execution time = 1.3212e+02 secs 
adaptive-nlpp/opt-NiO-fcc-S8.out-  QMC Execution time = 1.9585e+02 secs 
adaptive/opt-NiO-fcc-S8.out-  QMC Execution time = 1.3099e+02 secs 
```
no nlpp + buffer is a waste of time as expected.
nlpp + buffer saves 12% over nlpp
no nlpp is the fastest.

C2 MSD J123:
```
OSO_buffer_nlpp/qmc_short_pp_msdj.out-  QMC Execution time = 1.4476e+00 secs 
OSO_nlpp/qmc_short_pp_msdj.out-  QMC Execution time = 1.5033e+00 secs 
OSO/qmc_short_pp_msdj.out-  QMC Execution time = 1.2207e+00 secs 
```
Basically you don't feel the recomputing.

**Comment by prckent** [comment]
Thanks. The buffer is definitely not worth it then. It is not "enabling", i.e. significantly faster.

**Comment by ye-luo** [comment]
completed
