### ISSUE TITLE
Need at least cmake 3.21 on olcf ROCm CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4335]
**Is your feature request related to a problem? Please describe.**
Would like to enable hip as a language in cmake and need newer cmake.

**Comment by prckent** [comment]
Nightlies are now using CMake 3.24.2 for the hip builds
https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=370929

**Comment by ye-luo** [comment]
There are a few more steps to follow
1. update CI to >=3.21
2. merge hip language PR, hopefully no pain shows up.
3. change nightly script. HIP_ARCH -> CMAKE_HIP_ARCHITECTURES.
