### ISSUE TITLE
Build failure when MPI is off with parallel HDF

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#4370]
**Describe the bug**
Currently a No MPI build fails at build time when a parallel HDF5 version is passed as it still requires `#include <mpi.h>`.
The warning at config time should be an error:

```
CMake Warning at /usr/share/cmake-3.22/Modules/FindHDF5.cmake:745 (message):
  HDF5 found for language C is parallel but previously found language is not
  parallel.
Call Stack (most recent call first):
  CMakeLists.txt:656 (find_package)
```

**To Reproduce**
1. develop branch
2. cmake command:
   
```
cmake -GNinja \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DQMC_MPI=0 \
      -DQMC_COMPLEX=0 \
      -DHDF5_ROOT=/opt/hdf5/openmpi/1.12.1/ \
      ..
```

4. Just try to build with ninja or 
5. additional steps

**Expected behavior**
Either initial configuration should fail or find a workaround to still enable parallel HDF5 consumption with MPI turned off in QMCPACK

**System:**
Ubuntu 22.04

**Additional context**
Assigned this to @PhilipFackler as a first time contribution

**Comment by prckent** [comment]
Surprised that this doesn't already abort, but worth catching in CMake and printing a helpful error - it is the kind of thing that can trip people up on new systems.

**Comment by ye-luo** [comment]
This is a very annoying issue.
To my best knowledge, MPI-enabled hdf5 library builds cannot be used with non-MPI code.
We need a simple test in cmake to see if
```
#include <hdf5.h>
int main() {}
```
compiles or not.
