### ISSUE TITLE
AFQMC with ROHF trial wavefunction

### ISSUE THREAD

**Issue by HehnLukas** [QMCPACK/qmcpack#4399]
Dear all, 

this is more a question than an issue.
I am trying to run AFQMC calculations using a ROHF trial wavefunction from PySCF. While there are great examples here [qmcpack/examples/afqmc at develop · QMCPACK/qmcpack · GitHub](https://github.com/QMCPACK/qmcpack/tree/develop/examples/afqmc) on how to run AFQMC using RHF or UHF trial wavefunctions I just want to make sure that I am doing everything correctly in case of a ROHF trial wavefunction.

For example, when having obtained a ROHF checkpoint file from PySCF, does one need to apply the integral generation script pyscf_to_afqmc.py with or without the “-a/--ao” flag, which tells the script to transform the integrals to an orthogonalized atomic orbital basis rather than the MO basis. This flag is required in case of a UHF trial wave function but not in case of a RHF wave function. So I am not sure about how I need to do this correctly in case of a ROHF trial wave function.

Furthermore, in the afqmc.xml file, do I need to specify walker_type COLLINEAR (as in case of UHF) or rather walker_type CLOSED (as in case of RHF).

Help would be very much appreciated! Thank you very much!

**Comment by prckent** [comment]
Hehn - I was hoping that one of the AFQMC folks would respond to this; you have a good question as regards choices for UHF vs RHF. I suggest you try contacting Miguel Morales (@mmorale3 ) who is now at the Flatiron Institute if he does not respond here.

**Comment by fdmalone** [comment]
For the second part, walker_type should be COLLINEAR as CLOSED assumes Na == Nb.

**Comment by HehnLukas** [comment]
Thank you very much!
I just did the sanity check you recommended and it seems that for the systems I have been studying so far everything is correct when using ROHF.
