### ISSUE TITLE
 Inbound license for contributions

### ISSUE THREAD

**Issue by chrisgoodyer** [QMCPACK/qmcpack#440]
Hi.

Can you confirm that contributions to the project are licensed inbound to the project under the same license as the outbound license?

Thanks.

Chris

**Comment by prckent** [comment]
Yes. If it would help to setup a formal contributor agreement and tracking process please let us know, either here or by email. Examples from other projects that are convenient to work with would help, plus explanations why.

**Comment by prckent** [comment]
The same considerations also apply to the in-development miniapps, https://github.com/QMCPACK/miniqmc and https://github.com/QMCPACK/miniAFQMC .

**Comment by chrisgoodyer** [comment]
Hi.

I'm told that it's useful to have at least a statement in the README to the effect that inbound is the same as outbound.  This confirmation should be fine for us (at Arm) for now.  I'll let you know if we ever ended up needing more.
