### ISSUE TITLE
Change orbital rotation input

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4428]
Current orbital rotation input looks like this
```
    <sposet_collection  type="MolecularOrbital" transform="yes" source="ion0">
      <sposet basisset="LCAOBSet" name="spo" size="4" optimize="yes">
        <... usual LCAO input>
        <opt_vars size="4">
          -6.2352e-02 1.5072e-02 8.3825e-02 -2.4339e-02
        </opt_vars>
     </sposet>
  </sposet_collection>
```
but I would like to propose the following change.
```
    <sposet_collection  type="MolecularOrbital" transform="yes" source="ion0">
      <sposet basisset="LCAOBSet" name="spo_orig" size="4">
        <... usual LCAO input>
     </sposet>
     <rotated_sposet name="spo_rorated" spo_ref="spo_orig" size="4">
        <opt_vars size="4">
          -6.2352e-02 1.5072e-02 8.3825e-02 -2.4339e-02
        </opt_vars>
     </rotated_sposet>
  </sposet_collection>
```

|       | old |new |
| ----------- | ----------- | ----------- |
|    |   optimize="yes"    | explicit "rotated_sposet" node|
|  number of sposets exposed  | 1("spo")   | 2("spo_orig", "spo_rotated") |
| rotation basis size | unspecified, all MOs | possible selection at  spo_orig level |

**Comment by PDoakORNL** [comment]
I like the structure of the input much better, but I feel like it would be better to still provide a hint this involved optimizing the sposet.  

So `rotated_sposet` -> `optimized_sposet`

I'm not sure I understand the idea about specifying the rotation basis size.    If I have a optimized sposet what would
it mean if its size != spo_ref.size.  I assume it must be <= and if it is < then?  do they count down from the HOMO/VB?  What if I want to optimize unoccupied MO's?  What if I want to pick an choose say I have several bands near the band edge but only care about the ones with high dispersion?

How would i do those things now?

**Comment by ye-luo** [comment]
> I like the structure of the input much better, but I feel like it would be better to still provide a hint this involved optimizing the sposet.
> 
> So `rotated_sposet` -> `optimized_sposet`

I resist calling it optimized_sposet. orbital rotation is only one way of optimizing SPOSet. This is going a through a layer of RotatedSPO and thus named the input tag rotated_sposet.

> I'm not sure I understand the idea about specifying the rotation basis size. If I have a optimized sposet what would it mean if its size != spo_ref.size. I assume it must be <= and if it is < then? do they count down from the HOMO/VB? What if I want to optimize unoccupied MO's? What if I want to pick an choose say I have several bands near the band edge but only care about the ones with high dispersion?
> 
> How would i do those things now?

What we are optimizing is the occupied orbitals of rotated spo which are all the original orbitals multiplied by the rotation.
Unoccupied orbitals of the rotated sposet are not contributing to sampling/energy. Or we can say rotated sposet only has occupied orbitals.

We don't support down select occupied orbitals during optimization right now.

**Comment by markdewing** [comment]
I'm trying to implement this and running into some issues with ownership of the SPOSet's.

In the current implementation, the RotatedSPOs takes ownership of the SPOSet that it is applied to.  And the original SPOSet never enters the SPO map that SPOSetBuilderFactory maintains.

With the proposed change, the original SPOSet is also in the SPO map.  And now the SPO map and RotatedSPOs are in conflict over who should own the original SPOSet.

I tried changing RotatedSPOs to use a reference, but then the makeClone makes a copy of the SPOSet, and there's nowhere local to the object to put it.

**Comment by ye-luo** [comment]
@markdewing I thought about this issue. In the splitting input case, the original SPOSet should enter the SPOSet map in SPOSetBuilderFactory. RotatedSPO needs to make a copy of the original SPOSet and owns only the copy. However, this copy process cannot  be done via makeClone because that is intended for making walker clone copies. I think we need to add an API SPOSet::makeIndependentCopy.

**Comment by markdewing** [comment]
What needs to be different from makeClone?  Does it need to copy the coefficients as well?

While I like the new input format to make orbital rotation more obvious, having both the original and rotated SPOs available by name introduces the possibility of a new kind of error.  A user can write an input file that intends to use rotated version of the SPOs, but accidentally refers to the original ones instead.  Is there a use-case where the input file contains rotated SPOs, but using the original SPO set is necessary?

**Comment by ye-luo** [comment]
I was thinking of running estimators involving original sposet which had the connection to a mean-field method. Rotated orbitals (VMC determined) may not be straightforward used for comparison.

Since anyway we need to keep the original one somewhere, I'd rather make it explicit than implicit.

**Comment by prckent** [comment]
>Is there a use-case where the input file contains rotated SPOs, but using the original SPO set is necessary?

I think that the use case mentioned by Ye argues for two SPO sets, not an original and rotated. Consider the case when the trial wavefunction is constructed from some rotated SPOs, say natural orbitals. Then the user requests one body density matrix evaluation in the original unrotated SPO set, e.g. for consistency in the analysis compared to results from trial wavefunction with unrotated SPOs. In principle the user may want to do this with any SPO set. This argues for flexibility in the estimators. Not sure if the plumbing is fully there for the batched case. If there are simplifications to be made by dropping access to unrotated SPOsets, why not make them?

**Comment by ye-luo** [comment]
another input to consider that hides the original sposet before rotation
```
    <sposet_collection  type="MolecularOrbital" transform="yes" source="ion0">
     <rotated_sposet name="spo_rorated" size="4">
        <sposet basisset="LCAOBSet" size="4">
          <... usual LCAO input>
       </sposet>
        <opt_vars size="4">
          -6.2352e-02 1.5072e-02 8.3825e-02 -2.4339e-02
        </opt_vars>
     </rotated_sposet>
  </sposet_collection>
  ```

**Comment by jptowns** [comment]
Personally, I like having `rotated_sposet` as a child of `sposet_collection`. After all, if the builder sees `optimize="yes"` then the SPOSet becomes a RotatedSPOs. 

- What is the purpose of the new `transform` keyword?
- My 2c: We should prefer 'transform' throughout instead of 'rotated' or 'optimize'? (thinking ahead to enabling arbitrary user-specified transformations e.g. natural orbs)

**Comment by markdewing** [comment]
The "transform" keyword on sposet_collection isn't new - it's been there for molecular orbitals.  It converts the basis set to splines.

**Comment by prckent** [comment]
I like the idea of using transform consistently everywhere (vs optimized, rotated etc.), since the transformation can be arbitrary. => transformed_sposet would be the container.

I also forgot what transform="yes" is needed for. How about renaming it something clearer why also supporting transform= for backwards compatibility?

opt_vars could be `transform_vars` or even just `transformation`?

**Comment by markdewing** [comment]
Is this the input that you envision using a general "transform_sposet" tag.   I added a type attribute because there needs to be something to make it specific to orbital rotation.
```
 <sposet_collection  type="MolecularOrbital" transform="yes" source="ion0">
     <transform_sposet type="rotation" name="spo_rotated" size="4">
        <sposet basisset="LCAOBSet" size="4">
          <... usual LCAO input>
       </sposet>
        <transform_vars size="4">
          -6.2352e-02 1.5072e-02 8.3825e-02 -2.4339e-02
        </transform_vars>
     </transform_sposet>
  </sposet_collection>
```

**Comment by markdewing** [comment]
The "size" attribute on the "rotated_sposet" element is not going to be used in a simple implementation of this input.  

Currently orbital rotation uses the number of orbitals from the underlying SPOSet.  The easy path is to continue to use the SPOSet input to specify the number of orbitals involved in rotation.  If we want to set it at the rotated_sposet level, there will need to be more implementation work.

**Comment by jptowns** [comment]
Wow, I did not know that transform was already a thing maybe it should be "convert_to_splines" to distinguish it from a linear transformation on the orbitals? I agree that self-describing input tags are good to have. Naming things is hard!

@markdewing : What does the type="rotation" do? Is it just a label for humans, or does it change the object that gets created?

**Comment by markdewing** [comment]
My preference is to use "rotated_sposet" for the tag name, since it precisely describes what code the input file corresponds to.

The use of a more general name like "transform_sposet" implies there's more than one kind of transformation that could be applied.  So there would need to be something else (like an attribute) to to distinguish what kind of transformation.
