### ISSUE TITLE
Batched driver walker count at restart

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4436]
**Describe the bug**
In batched drivers, xml input takes precedence over walker count from the previous QMC driver section or restart.
Even when no walker control input is given, input parameters default values are still used.
For this is reason, there is no way to retain the exact population.

My fix suggestion is retaining the exact population if no walker control input is given in the QMC driver section input.
Namely
````
<qmc>
  <parameter name="walkers_per_rank"    >    1190            </parameter>
</qmc>
```
or
```
<qmc>
  <parameter name="total_walkers"    >    2380            </parameter>
</qmc>
```
the previous population will be tailored based the request in the current input block.
If neither control is given in the input. The previous population is retained.

**Comment by prckent** [comment]
If I understand it, another way of looking at this problem is that the population is normalized according to walkers_per_rank / total_walkers at the start of the section. If we simply don't do that then this problem goes away.
