### ISSUE TITLE
Replace all sprintf

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4438]
**Is your feature request related to a problem? Please describe.**
I got a lot of warning about sprintf on mac when using gcc.
They should be replaced with ostringstream. I also noticed unsafe code nearby like
```
../src/Utilities/SimpleParser.cpp-  char end_key[128]; // magic size
../src/Utilities/SimpleParser.cpp:  sprintf(end_key, "</%s>", field);
```

**Describe the solution you'd like**
Get rid of all sprintf

**Comment by quantumsteve** [comment]
Moving format specifiers to ostringstream is possible but ugly.

What do you think about using [{fmt}](https://fmt.dev/latest/index.html) as an alternative to streams? We could add it to `external_codes` or use CMake FetchContent.

**Comment by prckent** [comment]
Counter argument: adding an external code is ugly and adds to the learning surface.

**Comment by markdewing** [comment]
Once we reach C++ 20, std::format will be available.

**Comment by prckent** [comment]
@markdewing Good argument. How to make sure we don't use any extensions from what is in c++20 though? It will be more than two years before we can force the use of a compiler implementing std::format. e.g. g++ 13 should have it but gnu 13 isn't out quite yet. ( https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B20_library_features )

**Comment by quantumsteve** [comment]
A minimal change to [snprintf](https://en.cppreference.com/w/c/io/fprintf) would eliminate the warnings and push the `std::format` vs `std::ostringstream` question further into the future.
