### ISSUE TITLE
Continuing a DMC run results in "Fatal Error. Aborting at SimpleFixedNodeBranch::resetRun cannot initialize WalkerController"

### ISSUE THREAD

**Issue by krongch2** [QMCPACK/qmcpack#4483]
Continuing a DMC run results in "Fatal Error. Aborting at SimpleFixedNodeBranch::resetRun cannot initialize WalkerController"

**Describe the bug**
I tried to continue a DMC run for this H2O example: https://github.com/QMCPACK/qmcpack/tree/develop/examples/molecules/H2O
and ran into the following error: 
```
Fatal Error. Aborting at SimpleFixedNodeBranch::resetRun cannot initialize WalkerController
```
All the files including inputs and outputs within the directory are uploaded here: https://drive.google.com/drive/folders/1QJ2mZvzO0F1wCGVN22hB4VQ8WOmMp19N?usp=share_link

**To Reproduce**
1. First, I edited the `simple-H2O.xml` file so that the field `checkpoint="-1"` becomes `checkpoint="0"` to ensure that the `config.h5` file is generated after the first DMC run.
2. Then, I ran the input file `simple-H2O.xml` by submitting the following script with `bsub dmc.bsub.in`. 
```
#!/bin/bash
#BSUB -P mat221
#BSUB -J dmc
#BSUB -o dmc.out
#BSUB -e dmc.err
#BSUB -W 00:20
#BSUB -nnodes 1
#BSUB -alloc_flags "smt1"

module load gcc/9.3.0 spectrum-mpi cuda essl netlib-lapack hdf5/1.10.7 fftw; module use /gpfs/alpine/mat151/world-shared/opt/modules; module load llvm/release-15.0.0-cuda11.0
export OMP_NUM_THREADS=7
jsrun -a 1 -b rs -c 7 -d packed -g 1 -n 6 -r 6 --smpiargs="-disable_gpu_hooks" /gpfs/alpine/mat151/world-shared/opt/qmcpack/release-3.15.0/build_summit_Clang_cpu_cplx/bin/qmcpack_complex simple-H2O.xml
```
The QMCPACK executable was compiled by @ye-luo and is located in `/gpfs/alpine/mat151/world-shared/opt/qmcpack/release-3.15.0/build_summit_Clang_cpu_cplx/bin/qmcpack_complex` on Summit. 
This step autogenerates `H2O.s002.cont.xml` for the subsequent run. 

3. Next, I ran the newly generated input file `H2O.s002.cont.xml` by submitting the following script with `bsub dmc.bsub.cont.in`
```
#!/bin/bash
#BSUB -P mat221
#BSUB -J dmc.cont
#BSUB -o dmc.cont.out
#BSUB -e dmc.cont.err
#BSUB -W 00:20
#BSUB -nnodes 1
#BSUB -alloc_flags "smt1"

module load gcc/9.3.0 spectrum-mpi cuda essl netlib-lapack hdf5/1.10.7 fftw; module use /gpfs/alpine/mat151/world-shared/opt/modules; module load llvm/release-15.0.0-cuda11.0
export OMP_NUM_THREADS=7
jsrun -a 1 -b rs -c 7 -d packed -g 1 -n 6 -r 6 --smpiargs="-disable_gpu_hooks" /gpfs/alpine/mat151/world-shared/opt/qmcpack/release-3.15.0/build_summit_Clang_cpu_cplx/bin/qmcpack_complex H2O.s002.cont.xml
```
This step seems to get past the VMC block successfully as shown by the newly produced `H2O.s003.scalar.dat` with the series number `s003`, which indicates the VMC run. However, no files from the series number `s004` were produced due to the error when initializing the DMC run as shown in the file `dmc.cont.err`. 

**Expected behavior**
I expect the continuation of the DMC run to produce `H2O.s004.scalar.dat` and other files with the prefix `H2O.s004.*` as expected from a successful DMC run.

**System:**
 - Summit
 - module load gcc/9.3.0 spectrum-mpi cuda essl netlib-lapack hdf5/1.10.7 fftw; module use /gpfs/alpine/mat151/world-shared/opt/modules; module load llvm/release-15.0.0-cuda11.0

I'd appreciate it if you could help me figure out whether there is any mistake in the input files or what I am missing. Thank you.

**Comment by ye-luo** [comment]
Legacy drivers load the previous driver state. VMC->DMC, VMC->VMC, DMC->DMC work but DMC->VMC breaks internal code paths. I can add a safeguard to stop the code earlier with clear message but we won't make this case to work. DMC->VMC does run with batched drivers.

**Comment by krongch2** [comment]
I see. So, what's the correct input file for this H2O example? https://github.com/QMCPACK/qmcpack/blob/develop/examples/molecules/H2O/simple-H2O.xml

Should the `driver_version` field be added? 

Also, is the autogenerated `H2O.s002.cont.xml` not correct? In this file, `<mcwalkerset fileroot="H2O.s002" node="-1" nprocs="6" version="3 15" collected="yes"/>` is added before the VMC block. Are you suggesting removing the VMC block (keeping only the DMC block) in the restart input file?

**Comment by ye-luo** [comment]
Drop the vmc block is the simplest way. The continuation file is only made available to you for tweaking.

**Comment by prckent** [comment]
Another way would be to switch to the batched drivers.

If you have a real workflow that you can't run please provide more details - we certainly wish to support all reasonable workflows and ensure the code is productive for science runs.

**Comment by krongch2** [comment]
Thank you for your help. I dropped the VMC block in the subsequent run, but now the local energy is `nan`.
https://github.com/krongch2/h2o_qmc/blob/main/2_dmc/H2O.s003.dmc.dat

The full output is uploaded here: 
https://github.com/krongch2/h2o_qmc/blob/main/2_dmc/dmc.cont.out

**Comment by ye-luo** [comment]
> Thank you for your help. I dropped the VMC block in the subsequent run, but now the local energy is `nan`. https://github.com/krongch2/h2o_qmc/blob/main/2_dmc/H2O.s003.dmc.dat
> 
> The full output is uploaded here: https://github.com/krongch2/h2o_qmc/blob/main/2_dmc/dmc.cont.out

Could you make a new issue? Does v3.16/develop show the same problem?

**Comment by krongch2** [comment]
Yup. I submitted a new issue here: https://github.com/QMCPACK/qmcpack/issues/4487

v3.16 shows the same problem for both `offload_cuda_real` and `Clang_cpu_cplx`
