### ISSUE TITLE
Walker Weights always saved as 1.0

### ISSUE THREAD

**Issue by quantumsteve** [QMCPACK/qmcpack#4493]
**Describe the bug**

**To Reproduce**
1. release version or git commit hash being built
    [restart_dmc branch](https://github.com/QMCPACK/qmcpack/compare/develop...quantumsteve:restart_dmc)
3. cmake command
   `cmake -DQMC_MPI=OFF ../`
5. full program/test invocation command
    `ctest -R deterministic-restart_dmc-1-16$`
6. additional steps
    ```
    $ cd tests/io/deterministic-restart_dmc-1-16
    h5dump det_qmc_vmcbatch_dmcbatch_tm.s001.config.h5
    ```
    and check `walker_weights` dataset

**Expected behavior**

`walker_weights` should be different from 1.0

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]
   my laptop (Ubuntu 20.04)

**Additional context**

Is `MCSample` dropping walker weight? See [MCWalkerConfiguration.cpp:239](https://github.com/QMCPACK/qmcpack/blob/56e2f6c18a6703ad2c36a722beb0363787ba6d64/src/Particle/MCWalkerConfiguration.cpp#L239) and [MCSample.h:60](https://github.com/QMCPACK/qmcpack/blob/56e2f6c18a6703ad2c36a722beb0363787ba6d64/src/Particle/MCSample.h#L60)

**Comment by quantumsteve** [comment]
@ye-luo Should a `Weight` member be added to `MCSample`?

**Comment by ye-luo** [comment]
> @ye-luo Should a `Weight` member be added to `MCSample`?

Yes. Please add it.

**Comment by quantumsteve** [comment]
All weights are being set to `1.0` [here](
https://github.com/QMCPACK/qmcpack/blob/9ba8a194c6a842003e4dedc8d1dad5ea0e5ef654/src/QMCDrivers/DMC/DMCBatched.cpp#L478). 

It appears to be set by the last variable
https://github.com/QMCPACK/qmcpack/blob/9ba8a194c6a842003e4dedc8d1dad5ea0e5ef654/src/QMCDrivers/DMC/WalkerControl.cpp#L240

Could that explain why the walker weights are set to 1?

**Comment by ye-luo** [comment]
Once walker branching finishes, all the walker weight are reset to 1. Use `debug_disable_branching` should give weights not 1.

**Comment by quantumsteve** [comment]
@ye-luo Would you look over the test input files I added in the branch below? It's failing with either `debug_disable_branching=yes` or `debug_disable_branching=no` :confused:

https://github.com/QMCPACK/qmcpack/compare/develop...quantumsteve:restart_dmc
