### ISSUE TITLE
Spack CI constant failure

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#4510]
**Describe the bug**
The recent CI report a constant failure related to numerical issues on Debug mode: 
- https://github.com/QMCPACK/qmcpack/actions/runs/4407886471/jobs/7723357699
- https://github.com/QMCPACK/qmcpack/actions/runs/4407661797/jobs/7721631980

**To Reproduce**
1. current develop branch
2. cmake command: `cmake -GNinja -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DQMC_MPI=0 -DCMAKE_BUILD_TYPE=Debug /__w/qmcpack/qmcpack`
3. build: `ninja`
4. run tests: `ctest --output-on-failure -L deterministic -j 2`

**Expected behavior**
Tests should pass

**System:**
 - GitHub Actions runners, local Ubuntu 22 running on container 

**Additional context**
Numerical differences might be related to debug mode?
Try configuring with RelWithDebInfo

**Comment by camelto2** [comment]
I'll point out that it does seem to be specific to Debug mode in the CI, but these tests actually fail on my M1 Mac, and I am not building with debug mode on.

**Comment by prckent** [comment]
deterministic-He_ae-opt-1-16-check  fails indicating that the wavefunction optimization has produced a different jastrow factor.

It could be that the test is just a bit sensitive, but my worry has always been that there is a threading related bug here. These are not simple single driver QMC tests and involve a wavefunction optimization. Perhaps something is not initialized or there is a botched reduction operation. Some experimentation will be needed to clear this up. e.g. Does a test using 1 thread but same statistics as current test prove much more reliable.

**Comment by ye-luo** [comment]
We can try thread sanitizer to see if there is race.

**Comment by ye-luo** [comment]
Orange pi (ARM) also failed. https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=403751

**Comment by markdewing** [comment]
An aside on the Orange Pi failure - the run for deterministc-He_ae-opt-1-16 switches to 8 threads for the second optimizer loop.
https://cdash.qmcpack.org/CDash/testDetails.php?test=25483891&build=404150
```
<vmc stage="main" blocks="5">
  Cannot make clones again. Use existing 8 clones
  Initial partition of walkers 0 2 4 6 8 10 12 14 16 
```
```
  Number of samples loaded to each thread : 2 2 2 2 2 2 2 2
```
I don't think this is causing the failure, but it was surprising when I was looking through the output.

**Comment by markdewing** [comment]
I compiled with gcc 11.2.0 and gcc 12.1.0 and could not reproduce it.
On the Orange Pi, it's compiled with clang.  And the CI uses gcc 11.3.0.

I'm using MKL for the blas library.   The failure cases are using openBLAS.


The first iteration of the optimizer seems to match between a passing run and failing run, but the second iteration has a different VMC energy.

**Comment by ye-luo** [comment]
A bit digging.
https://github.com/xianyi/OpenBLAS/issues/3940
@camelto2 could you attach `ctest -R deterministic-He_ae-opt-batch-mwalkers-1-16 -VV` output
@williamfgc what is the processor used in spack CI?

**Comment by williamfgc** [comment]
@ye-luo it could be any of the Intel Xeon listed [here](https://learn.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) using 2 cores. Thank you all for your input.

**Comment by williamfgc** [comment]
I did more digging and I can reproduce running on the CI container `docker run -it walshmm/qmcpack-ci:centos-stream-gcc11 /bin/bash`  with gcc and clang (added with yum) on my AMD Ryzen 9 5900X. ThreadSanitizer doesn't report issues with these tests. I opened another issue #4512 for @walshmm so we can have spack available. Somehow a yum installed version of OpenBLAS is not picked up even adding to the CMAKE_PREFIX_PATH.

**Comment by markdewing** [comment]
It looks like OpenBLAS picks up the number of cores on the machine it's being built on and sets that as a MAX_CPU_NUMBER.  The number of threads is capped at that number inside (openblas) driver/others/blas_server_omp.c.  Our tests run with 16 threads, so we're going to run into problems when openblas is compiled with max threads fewer than that.
The workaround suggested in the openblas issue Ye opened is to set NUM_THREADS to a larger value when compiling openblas.
How does this interact with Spack?  Does it let the openblas build pick up num threads.  Can we set the NUM_THREADS for the Spack build?

**Comment by quantumsteve** [comment]
Don't know if it's relevant here, but I've run into issues with avx-512 and OpenBLAS < v0.3.21
https://github.com/xianyi/OpenBLAS/issues/3494

**Comment by quantumsteve** [comment]
> How does this interact with Spack? Does it let the openblas build pick up num threads. Can we set the NUM_THREADS for the Spack build?

I think the ['virtual machine' variant](https://github.com/davydden/spack/blob/878b122f45815383297a352e689a476c93f4b4b8/var/spack/repos/builtin/packages/openblas/package.py#L53) would work around the current NUM_THREADS issue.
