### ISSUE TITLE
using namespace std in header file

### ISSUE THREAD

**Issue by quantumsteve** [QMCPACK/qmcpack#4513]
**Describe the bug**

`using namespace std;`  should be [limited to local scope and not a header file](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-using-directive)

https://github.com/QMCPACK/qmcpack/blob/089de296a517c8e3c54055aaf7f7ac8ad4e41f87/src/QMCTools/QMCFiniteSize/SkParserBase.h#L13

Remove `using namespace std;` and add `std::` where necessary to make QMCPACK compile.

**Comment by ye-luo** [comment]
Good catch. This should not happen in header files.
