### ISSUE TITLE
Update self-host CI tasks.

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4536]
Our self hosted CI needs some updates.

- sulfur CI Intel21-MPI-CUDA-AFQMC **sick due to CUDA 12 Intel Classic incompatibility**
- nitrogen CI RadeonVII-ROCm-NoMPI-CUDA2HIP **Working**
- sulfur CI Clang15-MPI-CUDA-AFQMC-Offload **Working**
- sulfur CI GCC9-NoMPI-MKL **Working**
- nitrogen CI GCC9-MPI-CUDA-AFQMC **inactive**

CPU testing is fast.
NVIDIA GPU testing is OK.
AMD GPU testing is very slow.

We are missing
CPU only + AFQMC. I'm afraid there is breakage already.
NVIDIA clang only offload + no CUDA
NVIDIA clang only CUDA + no offload
AMD ROCm Offload + CUDA2HIP.

My suggestion

- sulfur CI GCC9-NoMPI-MKL *basic sanity check the node*
- sulfur CI Intel21-MPI-AFQMC *Intel classic CPU only*
- sulfur CI OneAPI21-MPI-AFQMC *Intel oneAPI CPU only* #4326
- nitrogen CI RadeonVII-ROCm-MPI *CPU only*
- nitrogen CI RadeonVII-ROCm-NoMPI-CUDA2HIP *AMD HIP + no Offload*
- nitrogen CI RadeonVII-ROCm-NoMPI-Offload-CUDA2HIP *AMD Offload + HIP*
- sulfur CI Clang15-MPI-AFQMC *CPU only*
- sulfur CI Clang15-MPI-Offload-CUDA-AFQMC *NV Offload + CUDA*
- sulfur CI Clang15-MPI-Offload-AFQMC *NV Offload + no CUDA*

In general, GPU builds for each vendor needs 4 variants +/- CUDA/HIP and +/- Offload.
We probably won't do all combinations. + CUDA/HIP and + Offload must be covered.
In partial variants, I chose ROCm with the HIP only + no offload build and Clang15 with the offload + no CUDA build

**Comment by prckent** [comment]
Long since addressed. Lets make a new issue for any CI requests.
