### ISSUE TITLE
handle h5 group check in hdf_archive

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4547]
**Is your feature request related to a problem? Please describe.**
See comment
https://github.com/QMCPACK/qmcpack/pull/4541/files#r1158964516

**Comment by markdewing** [comment]
The comment is asking for the error to be handled in the call to `push`.

To be clear, the desired behavior is:
   If the group name is not present and `createit` is false, then the `push` call should throw an exception.

**Comment by ye-luo** [comment]
I don't feel right returning hid_t type outside hdf_archive which should hid details of the hdf5 library. So  I'm thinking of
1. push(name, createit). Throw an exception when creation is requested and failed or whgen creation is not requested and open group failed.
2. is_group can be used to inspect group existence.
3. if the group tid_t is actually needed use top() after a successful push().
