### ISSUE TITLE
Building process stopped due to "libstdc++ from a GCC version lower than 9 is not supported"

### ISSUE THREAD

**Issue by YanyongW91** [QMCPACK/qmcpack#4563]
Hi, qmcpack developers

I'm a beginner to qmc. When I trying to install qmcpack on the cluster, error reported as title said, and the detail is that

qmcpack-3.16.0
--------------------------------------------------------------------------------------------------------------------------------------------
system info
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              256
On-line CPU(s) list: 0-255
Thread(s) per core:  2
Core(s) per socket:  64
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7702 64-Core Processor
--------------------------------------------------------------------------------------------------------------------------------------------
**building script:**
#!/bin/bash
CC=/opt/intel/oneapi/mpi/2021.2.0/bin/mpiicc
CXX=/opt/intel/oneapi/mpi/2021.2.0/bin/mpiicpc
MKL_ROOT=/home/ywang/code/intel/oneapi/mkl/2023.1.0
HDF5_ROOT=/home/ywang/code/hdf5-1.14.0/hdf5
BOOST_ROOT=/home/ywang/code/boost_1_82_0
FFTW_HOME=/home/ywang/code/fftw-3.3.10ing
cd build
cmake -D CMAKE_C_COMPILER=$CC -D CMAKE_CXX_COMPILER=$CXX ..
--------------------------------------------------------------------------------------------------------------------------------------------
**Error message:**
 /home/ywang/code/qmcpack-3.16.0/CMake/try_compile_sources/check_libstdcxx.cpp(7):
  error: #error directive: Detected libstdc++.  libstdc++ from a GCC version
  lower than 9 is not supported.
    #error Detected libstdc++. libstdc++ from a GCC version lower than 9 is not supported.
     ^

  compilation aborted for
  /home/ywang/code/qmcpack-3.16.0/CMake/try_compile_sources/check_libstdcxx.cpp
  (code 2)

  gmake[1]:  [CMakeFiles/cmTC_42d90.dir/build.make:86:
  CMakeFiles/cmTC_42d90.dir/check_libstdcxx.cpp.o] Error 2

  gmake[1]: Leaving directory
  '/home/ywang/code/qmcpack-3.16.0/build/CMakeFiles/CMakeTmp'
  gmake:  [Makefile:141: cmTC_42d90/fast] Error 2
--------------------------------------------------------------------------------------------------------------------------------------------

**Context**
1. this error occur for both intel 2021.9 and intel 2021.2
2. I have install a gcc-9.5.0 and add
alias gcc="/home/ywang/code/gcc-9.5.0ing/bin/gcc"
alias g++="/home/ywang/code/gcc-9.5.0ing/bin/g++"
to my local user .bashrc file

Please help!

**Comment by ye-luo** [comment]
icpc uses gcc toolchain. Make sure your icpc properly picks up the intended gcc 9.
On my computer, my icpc sees the gcc 11.3.0 toolchain. 
```
$ icpc -v
icpc version 2021.4.0 (gcc version 11.3.0 compatibility)
```
So make sure yours show `gcc version 9.5.0 compatibility`.
If not, try `export PATH=/home/ywang/code/gcc-9.5.0ing/bin:$PATH`.

**Comment by YanyongW91** [comment]
Hi, @ye-luo , thanks for the help, it works! When compiling, the below warning can be ignored, right?

`icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.`

**Comment by prckent** [comment]
You can ignore it. Once you are up and running, you might want to investigate a different compiler, including one optimized for AMD.

**Comment by YanyongW91** [comment]
all right, thanks

**Comment by prckent** [comment]
Feel free to open another issue if needed as you get up and running.
