### ISSUE TITLE
Memory goes up to 500GB when compiling

### ISSUE THREAD

**Issue by YanyongW91** [QMCPACK/qmcpack#4564]
hi, developers

OS: CentOS Linux 8
version: qmcpack-3.16.0

When I do the building process, it seems got stuck at "_[ 45%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/WaveFunctionFactory.cpp.o_" and the memory of the compiling process goes up to 500 GB of the "mcpcom". And this situation could be repeated.

please help, thanks

**Comment by ye-luo** [comment]
What makes you think "Memory goes up to 500GB"? Please provide details.

**Comment by YanyongW91** [comment]
Sorry, my bad, I mistakenly typed unmeaning letters in the cmake line.

**Comment by YanyongW91** [comment]
@ye-luo hi, I use intel 2021.2.0, but it gives error "CMake Error at CMake/IntelCompilers.cmake:12 (message):
  Requires Intel classic compiler 2021.1 or higher!", do you know how to resolve this?

**Comment by YanyongW91** [comment]
hi, @ye-luo , after #4565  resolved according to your advice, this large memory occurs again when it comes to

```
 44%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/Fermion/DiracDeterminantWithBackflow.cpp.o
[ 44%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/Fermion/SlaterDetWithBackflow.cpp.o
[ 44%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/SPOSetBuilderFactory.cpp.o
[ 44%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/TrialWaveFunction.cpp.o
[ 44%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/TWFdispatcher.cpp.o
[ 44%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/TWFFastDerivWrapper.cpp.o
[ 45%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/TWFGrads.cpp.o
[ 45%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/WaveFunctionFactory.cpp.o
icpc: error #10106: Fatal error in /opt/intel/oneapi/compiler/2021.2.0/linux/bin/intel64/../../bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /home/ywang/code/testing/qmcpack-3.16.0/src/QMCWaveFunctions/EinsplineSet.cpp (code 1)
make[2]: *** [src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/build.make:594: src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/EinsplineSet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

![Screenshot from 2023-04-24 17-57-13](https://user-images.githubusercontent.com/63693685/234134038-7e962f0f-43b9-41df-bc63-a1e9db9173c3.png)


where the command `mcpcom` is the compiling process, can you figure out why?

**Comment by ye-luo** [comment]
Unfortunately no idea... very strange. It can be a bug in the compiler. Try a newer intel compiler...

**Comment by YanyongW91** [comment]
here is with intel 2021.9.0 around 100GB -250 GB, also when it comes to compiling ```Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/WaveFunctionFactory.cpp.o```
![Screenshot from 2023-04-24 18-16-06](https://user-images.githubusercontent.com/63693685/234135774-4efc0986-8fd4-4fad-ad5b-1aee852fce3b.png)

**Comment by YanyongW91** [comment]
Hi, developers, Can you provide some help?
I really need this to be solved so I can continue my use of qmcpack.
As mentioned, the building process always got stuck at the ```WaveFunctionFactory.cpp``` file, probably this could provides some clue. Thanks!

**Comment by ye-luo** [comment]
Unfortunately, I cannot reproduce your issue on my local computer and hence there is not much we can do.
You may use clang/gcc+MKL to get out of the trap.

**Comment by YanyongW91** [comment]
Hi, it asks for gcc 9.0, but I do installed gcc9.5
here is my **cmake script**:
```
#!/bin/bash

MKL_ROOT=/opt/intel/oneapi/mkl/2021.2.0/
HDF5_ROOT=/home/ywang/code/hdf5-1.14.0/hdf5
BOOST_ROOT=/home/ywang/code/boost_1_82_0
FFTW_HOME=/home/ywang/code/fftw-3.3.10ing
cd build
cmake ..
make -j 8
```
**OUTPUT**
```
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Defining the float point precision
   Base precision = double
   Full precision = double
-- CMAKE_BUILD_TYPE is RELEASE
-- Enable sanitizer ENABLE_SANITIZER=none
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Trying to figure out compiler options ....
-- C++ Compiler is identified by QMCPACK as : GNU
CMake Error at CMake/GNUCompilers.cmake:3 (message):
  Requires GCC 9.0 or higher
Call Stack (most recent call first):
  CMake/inspectCompiler.cmake:47 (include)
  CMakeLists.txt:293 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ywang/code/testing/qmcpack-3.16.0/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
```
**context**
added ```export PATH=/home/ywang/code/gcc-9.5.0ing/bin:$PATH``` to .bashrc as you suggested

**Comment by ye-luo** [comment]
You'll need to properly to configure your MPI wrappers using gcc 9.

**Comment by YanyongW91** [comment]
That's too professional for me. Can you give some technique details or provide some links so I can refer?

**Comment by williamfgc** [comment]
@YanyongW91 we do this in CI, see [this line](https://github.com/QMCPACK/qmcpack/blob/develop/tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh#L66) to pass the underlying compiler to OpenMPI CC and CXX.

**Comment by YanyongW91** [comment]
Thanks William! I'll try it

**Comment by markdewing** [comment]
You'll need to figure out if you're running MPICH or OpenMPI - the environmental variable to set the underlying compiler is different between those MPI implementations.

**Comment by YanyongW91** [comment]
I'll try openmpi

**Comment by YanyongW91** [comment]
It works, thanks everybody!
