### ISSUE TITLE
Bump GitHub Actions CI containers to Ubuntu 22

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#4570]
**Is your feature request related to a problem? Please describe.**
QMCPACK has a 2-year compiler support policy, current Ubuntu 20 CI images are out of the scope.

**Describe the solution you'd like**
Bump [CI done on GitHub Actions runners](https://github.com/QMCPACK/qmcpack/blob/develop/.github/workflows/ci-github-actions.yaml) to Ubuntu 22 container images

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by walshmm** [comment]
Since my PR was merged this should be resolved
