### ISSUE TITLE
Readthedocs CI failure 

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#4587]
**Describe the bug**
Current readthedocs build fails on CI related to Sphinx packages with message:
`Could not import extension sphinx.builders.linkcheck`

**To Reproduce**
From latest CI check:
https://readthedocs.org/projects/qmcpack/builds/20387555/ 

**Expected behavior**

**System:**
N/A

**Additional context**
N/A

**Comment by prckent** [comment]
I can investigate bumping the old versions in requirements.txt . Those are quite old.

**Comment by prckent** [comment]
I did a quick investigation to see if I could avoid this problem with using the current versions of the sphinx packages in spack, thinking to then bump requirements.txt versions. However, I ran into problems with an undeclared runtime dependency on sphinxcontrib.applehelp which I could not quickly get working. I need to work on other tasks for some days so I will not revisit this soon.

**Comment by prckent** [comment]
Failed attempt in #4590 

Maybe see how other repos are faring. Our sphinx config is not special.

**Comment by prckent** [comment]
See https://github.com/readthedocs/readthedocs.org/issues/10290

**Comment by prckent** [comment]
Fixed by #4592
