### ISSUE TITLE
Remove MPI walker swap methods

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#461]
Question about the walker exchange code in WalkerControlMPI.  There a four variants for swapping walkers.  A comment in the *.h file indicates three are 'old implementations': swapWalkersAsync, swapWalkersBlocked, and swapWalkersMap.  Can we rid of any or all of these?  The async version is still accessible via command line switch, so probably not that one.  But are the last two useful or worth keeping around?

Also, what techniques did swapWalkersBlocked and swapWalkersMap try?  It would be nice to have some record of what was tried, and some indication of why it didn't work (or more likely, didn't perform any better than existing method)

**Comment by prckent** [comment]
Is there any reason to not use async by default? Since this is generally believed to be more performant, I don't understand why it is not default.

**Comment by jngkim** [comment]
It is not faster in general.

Calling async send.recv is not sufficient and the plan was to integrate it
with DMC algorithm to make it really asynchronous. And, there are many cool
things one can do but is this the time to worry about MPI?

I suggest to leave them alone unless there is a better implementation.

**Comment by jtkrogel** [comment]
Would it be worthwhile to perform a test at scale with the four options to assess correctness and performance on current problems?

**Comment by prckent** [comment]
@adbacze Is working on walker load balancing, constant population schemes. These sit above the MPI implementation but will be benchmarked at scale soon. Andrew, have you looked at any of MPI? Any preferences?

**Comment by markdewing** [comment]
We are preparing to switch MPI wrappers, and my motivation is to get rid of unnecessary MPI-dependent code.

**Comment by prckent** [comment]
Unless anyone speaks up soon for the old code, remove it. This is the same test we are applying across the application.

**Comment by jngkim** [comment]
I think the comb (previously named as reconfiguration) will be the main
method and I agree with Paul that let Andrew decide what to do.

Currently, the comb method uses blocking send/recv in its own because it is
much simpler than the usual DMC method.

**Comment by prckent** [comment]
@markdewing Remove the old versions Tuesday afternoon if no one has spoken for them by then.

**Comment by adbacze** [comment]
@prckent I've looked at the 'old' implementations but I haven't benchmarked them. While I'm testing the comb method against branching at scale, it would be simple enough for me to attempt some runs with the 3 'old' implementations (for branching, of course - as @jngkim indicates none of this touches comb). It certainly couldn't hurt to have some data somewhere documenting this, but I can just as easily run all of this on my own fork and take responsibility for revisiting these other implementations if it seems worthwhile for comb (or minimal reconfiguration). That is, nothing should stop @markdewing from removing the old implementations from the main branch to avoid creating extra work for the MPI wrapper swap (the wrappening? :)).

**Comment by ye-luo** [comment]
I think out-dated swap methods are all gone. We will do better documentation for the newly added schemes or new implementations.
