### ISSUE TITLE
How to get the total energy and error bar from a bunch of series scalar file output

### ISSUE THREAD

**Issue by YanyongW91** [QMCPACK/qmcpack#4624]
hi developers,

I'm a beginner with qmc simulations. after running with VMC Jastrow optimization (diamond-Silicon system), I type ```qmca -q ev *scalar*```  under the working directory, I get this
```
optJ12  series 0  -30.236975 +/- 0.005954   2.948963 +/- 0.012536   0.0975 
optJ12  series 1  -30.977487 +/- 0.001999   0.585959 +/- 0.002522   0.0189 
optJ12  series 2  -31.150560 +/- 0.001378   0.384033 +/- 0.002216   0.0123 
optJ12  series 3  -31.161695 +/- 0.001331   0.405114 +/- 0.002416   0.0130 
optJ12  series 4  -31.158001 +/- 0.001489   0.420003 +/- 0.006180   0.0135 
optJ12  series 5  -31.157384 +/- 0.001175   0.422483 +/- 0.006929   0.0136 
optJ12  series 6  -31.161433 +/- 0.001439   0.415706 +/- 0.002100   0.0133 
optJ12  series 7  -31.155821 +/- 0.001515   0.408680 +/- 0.004176   0.0131 
optJ12  series 8  -31.159205 +/- 0.001747   0.392198 +/- 0.001548   0.0126 
optJ12  series 9  -31.158458 +/- 0.001770   0.401699 +/- 0.001683   0.0129 
optJ12  series 10  -31.159835 +/- 0.001259   0.394489 +/- 0.001333   0.0127 
optJ12  series 11  -31.159004 +/- 0.001165   0.404021 +/- 0.001758   0.0130 
optJ12  series 12  -31.158124 +/- 0.001709   0.386624 +/- 0.001579   0.0124 
optJ12  series 13  -31.156982 +/- 0.001781   0.388085 +/- 0.001742   0.0125 
optJ12  series 14  -31.161059 +/- 0.001436   0.385070 +/- 0.001599   0.0124 
optJ12  series 15  -31.160763 +/- 0.001343   0.399635 +/- 0.003061   0.0128 
optJ12  series 16  -31.160850 +/- 0.001489   0.391498 +/- 0.001668   0.0126 
optJ12  series 17  -31.158756 +/- 0.001729   0.405100 +/- 0.002276   0.0130 
```
which one should be chosen as the total energy and corresponding error bar of the system for this calculation? or taking an average from series 3 to series 17?
Sorry, I'm very naive on qmc simulations.

This is corresponding input part in nexus script:
```
  optJ12= generate_qmcpack(
     identifier  = 'optJ12',
     path        = 'a_{:6.4f}'.format(a) +'/optJ12',
     job         = job( cores= cores, threads= cores/8, app= qmcx),
     input_type  = 'basic',
     system      = supercell,
     pseudos     = ['Si.ccECP.xml'],
     twistnum    = 0,
     J1          = True, 
     J2          = True, 
     qmc         = 'opt', 
     minmethod   = 'oneshift',
     init_cycles = 6, 
     cycles      = 12, 
     warmupsteps = 12, 
     blocks      = 512, 
     timestep    = 0.08, 
     init_minwalkers= 0.02, 
     minwalkers  = 0.5,  
     samples     = 8192, 
     #use_nonlocalpp_deriv= False,
     dependencies= (conv, 'orbitals') )
```

**Comment by prckent** [comment]
Good question. You have run a series of optimization cycles (series) here. qmca is printing the energy and its error bar, the variance of the energy and its error bar, pus the variance/energy ratio. For a successful optimization we hope to see a reduction in both the energy and variance for a few series, then they will stabilize as the optimization has converged, at least at the level the statistics the optimization steps allow. You have series 0 energy -30.2, and by series two or three the energy is basically stable at -31.158 to -31.161 or so. For the rest of the series this is consistent, so it looks like you have a good optimization here. For one and two body Jastrow optimization (only), this rapid convergence within <6 cycles is common. If quoting an energy from this data I would give the final energy -31.159(2), where (2) is the error on the last quoted digit. However it is a common practice to do a dedicated VMC run using the final Jastrow from the optimization and to increase the statistics as a consistency check. Several of the examples have a VMC or DMC section that follows the opt section that could be adapted.

**Comment by YanyongW91** [comment]
Great thanks for the reply and advices!
 I'll check the the convergence behavior and relevant section.
