### ISSUE TITLE
Hydrogen atomic run is aborted due to absence of down spin electrons

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/qmcpack#4630]
**Describe the bug**
A Hydrogen atom was simulated in a PBC box using QE. The QMCPACK run aborts due to no down spin electrons present in the input. Line 180 in `src/Particle/ParticleIO/XMLParticleIO.cpp` throws an error:
``
Fatal Error. Aborting at Some 'group' XML element node doesn't contain a 'size' attribute!
``

**To Reproduce**
1. Version: QMCPACK 3.16.9 (using batched VMC drivers)
2. The files are copied to OLCF and can be found at: `/gpfs/alpine/mat151/proj-shared/bugs/boxed_H`

**Expected behavior**
I realize this is an exactly solvable system, but in general, one would expect to be able to run systems without down spin electrons. For example, isovalent elements (Li, Na, K, ...) or the excited state of Be (2s^1 2p^1) will probably show a similar problem.

**System:**
 - NERSC/Perlmutter

**Additional context**
The problem was encountered when trying to study the `rcut` parameter in H for use in hybrid orbital representation. I checked the `pwscf.pwscf.h5` file and both spin information were written by QE. So everything seems to be OK on the QE side.

**Comment by markdewing** [comment]
What happens if the down group with size 0 is deleted?

**Comment by markdewing** [comment]
Also, the determinant element corresponding to the down electrons should also be removed.

It looks like the code for the error message assumes that if the size == 0 (the default value), then the size attribute must have been missing.
```
    if (ntot > 0 && num_non_zero_group != nat_group.size())
      throw UniformCommunicateError("Some 'group' XML element node doesn't contain a 'size' attribute!");
```
In this case, nat_group.size() will be 2, but num_non_zero_group will be 1.

It looks like the issue is probably in the converter - it should not emit particle groups with a size of 0.

**Comment by aannabe** [comment]
If I delete `size="0"` from `particleset` and also delete the empty determinants, it runs successfully. So yes, either the `src/Particle/ParticleIO/XMLParticleIO.cpp` part needs to be adjusted to ignore the empty elements, or the converter needs to be adjusted not to write them. In this case, the input was generated via Nexus.

**Comment by ye-luo** [comment]
`XMLParticleIO.cpp` should error out more properly. What is the tool that you used to write the input xml?

**Comment by aannabe** [comment]
I used Nexus for both QE and QMCPACK. See attached.

[workflow.zip](https://github.com/QMCPACK/qmcpack/files/11773581/workflow.zip)
