### ISSUE TITLE
how to continue a dmc run from a vmc or dmc outputs

### ISSUE THREAD

**Issue by YanyongW91** [QMCPACK/qmcpack#4633]
**Calculation Purpose**
Basically I want to divide an complete time-extrapolation DMC calculation (vmc --> dmc [timestep: 0.04] --> dmc [timestep: 0.02] --> dmc [timestep: 0.01] ) into four jobs by series.

First I do the first-step vmc run, with ` <qmc method="vmc" move="pbyp" checkpoint="0">` in the input xml file according to the manual, then I get the corresponding dmc.s000.config.h5, dmc.s000.qmc.xml, dmc.s000.random.h5 that needed for the next dmc run.

**Describe the bug**
However, after I added `</qmcsystem><mcwalkerset fileroot="dmc.s000" node="-1" nprocs="16" version="3 16" collected="yes"/>` in the input xml for the next dmc run, it rerun the vmc part from the very beginning (producing s004, s005, s006, s005 files. respectively), while what I want is to continue the run for the next dmc block, not repeat the vmc run.

**System:**
qmcpack version: `3.16.0`, cpu
platform: nersc perlmutter
job script setting (number of cpus, processes..)  keeps the same

**Additional questions**
If I follow the same way but modify the input xml file with `</qmcsystem><mcwalkerset fileroot="dmc.s001" node="-1" nprocs="16" version="3 16"` to start from a dmc run (`dmc.s001.config.h5, dmc.s001.qmc.xml, dmc.s001.random.h5` provided), it reports error:
`Fatal Error. Aborting at SimpleFixedNodeBranch::resetRun cannot initialize WalkerController`
and the final lines in the dmc.out file are
```
QMC Execution time = 5.9797e-01 secs
BRANCH resetRun
 SimpleFixedNodeBranch::resetRun detected changes in <parameter>'s 
 BranchMode : 0001001111 0001001111
```
Please help! If there's practical example for rerun, that would be helpful!

**Comment by YanyongW91** [comment]
Thanks! I do need this function due to time limits on perlmutter. What I missed is that I need to comment out already completed vmc or dmc section. I also checked that when setting checkingpoints to a limit number of blocks, qmcpack still only write out the random.h5 and config.h5 files only if it has finished an independent vmc or dmc section run, which is against what the manual stated. I don't know where goes wrong.

**Comment by prckent** [comment]
I have verified that the checkpointing is not working on an every number of blocks basis, only at the end of each section. To work around time limits, with the batched drivers you can use the maxseconds parameter. See https://qmcpack.readthedocs.io/en/develop/input_overview.html#time-limits

```
<?xml version="1.0"?>
<simulation>
   <project id="test" series="0">
     <application name="qmcapp" role="molecu" class="serial" version="1.0"/>
     <driver_version>batched</driver_version>
     <parameter name="max_seconds">3500</parameter>
   </project>
   <qmcsystem>
      <simulationcell>
         <parameter name="lattice" units="bohr">
                  6.74632230        6.74632230        0.00000000
                  0.00000000        3.37316115        3.37316115
                  3.37316115        0.00000000        3.37316115
```

**Comment by YanyongW91** [comment]
Thanks for the information! I will give it a try.

**Comment by prckent** [comment]
We are working to simplify this. In the interim, if you are using the legacy (non-batched) drivers, we found you also needed to specify <parameter name="storeconfigs">1</parameter> inside the VMC or DMC section in addition to using the checkpoint setting. Once the above PR is merged, the development version will only need the checkpoint parameter to control the behavior.
