### ISSUE TITLE
Testing jastrow functionality

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#465]
#464 and #462 make clear that we need to be more thorough in checking/identifying that the full set of functionality is implemented for different jastrows. This is  relevant for the "extended" functionality used by estimators such as the momentum distribution that need functionality not touched upon by a standard VMC run.

It would be good to (1) at least know the matrix of functionality that is supported, (2) [harder] that this functionality is correct.

Is this straightforward to add to our test sets?

**Comment by ye-luo** [comment]
Do we have a bspline J1 unit test?

**Comment by jtkrogel** [comment]
More needed here or done?

**Comment by ye-luo** [comment]
We have
```
test_J1OrbitalSoA.cpp
test_J1Spin.cpp
test_J2_bspline.cpp
test_kspace_jastrow.cpp
test_polynomial_eeI_jastrow.cpp
```
if the functionality in a specific jastrow is not  covered by unit test, we will use new issues to track that.
