### ISSUE TITLE
Unexpected VMC acceptance ratio behavior

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/qmcpack#4652]
**Describe the bug**
The linear molecule C4N2 was simulated using QE and batched VMC with PBC:
![C4N2](https://github.com/QMCPACK/qmcpack/assets/26770234/ec0d2974-6599-432c-b0ad-2945c2f45141)

As the total number of walkers is increased via increasing the number of nodes in the job while leaving the QMC input the same, the following unexpected behavior occurs in the VMC acceptance ratio in the large walker limit for 500 steps/block:
![acceptance](https://github.com/QMCPACK/qmcpack/assets/26770234/6297fbf2-51c0-4474-b228-4d6e63110f71)

To check if it was related to #4648, I ran with `crowd_serialize_walkers=yes`, and this didn't resolve the problem, as can be seen above. However, decreasing the number of steps to 300/block or 50/block resolves the issue.

I also checked to total energies and they seem unaffected by all of this:
![energy](https://github.com/QMCPACK/qmcpack/assets/26770234/d83c6eb3-6add-4b17-8268-91c3f9286354)

**To Reproduce**
Steps to reproduce the behavior: Relase Version 3.16.9
Input and output files are copied to OLCF at:
`/gpfs/alpine/mat151/proj-shared/bugs/issue_acceptance`

**Expected behavior**
The acceptance ratio should stay the same as the total number of walkers is increased.

**System:**
- NERSC/Perlmutter. CPU run with batched-VMC

**Additional context**
In this case, it was desired to keep the number of steps as high as possible since `spindensity` was being accumulated, which dumps large amounts of data every block. So by increasing the number of steps, the statistics can be improved without large files.

**Comment by jtkrogel** [comment]
Clearly a bug.  Thanks for reporting this Gani.

**Comment by jtkrogel** [comment]
@aannabe does the issue go away when you turn off the spin density estimation?  

The fishy part is that the issue shows up as you increase the node count with nothing else changing.  This could implicate the data aggregation machinery for estimators that has been rebuilt from scratch for the  batched code.

**Comment by aannabe** [comment]
This was the first thing I tested - the issue persists whether the `spindensity` is included or not. I also tested if something was problematic with the large `warmuptsteps = 500` provided, but this also didn't make a difference when decreased.

**Comment by prckent** [comment]
No question a bug.

Curiously while the acceptance ratios are 1.0 for every block for 122880 and 143360 total walkers, all the other entries in the scalar files look consistent (by eye). This includes the blockCPU time (about the same independent of node count) and the block weight (increasing proportional to node count). The energy component averages are consistent down to the block level, so this is not a problem that gradually occurs.

This points to the runs being OK apart from there being some problem handling the recording and reporting of the acceptance ratio. This is a puzzle since, e.g. the problematic runs don't cross an obvious power of 2 boundary or type limit.

If the problem is purely related to the total walker count, then a 1 step 1 block run will show the problem. No estimators required. Do you have bandwidth to try?

**Comment by aannabe** [comment]
I have tried the above suggestion: 1 step, 1 block, and warmup=100 steps. I have gone up to 266240 walkers and can not reproduce the issue:
```
Tot_Walkers  VMC_Energy        VMC_Acceptance
 61440      -4.2166726221e+01  5.3520820813e-01
 81920      -4.2171180286e+01  5.3547504132e-01
102400      -4.2170909669e+01  5.3506798377e-01
122880      -4.2168436208e+01  5.3482165214e-01
143360      -4.2170639333e+01  5.3505161830e-01
163840      -4.2173252408e+01  5.3508934608e-01
184320      -4.2167277013e+01  5.3540205996e-01
204800      -4.2171154315e+01  5.3513540415e-01
225280      -4.2167932839e+01  5.3514105523e-01
245760      -4.2170001955e+01  5.3496938852e-01
266240      -4.2167602400e+01  5.3529897837e-01
```

It seems some bookkeeping done at the end of each block is not done soon enough, which causes the incorrect acceptance ratio.

**Comment by prckent** [comment]
I am checking to see if this can be reproduced on a workstation since it would be easier to debug, i.e. no/few mpi tasks but many walkers. So far energies and acceptance ratios are consistent with your correct runs.

A couple of extra things to try:
. If you have the same number of mpi tasks as for the bad runs above, but e.g. halve the walkers_per_rank, does the problem appear?
. If it fits, try without hybrid basis.

**Comment by aannabe** [comment]
* Using the problematic run of 500 steps/block and 560 total MPI tasks but halving the `walkers_per_rank` gives the VMC energy (-42.17017(4) Ha) and acceptance ratio (0.5352543). Thus the problem is not related to the number of MPI tasks.
* Using the problematic run of 500 steps/block and 560 total MPI tasks but using regular splines does not resolve the issue, giving VMC energy of -42.1717(9) Ha and an acceptance ratio of 1.00, namely not related to the hybrid basis.

**Comment by prckent** [comment]
Credit to Jaron for the following: try a run that accepts no moves, i.e. put substeps=0 . For the 500steps/block runs and say 560 total MPI tasks, the energies should now be bad + constant and the acceptance ratio should be zero. If it is still one that would be very curious.

**Comment by aannabe** [comment]
Yes, with the above input, the results are off, and the acceptance is given as `nan`:
```
vmc_J123  series 0 
  LocalEnergy           =       -45.6518482 +/-        0.0000018    1.7 
  Variance              =         3400.0914 +/-           0.0049    1.5 
  Kinetic               =             31.69 +/-             0.00    1.0 
  LocalPotential        =       -77.3458426 +/-        0.0000018    1.7 
  AcceptRatio           =               nan +/-              nan    1.0 
```

**Comment by ye-luo** [comment]
If substeps=0, the number of accept moves / the number of total moves = 0 / 0 = NaN which is expected.

**Comment by ye-luo** [comment]
32 bit int upper bound  -2,147,483,648 to 2,147,483,647
We count nAccept nReject using 23 bit int.

102400(wakers)*3(substeps)*500*(steps)*26(electrons) *0.53 = > 2116608000 below the upper bound
122880(wakers)*3(substeps)*500*(steps)*26(electrons) *0.53 = > 2539929600 integer overflow.

So a fix is to use 64 bit Integer in such counters.

**Comment by prckent** [comment]
Happily it is just the bookkeeping.
