### ISSUE TITLE
Momentum distribution estimator not working with gpu implementation

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#467]
The gpu code does not support nofk.  When a run is attempted, this is printed thousands of times (once per step?):

ERROR Need specialization for MomentumEstimator::addEnergy(MCWalkerConfiguration &W).

The code runs to completion and the stat.h5 output, while properly formed, is filled completely with zeros for nofk.

**Comment by prckent** [comment]
Additional question: is there an equivalent to get_ratios ( #464 ) that has not yet been hit before this error/missing implementation?

**Comment by jtkrogel** [comment]
CPU Hamiltonian code path uses MomentumEstimator::evaluate which contains the call to TrialWaveFunction::get_ratios.

GPU Hamiltonian code path uses MomentumEstimator::addEnergy instead of evaluate.  This function is currently empty for MomentumEstimator (the QMCHamiltonianBase empty version is called), but should it be implemented, it would need to contain a call to get_ratios, which does not appear to be supported for any GPU-enabled wavefunction component.

Apparently supports get_ratios (CPU-only): SlaterDet, OneBodyJastrowOrbital, TwoBodyJastrowOrbital, kspaceJastrow.

Does not support get_ratios: J3, backflow, multideterminant, multideterminant-backflow, anything for gpu.

**Comment by prckent** [comment]
Thanks. We'll have to discuss how to fix this half bakery since we need this for science soon.

It is very tempting to make all the functions in OrbitalBase that should be virtual actually virtual so that the responsibility for declaring an error goes with the (non)implementer. This would make it a lot easier to identify what is actually missing. Integration tests with these errors would also help.

**Comment by prckent** [comment]
Debugging/fixing and extending the CPU AoS implementations should take precedence  over GPU implementation because that is by far the shortest route to science. A trusted reference implementation will also be needed for the (hopefully simple) GPU implementation.

**Comment by prckent** [comment]
These missing CUDA capabilities will never be implemented by the main developers, so I am closing the issue. Anyone needing these is welcome to make the updates themselves. The plan is to delete the legacy CUDA implementation, delete the legacy AoS CPU implementation, and concentrate on adding GPU capabilities to the "SoA" CPU code in a fully compatible manner. Moving forward QMCPACK will not have internal forks and sparse feature coverage such as this.
