### ISSUE TITLE
Is QMC_ASYNC_COLLECT still useful in Estimators?

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#469]
The QMC_ASYNC_COLLECT define turns on asynchronous MPI communication for the Estimators in collectBlockAverages.
It was added in 2006, and it was deactivated by default in 2007 (the define for it in EstimatorManager.cpp was commented out)

Two questions
1. Is this particular code still used or useful?  (I would guess not based on how little attention it's had in the log)
2.  More generally, is collection of the estimators from the nodes a bottleneck or potential bottleneck?  Is this code (or similar) likely to be useful in the future?

**Comment by jngkim** [comment]
1. It was not used in production. First, it did not affect performance.
Cray MPI had a lot of problems at scale and the combination of asynchronous
and collective is still not well supported.
2. We should avoid ever coming to the point when this becomes a bottleneck.
The code can be removed.

**Comment by jtkrogel** [comment]
I can't comment on (1), but possibly on (2).  I've seen performance hits of 15-20% when writing Collectables (e.g. spin density, order 10 GB) vs performance hits of 5% when using traces (order 10 TB), so yes the collection of estimators can impact performance.

The difference says something about the efficiency of the overall network for writes (traces), vs the overhead from using collective communication for large chunks of data (spin density).

We haven't done a systematic study recently (maybe we did at some earlier point?) of the effects of using estimators like the spin density as a function of system size and node count.

**Comment by jngkim** [comment]
Yes, that is the case.

One should be careful with a collective of large messages which becomes the
serial bottleneck.
This can be fixed using multiple endpoints and something I can experiment
with Intel MPI.

**Comment by jngkim** [comment]
Back to Mark's question on eliminating Async: yes, please do.

It has a danger of using too much memory with collectables and
parallelizing with OpenMP will give much more boost than async method as
written.

**Comment by ye-luo** [comment]
I can confirm that async collectables are eating extra memory.
