### ISSUE TITLE
Batched Optimization Run Crash With Improper walkers_per_rank choice

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#4690]
**Describe the bug**
For the batched linear optimization driver, it appears as though if the walkers_per_rank flag is not set to be commensurate with the number of cores per rank, the code will crash during the optimization step.  Specifically, VMC sample collection proceeds without issue, but during the actual optimization, it will crash.  Sometimes without notification, sometimes with "NaN" and "divide by zero" warnings.  

**To Reproduce**
1. release version or git commit hash being built:  Last git commit: 45f7840026c1d6d6ee3487ccadea9db0f7fda173
2. cmake command:  cmake -DQMC_COMPLEX=1 -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_FLAGS="-xCORE-AVX512" -DCMAKE_CXX_FLAGS="-xCORE-AVX512" ..
3. full program/test invocation command:  Included in reproducer.  
4. Set OMP_NUM_THREADS=4.  Test cases should handle the rest.  

**Expected behavior**
Not to crash, give reasonable parameter updates, iterate.  If the walkers_per_rank has to be some integer multiple of something, code needs to catch this and abort with an error message.  

**System:**
 - system name:  Attaway
 - Modules:  gnu/10.2.1, intel/22.2.0, mkl/22.2.0, openmpi-intel/4.0, cmake/3.22.3

**Additional context**
Noticed this when doing non-collinear calculations, but it seems to be present in spin polarized calculations as well.
[spin_polarized_opt_bug.tar.gz](https://github.com/QMCPACK/qmcpack/files/12255611/spin_polarized_opt_bug.tar.gz)

**Comment by ye-luo** [comment]
The behavior needs to be the same as VMC. When `walkers_per_rank` is not set, one walker per thread (indirectly per core) is set by the code. When `walkers_per_rank` is set, the code must do exactly as the input. So this is clearly a bug.

**Comment by prckent** [comment]
Thanks Mark for #4691 .

General comment:

All the logic for setting the walker count that will be should be in one place for each method. Here the code should make reasonable efforts to keep going (Jaron's point) and in general implement sensible defaults for user productivity.

As much as possible, we should write the rest of the code to be flexible regarding the actual number of walkers. => Particularly for new code, we should guard against zeros and walker counts that are not simple divisors of parallelization settings. This will give us more flexibility and better maintenance long term.
