### ISSUE TITLE
Expected Runtime of CTests for QMCPACK?

### ISSUE THREAD

**Issue by etpalmer63** [QMCPACK/qmcpack#4749]
Hi QMCPACK,

I'm a software integration engineer at NERSC and I've been working on helping a user install QMCPACK on Perlmutter. I was able to successfully build the code, but I wanted to ask about the tests that run with post-build ctest command. 

When I run the command, `ctest -R short -LE unstable` , it takes a very long time to complete (>8 hours). Is this normal? Or is there a performance issue I should be trying to track down next? Also, what set of tests do you recommend we use to validate an install? 

Thank you!

Erik

**Comment by prckent** [comment]
Possibly normal depending on the machine setup, however you can exclude the "short" tests for an installation check.

We would recommend ctest -j 64 -R deterministic as an installation check, adjusting the parallelization option for what is reasonable on the build machine. This includes the unit test and deterministic tests only; the latter are very quick to run integration tests. For CPU only builds, these should complete in a few minutes. This is the case even on a Ryzen 6850U or Apple M1 laptop. You can get an idea at https://cdash.qmcpack.org/CDash/index.php?project=QMCPACK . GPU builds and tests only use one 1 GPU, effectively serializing, and will take longer.

**Comment by etpalmer63** [comment]
I ran `ctest -j 64 -R deterministic --output-on-failure` and got a total time of about 19 mins (1146.39 secs) for `cpu_real` . This still seems a bit off what I hoped performance would be but I did get 100% passing. 

I'll retry with one of the GPU builds but I just ran into an issue trying to rebuild it tonight. Hopefully I just overlooked something. 

Thanks for your input!

**Comment by etpalmer63** [comment]
Ok, `ctest -j 256 -R deterministic`  is getting down to 444.76 secs. I'm starting to feel better.
