### ISSUE TITLE
add MW resource collection for AO rad/sph components

### ISSUE THREAD

**Issue by kgasperich** [QMCPACK/qmcpack#4803]
If we have MW resource collections for the radial and angular AO components, we can reduce the amount of data transfer we do and also reduce device memory usage.

- For `SoaAtomicBasisSet`
  - add [`periodic_image_displacements` and `periodic_image_phase_factors`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/QMCWaveFunctions/LCAO/SoaAtomicBasisSet.h#L53-L54) to the MW resource collection.
  - add MW version of [`SoaAtomicBasisSet::setPBCParams`](https://github.com/kgasperich/qmcpack/blob/8bce6a6478fd25827882be2cb3b63a3ecaa9bf7e/src/QMCWaveFunctions/LCAO/SoaAtomicBasisSet.h#L112-L127) to assign correct values to these and update the device data
(will also need to make MW version of  [`SoaLocalizedBasisSet::setPBCParams`](https://github.com/kgasperich/qmcpack/blob/8bce6a6478fd25827882be2cb3b63a3ecaa9bf7e/src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.cpp#L103-L113), and call this MW version from the LCAO builder ([xml](https://github.com/kgasperich/qmcpack/blob/8bce6a6478fd25827882be2cb3b63a3ecaa9bf7e/src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp#L367), [h5](https://github.com/kgasperich/qmcpack/blob/8bce6a6478fd25827882be2cb3b63a3ecaa9bf7e/src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp#L367))

- For `MultiQuinticSpline1D`
  - add MW resource collection for [`coeffs` and `first_deriv`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/QMCWaveFunctions/LCAO/MultiQuinticSpline1D.h#L118-L119)
  - add MW version of [`add_spline`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/QMCWaveFunctions/LCAO/MultiQuinticSpline1D.h#L330-L356C4) to assign correct values to these and update device data.
  - consider combining [`initialize`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/QMCWaveFunctions/LCAO/MultiQuinticSpline1D.h#L316-L327) and `add_spline` into single `mw_initialize` function 
    - If I'm reading this correctly, we can't change the allocated size of `coeffs` and `first_deriv` after `initialize` anyway, so the only reason I can see for keeping them separate is that it might be easier to parse the xml/h5 if we add them one at a time?
- For `MultiFunctorAdapter`
  - [`batched_evaluate`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/QMCWaveFunctions/LCAO/MultiQuinticSpline1D.h#L316-L327) is still all done on the host, but fixing that is outside of the scope of this issue.
  - might still need to define some no-op resource-related functions here (or do some type checking in SoaAtomicBasisSet to avoid calling  `MultiRnl->{create,acquire,release}Resource` for the radial component if we have a `MultiFunctorAdapter`)
- For `SoaSphericalTensor`
  - add MW resource collection for [`NormFactor`, `Factor{L,LM,2L}`](https://github.com/kgasperich/qmcpack/blob/8bce6a6478fd25827882be2cb3b63a3ecaa9bf7e/src/Numerics/SoaSphericalTensor.h#L46-L53)
  - add some mw_initialize function to initialize data on device (currently done in [constructor](https://github.com/kgasperich/qmcpack/blob/8bce6a6478fd25827882be2cb3b63a3ecaa9bf7e/src/Numerics/SoaSphericalTensor.h#L163-L215), so this may need to be changed a bit)
 
- For `SoaCartesianTensor`
  - similar to `SoaSphericalTensor`, but only need [`NormFactor`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/Numerics/SoaCartesianTensor.h#L49-L50)
  - add some mw_initialize function to initialize data on device (currently done in [constructor](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/Numerics/SoaCartesianTensor.h#L143-L179), so this may need to be changed a bit)

- (optional) scratch space in [`SoaCartesianTensor`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/Numerics/SoaCartesianTensor.h#L53) and [`SoaSphericalTensor`](https://github.com/kgasperich/qmcpack/blob/35234492359a321c45bc9c181535e0c04fe35435/src/Numerics/SoaSphericalTensor.h#L55)
  - I've been passing in pre-allocated scratch space from the SoaAtomicBasisSet MW resource collection, but it might be worth considering using arrays that belong to the Ylm object instead? (this would be closer to the single-walker functionality)

**Comment by ye-luo** [comment]
#4808 resolved

- For `SoaAtomicBasisSet`. Constant data changed to dual space and shared_ptr.
- For `MultiQuinticSpline1D`. Constant data changed to dual space and shared_ptr.
- For `MultiFunctorAdapter`. untouched.
- For `SoaSphericalTensor` and `SoaCartesianTensor`. Constant data changed to dual space and shared_ptr.
