### ISSUE TITLE
Remove warnings caused by#4808 

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#4810]
**Describe the bug**
struct class mismatch in SoaSphericalTensor.

**To Reproduce**
build with a compiler such as clang 16 that warns for this.

**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

**Comment by ye-luo** [comment]
I was expecting CI to stop me. It seems that GCC `-Werror` doesn't complain.
