### ISSUE TITLE
NEXUS example tests run and fail when numpy is not available

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#484]
Numpy availability test or bypass needed  

```
    Start 274: nexus_example_c20

274: Test command: /opt/local/bin/python "nexus_example_test.py" "/Users/ .... /c20" "--nexus-file" "c20.py" "--nexus-path" "/Users/ .... /examples/../library"
274: Test timeout computed to be: 240
274: ('Error ', <type 'exceptions.ImportError'>, ImportError('No module named numpy',))
274:   FAIL
1/8 Test #274: nexus_example_c20 .....................***Failed    0.08 sec
```

**Comment by jtkrogel** [comment]
This needs to be caught early in the test system (e.g. if numpy is not available, do not attempt to run nexus tests at all).  

I thought we were already guarding for numpy, h5py, etc in the test system.  @markdewing has something changed about this or am I remembering wrong?

**Comment by markdewing** [comment]
The python module checks only guard particular tests.  I'll change it so they guard the nexus tests.
