### ISSUE TITLE
Updates to CI images needed

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4846]
**Describe the bug**
Noticed in #4845 CI failure.
https://github.com/QMCPACK/qmcpack/actions/runs/6950210526/job/18909921650?pr=4845
Shows `ghcr.io/qmcpack/ubuntu2110-serial:latest` image has outdated software.
I think we should use `ghcr.io/qmcpack/ubuntu22-openmpi:latest` instead.
I noticed that `ghcr.io/qmcpack/ubuntu22-openmpi:latest` has gcc-11 although default to gcc-9.
We can just change `https://github.com/QMCPACK/qmcpack/blob/27c8838292e922925717f49b2ce7bf6f3182c901/tests/test_automation/github-actions/ci/run_step.sh#L121` to `g++-9` and `g++-11` respectively.
Maintaining fewer images always wins.

**Comment by prckent** [comment]
Use of separate images for MPI and no-MPI configurations is very intentional. This is to ensure there is no mpi.h that can be accidentally used by the no-MPI builds, giving us a falsely passing set of no-MPI tests. We had something similar occur recently with OpenMP includes. => We should keep maintaining these different images all the while it is lightweight enough to do so.

**Comment by ye-luo** [comment]
For that purpose, we can just a public base image which naturally comes without MPI or even OpenMP(in Mac). Lack of maintenance of the non-MPI image indicates we potentially need changes.

**Comment by prckent** [comment]
You are making the more important point - something is out of date and the images are apparently not in sync (?). For the nightlies we take care to have the only difference between the MPI and no-MPI images as exactly that to aid debugging and keep things simple. => We should update the CI images consistently to a set of new and consistent versions. What are your preferences? I note #4845 . Anything else?

**Comment by ye-luo** [comment]
I still don't like jumping between CI images for only have a non-MPI environment which is unnecessary IMO. The best way of fixing out-of-sync issue is to keep only one copy. But if you insist, I can live with that. Apart from CMake, I noticed one is in ubuntu 22.04 and one is in 21.10 (tell by the name) which is EOL.

**Comment by ye-luo** [comment]
Still prefer to keep some CI with gcc-9 as our oldest gcc support. For the newest gcc, I would skip gcc 11 but prefer gcc-12 which might see better code coverage accuracy I guess.

**Comment by prckent** [comment]
I suggest william makes a "serial" directory with a fresh dockerfile that will be the same as the openmpi one except for removing mpi packages.

Good point on the OS. Both should be ubuntu 22.04.

OK on the gcc9.

When I look at what slows down our CI overall, it is generally the self-hosted GPU builds. For more variety and without slowing the testing much, we can add more self-hosted CPU builds.
