### ISSUE TITLE
Time limit 

### ISSUE THREAD

**Issue by BUfangj** [QMCPACK/qmcpack#4858]
Good morning! I do not konw weather it's a bug or not. I had a problem doing DMC calculations when block is set to 100 and steps is set to 102400 last week. The calculation stopped on the 26th block, and the error reported was Time limit reached for DMC, which is the time limit set internally by qmcpack? can I reset it? 
Best regards.

**Comment by prckent** [comment]
See https://qmcpack.readthedocs.io/en/develop/input_overview.html#time-limits

Use either max_seconds (batched drivers) or maxcpusecs . There are examples of these in the tests (grep -R -n -i max_seconds qmcpack/tests/*).

I recommend trying a small value to verify the code aborts as expected before doing a long production run with a different value.

**Comment by BUfangj** [comment]
Thank you for your reply and suggestions, it helped me a lot
