### ISSUE TITLE
OSX CI is broken, can't find HDF5

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#4907]
**Describe the bug**
Makes otherwise clean PR look failing.

**To Reproduce**
Seeming just bump a PR

**Expected behavior**
HDF5 library can be found.

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

**Comment by prckent** [comment]
Something changed with GitHub CI or the software we pull in the mac CI image. The version of HDF5 used is fine elsewhere and has not been changed recently.
