### ISSUE TITLE
MatrixDelayedUpdateCUDA needs mw_evalGradWithSpin

### ISSUE THREAD

**Issue by camelto2** [QMCPACK/qmcpack#4920]
**Is your feature request related to a problem? Please describe.**
MatrixDelayedUpdateCUDA currently has a throw stating it needs an implementation of mw_evalGradWithSpin. Once this is implemented, need to remove guard in test_TrialWaveFunction introduced in #4918. 

**Describe the solution you'd like**
Implement the missing API. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ye-luo** [comment]
Completed by https://github.com/QMCPACK/qmcpack/pull/5026
