### ISSUE TITLE
Mac OS CI unstable

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4924]
**Describe the bug**
The gcc-12 being used has bugs and failure was sporadic https://github.com/QMCPACK/qmcpack/actions/runs/7891319137/job/21535393463#step:6:126

Based on https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
It is from HomeBrew. Will give gcc 13 a try.

**Comment by camelto2** [comment]
This error used to happen to me a lot on my mac. It had something to do with some updates they made to the command line tools. Reverting to a previous version seems to fix it. However, I haven't had this problem in a while and I'm using the current CLT

**Comment by camelto2** [comment]
At least on my mac, changing to a different gcc did not help. I had to change my CLT to the previous version.

**Comment by camelto2** [comment]
https://forums.developer.apple.com/forums/thread/737707

**Comment by ye-luo** [comment]
Got some warning with gcc 13. https://github.com/QMCPACK/qmcpack/actions/runs/7891758172/job/21536758598#step:6:687
trying macos-14 with gcc12.

**Comment by ye-luo** [comment]
macos-14 with both gcc12 and 13 choked at FindHDF5.

**Comment by camelto2** [comment]
Probably need to update the hdf5 as well. I always have to brew reinstall packages whenever I update the OS to a new version

**Comment by ye-luo** [comment]
OK. The current solution is using the classic linker.
