### ISSUE TITLE
Nexus tests fail with Python 3.12 due to deprecated imp module

### ISSUE THREAD

**Issue by williamfgc** [QMCPACK/qmcpack#4949]
**Describe the bug**
Nexus tests are not passing CI due to use of the deprecated imp module starting with Python 3.12
e.g. [this line in machines.py#L57](https://github.com/QMCPACK/qmcpack/blob/develop/nexus/lib/machines.py#L57)

**To Reproduce**
See CI [log](https://github.com/QMCPACK/qmcpack/actions/runs/8473364587/job/23217504835#step:7:1546) on macOS using Python 3.12

**Expected behavior**
Nexus tests should pass

**System:**
 - macOS CI
 - Any Python 3.12 installation
 
**Additional context**
Replace module imp in favor of importlib as indicated in the [documentation](https://docs.python.org/3.11/library/imp.html)

**Comment by prckent** [comment]
Quick followup note after discussing with Jaron and checking the python release history. imp was marked deprecated in python 3.4.0 released 17 March 2014 and finally removed on 3.12.0 released 2 October 2023. Therefore while we could straightforwardly protect the import, in practice it won't be long before a workaround is needed to support this functionality for most users. However it is only needed for those who can't/won't patch machines.py locally.
