### ISSUE TITLE
Too many warmup steps, diamondC_2x1x1-Gaussian_pp/det_qmc_short_vmcbatch_dmcbatch.in.xml

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4950]
**Describe the bug**
https://github.com/QMCPACK/qmcpack/blob/03e821b46f933546108b94af564bd707a894138d/tests/solids/diamondC_2x1x1-Gaussian_pp/det_qmc_short_vmcbatch_dmcbatch.in.xml#L20
100 step warmup makes GPU runs taking 20sec. It is too long. Better to reduce it to 3 like all other deterministic tests.

**Comment by prckent** [comment]
(Quick note that happily this is the only det_*.xml with this issue)
