### ISSUE TITLE
Batch optimization leads to  hanging before start

### ISSUE THREAD

**Issue by anbenali** [QMCPACK/qmcpack#4959]
**Describe the bug**
Trying to run Jastrow optimization or Orbital Optimization with batch code fail. The VMC block prior to the optimization runs well, but then the code hangs in 
```
*****************************************
Building overlap and Hamiltonian matrices
*****************************************
```
Same code in legacy (and replacing walkers_per_rank with Samples works fine. 

**To Reproduce**
All files to reproduce attached in the following. 
[Optimization_issue.tar.gz](https://github.com/QMCPACK/qmcpack/files/15027710/Optimization_issue.tar.gz)
1. release version or git commit hash being built
```
     
  Git branch: develop
  Last git commit: ce1c0bee4e7c1d983c7a45e5b6824b93aeea0832-dirty
  Last git commit date: Fri Jan 5 14:35:58 2024 -0500
  Last git commit subject: Merge pull request #4894 from ye-luo/fix-MP
```
This is the standard build by @ye-luo  on Polaris. 

**Expected behavior**
Jastrow or Orbital optimization

**System:**
 - system name [e.g. fusiont5, summit]
      Polaris

 - modules loaded [e.g. output of `module list`]
      Currently Loaded Modules:
```
  1) nvhpc/22.11        4) cray-mpich/8.1.25   7) cray-libpals/1.2.11  10) craype-network-ofi      13) libfabric/1.15.2.0
  2) craype/2.7.20      5) cray-pmi/6.1.10     8) PrgEnv-nvhpc/8.3.3   11) perftools-base/23.03.0
  3) cray-dsmml/0.2.2   6) cray-pals/1.2.11    9) craype-x86-rome      12) craype-accel-nvidia80
```

 - other systems where this is reproducible [e.g. "my laptop", "none"]
none

**Additional context**
Not the first time this happens.. Similar issue seen by Andra Zen & Co

**Comment by camelto2** [comment]
the build overlap and hamiltonian matrices is one of the bottlenecks. I expect the code isn't "hanging", but you have 10k parameters and this part of the calculation is just slow

**Comment by markdewing** [comment]
The legacy version completes, though.  I'm curious how long the fill function takes in that case (and the eigenvalue solve)

**Comment by camelto2** [comment]
> The legacy version completes, though. I'm curious how long the fill function takes in that case (and the eigenvalue solve)

I didn't read closely enough to see that legacy worked. 

We had cases in the beginning where we thought it was hanging in build overlap for batched for problems of this size, but it ended up being that all the threads were spawned on one core because the OMP affinity settings weren't correct. I assume that isn't happening here?

**Comment by anbenali** [comment]
Keep in mind, this hangs also for simple 1,2 and 3 body jastrow
optimization without OO. I was never able to get the batch optimization to
work. Hence putting the jastrow only WF.

**Comment by prckent** [comment]
1. How long did you wait with the hang?
2. "Keep in mind, this hangs also for simple 1,2 and 3 body jastrow optimization without OO. I was never able to get the batch optimization to work." Can you describe further? Slow convergence/obviously bad numerics/crash?. Which optimizer etc.?

**Comment by ye-luo** [comment]
@markdewing What did you mean by "The legacy version completes"? Not understanding. Did you try a run with the reproducer?

**Comment by anbenali** [comment]
It means that the same input with same wavefunction runs fine (whatever
that means for an optimizer) with the legacy driver but hangs with the
batched driver.

Again, I have not been able to successfully optimize 1, 2 and 3 body
jastrows with LCAO with the batched driver. While there are no issues with
legacy.

**Comment by ye-luo** [comment]
```
Again, I have not been able to successfully optimize 1, 2 and 3 body
jastrows with LCAO with the batched driver. While there are no issues with
legacy.
```
Did you mean 1) hang or 2) all proposed parameters rejected or 3) parameters are changing but doesn't lower energy?

Could you upload your output files?
I ran J123 optimization on my workstation and polaris. It seems fine. From Polaris.
```
qmca -e 2 -q ev *.scalar.dat
 
                            LocalEnergy               Variance           ratio 
paraquinone  series 0  -68.332672 +/- 0.001649   1.195709 +/- 0.010840   0.0175 
paraquinone  series 1  -68.331383 +/- 0.001528   1.201866 +/- 0.011193   0.0176 
paraquinone  series 2  -68.332755 +/- 0.001348   1.183246 +/- 0.008225   0.0173 
paraquinone  series 3  -68.332284 +/- 0.001658   1.339845 +/- 0.162084   0.0196 
```

**Comment by ye-luo** [comment]
Try cutdown the number of blocks to 1 and see if it still hangs.

**Comment by anbenali** [comment]
I ran the same input with Polaris but with legacy and I get with 20 nodes the following:
''' 
                            LocalEnergy               Variance           ratio 
paraquinone  series 0  -68.332758 +/- 0.001228   1.199376 +/- 0.008308   0.0176 
paraquinone  series 1  -68.334208 +/- 0.001360   1.214502 +/- 0.008327   0.0178 
paraquinone  series 2  -68.312433 +/- 0.001456   1.294571 +/- 0.005991   0.0190 
paraquinone  series 3  -68.310320 +/- 0.001353   1.294074 +/- 0.007196   0.0189 
paraquinone  series 4  -68.305985 +/- 0.001266   1.435195 +/- 0.106026   0.0210 
paraquinone  series 5  -68.303659 +/- 0.001320   1.342323 +/- 0.013391   0.0197 
paraquinone  series 6  -68.301372 +/- 0.001263   1.361414 +/- 0.018238   0.0199 
paraquinone  series 7  -68.264232 +/- 0.001766   1.537146 +/- 0.013821   0.0225 
paraquinone  series 8  -68.259748 +/- 0.001368   1.539428 +/- 0.012193   0.0226 
paraquinone  series 9  -68.260442 +/- 0.001601   1.575466 +/- 0.024732   0.0231 
'''
but with the batched I get this

'''
                           LocalEnergy               Variance           ratio 
paraquinone  series 0  -68.332550 +/- 0.000373   1.207556 +/- 0.004162   0.0177 
'''

this is with 20 nodes on polaris for 1h30 min for both codes.

**Comment by ye-luo** [comment]
Could you provide both printout files? Would like to diff.

**Comment by ye-luo** [comment]
Oh remember, since you are using walkers_per_rank which legacy doesn't honor. You run much lower walker/sample count with legacy and hence faster.

**Comment by anbenali** [comment]
> Oh remember, since you are using walkers_per_rank which legacy doesn't honor. You run much lower walker/sample count with legacy and hence faster.

As I said and can be seen in the input and outputs I provided, I commented walker_per_rank on the legacy and replaced it with samples. 

[output.tar.gz](https://github.com/QMCPACK/qmcpack/files/15030978/output.tar.gz)

**Comment by ye-luo** [comment]
The legacy driver run generates `80000` samples but your batched driver run generated `16000000`. 200x difference.

**Comment by markdewing** [comment]
Would #4224 ease this issue, since it would make the `samples` tag behave similarly between the legacy and batched drivers? (I realize this build is older than that PR merge, so it won't work yet)

**Comment by ye-luo** [comment]
> Would #4224 ease this issue, since it would make the `samples` tag behave similarly between the legacy and batched drivers? (I realize this build is older than that PR merge, so it won't work yet)

The current run with legacy driver activates `stepsbetweensamples = 16` which is disallowed in the batched driver. #4224 should reject the current value of "samples" use in the legacy driver run.

**Comment by ye-luo** [comment]
I added a bit print to the code and obtained
```
paraquinone.qmc.in-wfj.out:  Execution time (sampling) = 2.9441e+00
paraquinone.qmc.in-wfj.out:  Execution time (derivatives) = 3.2054e+01
paraquinone.qmc.in-wfj.out:  Execution time (building matrices) = 3.8318e+02
paraquinone.qmc.in-wfj.out:  Execution time (eigenvalue) = 3.7726e+02
paraquinone.qmc.in-wfj.out:  QMC Execution time = 797.4 secs
```
with `samples per rank = 4000`. @anbenali did `samples per rank = 200000` so 50x.
sampling, derivatives and building matrices are all expected to increase 50x.
In the output from @anbenali, calculating derivatives took 1.5782e+03, matching 50x well.
So building matrices should take 19150 second. Clearly time out.

There is no hang. the job does need more time. Or try to reduce the amount of samples, for example, reducing `blocks` from 500 to 50.

In addition, I found the timer report nesting was quite messed up. I will make some improvements.

**Comment by jptowns** [comment]
We met yesterday and I think we sorted things out. As mentioned by others the main issue was the very large number of samples per MPI task. This lead to a very long time required to compute derivatives and build the linear method matrices. We got the problem working by running fewer samples per MPI task and using more nodes.

**Comment by prckent** [comment]
Great. My understanding then is that (i) using the samples tag in the batched driver would minimize the risk of this problem (ii) printing some timing guidance would be helpful

**Comment by ye-luo** [comment]
More timing info has been provided since https://github.com/QMCPACK/qmcpack/pull/4960
Or use QMCPACK timer after https://github.com/QMCPACK/qmcpack/pull/4961
