### ISSUE TITLE
Stop the code on the fly

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#498]
Sometimes, I feel the need to stop the code execution on the fly and exit clean. Is this useful?
Basically the code monitors a file at the end of each block.

**Comment by jtkrogel** [comment]
I think a "kill switch" file could be useful, though hopefully the filesystem touches won't introduce (parallel) block points.

I've been considering implementing something similar for Nexus to allow control of e.g. long lived background nohup'ed Nexus scripts.

**Comment by kylanpaa** [comment]
I also think a "kill switch" file could be useful. Possible even some kind of a control file that can potentially interact with qmcpack also by other means, e.g., stop cleanly after the next 5 hours or as soon as possible after some specific date and time, or start using checkpoints etc.

I assume a clean "kill" would include a checkpoint file. It would be good to be able to continue the run if needed.
