### ISSUE TITLE
QMCPACK 3.17.1 installation error

### ISSUE THREAD

**Issue by Walser52** [QMCPACK/qmcpack#4980]
**Problem During Installation**
I'm trying to install QMCPACK 3.17.1. I installed most of the libraries in a conda environment. 

The cmake command runs fine:

`cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ ..`

But when I do `make -j 8`, I get the error below.

**Error generated**
At around 18% I get the following errors:

```
[ 17%] Building CXX object src/Utilities/CMakeFiles/qmcutil.dir/TimerManager.cpp.o
[ 17%] Building CXX object src/Utilities/CMakeFiles/qmcutil.dir/RunTimeManager.cpp.o
[ 17%] Building CXX object src/Numerics/CMakeFiles/qmcnumerics.dir/SoaSphericalTensor.cpp.o
[ 17%] Building CXX object src/Utilities/CMakeFiles/qmcutil.dir/ProgressReportEngine.cpp.o
[ 17%] Linking CXX executable ../../bin/qmc-extract-eshdf-kvectors
/home/misbah/miniforge3/envs/qmcpack/bin/../lib/gcc/x86_64-conda-linux-gnu/13.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: liblzma.so.5, needed by /usr/lib64/libxml2.so, not found (try using -rpath or -rpath-link)            [1/1972]
/home/misbah/miniforge3/envs/qmcpack/bin/../lib/gcc/x86_64-conda-linux-gnu/13.2.0/../../../../x86_64-conda-linux-gnu/bin/l
d: /usr/lib64/libxml2.so: undefined reference to `lzma_properties_decode@XZ_5.0'
/home/misbah/miniforge3/envs/qmcpack/bin/../lib/gcc/x86_64-conda-linux-gnu/13.2.0/../../../../x86_64-conda-linux-gnu/bin/$
d: /usr/lib64/libxml2.so: undefined reference to `lzma_code@XZ_5.0'
/home/misbah/miniforge3/envs/qmcpack/bin/../lib/gcc/x86_64-conda-linux-gnu/13.2.0/../../../../x86_64-conda-linux-gnu/bin/$
d: /usr/lib64/libxml2.so: undefined reference to `lzma_auto_decoder@XZ_5.0'
/home/misbah/miniforge3/envs/qmcpack/bin/../lib/gcc/x86_64-conda-linux-gnu/13.2.0/../../../../x86_64-conda-linux-gnu/bin/$
d: /usr/lib64/libxml2.so: undefined reference to `lzma_end@XZ_5.0'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/qmc-extract-eshdf-kvectors] Error 1
make[1]: *** [src/QMCTools/CMakeFiles/qmc-extract-eshdf-kvectors.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object src/Utilities/CMakeFiles/qmcutil.dir/unit_conversion.cpp.o
[ 17%] Linking CXX executable ../../../../bin/ppconvert
[ 17%] Built target ppconvert
[ 18%] Building CXX object src/Utilities/CMakeFiles/qmcutil.dir/ResourceCollection.cpp.o
[ 18%] Linking CXX static library libqmcnumerics.a
[ 18%] Building CXX object src/Utilities/CMakeFiles/qmcutil.dir/ProjectData.cpp.o
[ 18%] Built target qmcnumerics
[ 18%] Building CXX object src/Utilities/CMakeFiles/qmcutil.dir/RandomNumberControl.cpp.o
[ 18%] Linking CXX static library libqmcutil.a
[ 18%] Built target qmcutil
[ 18%] Linking CXX static library libcatch_main_no_mpi.a
[ 18%] Built target catch_main_no_mpi
[ 18%] Linking CXX static library libcatch_main.a
[ 18%] Built target catch_main
make: *** [all] Error 2
```

I am also attaching the contents of my conda environment. 

Thank you for your time. 

[conda_qmcpack.txt](https://github.com/QMCPACK/qmcpack/files/15271649/conda_qmcpack.txt)

**Comment by ye-luo** [comment]
The linking error
```
/usr/lib64/libxml2.so: undefined reference to `lzma_properties_decode@XZ_5.0'
```
Indicate there is a mismatch between the system libxml2 and the dynamically loaded libxz probably from your conda environment. A quick attempt can be installing the libxml2 from conda as well. Technically the root causes are unrelated to QMCPACK and you may debug the issue without QMCPACK.

**Comment by prckent** [comment]
Thanks for trying QMCPACK. We make only minimal use of libxml2, and as noted by Ye, the problem is coming from what your libxml2 uses. Probably there is some conflict between the libraries you are getting via conda and the system ones. This could be something a simple as a missed path or library. Maybe trying getting libxml2 and liblzma both from conda? If you have not already, you might try installing QMCPACK natively following the regular installation instructions for (say) Ubuntu, and if this works, as it should, then try conda and compare.

**Comment by Walser52** [comment]
It seems that libxml2 was already installed via conda but the installer was using the `/usr/lib64` one. Adding the library path via `locate libxml2.so` and then adding it to `LD_LIBRARY_PATH` seemed to do the trick. 

`echo 'export LD_LIBRARY_PATH=/export/home/misbah/miniforge3/lib/:$LD_LIBRARY_PATH' >> ~/.bashrc
`

Installation was successful after that. Thank you for your help.
