### ISSUE TITLE
Multidet wavefunction problems in batched code

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#4992]
The batched code produces gigantic kinetic energy spikes and incorrect acceptance ratios (with and without drift) for VMC for general multideterminant wavefunctions.

This problem was observed for the LiH test problem included with QMCPACK when the coefficients in the MSD file were changed by hand/with a tool.  

The legacy code handles the updated coefficients without issue, as evidenced by successful self-healing DMC iterations converging on exact results.

Included/attached is a short deterministic 1 MPI 1 OMP-thread run to reproduce and hunt down this issue.  For VMC, the batched and legacy drivers were verified to deterministically reproduce each other for the full original wavefunction as well as the updated wavefunction when restriced to MSD with a single determinant.  The included case uses 2-determinants, which is sufficient to show the problem.

The first presenting issue is that the kinetic energy is crazy for some walker steps with the batched code (the spike at step 9 goes up to **400 Ha**):
![batched_vs_legacy_2det_1walker__kinetic](https://github.com/QMCPACK/qmcpack/assets/24547905/84f1786b-59a3-44ba-8ee9-577779ae2cd9)

The second issue is that the acceptance ratio is too low in the batched code with and without drift, which affects quantities like the electron-electron energy:
![batched_vs_legacy_2det_1walker__elecelec](https://github.com/QMCPACK/qmcpack/assets/24547905/67fca810-594d-4f7d-bd36-37b7313b5993)

The legacy driver (and also the batched one for the correctly functioning related cases described above), produces an acceptance ratio near 60%, while for the problem case with the batched code an acceptance ratio closer to 40% is observed.

The very fast fixed seed deterministic test cases are attached (each run finishes in 10ms):
[lih_short_deterministic.zip](https://github.com/QMCPACK/qmcpack/files/15313694/lih_short_deterministic.zip)

**Expected behavior**
The batched code should reproduce the legacy code deterministically, quantity for quantity, for each MC step.

**System:**

Laptop.

**Comment by jtkrogel** [comment]
Here is a plot of the local energy of the longer original 5-determinant run (batched vs legacy):
![Uploading lih_multidet_5rand__batched_vs_legacy.png…]()

**Comment by prckent** [comment]
Of note, VMC without drift gives wrong acceptance ratio => the value of the wavefunction is wrong.

**Comment by ye-luo** [comment]
> when the coefficients in the MSD file were changed by hand/with a tool.

Please explain what dataset has been changed and how.

**Comment by jtkrogel** [comment]
These basic operations were performed (Python pseudo-code):
```
h = read_hdf('./LiH.orbs.h5')
h.MultiDet.Coeff[:] = 0
h.MultiDet.Coeff[:5] = np.random.random(5)
```

The bug persists even when only the second determinant (index 1) has a finite coefficient:
```
h = read_hdf('./LiH.orbs.h5')
h.MultiDet.Coeff[:] = 0
h.MultiDet.Coeff[1] = 1.0
```
