### ISSUE TITLE
deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4 hidden error

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4997]
**Describe the bug**
Current develop.
```
ctest -R deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4 -VV
    Start 1148: deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4-check

1148: Test command: /usr/bin/python3.10 "/home/yeluo/opt/qmcpack/tests/scripts/check_stats.py" "-s" "1" "-q" "1rdm" "-e" "0" "-c" "8" "-p" "det_qmc_1rdm_short_vmc_dmc" "-r" "qmc-ref/det_qmc_1rdm_short_vmc_dmc.s001.stat_ref_1rdm_4_4_real.dat"
1148: Test timeout computed to be: 3600
1148: hdfreader error: encountered invalid type: <class 'h5py._debian_h5py_serial._hl.group.Group'>
2/2 Test #1148: deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4-check ...   Passed    0.11 sec
```
both tests show pass but the "hdfreader error" is concerning. 
Is check_stats.py not robust? Probably not checking file operation(open/read) status?

**Comment by jtkrogel** [comment]
What is the Python environment on the machine in question?  Do you see this error elsewhere?

**Comment by ye-luo** [comment]
It is Ubuntu 22.04.4 OS provided python and h5py.

**Comment by jtkrogel** [comment]
Please post the output from the following:
```
>python3
>>> import h5py
>>> h5py.__version__
```

**Comment by ye-luo** [comment]
Got '3.6.0'

**Comment by ye-luo** [comment]
I fixed the false negative issue https://github.com/QMCPACK/qmcpack/pull/4998 and exposed the failure on multiple CI nodes.

**Comment by ye-luo** [comment]
Good news is that  #4991 failed for unrelated reasons.

**Comment by ye-luo** [comment]
All the failures in the CI runs of https://github.com/QMCPACK/qmcpack/pull/4998 use ubuntu 22.04
