### ISSUE TITLE
pw2qmcpack converter (5.1) does not overwrite a wave function file

### ISSUE THREAD

**Issue by kylanpaa** [QMCPACK/qmcpack#501]
The pw2qmcpack converter version 5.1 does not seem to overwrite/update a pwscf.pwscf.h5 file if one already exists. Do you know what is the behaviour in the newer versions?

**Comment by ye-luo** [comment]
I don't think it changes in newer versions. I usually dump the h5 into outdir and then move it up to the current directory for QMC. outdir may be very large and you can delete it as long as you don't need to restart your DFT.

**Comment by prckent** [comment]
It was not changed intentionally in the newer version (5.2). It is intended as a safety feature.

**Comment by jtkrogel** [comment]
Perhaps the correct behavior is to detect if an h5 file is already present and then abort if that is the case.  

The current situation was brought about by copying an old directory to have starting inputs for a different/new run (probably not rare to try this), changing the scf inputs, and then running pw2qmcpack with the intent of obtaining an h5 file corresponding to the current scf run.  IMO this situation should generate an abort rather than silently passing over the fact that a new h5 file was not created.

**Comment by kylanpaa** [comment]
OK. I ended up having a small problem when doing another nscf (in a separate directory) by modifying the nexus script I had used before. Since I had done the first nscf and pw2qmcpack in the same directory as the scf, the wave function file was also automatically rsynced to the new nscf directory. Thus, despite the new nscf run was good and pw2qmcpack reported on being successful (JOB DONE), the wave function file had not been updated. The pw2qmcpack output file in this case is otherwise similar, but is lacking the line "esh5 create pwscf_output/pwscf.pwscf.h5". Luckily I was doing tests using the real valued code, which is why qmcpack didn't run, since the older wave functions were wrong for this case (i.e. complex). So, maybe a good thing would be to add --exclude=pwscf.pwscf.h5 in nexus when doing the rsync (using appropriate prefix for the file).

**Comment by jtkrogel** [comment]
Yes, this would prevent users from making this workflow mistake when using Nexus (should be done), but it won't help the command-line workflow.

**Comment by prckent** [comment]
I think Nexus needs the update here.

If we are going to update the converter, we should make a 6.2 HDF version first.

**Comment by jtkrogel** [comment]
I will update Nexus.  Fine with behavior change of pw2qmcpack being deferred to QE 6.2.
