### ISSUE TITLE
Question on GPU support

### ISSUE THREAD

**Issue by vvp-nsk** [QMCPACK/qmcpack#5051]
Hej!

Does AFQMC implementation in QMCPACK support PHMSD trial WF on NVIDIA/CUDA GPU? 

Thank you in advance!

With best regards, 
Victor

**Comment by prckent** [comment]
Victor - Sorry for the delay. I was hoping one of the AFQMC authors would respond. While https://doi.org/10.1021/acs.jctc.0c00262 has single determinant results, a browse of the source code does look promising for MSD. e.g. The phmsd tests know about GPU memory allocation. Unfortunately I don't know the status for research usability or overall level of optimization -- given the delay I suspect you have probably already tried. You might look at ipie, which definitely does have what you need https://arxiv.org/pdf/2406.16238 .

**Comment by vvp-nsk** [comment]
Hej!

Now is a Midsummer season holidays, IMHO :) 

The IPIE package is fantastic, and it is in use, of course. Being written in Python, IPIE does support NVIDIA GPU through Numba. However, it does not support AMD GPU(s) such as MI250X. If I understand correctly, QMCPACK does support AMD GPU via CUDA2HIP. We will try to compile QMCPACK with AMD GPUs support and see how it works and performs. 

Thank you for your response! The ticket can be closed. 

With best regards, 
Victor

**Comment by linusjoonho** [comment]
Hello, @prckent sent me this thread. We looked into running ipie on older AMD GPUs, but I am unsure if ipie can run on MI250X by fiddling with cupy and numba. Sounds like a good Github issue to create for ipie-

**Comment by fdmalone** [comment]
QMCPACK does not support GPU accelerated MSD trials. The AMD support (if any) is for single determinant. Adding AMD support for ipie would be reliant on cupy ([experimental apparently](https://docs.cupy.dev/en/v8.6.0/install_rocm.html)) and porting the cuda kernels over to use [rocm jit ](https://numba.pydata.org/numba-doc/latest/roc/kernels.html#workitem-positioning). The GPU-MSD support in ipie I believe wrote cuda kernels directly so porting that over should also not be too hard but requires work and is likely not as performant.

@prckent please @ me as I don't check the issues here but am happy to clear anything up!
