### ISSUE TITLE
LCAO hdf5 convert test issue

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#509]
https://cdash.qmcpack.org/CDash/testDetails.php?test=1127858&build=14612
Indicates that h5dump is not a reliable way to check results.
1, h5dump is not always available. It is not shipped with hdf5 library but with the hdf5 tools.
2, The output format and the output contents depend on the machine defaults.

**Comment by anbenali** [comment]
Any Ideas/suggestion about how to fix this?

**Comment by markdewing** [comment]
The return value from the os.system call to h5dump should be checked - if non-zero, issue a message.  This would at least make it easier to diagnose if h5dump is not present.

Would h5diff work to compare the hdf files?

If not,
  - if object ordering is an issue, the comparison could test individual objects or smaller groups
  - the text could be preprocessed in the test script before being compared (depending on the nature of the format differences)

The big hammer would be to write a program that reads the HDF file and outputs a text format.  That would solve both problems, but takes more up-front work.

**Comment by ye-luo** [comment]
I would prefer using h5diff for checking.

**Comment by ye-luo** [comment]
Completed by #640
