### ISSUE TITLE
LCAO HDF5 SoA test failings

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#511]
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-LiH_dimer_pp-vmc_hf_sdj_hdf5-1-16&date=2017-11-18

Indicates that there is a problem with either the code or the test setup.

Note that the non-SoA (==AoS, older code) tests are working on this machine, so the problem is distinct from #509

**Comment by ye-luo** [comment]
HDF5 support has not been ported to SoA LCAO builders yet. @anbenali will take care of it.

**Comment by ye-luo** [comment]
Resolved.
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-LiH_dimer_pp-vmc_hf_sdj_hdf5-1-16&date=2018-02-07
