### ISSUE TITLE
Building qmcpack on Frontier

### ISSUE THREAD

**Issue by kayahans** [QMCPACK/qmcpack#5131]
Using the current build script, all qmcpack executables in the frontier build script are produced successfully on a recent develop version. However, when running a job utilizing `gpu=Yes`, an error is produced as below: 

`/ccs/home/kayahan/SOFTWARE/frontier/qmcpack/latest/qmcpack/build_frontier_rocm600_offload_cuda2hip_cplx/bin/qmcpack_complex: /opt/cray/pe/gcc-libs/libstdc++.so.6: version GLIBCXX_3.4.32 not found (required by /ccs/home/kayahan/SOFTWARE/frontier/qmcpack/latest/qmcpack/build_frontier_rocm600_offload_cuda2hip_cplx/bin/qmcpack_complex)`

I believe this is due to using an out of date gcc compiler somewhere. Here are additional messages from the error file which suggest that the build recipe could be due for an update: 

```
amd/6.0.0:
   As of July 16, 2024, the 'amd' compiler modules do not load the ROCm
   toolchain (see https://docs.olcf.ornl.gov/software/software-news.html#frontier-system-software-update-july-16-2024).
   Please load the matching version of a rocm module to enable GPU
   programming.

```

**To Reproduce**
1. Last git commit: 9617b189209ce13b7b32b4c60c543a226344b50b
2. Using the build_olcf_frontier_ROCm.sh build script with no changes

**System:**
 - Frontier
 - modules loaded:

```
for module_name in PrgEnv-gnu PrgEnv-cray PrgEnv-amd PrgEnv-gnu-amd PrgEnv-cray-amd amd amd-mixed gcc gcc-mixed cce cce-mixed rocm
do
  if module is-loaded $module_name ; then module unload $module_name; fi
done

module load PrgEnv-amd amd/6.0.0
module unload darshan-runtime
unset HIP_PATH # it messed up clang as a HIP compiler.
module load craype/2.7.16 # hard-coded version. 2.7.19/20/21 cause CC segfault.
module unload cray-libsci
module load cmake/3.22.2
module load cray-fftw
module load openblas/0.3.17-omp
module load cray-hdf5-parallel
module load rocm/6.0.0
export BOOST_ROOT=/ccs/proj/mat151/opt/boost/boost_1_81_0
```
 - other systems where this is reproducible [none]

**Additional context**

**Comment by ye-luo** [comment]
Please report the actual `module list` output.

**Comment by kayahans** [comment]
Thanks for quick reply. Yes, you are right, I had a gcc module loaded at that time. I unloaded it and the problem seems to be resolved. 

```
module list

Currently Loaded Modules:
  1) craype-x86-trento    3) craype-network-ofi       5) xpmem/2.6.2-2.5_2.40__gd067c3f.shasta   7) Core/24.00   9) hsi/default        11) DefApps               13) cmake/3.22.2        15) openblas/0.3.17-omp  17) craype/2.7.31     19) cray-mpich/8.1.27    21) PrgEnv-gnu/8.5.0  23) python/3.11.7-wdp6gxo
  2) libfabric/1.15.2.0   4) perftools-base/23.12.0   6) cray-pmi/6.1.13                         8) tmux/3.2a   10) lfs-wrapper/0.0.1  12) cray-python/3.9.13.1  14) cray-fftw/3.3.10.6  16) gcc-native/12.3      18) cray-dsmml/0.2.2  20) cray-libsci/23.12.5  22) gcc/11.2.0        24) cray-hdf5-parallel/1.12.2.7
```

Restarted job modules:
```
Currently Loaded Modules:
  1) craype-x86-trento                      12) cray-python/3.11.5
  2) libfabric/1.15.2.0                     13) craype/2.7.31
  3) craype-network-ofi                     14) cray-dsmml/0.2.2
  4) perftools-base/23.12.0                 15) PrgEnv-amd/8.5.0
  5) xpmem/2.6.2-2.5_2.40__gd067c3f.shasta  16) amd/6.0.0
  6) cray-pmi/6.1.13                        17) cray-mpich/8.1.28
  7) Core/24.00                             18) cmake/3.22.2
  8) tmux/3.2a                              19) cray-fftw/3.3.10.6
  9) hsi/default                            20) openblas/0.3.17-omp
 10) lfs-wrapper/0.0.1                      21) cray-hdf5-parallel/1.12.2.9
 11) DefApps
```

Another issue I noted is the craype module no longer seems to be loaded. The recipe has `module load craype/2.7.16 # hard-coded version. 2.7.19/20/21 cause CC segfault.`. However `module avail craype` gives:

```------------------------------------------------------------------------------------------------------------------------------------------------------------ /opt/cray/pe/lmod/modulefiles/core ------------------------------------------------------------------------------------------------------------------------------------------------------------
   craype/2.7.19    craype/2.7.20    craype/2.7.21    craype/2.7.23    craype/2.7.31 (L,D)
```

2.7.16 does not seem to be in the list any more. Despite this, the code has compiled and seems to be running.

**Comment by prckent** [comment]
Please confirm you can run after 5136 is in.

**Comment by kayahans** [comment]
I could run this today, since frontier was down yesterday. I confirm that the new compiler is working.
