### ISSUE TITLE
BsplineFunctor rcut defaults to Rws instead of Rins

### ISSUE THREAD

**Issue by Paul-St-Young** [QMCPACK/qmcpack#514]
Both Jastrow and backflow use the `BsplineFunctor` class to represent their respective short-range correlation functions. However, the default cutoff radius `rcut` is `Rws=min(|a|/2,|b|/2,|c|/2)`, where `a,b,c` are the lattice vectors. This default may create artificial correlation by allowing particles to see their own periodic images in a non-cubic cell having `Rins<Rws`, where `Rins=0.5*volume/max(face area)` is the radius of the inscribed sphere inside the simulation cell.

Fortunately, the Jastrow is barely (if at all) affected  by the aforementioned artificial correlation, presumably because it dies off so quickly with distance that the artificial correlation is not noticeable. However, this artificial correlation can devastate backflow, making the wavefunction unrealistically sensitive to particle positions. In the following figures I plotted the laplacian values for 72 electrons as a function of the electron's index. I got the orange squares by using QMCPACK's default `rcut=Rws` and the blue circles by reducing `rcut` below `Rins`. For my structure, `Rws=4.388`, `Rins=3.634`. I used `rcut=3.6` for the blue circles. (I have attached the output)

I think `rcut` should default to `Rins`. This new default would also bring the `BsplineFunctor` in-line with other periodic classes. A close inspection of QMCPACK output (attached) reveals that the long-range breakup parameter `rc` defaults `Rins`; Distance table `Rmax` defaults to `Rins`; Coulomb PBCAB `Rcut` defaults to `Rins`.

Is there a reason why `BsplineFunctor`'s `rcut` defaults to `Rws` instead of `Rins`?

![jas_lap](https://user-images.githubusercontent.com/8060441/33087428-2e9b5c58-ceb0-11e7-81cf-826d1cd6cba3.png)
![bf_lap](https://user-images.githubusercontent.com/8060441/33087437-357657ee-ceb0-11e7-8ded-eda57a63528c.png)

[default.txt](https://github.com/QMCPACK/qmcpack/files/1492432/default.txt)

**Comment by prckent** [comment]
I agree that the default should be Rins. I do not know the history. Unless someone comments quickly with a justification for the current situation, I suggest we change it.

**Comment by ye-luo** [comment]
Rws is the Wigner-Seitz radius. By construction, there is no artificial correlation even when Rws>Rins.
I know the routine computing Rws is not fully safe since it only checks the nearest neighbour cells. It may fail when you have a structure very very far from cubic.

What is the difference between the first and second plots?

**Comment by Paul-St-Young** [comment]
Also, why is there no artificial correlation when Rws>Rins?

**Comment by ye-luo** [comment]
Wigner-Seitz cell construction guarantees it.

**Comment by Paul-St-Young** [comment]
I am sorry. I still do not see why.

Consider a rectangular box in 3D where the base is a square with side length `a` and the height `c << a`. A particle at the origin will have a periodic image `c` away from it above and below. `Rws=c/2` and we are OK. Now if we sheer the box by more than 60 degrees along the x direction while keeping the height at `c`, then `Rws>c` and the image is within reach.

**Comment by Paul-St-Young** [comment]
Oh wait, that was wrong. The image also moves. OK I agree that one-body properties should be fine. Perhaps correlations will be messed up when `Rws>Rins`?

**Comment by jngkim** [comment]
It is because of the chain rule and quasi-particle vs real particles.

**Comment by Paul-St-Young** [comment]
@jngkim could you elaborate?

**Comment by Paul-St-Young** [comment]
The following example may be a bit extreme. If I sheer the box enough, then an ion at the origin can see two copies of the same electron (bold crosses). This is because `Rws` reaches outside the simulation cell. `Rins` does not have this behavior.

I am not sure if this is necessarily bad, but I am worried about the consistency between wavefunction  and interaction. (i.e. CoulombPBC uses `Rins`). 

![sheer_small](https://user-images.githubusercontent.com/8060441/33095454-6031b6fe-cec9-11e7-8481-0f1b4ba896d2.png)
![sheer_large](https://user-images.githubusercontent.com/8060441/33095459-636388c0-cec9-11e7-90d7-fde90c5b7249.png)

**Comment by ye-luo** [comment]
The upper panel: There is no overlap the two parts out of the box. No "same electrons"
The lower panel: Your Rws is wrong. Rws is the minimal picked out of 8 corners (2D, x,y = -1,0,1).

**Comment by prckent** [comment]
Suggestion: Why don't we make the default cutoff for *everything* the Wigner Seitz radius? This would certainly simplify things. And it is only a default: larger values can be used where physical.

**Comment by Paul-St-Young** [comment]
@prckent did you mean radius of the inscribed sphere (`Rins`) or Wigner-Seitz radius (`Rws`)?

`Rins <= Rws`

**Comment by Paul-St-Young** [comment]
@ye-luo yes you are correct. I misunderstood the definition of `Rws`. However, my point about consistency remains.

I would also like to understand why `Rws>Rins` hurts backflow so much.

**Comment by prckent** [comment]
Ignore my comment above - got things backwards.

**Comment by jngkim** [comment]
They are unrelated: the tail in Coulomb is taken care by S(k) term. It is
the point of optimized breakup method.

**Comment by jngkim** [comment]
Sorry, I digress.

Maybe it is the space wrap problem due to gravitational field. Joking but
not joking at the same time.

**Comment by ye-luo** [comment]
@Paul-St-Young my knowledge on BF is very limited. It is not clear to me if the quasi-particles still live in the same box as the real particles.

**Comment by Paul-St-Young** [comment]
Oh wait, my backflow wavefunction uses splined single particle orbitals. I believe these orbitals are defined only in the simulation cell. How would the orbital spline functions react if I requested a point outside the simulation cell?

**Comment by ye-luo** [comment]
For a periodic system, we don't restrict the moving of electrons out of the box and the SPOs are well defined all over the space not just inside the box.

**Comment by Paul-St-Young** [comment]
Oh yes, I remember now. The derivative mapping from the simulation cell to all space is handled by the owner of SPOSet, not the SPOSet itself. In this case the owner of the SPOSet is `DiracDeterminantWithBackflow`, which we know from #442 cannot map derivatives correctly from the unit cell to the super cell. 

@ye-luo are there different codes for derivative mapping from unit->super v.s. super->all space?

**Comment by ye-luo** [comment]
Orbital v/g/l are mapped directly from unit to all space by applying a phase computed by dot(r,k) where r is all over the space, k is determined by unit->super mapping.
