### ISSUE TITLE
R2R GPU offload implementation needed

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#5148]
**Is your feature request related to a problem? Please describe.**

There is currently no GPU offload implementation for the R2R (real to real) coefficients case. The code instead falls back to host CPU evaluation. Some user science runs need this GPU capability.

**Describe the solution you'd like**
Implement R2R GPU offload.

**Describe alternatives you've considered**
Running on the CPU incurs a large performance penalty; GPU runs will be much faster and more efficient.

**Additional context**

The NiO 4 atom performance test uses the CPU fallback code path.
```
We will read 0 distinct complex-valued orbitals from h5.
    Using real valued spline SPOs with real single precision storage (R2R).
OpenMP offload has not been implemented to support real valued spline SPOs with real storage!
    Running on CPU.
BandInfoGroup::selectBands bigspace has 29 distinct orbitals 
BandInfoGroup::selectBands using distinct orbitals [0,24)
```

**Comment by ye-luo** [comment]
Completed by https://github.com/QMCPACK/qmcpack/pull/5198
