### ISSUE TITLE
T-move evaluation assertion errors (target < wgt_t failed)

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#5175]
**Describe the bug**

Hopefully a tolerance issue in v1v3 Tmove evaluation

https://cdash.qmcpack.org/tests/4312438
https://cdash.qmcpack.org/tests/4312436

qmcpack_complex: src/QMCHamiltonians/NonLocalTOperator.cpp:100: const qmcplusplus::NonLocalData* qmcplusplus::NonLocalTOperator::selectMove(RealType, const std::vector<qmcplusplus::NonLocalData>&): Assertion `target < wgt_t' failed.

qmcpack_complex: src/QMCHamiltonians/NonLocalTOperator.cpp:100: const qmcplusplus::NonLocalData* qmcplusplus::NonLocalTOperator::selectMove(RealType, const std::vector<qmcplusplus::NonLocalData>&): Assertion `target < wgt_t' failed.

**To Reproduce**

Nightly tests, per cdash

**Expected behavior**

Passes

**System:**

Standard nightly test configurations, GCC14.

*Additional context**

**Comment by ye-luo** [comment]
I reproduced the issue and figured out the details. We always use double precision RNG. When the value is very close to 1.0, down casting to float makes it 1.0f and breaks the assertion. I will put up a fix but there is nothing to worry and there is no perfect fix due to the nature of computers.
