### ISSUE TITLE
WFtester grad-lap check script issue

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#518]
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-bccH_2x2x2_ae-grad-lap-1-1-check&date=2017-11-24
SoA fails can be ignore but some failures in the AoS are due to script issue. For example, Intel2017-Complex-Release.

**Comment by Paul-St-Young** [comment]
Ah, I see. I need to parse complex numbers of the form (a,b). Will commit a fix ASAP

**Comment by ye-luo** [comment]
resolved.
