### ISSUE TITLE
ERROR To developer: User is requesting for orbitals in an invalid spin group 0.

### ISSUE THREAD

**Issue by aldzubak** [QMCPACK/qmcpack#525]
No error with previous versions of qmcpack. 
[optJ2.in.xml.txt](https://github.com/QMCPACK/qmcpack/files/1510298/optJ2.in.xml.txt)

TOKEN=4 OccupyBands /home/iad/apps/qmcpack_develop_171127/qmcpack-develop/src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp 798
ERROR To developer: User is requesting for orbitals in an invalid spin group 0. Current h5 file only contains spin groups [0..-1].
ERROR To user: Orbital H5 file contains no spin down data and is appropriate only for spin unpolarized calculations. If this is your intent, please replace 'spindataset=1' with 'spindataset=0' in the input file.

**Comment by prckent** [comment]
Thanks for the report. Which version are you running?

**Comment by ye-luo** [comment]
"ERROR To developer" is a message technically meaningful for develops.
"ERROR To user" explains the issue to users.
We are adding more warning and error message to prevent misuse.

Based on this info, QMCPACK complains that your h5 file doesn't contain orbitals for spin-down electrons. Please examine your DFT calculation whether nspin=2 is set in QE to enable spin polarized calculation. If you did have a polarized calculation, please report `h5ls ../scf/pwscf_output/pwscf.pwscf.h5/electrons/kpoint_0` output.

**Comment by aldzubak** [comment]
QMCPACK version 3.2.0 - 2017-09-21

Yes nspin=2 in QE 

[iad@b22l01 err_optJ2]$ h5ls ../scf/pwscf_output/pwscf.pwscf.h5/electrons/kpoint_0
gvectors                 Dataset {494027, 3}
number_of_gvectors       Dataset {1}
numsym                   Dataset {1}
reduced_k                Dataset {3}
spin_0                   Group
spin_1                   Group
symgroup                 Dataset {1}
weight                   Dataset {1}

**Comment by ye-luo** [comment]
It seems that orbitals exist in h5. Could you provide the h5 such that I can investigate the issue?

**Comment by aldzubak** [comment]
Thanks
[pwscf.pwscf.h5.zip](https://github.com/QMCPACK/qmcpack/files/1510775/pwscf.pwscf.h5.zip)

**Comment by ye-luo** [comment]
gvectors takes 494027*3*8byte(double precision) = 11.3 MB.
Your h5 is only 13MB.
`$h5ls pwscf.pwscf.h5/electrons/kpoint_0/spin_0/state_0` outputs nothing.
Your h5 is corrupted and doesn't contain any orbitals.
Please check if you pw2qmcpack completes properly.

**Comment by ye-luo** [comment]
Your optimization blocks are not optimal. Please follow the OneShiftOnly section in the up-to-date manual. For the moment, OneShiftOnly in MinMethod is case sensitive.

**Comment by ye-luo** [comment]
@aldzubak did you solve the problem? Can we close this issue?

**Comment by aldzubak** [comment]
Problem resolved. And thanks, have changed my opt blocks.
