### ISSUE TITLE
Possible bug using glibc 2.23 and libmvec

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#526]
As discussed in #375 cmake guards against proven buggy combinations of libraries should be added. The bugs should also be cleanly reproduced and a tester made if practical.

**Comment by ye-luo** [comment]
Please add this info in the release note under known issues.
GNU compiler + glibc 2.23 builds will crash due to the bug in the libmvec of glibc.
glibc version can be verified by `ldd --version`

**Comment by prckent** [comment]
Is it possible to catch this bug with a unit test? Do we have a reproducer / know which call is bad?

**Comment by correaa** [comment]
I fall into this case when using clang++-11 (11.0.0-2-ubuntu20.04.1). Is there a workaround? (e.g. by adding a flag to `cmake` or disable a compiler optimization)

```
$ OMPI_CXX=clang++-11 cmake .. -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ -DBUILD_PPCONVERT=1
...
-- Compiler: GNU
CMake Error at CMake/GNUCompilers.cmake:94 (MESSAGE):
  Your system and GNU compiler are using glibc 2.22 or 2.23 which contains a
  buggy libmvec.  This results in crashes.  Workaround needed.  Alternatively
  upgrade or use another compiler.
Call Stack (most recent call first):
  CMakeLists.txt:384 (INCLUDE)
```
