### ISSUE TITLE
Assess input files created by revised converter

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#528]
This is a highly visible change and likely to be propagated to the QE / pwscf converter.

**Comment by prckent** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing Trello GitHub integration](https://trello.com/c/SJgNzCOZ/3-testing-trello-github-integration)

**Comment by anbenali** [comment]
I will generate 4 tests (from existing) from converter to full run with AE, PP, AE-HDF5, PP-HDF5.

**Comment by prckent** [comment]
Helpful. Note that the filen

**Comment by prckent** [comment]
Closed by #583
