### ISSUE TITLE
restrict types for accumulators and iszero()

### ISSUE THREAD

**Issue by grahamlopez** [QMCPACK/qmcpack#540]
Newer versions of glibc provide an external `iszero()`, which causes the estimators unit test to (correctly) fail on integers. This test was previously passing because the internal `iszero()` at `src/config/stdlib/limits.h:19:inline bool iszero(T a)` happily accepts integers, but doesn't do the right thing with them.

Proposed solution is to restrict the templates on the accumulators and the internal `iszero()` to only accept float types, to match the behavior of glibc (see [the glibc manual](https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html#index-iszero))

A tiny detail before I submit a patch: do we prefer to use `enable_if` or SFINAE to restrict the template types? The only preference I can think of is that `enable_if` with give compile-time errors that will likely be easier to understand than the link-time SFINAE errors.

**Comment by ye-luo** [comment]
Is this related to issue #429 ?

**Comment by grahamlopez** [comment]
No, I think the checking is doing the right thing. In my situation, CMake correctly sees that glibc's `iszero()` is available, and that's what gets called. The problem is that the estimator unit test for the estimators is written to accommodate `iszero()` at `src/config/stdlib/limits.h:19` which does the wrong thing when passed an integer. This unit test fails when using glibc's `iszero()`.

Since glibc's `iszero()` implementation doesn't even support integers, the proposed fix is to disallow integers in our `iszero()` and accumulators, and to disable the integer version of the estimators unit test.

**Comment by ye-luo** [comment]
@markdewing Can we just remove `accumulator basic int` in the unit test? I don't think the main code uses int as the template type of accumulator.

**Comment by markdewing** [comment]
The accumulator basic int test should be removed.  
It would be nice to have, but not essential, to add the type restrictions on the accumulator and is_zero.  Mostly to avoid any surprises in the future if anyone does try to use them with an int type.

**Comment by ye-luo** [comment]
OK. Since the glibc has been engaged for iszero. The removal must be conducted before v3.3 release.

**Comment by grahamlopez** [comment]
resolved via #545
