### ISSUE TITLE
What does the vacuum option do, and does anyone use it?

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#542]
The vacuum setting is used in Particle/ParticleSet.BC.cpp, in createSK and it modifies the lattice (or at least a copy of the lattice) for the slab and wire geometries. 

The question comes up because createSK prints another copy of the lattice information to the output.  It seems like this should only be printed if the boundary conditions and vacuum setting change the lattice.  And I'm wondering what the significance of this is to the user and their calculation?

And as mentioned in #146, the --vacuum option should be moved to the XML input file.

**Comment by ye-luo** [comment]
I think we only need to print the lattice when --vacumm != 0 case.

**Comment by jngkim** [comment]
It is a way to expand the vacuum layer (z) even though PW calculation is
done with a smaller vacuum.

It is better to do the quasi-2d correctly.

**Comment by prckent** [comment]
This is potentially useful functionality for slabs but untested and little used. I think we reexamine if/when we have users of it.

**Comment by jngkim** [comment]
Correct. Not for general use.

**Comment by prckent** [comment]
So it is useful and used today but untested.

@anbenali Could you arrange for someone to create an issue proposing what the vacuum option should look like inside the .xml to aid planning removing this option.

 (@markdewing ) To test this I think we would need a unit test to checking particle positions and periodic boundary conditions?

**Comment by prckent** [comment]
I think this issue has now been adequately addressed: option relocated, docs improved, test added.
