### ISSUE TITLE
Purpose and future of SQD and AtomicHF?

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#561]
What is purpose of the code in the SQD and AtomicHF directories?
Are we going to keep these codes?  If so, we should build and test them regularly.

**Comment by jngkim** [comment]
You can get rid of them.

**Comment by jtkrogel** [comment]
These are numerical Hartree-Fock codes for spherical potentials (e.g. atoms or spherical quantum dots) that can produce orbitals for QMCPACK.  I was going to add a test for this code path soon, but perhaps more discussion is warranted.

**Comment by jtkrogel** [comment]
Votes for keep or remove?  

I am in between myself.  On the plus side this is actually a feature from early in QMCPACK's history that still works.  On the minus side, I don't see it as being terribly useful except in a tutorial setting unless one wants to check the veracity of HF calculations of atoms or unless spherical quantum dots become of interest.

Related to #807.  Suggest we make a decision one way or another and proceed.

**Comment by jtkrogel** [comment]
Having thought about it more, I'm switching to a down vote.

**Comment by jtkrogel** [comment]
"Resolved" by PRs #833 and #806.
