### ISSUE TITLE
Hybrid representation needed on GPU

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#564]
This formerly working code path was broken by the SoA changes *even when the AoS-GPU code is built*. A HybridSplineR2RSoAAdoptor is wrongly invoked. Due to the accuracy improvements with hybrid, this needs to work "soon".

@ye-luo Is this working in your branch with all the updates on the hybrid conversion?

**Comment by ye-luo** [comment]
"This formerly working code path" do we have an input file?
Invoking HybridSplineR2RSoAAdoptor is the correct bahaviour since the hybredrep="yes" is only for the new implementation. The old GPU hybrid is accessed based on h5 not input file if I remember correctly.

**Comment by prckent** [comment]
I think we have the BN inputs archived, the system for which the APW was developed and coded (@jtkrogel  ?). This was last checked a long time ago, so there could be other breakages besides SoA.

**Comment by ye-luo** [comment]
The old implementation on GPU and new implementation on CPU with SoA are largely different.
I would say connect everything GPU to SoA and get ride of AoS.

**Comment by lshulen** [comment]
In trying to get a working example of the old code, you will need the hdf files.  BN is actually not a great choice because it exercised a different route than we will be wanting to enable (that is it started from exciting output, not espresso).  I have for instance a number of h5 files laying around for an isolated Pt atom with various radii and numbers of l channels.  They are fairly small (~20MB) and I could provide sample input if desired.

**Comment by prckent** [comment]
The old files might only be needed to see how the GPU version worked/was called at one point and for debugging. The new code should run on GPU with the same inputs as the current test.

I was unaware until yesterday that the new hybrid rep implementation in the SoA code was anything more than an update for SoA, plus minor mods for smoothing at the boundary between the two basis sets. It is critical that the CUDA version works. "Hybrid rep" team has this responsibility.

**Comment by lshulen** [comment]
Ye can clarify, but I think you are correct except for one important piece.  Ye did all of the hard work to move the (very painful) conversion from wfconvert into qmcpack proper and to parallelize it well.  The reason the old input file is different (in fact there are no clues in the input file that hybrid is used at all) is that it relied entirely on the choices put into the h5 file to specify the hybrid.

The other minor change from an algorithmic perspective was that the old GPU code had a some tricks regarding how to efficiently evaluate the nonlocal pseudopotential when hybrid wavefunctions were present that have not been carried over.  I think this is still under consideration, but the current SoA code is so efficient that this has not proven necessary.

**Comment by ye-luo** [comment]
R2R, C2R, C2C means Real/complex spline to Real/Complex orbital.
The old implementation has R2R and C2R but no C2C.
The new implementation has all the three.

The underlining arithmetic is different.
The old implementation uses real Ylm in R2R and complex Ylm in C2R case.
The new implementation uses real Ylm in all the three cases for better efficiency. So its splines can not be used in the old implementation.

The old implementation expand the orbital in very near core region (<0.1 a.u.) with polynomials.
The new implementation only uses 1D splines in AO region.

@lshulen The optimization for NLPP is undergoing however requiring engaging the vritual particle set (VP) first.

**Comment by prckent** [comment]
These missing CUDA capabilities will never be implemented by the main developers, so I am closing the issue. Anyone needing these is welcome to make the updates themselves. The plan is to delete the legacy CUDA implementation, delete the legacy AoS CPU implementation, and concentrate on adding GPU capabilities to the "SoA" CPU code in a fully compatible manner. Moving forward QMCPACK will not have internal forks and sparse feature coverage such as this.
