### ISSUE TITLE
Complex CUDA build fails with CUDA 9 due to thrust uninitialized missing file

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#565]
With CUDA 9.1, determinant_update.cu will fail to build due to a missing file:
```
#include <thrust/system/cuda/detail/bulk/uninitialized.hpp>
```

I tried a quick replacement with thrust/device_vector.h, but this results in a series of declaration errors later on.

**Comment by prckent** [comment]
I have downgraded the CUDA version used for the nightlies to 8.0 until this is solved

**Comment by jefflarkin** [comment]
I've reached out to the thrust team for more information.

**Comment by jefflarkin** [comment]
@prckent That header was definitely removed from the version of thrust that shipped with CUDA9. You can restore the functionality, however, with https://github.com/jaredhoberock/uninitialized.

**Comment by prckent** [comment]
Thanks. It looks like we could incorporate these files directly and use these implementations with all versions of CUDA. Agree?

**Comment by jefflarkin** [comment]
Yes. I checked with the author ahead of posting this comment and got him to put the license file in place for you. It’s BSD3, so you should be in the clear to incorporate it into your repo.
