### ISSUE TITLE
Integration test: helium Hamiltonian

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#572]
Resurrect old test using helium pair potentials

**Comment by ye-luo** [comment]
Can we also have a test for the harmonic oscillator?

**Comment by jtkrogel** [comment]
An example of the Helium hamiltonian exists from 2008 (128 atom, HFDHE2 potential, J2 modMcMillan+shiftedGaussian) and it was included in the original test set at the time.  Versions of QMCPACK from 2010-2014 (SVN 4648-6259) segfault at the beginning of VMC in TrialWaveFunction::registerData(ParticleSet,PooledData).

Reference data for this system does exist (short VMC, RMC, RMC):
HE4.n128.equilibrium  series 1  LocalEnergy           =  -0.002117 +/- 0.000043 
HE4.n128.equilibrium  series 2  LocalEnergy           =  -0.002781 +/- 0.000041 
HE4.n128.equilibrium  series 3  LocalEnergy           =  -0.002879 +/- 0.000016 

We can include this as a developer test (not run with regular tests) and revive it, or exclude it to lighten the code base.

**Comment by jtkrogel** [comment]
Do we want to keep Helium or not?  I don't know what units the above reference data are in (presumably Kelvin) or if they are at all sensible.  

Given the uncertainties, the cost to resurrect, and the added maintenance burder, I would probably prefer to let it go.

**Comment by jtkrogel** [comment]
Helium has been removed (PR #835).
