### ISSUE TITLE
Integration test: spin-polarized system

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#576]

**Comment by ye-luo** [comment]
In one QE test, LiH is spin polarized.

**Comment by jtkrogel** [comment]
OK, will take a look.

**Comment by jtkrogel** [comment]
@ye-luo I see the "fake_nspin2" directory associated with the LiH tests (LiH_solid_1x1x1_pp) and the input files therein do refer to a second spin channel (spindataset="1"), but these input files are not used in any test that I can see and no spin down channel exists in any of the visible LiH*h5 files.

Is this correct?

**Comment by ye-luo** [comment]
@jtkrogel tests are under tests/pw2qmcpack. H5 is generated on the fly.

**Comment by jtkrogel** [comment]
@ye-luo Thanks, I see it now.

**Comment by jtkrogel** [comment]
Closing due to existing test.
