### ISSUE TITLE
Tests copy files, thereby using disk space. Symlinks more economical and would help consistency

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#58]
Currently when a build is created, the files related to tests are copied.
It could be better that just create the folder and make softlinks of the files instead of copy the whole folder.
This way not only save space (h5 files) but also make sure the tests in your build folder are consistent with the repo.

**Comment by atillack** [comment]
I concur - that would be very helpful to me as well.

**Comment by markdewing** [comment]
One option is to use 'cp -as' to copy the test directories.  This makes a copy of the directories and directory structure, but symlinks all the files.
The question is: Should all the files use symlinks, or just large ones (such as the *.h5 files)?

There could be a problem if any files in the test input directory are overwritten during the test run.  If using   a symlink, the original test file would be overwritten.  I don't think there are any test files that fall into this category, but I'm asking to make sure.

Another potential issue is systems with non-uniform file system visibility (eg. Titan - home directories are visible to login nodes, but not compute nodes during job runs).  I suppose this will just require care on the user's part.  Related, should copy vs. symlink be a configure time option?  Or switch it to use symlinks?

**Comment by prckent** [comment]
The tests don't overwrite any files at present.  We could make this a requirement.

I agree that a force copy could well be needed. This requires a setting in cmake configure and a tweak to the ctest script so that the setting is passed through.

**Comment by ye-luo** [comment]
I actually changed my option on the consistency because of using git for a while.
I think it is better only softlinking h5.
When I work on multiple branches.
I create build_branchA/B_versionA/B.
I'd like to have decoupled input files because I need to debug locally with modified input files.

**Comment by prckent** [comment]
To softlink only the large files, e.g. hdf5, we need a way of identifying/handling them in the cmake/ctest setup.

**Comment by prckent** [comment]
Closed by #112
