### ISSUE TITLE
Total energy disagreement between CPU and GPU codes

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#614]
I recently ran longish test runs with the 32 atom NiO performance test system (two body Jastrow) comparing version 3.1.1 AoS to develop AoS, SoA, and GPU (AoS) codes.  While all CPU runs agreed for NiO, a difference was apparent for the GPU runs:
```
                         E_VMC           E_DMC
NiO/cpu_311_aos_real   -2966.749(2)    -2970.502(2)
NiO/cpu_dev_aos_real   -2966.747(2)    -2970.504(3)
NiO/cpu_dev_soa_real   -2966.750(2)    -2970.507(3)
NiO/gpu_dev_aos_real   -2966.7428(6)     ------      
                                                   
NiO/cpu_311_aos_comp   -2966.746(2)    -2970.486(3)
NiO/cpu_dev_aos_comp   -2966.747(2)      ------      
NiO/cpu_dev_soa_comp   -2966.746(2)    -2970.486(3)
NiO/gpu_dev_aos_comp   -2966.7422(6)   -2970.481(1)
```

For reference the DMC data for GPU real is missing due to a bad alloc thrown early in the DMC portion of the run (a separate known issue), while for CPU complex the missing data is due to a single node crashing on Titan.

Averaging over the CPU data, I get the following differences:
```
NiO/cpu_avg_real     vmc  -2966.750(1)
NiO/gpu_dev_aos_real vmc  -2966.7428(6)  7(1) mHa difference (7 sigma)
                                                   
NiO/cpu_avg_comp     vmc  -2966.747(1)   
NiO/gpu_dev_aos_comp vmc  -2966.7422(6)  5(1) mHa difference (5 sigma)

NiO/cpu_avg_comp     dmc  -2970.486(2)
NiO/gpu_dev_aos_comp dmc  -2970.481(1)   4(2) mHa difference (2 sigma)
```

The CPU/GPU energy difference is consistent in all cases, though for DMC it is not as significant possibly due to the larger error bars.

Input files for cpu and gpu runs are attached: [input_files.zip](https://github.com/QMCPACK/qmcpack/files/1598549/input_files.zip)

Each run was performed on 3000 nodes on Titan with 1 MPI task and 16 OpenMP threads per node.

**Comment by ye-luo** [comment]
@jtkrogel Please list the commit hash of the develop you use.

**Comment by jtkrogel** [comment]
The commit hash for "develop" is: 890a251837d5c2aee091131bcbafc4d34754b57c

**Comment by jtkrogel** [comment]
Here are VMC energy component differences between CPU and GPU averaged over all runs:
```
LocalEnergy       0.00521(82)  6.3 sigma
Kinetic           0.026(13)    2.0 sigma
LocalPotential   -0.021(13)    1.6 sigma
ElecElec          0.022(06)    3.7 sigma
LocalECP         -0.038(12)    3.2 sigma
NonLocalECP      -0.0043(84)   0.5 sigma
IonIon            0.000002
```

**Comment by prckent** [comment]
What precision was used for the CPU and GPU runs? If default, I wonder if we are studying the utility of single precision?

**Comment by jtkrogel** [comment]
According to QMCPACK input on determinantset: 
precision="single"

According to QMCPACK output:
CPU base/full precision: double/double
GPU base/full precision: single/double

**Comment by prckent** [comment]
I think it would be useful to run GPU VMC only with double precision and, in parallel, determinant only VMC runs in default mixed precision and double  precision.

**Comment by jtkrogel** [comment]
I now have results for GPU full precision (nomix) and CPU mixed precision (mixed) in addition to the default GPU mixed precision and CPU full precision results:

```
NiO/cpu_avg_real           vmc  -2966.750(1)
NiO/gpu_dev_aos_real       vmc  -2966.7428(6)  7(1) mHa difference (7 sigma)
NiO/gpu_dev_aos_real_nomix vmc  -2966.7442(7)  6(1) mHa difference (6 sigma)
NiO/cpu_dev_soa_real_mixed vmc  -2966.7480(8)  2(1) mHa difference (1.5 sigma)
                                                         
NiO/cpu_avg_comp           vmc  -2966.747(1)   
NiO/gpu_dev_aos_comp       vmc  -2966.7422(6)  5(1) mHa difference (5 sigma)
NiO/gpu_dev_aos_comp_nomix vmc  -2966.7441(6)  2(1) mHa difference (2 sigma)
NiO/cpu_dev_soa_comp_mixed vmc  -2966.7488(8) -2(1) mHa difference (2 sigma)

NiO/cpu_avg_real           dmc  -2970.504(2)
NiO/gpu_dev_aos_real_nomix dmc  -2970.501(1)   4(2) mHa difference (2 sigma)
NiO/cpu_dev_soa_real_mixed dmc  -2970.504(3)   0(3) mHa difference (0 sigma)
                          
NiO/cpu_avg_comp           dmc  -2970.486(2)
NiO/gpu_dev_aos_comp       dmc  -2970.481(1)   4(2) mHa difference (2 sigma)
NiO/gpu_dev_aos_comp_nomix dmc  -2970.477(1)   8(2) mHa difference (3.5 sigma)
NiO/cpu_dev_soa_comp_mixed dmc  -2970.486(3)   0(4) mHa difference (0 sigma)
```

The CPU VMC/DMC results with and without mixed precision agree with each other to within 0/2 sigma (respectively) and for the GPU the full vs. mixed precision also agree to within 2 sigma.  Differences between CPU and GPU runs reach 5-7 sigma.

This indicates the bug is largely CPU vs. GPU rather than mixed vs. full precision.

**Comment by ye-luo** [comment]
I ran the most recent develop with GPU
```
NiO/gpu_dev_aos_real    vmc   -2966.7462(8)
NiO/gpu_dev_aos_real    dmc   -2970.503(4)
```
VMC energy is a bit closer to the cpu_avg_real than yours.
DMC energy is within 1 sigma.
@jtkrogel I feel we need more statistics on the CPU reference.

**Comment by jtkrogel** [comment]
@ye-luo We have VMC results that deviate by 6 and 7 sigma and yours deviate by 3 sigma.  Why do we need smaller error bars if the results are statistically significant?

I agree that the case for an error in DMC is smaller, mostly due to the larger error bars there.  My preference would be to focus on the VMC fix and then follow up with a longer VMC+DMC run once we think it is solved.

Incidentally, what machine are you running on?

**Comment by ye-luo** [comment]
@jtkrogel If you take my VMC energy as the reference, all your CPU GPU values are not far. I would prefer to have a more accurate CPU VMC energy to compare with. cpu_avg_real needs a smaller error bar.

**Comment by prckent** [comment]
Can we check a smaller and cheaper NiO cell?

**Comment by jtkrogel** [comment]
If the problem surfaces there, that would be ideal.  The downside is that if we get agreement in a small cell, it may just indicate that the problem emerges at larger system size.

Still investing computing time in the smaller cell is probably a better one to do first, even if we have to return to the larger one to be sure.

**Comment by jtkrogel** [comment]
@ye-luo We can average all cpu results together and all gpu results together to get a single comparison with the smallest available error bar on the difference.  I suspect this will show significance too, but we should just calculate it and see.

**Comment by ye-luo** [comment]
@jtkrogel The CPU runs in your original post has 0.002 error and it is better to have them as small as your CPU mixed precision run.

**Comment by jtkrogel** [comment]
Note that the same k-point is used for real/complex runs so correct => cpu_real=cpu_comp=gpu_real=gpu_comp.

**Raw VMC data**
```
cpu_311_aos_real         -2966.749365 +/- 0.001855 
cpu_dev_aos_real         -2966.747275 +/- 0.001608 
cpu_dev_soa_real         -2966.750051 +/- 0.001918 
cpu_dev_soa_real_mixed   -2966.747968 +/- 0.000782 

cpu_311_aos_comp         -2966.746408 +/- 0.001637 
cpu_dev_aos_comp         -2966.746808 +/- 0.001644 
cpu_dev_soa_comp         -2966.746382 +/- 0.001843 
cpu_dev_soa_comp_mixed   -2966.748767 +/- 0.000863 

gpu_dev_aos_real         -2966.742784 +/- 0.000564 
gpu_dev_aos_real_nomix   -2966.744227 +/- 0.000660 
gpu_dev_aos_real_yeluo   -2966.746200 +/- 0.000800

gpu_dev_aos_comp         -2966.742232 +/- 0.000556 
gpu_dev_aos_comp2        -2966.742304 +/- 0.000563 
gpu_dev_aos_comp_nomix   -2966.744086 +/- 0.000581 
```

**Averages**
```
avg cpu real  -2966.748665 +/- 0.000803
avg cpu comp  -2966.747091 +/- 0.000772
avg cpu all   -2966.747878 +/- 0.000557

avg gpu real  -2966.744404 +/- 0.000394
avg gpu comp  -2966.742874 +/- 0.000327
avg gpu all   -2966.743639 +/- 0.000256
```

**Differences**
```
cpu   real-comp  -1.6(1.1) mHa  (1.5 sigma)
gpu   real-comp  -1.5(0.5) mHa  (3 sigma)

real  cpu-gpu    -4.3(0.9) mHa  (5 sigma)
comp  cpu-gpu    -4.2(0.8) mHa  (5 sigma)

all   cpu-gpu    -4.2(0.6) mHa  (7 sigma)
```

Data best supports that cpu real/comp are the same, gpu real/comp may be different, and cpu/gpu are almost certainly different.

**Comment by ye-luo** [comment]
@jtkrogel I updated the raw data including my complex run. I noticed that my GPU run doesn't agree with yours. Could you try the most recent code?

**Comment by jtkrogel** [comment]
Interesting.  Your gpu runs are much closer (-1.4(7) mHa real, -1.5(7) mHa complex) to the fully averaged cpu reference of -2966.7479(6) Ha.

Is there anything that could have changed (as a fix) in gpu VMC between Dec. 14 (my runs) and ~today (your runs)?  

My runs are built and run on Titan using the included build scripts.  What machine/architecture were your runs performed on?

**Comment by ye-luo** [comment]
Actually, I don't think there is any relevant fix. I'm doing usedrift=no. Were you using drift?
I'm running also on Titan with the build_script provided.
I also have a run using v3.3.0. It gives `-2966.746639 +/- 0.000636`

**Comment by ye-luo** [comment]
OK drift is not a problem. It gives `-2966.746515 +/- 0.000522`.

**Comment by prckent** [comment]
This is a really old issue. I think we consider it fixed and certainly other checks have been done since and passed. @ye-luo or @jtkrogel are welcome to reopen.
