### ISSUE TITLE
particleset and ecp naming bug

### ISSUE THREAD

**Issue by jptowns** [QMCPACK/qmcpack#619]
I have discovered a potential "bug" in how QMCPACK handles the ion particleset names and pseudopotential names.

Here is the essence of the bug. If I specify an ion particleset as below:
```
  <particleset name="i" size="2">
    <group name="Fe1">
      <parameter name="charge"        >    16 </parameter>
      <parameter name="valence"       >    16 </parameter>
      <parameter name="atomicnumber"  >    26 </parameter>
    </group>
    <group name="Fe2">
      <parameter name="charge"        >    16 </parameter>
      <parameter name="valence"       >    16 </parameter>
      <parameter name="atomicnumber"  >    26 </parameter>
    </group>
    <attrib name="position" datatype="posArray" condition="1">
      0.00   0.00   0.00
      0.50   0.50   0.50
    </attrib>
    <attrib name="ionid" datatype="stringArray">
      Fe  Fe
    </attrib>
  </particleset>

```
and then refer to that particleset incorrectly (notice the "Fe Fe" rather than "Fe1 Fe2" in the ionid stringarray)
Then, if I specify the pseudopotentials as below:
```
    <pairpot type="pseudo" name="PseudoPot" source="ion0" wavefunction="psi0" format="xml">
      <pseudo elementType="Fe" href="./Fe.opt.xml"/>
    </pairpot>

```

QMCPACK correctly points out that the ion species "Fe" cannot be found:
```
  ECPotential builder for pseudopotential 
ERROR   Ion species Fe is not found.
  ... ParticleSet::addTable Reuse Table #1 ion0_e
  ECPotential::Rmax 0.0000000000

```

However, rather than aborting, QMCPACK seems to replace the pseudopotential with a bare coulomb potential... And then happily carries out the calculation! I am not exactly sure what QMCPACK is doing, but based on the difference in the energy.pl report from a baseline calculation:
```
LocalEnergy           =          -230.279 +/-            0.028
Variance              =             66.45 +/-             0.61
LocalPotential        =           -427.47 +/-             0.16
Kinetic               =            197.20 +/-             0.18
ElecElec              =            52.285 +/-            0.100
IonIon                =     -186.32873833 +/-       0.00000000
LocalECP              =           -255.68 +/-             0.18
NonLocalECP           =           -37.755 +/-            0.089
BlockWeight           =    20224.00000000 +/-       0.00000000
BlockCPU              =            1.2606 +/-           0.0027
AcceptRatio           =           0.43849 +/-          0.00014
Efficiency            =         16043.676 +/-            0.000
```

 and a bugged calculation:
```
LocalEnergy           =          -247.171 +/-            0.046
Variance              =               511 +/-               14
LocalPotential        =           -444.76 +/-             0.20
Kinetic               =            197.59 +/-             0.16
ElecElec              =            52.574 +/-            0.093
IonIon                =     -186.32873833 +/-       0.00000000
LocalECP              =           -292.06 +/-             0.26
NonLocalECP           =           -18.953 +/-            0.038
BlockWeight           =    20224.00000000 +/-       0.00000000
BlockCPU              =            1.0506 +/-           0.0023
AcceptRatio           =           0.43838 +/-          0.00011
Efficiency            =         19249.212 +/-            0.000
```

It seems that the NonLocalECP, LocalPotential, and LocalECP are where the differences lie.

Naturally this gives rather absurd results (notice the energy of the bugged calculation is ~17 Ha lower than the baseline).

It seems to me that if I am a stupid monkey and screw up the input file by being inconsistent then QMCPACK should scream at me and "refuse to continue with this sick job!" (to borrow a phrase from VASP) rather then surreptitiously replacing a piece of my hamiltonian and merrily crunching along. 

I have attached a tarball with a minimal working example that illustrates the nature of this error.

[qmcpack-ecp-naming-bug-mwe1.zip](https://github.com/QMCPACK/qmcpack/files/1601400/qmcpack-ecp-naming-bug-mwe1.zip)

**Comment by prckent** [comment]
Definitely a missing abort here

**Comment by ye-luo** [comment]
The should have already been resolved. Which version of code are you using? Try develop.

**Comment by jptowns** [comment]
Oops, I knew I had forgot something important. It looks like the version I used was 3.2.0 Dated Nov 21, 2017.

Looks like using the 3.3.0 build as of Wed Dec 20 properly recognizes the issue and aborts. It even has the decency to say why!

Move along, nothing to see here.
