### ISSUE TITLE
short-c_no-hf_vmc tests have HDF5 failures

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#624]
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-c_no-hf_vmc-4-4&date=2018-01-04

Appears to be a multiple MPI / multiple threads problem. The tests with 1 MPI task and 16 threads are passing.

**Comment by anbenali** [comment]
Paul, Is this related to the molecular code? I could not find this test!

**Comment by prckent** [comment]
No. "NO" is numerical orbitals, not natural orbitals.

qmcpack/tests/molecules/C_NO_ae

**Comment by anbenali** [comment]
my bad.. my branch was behind...

**Comment by prckent** [comment]
This test shows a repeated failure in the nightlies (5 fails) followed by a pass when run in the weekend runs. This  indicates some unintentional difference in the test configuration, dependencies , build environment etc. between these cases that bypasses the bug. In theory there is no difference but in practice there is.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/13683814/38200167-4d199dde-3661-11e8-8bff-87ce85c40e53.png">

**Comment by jtkrogel** [comment]
This functionality was removed.
