### ISSUE TITLE
data race in nonblocking send/recv implementation

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#631]
I realized there is a data race bug in the nonblocking send/recv implementation.
When the same walker is sent to multiple ranks, encoding the number of sent copies in the message has a data race.
This will cause MPI hanging on the receiving side.
expect to get it fixed in about a week.

**Comment by ye-luo** [comment]
This is bug doesn't show up with the default maxCopy=2. Only when you use maxCopy>2, it causes a problem. In the case of maxCopy=2, you can only send 1 walker + 1copy to 1 node or  1 walker + 0 copy to 2 nodes. No data race.

**Comment by prckent** [comment]
Q. Relating to the previous as well as current implementation. Why is maxCopy not infinity, or at least a much larger value? (Say targetwalkers/no_mpi_tasks)  Would the improvement in load balancing not always win out over the reduced messaging/copying? We need to think about atomic runs as well as large solid state runs when setting default parameters...

**Comment by ye-luo** [comment]
maxCopy is per walker not per node. So on a node by default you can get maximum 2x walkers before the load balancing. I think it is mainly to maintain a stable population and avoid the ensemble being destroyed by bad walkers.

**Comment by prckent** [comment]
Just set to 2 if >2 requested for now. This area needs to be looked at sometime and sensibly studied/documented.
