### ISSUE TITLE
src/miniapps to be renamed

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#634]
The old miniapps directory is causing confusion with the actively maintained ECP miniapp effort (#633 ). It needs to be renamed. Any preferred names?

**Comment by ye-luo** [comment]
proxyapps?

**Comment by markdewing** [comment]
I don't think the name should have 'mini', 'app', or 'proxy' in it, to very clearly distinguish it from miniqmc.

There is the existing Sandbox directory, which contains a somewhat similar category of code -  testing or driving pieces or subsets of the whole QMCPACK code.

The unit tests call as small a piece of code as possible for regression testing purposes.

This code (in the directory formerly known as 'miniapps') operates at a higher level than the unit tests, and the purpose is different.  It is for explanation and display of a smaller model of the QMCPACK code.  As Ye pointed out elsewhere, it is also a place to try new ideas.

Maybe we could call it the "Test Chamber" (for fans of Portal)
Or call it "Stennis", for Stennis Space Center, where rocket engines get tested.

**Comment by prckent** [comment]
My preference would currently be to clean up Sandbox and move the miniapps there.
