### ISSUE TITLE
Refactor copies of expandYlm

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#636]
The code for expandYlm(H5) is copied in several places (#635)
 - MolecularOrbitals/AtomicBasisBuilder.h
 - lcao/AOBasisBuilder.h
 - MolecularOrbitals/GTOMolecularOrbitals.cpp (this file doesn't seem to be used, maybe it can be removed?)

Ideally, there could be a single copy (that might make the code too complicated, though).
As an alternative, the code that actually performs the ordering for each type should be extracted to a function (per ordering type), and only one copy of that function should exist.

It should have a unit test, and a reference (where would I go to find out or verify the Ylm ordering of Gaussian98 or Gamess, for example).

**Comment by ye-luo** [comment]
lcao/AOBasisBuilder.h will be the only one.

**Comment by jngkim** [comment]
As Ye said,
this is just a temporary solution and MolecularOrbitals should be removed
once SoA is fully implemented.

How they work is very different and names are intentionally mirrored from
the old version. Now is not the time to clean up the code.

**Comment by ye-luo** [comment]
I've changed the code to keep only one copy in SoA.

**Comment by ye-luo** [comment]
When AoS classes are removed, there will be only one copy in SoA. No need to keep this issue open at the moment.
