### ISSUE TITLE
LCAO test issues

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#641]
- [x] short-FeCO6_gms-vmc_b3lyp_noj, softlink to the BFD.xml are missing.
- [x] short-FeCO6_pyscf-vmc_b3lyp are too long, as well as _gms
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-FeCO6_pyscf-vmc_b3lyp_noj-1-16&date=2018-01-13
- [x] enable failing check for AoS pyscf tests
- [x] there is a bug in hdf5 file or converter.
https://cdash.qmcpack.org/CDash/testDetails.php?test=1430956&build=17119
 rid is not correct, should be "Li101"
This is caught by the added check after expandYlm.
```
h5ls -d LiH_dimer_ae_pyscf/LiH-pyscf.h5/basisset/atomicBasisSet0/basisGroup10/rid
l                        Dataset {1}
    Data:
        (0) 1
n                        Dataset {1}
    Data:
        (0) 10
rid                      Dataset {1}
    Data:
        (0) "Li10"
```
 - [x] In tests/converter/test_LiH_pyscf, remove LiH.h5 since is carries the previous problem. Replace it with a softlink when the previous one is fixed.
 - [ ] AB- Does not apply (using cartesian orbitals in the Gamess order- hence the specification) h5ls -d FeCO6.h5/basisset/atomicBasisSet0
```
expandYlm                Dataset {1}
    Data:
        (0) "Gamess"
```

**Comment by anbenali** [comment]
>> short-FeCO6_gms-vmc_b3lyp_noj, softlink to the BFD.xml are missing.

Fixed!! 

>>    there is a bug in hdf5 file or converter.
The bug was in the reference H5. I fixed it in the converter but forgot to generate a new H5. 

>>     In tests/converter/test_LiH_pyscf, remove LiH.h5 since is carries the previous problem. Replace it with a softlink when the previous one is fixed.

Done

>>     enable failing check for AoS pyscf tests

I do not understand this request. AoS pyscf is supported... 

>>    short-FeCO6_pyscf-vmc_b3lyp are too long, as well as _gms

Can you remind how long should the tests last? I can reduce more the number of blocks...

**Comment by ye-luo** [comment]
It is better to have short test <30 sec on oxygen so it is no more than 1min on other platforms.
If the statistics is too noisy, we probably need to replace this test with smaller ones.
For checking high angular momentum, unit tests are better choices.

**Comment by anbenali** [comment]
>>short-FeCO6_pyscf-vmc_b3lyp are too long, as well as _gms

@ye-luo  @prckent : 
If we reduce the number of blocks for this tests, the error bar will be so large even if we remove orbitals by mistake, we won't be able to catch an issue. as @ye-luo  says, the order of the orbitals according to the cartesian tensor should be put in a unit test to avoid this situation. For now the test takes 900s, and it should be driven to 30s. that is 30x less time. It is not enough for 50 warmup steps...

**Comment by prckent** [comment]
For now I suggest we relabel the too long tests as actual long tests and we have no equivalent short tests for FeCO6. In future we might consider constructing a wavefunction and basis set for a model system to specifically test the conversion and evaluation.

**Comment by ye-luo** [comment]
completed by #654

**Comment by ye-luo** [comment]
completed by #654
