### ISSUE TITLE
Is anything but ESHDF still used for orbital files?

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#647]
There seem to be a couple of major HDF layouts for the single particle orbitals - ESHDF, and something else.  Can the non-ESHDF reading code be removed, or are the other formats still in use?

In EinsplineSetBuilder::ReadOrbitalnfo the code path is chosen based on the 'format' group in the HDF file. If 'ES' is present, ReadOrbitalInfo_ESHDF is called.  If not, ReadOrbitalInfo continues and reads from the HDF file (with a couple of variations based on the version)

**Comment by jtkrogel** [comment]
I think the non-ESHDF code can be removed.  Comments from @ye-luo or @lshulen?

**Comment by ye-luo** [comment]
non-ESHDF routines should be removed. There are too many EinsplineSetXXX.cpp files. Those with small routines can be merged.
