### ISSUE TITLE
What are higher wavefunction derivatives used for?

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#653]
There are higher spatial derivatives of the wavefunction, such as the Hessian in 
evaluateHessian (defined in OrbitalBase.h) and evaluateWithHessian (defined in BasisSetBase.h)

The Hessian appears to be used for the stress tensor in QMCHamiltonians/StressKinetic.cpp.  Is it used anywhere else? And, related, is the stress tensor an important observable?

Then BasisSetBase.h also defines evaluateWithThirdDeriv and evaluateWithThirdDerivOnly, which appear to be used in various overloads of evaluateForWalkerMove in SphericalBasisSet.h.   It appears that these overloads are not used (searching for the GGGVector_t type or grad_grad_grad_Phi doesn't seem to turn up anywhere outside QMCWaveFunctions).
Are these third derivatives used?  What is their intended purpose?

**Comment by lshulen** [comment]
Not sure about the answers to many of these (for example the third deriv stuff), but I consider the stress tensor to potentially be an important observable.  I think it is not used much now for many reasons, but I routinely use it for many classes of calculation in DFT.

**Comment by prckent** [comment]
Stress tensor is important.

If no-one comments on third derivatives lets get rid of them. Anything we can do to simplify OrbitalBase is helpful. We need to evolve OrbitalBase so that only actually used functionality is referenced (!), and that we identify the minimal set of functionality needed to implement (say) a new Jastrow.

**Comment by Paul-St-Young** [comment]
@rcclay do you know what the higher derivatives are used for?

**Comment by rcclay** [comment]
Backflow optimization?

**Comment by jngkim** [comment]
Yes.

**Comment by Paul-St-Young** [comment]
Oh yes. `evaluateWithThirdDeriv` is used in `LCOrbitalSetWithCorrection.h::evaluate_notranspose` for `grad_grad_grad_logdet`. This is in the molecular code path for backflow optimization.

**Comment by prckent** [comment]
Thanks. Some comments about exactly which derivative is being taken and the main use case in orbitalbase would help.

**Comment by mmorale3** [comment]
Optimizing parameters in the backflow transformation requires the mixed second order derivatives, not just the diagonal terms. The formulas are in the BF classes and in David’s papers.

**Comment by jtkrogel** [comment]
Question answered.
