### ISSUE TITLE
Error reading molecular orbitals from GAMESS

### ISSUE THREAD

**Issue by nsblunt** [QMCPACK/qmcpack#666]
I'm using the convert4qmc script to generate a wave function xml file from GAMESS. In one case, some of the virtual molecular orbitals have very large coefficients. In cases where these are negative and have magnitude greater than 100.0, there is a quirk in the printing where orbital coefficient are merged together - here's an example, see the "-103.88..." on the final line:

  102  C  5  Z    0.000000   0.000000  -0.215939   0.071102   0.000706
  103  C  5  X    0.000000   0.000000  -8.413034 -73.890437  10.713047
  104  C  5  Y   -1.957422   0.366991  -0.000000  -0.000000   0.000000
  105  C  5  Z    0.000000   0.000000  -0.567800-103.884284  -2.142253

The convert4qmc script doesn't deal with this properly, and the corresponding coefficients for that MO look like this in the QMCPack xml file:

7.11020000000000e-02 -7.38904370000000e+01 -0.00000000000000e+00 -5.67800000000000e-01

i.e., the -103.88 is replaced by the -0.5678 before it.

For multi-determinant calculations that make use of the virtual orbitals, this gives some badly incorrect energies. I'm not sure if you're aware of this, but I thought I should at least point it out. It could cause problems if a user doesn't spot it. Although the energy was clearly wrong in my current case, perhaps it may be more subtle in others.

I can send the GAMESS file if helpful.

**Comment by prckent** [comment]
Nick - Thanks. Please can you attach the example here. We have a responsibility to handle this awkwardness correctly.

**Comment by nsblunt** [comment]
I've attached the GAMESS input and output, and XML. The system is benzonitrile with a BFD pseudo potential, and an augmented-VDZ basis. The problems really come about for excited state calculations, using multi-det, or in my case FDLR. I can send my FDLR input files if needed, but hopefully the problem is visible anyway. Thanks.

[benzonitrile.tar.gz](https://github.com/QMCPACK/qmcpack/files/1691975/benzonitrile.tar.gz)

**Comment by markdewing** [comment]
Looking at GAMESS, it appears the eigenvectors are output in subroutine PREV, in mthlib.src.
The format description is labeled 9048
```9048 FORMAT(I5,2X,A8,10F11.6)```

The ```F11.6``` is the relevant format descriptor.
 For negative numbers between 100 and 999, the numbers run together with a dividing minus (`0.000000-103.000000`). 
For positive numbers between 1000 and 9999, the numbers run together with no divider (`-103.0000001103.000000`). 
For negative numbers less than -1000 or positive numbers greater than 10000, the field width is exceeded and it prints a series of `*`'s (at least with gfortran)

For higher angular momentum states, the atom label has 4 different formats with respect to spacing.   These formats are set up in the SETLAB subroutine in inputb.src.

1. An atom number is included, with spaces between everything. This is the format the converter expects  (`   91  AR 1 YYY`)
2. The atom number runs up against the angular momentum label (`  100  AR 1XXXX`)
3. For higher states, the atom number is dropped to make room for the angular momentum label (`  208  AR X3Y2Z`)
4. The atom label runs up against the against the angular momentum label (`  214  ARX2Y2Z2`)
