### ISSUE TITLE
ppconvert segfaults in release with modern clang and mkl

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#679]
Seg faults in release on OSX with llvm 5.0.1. on lab 2's 
```shell
ppconvert --gamess_pot O.BFD.gamess --s_ref "1s(2)2p(4)" --p_ref "1s(2)2p(4)" --d_ref "1s(2)2p(4)" --xml O.BFD.xml
```
Also trips so so many warnings even with the warning suppression the rest of the codebase requires on.

**Comment by prckent** [comment]
Do other uses of ppconvert work when compiled this way or have you only tried lab 2?

**Comment by PDoakORNL** [comment]
So far I haven't returned to it or tried it with a different compiler. But this is a pretty new compiler. I'll share results when I do.

**Comment by PDoakORNL** [comment]
Until llvm 5.0.1 build is supported this is not reproducable
