### ISSUE TITLE
Updated documentation for QE 6.2.1 converter needed

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#681]
Once #678 is committed we need to update the manual. For the converter to work we now require QE to be built using the internal HDF5 support which requires access to HDF5 with Fortran and MPI parallel interfaces enabled. Some full examples will help.

Below I list what I used while testing.

For HDF5 1.10.1:
```
source /opt/intel2017/bin/compilervars.sh intel64
which mpiifort
ver=hdf5-1.10.1
refdir=`pwd`/$ver
INSTALLDIR=`pwd`/${ver}-intel-mpi
rm -r -f ${refdir} ${INSTALLDIR}
tar xvf ${ver}.tar.gz
mkdir ${INSTALLDIR}
cd $INSTALLDIR
CC=mpiicc FC=mpiifort ../$ver/configure --enable-parallel --enable-fortran  --prefix=$INSTALLDIR
make
make install
```
I specifically used the Intel2017 compiler series and not Intel2018 because the Intel 2018 Fortran compiler (correctly) does not build HDF5 1.10.1 due to illegal Fortran. Older compilers ignored the error. The bug will be fixed in HDF5 1.10.2.

For QE 6.2.1 downloaded with download_and_patch_qe6.2.1.sh script:
```
source /opt/intel2017/bin/compilervars.sh intel64
which mpiifort
export MPIF90=mpiifort
export F77=mpiifort
export CC=mpiicc
export HDF5_LIB=/full/path/to/hdf5-1.10.1-intel-mpi/
./configure --with-scalapack=intel --with-hdf5=$HDF5_LIB
make all
```
We should request people check the HDF5 is detected and enabled by configure.

To build QMCPACK and test the converter:
```
cmake -DCMAKE_CXX_COMPILER=mpiicpc -DCMAKE_C_COMPILER=mpiicc -DENABLE_SOA=1 -DENABLE_TIMERS=1 -DQMC_DATA=/full/path/to/QMC_DATA/ -DQE_BIN=/full/path/to/qmcpack/external_codes/quantum_espresso/qe-6.2.1/bin ../qmcpack/
make -j 16
ctest -R qe
```

**Comment by ye-luo** [comment]
In fact, if there is only hdf5 with c and serial, you can still build the converter.
Just manually edit make.inc by adding `-D__HDF5_C -DH5_USE_16_API` in `DFLAGS` and provide include and library path in `IFLAGS` and `HDF5_LIB`

**Comment by prckent** [comment]
Presumably the converter uses the old style I/O format from QE in that case?

**Comment by ye-luo** [comment]
@prckent Correct. via iotk.

**Comment by ye-luo** [comment]
- [ ] Also need to include the norm check in the patch.
