### ISSUE TITLE
cmake halts on iszero test that should just fail for intel and clang on linux and clang on osx and when bad cmake policy is set on cray.

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#685]
It intermittently fails the iszero test for clang and intel setup in the obvious way on linux and (llvm not apple) clang on osx.

**Comment by PDoakORNL** [comment]
hdf5 support fails to add necessary link flag when used with standard spack module for hdf5

workaround 
-DCMAKE_EXE_LINKER_FLAGS=-L/software/user_tools/centos-7.2.1511/cades-cnms/spack/opt/spack/linux-centos7-x86_64/intel-17.0.0/hdf5-1.10.1-i46vzubx6vks4hqs4jfhjyfoi65l6wbh/lib
or the like

**Comment by PDoakORNL** [comment]
I also saw this on titan without protecting it from calling cmake_policy with a cmpxxxx it didn't know about.

**Comment by PDoakORNL** [comment]
The above is the one way I can guarantee you will see it. Mind you the test always fails, I will change title.  put cmake_policy(cmp0056) into CMakeLists.txt under cmake_policy(cmp0003) on titan with cmake 2.8.10 and this test will be what at least appears to kill everything in CMakeError.log.

Adding test short-hcpBe_1x1x1_pp-vmc_sdj-1-16
Adding test long-hcpBe_1x1x1_pp-vmc_sdj-1-16
Adding test short-monoO_1x1x1_pp-vmc_sdj-1-16
Adding test short-monoO_1x1x1_pp-vmc_sdj3-1-16
Adding test long-monoO_1x1x1_pp-vmc_sdj-1-16
Adding test long-monoO_1x1x1_pp-vmc_sdj3-1-16
Adding example tests for QMCPACK
-- Configuring incomplete, errors occurred!

Then look in CMakeError.log
```shell
Performing C++ SOURCE FILE Test HAVE_ISZERO failed with the following output:
Change Dir: /lustre/atlas/proj-shared/cph108/epd/qmcpack/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec3011767995/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3011767995.dir/build.make CMakeFiles/cmTryCompileExec3011767995.dir/build
gmake[1]: Entering directory `/lustre/atlas2/cph108/proj-shared/epd/qmcpack/build/CMakeFiles/CMakeTmp'
/autofs/nccs-svm1_sw/xk6/cmake/2.8.10.2/cle4.0_gnu4.7.2/bin/cmake -E cmake_progress_report /lustre/atlas/proj-shared/cph108/epd/qmcpack/build/CMakeFiles/CMakeTmp/CMakeF
iles 1
Building CXX object CMakeFiles/cmTryCompileExec3011767995.dir/src.cxx.o
/opt/cray/craype/2.5.13/bin/CC    -DHAVE_ISZERO   -o CMakeFiles/cmTryCompileExec3011767995.dir/src.cxx.o -c /lustre/atlas/proj-shared/cph108/epd/qmcpack/build/CMakeFile
s/CMakeTmp/src.cxx
/lustre/atlas/proj-shared/cph108/epd/qmcpack/build/CMakeFiles/CMakeTmp/src.cxx: In function 'int main()':
/lustre/atlas/proj-shared/cph108/epd/qmcpack/build/CMakeFiles/CMakeTmp/src.cxx:2:48: error: 'iszero' was not declared in this scope
                          int main() {iszero(1.0); return 0;}
                                                ^
gmake[1]: *** [CMakeFiles/cmTryCompileExec3011767995.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory `/lustre/atlas2/cph108/proj-shared/epd/qmcpack/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTryCompileExec3011767995/fast] Error 2

Source file was:
#include <math.h>
                         int main() {iszero(1.0); return 0;}
```

**Comment by markdewing** [comment]
With cmake 2.8.10.2 and policy CMP0056, the unknown policy error is what causes the 'Configuring incomplete, errors occurred' message at the end.    (From there, running 'make' will fail to compile anything, and CI will fail because no unit tests were run).

The CMakeError.log file is a log of trial compiles that failed, not necessarily a log of what caused the CMake configuration to fail.     Some trial compiles are expected to fail, as in this case for iszero.

**Comment by PDoakORNL** [comment]
Ok so basically I was misreading cmake output I guess.  Closing this.
