### ISSUE TITLE
Removing OMP labels in filenames?

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#692]
I propose we remove all of these. We are intrinsically an OpenMP code and I don't think we gain anything from labeling a subset of files with OMP. Are the OMP labels helping anyone?

**Comment by jtkrogel** [comment]
I have no objection to this change.

**Comment by ye-luo** [comment]
Though they are needed just in case, it is simple and no harm to keep them.

**Comment by prckent** [comment]
OK. I'll keep the rename of OrbitalBase->WavefunctionComponent focused on that.

**Comment by grahamlopez** [comment]
Why are they needed?

**Comment by ye-luo** [comment]
Since we have XXX_CUDA, having XXXOMP is also also easy to distinguish from each other.
XXXSingleOMP is wired, 'Single' should be removed.
Maybe XXX_OMP is more readable than XXXOMP.
We should definitely have all names consistent.

**Comment by prckent** [comment]
This issues is largely about renaming the drivers.
```
cd qmcpack/src; find . -name "*OMP*"
./OOMPI
./QMCDrivers/LMYEngineInterface/LMYE_QMCCostFunctionOMP.cpp
./QMCDrivers/QMCCostFunctionOMP.cpp
./QMCDrivers/DMC/DMCOMP.cpp
./QMCDrivers/DMC/DMCOMP.h
./QMCDrivers/RMC/RMCSingleOMP.cpp
./QMCDrivers/RMC/RMCSingleOMP.h
./QMCDrivers/VMC/VMCSingleOMP.cpp
./QMCDrivers/VMC/VMCLinearOptOMP.h
./QMCDrivers/VMC/VMCSingleOMP.h
./QMCDrivers/VMC/VMCLinearOptOMP.cpp
./QMCDrivers/QMCCostFunctionOMP.h
```

From an accessibility point of view, dropping OMP and Single would be helpful. Then we actually have a file VMC.cpp that does VMC (etc.). Some grepping (grep -n -i -r '#pragma omp' *) shows that OpenMP is pervasive, so calling it out in these drivers is not needed.

**Comment by prckent** [comment]
To minimize conflicts with ongoing work, I suggest doing this immediately after #1152
