### ISSUE TITLE
Deterministic integration tests needed

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#704]
Integration tests for production scale (high atom/electron count) systems remain a hole in our test system.  Since statistical tests are not feasible here, I propose that we make a variety of deteriministic tests that will be both high precision and fast, enabling rapid testing of new code for these important use cases.

The basic idea is to implement a few new, but small, features in QMCPACK:
1) A simple, per thread deterministic "random number" generator that will always supply the same stream per thread.
2) A basic data streaming facility that will write out a few scalars per walker, per step (e.g. the local energy, mean electron coordinate, wavefunction value, mean gradient, laplacian) at high precision, e.g. in HDF5.  If desired, the existing Traces facility could be used for this.  
3) The ability to read data from an existing stream file and check the current generated stream of internal data against the reference data with a given tolerance.

Features 1 & 2 are for test generation and 3 is for test execution.  Once all three features are in place, one could take any short run (a couple blocks and steps) and create a test by turning on the appropriate compile/run-time flags.

This would allow fast deterministic tests to be created for small to large physical systems and give more confidence in the correctness of commits affecting large portions of the code base.

**Comment by markdewing** [comment]
I think the RNG will produce the same stream of numbers give the same initial seed.   So 1 and 2 might already be possible with the current qmcpack - specify the RNG seed in the input file, use the same number of threads, and use traces to write out the scalars (can Traces already do what you want, or does it need additions?)

There exists a fake random number generator for unit test purposes.  It currently outputs 0.5 for every value, but it could be modified to produce a more random looking sequence.
https://github.com/QMCPACK/qmcpack/blob/develop/src/Utilities/FakeRandom.h

The unit test for VMC (and DMC) advanceWalker uses the fake RNG and a constant wavefunction to check the results for one step.

https://github.com/QMCPACK/qmcpack/blob/develop/src/QMCDrivers/tests/test_vmc.cpp

**Comment by prckent** [comment]
@jtkrogel makes an important point. Without deterministic tests we will not be able to test high electron count systems with confidence.

**Comment by prckent** [comment]
After some discussion with @grahamlopez : A further benefit of deterministic integration tests would be that we could largely remove the unreliable and slow to run statistical integration tests we currently use. This would be hugely beneficial since the tests would be reliable and very fast to run, allowing them to be used during installation and for continuous integration. It should help development too: developers will be able to run the tests routinely.

We would likely still need a few statistical integration to convince people that the methods work, particularly the parallelization settings, but these could be run in nightlies only.

To implement this we need a repeatable strategy to generate gold data via an appropriately rigged/fixed random number seed or generator (via an input option), store restart data, then do a single block and single move. Thoughts, improvements?

**Comment by ye-luo** [comment]
Deterministic tests are clearly useful.

RNG route may not work. The reason is even if you have exactly identical RNG stream, the subtle numeric difference on ratio and drift will alter the trajectory. If some changes use more RNG, the test will also be messed up.

Having these tests going through the VMC/DMC can be a mess. I prefer adding it in the wftest driver and having a 'replay' feature that repeats the calculation based on the configurations stored in a file, just like what @jtkrogel wants.

On the other hand, we should improve our unit tests. The level of detail is still different from deterministic integration tests.

**Comment by grahamlopez** [comment]
> Having these tests going through the VMC/DMC can be a mess.

I think this is an argument for needing the tests to use this code; if it is already difficult/messy, even more reason that it needs to be validated.

> I prefer adding it in the wftest driver

IMO, integration tests are most (only?) useful when they run through the production code paths.

> On the other hand, we should improve our unit tests. The level of detail is still different from deterministic integration tests.

definitely. +1

**Comment by lshulen** [comment]
I like the idea of these tests going through the same code path as would be used in the code.  Otherwise I think the risk becoming overly complicated unit tests.  I do like Ye’s idea to used canned trajectories rather than a fixed random number generator.  Perhaps we could actually have as input both the trajectories and the random numbers that led to them.  In that case one could test not only observable a or properties of the wavefunction, but also that the propagation was leading to the “correct” trajectories.

One place that could run into difficulty though is when modifications are made that knowingly compromise numerical accuracy, but are thought to lead to correct integrated quantities.  I’m thinking of some of the mixed precision work for example.

**Comment by jtkrogel** [comment]
If the goal of the tests is simply to ensure the code does not change (numerically) from its current state when commits are made, then we could partially solve the second point that Luke raises by having the deterministic tests be specific to the actual code base run (e.g. create a new set of test data self-consistently with the mixed precision code).

The decision about what degree of change is acceptable (setting failure tolerances) in general is more difficult as there are at least three regimes for this:
1. Deviates from "large tolerance" e.g. 1e-3 -> obviously wrong/bug
2. Deviates from "medium tolerance" -> wrong or subtly right
3. Agrees to "high tolerance" e.g. machine precision-> obviously right

This is exactly the difficulty in deciding that the mixed precision implementation is correct or not when judging its deviation from the full precision code with deterministic tests.  

Of course, we are left to make/solve this difficult judgement for every change that comes in, with the mixed precision implementation just being a single example.

**Comment by jtkrogel** [comment]
I suppose we could demand that new changes agree to whatever is appropriate for "high tolerance" and give exception to intentionally made and deeply vetted changes like mixed precision.

**Comment by prckent** [comment]
I think we can decide to use gold data and appropriate tolerances. The tolerances will need tuning, but thinking about the tolerances is already a useful exercise.

**Comment by prckent** [comment]
We need to address the question of how to handle multiple threads and multiple walkers. I'll make a simplifying suggestion after discussing possibilities:

To handle multiple walkers we need to generate gold data for multiple walkers (easy), but then ensure that the correct next steps are taken during the test (tricky). We could rig a constant random number generator, or as discussed above, we could use a rigged simple random number generator to avoid a constant sequence and possible edge cases. However, this assumes that we use the random numbers in the same order on different architectures and with different thread counts, which is not the case currently, and can't easily be made the case.

If we wanted to always be able to run the tests on as many threads (cores etc.) as we chose, we could consider duplicating/cloning an initial walker, and using either a rigged or constant random sequence. This would allow us to check threading code and easily know the gold result.

We then arrive at the simplified starting point: why not write the tests for only a single walker? This would test all the main physics logic and numerics, and would catch all the cases of historic breakage that we have had to deal with. What would not be tested would be threading and mpi related, but we have the stochastic integration tests to fall back on. We could add tests using another strategy (e..g the cloning strategy, previous paragraph) if ever warranted.

**Comment by jtkrogel** [comment]
This is how I was thinking of tackling these problems:

Issues:
1) Support for varying walker/core counts
2) Output sequence/values depend on compiler/architecture

Solution:
1) Have a single reference version of the code, but not a single set of reference values.
2) Make process of generating reference data identical to process of generating test data (must be fast and easy).  In this case, a short traces run suffices to satisfy this requirement.
3) Generate a set of reference data on each machine+walker/thread count using a fixed inputted random number seed.  Easy, just do a short traces run identical to the test first.
4) Reference and test data generated by traces: each value is already tagged with a walker id and step number.
5) Compare traces hdf output from reference and test run directly, no in-code instrumentation required.

As long as we can count on a fixed random number seed resulting in the same sequence of events on a fixed architecture/environment, then we are good.  An open question is the compatibility of existing traces code with the existing gpu branch.

**Comment by jtkrogel** [comment]
A good path forward would be to make e.g. a 4 block 4 step version of each current test case (should run very fast, initialization will dominate in many cases) and add traces input blocks.  Next, some external tooling (cmake+python) to generate/update reference data and to run tests+compare w/ reference data.

**Comment by prckent** [comment]
Summarizing a conversation with @jtkrogel and next steps:

We think single walker testing is a good place to start investigations, although clearly this can't test threading of multiple walkers or MPI code. We will setup a single walker test case "by hand" and check the current ability to run the code deterministically and on multiple architectures. We'll try seeding the existing random number generator first. Runs will initially generate their own electron positions i.e. will not load and use equilibrated data. The idea is to use traces to check components of the total energy and electron positions for a few steps. These will be fast to run and only require storage of a small gold trace file. 

If we convert the existing statistical tests, they will all be similar enough that we could likely automate running a list of them in cmake/ctest.

Questions to answer before proceeding:

1. Are the steps platform independent?
2. Do traces work on all platforms?

If no to either, it will be worth fixing them since it will make testing much easier.

Note: https://stackoverflow.com/questions/30649381/crossplatform-reproducible-number-generator reports boost:mt19937 gives same results on multiple platforms.

**Comment by prckent** [comment]
Following up on random numbers, the TRIQS folks have been through this e.g. https://github.com/TRIQS/triqs/blob/master/test/triqs/mc_tools/rng.cpp . Used with caution MT is reproducible even though there are no guarantees.

```
// This test that std::random and boost::random are the same for MT and uniform distribution
// Conclusion : the std and boost generator give the same numbers.
// However the uniform_real_distrib differ. Anyway, this is not guaranteed to be implementation dep.
// by the std.
```

**Comment by lshulen** [comment]
I think this is a reasonable path.  There are two things longer term that may be worth considering.  The first is how this will work on truly different architectures.  By that I mean, what would this look like for the GPU code?  I'm hopeful given the IEEE floating point that there would not be a problem, but given that the algorithm is different, I don't know this has to be the case.  That leads me to the other question.  Is this the right thing to look at as we change algorithms / parallelization strategy for the ECP?  

At worst case, we could just maintain a set of "golden standard" data for each algorithm, but I wanted to mention these anyway.

**Comment by ye-luo** [comment]
I still feel the need of a replay mode in the drivers namely all the particle coordinates are loaded from file. 
This will totally bypass the RNG problem.
This can be made independently from architecture and code paths.

**Comment by prckent** [comment]
Some people have been wondering about the current status:

- By setting the initial random seed, CPU runs appear to be reproducibility between compilers and platforms. Numerical differences are small enough that, at least for a few 10s of steps, our current tests could be used as a basis for tests.

- The CUDA implementation is definitely doing something different from the CPU code. bccH 1x1x1 with no jastrow i.e. with just one up and one down electron, yields different acceptances than the CPU code for a single walker. This indicates that some part of particle initialization or VMC Monte Carlo is different. Below compares GCC, Intel, GCC+CUDA. Each block is 10 steps, more than sufficient for our purposes.

```
[pk7@oxygen deterministic_testing]$ cat test_gcc/bccH_vmc.s000.scalar.dat test_intel2018_soa/bccH_vmc.s000.scalar.dat test_gcc_cuda_double/bccH_vmc.s000.scalar.dat
#   index    LocalEnergy         LocalEnergy_sq      LocalPotential      Kinetic             ElecElec            IonIon              ElecIon             Flux                BlockWeight         BlockCPU            AcceptRatio
         0   -1.8767408467e+00    3.5725852115e+00   -1.8451093640e+00   -3.1631482623e-02   -7.6779892757e-01   -9.6289961705e-01   -1.1441081942e-01    3.8336071072e-01    1.0000000000e+01    8.5223698989e-04    9.5000000000e-01
         1   -2.0025263481e+00    4.0392521810e+00   -2.9790282007e+00    9.7650185262e-01   -8.6541463784e-01   -9.6289961705e-01   -1.1507139458e+00   -1.4319055813e+00    1.0000000000e+01    8.8477204554e-04    8.5000000000e-01
         2   -1.9304980442e+00    3.7668924962e+00   -2.8624642447e+00    9.3196620054e-01   -8.9345418391e-01   -9.6289961705e-01   -1.0061104438e+00   -1.1842689049e+00    1.0000000000e+01    8.3827902563e-04    9.2500000000e-01
         3   -1.8496669819e+00    3.4505150261e+00   -2.3709851038e+00    5.2131812184e-01   -8.1674094228e-01   -9.6289961705e-01   -5.9134454445e-01   -5.1026090577e-01    1.0000000000e+01    8.1993499771e-04    9.0000000000e-01
         4   -1.7949128434e+00    3.2668638472e+00   -1.9770352069e+00    1.8212236347e-01   -7.4095567238e-01   -9.6289961705e-01   -2.7317991747e-01   -1.2418558242e-01    1.0000000000e+01    8.6864701007e-04    9.5000000000e-01
         5   -1.7668853682e+00    3.1677302551e+00   -2.9252887434e+00    1.1584033752e+00   -8.2415162992e-01   -9.6289961705e-01   -1.1382374964e+00   -1.8525419246e+00    1.0000000000e+01    8.5969502106e-04    7.5000000000e-01
         6   -1.9409935449e+00    3.7702434728e+00   -1.8805080314e+00   -6.0485513486e-02   -8.2917119022e-01   -9.6289961705e-01   -8.8437224126e-02    4.3805088371e-01    1.0000000000e+01    8.3157105837e-04    9.5000000000e-01
         7   -1.6509555075e+00    2.9487319736e+00   -1.4427210738e+00   -2.0823443369e-01   -5.7084093530e-01   -9.6289961705e-01    9.1019478526e-02    6.2737101101e-01    1.0000000000e+01    8.6424197070e-04    9.5000000000e-01
         8   -1.8536547485e+00    3.4944881625e+00   -1.6819866802e+00   -1.7166806833e-01   -7.6678954285e-01   -9.6289961705e-01    4.7702479685e-02    5.7521893297e-01    1.0000000000e+01    8.6558493786e-04    9.7500000000e-01
         9   -1.8652333024e+00    3.5046724151e+00   -1.6677515394e+00   -1.9748176303e-01   -7.7378805424e-01   -9.6289961705e-01    6.8936131929e-02    6.3967064433e-01    1.0000000000e+01    8.3466991782e-04    1.0000000000e+00
#   index    LocalEnergy         LocalEnergy_sq      LocalPotential      Kinetic             ElecElec            IonIon              ElecIon             Flux                BlockWeight         BlockCPU            AcceptRatio
         0   -1.8767408660e+00    3.5725852840e+00   -1.8451093833e+00   -3.1631482623e-02   -7.6779893722e-01   -9.6289962670e-01   -1.1441081943e-01    3.8336071072e-01    1.0000000000e+01    2.5010108948e-04    9.5000000000e-01
         1   -2.0025263674e+00    4.0392522583e+00   -2.9790282200e+00    9.7650185262e-01   -8.6541464750e-01   -9.6289962670e-01   -1.1507139458e+00   -1.4319055813e+00    1.0000000000e+01    2.3794174194e-04    8.5000000000e-01
         2   -1.9304980635e+00    3.7668925708e+00   -2.8624642640e+00    9.3196620054e-01   -8.9345419356e-01   -9.6289962670e-01   -1.0061104438e+00   -1.1842689049e+00    1.0000000000e+01    2.4008750916e-04    9.2500000000e-01
         3   -1.8496670012e+00    3.4505150975e+00   -2.3709851231e+00    5.2131812184e-01   -8.1674095193e-01   -9.6289962670e-01   -5.9134454445e-01   -5.1026090577e-01    1.0000000000e+01    2.4294853210e-04    9.0000000000e-01
         4   -1.7949128627e+00    3.2668639166e+00   -1.9770352262e+00    1.8212236347e-01   -7.4095568203e-01   -9.6289962670e-01   -2.7317991747e-01   -1.2418558242e-01    1.0000000000e+01    2.5105476379e-04    9.5000000000e-01
         5   -1.7668853875e+00    3.1677303233e+00   -2.9252887627e+00    1.1584033752e+00   -8.2415163957e-01   -9.6289962670e-01   -1.1382374964e+00   -1.8525419246e+00    1.0000000000e+01    2.3484230042e-04    7.5000000000e-01
         6   -1.9409935642e+00    3.7702435477e+00   -1.8805080507e+00   -6.0485513486e-02   -8.2917119987e-01   -9.6289962670e-01   -8.8437224125e-02    4.3805088371e-01    1.0000000000e+01    2.3794174194e-04    9.5000000000e-01
         7   -1.6509555268e+00    2.9487320373e+00   -1.4427210931e+00   -2.0823443369e-01   -5.7084094495e-01   -9.6289962670e-01    9.1019478528e-02    6.2737101101e-01    1.0000000000e+01    2.5105476379e-04    9.5000000000e-01
         8   -1.8536547679e+00    3.4944882341e+00   -1.6819866995e+00   -1.7166806833e-01   -7.6678955250e-01   -9.6289962670e-01    4.7702479683e-02    5.7521893297e-01    1.0000000000e+01    2.3984909058e-04    9.7500000000e-01
         9   -1.8652333217e+00    3.5046724871e+00   -1.6677515587e+00   -1.9748176303e-01   -7.7378806389e-01   -9.6289962670e-01    6.8936131928e-02    6.3967064433e-01    1.0000000000e+01    2.3984909058e-04    1.0000000000e+00
#   index    LocalEnergy         LocalEnergy_sq      LocalPotential      Kinetic             ElecElec            IonIon              ElecIon             Flux                BlockWeight         BlockCPU            AcceptRatio
         0   -1.8558034783e+00    3.4832879431e+00   -1.8362729172e+00   -1.9530561122e-02   -7.6128961581e-01   -9.6289961705e-01   -1.1208368434e-01    3.8355197097e-01    1.0000000000e+01    7.9856150551e-03    9.7500000000e-01
         1   -1.8795612353e+00    3.5907938691e+00   -2.4674450669e+00    5.8788383165e-01   -7.6094836143e-01   -9.6289961705e-01   -7.4359708843e-01   -5.6050439351e-01    1.0000000000e+01    7.8698178986e-03    9.0000000000e-01
         2   -1.9657775059e+00    3.8738254294e+00   -2.1554319501e+00    1.8965444420e-01   -8.8673599870e-01   -9.6289961705e-01   -3.0579633440e-01    1.7329116190e-02    1.0000000000e+01    7.7455129940e-03    9.0000000000e-01
         3   -1.8215651830e+00    3.3290428680e+00   -2.2710459260e+00    4.4948074308e-01   -8.2874771877e-01   -9.6289961705e-01   -4.7939859023e-01   -4.7375606303e-01    1.0000000000e+01    7.6813390478e-03    9.0000000000e-01
         4   -1.8201840491e+00    3.3634591754e+00   -2.0029612003e+00    1.8277715114e-01   -7.4982013242e-01   -9.6289961705e-01   -2.9024145079e-01    4.4169720578e-02    1.0000000000e+01    7.7066239901e-03    9.2500000000e-01
         5   -1.8239950380e+00    3.3439902975e+00   -1.7751233117e+00   -4.8871726280e-02   -7.2329375583e-01   -9.6289961705e-01   -8.8929938796e-02    4.0447371598e-01    1.0000000000e+01    7.7585780527e-03    1.0000000000e+00
         6   -1.9159355982e+00    3.6917806120e+00   -2.1452842500e+00    2.2934865181e-01   -8.1932311208e-01   -9.6289961705e-01   -3.6306152091e-01    1.8879024727e-02    1.0000000000e+01    7.7583839884e-03    8.7500000000e-01
         7   -1.9400346315e+00    3.7916261247e+00   -2.1707851391e+00    2.3075050762e-01   -8.5132945185e-01   -9.6289961705e-01   -3.5655607023e-01   -1.0417461349e-01    1.0000000000e+01    7.8827680554e-03    9.7500000000e-01
         8   -1.7254781084e+00    3.0120160593e+00   -1.9459173757e+00    2.2043926732e-01   -6.9531586072e-01   -9.6289961705e-01   -2.8770189794e-01    1.5200957192e-02    1.0000000000e+01    7.7085189987e-03    9.7500000000e-01
         9   -1.9362032158e+00    3.7701447546e+00   -2.1172237524e+00    1.8102053655e-01   -8.6658408829e-01   -9.6289961705e-01   -2.8774004705e-01    2.4091328955e-02    1.0000000000e+01    7.6869840268e-03    9.0000000000e-01
```

**Comment by jtkrogel** [comment]
We have deterministic tests, but mostly for small systems.
