### ISSUE TITLE
Incorrect reference values used in long-FeCO6 tests

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#728]
Based on the most recent long runs, https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=20711 it appears that some of the reference values for long-FeCO6 are incorrect. E.g.  long-FeCO6_gms-vmc_b3lyp_noj-1-16-samples . These failures could be hiding other problems.

**Comment by anbenali** [comment]
addressed by #905
