### ISSUE TITLE
Use of _CRAYMPI preprocessor flag in src/Message/CommOperatorsMPI.h

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#73]
This must have been added at some point to avoid an MPI problem. Current "blame" shows Miguel, but this might not be the true origin. Can use of _CRAYMPI be removed? The current titan, eos build scripts do not use it.

**Comment by ye-luo** [comment]
A quick googling shows the buffer size was related to XT5 in the old days. I think we can just keep these lines of code as long as we have a record here.

**Comment by prckent** [comment]
I am very much in favor of removing this cruft (assuming it is confirmed as really cruft). If all the currently-being-run benchmarks are OK I suggest we remove.

**Comment by prckent** [comment]
The code builds with -D_CRAYMPI after #72 . We'll keep the code for now, but NOT recommend it for general use.  It is not needed e.g. for scaling runs on current generation CRAYs.
