### ISSUE TITLE
Add QMCPACK citation paper final citation to header

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#731]
In the timeframe of the release, this accepted paper will hopefully have final page numbers and citation info.

**Comment by ye-luo** [comment]
Just to use this issue as a memo. Updating the info on our website is also needed. Recently people asked me again how to cite.

**Comment by prckent** [comment]
We have a whole new website in the works. The framework is there but the content has to be ported.

**Comment by ye-luo** [comment]
Please add one more empty line between paper info and git info in the next paper number update.
```
=====================================================
                    QMCPACK 3.4.0

       (c) Copyright 2003-  QMCPACK developers

                    Please cite:
      J. Kim et al. J. Phys. Cond. Mat. (2018)
      https://doi.org/10.1088/1361-648X/aab9c3
  Git branch: develop
  Last git commit: 8df128da96983e703cea69b54d4a4dfe96145807
  Last git commit date: Fri Apr 6 19:13:48 2018 -0500
  Last git commit subject: Merge pull request #746 from jtkrogel/nxdev
=====================================================
```
