### ISSUE TITLE
QMCPACK should abort when given bad planewave/bspline orbitals

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#761]
QMCPACK should abort when orbitals coming from pw2qmcpack are malformed.  I observed a case recently (using QE 5.3.0) where selected up orbitals for 3 out of 19 twists had unreasonably large per orbital kinetic energies.  This in and of itself reflects a bug in either pw2qmcpack or QE itself, with the converter being the most likely suspect.

In events similar to this, QMCPACK should abort with an error, rather than running and producing bad data (VMC at least, DMC generally crashes due to the extreme variance).

These cases could be guarded against by computing the per orbital kinetic energies (just summing planewave coeffs x g-vectors^2) and checking against a maximum value.  Since both the total kinetic energy and the number of orbitals scales like N, the per orbital kinetic energy is intensive.  The maximum value I have encountered for this quantity is around 7 Ha, while these failure cases are in the range of 60-120 Ha per orbital.  A maximum value of around 15 Ha might be reasonable.

Separately, the potential bug with the converter needs looking into, but the problem runs take days to converge and I do not know if the problem is easy to reproduce.  Robustness is hard.

**Comment by ye-luo** [comment]
Did your python tool also get a bad KE from the generated h5?
How about having pw2qmcpack computes the KE for each orbital and record them in hdf5? Then in qmcpack computes KE from gvec and check.

**Comment by jtkrogel** [comment]
Yes, post-failure I found the bad KE's directly from the h5 file with my tool.  

I think pw2qmcpack should compute the total KE per supercell k-point and report it in the output for user reference.

Bug checking can take multiple forms based on the per orbital KE's:
1) Orbital KE's are very similar across supercell twist (typically differ by ~0.03 Ha when comparing orbitals with same index, ordered by KS eigenvalue).  Any difference in orbital KE across supercells twists/kpoints exceeding e.g. 1 Ha is a bug.
2) In pw2qmcpack and QMCPACK, an orbital KE > 15 Ha is a bug.
3) In QMCPACK total and per orbital KE could be checked against the values calculated within pw2qmcpack, but as you mention this would require an update to the h5 file format.

I would recommend all of the above with a hard look being given to the KE's computed within pw2qmcpack.  I strongly suspect there is a bug at that level since the DFT total energies looked fine.  

If desired, I can make available the directory where h5 generation with pw2qmcpack was performed (on Eos) for conversion step reruns + bug hunting.

**Comment by prckent** [comment]
Perhaps an argument for a standalone tool that computes the K.E.?

**Comment by jtkrogel** [comment]
I think pw2qmcpack and QMCPACK should take responsibility for not producing or accepting bad orbitals.  The more checks available, via external tools or internally, the better.

**Comment by lshulen** [comment]
@jtkrogel my tool has no internal check that the KE is correct.  I've relied either on either the -pw2casino flag for espresso to print this, or on doing a VMC calculation with no Jastrow.  What sort of test do you recommend?

Specifically for my tool, it will have available to it all of the pieces to the total energy (save the XC energy) that espresso has.  I suppose I could check that the states coming out of espresso are still ordered in terms of increasing energy.

**Comment by lshulen** [comment]
Thanks.  If it's easy to hijack the machinery from pw2casino, it would also be useful to print out other quantities like non-local pp energy, local pp energy etc.

**Comment by jtkrogel** [comment]
This is a good suggestion.  I will check it explicitly for one problem case.

**Comment by jtkrogel** [comment]
Bad orbitals are indeed marked by non-unit norm.  I observe norms between 0.7 and 3.4 for the problem orbitals previously identified on the basis of kinetic energy.  Neighboring non-problem orbitals have a norm of 1.0.  Orthogonality is also broken with problem orbital overlaps of about +/-0.04.

This is a good check to always perform on the orbitals and will probably help to track down the bug (#763) faster.  This could probably also be extended to make a general measure for the quality of B-spline orbitals post-meshing.

**Comment by prckent** [comment]
My suggestion is then that we add a check (and abort) for inconsistent norms with a modest tolerance. I do not know of any electronic structure code that writes un-normed orbitals.  Checking for orthogonalization would be significantly more work. If in the far future we need to make these checks optional we can add an option to avoid the check.

**Comment by prckent** [comment]
Closing, since this is covered by #770 . However, there is still a bug in the conversion #763
