### ISSUE TITLE
Removing support for versions of QE older than v6.2.1?

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#762]
We currently have patches for QE 5.1, 5.2.0, 5.2.1, 5.3.0, and 6.2.1. This facilitates use of old versions of QE, but given the >3000 committed changes to QE since 5.1 I do not consider this a good thing. A fair fraction of the changes are bug fixes or important performance improvements. Support for old versions also increases our maintenance surface.

 My suggestion is that we only include patches for 6.2.1. I believe that this is feasible because:

- Our testing for 6.2.1 is as strong if not stronger than for older versions
- Compilation requirements for 6.2.1 are the same as for older versions. i.e. Anyone using 5.1 should be able to upgrade with little work.
- The older converters will still work and be available in previous releases should anyone really need them.

Are there good reasons to keep the older patches?

**Comment by jtkrogel** [comment]
I agree.

**Comment by prckent** [comment]
2 stable versions is the verdict and I think a good policy.
