### ISSUE TITLE
Poor orbitals resulting from QE+pw2qmcpack

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#763]
This issue details the problems observed that led to the creation of #761.  They are detailed here as requested by @prckent so that a specific fix can be created in addition to, or in place of, internal checks/guards in pw2qmcpack and/or QMCPACK. 

QE+pw2qmcpack+QMCPACK runs were performed for 48 atom cells of VO2 for five cases: pristine bulk, O vacancy with PBE+U/SCAN structures, V vacancy with PBE+U/SCAN structures.  All five runs were performed identically using the same supercell and supercell twist grid (3x3x3 inversion symmetrized by QE -> 19 twists).

All SCF runs required multiple day long restarts to complete.  At present the user recourse for a situation like the one detailed below is to rerun the SCF (>1 week user time when queues are accounted for) and hope for a better result.  Poor robustness at this level is detrimental to research timelines.

The DFT energies for these cases look fine (QE 5.3.0):
```
bulk       total energy = -3314.36064220 Ry
pbeu_ovac  total energy = -3282.06705718 Ry
scan_ovac  total energy = -3282.15912239 Ry
pbeu_vvac  total energy = -3170.97722852 Ry
scan_vvac  total energy = -3171.04621109 Ry
```
The VMC energies and variances do not:
```
            LocalEnergy               Variance                    ratio 
bulk       -1658.761501 +/- 0.002768     43.635270 +/-  0.034239    0.0263 
pbeu_ovac    249.763008 +/- 0.064952  25363.723318 +/- 68.664367  101.5512 
scan_ovac    431.577043 +/- 0.076007  27819.738736 +/- 81.120415   64.4607 
pbeu_vvac  -1586.506815 +/- 0.002816     42.241800 +/-  0.038467    0.0266 
scan_vvac    195.415773 +/- 0.064429  23688.654019 +/- 61.695259  121.2218 
```

For each of pbeu_ovac, scan_ovac, and scan_vvac, it is only the first three supercell twists that show a problem.   VMC energy, variance, kinetic energy, and electron-electron potential energy per twist are shown below for the pbeu_ovac case:
```
          LocalEnergy   Variance       ratio  Kinetic       ElecElec
qmc.g000  17194.20(82)  253331(1054)   14.733 19302.47(82)  -28.058(73) 
qmc.g001  11998.19(83)  182240(722)    15.189 14277.93(83)   58.865(88) 
qmc.g002   1832.86(37)   45647(268)    24.904  4292.51(43)   95.213(60) 
qmc.g003  -1642.42(01)      43.22(12)   0.026   911.97(16)  169.732(64) 
qmc.g004  -1642.43(01)      43.15(17)   0.026   911.73(12)  169.696(58) 
qmc.g005  -1642.43(01)      43.65(17)   0.026   912.04(22)  169.755(77) 
qmc.g006  -1642.43(01)      43.20(13)   0.026   911.78(16)  169.698(89) 
qmc.g007  -1642.47(01)      43.70(16)   0.026   912.07(16)  169.587(58) 
qmc.g008  -1642.46(01)      43.26(13)   0.026   912.06(19)  169.752(78) 
qmc.g009  -1642.50(01)      43.42(16)   0.026   912.04(14)  169.701(53) 
qmc.g010  -1642.46(01)      43.27(16)   0.026   912.10(14)  169.712(60) 
qmc.g011  -1642.53(01)      42.48(14)   0.025   910.98(16)  169.115(69) 
qmc.g012  -1642.53(01)      42.87(18)   0.026   910.99(12)  169.069(63) 
qmc.g013  -1642.51(01)      42.74(20)   0.026   911.41(13)  169.285(64) 
qmc.g014  -1642.54(01)      42.66(16)   0.026   910.99(13)  169.066(50) 
qmc.g015  -1642.54(01)      42.83(16)   0.026   910.88(13)  169.045(61) 
qmc.g016  -1642.52(01)      42.55(13)   0.025   910.97(19)  169.065(81) 
qmc.g017  -1642.51(01)      42.57(13)   0.025   910.78(16)  169.063(67) 
qmc.g018  -1642.53(01)      42.85(15)   0.026   911.04(16)  169.136(64) 
```

The root of the problem was identified at the orbital level by calculating the per orbital kinetic energies with the eshdf_mod python tool acting on the h5 orbital file created by pw2qmcpack (5.3.0).  For each of the three problem twists, a subset of the up orbitals (but not down) showed anomalously large kinetic energies (~100 Ha) while typical values (both here and in many other materials studied) were less than 7 Ha.  The first 25 out of 277 per orbital kinetic energies are shown below for the up and down channels of one problem twist (twist 0) and one non-problem twist (twist 4).  The specific orbitals (as ordered by KS eigenvalue) manifesting the problem vary from twist to twist.
```
      twist 0                twist 4
  up        down         up        down
  1.470304  1.473453     1.487776  1.490919
  1.479950  1.468546     1.497419  1.486005
  1.479503  1.462693     1.496974  1.480185
  1.478456  1.472071     1.495916  1.489527
  1.479472  1.472619     1.496903  1.490094
  1.477827  1.473012     1.495278  1.490419
  1.473747  1.470323     1.491169  1.487774
  1.477842  1.470448     1.495358  1.487913
  1.477816  1.469970     1.495244  1.487425
  1.477398  1.469257     1.494869  1.486708
  1.477663  1.470028     1.495106  1.487478
  1.471296  1.462544     1.488748  1.479996
  1.476725  1.467515     1.494179  1.484972
  1.475060  1.467204     1.492511  1.484656
  1.477380  1.469164     1.494834  1.486618
  1.475348  1.466361     1.492801  1.483815
 60.078338  2.693886     2.682154  2.711286
 95.765120  2.721288     2.717979  2.738885
100.563940  2.717462     2.751101  2.734961
106.665935  2.719877     2.744565  2.737331
135.226949  2.720652     2.745884  2.737665
112.038779  2.680695     2.707935  2.700469
 96.510487  2.718377     2.715706  2.735815
107.772343  2.716846     2.730897  2.735231
115.525116  2.715960     2.700849  2.734565
```

Correct per orbital kinetic energies agree closely across twists and across spin channels, leading to some of the recommended checks in #761.

Given that the DFT energies agree closely and the KE's do not, the problem/bug is very likely resident in pw2qmcpack itself.

Access to the raw input/output files of the runs described here is provided upon request (data resides on Eos at OLCF and Mira at ALCF).

The issue might be tracked down by rerunning pw2qmcpack (5.3.0) on the SCF output with sufficient monitoring/checking code inserted.  The buggy section of code in 5.3.0 is likely to be present in 6.2.1 and the patch can be applied forward.

**Comment by ye-luo** [comment]
After adding the norm check (after loading and before writing) in pw2qmcpack, I catch **nothing**.
Then I went to check the hdf5 library on EoS.
Jaron built QE with 1.8.14. I can reproduce the issue and the current qmcpack will stop due to wrong orbital norm.
Then I switched to 1.8.16. Everything goes fine.
```
$ qmca -q ev -e 5 *.scalar.dat
                            LocalEnergy               Variance           ratio 
qmc.g000  series 0  -1642.292033 +/- 0.031431   46.302886 +/- 0.507574   0.0282 
qmc.g001  series 0  -1642.389007 +/- 0.031634   44.225852 +/- 0.343456   0.0269 
qmc.g002  series 0  -1642.332400 +/- 0.031593   46.372948 +/- 0.512868   0.0282 
qmc.g003  series 0  -1642.411802 +/- 0.027953   43.104159 +/- 0.358453   0.0262 
qmc.g004  series 0  -1642.445330 +/- 0.027695   43.365788 +/- 0.374558   0.0264 
qmc.g005  series 0  -1642.413731 +/- 0.028494   43.128951 +/- 0.323674   0.0263 
qmc.g006  series 0  -1642.465815 +/- 0.026725   43.275634 +/- 0.335239   0.0263 
qmc.g007  series 0  -1642.502622 +/- 0.029978   43.352679 +/- 0.437195   0.0264 
qmc.g008  series 0  -1642.466392 +/- 0.037153   43.173871 +/- 0.369996   0.0263 
qmc.g009  series 0  -1642.444824 +/- 0.027187   43.399198 +/- 0.397494   0.0264 
qmc.g010  series 0  -1642.478098 +/- 0.035314   43.213327 +/- 0.409626   0.0263 
qmc.g011  series 0  -1642.530215 +/- 0.026411   42.846378 +/- 0.381500   0.0261 
qmc.g012  series 0  -1642.487845 +/- 0.023271   42.148928 +/- 0.268784   0.0257 
qmc.g013  series 0  -1642.533088 +/- 0.031279   42.846107 +/- 0.305724   0.0261 
qmc.g014  series 0  -1642.554519 +/- 0.031364   42.704338 +/- 0.303841   0.0260 
qmc.g015  series 0  -1642.504657 +/- 0.026028   42.528168 +/- 0.322438   0.0259 
qmc.g016  series 0  -1642.500618 +/- 0.025564   42.383356 +/- 0.318919   0.0258 
qmc.g017  series 0  -1642.504236 +/- 0.024886   42.607049 +/- 0.244987   0.0259 
qmc.g018  series 0  -1642.523180 +/- 0.024096   42.934537 +/- 0.368342   0.0261 
```

**Comment by jtkrogel** [comment]
It is a little unsettling that users can get poor results based on the minor version of hdf5 used, but it is good that such problems will now at least be caught.

**Comment by jtkrogel** [comment]
Should we decorate the pw2qmcpack/qmcpack orbital norm check error message with notifications to try different hdf versions?

**Comment by prckent** [comment]
Lets keep things simple and add to the error check message in QMCPACK. "This may indicate a problem with the HDF5 library versions used during wavefunction conversion or read".

**Comment by prckent** [comment]
@jtkrogel , @ye-luo  : Who of you will make the PR?

**Comment by ye-luo** [comment]
I will do. I need to update the QE patch and doc as well as QMCPACK notes together.
