### ISSUE TITLE
billmp1 nightly AppleClang tests are not pulling from GitHub

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#79]
The changes to the optimizer tests are not propagated to the tests last night.

**Comment by prckent** [comment]
Good point. Mark's scripts will need updating to pull from GitHub.

Mark: See tests/test_automation for some examples.

**Comment by prckent** [comment]
Mark has stopped the runs, but it would be good to have them resume with the GitHub code

**Comment by prckent** [comment]
Safe to close. If someone has a spare up to date Mac we can resume tests on OS X.
