### ISSUE TITLE
Tests needed for qmca

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#792]
Since qmca is a user-facing tool, it is desirable to have tests in place to verify its correct operation under known use cases and avoid bugs such as #791.

**Comment by markdewing** [comment]
Two kinds of tests:
1. Internal (unit tests).  This could be provided by the test framework for other parts of nexus in #760
2. External (system tests). Use qmca as from the command line and check the output
     These could go in nexus/tests/executables ?

     For these tests, it might also be useful to have a csv output option to  make parsing qmca output easier

**Comment by jtkrogel** [comment]
Addressed by #2091.
