### ISSUE TITLE
The (automatic) code format

### ISSUE THREAD

**Issue by grahamlopez** [QMCPACK/qmcpack#794]
It would help to move to automated source code formatting. Some candidate examples are available at https://github.com/qmcpack/src-formatting; more explanation of these examples are in the readme for that repo.

Note that the formatter can be turned off inside the source by enclosing regions with appropriate comments (`// clang-format off/on`). I didn't search for everywhere this will be needed; I think we can pick them up as people run into them. We probably want try to minimize how often we use that feature (e.g. only for arrays/matrices of constants), as it adds to maintenance overhead and erodes the advantage of automation.

Let's use this issue thread to discuss which of these formats we would like to use, and any ways to tweak them.

**Comment by prckent** [comment]
My vote is for custom. I find the placement of the opening and closing {} helpful to scan the logical flow of the code.

**Comment by jtkrogel** [comment]
My main issue with all the current options is that they make heavy math illegible.

Compare for the following files:
./src/einspline/multi_bspline_eval_d_std3.cpp
./src/einspline/nubspline_eval_d_std.cpp
./src/QMCWaveFunctions/Fermion/BFsplineFunctor.h
./src/QMCWaveFunctions/Jastrow/eeI_Jastrow

Spaces before and after */,< is excessive and the line wrap cutoff could be extended.  Note that even the original code is not ideal on math presentation as it was passed through another auto-formatter on 25 Apr 2013.

Perhaps some of this can be addressed with additional customization?

**Comment by jtkrogel** [comment]
Good to know that this can be selectively applied.  Perhaps adjusting the rules also will help (favoring more compact math).  There will be many cases that I don't have time to find that will/could be handled poorly.  I suggest instead that we shape the rules to render the above files (and others we find) well so that we can apply the formatter to the whole of the code without concern.

Overall, I would strongly prefer to not introduce spaces before/after */,<.  I might also add +- to this list as sometimes spaces help, but often they hinder readability by expanding e.g. for loop declarations a lot.  These cases could be handled manually (less space in for loop decls, more space in full math expressions) for readability if an auto-tool cannot be customized enough.

**Comment by jtkrogel** [comment]
Last time the code formatting was performed by using astyle: [http://astyle.sourceforge.net/](http://astyle.sourceforge.net/)

**Comment by jtkrogel** [comment]
Presumably this would render the files listed above sufficiently well.

**Comment by jtkrogel** [comment]
> I suggest that we just fix these as we encounter them after the fact

Anything that takes additional time will tend not to be done and so we will just be left with more illegible code.

Since we are planning to apply this to all incoming code and at least most existing code, I suggest we set the rules once and then apply it uniformly.

As far as what those rules are (style guide) we are not likely to get agreement, but my prior comments on spacing, etc, represent my vote.

**Comment by prckent** [comment]
Please make comments by Friday

**Comment by markdewing** [comment]
This seems small, but it bothers me how the formatting changes the license header
```
// This file is distributed under the University of Illinois/NCSA Open Source
// License.
```
  ^---- The original line is 86 characters long, and the trailing 'License' gets moved to a new line. (So lonely on the line by itself!)
Are we dedicated to an 80 character limit? If we did 90 or 100 characters, this line would be okay. (But maybe a character limit discussion  will open a can of worms?)

Also, the formats don't indent the wrapped line following 'File developed by:'
```
// File developed by: Ken Esler, kpesler@gmail.com, University of Illinois at
// Urbana-Champaign
//                    Luke Shulenburger, lshulen@sandia.gov, Sandia National
//                    Laboratories
```
Plus the character limit winds up wrapping almost every attribution line.  This wouldn't be so bad if the entire institution were on a second line, but it's usually just the last part of the name.

Increasing the character width would allow most (but not all) of these to stay on one line.
Another option is to change how we write these: put the 'File developed by:' on one line and start the list of names on the next line
```
// File developed by:
//   Ken Esler, kpesler@gmail.com, University of Illinois at Urbana-Champaign
//   Luke Shulenburger, lshulen@sandia.gov, Sandia National Laboratories
```

**Comment by PDoakORNL** [comment]
We should move beyond narrow source code, I think we should go to at least 100 if not 120, I had 80 columns on my Apple II+ in the mid 80's. Most of us work on large monitors and use editors that can handle long lines according to developer preference.

I'm skeptical of the IncludeSorting, while this is nice in principle sometimes order can matter and when it does this creates a maintenance overhead.

I really don't care for AlignConsecutiveAssignments its rather precious and is annoying if you need to change something with a stripped down editor. When the assigments don't have semantic relation to each other it is also confusing. If it helps a particular author I'm fine with it being used in a limited fashion, but I don't want it done automatically.

My votes start with Custom and make these changes:
**pointeralignment**:left
**AlignConsecutiveAssignments**:false
**AlignOperands**:false
**AllowShortBlocksOnASingleLine**:true
**AllowShortCaseLabelsOnASingleLine**:false
**ConstructorInitializerAllOnOneLineOrOnePerLine**:true
**ConstructorInitializerIndentWidth**: 4
**ContinuationIndentWidth**: 4
**ColumnLimit**: 120
**IndentWrappedFunctionNames**: true
**MaxEmptyLinesToKeep**: 2

**Comment by ye-luo** [comment]
How about format a folder and make a PR and then we comment on the things we don’t like.

**Comment by ye-luo** [comment]
I tried `.clang-format` out of the qmcpack/src-formatting repo and got
```
YAML:94:22: error: unknown key 'Delimiter'
  - Delimiter:       pb
                     ^~
Error reading /sandbox/opt/src-formatting/.clang-format: Invalid argument
```

**Comment by prckent** [comment]
Works for me with clang-format v6.0. 

@ye-luo , @PDoakORNL  Good suggestion on the PR.

**Comment by grahamlopez** [comment]
RE: line length limits:
1) using this to fix the file headers (comments) would be overkill, since could/should be changed anyway (not necessarily part of this initial formatting effort).
2) Pasting in some of my previous comments about line lengths from when this was discussed on miniqmc:

>  I personally very much like 80 characters. On the current 28" monitor I'm using, I have one web browser open for GitHub/google/docs, two terminals for code (so that I can edit one part of the code while looking at another part for reference to the interface), and one more terminal for compiling/testing/grepping so that I can see the errors and output at the same time as the code. With this scheme, 80c terminals are barely narrow enough to fit while still rendering everything in a readable way.

> This is just one example. Some people need to use larger fonts. Some IDEs take up horizontal space with built-in file browsers, debuggers, and other tools. Windows can be alt+tab'ed, but these milliseconds added up can become distracting if you are mostly reading from one spot and working in another.

> Another smaller issue with the 80c subject is external tools. Some email clients, web pages (think wikis), etc. will automatically wrap at 80. So if code gets copy/pasted into these places a lot, it can make things easier to read.

(We found this to be true in the GItHub web interface when reviewing and commenting on code: e.g. lines longer than 80c cause a horizontal scrollbar to be generated.)

> Some people claim narrower code can be read more quickly because you don't have to scan your eyes side to side as much. Wider code will have lines that vary in length more, resulting in more blank screen and less code able to be displayed per screen.

**Comment by grahamlopez** [comment]
@PDoakORNL 
You are correct that include sorting can possibly break the code, and I think I remember that it does, for QMCPACK. So we will likely need to turn it off. 
HOWEVER, the fact that include order matters is a symptom of having cyclic and/or hidden include dependencies, and so we should strive to be able to turn it on because we'd want that issue fixed anyway. I have found that having alphabetically-sorted includes is non-trivially nice when the include list grows beyond just a few (quicker to scan the list than search the filename). I admit this is a minor thing, but I still think we should try to fix up the fragility of the current include situation.

**Comment by jtkrogel** [comment]
On the longer lines vs. shorter lines issue:  even if the line limit is increased, I fully expect most code written will naturally have 80c or shorter lines due to the nature of the code and so a short line limit does not need to be enforced.  Most of the codebase is like this already.  When longer lines are used in the codebase it appears to be consciously done for readability.  Therefore I think we should be generous in the line limit since most code will naturally be 80c or less.

On a different note, I vote for aligned consecutive assignments.

**Comment by prckent** [comment]
We will do this immediately after the next release v3.6.0, i.e. just after 12 Dec if the release schedule holds. Outstanding PRs and branches in forks will need to be updated.

**Comment by prckent** [comment]
We need to pick which version of clang-format to use. clang is easy to install but we should minimize barriers for contributions. e.g. Ubuntu 18.04 LTS has clang 6.

**Comment by markdewing** [comment]
Did we ever discuss which directories will be affected - my thought is everything in src/ should be formatted.  Anything that shouldn't be?
And code elsewhere (especially external_codes) would not be affected by formatting rules.

**Comment by PDoakORNL** [comment]
It was my belief that we resolved it to be just src

**Comment by prckent** [comment]
src only

**Comment by markdewing** [comment]
The code in src/formic should probably not be formatted, since it comes externally.

**Comment by prckent** [comment]
@PDoakORNL What remains to be formatted? Can this issue be closed? (We should add a formatting step to the release procedure from now on. Anything else? )
