### ISSUE TITLE
Experimental code still needed?

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#795]
I want to delete the following folders with its source files inside. They are not needed for compilation at all. From the file names inside, I basically see them copied from old files many years ago.

qmcpack/src$ find -name Experimental
./QMCHamiltonians/Experimental
./LongRange/Experimental
./Particle/Experimental
./QMCWaveFunctions/Experimental
./QMCWaveFunctions/Jastrow/Experimental
./QMCDrivers/Experimental
./Estimators/Experimental

**Comment by prckent** [comment]
Unless anyone champions these files, we should delete them. It is a similar story to the old sandbox files.

**Comment by jtkrogel** [comment]
These should be deleted.
