### ISSUE TITLE
Born effective charge

### ISSUE THREAD

**Issue by ragch577** [QMCPACK/qmcpack#801]
Hi,

I would like to calculate Born effective charges at DMC calculations. Is it possible to access the ionic valence on each ionic sites?

Thanks,
Raghuveer Chimata

**Comment by prckent** [comment]
Good question. We can calculate the electronic charge density e.g. as in https://journals.aps.org/prmaterials/abstract/10.1103/PhysRevMaterials.1.065408 . You may be able to infer changes in valence from this - I suggest checking DFT results for your system first.

Computation of electronic polarization is a research topic.
