### ISSUE TITLE
Status/future of Stress files

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#813]
I noticed recently that several of the Stress files are never included/built in QMCPACK.

@rcclay are the below to be expanded/completed later, or have they been superseded by StressPBC.* (and can therefore be removed):

```
StressKinetic.cpp  StressPBCAA.cpp  StressPBCAB.cpp  
StressKinetic.h    StressPBCAA.h    StressPBCAB.h    

```

**Comment by rcclay** [comment]
I believe those have been superceded by StressPBC, but before that becomes an advertised and tested observable, I would like to keep these around for debugging purposes.
