### ISSUE TITLE
Status of MultiDiracDeterminantWithBackflow

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#826]
MultiDiracDeterminantWithBackflow.cpp was identified as a dangling (unbuilt) file during automated searches for dead code.  What is the status of this code/should it be kept?  Is there any functionality here that is not covered in MultiSlaterDeterminantWithBackflow?

**Comment by ye-luo** [comment]
It seems out-of-date and all the routines have a linked copy in MultiDiracDeterminantBase.cpp and MultiDiracDeterminantBase.2.cpp

**Comment by prckent** [comment]
Note: We are recently using the backflow functionality, but with single determinants. Use of mutlideterminants with backflow is a proven improvement. Does MultiSlaterDeterminantWithBackflow work?

**Comment by mmorale3** [comment]
This was an initial (incomplete) attempt to implement the Woodbury formula for fast updates on top of backflow. Many years ago, I worked out how to do it for the gradient but not for the laplacian, so I never finished it. 

Miguel

**Comment by ye-luo** [comment]
As far as I know, now we have the following classes.
MultiSlaterDeterminant: dummy implementation directly creating N determinants
MultiSlaterDeterminantWithBackflow: the previous one + backflow
MultiSlaterDeterminantFast: the table method.
MultiDiracDeterminantBase: operates at single det level to provide calculations for the above three.

MultiSlaterDeterminantFast is the main one used to MSD. Probably MultiSlaterDeterminant can perform but slower. MultiSlaterDeterminantWithBackflow carries all the character of MultiSlaterDeterminant.

To move forward, I think we need to add Backflow on top of the fast algorithm and remove the dummy ones. On the other hand, backflow can be largely improved by itself, I saw similar problems like the AoS Jastrow in the backflow. So I think first, we improve the backflow on single det and then bring it to the fast multidet class.

**Comment by prckent** [comment]
It might be useful to have a slow (traditional) multiple determinant implementation available too. 

This is well defined topic that will need investigating as we learn about the effectiveness (cost, accuracy) of different ways to improve the nodal surfaces.

**Comment by ye-luo** [comment]
Tests are requested by #844
