### ISSUE TITLE
Status/future of AGP

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#827]
AGP code was implemented in 2007 including an Antisymmetrized Geminal Power fermionic part and a three-body Geminal Jastrow.  The Geminal Jastrow is eq 10 from Casula and Sorella J. Chem. Phys. 121, 7110 (2004).  See #652 for more detailed discussion.

Inputs and a reference output energy exist for this wavefunction (benzene) from the 2007 summer school.  The code builds and (at least with an older version of qmcpack) runs up until a changed wavefunction API function is reached.

Do we want to keep this around and revive or do we want to remove it with potential reimplementation from scratch down the road?

**Comment by ye-luo** [comment]
If they are still built, just keep them.

AGP is cheaper than MSD. There is potential use.
Cleaning them up is easier than from scratch. Fixing it should be simple.
For the moment, I prefer to move it to Fermion subfolder.

Geminal J3. Consider we don't have optimization capability and the cost may be high, it may be not worth to carry on.

**Comment by jtkrogel** [comment]
Geminal J3 has been removed (#839) and AGP has been kept.
