### ISSUE TITLE
Manual versioning

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#828]
Currently, we only provide the manual nightly built from the development branch.
For users stick to released versions, there may be an inconsistency.
So we need to provide the manual for the latest release.

- [x] add version printing in the manual.
- [x] update the release process to include a step generating a manual shapshot for the release.

**Comment by prckent** [comment]
We'll have this shortly after #887

**Comment by prckent** [comment]
Wiki updated. v3.5.0 will be the first live run of this process with versioned PDFs. In future HTML will be added.
