### ISSUE TITLE
Update minimum CMake version from 2.8.10

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#832]
There is a tension with the minimum CMake version required - supporting older versions makes it easier for users, but moving to newer versions makes life easier for developers. 
 This issue is to gather some information on what versions would help developers, and which versions are easily accessible on various platforms.

The current minimum required is 2.8.10, with some additional unit tests enabled for versions > 2.8.11

CMake 3.1 introduces the CMAKE_CXX_STANDARD and CMAKE_CXX_STANDARD_REQUIRED, which should set the flags on the compilers properly, and the existing c++11 flag checking could be removed.

A more modern approach to CMake organization uses target_* commands.  The target_source command was added in CMake 3.1.  I don't know if there are subsequent additions in later CMake versions to better support this style of organization.

**Comment by prckent** [comment]
Someone using creaky machines will have to admit their minimum (maximum?) CMake version. CMake is generally trivial to install, so I am happy to move to (say) 3.1. As with (say) our QE support it would be good to define a policy if possible.

**Comment by prckent** [comment]
No replies yet. Seems like it would be safe to require cmake 3. Package managers have it and the HPC centers have it....

**Comment by prckent** [comment]
We have been using 3.6.3 on oxygen since 9/2016. Unless anyone chirps up by the 9th, when this issue will have been up for a week, lets make 3.6.0 the minimum version.

**Comment by ye-luo** [comment]
ALCF Mira has 3.8.1 and Theta has 3.9.1.
