### ISSUE TITLE
Clean manual and tutorial files of historical and now removed functionality

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#841]
After the current major cleanup is over we should tidy the manual appropriately, either removing references or reducing references to mention features that were included but unsupported before v3.5. The tutorial files should also be checked over e.g. #824

**Comment by jtkrogel** [comment]
Agreed.  Should this be a milestone for release version 3.5?

**Comment by jtkrogel** [comment]
When are we aiming to release v3.5.0?
