### ISSUE TITLE
Considering making C++14 a requirement 

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#846]
We would like to move to C++14 for the entire application due to many enhanced language and library features. This requires use of a sufficiently capable compiler, e.g. GCC 5.1 released in 2015 ( http://en.cppreference.com/w/cpp/compiler_support ). All HPC centers should be up to date, but individual workstations might need updated software. The QMCPACK spack package is a potential workaround in this case.

Please comment within a week of this posting if this requirement would be a problem.

**Comment by jtkrogel** [comment]
C++ 14 was not fully supported by the Intel C++ compiler until version17.0 (released Sept. 2016).  

I suggest we make a decision about a support window (i.e. consciously break user's ability to compile QMCPACK on machines X years old or older) and stick to it.  

In the current proposal, X is about 1.5 years.

**Comment by prckent** [comment]
I agree about a general guide for a support window, but I think what is more important is that we can provide a viable compilation route for the user. In a speculative future scenario where one vendor is laggardly we do not wish to be constrained by them. e.g. The compilation route could be clang or gcc.

Note that Intel compilers are free for several categories of non-commercial use https://software.intel.com/en-us/qualify-for-free-software

**Comment by jtkrogel** [comment]
I think the support window and the viable route are the same since it is not uncommon for users to have no control over the machine environment.

IMO we should be somewhat conservative here since restricting usership hurts us and those who do not choose us are most likely to never inform us of that choice.    

Probably we are currently committed to supporting intel, gcc, and clang builds.  I don't know what the best choice is for X.

**Comment by jtkrogel** [comment]
To be clear, I am fine with proceeding as is if others think it is a good idea.

**Comment by prckent** [comment]
Just for the record, I investigated using spack to get a modern C++ compiler and install QMCPACK on a dusty workstation with only gcc 4.4. Spack needed a few hints due to missing dependencies for cmake and for problems with fftw, but the eventual process is simple:

```
cd $HOME/apps # Pick a location for spack directory
git clone https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh
spack bootstrap
emacs -nw ~/.bashrc #Add the following two lines, adjusting for spack location

export SPACK_ROOT=$HOME/apps/spack
. $SPACK_ROOT/share/spack/setup-env.sh

module list # Modules should be working
spack install gcc@7.3.0
spack load gcc@7.3.0
spack compiler find
# Should print similar to:
#==> Added 1 new compiler to /home/pk7/.spack/linux/compilers.yaml
#    gcc@7.3.0
#==> Compilers are defined in the following files:
#    /home/pk7/.spack/linux/compilers.yaml


spack install qmcpack # Does not work since cmake build fails due to missing C++11 compiler capability (gcc 4.4 installed on psi3)
spack install qmcpack %gcc@7.3.0 # Fails with fftw problems but would probably work on a more recent CPU:

>> 3035    /tmp/ccswGOIV.s:3462: Error: no such instruction: `vpermpd $177,%ymm0,%ymm0'
>> 3036    /tmp/ccswGOIV.s:3472: Error: no such instruction: `vpermpd $177,%ymm8,%ymm8'
>> 3037    /tmp/ccswGOIV.s:3488: Error: no such instruction: `vpermpd $177,%ymm0,%ymm0'
>> 3038    /tmp/ccswGOIV.s:3493: Error: no such instruction: `vpermpd $177,%ymm3,%ymm3'
>> 3039    make[5]: *** [n1fv_128.lo] Error 1
      3040    make[5]: Leaving directory `/tmp/pk7/spack-stage/spack-stage-Y9WpRL/fftw-3.3.7/double/dft/simd/avx2'
>> 3041    make[4]: *** [all] Error 2
      3042    make[4]: Leaving directory `/tmp/pk7/spack-stage/spack-stage-Y9WpRL/fftw-3.3.7/double/dft/simd/avx2'
>> 3043    make[3]: *** [all-recursive] Error 1
      3044    make[3]: Leaving directory `/tmp/pk7/spack-stage/spack-stage-Y9WpRL/fftw-3.3.7/double/dft/simd'
>> 3045    make[2]: *** [all-recursive] Error 1
      3046    make[2]: Leaving directory `/tmp/pk7/spack-stage/spack-stage-Y9WpRL/fftw-3.3.7/double/dft'
>> 3047    make[1]: *** [all-recursive] Error 1
      3048    make[1]: Leaving directory `/tmp/pk7/spack-stage/spack-stage-Y9WpRL/fftw-3.3.7/double'
>> 3049    make: *** [all] Error 2

See build log for details:
  /home/pk7/apps/spack/var/spack/stage/fftw-3.3.7-3nmyhzjkhz26z76teigspg3j6eb65njh/fftw-3.3.7/spack-build.out

Working solution:

spack install qmcpack %gcc@7.3.0 ^fftw@3.3.7 simd=sse2
# Manually specify the vectorization that the system is capable of via simd option
# "spack info fftw" shows options for this package.
# Note: QMCPACK does not require a highly performant FFT. No major need to optimize simd= option.
```
I did not investigate QE on this machine yet.

**Comment by ye-luo** [comment]
C++14 is now required since #1135
