### ISSUE TITLE
Checking pseudo charge breaks CASINO pseudopotential read

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#865]
Guard introduced in #529 breaks QMCPACK's ability to read potentials from CASINO's native *.data format.  This bug was uncovered by running a Nexus example (LiH.py) involving CASINO potentials.

The checking code erroneously attributes a charge of "0" to the H pseudopotential, resulting in the following message and abort:
```
ERROR   Ion species H atomicnumber 1 pseudopotential atomic-number 0 mismatch!
ERROR  Failed to add pseudopotential for element H
Fatal Error. Aborting at ECPotentialBuilder::useXmlFormat failed!
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
This bug affects releases 3.3.0 and beyond; I confirmed that 3.2.0 works properly.

**Comment by prckent** [comment]
If we are value this ability (and I think we do), first thing to do is add a test. 

It would be wonderful if we had unit test(s) that read potentials (XML and casino_pp.data)
