### ISSUE TITLE
Can we make the default precision the same for the CPU and GPU builds?

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#869]
Is there any reason to not make the default precision the same, i.e. mixed CPU & GPU? Currently we build double for CPU and mixed on GPU, reflecting the history of these implementations.

This question also encapsulates questions about the expectations we have of users. e.g. The mixed precision code will get the wrong result for a large enough system.

**Comment by ye-luo** [comment]
CPU mixed precision is not feature complete currently.
It is known that MP has issue with multi dets and also optimization has some issue.

**Comment by ye-luo** [comment]
I somehow feel it is not pragmatic to let users looking at cdash what does and does not work. We need to provide a feature table just like the c++ language feature complete list for different compilers.

**Comment by jtkrogel** [comment]
I agree about the feature table (in the manual).  Probably should have its own issue to outline what this should look like.  Probably someone should run a cartesian product of functionalities and map all the explicit breakages.

I'm also in favor of making issues (if not there already) for currently known deficiencies like the couple noted above for MP.

**Comment by prckent** [comment]
I agree on the feature table also.

**Comment by prckent** [comment]
Closing. The answer is "No, not yet fully implemented" and "we need a feature table" #870
