### ISSUE TITLE
Wrong MKL fftw include path with intel compiler

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#881]
PR#876 The change from "fftw/fftw3.h" to "fftw3.h" in FindMKL is wrong. The reason of passing on certain machines is the existence of /usr/include/fftw3.h.
We have two options
1, add explict include path MKL/include/fftw
2, revert to the old way just creating a fake fftw.h in build/include.

**Comment by prckent** [comment]
@ye-luo Did you notice this on one of your own machines, or is this happening in any of the nightly builds on cdash? If so we might want to remove/move /usr/include/ffw3.h.

My vote is for option 1, which tackles the problem directly.

**Comment by ye-luo** [comment]
Theta, EoS both failed.
https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=23701
"remove/move /usr/include/ffw3.h" is not possible. It appears when user installed fftw from package manager and it needs root.
In option 1, we need to search for MKL path even if we use -mkl with intel compiler. -mkl can't assume you want intel fftw so it doesn't add the intel mkl fftw include path automatically for you.

**Comment by prckent** [comment]
(I wrote it backwards: add a /usr/include/fftw3.h on oxygen via a package manager to improve testing. e.g. we only test eos weekly)

**Comment by ye-luo** [comment]
Then the logic becomes ill. It uses the header files from fftw library and link library with intel. I feel this dangerous.

**Comment by PDoakORNL** [comment]
I think this can be fixed properly, give me half an hour before we revert.

**Comment by PDoakORNL** [comment]
Ok here is what I've done.
If ENABLE_MKL=1 intel or not
${MKL_ROOT}/include is added to the root directory include_directories property. Every entity added at or below this directory inherits these include directories.  This was how mkl for non intel already worked.

Then cmake checks for mkl/fftw/fftw3.h
if it finds it, then it adds $MKL_ROOT/include/fftw to the include_directories
on intel mkl linking is still handled implicitly

Is there ever a case when we want mkl but not the mkl fftw?

**Comment by prckent** [comment]
MKL but no MKL FFTW: I think no. It is also such an edge case that we can tackle it later if ever needed.

**Comment by prckent** [comment]
Do we catch MKL_ROOT not set?

**Comment by ye-luo** [comment]
MKL but no MKL FFTW: I also think no.
I remember there are several flavour of MKL_ROOT MKLROOT MKL_HOME...
