### ISSUE TITLE
Manual does not build on Ubuntu 16.04 (Tex Live 2015)

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#888]
It stops with  'LaTex Error: Unknown graphics extension: .eps.'
when including LPQHI.eps in design_features.tex

Two possible solutions:
1. Include an additional package epstopdf
2. Convert LPQHI.eps to pdf.  It's the only EPS figure, and the epsfig package include could be removed.

I think the second would be preferable because it simplifies the manual source.

**Comment by markdewing** [comment]
Adding the pdfoutput line does not fix the problem.

**Comment by PDoakORNL** [comment]
This works now correct?  at least in #887 ?

**Comment by jtkrogel** [comment]
@markdewing is this resolved now?

**Comment by ye-luo** [comment]
@jtkrogel It builds now.

**Comment by prckent** [comment]
Good that it builds. (TeX Live 2017 is our official minimum requirement now.)
