### ISSUE TITLE
Make Nexus manual available online

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#889]
Include the Nexus manual in the nightly pdf and html manual builds and include links to both on the main qmcpack.org website.  The current static manual pdf can then be removed from the repo.

**Comment by jtkrogel** [comment]
Is this issue for v3.5.0 or v3.6.0?

**Comment by prckent** [comment]
I tried compiling with TeX Live 2017 (pdflatex nexus_user_guide.tex), I believe full install, and ran into issues with package availability. What do you suggest?


```
Package ifplatform Warning:
    shell escape is disabled, so I can only detect \ifwindows.

))

! Package minted Error: You must invoke LaTeX with the -shell-escape flag.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.27

?

! Package minted Error: You must have `pygmentize' installed to use this package.

See the minted package documentation for explanation.
```

**Comment by prckent** [comment]
The PDF version can be automated as soon as I can build the Nexus manual with Tex Live 2017 (this is what is installed in the VM). HTML will take longer - we are exploring upgrading the VM to get to TeX Live 2018 and newer packages, easier installs etc. All the necessary tools for HTML production do not run currently.

**Comment by jtkrogel** [comment]
This is the process I've used (from the header to nexus_user_guide.tex):

% to use minted
%   install the pygments package for python
%   sudo apt-get install python-pygments
%   get the style file, minted.sty
%     http://code.google.com/p/minted/downloads/detail?name=minted.sty
%   running pdflatex:
%     pdflatex -shell-escape nexus_user_guide.tex

Checking on minted status.

**Comment by prckent** [comment]
I misread the error as TeX package availability. Sadly "python-pygments-1.1.1-2.el6.noarch already installed and latest version", so some debugging will be needed. Presumably a path or python setup.

**Comment by jtkrogel** [comment]
OK, still alive beyond google code:

[https://ctan.org/pkg/minted?lang=en](https://ctan.org/pkg/minted?lang=en)
[https://github.com/gpoore/minted](https://github.com/gpoore/minted)

**Comment by jtkrogel** [comment]
Same error with this?

pdflatex -shell-escape nexus_user_guide.tex

**Comment by prckent** [comment]
What benefit are we getting from these packages? It violates our new "TeX Live 2017" rule for the main QMCPACK manual and means custom installs will be needed. Perhaps the rule will need changing, but I would prefer not for the same reasons we established it. e.g. It discourages contributions. Is there another way of getting the same functionality?

**Comment by jtkrogel** [comment]
It enables syntax highlighting (via color and style) of Python and other programming languages.  IMO much more readable than verbatim.  See e.g. the included Nexus file near the top of section 5.1 in the pdf.

I like this feature; possibly similar functionality is available now without pygmentize, but I will have to look.

**Comment by jtkrogel** [comment]
Trying to get something decent out of the listings package now.

**Comment by prckent** [comment]
This is working with an installed python pygmentize and TeX Live 2017. Avoiding the pygmentize dependency would be nice if the listings package is similarly capable. However I think we can live with it. HTML output will happen when we the QMCPACK manual HTML generation is automated.
