### ISSUE TITLE
ppconvert hangs indefinitely on solve

### ISSUE THREAD

**Issue by camelto2** [QMCPACK/qmcpack#891]
After compiling with the new additions to ppconvert using -DBUILD_PPCONVERT=1 and make ppconvert, ppconvert seems to hang indefinitely on converting any potential. As an example, simply running the example in the manual for the Oxygen BFD ECP in gamess format hangs indefinitely with the output

Atomic symbol = O
PseudoCharge = 6
lmax = 1
Finished reading GAMESS pseudopotential.
Solving atom for reference state 1s(2)2p(4):

and it never actually starts solving for the reference states. An executable prior to the recent changes works fine

**Comment by ye-luo** [comment]
I noticed similar things on my AMD box with gnu compiler. Which compiler do you use?

**Comment by ye-luo** [comment]
What is the new addition you referred to?

**Comment by camelto2** [comment]
This was a gnu compiler as well. I was just referring to the changes you made to include the density_mix as well as adding the option to compiler ppconvert using -DBUILD_PPCONVERT and make ppconvert as opposed to having to manually compiler yourself. My previous executable prior to those changes works fine with the gnu compilers. However, compiling as described in the manual now results in it hanging

**Comment by mcbennet** [comment]
Just to add to the investigation. This looks to not be a problem if compiled with intel compilers -- which I just tested.

**Comment by prckent** [comment]
I believe that this has been solved in develop. Will reopen if not.

**Comment by ye-luo** [comment]
Fixed by #1403
