### ISSUE TITLE
Prioritization of GitHub issues

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#906]
We have accumulated quite a large number of GitHub issues (which imbues some irony upon the current discussion, but so be it).  Further growth of the list without some kind or prioritization likely will lead to development paralysis and/or inefficiency w.r.t. diminishing the issue list.

I suggest we somewhere rank the issues by priority so that intermittent efforts aimed at killing issues will be both encouraged and well spent because what is most useful is known.

**Comment by prckent** [comment]
If we have enough issues (150, 250, 550?) then we will need to do something. If we get better at closing issues, this could be delayed indefinitely :-) 

From my perspective the most important issues are the ones we need for the next release at https://github.com/QMCPACK/qmcpack/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22V3.5.0+release%22  A v3.6.0 milestone also exists to assign important issues to. This doesn't solve the overall prioritization issue though.

As regards picking issues to work on and prioritization, yes it would be useful to have a priorities assigned. The ability to vote on issues would also help. However there is also the complexity of the task to consider. For anyone looking to hack on an issue, e.g. on a "rainy Friday afternoon", it would be helpful if people asked before picking. e.g. "I am thinking of working on X, any better suggestions?". For example it would be great to have the output cleanup issues tackled...

Any suggestions from anyone else? How much of a problem is this perceived to be ?

**Comment by ye-luo** [comment]
Having a certain amount of issues are fine as long as they are not bugs. For bugs, I'd like to put a 2 week limit. Associating issues with milestones and release should be a good strategy to eliminate them.

**Comment by jtkrogel** [comment]
I agree that attaching a layer of higher priority issues to each release is a good idea.  If done consistently, this could be enough to whittle down the pile on its own.

**Comment by prckent** [comment]
Two week limit on bugs, hmm:

https://github.com/QMCPACK/qmcpack/labels/bug

We have 32 issues tagged as bugs. Some are limitations that we don't error trap, some might be completed and closable, and some are feature requests. But some are bugs.

I agree with @ye-luo that we should proactively attach these to GitHub release milestones and get them fixed.

**Comment by jtkrogel** [comment]
In practice, the limit for action seems to be 300 :-)

**Comment by PDoakORNL** [comment]
We can of course recategorize bugs to features right?
