### ISSUE TITLE
Skip unimplemented features in PySCF/molecular related AoS test

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#919]
There are a few some running in the AoS code where we have no intention of ever supporting a particular feature. 

e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=2646497&build=25212
 short-LiH_dimer_ae_pyscf-vmc_hf_noj-1-16 

We should skip these tests.

**Comment by ye-luo** [comment]
We have two tests for pyscf LiH and FeCO3. One was testing failure and one was skipping the test.
In #918, align them both to test failure. I think it is better than directly skipping the tests.

**Comment by prckent** [comment]
OK, I'll close this.
