### ISSUE TITLE
HTML version of current manual needed

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#92]
The current manual is only available in PDF. People may find the old online documentation which is now outdated, particularly some of the configure options and descriptions of how to get the code.

Making HTML will entail updating the LaTeX source so that it converts well.

Updating the website also needs to be automated.

**Comment by prckent** [comment]
h2latex works for the initial conversion, but readability is poor. Title graphic, figures and tables are not formatted at a sensible size or in some cases correctly.

**Comment by ye-luo** [comment]
@prckent Close?

**Comment by prckent** [comment]
Solved by https://qmcpack.readthedocs.io/en/develop/
