### ISSUE TITLE
RCSfile footers are not maintained

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#94]
How are we going to do will the following file footer?
/***************************************************************************
 * $RCSfile$   $Author$
 * $Revision$   $Date$
 * $Id$
 ***************************************************************************/
When I looked at a recent pull request, I noticed these lines are not well maintained in general.

**Comment by markdewing** [comment]
In my opinion, the RCS file tags should be removed.

**Comment by jngkim** [comment]
Remove it.

**Comment by ye-luo** [comment]
I agree. Please do it after the merge of GPU changes.

**Comment by prckent** [comment]
After the 3.0.0 release
