### ISSUE TITLE
Unit test failing on BGQ

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#941]
From last night,
test_unit_spline2 fails with mixed precision build and hangs with full precision build.
https://cdash.qmcpack.org/CDash/testDetails.php?test=2803958&build=26247
test_particle has kc = nan
https://cdash.qmcpack.org/CDash/testDetails.php?test=2803962&build=26247

**Comment by ye-luo** [comment]
@markdewing Will you have time to have a look at the spline2 since you created it?

**Comment by markdewing** [comment]
Yes, I can look at it.
