### ISSUE TITLE
Documentation on evaluate* methods in SPOSet

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#942]
There are 15 evaluate* methods in SPOSet(old class name SPOSetBase).    What differentiates them?  How are they used in the code (NLPP, backflow, etc)?   One (evaluateVGL) uses an SoA container for VGL, so presumably that's one that should be used in new SoA code.   Are there are others that should be deprecated (used only in AoS code)?

From an implementation view, there four pure virtual functions that must be implemented by any derived class
```
1 evaluate(const ParticleSet& P, int iat, ValueVector_t& psi) = 0;

2 evaluate(const ParticleSet& P, int iat,
           ValueVector_t& psi, GradVector_t& dpsi, ValueVector_t& d2psi)=0;

3 evaluate(const ParticleSet& P, int iat,
           ValueVector_t& psi, GradVector_t& dpsi, HessVector_t& grad_grad_psi)=0;

4 evaluate_notranspose(const ParticleSet& P, int first, int last
                                    , ValueMatrix_t& logdet, GradMatrix_t& dlogdet, ValueMatrix_t& d2logdet)=0;

```

Other functions throw an error or abort if they are not overridden
```
5 evaluate (const ParticleSet& P, PosType &r, ValueVector_t &psi)

6 evaluateVGL(const ParticleSet& P, int iat, VGLVector_t& vgl, bool newp)

7 evaluateThirdDeriv(const ParticleSet& P, int first, int last,
                                    GGGMatrix_t& grad_grad_grad_logdet)

8 evaluate_notranspose(const ParticleSet& P, int first, int last
                                      , ValueMatrix_t& logdet, GradMatrix_t& dlogdet, HessMatrix_t& grad_grad_logdet)

9 evaluate_notranspose(const ParticleSet& P, int first, int last,
                                      ValueMatrix_t& logdet, GradMatrix_t& dlogdet, HessMatrix_t& grad_grad_logdet, GGGMatrix_t& grad_grad_grad_logdet)

10 evaluateBasis (const ParticleSet &P, int first, int last,
                                ValueMatrix_t &basis_val,  GradMatrix_t  &basis_grad,
                                ValueMatrix_t &basis_lapl)

11 evaluateForDeriv (const ParticleSet &P, int first, int last,
                                   ValueMatrix_t &basis_val,  GradMatrix_t  &basis_grad,
                                   ValueMatrix_t &basis_lapl)

12 evaluateGradSource (const ParticleSet &P
                                     , int first, int last, const ParticleSet &source
                                     , int iat_src, GradMatrix_t &gradphi)

13 evaluateGradSource (const ParticleSet &P, int first, int last,
                                     const ParticleSet &source, int iat_src,
                                     GradMatrix_t &grad_phi,
                                     HessMatrix_t &grad_grad_phi,
                                     GradMatrix_t &grad_lapl_phi)


```

And a few others.  The documentation string on evaluateDerivatives seems clear - derivative wrt wavefunction parameters
```
14 evaluateDerivatives
  (ParticleSet& P, int iat, const opt_variables_type& active,
   ValueMatrix_t& d_phi, ValueMatrix_t& d_lapl_phi) {}

```

The evaluateValues method has a default implementation in terms of evaluate(ParticleSet &P, int iat, ValueVector_t& psi)
```
15 evaluateValues(VirtualParticleSet& VP, ValueMatrix_t& psiM)
```

**Comment by ye-luo** [comment]
We can probably remove 5, 6, 10, 11
7 used by the optimization of backflow
12,13 with source are related to forces.

**Comment by PDoakORNL** [comment]
I think this will ease some complication we don't need right now.

**Comment by prckent** [comment]
Very important to trim these functions and document those that remain. It is utterly opaque to non-experts as to which are truly needed...

As a general comment, I think we should consider how much advantage we gain from the various specializations. A better design would enable (and require) a default, but potentially slower, implementation of all functionality while leaving room for merited optimization. This will make it easier to add functionality in future as well as easing porting requirements. I don't know if this implies a big reduction or if what we have now is needed, although I suspect the former :-) This applies to SPOSet, WavefunctionComponent, and no doubt other parts of the design.

**Comment by PDoakORNL** [comment]
Since step 1, 2, 3 etc. to QMCDriver mk2 involve touch these API's this should get punted to 3.9+

**Comment by ye-luo** [comment]
All the evaluateXXX functions are documented in SPOSet.h
