### ISSUE TITLE
GPU + SoA build is not checked by CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#948]
Another hole in current CI.

**Comment by grahamlopez** [comment]
Well, IIRC this was intentional, as the GPU+SoA path wasn't far enough along that we wanted to test it.

**Comment by ye-luo** [comment]
Since the SoA compatiable CUDA classes have been added, we may want to build this combination. We will probably just replace an existing one with this combination instead of adding more.

**Comment by grahamlopez** [comment]
Yeah, seems reasonable. Probably just start to phase out the AoS?

**Comment by prckent** [comment]
Probably a few months.

**Comment by ye-luo** [comment]
Probably 3.6 release will have SoA by default and then 4.0 has AoS deleted.

**Comment by ye-luo** [comment]
Some failure on #1116 draws my attention to this open issue. Can we get this fixed ASAP?
The same setting as CPU. MP with SoA and FP with AoS.

**Comment by grahamlopez** [comment]
This can be enabled any time in the existing scripts. Is it ready to go now?

**Comment by ye-luo** [comment]
GPU binary built with SoA enabled is in production.

**Comment by jtkrogel** [comment]
We should keep the AoS checks in place and expand to include SoA.

**Comment by ye-luo** [comment]
MP with SoA and FP with AoS just like the CPU case.

**Comment by grahamlopez** [comment]
closed via #1117
