### ISSUE TITLE
DiffWaveFunctionComponent needs retirement

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#958]
DiffWaveFunctionComponent(previously DiffOrbitalBase) and its derived classes wrere introduced to handle multiple implementation of WF derivatives. It is no more needed and the evaluateDerivatives needs to be placed directly into the corresponding derived classes.

Jastrow/DiffTwoBodyJastrowOrbital.h holds both the AoS and the SoA implementations. and they should be disentangled.

```
DiffWaveFunctionComponent.h
DiffWaveFunctionComponent.cpp
Jastrow/DiffOneBodySpinJastrowOrbital.h
Jastrow/DiffTwoBodyJastrowOrbital.h
Jastrow/DiffOneBodyJastrowOrbital.h
```
should go away

**Comment by jtkrogel** [comment]
I heartily agree.

**Comment by eneuscamman** [comment]
To follow up on this, I noticed that there is likely a memory leak in the way the DiffOneBodyJastrowOrbital class handles the pointers inside its Funique vector.  This class's makeClone function uses new to create copies of the objects pointed to by the Funique pointers, but there does not appear to be anything that can delete these copies.  Am I missing something?
