### ISSUE TITLE
utils directory needs cleaning

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#962]
The utils directory has a large number of scripts and it is unclear which are currently in use.

Here is the current set of scripts:
```
bgrunjobhelper.sh     DMCEnergy.py         OptProgress.pl    PlotTwists.pl
check_input.py        energy.pl            PlotBsplConv.pl   setup-qmc-conf.pl
check_qmcsystem.py    Energy.py            PlotDMC.pl        setup-qmc.pl
check_scalars.py      Forces.py            PlotDMC.py        single_stat.perl
clean_and_link_h5.sh  FWforces.py          plot_fsatom.py    test_import.py
ConfigureScripts.pl   generate.py          PlotTstepConv.pl  TwistAvg.pl
cuspcorrection.py     getBestSupercell.pl  PlotTwistConv.pl
```

Please comment here if you use (or know of the use of) one of these scripts.  Unchampioned scripts will be flagged for removal.

Check the box next to any script below if it is in active use (bonus: add a parenthetical comment to describe its use):
- [X] bgrunjobhelper.sh (used by config/BGQ_Clang++11_ToolChain.cmake to set MPI NUMPROC)
- [ ] check_input.py
- [ ] check_qmcsystem.py
- [X] clean_and_link_h5.sh (used in CMake/run_qe.cmake as part of QE testing)
- [x] ConfigureScripts.pl (update paths to the external tools inside perl scripts)
- [ ] cuspcorrection.py
- [ ] DMCEnergy.py
- [x] energy.pl
- [ ] Energy.py
- [ ] Forces.py
- [ ] FWforces.py
- [ ] generate.py
- [ ] getBestSupercell.pl
- [x] OptProgress.pl
- [ ] PlotBsplConv.pl
- [x] PlotDMC.pl
- [ ] PlotDMC.py
- [ ] plot_fsatom.py
- [ ] PlotTstepConv.pl
- [ ] PlotTwistConv.pl
- [ ] PlotTwists.pl
- [x] setup-qmc-conf.pl
- [x] setup-qmc.pl
- [ ] single_stat.perl
- [x] test_import.py (used by test system, needs to be moved to tests/scripts)
- [x] TwistAvg.pl

**Comment by jtkrogel** [comment]
test_import.py and check_scalars.py are in active use by the testing system.

**Comment by jtkrogel** [comment]
@lshulen are you still using any of the perl/python data analysis scripts here?  

What is used by setup-qmc.pl?  So far I see energy.pl and TwistAvg.pl.

**Comment by prckent** [comment]
@jtkrogel Good questions. Several are used by the test system. Please can you convert your first post into a checklist?

- [ ] I_am_an_unknown_script.sh
- [x] I_am_important_and_used.py

**Comment by jtkrogel** [comment]
@prckent good suggestion.  See above.

**Comment by Hyeondeok-Shin** [comment]
I just additionally flagged two scripts, PlotDMC.pl and TwistAvg.pl. I know function in TwistAvg.pl can be replaced to qmca but I have been frequently using TwistAvg.pl when I need to quickly look at Twist-averaged energy without any concern about weights and Python version & libraries currently I'm using.

**Comment by jtkrogel** [comment]
Any other changes prior to cleanup?  Will do this in a day or two.
