### ISSUE TITLE
unit_test_hamiltonian is failing on BGQ

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#964]
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=unit_test_hamiltonian&date=2018-08-09
I think this is related to #956. Only affects the unit test not the production code.

**Comment by PDoakORNL** [comment]
Also on OSX SOA and AOS CPU builds.

**Comment by prckent** [comment]
Lets clean up the unit test situation these before merging #959. The unit tests should be totally reliable.

**Comment by markdewing** [comment]
I expected it would be a precision issue - some numbers slightly outside the compared value, but it's not.  The numbers produced are quite different from the expected values.

**Comment by prckent** [comment]
GCC Volta is also newly sick https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=unit_test_hamiltonian&date=2018-08-09

**Comment by prckent** [comment]
Revising previous comment - it seems that we have sporadic failures with this test on some platforms, so this is not new breakage. Presumably a bad pointer, memory use etc.

**Comment by markdewing** [comment]
Using clang 4 or 7 on linux, one of the failures reproduces
```
home/mdewing/prev/physics/codes/qmcpack/github/tmp_qmcpack/src/QMCHamiltonians/tests/test_force_ewald.cpp:126: FAILED:
  REQUIRE( force.forces_IonIon[0][0] == Approx(-0.0228366 ) )
with expansion:
  -0.0281f == Approx( -0.0228366 )
```
Though on BG/Q the value is -0.0f

**Comment by markdewing** [comment]
valgrind indicates that MaxKshell in EwaldHandler3D is not initialized.  This could be causing an issue. It's not clear how it is supposed to be set.

**Comment by markdewing** [comment]
The uninitialized MaxKshell is the problem.   When initialized, the tests pass on Linux and BG/Q.
To initialize it, I commented out the 'if(MaxKshell >= kshell.size())' line in fillYkgstrain, leaving MaxKshell initialized to kshell.size()-1.  This is how it is set in EwaldHander.cpp.
Other places, MaxKshell is set to the return value from SetupKVecs.
How should it be set?
