### ISSUE TITLE
USE_REAL_STRUCT_FACTOR feature complete?

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#972]
Is this macro fully implemented in all the places touching and using structure factor?

I also noticed QMC_SK_USE_RECURSIVE. Is this deprecated?

**Comment by prckent** [comment]
Does the code run with this option or are there gaps in the plumbing?

I also worry about the consistent (?) use of StorePerParticle in StructFact.h/.cpp. More generally, if USE_REAL_STRUCTURE_FACTOR is actually complete (?), shouldn't it be an automatic runtime setting and not a compile time setting? 

SK_USE_RECURSIVE has implementation in src/LongRange/StructFact.cpp. I don't know of any users and we certainly don't have any tests or docs.

**Comment by jtkrogel** [comment]
As far as I know, USE_REAL_STRUCT_FACTOR is an optimization (mostly aimed at Ewald sums?), but I don't know if it is feature complete.  A good proxy for feature completeness would be to run the long tests with this enabled and look for additional breakages.

**Comment by ye-luo** [comment]
USE_REAL_STRUCTURE_FACTOR seems set default in CMakeList.txt ADD_DEFINITIONS.
SK_USE_RECURSIVE is not default and I believe this is obsolete.

**Comment by prckent** [comment]
@ye-luo OK to remove SK_USE_RECURSIVE unless someone speaks up in a few days.
