### ISSUE TITLE
Correct atomic representation of the 1RDM?

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#977]
Several codes rely on atomic basis expansions of the 1RDM to describe local electronic structure (e.g. Lowdin and Mulliken charge analysis).  What method should we use to do this?  What is the "correct" atomic basis and how is it to be obtained?

**Comment by prckent** [comment]
I view this as an input choice. 1RDM might use e.g. the DFT orbitals used in the Slater determinant trial wavefunction, or they might use atomic wave functions. The former we have a simple route for, but do we have a route to get atomic wave functions? Have "we" (QMCPACK) ever used a route like this?

Why not accumulate the 1RDM  in the _complete_ set of (say) DFT orbitals and then use the projection of the DFT orbitals onto atomic wavefunctions to rotate the 1RDM into this new but less complete basis?

**Comment by jtkrogel** [comment]
Your second suggestion (postprocessing) is more of what I was thinking of.  This is certainly easier to accomplish and allows more flexibility.  What I am less sure of is how these atomic orbitals should be defined and which scheme to use as default.

Is there a "right way" to arrive at these orbitals, or at least one that is most self-consistent (i.e. what is the standard in quantum chemistry)?   One choice would be the e.g. LDA atomic orbitals corresponding to our pseudopotentials, and this might be a place to start, but it isn't very theoretically consistent.  Eventually is the "right" thing to e.g. totally squish each (neutral?) atom with CIPSI+DMC and get the atomic natural orbitals for further use as a post-processing basis for larger calculations?

**Comment by prckent** [comment]
There is no established "right way". Perhaps what Sorella or Wagner have been using so at least the QMC community has a common choice?
