### ISSUE TITLE
Tests with 4 MPI tasks and 4 OpenMP threads needed

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#988]
Most tests are written using 1 MPI and 16 threads.  This is convenient because the tests can be run on both CPU and GPU when walkers=16 is set in the input.  The shortcoming is that MPI is not tested and also the possible interaction between MPI and OpenMP.

To fill this gap in testing, more 4 MPI 4 thread tests should be added on the CPU side.  The problem here is that separate input files are required due to the lack of a way to consistently set the total number of walkers (see #8).  Currently any CPU test (16 MPI, 1 thread), (4 MPI, 4 threads), (1 MPI, 16 threads) can be handled correctly by setting walkers=1.  By contrast, a GPU test requires walkers=16, and so two separate input files must be generated to handle all cases until #8 is resolved.

**Comment by jtkrogel** [comment]
All CPU tests should be converted to 4 MPI with 4 threads since 16x1 and 1x16 configurations add no value (and also miss functionality) relative to the 4x4 case.  This requires either: 1) Creating CPU and GPU versions of all test input files or 2) Resolving #8 in at least a simple way, updating test files, and removing existing duplicated CPU/GPU input files.

The second option is preferred, but it depends on finally tackling #8.

**Comment by jtkrogel** [comment]
I agree that we can allow it, but it does not need to be default.  I don't think I have ever seen a case that fails for threads=16 with mpirun -np 1 (less complex) but succeeds for threads=4 with mpirun -np 4 (more complex).  Maybe I am just not being creative enough to see how it could happen either.

Running without any MPI built in is of course different, but I don't think we are testing any like this right now (am I missing this?).

**Comment by ye-luo** [comment]
When there is a bug. 4x4 may have the MPI and threading problem entangled.
I prefer the machine to do more testing work. If we have both 1x16 and 16x1, either failure will give more accurate info about where the issue is.

**Comment by prckent** [comment]
Lets solve #8, then this problem will also be solved. It will allow us to e.g. easily run tests where the number of walkers is not a factor of the number of mpi tasks. This might catch some edge cases.

**Comment by jtkrogel** [comment]
Good point.
