### ISSUE TITLE
Short tests aren't short

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#993]
Many of the short tests actually take quite a long time i.e. many minutes.  Perhaps they are short relative to the long test for there particular feature but if you want to do more than just run unit tests while for instance developing
```
ctest -R short
```
Is not viable.

**Comment by jtkrogel** [comment]
Short tests should not take more than 60 seconds each, with the possible exception of a few DMC tests.  Perhaps "short" was the wrong nomenclature, but these are the shortest acceptable/useful statistical tests we can make.

As Paul points out, the deterministic tests should be much faster, though for full correctness testing we sadly can't escape statistical integration tests.

**Comment by PDoakORNL** [comment]
How about these?
```shell
ctest -R short-diamondC_1x1x1_pp-vmc_sdj-1-16
ctest -R short-diamondC_1x1x1_pp-dmc_sdj-1-16
```

**Comment by prckent** [comment]
The vmc and dmc diamond C 1x1x1 tests give good coverage of QMC using periodic splines.

**Comment by markdewing** [comment]
It might be useful to:
 - pick a subset of short tests that covers major features (quick tests?)
 - document some subsets that cover various features (and/or add labels to the tests for this).

**Comment by jtkrogel** [comment]
@PDoakORNL the vmc example you cite runs in 8.5 seconds wall time on my 6 year old workstation.  What are you seeing for this case?

**Comment by PDoakORNL** [comment]
I was putting those forward as tests that would be good to run, they're pretty fast for me as well.
Would be nice if there were an easy way to make them 4 thread without editing.
