### ISSUE TITLE
Density estimator test need protection for NoMPI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#997]
https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=26979

**Comment by jtkrogel** [comment]
I don't see why this is causing problems for USE_MPI=0 while others are not.  Shouldn't we just override the number of mpi tasks and omp threads in this case?  I.e. override mpi=4, omp=4 with omp=16 and allow the test to be added for the no mpi case?

**Comment by prckent** [comment]
We should understand the problem and fix it. What is different about this case from other cases with no-mpi and the 4-4 combination?

**Comment by ye-luo** [comment]
the cmake script generating tests find that you request 4 MPI but it can't provide in NoMPI case and a stop is triggered. This is expected behaviour and I mentioned earlier that only have 4x4 will not work with NoMPI.

**Comment by prckent** [comment]
For the solids we are often checking 16x1, 1x16 and 4x4. RUN_QMC_APP defined in macros.cmake takes care to skip tests that don't make sense with no mpi / 1 mpi task.

**Comment by jtkrogel** [comment]
OK, gpu needs 1x16, cpu needs 4x4, and no mpi needs 1x16.  We really only want one mpi/omp configuration per test (it would be overkill to run 1x16, 4x4, and 16x1 for every test), so I suggest we bury these specifications into QMC_RUN_AND_CHECK and SIMPLE_RUN_AND_CHECK, i.e.:
```
if(NOT USE_MPI OR QMC_CUDA)
  set(NMPI 1)
  set(NOMP 16)
else()
  set(NMPI 4)
  set(NOMP 4)
endif()
```
This way we have just one test run per hardware/mpi configuration in a correct way.

**Comment by jtkrogel** [comment]
What gaps?  Why do we need to do 1x16 and 4x4 with MPI and no GPU?

**Comment by ye-luo** [comment]
Since we are not building no MPI case on every platform, only 4x4 doesn't give me if it is broken in the threading or MPI. Testing both 1x16 and 4x4 will help us to tell which one is broken just looking at the nightly results. Running more tests with robot is preferred to manual examination.

**Comment by jtkrogel** [comment]
I think what we are finding is that the CI is getting too heavy time wise.  Integration tests by nature only roughly tell you what is wrong, but there virtue is to cover a broad base of functionality.

Once a test fails (e.g. 4x4) it really is not much extra work to submit a 30s 1x16 job on your own if you suspect it is an MPI problem (which it probably is not, and will require many more investigative runs to find anyway).  I don't see why we should double all CI work when the check is so easy to make on our own.

**Comment by jtkrogel** [comment]
That is fair.  Why do you think this 4x4 is failing while others added in the past are fine?

If we know why and the 1x16+guarded 4x4 is the way to fix it, then I will make the update.
